NEST: nest::NestModule::GetStatus_iFunction Class Reference
nest::NestModule::GetStatus_iFunction Class Reference
SLI Interface functions of the NEST kernel.
#include <nestmodule.h>
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void nest::NestModule::GetStatus_iFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, nest::NestModule::get_network(), nest::Network::get_status(), getValue< long >(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), and TokenStack::push().
The documentation for this class was generated from the following files:
nestmodule.h
nestmodule.cpp