NEST: librandom::BinomialRandomDev Class Reference
librandom::BinomialRandomDev Class Reference
Random Deviate Generators.
Class BinomialRNG.
#include <binomial_randomdev.h>
Public Member Functions
BinomialRandomDev (RngPtr, double p_s=0.5, unsigned int n_s=1)
BinomialRandomDev (double p_s=0.5, unsigned int n_s=1)
void set_p_n (double, unsigned int)
set parameters for p and n p - success probability for single trial n - number of trials
void set_p (double)
set p
void set_n (unsigned int)
set n
long ldev (RngPtr) const
draw integer, threaded
bool has_ldev () const
true if RDG implements ldev function
double operator() (RngPtr) const
return as double, threaded
void set_status (const DictionaryDatum &)
set distribution parameters from SLI dict
void get_status (DictionaryDatum &) const
get distribution parameters from SLI dict
Public Member Functions inherited from librandom::RandomDev
RandomDev (RngPtr rng=RngPtr(0))
Construct with (single-threaded) or without (multithreaded) RNG.
virtual ~RandomDev ()
ensure proper clean-up
virtual double operator() (void)
Operator delivering doubles.
virtual long ldev (void)
integer valued functions for discrete distributions
void set_rng (RngPtr rng)
set RNG
Private Member Functions
void init_ ()
check and initialize internal parameters
void PrecomputeTable (size_t)
compute the internal lookup table
Private Attributes
PoissonRandomDev poisson_dev_
source of Poisson random numbers
ExpRandomDev exp_dev_
source of exponential random numbers
double p_
probability p of binomial distribution
double phi_
long m_
unsigned int n_
parameter n in binomial distribution
std::vector< double_t > f_
precomputed table of f
unsigned int n_tablemax_
current maximal n with precomputed values
Additional Inherited Members
Protected Attributes inherited from librandom::RandomDev
RngPtr rng_
store underlying RNG
Detailed Description
Class BinomialRNG.
Generates an RNG which returns Binomial(k;p;n) distributed random numbers out of an RNG which returns binomially distributed random numbers:
p(k) = (n! / k!(n-k)!) p^k (1-p)^(n-k) , 0<=k<=n, n<0
Arguments:
pointer to an RNG
parameter p (optional, default = 0.5)
parameter n (optional, default = 1)
See also
Fishman, Sampling From the Binomial Distribution on a Computer, Journal of the American Statistical Association, Vol. 74, No. 366 (Jun., 1979), pp. 418-423
Constructor & Destructor Documentation
librandom::BinomialRandomDev::BinomialRandomDev (RngPtr r_s, double p_s = 0.5, unsigned int n_s = 1)
References init_(), and PrecomputeTable().
librandom::BinomialRandomDev::BinomialRandomDev (double p_s = 0.5, unsigned int n_s = 1)
References init_(), and PrecomputeTable().
Member Function Documentation
void librandom::BinomialRandomDev::get_status (DictionaryDatum & d) const virtual
get distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::d.
bool librandom::BinomialRandomDev::has_ldev () const inline virtual
true if RDG implements ldev function
Reimplemented from librandom::RandomDev.
void librandom::BinomialRandomDev::init_ () private
check and initialize internal parameters
References assert(), nest::names::mu, and nest::names::theta.
Referenced by BinomialRandomDev().
long librandom::BinomialRandomDev::ldev (RngPtr rng) const virtual
draw integer, threaded
Reimplemented from librandom::RandomDev.
References assert(), and lockPTR< D >::valid().
Referenced by nest::FixedTotalNumberBuilder::connect_().
double librandom::BinomialRandomDev::operator() (RngPtr rthrd) const inline virtual
return as double, threaded
Implements librandom::RandomDev.
References librandom::RandomDev::ldev().
void librandom::BinomialRandomDev::PrecomputeTable (size_t nmax) private
compute the internal lookup table
Referenced by BinomialRandomDev().
void librandom::BinomialRandomDev::set_n (unsigned int n_s)
set n
Referenced by nest::FixedTotalNumberBuilder::connect_().
void librandom::BinomialRandomDev::set_p (double p_s)
set p
Referenced by nest::FixedTotalNumberBuilder::connect_().
void librandom::BinomialRandomDev::set_p_n (double p_s, unsigned int n_s)
set parameters for p and n p - success probability for single trial n - number of trials
void librandom::BinomialRandomDev::set_status (const DictionaryDatum & d) virtual
set distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::d, and nest::names::max.
Member Data Documentation
ExpRandomDev librandom::BinomialRandomDev::exp_dev_ private
source of exponential random numbers
std::vector<double_t> librandom::BinomialRandomDev::f_ private
precomputed table of f
long librandom::BinomialRandomDev::m_ private
unsigned int librandom::BinomialRandomDev::n_ private
parameter n in binomial distribution
unsigned int librandom::BinomialRandomDev::n_tablemax_ private
current maximal n with precomputed values
double librandom::BinomialRandomDev::p_ private
probability p of binomial distribution
double librandom::BinomialRandomDev::phi_ private
PoissonRandomDev librandom::BinomialRandomDev::poisson_dev_ private
source of Poisson random numbers
The documentation for this class was generated from the following files:
binomial_randomdev.h
binomial_randomdev.cpp