NEST: IloopFunction Class Reference
IloopFunction Class Reference
#include <slibuiltins.h>
Public Member Functions
IloopFunction ()
void execute (SLIInterpreter *) const
void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
Constructor & Destructor Documentation
IloopFunction::IloopFunction () inline
Member Function Documentation
void IloopFunction::backtrace (SLIInterpreter * , int) const virtual
Show stack backtrace information on error.
This function tries to extract and display useful information from the execution stack if an error occurs. This function should be implemented for all functions which store administrative information on the execution stack. Examples are: loops and procedure iterations. backtrace() is only called, if the interpreter flag show_backtrace is set.
Reimplemented from SLIFunction.
References assert(), Token::datum(), SLIInterpreter::EStack, GenericDatum< D, slt >::get(), AggregateDatum< C, slt >::list(), and TokenStack::pick().
void IloopFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References Token::datum(), SLIInterpreter::EStack, SLIInterpreter::OStack, TokenStack::pick(), and TokenStack::push().
The documentation for this class was generated from the following files:
slibuiltins.h
slibuiltins.cc