NEST: nest::STDPFACETSHWConnectionHom< targetidentifierT > Class Template Reference
nest::STDPFACETSHWConnectionHom< targetidentifierT > Class Template Reference
Class representing an STDP connection with homogeneous parameters, i.e.
#include <stdp_connection_facetshw_hom.h>
Classes
class ConnTestDummyNode
Public Types
typedef
STDPFACETSHWHomCommonProperties
< targetidentifierT > CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
STDPFACETSHWConnectionHom ()
Default Constructor.
STDPFACETSHWConnectionHom (const STDPFACETSHWConnectionHom &)
Copy constructor from a property object.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t t_lastspike, const STDPFACETSHWHomCommonProperties< targetidentifierT > &)
Send an event to the receiver of this connection.
void check_connection (Node &s, Node &t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &)
void set_weight (double_t w)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Member Functions
bool eval_function_ (double_t a_causal, double_t a_acausal, double_t a_thresh_th, double_t a_thresh_tl, std::vector< long_t > configbit)
uint_t weight_to_entry_ (double_t weight, double_t weight_per_lut_entry)
double_t entry_to_weight_ (uint_t discrete_weight, double_t weight_per_lut_entry)
uint_t lookup_ (uint_t discrete_weight_, std::vector< long_t > table)
Private Attributes
double_t weight_
double_t a_causal_
double_t a_acausal_
double_t a_thresh_th_
double_t a_thresh_tl_
bool init_flag_
long_t synapse_id_
double_t next_readout_time_
uint_t discrete_weight_
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Detailed Description
template<typename targetidentifierT>
class nest::STDPFACETSHWConnectionHom< targetidentifierT >
Class representing an STDP connection with homogeneous parameters, i.e.
parameters are the same for all synapses.
Member Typedef Documentation
template<typename targetidentifierT > typedef STDPFACETSHWHomCommonProperties<targetidentifierT> nest::STDPFACETSHWConnectionHom< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::STDPFACETSHWConnectionHom< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::STDPFACETSHWConnectionHom< targetidentifierT >::STDPFACETSHWConnectionHom ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::STDPFACETSHWConnectionHom< targetidentifierT >::STDPFACETSHWConnectionHom (const STDPFACETSHWConnectionHom< targetidentifierT > & rhs)
Copy constructor from a property object.
Needs to be defined properly in order for GenericConnector to work.
Member Function Documentation
template<typename targetidentifierT > void nest::STDPFACETSHWConnectionHom< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_(), nest::Connection< targetidentifierT >::get_delay(), and nest::Node::register_stdp_connection().
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::entry_to_weight_ (uint_t discrete_weight, double_t weight_per_lut_entry) inline private
template<typename targetidentifierT > bool nest::STDPFACETSHWConnectionHom< targetidentifierT >::eval_function_ (double_t a_causal, double_t a_acausal, double_t a_thresh_th, double_t a_thresh_tl, std::vector< long_t > configbit) inline private
template<typename targetidentifierT > void nest::STDPFACETSHWConnectionHom< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, and nest::names::weight.
template<typename targetidentifierT > uint_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::lookup_ (uint_t discrete_weight_, std::vector< long_t > table) inline private
template<typename targetidentifierT > void nest::STDPFACETSHWConnectionHom< targetidentifierT >::send (Event & e, thread t, double_t t_lastspike, const STDPFACETSHWHomCommonProperties< targetidentifierT > & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
t_lastspike Point in time of last spike sent.
e The event to send
p The port under which this connection is stored in the Connector.
t_lastspike Time point of last spike emitted
References nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::calc_readout_cycle_duration_(), nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::configbit_0_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::configbit_1_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::driver_readout_time_, numerics::e, nest::Time::get_ms(), nest::Event::get_stamp(), nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::lookuptable_0_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::lookuptable_1_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::lookuptable_2_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::no_synapses_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::readout_cycle_duration_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::reset_pattern_, nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), nest::Event::set_weight(), nest::names::start, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::synapses_per_driver_, nest::names::t_spike, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::tau_minus_, nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::tau_plus_, and nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::weight_per_lut_entry_.
template<typename targetidentifierT > void nest::STDPFACETSHWConnectionHom< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties of this connection from the values given in dictionary.
References nest::names::d, and nest::names::weight.
template<typename targetidentifierT > void nest::STDPFACETSHWConnectionHom< targetidentifierT >::set_weight (double_t w) inline
References nest::names::w, and nest::STDPFACETSHWConnectionHom< targetidentifierT >::weight_.
template<typename targetidentifierT > uint_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::weight_to_entry_ (double_t weight, double_t weight_per_lut_entry) inline private
Member Data Documentation
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::a_acausal_ private
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::a_causal_ private
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::a_thresh_th_ private
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::a_thresh_tl_ private
template<typename targetidentifierT > uint_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::discrete_weight_ private
template<typename targetidentifierT > bool nest::STDPFACETSHWConnectionHom< targetidentifierT >::init_flag_ private
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::next_readout_time_ private
template<typename targetidentifierT > long_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::synapse_id_ private
template<typename targetidentifierT > double_t nest::STDPFACETSHWConnectionHom< targetidentifierT >::weight_ private
Referenced by nest::STDPFACETSHWConnectionHom< targetidentifierT >::set_weight().
The documentation for this class was generated from the following files:
stdp_connection_facetshw_hom.h
stdp_connection_facetshw_hom_impl.h