NEST: nest::DataLoggingRequest Class Reference
nest::DataLoggingRequest Class Reference
Event types for analog logging devices.
Request data to be logged/logged data to be sent.
#include <event.h>
Public Member Functions
DataLoggingRequest ()
Create empty request for use during simulation.
DataLoggingRequest (const Time &, const std::vector< Name > &)
Create event for given time stamp and vector of recordables.
DataLoggingRequest * clone () const
Virtual copy constructor.
void operator() ()
Deliver the event to receiver.
const Time & get_recording_interval () const
Access to stored time interval.
const std::vector< Name > & record_from () const
Access to vector of recordables.
Public Member Functions inherited from nest::Event
Event ()
virtual ~Event ()
void set_receiver (Node &)
Change pointer to receiving Node.
Node & get_receiver () const
Return reference to receiving Node.
Node & get_sender () const
Return reference to sending Node.
void set_sender (Node &)
Change pointer to sending Node.
index get_sender_gid () const
Return GID of sending Node.
void set_sender_gid (index)
Change GID of sending Node.
Time const & get_stamp () const
Return time stamp of the event.
void set_delay (delay)
Set the transmission delay of the event.
delay get_delay () const
Return transmission delay of the event.
delay get_max_delay () const
long_t get_rel_delivery_steps (const Time &t) const
Relative spike delivery time in steps.
port get_port () const
Return the sender port number of the event.
rport get_rport () const
Return the receiver port number of the event.
void set_port (port p)
Set the port number.
void set_rport (rport p)
Set the receiver port number (r-port).
double_t get_offset () const
Return the creation time offset of the Event.
void set_offset (double_t t)
Set the creation time of the Event.
weight get_weight () const
Return the weight.
void set_weight (weight t)
Set weight of the event.
bool is_valid () const
Check integrity of the event.
void set_stamp (Time const &)
Set the time stamp of the event.
Private Attributes
Time recording_interval_
Interval between two recordings, first is step 1.
std::vector< Name > const *const record_from_
Names of properties to record from.
Additional Inherited Members
Protected Attributes inherited from nest::Event
index sender_gid_
GID of sender or -1.
Node * sender_
Pointer to sender or NULL.
Node * receiver_
Pointer to receiver or NULL.
port p_
Sender port number.
rport rp_
Receiver port number (r-port).
delay d_
Transmission delay.
Time stamp_
Time stamp.
double offset_
Offset for precise spike times.
weight w_
Weight of the connection.
Detailed Description
Request data to be logged/logged data to be sent.
See also
DataLoggingReply
Constructor & Destructor Documentation
nest::DataLoggingRequest::DataLoggingRequest () inline
Create empty request for use during simulation.
Referenced by clone().
nest::DataLoggingRequest::DataLoggingRequest (const Time & rec_int, const std::vector< Name > & recs) inline
Create event for given time stamp and vector of recordables.
Member Function Documentation
DataLoggingRequest * nest::DataLoggingRequest::clone () const inline virtual
Virtual copy constructor.
Implements nest::Event.
References DataLoggingRequest().
const Time & nest::DataLoggingRequest::get_recording_interval () const inline
Access to stored time interval.
References assert(), nest::Time::is_finite(), and recording_interval_.
void nest::DataLoggingRequest::operator() () virtual
Deliver the event to receiver.
This operator calls the handler for the specific event type at the receiver.
Implements nest::Event.
References nest::Node::handle(), and nest::Event::receiver_.
const std::vector< Name > & nest::DataLoggingRequest::record_from () const inline
Access to vector of recordables.
References assert(), and record_from_.
Member Data Documentation
std::vector<Name> const* const nest::DataLoggingRequest::record_from_ private
Names of properties to record from.
Note
This pointer shall be NULL unless the event is sent by a connection routine.
Referenced by record_from().
Time nest::DataLoggingRequest::recording_interval_ private
Interval between two recordings, first is step 1.
Referenced by get_recording_interval().
The documentation for this class was generated from the following files:
event.h
event.cpp