NEST: AggregateDatum< C, slt > Class Template Reference
AggregateDatum< C, slt > Class Template Reference
#include <aggregatedatum.h>
Public Member Functions
AggregateDatum ()
AggregateDatum (const AggregateDatum< C, slt > &d)
AggregateDatum (const C &c)
virtual ~AggregateDatum ()
bool equals (const Datum *dat) const
virtual void print (std::ostream &out) const
virtual void pprint (std::ostream &out) const
virtual void list (std::ostream &out, std::string prefix, int l) const
virtual void input_form (std::ostream &out) const
virtual void info (std::ostream &out) const
template<>
void pprint (std::ostream &out) const
template<>
void list (std::ostream &out, std::string prefix, int line) const
template<>
void print (std::ostream &out) const
template<>
void pprint (std::ostream &out) const
template<>
void list (std::ostream &out, std::string prefix, int line) const
template<>
void print (std::ostream &out) const
template<>
void print (std::ostream &) const
template<>
void list (std::ostream &, std::string, int) const
template<>
void pprint (std::ostream &) const
template<>
void print (std::ostream &) const
template<>
void pprint (std::ostream &) const
template<>
void list (std::ostream &, std::string, int) const
template<>
void pprint (std::ostream &out) const
template<>
void pprint (std::ostream &out) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Protected Member Functions
template<>
sli::pool memory (sizeof(ProcedureDatum), 10240, 1)
template<>
sli::pool memory (sizeof(AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >), 10240, 1)
template<>
sli::pool memory
template<>
sli::pool memory
template<>
sli::pool memory (sizeof(AggregateDatum< std::string,&SLIInterpreter::Stringtype >), 100, 1)
template<>
sli::pool memory
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Static Protected Attributes
static sli::pool memory
Private Member Functions
virtual Datum * clone (void) const
Virtual copy constructor.
Additional Inherited Members
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Constructor & Destructor Documentation
template<class C, SLIType * slt> AggregateDatum< C, slt >::AggregateDatum () inline
template<class C, SLIType * slt> AggregateDatum< C, slt >::AggregateDatum (const AggregateDatum< C, slt > & d) inline
template<class C, SLIType * slt> AggregateDatum< C, slt >::AggregateDatum (const C & c) inline
template<class C, SLIType * slt> virtual AggregateDatum< C, slt >::~AggregateDatum () inline virtual
Member Function Documentation
template<class C, SLIType * slt> virtual Datum* AggregateDatum< C, slt >::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Implements Datum.
Reimplemented in LiteralDatum, NameDatum, SymbolDatum, and ParserDatum.
template<class C, SLIType * slt> bool AggregateDatum< C, slt >::equals (const Datum * dat) const inline virtual
Reimplemented from Datum.
template<class C, SLIType * slt> virtual void AggregateDatum< C, slt >::info (std::ostream & out) const inline virtual
Reimplemented from Datum.
template<class C, SLIType * slt> virtual void AggregateDatum< C, slt >::input_form (std::ostream & out) const inline virtual
Reimplemented from Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::list (std::ostream & , std::string , int) const virtual
Reimplemented from Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::list (std::ostream & , std::string , int) const virtual
Reimplemented from Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::list (std::ostream & out, std::string prefix, int line) const virtual
Reimplemented from Datum.
template<class C , SLIType * slt> void AggregateDatum< C, slt >::list (std::ostream & out, std::string prefix, int l) const virtual
Reimplemented from Datum.
Referenced by SLIArrayModule::IMapFunction::backtrace(), IiterateFunction::backtrace(), SLIArrayModule::IMap_ivFunction::backtrace(), SLIArrayModule::IMap_dvFunction::backtrace(), IloopFunction::backtrace(), IrepeatFunction::backtrace(), SLIArrayModule::IMapThreadFunction::backtrace(), IforFunction::backtrace(), SLIArrayModule::IMapIndexedFunction::backtrace(), SLIArrayModule::IMapFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), and SLIArrayModule::IMapIndexedFunction::execute().
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::list (std::ostream & out, std::string prefix, int line) const virtual
Reimplemented from Datum.
template<> sli::pool AggregateDatum< std::string,&SLIInterpreter::Stringtype >::memory (sizeof(AggregateDatum< std::string,&SLIInterpreter::Stringtype >) , 100 , 1) protected
template<> sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::memory (sizeof(ProcedureDatum) , 10240 , 1) protected
template<> sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::memory (sizeof(AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >) , 10240 , 1) protected
template<> sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::memory () protected
Referenced by AggregateDatum< Name,&SLIInterpreter::Nametype >::operator delete(), and AggregateDatum< Name,&SLIInterpreter::Nametype >::operator new().
template<> sli::pool AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::memory () protected
template<> sli::pool AggregateDatum< std::string,&SLIInterpreter::Stringtype >::memory () protected
template<class C, SLIType * slt> static void AggregateDatum< C, slt >::operator delete (void * p, size_t size) inline static
template<class C, SLIType * slt> static void* AggregateDatum< C, slt >::operator new (size_t size) inline static
template<> void AggregateDatum< std::string,&SLIInterpreter::Stringtype >::pprint (std::ostream & out) const virtual
Implements Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::pprint (std::ostream &) const virtual
Implements Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::pprint (std::ostream &) const virtual
Implements Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::pprint (std::ostream & out) const virtual
Implements Datum.
template<> void AggregateDatum< std::string,&SLIInterpreter::Stringtype >::pprint (std::ostream & out) const virtual
Implements Datum.
template<class C , SLIType * slt> void AggregateDatum< C, slt >::pprint (std::ostream & out) const virtual
Implements Datum.
Reimplemented in LiteralDatum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::pprint (std::ostream & out) const virtual
Implements Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::print (std::ostream &) const virtual
Implements Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::print (std::ostream &) const virtual
Implements Datum.
template<class C , SLIType * slt> void AggregateDatum< C, slt >::print (std::ostream & out) const virtual
Implements Datum.
Referenced by AggregateDatum< Name,&SLIInterpreter::Nametype >::info(), AggregateDatum< Name,&SLIInterpreter::Nametype >::input_form(), and SLIInterpreter::stack_backtrace().
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Proceduretype >::print (std::ostream & out) const virtual
Implements Datum.
template<> void AggregateDatum< TokenArray,&SLIInterpreter::Litproceduretype >::print (std::ostream & out) const virtual
Implements Datum.
Member Data Documentation
template<class C, SLIType * slt> sli::pool GIDCollectionDatum::memory static protected
The documentation for this class was generated from the following files:
aggregatedatum.h
nest_datums.cpp
nest_datums.h