NEST: nest::FixedTotalNumberBuilder Class Reference
nest::FixedTotalNumberBuilder Class Reference
#include <conn_builder.h>
Public Member Functions
FixedTotalNumberBuilder (Network &, const GIDCollection &, const GIDCollection &, const DictionaryDatum &, const DictionaryDatum &)
Public Member Functions inherited from nest::ConnBuilder
virtual void connect ()
Connect sources to targets according to specifications in dictionary.
ConnBuilder (Network &, const GIDCollection &, const GIDCollection &, const DictionaryDatum &, const DictionaryDatum &)
parameters: sources, targets, specifications
virtual ~ConnBuilder ()
Protected Member Functions
void connect_ ()
Implements the actual connection algorithm.
Protected Member Functions inherited from nest::ConnBuilder
void single_connect_ (index, Node &, thread, librandom::RngPtr &)
Create connection between given nodes, fill parameter values.
Private Attributes
long N_
Additional Inherited Members
Protected Attributes inherited from nest::ConnBuilder
Network & net_
const GIDCollection & sources_
const GIDCollection & targets_
bool autapses_
bool multapses_
std::vector< lockPTR
< WrappedThreadException > > exceptions_raised_
buffer for exceptions raised in threads
Constructor & Destructor Documentation
nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder (Network & net, const GIDCollection & sources, const GIDCollection & targets, const DictionaryDatum & conn_spec, const DictionaryDatum & syn_spec)
References nest::ConnBuilder::multapses_, N_, nest::GIDCollection::size(), nest::ConnBuilder::sources_, and nest::ConnBuilder::targets_.
Member Function Documentation
void nest::FixedTotalNumberBuilder::connect_ () protected virtual
Implements the actual connection algorithm.
Implements nest::ConnBuilder.
References nest::Communicator::get_num_virtual_processes(), nest::Node::get_thread(), librandom::BinomialRandomDev::ldev(), librandom::BinomialRandomDev::set_n(), librandom::BinomialRandomDev::set_p(), nest::names::target, and nest::names::target_thread.
Member Data Documentation
long nest::FixedTotalNumberBuilder::N_ private
Referenced by FixedTotalNumberBuilder().
The documentation for this class was generated from the following files:
conn_builder.h
conn_builder.cpp