NEST: nest::TimeModifier Class Reference
nest::TimeModifier Class Reference
#include <nest_timemodifier.h>
Static Private Member Functions
static void set_time_representation (double_t tics_per_ms, double_t ms_per_step)
Set the rime represeantation (TICS_PER_MS_, MS_PER_TICS_ and TICS_PER_STEP)
static void reset_to_defaults ()
Reset TICS_PER_MS_, MS_PER_TICS_ and TICS_PER_STEP_ to compiled in default values.
Friends
void Scheduler::set_status (DictionaryDatum const &)
void Scheduler::reset ()
Member Function Documentation
void nest::TimeModifier::reset_to_defaults () static private
Reset TICS_PER_MS_, MS_PER_TICS_ and TICS_PER_STEP_ to compiled in default values.
References nest::Time::reset_to_defaults().
Referenced by nest::Scheduler::reset().
void nest::TimeModifier::set_time_representation (nest::double_t tics_per_ms, double_t ms_per_step) static private
Set the rime represeantation (TICS_PER_MS_, MS_PER_TICS_ and TICS_PER_STEP)
Parameters
tics_per_ms number of TICS per ms
ms_per_step amount of ms per simulation step
References nest::Time::set_resolution().
Referenced by nest::Scheduler::prepare_nodes().
Friends And Related Function Documentation
void Scheduler::reset () friend
void Scheduler::set_status (DictionaryDatum const &) friend
The documentation for this class was generated from the following files:
nest_timemodifier.h
nest_timemodifier.cpp