NEST: sli::pool Class Reference
sli::pool Class Reference
Memory management | Pool allocator
pool is a specialized allocator class for many identical small objects.
#include <allocator.h>
Classes
class chunk
struct link
Public Member Functions
pool ()
Create pool for objects of size n.
pool (const pool &)
pool & operator= (const pool &)
pool (size_t n, size_t initial=100, size_t growth=1)
void init (size_t n, size_t initial=100, size_t growth=1)
~pool ()
deallocate ALL memory
void reserve_additional (size_t n)
Increase the pools capacity (free slots) by n.
size_t available (void) const
void * alloc (void)
allocate one element
void free (void *p)
put element back into the pool
size_t size_of (void) const
size_t get_el_size () const
size_t get_instantiations () const
size_t get_total () const
Private Member Functions
void grow (size_t)
make pool larger by n elements
void grow ()
make pool larger
Private Attributes
size_t initial_block_size
size_t growth_factor
size_t block_size
number of elements per chunk
size_t el_size
sizeof an element
size_t instantiations
number of instantiated elements
size_t total
total number of allocated elements
size_t capacity
number of free elements
chunk * chunks
linked list of memory chunks
link * head
head of free list
bool initialized_
True if the pool is initialized.
Detailed Description
pool is a specialized allocator class for many identical small objects.
It targets a performance close to the optimal performance which is achieved by allocating all needed objects at once.
Constructor & Destructor Documentation
sli::pool::pool ()
Create pool for objects of size n.
Initial is the initial allocation block size, i.e. the number of objects per block. growth is the factor by which the allocations block increases after each growth.
sli::pool::pool (const pool & p)
sli::pool::pool (size_t n, size_t initial = 100, size_t growth = 1)
sli::pool::~pool ()
deallocate ALL memory
References nest::names::n, sli::pool::chunk::next, and nest::names::p.
Member Function Documentation
void * sli::pool::alloc (void) inline
allocate one element
References block_size, grow(), growth_factor, head, instantiations, sli::pool::link::next, and nest::names::p.
Referenced by NumericDatum< D, slt >::operator new(), AggregateDatum< Name,&SLIInterpreter::Nametype >::operator new(), TrieDatum::operator new(), FunctionDatum::operator new(), and IteratorDatum::operator new().
size_t sli::pool::available (void) const inline
References instantiations, and total.
void sli::pool::free (void * p) inline
put element back into the pool
References head, instantiations, sli::pool::link::next, and nest::names::p.
Referenced by NumericDatum< D, slt >::operator delete(), AggregateDatum< Name,&SLIInterpreter::Nametype >::operator delete(), TrieDatum::operator delete(), FunctionDatum::operator delete(), and IteratorDatum::operator delete().
size_t sli::pool::get_el_size () const inline
References el_size.
size_t sli::pool::get_instantiations () const inline
References instantiations.
size_t sli::pool::get_total () const inline
References total.
void sli::pool::grow (size_t nelements) private
make pool larger by n elements
References sli::pool::chunk::mem, nest::names::n, sli::pool::chunk::next, nest::names::p, and nest::names::start.
void sli::pool::grow (void) private
make pool larger
Referenced by alloc().
void sli::pool::init (size_t n, size_t initial = 100, size_t growth = 1)
References assert().
Referenced by nest::GenericModel< ElementT >::init_memory_().
sli::pool & sli::pool::operator= (const pool & p)
References el_size, growth_factor, and initial_block_size.
void sli::pool::reserve_additional (size_t n)
Increase the pools capacity (free slots) by n.
reserve_additional() ensures that the pool has at least n empty slots, i.e., that the pool can store at least n additional elements before more memory needs to be allocated from the operating system.
size_t sli::pool::size_of (void) const inline
References el_size.
Referenced by NumericDatum< D, slt >::operator delete(), AggregateDatum< Name,&SLIInterpreter::Nametype >::operator delete(), TrieDatum::operator delete(), IteratorDatum::operator delete(), NumericDatum< D, slt >::operator new(), AggregateDatum< Name,&SLIInterpreter::Nametype >::operator new(), TrieDatum::operator new(), and IteratorDatum::operator new().
Member Data Documentation
size_t sli::pool::block_size private
number of elements per chunk
Referenced by alloc().
size_t sli::pool::capacity private
number of free elements
chunk* sli::pool::chunks private
linked list of memory chunks
size_t sli::pool::el_size private
sizeof an element
Referenced by get_el_size(), operator=(), and size_of().
size_t sli::pool::growth_factor private
Referenced by alloc(), and operator=().
link* sli::pool::head private
head of free list
Referenced by alloc(), and free().
size_t sli::pool::initial_block_size private
Referenced by operator=().
bool sli::pool::initialized_ private
True if the pool is initialized.
size_t sli::pool::instantiations private
number of instantiated elements
Referenced by alloc(), available(), free(), and get_instantiations().
size_t sli::pool::total private
total number of allocated elements
Referenced by available(), and get_total().
The documentation for this class was generated from the following files:
allocator.h
allocator.cpp