NEST: SLIArrayModule::ArraycreateFunction Class Reference
SLIArrayModule::ArraycreateFunction Class Reference
SLI array functions
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void SLIArrayModule::ArraycreateFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References ad, nest::names::depth, SLIInterpreter::EStack, TokenStack::load(), SLIInterpreter::M_ERROR, SLIInterpreter::mark_name, SLIInterpreter::message(), nest::names::n, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenArray::push_back_move(), TokenStack::push_move(), SLIInterpreter::raiseerror(), and TokenArray::reserve().
The documentation for this class was generated from the following files:
sliarray.h
sliarray.cc