NEST: nest::DifferenceParameter Class Reference
nest::DifferenceParameter Class Reference
Parameter class representing the difference of two parameters.
#include <parameter.h>
Public Member Functions
DifferenceParameter (const Parameter &m1, const Parameter &m2)
Construct the difference of the two given parameters.
DifferenceParameter (const DifferenceParameter &p)
Copy constructor.
~DifferenceParameter ()
double_t raw_value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t raw_value (const Position< 3 > &p, librandom::RngPtr &rng) const
Raw value disregarding cutoff.
Parameter * clone () const
Clone method.
Public Member Functions inherited from nest::Parameter
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Protected Attributes
Parameter * parameter1_
Parameter * parameter2_
Detailed Description
Parameter class representing the difference of two parameters.
Constructor & Destructor Documentation
nest::DifferenceParameter::DifferenceParameter (const Parameter & m1, const Parameter & m2) inline
Construct the difference of the two given parameters.
Copies are made of the supplied Parameter objects.
Referenced by clone().
nest::DifferenceParameter::DifferenceParameter (const DifferenceParameter & p) inline
Copy constructor.
nest::DifferenceParameter::~DifferenceParameter () inline
References parameter1_, and parameter2_.
Member Function Documentation
Parameter* nest::DifferenceParameter::clone () const inline virtual
Clone method.
Returns
dynamically allocated copy of parameter object
Implements nest::Parameter.
References DifferenceParameter().
double_t nest::DifferenceParameter::raw_value (const Position< 2 > & p, librandom::RngPtr & rng) const inline virtual
Returns
the value of the difference.
Reimplemented from nest::Parameter.
References parameter1_, parameter2_, and nest::Parameter::value().
double_t nest::DifferenceParameter::raw_value (const Position< 3 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References parameter1_, parameter2_, and nest::Parameter::value().
Member Data Documentation
Parameter* nest::DifferenceParameter::parameter1_ protected
Referenced by raw_value(), and ~DifferenceParameter().
Parameter * nest::DifferenceParameter::parameter2_ protected
Referenced by raw_value(), and ~DifferenceParameter().
The documentation for this class was generated from the following file:
parameter.h