NEST: IparseFunction Class Reference
IparseFunction Class Reference
#include <slicontrol.h>
Public Member Functions
IparseFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
IparseFunction::IparseFunction () inline
Member Function Documentation
void IparseFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References assert(), Token::datum(), Scanner::EndSymbol, SLIInterpreter::EStack, SLIInterpreter::parse, TokenStack::pick(), TokenStack::pop(), TokenStack::push_move(), SLIInterpreter::raiseerror(), Parser::readToken(), Parser::scan(), TokenStack::swap(), and lockPTR< D >::valid().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc