NEST: sparsetable< T, GROUP_SIZE, Alloc > Class Template Reference
sparsetable< T, GROUP_SIZE, Alloc > Class Template Reference
#include <sparsetable.h>
Classes
class Settings
Public Types
typedef T value_type
typedef Alloc allocator_type
typedef value_alloc_type::size_type size_type
typedef
value_alloc_type::difference_type difference_type
typedef value_alloc_type::reference reference
typedef
value_alloc_type::const_reference const_reference
typedef value_alloc_type::pointer pointer
typedef
value_alloc_type::const_pointer const_pointer
typedef table_iterator
< sparsetable< T, GROUP_SIZE,
Alloc > > iterator
typedef const_table_iterator
< sparsetable< T, GROUP_SIZE,
Alloc > > const_iterator
typedef table_element_adaptor
< sparsetable< T, GROUP_SIZE,
Alloc > > element_adaptor
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
typedef std::reverse_iterator
< iterator > reverse_iterator
typedef two_d_iterator
< std::vector< sparsegroup
< value_type, GROUP_SIZE,
value_alloc_type >
, vector_alloc > > nonempty_iterator
typedef const_two_d_iterator
< std::vector< sparsegroup
< value_type, GROUP_SIZE,
value_alloc_type >
, vector_alloc > > const_nonempty_iterator
typedef std::reverse_iterator
< nonempty_iterator > reverse_nonempty_iterator
typedef std::reverse_iterator
< const_nonempty_iterator > const_reverse_nonempty_iterator
typedef
destructive_two_d_iterator
< std::vector< sparsegroup
< value_type, GROUP_SIZE,
value_alloc_type >
, vector_alloc > > destructive_iterator
typedef sparsegroup
< value_type, GROUP_SIZE,
allocator_type > group_type
typedef std::vector
< group_type, vector_alloc > group_vector_type
typedef
group_vector_type::reference GroupsReference
typedef
group_vector_type::const_reference GroupsConstReference
typedef group_vector_type::iterator GroupsIterator
typedef
group_vector_type::const_iterator GroupsConstIterator
typedef
sparsehash_internal::pod_serializer
< value_type > NopointerSerializer
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
nonempty_iterator nonempty_begin ()
const_nonempty_iterator nonempty_begin () const
nonempty_iterator nonempty_end ()
const_nonempty_iterator nonempty_end () const
reverse_nonempty_iterator nonempty_rbegin ()
const_reverse_nonempty_iterator nonempty_rbegin () const
reverse_nonempty_iterator nonempty_rend ()
const_reverse_nonempty_iterator nonempty_rend () const
destructive_iterator destructive_begin ()
destructive_iterator destructive_end ()
u_int16_t pos_in_group (size_type i) const
size_type group_num (size_type i) const
GroupsReference which_group (size_type i)
GroupsConstReference which_group (size_type i) const
sparsetable (size_type sz=0, Alloc alloc=Alloc())
void swap (sparsetable &x)
void clear ()
allocator_type get_allocator () const
size_type size () const
size_type max_size () const
bool empty () const
size_type num_nonempty () const
void resize (size_type new_size)
bool test (size_type i) const
bool test (iterator pos) const
bool test (const_iterator pos) const
const_reference get (size_type i) const
const_reference unsafe_get (size_type i) const
reference mutating_get (size_type i)
const_reference operator[] (size_type i) const
element_adaptor operator[] (size_type i)
const_nonempty_iterator get_iter (size_type i) const
nonempty_iterator get_iter (size_type i)
size_type get_pos (const const_nonempty_iterator it) const
reference set (size_type i, const_reference val)
void erase (size_type i)
void erase (iterator pos)
void erase (iterator start_it, iterator end_it)
template<typename OUTPUT >
bool write_metadata (OUTPUT *fp) const
template<typename INPUT >
bool read_metadata (INPUT *fp)
bool write_nopointer_data (FILE *fp) const
bool read_nopointer_data (FILE *fp)
template<typename ValueSerializer , typename OUTPUT >
bool serialize (ValueSerializer serializer, OUTPUT *fp)
template<typename ValueSerializer , typename INPUT >
bool unserialize (ValueSerializer serializer, INPUT *fp)
bool operator== (const sparsetable &x) const
bool operator< (const sparsetable &x) const
bool operator!= (const sparsetable &x) const
bool operator<= (const sparsetable &x) const
bool operator> (const sparsetable &x) const
bool operator>= (const sparsetable &x) const
Static Public Member Functions
static size_type num_groups (size_type num)
Private Types
typedef Alloc::template rebind
< T >::other value_alloc_type
typedef Alloc::template rebind
< sparsegroup< T, GROUP_SIZE,
value_alloc_type > >::other vector_alloc
typedef unsigned long MagicNumberType
Static Private Member Functions
template<typename OUTPUT , typename IntType >
static bool write_32_or_64 (OUTPUT *fp, IntType value)
template<typename INPUT , typename IntType >
static bool read_32_or_64 (INPUT *fp, IntType *value)
Private Attributes
group_vector_type groups
Settings settings
Static Private Attributes
static const MagicNumberType MAGIC_NUMBER = 0x24687531
Member Typedef Documentation
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef Alloc sparsetable< T, GROUP_SIZE, Alloc >::allocator_type
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef const_table_iterator<sparsetable<T, GROUP_SIZE, Alloc> > sparsetable< T, GROUP_SIZE, Alloc >::const_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef const_two_d_iterator< std::vector< sparsegroup<value_type, GROUP_SIZE, value_alloc_type>, vector_alloc> > sparsetable< T, GROUP_SIZE, Alloc >::const_nonempty_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef value_alloc_type::const_pointer sparsetable< T, GROUP_SIZE, Alloc >::const_pointer
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef value_alloc_type::const_reference sparsetable< T, GROUP_SIZE, Alloc >::const_reference
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef std::reverse_iterator<const_iterator> sparsetable< T, GROUP_SIZE, Alloc >::const_reverse_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef std::reverse_iterator<const_nonempty_iterator> sparsetable< T, GROUP_SIZE, Alloc >::const_reverse_nonempty_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef destructive_two_d_iterator< std::vector< sparsegroup<value_type, GROUP_SIZE, value_alloc_type>, vector_alloc> > sparsetable< T, GROUP_SIZE, Alloc >::destructive_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef value_alloc_type::difference_type sparsetable< T, GROUP_SIZE, Alloc >::difference_type
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef table_element_adaptor<sparsetable<T, GROUP_SIZE, Alloc> > sparsetable< T, GROUP_SIZE, Alloc >::element_adaptor
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef sparsegroup<value_type, GROUP_SIZE, allocator_type> sparsetable< T, GROUP_SIZE, Alloc >::group_type
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef std::vector<group_type, vector_alloc > sparsetable< T, GROUP_SIZE, Alloc >::group_vector_type
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef group_vector_type::const_iterator sparsetable< T, GROUP_SIZE, Alloc >::GroupsConstIterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef group_vector_type::const_reference sparsetable< T, GROUP_SIZE, Alloc >::GroupsConstReference
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef group_vector_type::iterator sparsetable< T, GROUP_SIZE, Alloc >::GroupsIterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef group_vector_type::reference sparsetable< T, GROUP_SIZE, Alloc >::GroupsReference
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef table_iterator<sparsetable<T, GROUP_SIZE, Alloc> > sparsetable< T, GROUP_SIZE, Alloc >::iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef unsigned long sparsetable< T, GROUP_SIZE, Alloc >::MagicNumberType private
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef two_d_iterator< std::vector< sparsegroup<value_type, GROUP_SIZE, value_alloc_type>, vector_alloc> > sparsetable< T, GROUP_SIZE, Alloc >::nonempty_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef sparsehash_internal::pod_serializer<value_type> sparsetable< T, GROUP_SIZE, Alloc >::NopointerSerializer
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef value_alloc_type::pointer sparsetable< T, GROUP_SIZE, Alloc >::pointer
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef value_alloc_type::reference sparsetable< T, GROUP_SIZE, Alloc >::reference
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef std::reverse_iterator<iterator> sparsetable< T, GROUP_SIZE, Alloc >::reverse_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef std::reverse_iterator<nonempty_iterator> sparsetable< T, GROUP_SIZE, Alloc >::reverse_nonempty_iterator
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef value_alloc_type::size_type sparsetable< T, GROUP_SIZE, Alloc >::size_type
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef Alloc::template rebind<T>::other sparsetable< T, GROUP_SIZE, Alloc >::value_alloc_type private
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef T sparsetable< T, GROUP_SIZE, Alloc >::value_type
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> typedef Alloc::template rebind< sparsegroup<T, GROUP_SIZE, value_alloc_type> >::other sparsetable< T, GROUP_SIZE, Alloc >::vector_alloc private
Constructor & Destructor Documentation
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> sparsetable< T, GROUP_SIZE, Alloc >::sparsetable (size_type sz = 0, Alloc alloc = Alloc()) inline explicit
References sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::num_groups(), and sparsetable< T, GROUP_SIZE, Alloc >::settings.
Member Function Documentation
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> iterator sparsetable< T, GROUP_SIZE, Alloc >::begin () inline
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::operator<(), and sparsetable< T, GROUP_SIZE, Alloc >::rend().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_iterator sparsetable< T, GROUP_SIZE, Alloc >::begin () const inline
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> void sparsetable< T, GROUP_SIZE, Alloc >::clear () inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, and sparsetable< T, GROUP_SIZE, Alloc >::settings.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::read_metadata(), and sparsetable< T, GROUP_SIZE, Alloc >::unserialize().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> destructive_iterator sparsetable< T, GROUP_SIZE, Alloc >::destructive_begin () inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> destructive_iterator sparsetable< T, GROUP_SIZE, Alloc >::destructive_end () inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::empty () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::settings, and sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> iterator sparsetable< T, GROUP_SIZE, Alloc >::end () inline
References sparsetable< T, GROUP_SIZE, Alloc >::size().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::operator<(), and sparsetable< T, GROUP_SIZE, Alloc >::rbegin().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_iterator sparsetable< T, GROUP_SIZE, Alloc >::end () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::size().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> void sparsetable< T, GROUP_SIZE, Alloc >::erase (size_type i) inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::erase().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> void sparsetable< T, GROUP_SIZE, Alloc >::erase (iterator pos) inline
References sparsetable< T, GROUP_SIZE, Alloc >::erase(), and table_iterator< tabletype >::pos.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> void sparsetable< T, GROUP_SIZE, Alloc >::erase (iterator start_it, iterator end_it) inline
References sparsetable< T, GROUP_SIZE, Alloc >::erase().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reference sparsetable< T, GROUP_SIZE, Alloc >::get (size_type i) const inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> allocator_type sparsetable< T, GROUP_SIZE, Alloc >::get_allocator () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::settings.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::get_iter (size_type i) const inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::group_num(), sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), and sparsetable< T, GROUP_SIZE, Alloc >::test().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::get_iter (size_type i) inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::group_num(), sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), and sparsetable< T, GROUP_SIZE, Alloc >::test().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> size_type sparsetable< T, GROUP_SIZE, Alloc >::get_pos (const const_nonempty_iterator it) const inline
References const_two_d_iterator< containertype >::col_current, sparsetable< T, GROUP_SIZE, Alloc >::groups, const_two_d_iterator< containertype >::row_begin, and const_two_d_iterator< containertype >::row_current.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> size_type sparsetable< T, GROUP_SIZE, Alloc >::group_num (size_type i) const inline
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::get_iter(), and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> size_type sparsetable< T, GROUP_SIZE, Alloc >::max_size () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::settings.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> reference sparsetable< T, GROUP_SIZE, Alloc >::mutating_get (size_type i) inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin () inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::nonempty_rend(), sparsetable< T, GROUP_SIZE, Alloc >::read_nopointer_data(), sparsetable< T, GROUP_SIZE, Alloc >::serialize(), sparsetable< T, GROUP_SIZE, Alloc >::unserialize(), and sparsetable< T, GROUP_SIZE, Alloc >::write_nopointer_data().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end () inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::nonempty_rbegin(), sparsetable< T, GROUP_SIZE, Alloc >::read_nopointer_data(), sparsetable< T, GROUP_SIZE, Alloc >::serialize(), sparsetable< T, GROUP_SIZE, Alloc >::unserialize(), and sparsetable< T, GROUP_SIZE, Alloc >::write_nopointer_data().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> reverse_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_rbegin () inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reverse_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_rbegin () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> reverse_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_rend () inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reverse_nonempty_iterator sparsetable< T, GROUP_SIZE, Alloc >::nonempty_rend () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> static size_type sparsetable< T, GROUP_SIZE, Alloc >::num_groups (size_type num) inline static
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::resize(), and sparsetable< T, GROUP_SIZE, Alloc >::sparsetable().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> size_type sparsetable< T, GROUP_SIZE, Alloc >::num_nonempty () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, and sparsetable< T, GROUP_SIZE, Alloc >::settings.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::operator!= (const sparsetable< T, GROUP_SIZE, Alloc > & x) const inline
References nest::names::x.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::operator< (const sparsetable< T, GROUP_SIZE, Alloc > & x) const inline
References sparsetable< T, GROUP_SIZE, Alloc >::begin(), and sparsetable< T, GROUP_SIZE, Alloc >::end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::operator<= (const sparsetable< T, GROUP_SIZE, Alloc > & x) const inline
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::operator== (const sparsetable< T, GROUP_SIZE, Alloc > & x) const inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::settings, and sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::operator> (const sparsetable< T, GROUP_SIZE, Alloc > & x) const inline
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::operator>= (const sparsetable< T, GROUP_SIZE, Alloc > & x) const inline
References nest::names::x.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reference sparsetable< T, GROUP_SIZE, Alloc >::operator[] (size_type i) const inline
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> element_adaptor sparsetable< T, GROUP_SIZE, Alloc >::operator[] (size_type i) inline
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> u_int16_t sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group (size_type i) const inline
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::erase(), sparsetable< T, GROUP_SIZE, Alloc >::get(), sparsetable< T, GROUP_SIZE, Alloc >::get_iter(), sparsetable< T, GROUP_SIZE, Alloc >::mutating_get(), sparsetable< T, GROUP_SIZE, Alloc >::resize(), sparsetable< T, GROUP_SIZE, Alloc >::set(), sparsetable< T, GROUP_SIZE, Alloc >::test(), and sparsetable< T, GROUP_SIZE, Alloc >::unsafe_get().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> reverse_iterator sparsetable< T, GROUP_SIZE, Alloc >::rbegin () inline
References sparsetable< T, GROUP_SIZE, Alloc >::end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reverse_iterator sparsetable< T, GROUP_SIZE, Alloc >::rbegin () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> template<typename INPUT , typename IntType > static bool sparsetable< T, GROUP_SIZE, Alloc >::read_32_or_64 (INPUT * fp, IntType * value) inline static private
References sparsehash_internal::read_bigendian_number().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::read_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> template<typename INPUT > bool sparsetable< T, GROUP_SIZE, Alloc >::read_metadata (INPUT * fp) inline
References sparsetable< T, GROUP_SIZE, Alloc >::clear(), sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::MAGIC_NUMBER, sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::read_32_or_64(), sparsetable< T, GROUP_SIZE, Alloc >::resize(), sparsetable< T, GROUP_SIZE, Alloc >::settings, and sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::unserialize().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::read_nopointer_data (FILE * fp) inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin(), and sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> reverse_iterator sparsetable< T, GROUP_SIZE, Alloc >::rend () inline
References sparsetable< T, GROUP_SIZE, Alloc >::begin().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reverse_iterator sparsetable< T, GROUP_SIZE, Alloc >::rend () const inline
References sparsetable< T, GROUP_SIZE, Alloc >::begin().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> void sparsetable< T, GROUP_SIZE, Alloc >::resize (size_type new_size) inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::num_groups(), sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, and sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::read_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> template<typename ValueSerializer , typename OUTPUT > bool sparsetable< T, GROUP_SIZE, Alloc >::serialize (ValueSerializer serializer, OUTPUT * fp) inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin(), sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end(), and sparsetable< T, GROUP_SIZE, Alloc >::write_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> reference sparsetable< T, GROUP_SIZE, Alloc >::set (size_type i, const_reference val) inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> size_type sparsetable< T, GROUP_SIZE, Alloc >::size (void) const inline
References sparsetable< T, GROUP_SIZE, Alloc >::settings, and sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::end().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> void sparsetable< T, GROUP_SIZE, Alloc >::swap (sparsetable< T, GROUP_SIZE, Alloc > & x) inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::settings, swap(), and sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size.
Referenced by swap().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::test (size_type i) const inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::get_iter(), and sparsetable< T, GROUP_SIZE, Alloc >::unsafe_get().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::test (iterator pos) const inline
References table_iterator< tabletype >::pos, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::test (const_iterator pos) const inline
References const_table_iterator< tabletype >::pos, sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const_reference sparsetable< T, GROUP_SIZE, Alloc >::unsafe_get (size_type i) const inline
References assert(), sparsetable< T, GROUP_SIZE, Alloc >::pos_in_group(), sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, sparsetable< T, GROUP_SIZE, Alloc >::test(), and sparsetable< T, GROUP_SIZE, Alloc >::which_group().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> template<typename ValueSerializer , typename INPUT > bool sparsetable< T, GROUP_SIZE, Alloc >::unserialize (ValueSerializer serializer, INPUT * fp) inline
References sparsetable< T, GROUP_SIZE, Alloc >::clear(), sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin(), sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end(), and sparsetable< T, GROUP_SIZE, Alloc >::read_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> GroupsReference sparsetable< T, GROUP_SIZE, Alloc >::which_group (size_type i) inline
References sparsetable< T, GROUP_SIZE, Alloc >::group_num(), and sparsetable< T, GROUP_SIZE, Alloc >::groups.
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::erase(), sparsetable< T, GROUP_SIZE, Alloc >::get(), sparsetable< T, GROUP_SIZE, Alloc >::mutating_get(), sparsetable< T, GROUP_SIZE, Alloc >::set(), sparsetable< T, GROUP_SIZE, Alloc >::test(), and sparsetable< T, GROUP_SIZE, Alloc >::unsafe_get().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> GroupsConstReference sparsetable< T, GROUP_SIZE, Alloc >::which_group (size_type i) const inline
References sparsetable< T, GROUP_SIZE, Alloc >::group_num(), and sparsetable< T, GROUP_SIZE, Alloc >::groups.
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> template<typename OUTPUT , typename IntType > static bool sparsetable< T, GROUP_SIZE, Alloc >::write_32_or_64 (OUTPUT * fp, IntType value) inline static private
References sparsehash_internal::write_bigendian_number().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::write_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> template<typename OUTPUT > bool sparsetable< T, GROUP_SIZE, Alloc >::write_metadata (OUTPUT * fp) const inline
References sparsetable< T, GROUP_SIZE, Alloc >::groups, sparsetable< T, GROUP_SIZE, Alloc >::MAGIC_NUMBER, sparsetable< T, GROUP_SIZE, Alloc >::Settings::num_buckets, sparsetable< T, GROUP_SIZE, Alloc >::settings, sparsetable< T, GROUP_SIZE, Alloc >::Settings::table_size, and sparsetable< T, GROUP_SIZE, Alloc >::write_32_or_64().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::serialize().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> bool sparsetable< T, GROUP_SIZE, Alloc >::write_nopointer_data (FILE * fp) const inline
References sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin(), and sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end().
Member Data Documentation
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> group_vector_type sparsetable< T, GROUP_SIZE, Alloc >::groups private
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::clear(), sparsetable< T, GROUP_SIZE, Alloc >::destructive_begin(), sparsetable< T, GROUP_SIZE, Alloc >::destructive_end(), sparsetable< T, GROUP_SIZE, Alloc >::get_iter(), sparsetable< T, GROUP_SIZE, Alloc >::get_pos(), sparsetable< T, GROUP_SIZE, Alloc >::nonempty_begin(), sparsetable< T, GROUP_SIZE, Alloc >::nonempty_end(), sparsetable< T, GROUP_SIZE, Alloc >::operator==(), sparsetable< T, GROUP_SIZE, Alloc >::read_metadata(), sparsetable< T, GROUP_SIZE, Alloc >::resize(), sparsetable< T, GROUP_SIZE, Alloc >::sparsetable(), sparsetable< T, GROUP_SIZE, Alloc >::swap(), sparsetable< T, GROUP_SIZE, Alloc >::which_group(), and sparsetable< T, GROUP_SIZE, Alloc >::write_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> const MagicNumberType sparsetable< T, GROUP_SIZE, Alloc >::MAGIC_NUMBER = 0x24687531 static private
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::read_metadata(), and sparsetable< T, GROUP_SIZE, Alloc >::write_metadata().
template<class T, u_int16_t GROUP_SIZE = DEFAULT_SPARSEGROUP_SIZE, class Alloc = libc_allocator_with_realloc<T>> Settings sparsetable< T, GROUP_SIZE, Alloc >::settings private
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::clear(), sparsetable< T, GROUP_SIZE, Alloc >::empty(), sparsetable< T, GROUP_SIZE, Alloc >::erase(), sparsetable< T, GROUP_SIZE, Alloc >::get(), sparsetable< T, GROUP_SIZE, Alloc >::get_allocator(), sparsetable< T, GROUP_SIZE, Alloc >::max_size(), sparsetable< T, GROUP_SIZE, Alloc >::mutating_get(), sparsetable< T, GROUP_SIZE, Alloc >::num_nonempty(), sparsetable< T, GROUP_SIZE, Alloc >::operator==(), sparsetable< T, GROUP_SIZE, Alloc >::read_metadata(), sparsetable< T, GROUP_SIZE, Alloc >::resize(), sparsetable< T, GROUP_SIZE, Alloc >::set(), sparsetable< T, GROUP_SIZE, Alloc >::size(), sparsetable< T, GROUP_SIZE, Alloc >::sparsetable(), sparsetable< T, GROUP_SIZE, Alloc >::swap(), sparsetable< T, GROUP_SIZE, Alloc >::test(), sparsetable< T, GROUP_SIZE, Alloc >::unsafe_get(), and sparsetable< T, GROUP_SIZE, Alloc >::write_metadata().
The documentation for this class was generated from the following file:
sparsetable.h