NEST: table_iterator< tabletype > Class Template Reference
table_iterator< tabletype > Class Template Reference
#include <sparsetable.h>
Public Types
typedef table_iterator iterator
typedef
std::random_access_iterator_tag iterator_category
typedef tabletype::value_type value_type
typedef tabletype::difference_type difference_type
typedef tabletype::size_type size_type
typedef table_element_adaptor
< tabletype > reference
typedef table_element_adaptor
< tabletype > * pointer
Public Member Functions
table_iterator (tabletype *tbl, size_type p)
table_iterator ()
reference operator* ()
pointer operator-> ()
void check () const
iterator & operator+= (size_type t)
iterator & operator-= (size_type t)
iterator & operator++ ()
iterator & operator-- ()
iterator operator++ (int)
iterator operator-- (int)
iterator operator+ (difference_type i) const
iterator operator- (difference_type i) const
difference_type operator- (iterator it) const
reference operator[] (difference_type n) const
bool operator== (const iterator &it) const
bool operator< (const iterator &it) const
bool operator!= (const iterator &it) const
bool operator<= (const iterator &it) const
bool operator> (const iterator &it) const
bool operator>= (const iterator &it) const
Public Attributes
tabletype * table
size_type pos
Member Typedef Documentation
template<class tabletype> typedef tabletype::difference_type table_iterator< tabletype >::difference_type
template<class tabletype> typedef table_iterator table_iterator< tabletype >::iterator
template<class tabletype> typedef std::random_access_iterator_tag table_iterator< tabletype >::iterator_category
template<class tabletype> typedef table_element_adaptor<tabletype>* table_iterator< tabletype >::pointer
template<class tabletype> typedef table_element_adaptor<tabletype> table_iterator< tabletype >::reference
template<class tabletype> typedef tabletype::size_type table_iterator< tabletype >::size_type
template<class tabletype> typedef tabletype::value_type table_iterator< tabletype >::value_type
Constructor & Destructor Documentation
template<class tabletype> table_iterator< tabletype >::table_iterator (tabletype * tbl, size_type p) inline
template<class tabletype> table_iterator< tabletype >::table_iterator () inline
Member Function Documentation
template<class tabletype> void table_iterator< tabletype >::check () const inline
References assert(), and table_iterator< tabletype >::table.
Referenced by table_iterator< tabletype >::operator++(), table_iterator< tabletype >::operator+=(), table_iterator< tabletype >::operator--(), and table_iterator< tabletype >::operator-=().
template<class tabletype> bool table_iterator< tabletype >::operator!= (const iterator & it) const inline
template<class tabletype> reference table_iterator< tabletype >::operator* () inline
References table_iterator< tabletype >::pos, and table_iterator< tabletype >::table.
Referenced by table_iterator< tabletype >::operator->().
template<class tabletype> iterator table_iterator< tabletype >::operator+ (difference_type i) const inline
template<class tabletype> iterator& table_iterator< tabletype >::operator++ () inline
References table_iterator< tabletype >::check(), and table_iterator< tabletype >::pos.
template<class tabletype> iterator table_iterator< tabletype >::operator++ (int) inline
References table_iterator< tabletype >::check(), and table_iterator< tabletype >::pos.
template<class tabletype> iterator& table_iterator< tabletype >::operator+= (size_type t) inline
References table_iterator< tabletype >::check(), and table_iterator< tabletype >::pos.
template<class tabletype> iterator table_iterator< tabletype >::operator- (difference_type i) const inline
template<class tabletype> difference_type table_iterator< tabletype >::operator- (iterator it) const inline
References assert(), table_iterator< tabletype >::pos, and table_iterator< tabletype >::table.
template<class tabletype> iterator& table_iterator< tabletype >::operator-- () inline
References table_iterator< tabletype >::check(), and table_iterator< tabletype >::pos.
template<class tabletype> iterator table_iterator< tabletype >::operator-- (int) inline
References table_iterator< tabletype >::check(), and table_iterator< tabletype >::pos.
template<class tabletype> iterator& table_iterator< tabletype >::operator-= (size_type t) inline
References table_iterator< tabletype >::check(), and table_iterator< tabletype >::pos.
template<class tabletype> pointer table_iterator< tabletype >::operator-> () inline
References table_iterator< tabletype >::operator*().
template<class tabletype> bool table_iterator< tabletype >::operator< (const iterator & it) const inline
References assert(), table_iterator< tabletype >::pos, and table_iterator< tabletype >::table.
template<class tabletype> bool table_iterator< tabletype >::operator<= (const iterator & it) const inline
template<class tabletype> bool table_iterator< tabletype >::operator== (const iterator & it) const inline
References table_iterator< tabletype >::pos, and table_iterator< tabletype >::table.
template<class tabletype> bool table_iterator< tabletype >::operator> (const iterator & it) const inline
template<class tabletype> bool table_iterator< tabletype >::operator>= (const iterator & it) const inline
template<class tabletype> reference table_iterator< tabletype >::operator[] (difference_type n) const inline
References nest::names::n.
Member Data Documentation
template<class tabletype> size_type table_iterator< tabletype >::pos
Referenced by sparsegroup< T, GROUP_SIZE, Alloc >::erase(), sparsetable< T, GROUP_SIZE, Alloc >::erase(), table_iterator< tabletype >::operator*(), table_iterator< tabletype >::operator++(), table_iterator< tabletype >::operator+=(), table_iterator< tabletype >::operator-(), table_iterator< tabletype >::operator--(), table_iterator< tabletype >::operator-=(), table_iterator< tabletype >::operator<(), table_iterator< tabletype >::operator==(), sparsegroup< T, GROUP_SIZE, Alloc >::test(), and sparsetable< T, GROUP_SIZE, Alloc >::test().
template<class tabletype> tabletype* table_iterator< tabletype >::table
Referenced by table_iterator< tabletype >::check(), table_iterator< tabletype >::operator*(), table_iterator< tabletype >::operator-(), table_iterator< tabletype >::operator<(), and table_iterator< tabletype >::operator==().
The documentation for this class was generated from the following file:
sparsetable.h