NEST: nest::CommonPropertiesHomW Class Reference
nest::CommonPropertiesHomW Class Reference
Class containing the common properties for all synapses with common weight.
#include <common_properties_hom_w.h>
Public Member Functions
CommonPropertiesHomW ()
Default constructor.
void get_status (DictionaryDatum &d) const
Get all properties and put them into a dictionary.
double_t get_weight () const
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties from the values given in dictionary.
Public Member Functions inherited from nest::CommonSynapseProperties
CommonSynapseProperties ()
Standard constructor.
~CommonSynapseProperties ()
Destructor.
void get_status (DictionaryDatum &d) const
Get all properties and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate all time objects, which might be contained in this object.
Node * get_node ()
get reference to registering node
long_t get_vt_gid () const
Private Attributes
double_t weight_
Detailed Description
Class containing the common properties for all synapses with common weight.
Constructor & Destructor Documentation
nest::CommonPropertiesHomW::CommonPropertiesHomW () inline
Default constructor.
Sets all property values to defaults.
Member Function Documentation
void nest::CommonPropertiesHomW::get_status (DictionaryDatum & d) const inline
Get all properties and put them into a dictionary.
References nest::names::d, nest::CommonSynapseProperties::get_status(), nest::names::weight, and weight_.
double_t nest::CommonPropertiesHomW::get_weight () const inline
References weight_.
Referenced by nest::StaticConnectionHomW< targetidentifierT >::send().
void nest::CommonPropertiesHomW::set_status (const DictionaryDatum & d, ConnectorModel & cm) inline
Set properties from the values given in dictionary.
References nest::names::d, nest::CommonSynapseProperties::set_status(), nest::names::weight, and weight_.
Member Data Documentation
double_t nest::CommonPropertiesHomW::weight_ private
Referenced by get_status(), get_weight(), and set_status().
The documentation for this class was generated from the following file:
common_properties_hom_w.h