NEST: nest::Modelrangemanager Class Reference
nest::Modelrangemanager Class Reference
#include <modelrangemanager.h>
Public Member Functions
Modelrangemanager ()
void add_range (index model, index first_gid, index last_gid)
bool is_in_range (index gid) const
long_t get_model_id (index gid)
bool model_in_use (index i) const
void clear ()
void print () const
const modelrange & get_range (index gid) const
Private Attributes
std::vector< modelrange > modelranges_
index first_gid_
index last_gid_
Constructor & Destructor Documentation
nest::Modelrangemanager::Modelrangemanager ()
Member Function Documentation
void nest::Modelrangemanager::add_range (index model, index first_gid, index last_gid)
References assert(), first_gid_, last_gid_, and modelranges_.
Referenced by nest::Network::add_node(), and nest::Network::init_().
void nest::Modelrangemanager::clear ()
References modelranges_.
Referenced by nest::Network::destruct_nodes_().
long_t nest::Modelrangemanager::get_model_id (index gid)
References assert(), is_in_range(), and modelranges_.
Referenced by nest::Network::get_model_id_of_gid(), and nest::Network::get_node().
const modelrange & nest::Modelrangemanager::get_range (index gid) const
References is_in_range(), and modelranges_.
Referenced by nest::Network::get_contiguous_gid_range().
bool nest::Modelrangemanager::is_in_range (index gid) const inline
References first_gid_, and last_gid_.
Referenced by get_model_id(), nest::Network::get_model_id_of_gid(), and get_range().
bool nest::Modelrangemanager::model_in_use (index i) const
References modelranges_.
Referenced by nest::Network::model_in_use().
void nest::Modelrangemanager::print () const
Member Data Documentation
index nest::Modelrangemanager::first_gid_ private
Referenced by add_range(), and is_in_range().
index nest::Modelrangemanager::last_gid_ private
Referenced by add_range(), and is_in_range().
std::vector<modelrange> nest::Modelrangemanager::modelranges_ private
Referenced by add_range(), clear(), get_model_id(), get_range(), and model_in_use().
The documentation for this class was generated from the following files:
modelrangemanager.h
modelrangemanager.cpp