NEST: GenericDatum< D, slt > Class Template Reference
GenericDatum< D, slt > Class Template Reference
#include <genericdatum.h>
Public Member Functions
GenericDatum ()
virtual ~GenericDatum ()
GenericDatum (const D &d_s)
GenericDatum (const GenericDatum< D, slt > &gd)
const D & operator= (const D &d_s)
const D & get (void) const
D & get (void)
D & get_lval ()
void print (std::ostream &o) const
void pprint (std::ostream &o) const
void info (std::ostream &out) const
bool equals (const Datum *dat) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
virtual void list (std::ostream &o, std::string prefix, int l) const
virtual void input_form (std::ostream &o) const
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Protected Attributes
D d
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Private Member Functions
virtual Datum * clone (void) const
Virtual copy constructor.
Additional Inherited Members
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Constructor & Destructor Documentation
template<class D, SLIType * slt> GenericDatum< D, slt >::GenericDatum () inline
template<class D, SLIType * slt> virtual GenericDatum< D, slt >::~GenericDatum () inline virtual
template<class D, SLIType * slt> GenericDatum< D, slt >::GenericDatum (const D & d_s) inline
template<class D, SLIType * slt> GenericDatum< D, slt >::GenericDatum (const GenericDatum< D, slt > & gd) inline
Member Function Documentation
template<class D, SLIType * slt> virtual Datum* GenericDatum< D, slt >::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Implements Datum.
Reimplemented in IteratorDatum, NumericDatum< D, slt >, and BoolDatum.
template<class D, SLIType * slt> bool GenericDatum< D, slt >::equals (const Datum * dat) const inline virtual
Reimplemented from Datum.
template<class D, SLIType * slt> const D& GenericDatum< D, slt >::get (void) const inline
Referenced by array2vector(), SLIArrayModule::IMapFunction::backtrace(), IiterateFunction::backtrace(), SLIArrayModule::IMap_ivFunction::backtrace(), SLIArrayModule::IMap_dvFunction::backtrace(), IloopFunction::backtrace(), IrepeatFunction::backtrace(), SLIArrayModule::IMapThreadFunction::backtrace(), IforFunction::backtrace(), SLIArrayModule::IMapIndexedFunction::backtrace(), IforallarrayFunction::backtrace(), IforallindexedarrayFunction::backtrace(), IforallindexedstringFunction::backtrace(), IforallstringFunction::backtrace(), SLIArrayModule::Iforall_ivFunction::backtrace(), SLIArrayModule::Iforall_dvFunction::backtrace(), Add_diFunction::execute(), Add_iiFunction::execute(), Get_a_aFunction::execute(), SLIArrayModule::IMapFunction::execute(), Add_idFunction::execute(), RegexpModule::RegexecFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), SLIgraphics::WritePGMFunction::execute(), Add_ddFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), Sub_diFunction::execute(), CallbacktypeFunction::execute(), RollFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), SpecialFunctionsModule::GammaIncFunction::execute(), Sub_iiFunction::execute(), IforFunction::execute(), SpecialFunctionsModule::LambertW0Function::execute(), Sub_idFunction::execute(), SpecialFunctionsModule::LambertWm1Function::execute(), SLIArrayModule::IMapIndexedFunction::execute(), IforallarrayFunction::execute(), IfFunction::execute(), Sub_ddFunction::execute(), SLIArrayModule::RangeFunction::execute(), SpecialFunctionsModule::ErfFunction::execute(), IfelseFunction::execute(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), SpecialFunctionsModule::ErfcFunction::execute(), Mul_diFunction::execute(), IforallindexedarrayFunction::execute(), Prepend_sFunction::execute(), Mul_iiFunction::execute(), IforallindexedstringFunction::execute(), Mul_idFunction::execute(), IforallstringFunction::execute(), Mul_ddFunction::execute(), Insert_sFunction::execute(), Div_diFunction::execute(), Insert_aFunction::execute(), Div_iiFunction::execute(), InsertElement_sFunction::execute(), SLIArrayModule::PartitionFunction::execute(), Div_idFunction::execute(), InsertElement_aFunction::execute(), Replace_sFunction::execute(), Div_ddFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), SetwFunction::execute(), Replace_aFunction::execute(), SetprecisionFunction::execute(), Mod_iiFunction::execute(), Erase_sFunction::execute(), Erase_aFunction::execute(), Erase_pFunction::execute(), SLIArrayModule::AreaFunction::execute(), Processes::KillFunction::execute(), Reserve_aFunction::execute(), SLIArrayModule::Area2Function::execute(), Sqr_dFunction::execute(), Resize_aFunction::execute(), SLIArrayModule::Cv1dFunction::execute(), SLIArrayModule::Cv2dFunction::execute(), SLIArrayModule::GetMaxFunction::execute(), Pow_ddFunction::execute(), SLIArrayModule::GetMinFunction::execute(), Pow_diFunction::execute(), Reserve_sFunction::execute(), Resize_sFunction::execute(), Ldexp_diFunction::execute(), Getinterval_sFunction::execute(), Getinterval_aFunction::execute(), Abs_iFunction::execute(), Abs_dFunction::execute(), Neg_iFunction::execute(), Neg_dFunction::execute(), Inv_dFunction::execute(), SLIArrayModule::Mul_d_ivFunction::execute(), AndFunction::execute(), OrFunction::execute(), And_iiFunction::execute(), Or_iiFunction::execute(), XorFunction::execute(), Not_bFunction::execute(), Not_iFunction::execute(), Geq_iiFunction::execute(), Put_sFunction::execute(), SLIArrayModule::Put_dv_i_dFunction::execute(), Geq_idFunction::execute(), SLIArrayModule::Put_iv_i_iFunction::execute(), Put_aFunction::execute(), Geq_diFunction::execute(), SLIArrayModule::Zeros_ivFunction::execute(), Put_pFunction::execute(), SLIArrayModule::Zeros_dvFunction::execute(), Put_lpFunction::execute(), Geq_ddFunction::execute(), SLIArrayModule::Ones_dvFunction::execute(), SLIArrayModule::Ones_ivFunction::execute(), SetGuardFunction::execute(), Leq_iiFunction::execute(), SLIArrayModule::ArangeFunction::execute(), Leq_idFunction::execute(), Leq_diFunction::execute(), IrepeatanyFunction::execute(), Leq_ddFunction::execute(), SLIArrayModule::Iforall_ivFunction::execute(), Gt_iiFunction::execute(), SLIArrayModule::Iforall_dvFunction::execute(), Gt_ddFunction::execute(), Lt_iiFunction::execute(), Lt_ddFunction::execute(), Lt_idFunction::execute(), Lt_diFunction::execute(), IntegerFunction::execute(), DoubleFunction::execute(), UnitStep_dFunction::execute(), UnitStep_iaFunction::execute(), UnitStep_daFunction::execute(), Max_i_iFunction::execute(), Max_i_dFunction::execute(), Max_d_iFunction::execute(), Max_d_dFunction::execute(), Min_i_iFunction::execute(), Min_i_dFunction::execute(), Min_d_iFunction::execute(), Min_d_dFunction::execute(), nest::Time::ms::fromtoken(), get_double_in_range(), get_long_in_range(), nest::Network::random_convergent_connect(), TokenArray::toValarray(), TokenArray::toVector(), and nest::update_value_int().
template<class D, SLIType * slt> D& GenericDatum< D, slt >::get (void) inline
template<class D, SLIType * slt> D& GenericDatum< D, slt >::get_lval () inline
template<class D, SLIType * slt> void GenericDatum< D, slt >::info (std::ostream & out) const inline virtual
Reimplemented from Datum.
template<class D, SLIType * slt> const D& GenericDatum< D, slt >::operator= (const D & d_s) inline
template<class D, SLIType * slt> void GenericDatum< D, slt >::pprint (std::ostream & o) const inline virtual
Implements Datum.
Reimplemented in NumericDatum< D, slt >, NumericDatum< D, slt >, and NumericDatum< D, slt >.
template<class D, SLIType * slt> void GenericDatum< D, slt >::print (std::ostream & o) const inline virtual
Implements Datum.
Member Data Documentation
template<class D, SLIType * slt> D GenericDatum< D, slt >::d protected
Referenced by GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::equals(), GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::get(), GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::get_lval(), GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::info(), IteratorDatum::IteratorDatum(), NumericDatum< D, slt >::NumericDatum(), NumericDatum< D, slt >::operator D(), NumericDatum< D, slt >::operator D &(), GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::operator=(), IteratorDatum::operator==(), GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::pprint(), and GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::print().
The documentation for this class was generated from the following file:
genericdatum.h