NEST: ProceduretypeFunction Class Reference
ProceduretypeFunction Class Reference
#include <sliactions.h>
Public Member Functions
ProceduretypeFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
ProceduretypeFunction::ProceduretypeFunction () inline
Member Function Documentation
void ProceduretypeFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::code_accessed, Token::datum(), SLIInterpreter::EStack, SLIInterpreter::Iiterate(), SLIInterpreter::inc_call_depth(), TokenStack::push_by_pointer(), TokenStack::push_by_ref(), and TokenStack::top().
The documentation for this class was generated from the following files:
sliactions.h
sliactions.cc