NEST: nest::StaticConnectionHomW< targetidentifierT > Class Template Reference
nest::StaticConnectionHomW< targetidentifierT > Class Template Reference
Class representing a static connection.
#include <static_connection_hom_w.h>
Classes
class ConnTestDummyNode
Public Types
typedef CommonPropertiesHomW CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
void get_status (DictionaryDatum &d) const
void check_connection (Node &s, Node &t, rport receptor_type, double_t, const CommonPropertiesType &)
void send (Event &e, thread t, double_t, const CommonPropertiesHomW &cp)
Send an event to the receiver of this connection.
void set_weight (double_t)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Detailed Description
template<typename targetidentifierT>
class nest::StaticConnectionHomW< targetidentifierT >
Class representing a static connection.
A static connection has the properties weight, delay and receiver port. A suitable Connector containing these connections can be obtained from the template GenericConnector.
Member Typedef Documentation
template<typename targetidentifierT > typedef CommonPropertiesHomW nest::StaticConnectionHomW< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::StaticConnectionHomW< targetidentifierT >::ConnectionBase
Member Function Documentation
template<typename targetidentifierT > void nest::StaticConnectionHomW< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t , const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_().
template<typename targetidentifierT > void nest::StaticConnectionHomW< targetidentifierT >::get_status (DictionaryDatum & d) const
References nest::names::d, and nest::names::size_of.
template<typename targetidentifierT > void nest::StaticConnectionHomW< targetidentifierT >::send (Event & e, thread t, double_t , const CommonPropertiesHomW & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
p The port under which this connection is stored in the Connector.
t_lastspike Time point of last spike emitted
References numerics::e, nest::Connection< targetidentifierT >::get_delay_steps(), nest::Connection< targetidentifierT >::get_rport(), nest::Connection< targetidentifierT >::get_target(), nest::CommonPropertiesHomW::get_weight(), nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), and nest::Event::set_weight().
template<typename targetidentifierT > void nest::StaticConnectionHomW< targetidentifierT >::set_weight (double_t) inline
The documentation for this class was generated from the following file:
static_connection_hom_w.h