NEST: nest::STDPConnectionHom< targetidentifierT > Class Template Reference
nest::STDPConnectionHom< targetidentifierT > Class Template Reference
Class representing an STDP connection with homogeneous parameters, i.e.
#include <stdp_connection_hom.h>
Classes
class ConnTestDummyNode
Public Types
typedef STDPHomCommonProperties CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
STDPConnectionHom ()
Default Constructor.
STDPConnectionHom (const STDPConnectionHom &)
Copy constructor from a property object.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t t_lastspike, const STDPHomCommonProperties &)
Send an event to the receiver of this connection.
void set_weight (double_t w)
void check_connection (Node &s, Node &t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Member Functions
double_t facilitate_ (double_t w, double_t kplus, const STDPHomCommonProperties &cp)
double_t depress_ (double_t w, double_t kminus, const STDPHomCommonProperties &cp)
Private Attributes
double_t weight_
double_t Kplus_
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Detailed Description
template<typename targetidentifierT>
class nest::STDPConnectionHom< targetidentifierT >
Class representing an STDP connection with homogeneous parameters, i.e.
parameters are the same for all synapses.
Member Typedef Documentation
template<typename targetidentifierT > typedef STDPHomCommonProperties nest::STDPConnectionHom< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::STDPConnectionHom< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::STDPConnectionHom< targetidentifierT >::STDPConnectionHom ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::STDPConnectionHom< targetidentifierT >::STDPConnectionHom (const STDPConnectionHom< targetidentifierT > & rhs)
Copy constructor from a property object.
Needs to be defined properly in order for GenericConnector to work.
Member Function Documentation
template<typename targetidentifierT > void nest::STDPConnectionHom< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_(), nest::Connection< targetidentifierT >::get_delay(), and nest::Node::register_stdp_connection().
template<typename targetidentifierT > double_t nest::STDPConnectionHom< targetidentifierT >::depress_ (double_t w, double_t kminus, const STDPHomCommonProperties & cp) inline private
References nest::STDPHomCommonProperties::alpha_, nest::STDPHomCommonProperties::lambda_, nest::STDPHomCommonProperties::mu_minus_, and nest::STDPHomCommonProperties::Wmax_.
template<typename targetidentifierT > double_t nest::STDPConnectionHom< targetidentifierT >::facilitate_ (double_t w, double_t kplus, const STDPHomCommonProperties & cp) inline private
References nest::STDPHomCommonProperties::lambda_, nest::STDPHomCommonProperties::mu_plus_, and nest::STDPHomCommonProperties::Wmax_.
template<typename targetidentifierT > void nest::STDPConnectionHom< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, nest::names::size_of, and nest::names::weight.
template<typename targetidentifierT > void nest::STDPConnectionHom< targetidentifierT >::send (Event & e, thread t, double_t t_lastspike, const STDPHomCommonProperties & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
t_lastspike Point in time of last spike sent.
e The event to send
p The port under which this connection is stored in the Connector.
t_lastspike Time point of last spike emitted
References numerics::e, nest::Node::get_history(), nest::Node::get_K_value(), nest::Time::get_ms(), nest::Event::get_stamp(), nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), nest::Event::set_weight(), nest::names::start, nest::names::t_spike, nest::names::target, and nest::STDPHomCommonProperties::tau_plus_.
template<typename targetidentifierT > void nest::STDPConnectionHom< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties of this connection from the values given in dictionary.
References nest::names::d, and nest::names::weight.
template<typename targetidentifierT > void nest::STDPConnectionHom< targetidentifierT >::set_weight (double_t w) inline
References nest::names::w, and nest::STDPConnectionHom< targetidentifierT >::weight_.
Member Data Documentation
template<typename targetidentifierT > double_t nest::STDPConnectionHom< targetidentifierT >::Kplus_ private
template<typename targetidentifierT > double_t nest::STDPConnectionHom< targetidentifierT >::weight_ private
Referenced by nest::STDPConnectionHom< targetidentifierT >::set_weight().
The documentation for this class was generated from the following file:
stdp_connection_hom.h