NEST: sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS > Class Template Reference
sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS > Class Template Reference
#include <hashtable-common.h>
Classes
class hash_munger
class hash_munger< HashKey * >
Public Types
typedef Key key_type
typedef HashFunc hasher
typedef SizeType size_type
Public Member Functions
sh_hashtable_settings (const hasher &hf, const float ht_occupancy_flt, const float ht_empty_flt)
size_type hash (const key_type &v) const
float enlarge_factor () const
void set_enlarge_factor (float f)
float shrink_factor () const
void set_shrink_factor (float f)
size_type enlarge_threshold () const
void set_enlarge_threshold (size_type t)
size_type shrink_threshold () const
void set_shrink_threshold (size_type t)
size_type enlarge_size (size_type x) const
size_type shrink_size (size_type x) const
bool consider_shrink () const
void set_consider_shrink (bool t)
bool use_empty () const
void set_use_empty (bool t)
bool use_deleted () const
void set_use_deleted (bool t)
size_type num_ht_copies () const
void inc_num_ht_copies ()
void reset_thresholds (size_type num_buckets)
void set_resizing_parameters (float shrink, float grow)
size_type min_buckets (size_type num_elts, size_type min_buckets_wanted)
Private Attributes
size_type enlarge_threshold_
size_type shrink_threshold_
float enlarge_factor_
float shrink_factor_
bool consider_shrink_
bool use_empty_
bool use_deleted_
unsigned int num_ht_copies_
Member Typedef Documentation
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> typedef HashFunc sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::hasher
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> typedef Key sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::key_type
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> typedef SizeType sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::size_type
Constructor & Destructor Documentation
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::sh_hashtable_settings (const hasher & hf, const float ht_occupancy_flt, const float ht_empty_flt) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_factor(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_factor().
Member Function Documentation
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> bool sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::consider_shrink () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::consider_shrink_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> float sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::min_buckets().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_size (size_type x) const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::reset_thresholds().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_threshold () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_threshold_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::hash (const key_type & v) const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::hash_munger< HashKey >::MungedHash().
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::hash_munger< HashKey >::MungedHash().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::inc_num_ht_copies () inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::num_ht_copies_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::min_buckets (size_type num_elts, size_type min_buckets_wanted) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::num_ht_copies () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::num_ht_copies_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::reset_thresholds (size_type num_buckets) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_size(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_consider_shrink(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_threshold(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_threshold(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_size().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_consider_shrink (bool t) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::consider_shrink_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::reset_thresholds().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_factor (float f) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_resizing_parameters(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::sh_hashtable_settings().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_threshold (size_type t) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_threshold_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::reset_thresholds().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_resizing_parameters (float shrink, float grow) inline
References assert(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_factor(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_factor().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_factor (float f) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_factor_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_resizing_parameters(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::sh_hashtable_settings().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_threshold (size_type t) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_threshold_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::reset_thresholds().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_use_deleted (bool t) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_deleted_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> void sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_use_empty (bool t) inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_empty_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> float sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_factor () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_factor_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_size (size_type x) const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_factor_.
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::reset_thresholds().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_threshold () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_threshold_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> bool sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_deleted () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_deleted_.
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> bool sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_empty () const inline
References sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_empty_.
Member Data Documentation
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> bool sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::consider_shrink_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::consider_shrink(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_consider_shrink().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> float sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_factor(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_size(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_factor().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_threshold_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::enlarge_threshold(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_enlarge_threshold().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> unsigned int sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::num_ht_copies_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::inc_num_ht_copies(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::num_ht_copies().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> float sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_factor_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_factor(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_factor(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_size().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> size_type sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_threshold_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_shrink_threshold(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::shrink_threshold().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> bool sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_deleted_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_use_deleted(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_deleted().
template<typename Key , typename HashFunc , typename SizeType , int HT_MIN_BUCKETS> bool sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_empty_ private
Referenced by sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_use_empty(), and sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::use_empty().
The documentation for this class was generated from the following file:
hashtable-common.h