NEST: DynModule Class Reference
DynModule Class Reference abstract
Base class for dynamically loadable SLI interpreter modules.
#include <dynmodule.h>
Public Member Functions
virtual ~DynModule ()
virtual void init (SLIInterpreter *, nest::Network *)=0
Initialise the module.
virtual void unregister (SLIInterpreter *, nest::Network *)
Unregister the symbols defined in module.
virtual const std::string name (void) const =0
Return name of the module.
virtual const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
void install (std::ostream &, SLIInterpreter *, nest::Network *)
Print installation message via interpreter message command.
Detailed Description
Base class for dynamically loadable SLI interpreter modules.
Constructor & Destructor Documentation
virtual DynModule::~DynModule () inline virtual
Member Function Documentation
const std::string DynModule::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Referenced by SLIInterpreter::addlinkeddynmodule(), and nest::DynamicLoaderModule::LoadModuleFunction::execute().
virtual void DynModule::init (SLIInterpreter * , nest::Network *) pure virtual
Initialise the module.
When this function is called, most of the interpreter's fascilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialised, not all services may be available.
Referenced by install().
void DynModule::install (std::ostream & , SLIInterpreter * i, nest::Network * net)
Print installation message via interpreter message command.
References init(), SLIInterpreter::message(), and name().
Referenced by SLIInterpreter::addlinkeddynmodule(), and nest::DynamicLoaderModule::LoadModuleFunction::execute().
virtual const std::string DynModule::name (void) const pure virtual
Return name of the module.
Referenced by nest::DynamicLoaderModule::LoadModuleFunction::execute(), nest::has_name(), and install().
virtual void DynModule::unregister (SLIInterpreter * , nest::Network *) inline virtual
Unregister the symbols defined in module.
Referenced by nest::DynamicLoaderModule::UnloadModuleFunction::execute().
The documentation for this class was generated from the following files:
dynmodule.h
dynmodule.cpp