NEST: nest::NestModule::SetMaxBufferedFunction Class Reference
nest::NestModule::SetMaxBufferedFunction Class Reference
SLI Interface functions of the NEST kernel.
#include <nestmodule.h>
Private Member Functions
void execute (SLIInterpreter *) const
Additional Inherited Members
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void nest::NestModule::SetMaxBufferedFunction::execute (SLIInterpreter * i) const private virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, nest::NestModule::get_network(), getValue< long >(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), nest::names::port_name, and nest::Network::set_music_in_port_max_buffered().
The documentation for this class was generated from the following files:
nestmodule.h
nestmodule.cpp