NEST: nest::Device Class Reference
nest::Device Class Reference abstract
Devices
Class implementing common interface and properties common for all devices.
#include <device.h>
Classes
struct Parameters_
Independent parameters of the model.
struct Variables_
Internal variables of the model.
Public Member Functions
Device ()
Device (const Device &n)
virtual ~Device ()
virtual void init_parameters (const Device &)
Reset parameters to those of model; also resets state.
virtual void init_state (const Device &)
Reset dynamic state to that of model.
virtual void init_buffers ()
Reset buffers.
virtual void calibrate ()
Set internal variables, including opening files.
virtual void finalize ()
Housekeeping at end of simulation, eg close files.
virtual void get_status (DictionaryDatum &) const
virtual void set_status (const DictionaryDatum &)
virtual bool is_active (Time const &T) const =0
Returns true if the device is active at the given time stamp.
long_t get_t_min_ () const
Return lower limit in steps.
long_t get_t_max_ () const
Return upper limit in steps.
Time const & get_origin () const
Time const & get_start () const
Time const & get_stop () const
Private Attributes
Parameters_ P_
Variables_ V_
Detailed Description
Class implementing common interface and properties common for all devices.
This class provides a common interface for all derived device classes. Each class derived from Node and implementing a device, should have a member derived from class Device. This member will contribute the implementation of device specific properties.
This class manages the properties common to all devices, namely origin, start and stop of the time window during which the device is active and the optional device label. The precise semantics of when the device is active depend on the type of device and are defined in subclasses.
Author
HEP 2002-07-22, 2008-03-21, 2008-06-20
Constructor & Destructor Documentation
nest::Device::Device ()
nest::Device::Device (const Device & n)
virtual nest::Device::~Device () inline virtual
Member Function Documentation
void nest::Device::calibrate () virtual
Set internal variables, including opening files.
Reimplemented in nest::RecordingDevice.
Referenced by nest::RecordingDevice::calibrate().
virtual void nest::Device::finalize () inline virtual
Housekeeping at end of simulation, eg close files.
Reimplemented in nest::RecordingDevice.
nest::Time const & nest::Device::get_origin () const inline
nest::Time const & nest::Device::get_start () const inline
void nest::Device::get_status (DictionaryDatum & d) const inline virtual
Reimplemented in nest::RecordingDevice, nest::StimulatingDevice< EmittedEvent >, nest::StimulatingDevice< nest::SpikeEvent >, and nest::StimulatingDevice< nest::CurrentEvent >.
References nest::Device::Parameters_::get(), and P_.
Referenced by nest::RecordingDevice::get_status().
nest::Time const & nest::Device::get_stop () const inline
nest::long_t nest::Device::get_t_max_ () const inline
Return upper limit in steps.
Todo:
Should be protected, but is temporarily public to solve inheritance problems in AnalogSamplingDevice.
Referenced by nest::PseudoRecordingDevice::is_active(), nest::Multimeter::is_active(), and nest::RecordingDevice::is_active().
nest::long_t nest::Device::get_t_min_ () const inline
Return lower limit in steps.
Todo:
Should be protected, but is temporarily public to solve inheritance problems in AnalogSamplingDevice.
Referenced by nest::PseudoRecordingDevice::is_active(), nest::Multimeter::is_active(), and nest::RecordingDevice::is_active().
virtual void nest::Device::init_buffers () inline virtual
Reset buffers.
Reimplemented in nest::RecordingDevice.
Referenced by nest::RecordingDevice::init_buffers().
void nest::Device::init_parameters (const Device & proto) virtual
Reset parameters to those of model; also resets state.
References P_.
Referenced by nest::RecordingDevice::init_parameters().
virtual void nest::Device::init_state (const Device &) inline virtual
Reset dynamic state to that of model.
Referenced by nest::RecordingDevice::init_state().
virtual bool nest::Device::is_active (Time const & T) const pure virtual
Returns true if the device is active at the given time stamp.
Semantics are implemented by subclasses.
Implemented in nest::RecordingDevice, nest::StimulatingDevice< EmittedEvent >, nest::StimulatingDevice< EmittedEvent >, nest::StimulatingDevice< EmittedEvent >, nest::StimulatingDevice< EmittedEvent >, nest::StimulatingDevice< nest::SpikeEvent >, nest::StimulatingDevice< nest::CurrentEvent >, and nest::PseudoRecordingDevice.
void nest::Device::set_status (const DictionaryDatum & d) inline virtual
Reimplemented in nest::RecordingDevice.
References nest::Device::Parameters_::set().
Referenced by nest::RecordingDevice::set_status().
Member Data Documentation
Parameters_ nest::Device::P_ private
Referenced by get_status(), and init_parameters().
Variables_ nest::Device::V_ private
The documentation for this class was generated from the following files:
device.h
device.cpp