NEST: Token_sFunction Class Reference
Token_sFunction Class Reference
#include <slicontrol.h>
Public Member Functions
Token_sFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
Token_sFunction::Token_sFunction () inline
Member Function Documentation
void Token_sFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References assert(), Parser::clear_context(), Token::datum(), Scanner::EndSymbol, SLIInterpreter::EStack, TokenStack::load(), SLIInterpreter::OStack, SLIInterpreter::parse, TokenStack::pop(), TokenStack::push(), TokenStack::push_move(), Parser::readToken(), Parser::scan(), and TokenStack::top().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc