NEST: nest::DynamicLoaderModule::UnloadModuleFunction Class Reference
nest::DynamicLoaderModule::UnloadModuleFunction Class Reference
#include <dynamicloader.h>
Public Member Functions
UnloadModuleFunction (Network *pNet, vecDynModules &dyn_modules)
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Private Member Functions
void execute (SLIInterpreter *) const
Private Attributes
Network * pNet_
vecDynModules & dyn_modules_
Constructor & Destructor Documentation
nest::DynamicLoaderModule::UnloadModuleFunction::UnloadModuleFunction (Network * pNet, vecDynModules & dyn_modules)
Member Function Documentation
void nest::DynamicLoaderModule::UnloadModuleFunction::execute (SLIInterpreter * i) const private virtual
Implements SLIFunction.
References SLIInterpreter::ArgumentTypeError, Token::datum(), numerics::e, SLIInterpreter::EStack, GenericDatum< D, slt >::get(), nest::Network::has_user_models(), TokenStack::load(), SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, SLIInterpreter::message(), SLIInterpreter::OStack, nest::DynamicLoaderModule::pNet_, TokenStack::pop(), SLIInterpreter::raiseerror(), SLIInterpreter::StackUnderflowError, TokenStack::top(), DynModule::unregister(), and SLIException::what().
Member Data Documentation
vecDynModules& nest::DynamicLoaderModule::UnloadModuleFunction::dyn_modules_ private
Network* nest::DynamicLoaderModule::UnloadModuleFunction::pNet_ private
The documentation for this class was generated from the following files:
dynamicloader.h
dynamicloader.cpp