NEST: nest::Connector< K, ConnectionT > Class Template Reference
nest::Connector< K, ConnectionT > Class Template Reference
#include <connector_base.h>
Public Member Functions
Connector (const Connector< K-1, ConnectionT > &Cm1, const ConnectionT &c)
~Connector ()
void get_synapse_status (synindex syn_id, DictionaryDatum &d, port p) const
void set_synapse_status (synindex syn_id, ConnectorModel &cm, const DictionaryDatum &d, port p)
size_t get_num_connections ()
size_t get_num_connections (synindex syn_id)
Connector< K+1, ConnectionT > & push_back (const ConnectionT &c)
void get_connections (size_t source_gid, size_t thrd, synindex synapse_id, ArrayDatum &conns) const
void get_connections (size_t source_gid, size_t target_gid, size_t thrd, size_t synapse_id, ArrayDatum &conns) const
void send (Event &e, thread t, const std::vector< ConnectorModel * > &cm)
void trigger_update_weight (long_t vt_gid, thread t, const vector< spikecounter > &dopa_spikes, double_t t_trig, const std::vector< ConnectorModel * > &cm)
synindex get_syn_id () const
const ConnectionT * get_C () const
bool homogeneous_model ()
Public Member Functions inherited from nest::ConnectorBase
ConnectorBase ()
virtual ~ConnectorBase ()
double_t get_t_lastspike () const
void set_t_lastspike (const double_t t_lastspike)
Private Attributes
ConnectionT C_ [K]
Constructor & Destructor Documentation
template<size_t K, typename ConnectionT> nest::Connector< K, ConnectionT >::Connector (const Connector< K-1, ConnectionT > & Cm1, const ConnectionT & c) inline
References nest::names::c, nest::Connector< K, ConnectionT >::C_, and nest::Connector< K, ConnectionT >::get_C().
template<size_t K, typename ConnectionT> nest::Connector< K, ConnectionT >::~Connector () inline
Member Function Documentation
template<size_t K, typename ConnectionT> const ConnectionT* nest::Connector< K, ConnectionT >::get_C () const inline
References nest::Connector< K, ConnectionT >::C_.
Referenced by nest::Connector< K, ConnectionT >::Connector(), and nest::Connector< K_cutoff, ConnectionT >::Connector().
template<size_t K, typename ConnectionT> void nest::Connector< K, ConnectionT >::get_connections (size_t source_gid, size_t thrd, synindex synapse_id, ArrayDatum & conns) const inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and TokenArray::push_back().
template<size_t K, typename ConnectionT> void nest::Connector< K, ConnectionT >::get_connections (size_t source_gid, size_t target_gid, size_t thrd, size_t synapse_id, ArrayDatum & conns) const inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and TokenArray::push_back().
template<size_t K, typename ConnectionT> size_t nest::Connector< K, ConnectionT >::get_num_connections () inline virtual
Implements nest::ConnectorBase.
template<size_t K, typename ConnectionT> size_t nest::Connector< K, ConnectionT >::get_num_connections (synindex syn_id) inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::get_syn_id().
template<size_t K, typename ConnectionT> synindex nest::Connector< K, ConnectionT >::get_syn_id () const inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_.
Referenced by nest::Connector< K, ConnectionT >::get_connections(), nest::Connector< 1, ConnectionT >::get_connections(), nest::Connector< K_cutoff, ConnectionT >::get_connections(), nest::Connector< K, ConnectionT >::get_num_connections(), nest::Connector< 1, ConnectionT >::get_num_connections(), nest::Connector< K_cutoff, ConnectionT >::get_num_connections(), nest::Connector< K, ConnectionT >::get_synapse_status(), nest::Connector< 1, ConnectionT >::get_synapse_status(), nest::Connector< K_cutoff, ConnectionT >::get_synapse_status(), nest::Connector< 1, ConnectionT >::send(), nest::Connector< K, ConnectionT >::set_synapse_status(), nest::Connector< 1, ConnectionT >::set_synapse_status(), and nest::Connector< K_cutoff, ConnectionT >::set_synapse_status().
template<size_t K, typename ConnectionT> void nest::Connector< K, ConnectionT >::get_synapse_status (synindex syn_id, DictionaryDatum & d, port p) const inline virtual
Implements nest::ConnectorBase.
References assert(), nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and nest::names::p.
template<size_t K, typename ConnectionT> bool nest::Connector< K, ConnectionT >::homogeneous_model () inline virtual
Implements nest::ConnectorBase.
template<size_t K, typename ConnectionT> Connector<K+1, ConnectionT>& nest::Connector< K, ConnectionT >::push_back (const ConnectionT & c) inline virtual
Implements nest::vector_like< ConnectionT >.
References nest::names::c.
template<size_t K, typename ConnectionT> void nest::Connector< K, ConnectionT >::send (Event & e, thread t, const std::vector< ConnectorModel * > & cm) inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::Time::get_ms(), nest::Event::get_stamp(), nest::ConnectorBase::get_t_lastspike(), nest::Event::set_port(), and nest::ConnectorBase::set_t_lastspike().
template<size_t K, typename ConnectionT> void nest::Connector< K, ConnectionT >::set_synapse_status (synindex syn_id, ConnectorModel & cm, const DictionaryDatum & d, port p) inline virtual
Implements nest::ConnectorBase.
References assert(), nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and nest::names::p.
template<size_t K, typename ConnectionT> void nest::Connector< K, ConnectionT >::trigger_update_weight (long_t vt_gid, thread t, const vector< spikecounter > & dopa_spikes, double_t t_trig, const std::vector< ConnectorModel * > & cm) inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_.
Referenced by nest::Connector< K_cutoff, ConnectionT >::trigger_update_weight().
Member Data Documentation
template<size_t K, typename ConnectionT> ConnectionT nest::Connector< K, ConnectionT >::C_[K] private
Referenced by nest::Connector< K, ConnectionT >::Connector(), nest::Connector< 1, ConnectionT >::Connector(), nest::Connector< K_cutoff, ConnectionT >::Connector(), nest::Connector< K, ConnectionT >::get_C(), nest::Connector< 1, ConnectionT >::get_C(), nest::Connector< K, ConnectionT >::get_connections(), nest::Connector< 1, ConnectionT >::get_connections(), nest::Connector< K_cutoff, ConnectionT >::get_connections(), nest::Connector< K_cutoff, ConnectionT >::get_num_connections(), nest::Connector< K, ConnectionT >::get_syn_id(), nest::Connector< 1, ConnectionT >::get_syn_id(), nest::Connector< K_cutoff, ConnectionT >::get_syn_id(), nest::Connector< K, ConnectionT >::get_synapse_status(), nest::Connector< 1, ConnectionT >::get_synapse_status(), nest::Connector< K_cutoff, ConnectionT >::get_synapse_status(), nest::Connector< K_cutoff, ConnectionT >::push_back(), nest::Connector< K, ConnectionT >::send(), nest::Connector< 1, ConnectionT >::send(), nest::Connector< K_cutoff, ConnectionT >::send(), nest::Connector< K, ConnectionT >::set_synapse_status(), nest::Connector< 1, ConnectionT >::set_synapse_status(), nest::Connector< K_cutoff, ConnectionT >::set_synapse_status(), nest::Connector< K, ConnectionT >::trigger_update_weight(), nest::Connector< 1, ConnectionT >::trigger_update_weight(), and nest::Connector< K_cutoff, ConnectionT >::trigger_update_weight().
The documentation for this class was generated from the following file:
connector_base.h