NEST: RandomNumbers Class Reference
RandomNumbers Class Reference
Provides random numbers and deviates to SLI.
#include <random_numbers.h>
Classes
class CreateRDVFunction
class CreateRNGFunction
class DrandFunction
class GetStatus_vFunction
class IrandFunction
class RandomArrayFunction
class RandomFunction
class SeedFunction
class SetStatus_vdFunction
Public Member Functions
RandomNumbers ()
~RandomNumbers ()
const std::string name (void) const
Return name of the module.
const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
void init (SLIInterpreter *)
Initializes the random number module.
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Static Public Member Functions
static const Dictionary & get_rngdict ()
Returns global random number generator dictionary.
static const Dictionary & get_rdvdict ()
Returns global random deviate generator dictionary.
Public Attributes
CreateRNGFunction createrngfunction
CreateRDVFunction createrdvfunction
SetStatus_vdFunction setstatus_vdfunction
GetStatus_vFunction getstatus_vfunction
SeedFunction seedfunction
IrandFunction irandfunction
DrandFunction drandfunction
RandomArrayFunction randomarrayfunction
RandomFunction randomfunction
Static Public Attributes
static SLIType RngType
static SLIType RngFactoryType
static SLIType RdvType
static SLIType RdvFactoryType
Private Member Functions
template<typename NumberGenerator >
void register_rng_ (const std::string &name, Dictionary &dict)
Utility function for registering number generators.
template<typename DeviateGenerator >
void register_rdv_ (const std::string &name, Dictionary &dict)
Utility function for registering deviate generators.
Static Private Attributes
static Dictionary * rngdict_ = 0
manages random number generators
static Dictionary * rdvdict_ = 0
manages random deviate generators
Detailed Description
Provides random numbers and deviates to SLI.
Constructor & Destructor Documentation
RandomNumbers::RandomNumbers () inline
RandomNumbers::~RandomNumbers ()
References SLIType::deletetypename(), RdvFactoryType, RdvType, RngFactoryType, and RngType.
Member Function Documentation
const std::string RandomNumbers::commandstring (void) const inline virtual
Return sli command sequence to be executed for initialisation.
Reimplemented from SLIModule.
const Dictionary & RandomNumbers::get_rdvdict () inline static
Returns global random deviate generator dictionary.
References assert(), and rdvdict_.
Referenced by nest::RandomParameter::RandomParameter().
const Dictionary & RandomNumbers::get_rngdict () inline static
Returns global random number generator dictionary.
References assert(), and rngdict_.
void RandomNumbers::init (SLIInterpreter * i) virtual
Initializes the random number module.
The random number generator and the random deviate generator dictionaries are set up.
Implements SLIModule.
References librandom::GslRandomGen::add_gsl_rngs(), assert(), SLIInterpreter::createcommand(), createrdvfunction, createrngfunction, SLIInterpreter::datatypefunction, SLIInterpreter::def(), drandfunction, getstatus_vfunction, irandfunction, randomarrayfunction, randomfunction, rdvdict_, RdvFactoryType, RdvType, rngdict_, RngFactoryType, RngType, seedfunction, SLIType::setdefaultaction(), setstatus_vdfunction, and SLIType::settypename().
const std::string RandomNumbers::name (void) const inline virtual
Return name of the module.
Implements SLIModule.
template<typename DeviateGenerator > void RandomNumbers::register_rdv_ (const std::string & name, Dictionary & dict) private
Utility function for registering deviate generators.
References Dictionary::insert_move().
template<typename NumberGenerator > void RandomNumbers::register_rng_ (const std::string & name, Dictionary & dict) private
Utility function for registering number generators.
Member Data Documentation
CreateRDVFunction RandomNumbers::createrdvfunction
Referenced by init().
CreateRNGFunction RandomNumbers::createrngfunction
Referenced by init().
DrandFunction RandomNumbers::drandfunction
Referenced by init().
GetStatus_vFunction RandomNumbers::getstatus_vfunction
Referenced by init().
IrandFunction RandomNumbers::irandfunction
Referenced by init().
RandomArrayFunction RandomNumbers::randomarrayfunction
Referenced by init().
RandomFunction RandomNumbers::randomfunction
Referenced by init().
Dictionary * RandomNumbers::rdvdict_ = 0 static private
manages random deviate generators
Referenced by get_rdvdict(), and init().
SLIType RandomNumbers::RdvFactoryType static
Referenced by init(), and ~RandomNumbers().
SLIType RandomNumbers::RdvType static
Referenced by init(), and ~RandomNumbers().
Dictionary * RandomNumbers::rngdict_ = 0 static private
manages random number generators
Referenced by get_rngdict(), and init().
SLIType RandomNumbers::RngFactoryType static
Referenced by init(), and ~RandomNumbers().
SLIType RandomNumbers::RngType static
Referenced by init(), and ~RandomNumbers().
SeedFunction RandomNumbers::seedfunction
Referenced by init().
SetStatus_vdFunction RandomNumbers::setstatus_vdfunction
Referenced by init().
The documentation for this class was generated from the following files:
random_numbers.h
random_numbers.cpp