NEST: nest::ConnectorModel Class Reference
nest::ConnectorModel Class Reference abstract
#include <connector_model.h>
Public Member Functions
ConnectorModel (Network &net, const std::string)
ConnectorModel (const ConnectorModel &, const std::string)
virtual ~ConnectorModel ()
size_t get_num_connections () const
const Time & get_min_delay () const
const Time & get_max_delay () const
void update_delay_extrema (const double_t mindelay_cand, const double_t maxdelay_cand)
virtual ConnectorBase * add_connection (Node &src, Node &tgt, ConnectorBase *conn, synindex syn_id, double_t delay=NAN, double_t weight=NAN)=0
NAN is a special value in cmath, which describes double values that are not a number.
virtual ConnectorBase * add_connection (Node &src, Node &tgt, ConnectorBase *conn, synindex syn_id, DictionaryDatum &d, double_t delay=NAN, double_t weight=NAN)=0
virtual ConnectorModel * clone (std::string) const =0
virtual void calibrate (const TimeConverter &tc)=0
virtual void get_status (DictionaryDatum &) const =0
virtual void set_status (const DictionaryDatum &)=0
virtual const
CommonSynapseProperties & get_common_properties () const =0
virtual void set_syn_id (synindex syn_id)=0
void assert_valid_delay_ms (double_t)
Raise exception if delay value in milliseconds is invalid.
void assert_two_valid_delays_steps (long_t, long_t)
Raise exception if either of the two delays in steps is invalid.
std::string get_name () const
bool get_user_set_delay_extrema () const
Network & network () const
Protected Attributes
Network & net_
The Network instance.
Time min_delay_
Minimal delay of all created synapses.
Time max_delay_
Maximal delay of all created synapses.
size_t num_connections_
The number of connections registered with this type.
bool default_delay_needs_check_
Flag indicating, that the default delay must be checked.
bool user_set_delay_extrema_
Flag indicating if the user set the delay extrema.
bool used_default_delay_
std::string name_
Constructor & Destructor Documentation
nest::ConnectorModel::ConnectorModel (Network & net, const std::string name)
nest::ConnectorModel::ConnectorModel (const ConnectorModel & cm, const std::string name)
References nest::Time::calibrate(), max_delay_, and min_delay_.
virtual nest::ConnectorModel::~ConnectorModel () inline virtual
Member Function Documentation
virtual ConnectorBase* nest::ConnectorModel::add_connection (Node & src, Node & tgt, ConnectorBase * conn, synindex syn_id, double_t delay = NAN, double_t weight = NAN) pure virtual
NAN is a special value in cmath, which describes double values that are not a number.
If delay or weight is omitted in an add_connection call, NAN indicates this and weight/delay are set only, if they are valid.
Implemented in nest::GenericConnectorModel< ConnectionT >.
virtual ConnectorBase* nest::ConnectorModel::add_connection (Node & src, Node & tgt, ConnectorBase * conn, synindex syn_id, DictionaryDatum & d, double_t delay = NAN, double_t weight = NAN) pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
void nest::ConnectorModel::assert_two_valid_delays_steps (long_t new_delay1, long_t new_delay2)
Raise exception if either of the two delays in steps is invalid.
Note
Setting continuous delays requires testing d and d+1. This function implements this more efficiently than two calls to assert_valid_delay().
This test accepts the delays in steps, as this makes more sense when working with continuous delays.
Not const, since it may update delay extrema as a side-effect.
References nest::Time::delay_steps_to_ms(), nest::Network::get_max_delay(), nest::Network::get_min_delay(), nest::Time::get_ms(), nest::Time::get_resolution(), nest::Network::get_simulated(), nest::Time::get_steps(), nest::names::max, max_delay_, nest::names::min, min_delay_, net_, update_delay_extrema(), and user_set_delay_extrema_.
Referenced by nest::ContDelayConnection< targetidentifierT >::set_status().
void nest::ConnectorModel::assert_valid_delay_ms (double_t requested_new_delay)
Raise exception if delay value in milliseconds is invalid.
Note
Not const, since it may update delay extrema as a side-effect.
References nest::Network::get_max_delay(), nest::Network::get_min_delay(), nest::Time::get_ms(), nest::Time::get_resolution(), nest::Network::get_simulated(), max_delay_, min_delay_, net_, nest::Time::step, update_delay_extrema(), and user_set_delay_extrema_.
Referenced by nest::ContDelayConnection< targetidentifierT >::set_status(), and nest::Connection< targetidentifierT >::set_status().
virtual void nest::ConnectorModel::calibrate (const TimeConverter & tc) pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
virtual ConnectorModel* nest::ConnectorModel::clone (std::string) const pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
virtual const CommonSynapseProperties& nest::ConnectorModel::get_common_properties () const pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
const Time& nest::ConnectorModel::get_max_delay () const inline
References max_delay_.
const Time& nest::ConnectorModel::get_min_delay () const inline
References min_delay_.
std::string nest::ConnectorModel::get_name () const inline
References name_.
size_t nest::ConnectorModel::get_num_connections () const inline
References num_connections_.
virtual void nest::ConnectorModel::get_status (DictionaryDatum &) const pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
bool nest::ConnectorModel::get_user_set_delay_extrema () const inline
References user_set_delay_extrema_.
Network& nest::ConnectorModel::network () const inline
References net_.
virtual void nest::ConnectorModel::set_status (const DictionaryDatum &) pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
virtual void nest::ConnectorModel::set_syn_id (synindex syn_id) pure virtual
Implemented in nest::GenericConnectorModel< ConnectionT >.
void nest::ConnectorModel::update_delay_extrema (const double_t mindelay_cand, const double_t maxdelay_cand)
References max_delay_, and min_delay_.
Referenced by assert_two_valid_delays_steps(), and assert_valid_delay_ms().
Member Data Documentation
bool nest::ConnectorModel::default_delay_needs_check_ protected
Flag indicating, that the default delay must be checked.
Time nest::ConnectorModel::max_delay_ protected
Maximal delay of all created synapses.
Referenced by assert_two_valid_delays_steps(), assert_valid_delay_ms(), ConnectorModel(), get_max_delay(), and update_delay_extrema().
Time nest::ConnectorModel::min_delay_ protected
Minimal delay of all created synapses.
Referenced by assert_two_valid_delays_steps(), assert_valid_delay_ms(), ConnectorModel(), get_min_delay(), and update_delay_extrema().
std::string nest::ConnectorModel::name_ protected
Referenced by get_name().
Network& nest::ConnectorModel::net_ protected
The Network instance.
Referenced by assert_two_valid_delays_steps(), assert_valid_delay_ms(), and network().
size_t nest::ConnectorModel::num_connections_ protected
The number of connections registered with this type.
Referenced by get_num_connections().
bool nest::ConnectorModel::used_default_delay_ protected
bool nest::ConnectorModel::user_set_delay_extrema_ protected
Flag indicating if the user set the delay extrema.
Referenced by assert_two_valid_delays_steps(), assert_valid_delay_ms(), and get_user_set_delay_extrema().
The documentation for this class was generated from the following files:
connector_model.h
connector_model.cpp