NEST: destructive_two_d_iterator< containertype > Class Template Reference
destructive_two_d_iterator< containertype > Class Template Reference
#include <sparsetable.h>
Public Types
typedef destructive_two_d_iterator iterator
typedef std::input_iterator_tag iterator_category
typedef containertype::value_type _tmp_vt
typedef _tmp_vt::value_type value_type
typedef _tmp_vt::difference_type difference_type
typedef _tmp_vt::reference reference
typedef _tmp_vt::pointer pointer
Public Member Functions
destructive_two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr)
destructive_two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr, typename containertype::value_type::TWOD_ITER_ col)
destructive_two_d_iterator ()
void advance_past_end ()
reference operator* () const
pointer operator-> () const
iterator & operator++ ()
iterator operator++ (int)
bool operator== (const iterator &it) const
bool operator!= (const iterator &it) const
Public Attributes
containertype::iterator row_begin
containertype::iterator row_end
containertype::iterator row_current
containertype::value_type::TWOD_ITER_ col_current
Member Typedef Documentation
template<class containertype > typedef containertype::value_type destructive_two_d_iterator< containertype >::_tmp_vt
template<class containertype > typedef _tmp_vt::difference_type destructive_two_d_iterator< containertype >::difference_type
template<class containertype > typedef destructive_two_d_iterator destructive_two_d_iterator< containertype >::iterator
template<class containertype > typedef std::input_iterator_tag destructive_two_d_iterator< containertype >::iterator_category
template<class containertype > typedef _tmp_vt::pointer destructive_two_d_iterator< containertype >::pointer
template<class containertype > typedef _tmp_vt::reference destructive_two_d_iterator< containertype >::reference
template<class containertype > typedef _tmp_vt::value_type destructive_two_d_iterator< containertype >::value_type
Constructor & Destructor Documentation
template<class containertype > destructive_two_d_iterator< containertype >::destructive_two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr) inline
References destructive_two_d_iterator< containertype >::advance_past_end(), and destructive_two_d_iterator< containertype >::col_current.
template<class containertype > destructive_two_d_iterator< containertype >::destructive_two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr, typename containertype::value_type::TWOD_ITER_ col) inline
References destructive_two_d_iterator< containertype >::advance_past_end().
template<class containertype > destructive_two_d_iterator< containertype >::destructive_two_d_iterator () inline
Member Function Documentation
template<class containertype > void destructive_two_d_iterator< containertype >::advance_past_end () inline
References destructive_two_d_iterator< containertype >::col_current, destructive_two_d_iterator< containertype >::row_current, and destructive_two_d_iterator< containertype >::row_end.
Referenced by destructive_two_d_iterator< containertype >::destructive_two_d_iterator(), and destructive_two_d_iterator< containertype >::operator++().
template<class containertype > bool destructive_two_d_iterator< containertype >::operator!= (const iterator & it) const inline
template<class containertype > reference destructive_two_d_iterator< containertype >::operator* () const inline
References destructive_two_d_iterator< containertype >::col_current.
Referenced by destructive_two_d_iterator< containertype >::operator->().
template<class containertype > iterator& destructive_two_d_iterator< containertype >::operator++ () inline
References destructive_two_d_iterator< containertype >::advance_past_end(), assert(), destructive_two_d_iterator< containertype >::col_current, destructive_two_d_iterator< containertype >::row_current, and destructive_two_d_iterator< containertype >::row_end.
template<class containertype > iterator destructive_two_d_iterator< containertype >::operator++ (int) inline
template<class containertype > pointer destructive_two_d_iterator< containertype >::operator-> () const inline
References destructive_two_d_iterator< containertype >::operator*().
template<class containertype > bool destructive_two_d_iterator< containertype >::operator== (const iterator & it) const inline
References destructive_two_d_iterator< containertype >::col_current, destructive_two_d_iterator< containertype >::row_begin, destructive_two_d_iterator< containertype >::row_current, and destructive_two_d_iterator< containertype >::row_end.
Member Data Documentation
template<class containertype > containertype::value_type::TWOD_ITER_ destructive_two_d_iterator< containertype >::col_current
Referenced by destructive_two_d_iterator< containertype >::advance_past_end(), destructive_two_d_iterator< containertype >::destructive_two_d_iterator(), destructive_two_d_iterator< containertype >::operator*(), destructive_two_d_iterator< containertype >::operator++(), and destructive_two_d_iterator< containertype >::operator==().
template<class containertype > containertype::iterator destructive_two_d_iterator< containertype >::row_begin
Referenced by destructive_two_d_iterator< containertype >::operator==().
template<class containertype > containertype::iterator destructive_two_d_iterator< containertype >::row_current
Referenced by destructive_two_d_iterator< containertype >::advance_past_end(), destructive_two_d_iterator< containertype >::operator++(), and destructive_two_d_iterator< containertype >::operator==().
template<class containertype > containertype::iterator destructive_two_d_iterator< containertype >::row_end
Referenced by destructive_two_d_iterator< containertype >::advance_past_end(), destructive_two_d_iterator< containertype >::operator++(), and destructive_two_d_iterator< containertype >::operator==().
The documentation for this class was generated from the following file:
sparsetable.h