NEST: nest::Archiving_Node Class Reference
nest::Archiving_Node Class Reference
a node which archives spike history for the purposes of timing dependent plasticity
#include <archiving_node.h>
Public Member Functions
Archiving_Node ()
Constructor.
Archiving_Node (const Archiving_Node &)
double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
double_t get_triplet_K_value (const std::deque< histentry >::iterator &iter)
return the triplet Kminus value for the associated iterator.
void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike times (in steps) of spikes which occurred in the range (t1,t2].
void register_stdp_connection (double_t t_first_read)
Register a new incoming STDP connection.
void unregister_stdp_connection (double_t t_last_read)
Unregister this incoming connection.
void get_status (DictionaryDatum &d) const
void set_status (const DictionaryDatum &d)
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool has_proxies () const
Returns true if the node has proxies on remote threads.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool local_receiver () const
Returns true if the node only receives events from nodes/devices on the same thread.
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
virtual std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void calibrate ()=0
Re-calculate dependent parameters of the node.
virtual void finalize ()
Finalize node.
virtual void update (Time const &, const long_t, const long_t)=0
Bring the node from state $t$ to $t+n*dt$.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port send_test_event (Node &receiving_node, rport receptor_type, synindex syn_id, bool dummy_target)
Send an event to the receiving_node passed as an argument.
virtual port handles_test_event (SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (DataLoggingRequest &, rport receptor_type)
virtual port handles_test_event (CurrentEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void handle (SpikeEvent &e)
Handle incoming spike events.
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingRequest &e)
Handler for universal data logging request.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (CurrentEvent &e)
Handler for current events.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
virtual void event_hook (DSCurrentEvent &)
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
virtual bool is_subnet () const
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Protected Member Functions
void set_spiketime (Time const &t_sp)
record spike history
double_t get_spiketime_ms () const
void clear_history ()
clear spike history
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
virtual void init_state_ (Node const &)=0
Private function to initialize the state of a node to model defaults.
virtual void init_buffers_ ()=0
Private function to initialize the buffers of a node.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Private Attributes
size_t n_incoming_
double_t Kminus_
double_t triplet_Kminus_
double_t tau_minus_
double_t tau_minus_triplet_
double_t last_spike_
std::deque< histentry > history_
Additional Inherited Members
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Detailed Description
a node which archives spike history for the purposes of timing dependent plasticity
Constructor & Destructor Documentation
nest::Archiving_Node::Archiving_Node ()
Constructor.
Copy Constructor.
nest::Archiving_Node::Archiving_Node (const Archiving_Node & n)
Member Function Documentation
void nest::Archiving_Node::clear_history () protected
clear spike history
Referenced by nest::binary_neuron< TGainfunction >::init_buffers_(), nest::iaf_psc_exp_multisynapse::init_buffers_(), nest::iaf_psc_alpha_multisynapse::init_buffers_(), nest::parrot_neuron::init_buffers_(), nest::aeif_cond_alpha_multisynapse::init_buffers_(), nest::iaf_chs_2007::init_buffers_(), nest::izhikevich::init_buffers_(), nest::iaf_cond_exp::init_buffers_(), nest::sli_neuron::init_buffers_(), nest::volume_transmitter::init_buffers_(), nest::aeif_cond_alpha_RK5::init_buffers_(), nest::iaf_chxk_2008::init_buffers_(), nest::hh_cond_exp_traub::init_buffers_(), nest::iaf_cond_exp_sfa_rr::init_buffers_(), nest::iaf_cond_alpha::init_buffers_(), nest::iaf_psc_exp::init_buffers_(), nest::aeif_cond_alpha::init_buffers_(), nest::iaf_neuron::init_buffers_(), nest::iaf_psc_delta::init_buffers_(), nest::mat2_psc_exp::init_buffers_(), nest::aeif_cond_exp::init_buffers_(), nest::iaf_psc_alpha::init_buffers_(), nest::iaf_tum_2000::init_buffers_(), nest::ht_neuron::init_buffers_(), nest::amat2_psc_exp::init_buffers_(), nest::hh_psc_alpha::init_buffers_(), nest::pp_psc_delta::init_buffers_(), nest::pp_pop_psc_delta::init_buffers_(), and nest::iaf_cond_alpha_mc::init_buffers_().
void nest::Archiving_Node::get_history (double_t t1, double_t t2, std::deque< histentry >::iterator * start, std::deque< histentry >::iterator * finish) virtual
return the spike times (in steps) of spikes which occurred in the range (t1,t2].
Reimplemented from nest::Node.
double_t nest::Archiving_Node::get_K_value (double_t t) virtual
return the Kminus value at t (in ms).
Reimplemented from nest::Node.
void nest::Archiving_Node::get_K_values (double_t t, double_t & Kminus, double_t & triplet_Kminus) virtual
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
Exceptions
UnexpectedEvent
Reimplemented from nest::Node.
double_t nest::Archiving_Node::get_spiketime_ms () const inline protected
References last_spike_.
Referenced by nest::parrot_neuron::get_status(), and nest::hh_cond_exp_traub::get_status().
void nest::Archiving_Node::get_status (DictionaryDatum & d) const
References nest::names::archiver_length, nest::names::d, nest::names::t_spike, nest::names::tau_minus, and nest::names::tau_minus_triplet.
Referenced by nest::binary_neuron< TGainfunction >::get_status(), nest::iaf_psc_exp_multisynapse::get_status(), nest::iaf_psc_alpha_multisynapse::get_status(), nest::aeif_cond_alpha_multisynapse::get_status(), nest::iaf_chs_2007::get_status(), nest::izhikevich::get_status(), nest::sli_neuron::get_status(), nest::iaf_cond_exp::get_status(), nest::volume_transmitter::get_status(), nest::aeif_cond_alpha_RK5::get_status(), nest::iaf_chxk_2008::get_status(), nest::hh_cond_exp_traub::get_status(), nest::iaf_cond_exp_sfa_rr::get_status(), nest::iaf_cond_alpha::get_status(), nest::iaf_psc_exp::get_status(), nest::aeif_cond_alpha::get_status(), nest::iaf_neuron::get_status(), nest::ht_neuron::get_status(), nest::iaf_psc_delta::get_status(), nest::mat2_psc_exp::get_status(), nest::aeif_cond_exp::get_status(), nest::iaf_psc_alpha::get_status(), nest::iaf_tum_2000::get_status(), nest::amat2_psc_exp::get_status(), nest::hh_psc_alpha::get_status(), nest::pp_psc_delta::get_status(), nest::pp_pop_psc_delta::get_status(), and nest::iaf_cond_alpha_mc::get_status().
double_t nest::Archiving_Node::get_triplet_K_value (const std::deque< histentry >::iterator & iter)
return the triplet Kminus value for the associated iterator.
void nest::Archiving_Node::register_stdp_connection (double_t t_first_read) virtual
Register a new incoming STDP connection.
t_first_read: The newly registered synapse will read the history entries with t > t_first_read.
Reimplemented from nest::Node.
References history_, and n_incoming_.
void nest::Archiving_Node::set_spiketime (Time const & t_sp) protected
record spike history
References nest::Time::get_ms().
Referenced by nest::iaf_psc_exp_multisynapse::update(), nest::iaf_psc_alpha_multisynapse::update(), nest::parrot_neuron::update(), nest::aeif_cond_alpha_multisynapse::update(), nest::iaf_psc_alpha::update(), and nest::ht_neuron::update().
void nest::Archiving_Node::set_status (const DictionaryDatum & d)
References nest::names::clear, clear_history(), nest::names::d, nest::names::tau_minus, and nest::names::tau_minus_triplet.
Referenced by nest::binary_neuron< TGainfunction >::set_status(), nest::iaf_psc_exp_multisynapse::set_status(), nest::iaf_psc_alpha_multisynapse::set_status(), nest::parrot_neuron::set_status(), nest::aeif_cond_alpha_multisynapse::set_status(), nest::iaf_chs_2007::set_status(), nest::izhikevich::set_status(), nest::sli_neuron::set_status(), nest::iaf_cond_exp::set_status(), nest::volume_transmitter::set_status(), nest::aeif_cond_alpha_RK5::set_status(), nest::iaf_chxk_2008::set_status(), nest::hh_cond_exp_traub::set_status(), nest::iaf_cond_exp_sfa_rr::set_status(), nest::iaf_cond_alpha::set_status(), nest::iaf_psc_exp::set_status(), nest::aeif_cond_alpha::set_status(), nest::iaf_neuron::set_status(), nest::ht_neuron::set_status(), nest::iaf_psc_delta::set_status(), nest::mat2_psc_exp::set_status(), nest::aeif_cond_exp::set_status(), nest::iaf_psc_alpha::set_status(), nest::iaf_tum_2000::set_status(), nest::amat2_psc_exp::set_status(), nest::hh_psc_alpha::set_status(), nest::pp_psc_delta::set_status(), nest::pp_pop_psc_delta::set_status(), and nest::iaf_cond_alpha_mc::set_status().
void nest::Archiving_Node::unregister_stdp_connection (double_t t_last_read) virtual
Unregister this incoming connection.
t_last_read: The unregistered synapse has read all history entries with t <= t_last_read.
Reimplemented from nest::Node.
References history_, and n_incoming_.
Member Data Documentation
std::deque<histentry> nest::Archiving_Node::history_ private
Referenced by register_stdp_connection(), and unregister_stdp_connection().
double_t nest::Archiving_Node::Kminus_ private
double_t nest::Archiving_Node::last_spike_ private
Referenced by get_spiketime_ms().
size_t nest::Archiving_Node::n_incoming_ private
Referenced by register_stdp_connection(), and unregister_stdp_connection().
double_t nest::Archiving_Node::tau_minus_ private
double_t nest::Archiving_Node::tau_minus_triplet_ private
double_t nest::Archiving_Node::triplet_Kminus_ private
The documentation for this class was generated from the following files:
archiving_node.h
archiving_node.cpp