NEST: Sleep_dFunction Class Reference
Sleep_dFunction Class Reference
#include <slicontrol.h>
Public Member Functions
Sleep_dFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
Sleep_dFunction::Sleep_dFunction () inline
Member Function Documentation
void Sleep_dFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, SLIInterpreter::OStack, TokenStack::pick(), and TokenStack::pop().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc