NEST: nest::NestModule Class Reference
nest::NestModule Class Reference
SLI interface of the NEST kernel.
#include <nestmodule.h>
Classes
class ChangeSubnet_iFunction
class Connect_g_g_D_DFunction
class Connect_i_i_d_d_lFunction
class Connect_i_i_D_lFunction
class Connect_i_i_lFunction
class ConvergentConnect_ia_i_a_a_lFunction
class CopyModel_l_l_DFunction
class Create_l_iFunction
class CurrentSubnetFunction
class Cva_CFunction
class Cvdict_CFunction
class Cvgidcollection_i_iFunction
class Cvgidcollection_iaFunction
class Cvgidcollection_ivFunction
class DataConnect_aFunction
class DataConnect_i_D_sFunction
class DivergentConnect_i_ia_a_a_lFunction
class GetChildren_i_D_bFunction
class GetConnections_DFunction
class GetDefaults_lFunction
class GetGlobalRngFunction
class GetLeaves_i_D_bFunction
class GetNodes_i_D_b_bFunction
class GetStatus_aFunction
class GetStatus_CFunction
class GetStatus_iFunction
class GetVpRngFunction
class MemoryInfoFunction
class MPIAbort_iFunction
class NumProcessesFunction
class PrintNetworkFunction
class ProcessorNameFunction
class RankFunction
class RConvergentConnect_ia_i_i_da_da_b_b_lFunction
class RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction
class RDivergentConnect_i_i_ia_da_da_b_b_lFunction
class ResetKernelFunction
class ResetNetworkFunction
class RestoreNodes_aFunction
class ResumeSimulationFunction
class SetAcceptableLatencyFunction
class SetDefaults_l_DFunction
class SetFakeNumProcessesFunction_i
class SetMaxBufferedFunction
class SetNumRecProcessesFunction_i
class SetStatus_aaFunction
class SetStatus_CDFunction
class SetStatus_idFunction
class SimulateFunction
class Size_gFunction
class SyncProcessesFunction
class TimeCommunication_i_i_bFunction
class TimeCommunicationAlltoall_i_iFunction
class TimeCommunicationAlltoallv_i_iFunction
class TimeCommunicationv_i_iFunction
Public Member Functions
NestModule ()
~NestModule ()
void init (SLIInterpreter *)
Initialise the module.
const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
const std::string name (void) const
Return name of the module.
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Static Public Member Functions
static void register_network (Network &)
Set pointer to network.
static Network & get_network ()
Return a reference to the network managed by nestmodule.
static index get_num_threads ()
Get number of threads.
Public Attributes
nest::NestModule::ChangeSubnet_iFunction changesubnet_ifunction
nest::NestModule::CurrentSubnetFunction currentsubnetfunction
nest::NestModule::GetNodes_i_D_b_bFunction getnodes_i_D_b_bfunction
nest::NestModule::GetLeaves_i_D_bFunction getleaves_i_D_bfunction
nest::NestModule::GetChildren_i_D_bFunction getchildren_i_D_bfunction
nest::NestModule::GetStatus_iFunction getstatus_ifunction
nest::NestModule::GetStatus_CFunction getstatus_Cfunction
nest::NestModule::GetStatus_aFunction getstatus_afunction
nest::NestModule::SetStatus_idFunction setstatus_idfunction
nest::NestModule::SetStatus_CDFunction setstatus_CDfunction
nest::NestModule::Cva_CFunction cva_cfunction
nest::NestModule::SetStatus_aaFunction setstatus_aafunction
nest::NestModule::SetDefaults_l_DFunction setdefaults_l_Dfunction
nest::NestModule::GetDefaults_lFunction getdefaults_lfunction
nest::NestModule::CopyModel_l_l_DFunction copymodel_l_l_Dfunction
nest::NestModule::GetConnections_DFunction getconnections_Dfunction
nest::NestModule::SimulateFunction simulatefunction
nest::NestModule::ResumeSimulationFunction resumesimulationfunction
nest::NestModule::Create_l_iFunction create_l_ifunction
nest::NestModule::RestoreNodes_aFunction restorenodes_afunction
nest::NestModule::DataConnect_i_D_sFunction dataconnect_i_D_sfunction
nest::NestModule::DataConnect_aFunction dataconnect_afunction
nest::NestModule::Connect_i_i_lFunction connect_i_i_lfunction
nest::NestModule::Connect_i_i_d_d_lFunction connect_i_i_d_d_lfunction
nest::NestModule::Connect_i_i_D_lFunction connect_i_i_D_lfunction
nest::NestModule::Connect_g_g_D_DFunction connect_g_g_D_Dfunction
nest::NestModule::DivergentConnect_i_ia_a_a_lFunction divergentconnect_i_ia_a_a_lfunction
nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction rdivergentconnect_i_i_ia_da_da_b_b_lfunction
nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction convergentconnect_ia_i_a_a_lfunction
nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction rconvergentconnect_ia_i_i_da_da_b_b_lfunction
nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction rconvergentconnect_ia_ia_ia_daa_daa_b_b_lfunction
nest::NestModule::ResetKernelFunction resetkernelfunction
nest::NestModule::ResetNetworkFunction resetnetworkfunction
nest::NestModule::MemoryInfoFunction memoryinfofunction
nest::NestModule::PrintNetworkFunction printnetworkfunction
nest::NestModule::RankFunction rankfunction
nest::NestModule::NumProcessesFunction numprocessesfunction
nest::NestModule::SetFakeNumProcessesFunction_i setfakenumprocesses_ifunction
nest::NestModule::SetNumRecProcessesFunction_i setnumrecprocesses_ifunction
nest::NestModule::SyncProcessesFunction syncprocessesfunction
nest::NestModule::TimeCommunication_i_i_bFunction timecommunication_i_i_bfunction
nest::NestModule::TimeCommunicationv_i_iFunction timecommunicationv_i_ifunction
nest::NestModule::TimeCommunicationAlltoall_i_iFunction timecommunicationalltoall_i_ifunction
nest::NestModule::TimeCommunicationAlltoallv_i_iFunction timecommunicationalltoallv_i_ifunction
nest::NestModule::ProcessorNameFunction processornamefunction
nest::NestModule::MPIAbort_iFunction mpiabort_ifunction
nest::NestModule::GetVpRngFunction getvprngfunction
nest::NestModule::GetGlobalRngFunction getglobalrngfunction
nest::NestModule::Cvdict_CFunction cvdict_Cfunction
nest::NestModule::Cvgidcollection_i_iFunction cvgidcollection_i_ifunction
nest::NestModule::Cvgidcollection_iaFunction cvgidcollection_iafunction
nest::NestModule::Cvgidcollection_ivFunction cvgidcollection_ivfunction
nest::NestModule::Size_gFunction size_gfunction
nest::NestModule::SetAcceptableLatencyFunction setacceptablelatency_l_dfunction
nest::NestModule::SetMaxBufferedFunction setmaxbuffered_l_ifunction
Static Public Attributes
static SLIType ConnectionType
static SLIType GIDCollectionType
Static Private Attributes
static Network * net_ = 0
Pointer to network.
Detailed Description
SLI interface of the NEST kernel.
This class implements the SLI functions which connect the NEST kernel with the interpreter.
Constructor & Destructor Documentation
nest::NestModule::NestModule ()
References assert(), and net_.
nest::NestModule::~NestModule ()
References ConnectionType, SLIType::deletetypename(), and GIDCollectionType.
Member Function Documentation
const std::string nest::NestModule::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Reimplemented from SLIModule.
void nest::NestModule::init (SLIInterpreter *) virtual
Initialise the module.
When this function is called, most of the interpreter's fascilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialised, not all services may be available.
Implements SLIModule.
References assert(), SLIInterpreter::baselookup(), nest::Network::calibrate_clock(), changesubnet_ifunction, connect_g_g_D_Dfunction, connect_i_i_d_d_lfunction, connect_i_i_D_lfunction, connect_i_i_lfunction, ConnectionType, convergentconnect_ia_i_a_a_lfunction, copymodel_l_l_Dfunction, create_l_ifunction, SLIInterpreter::createcommand(), currentsubnetfunction, cva_cfunction, cvdict_Cfunction, cvgidcollection_i_ifunction, cvgidcollection_iafunction, cvgidcollection_ivfunction, dataconnect_afunction, dataconnect_i_D_sfunction, SLIInterpreter::datatypefunction, divergentconnect_i_ia_a_a_lfunction, nest::Communicator::get_initialized(), getchildren_i_D_bfunction, getconnections_Dfunction, getdefaults_lfunction, getglobalrngfunction, getleaves_i_D_bfunction, getnodes_i_D_b_bfunction, getstatus_afunction, getstatus_Cfunction, getstatus_ifunction, getvprngfunction, GIDCollectionType, memoryinfofunction, mpiabort_ifunction, net_, numprocessesfunction, printnetworkfunction, processornamefunction, rankfunction, rconvergentconnect_ia_i_i_da_da_b_b_lfunction, rconvergentconnect_ia_ia_ia_daa_daa_b_b_lfunction, rdivergentconnect_i_i_ia_da_da_b_b_lfunction, nest::Network::register_conn_builder(), nest::Time::reset_resolution(), resetkernelfunction, resetnetworkfunction, restorenodes_afunction, resumesimulationfunction, setacceptablelatency_l_dfunction, SLIType::setdefaultaction(), setdefaults_l_Dfunction, setfakenumprocesses_ifunction, setmaxbuffered_l_ifunction, setnumrecprocesses_ifunction, setstatus_aafunction, setstatus_CDfunction, setstatus_idfunction, SLIType::settypename(), simulatefunction, size_gfunction, syncprocessesfunction, timecommunication_i_i_bfunction, timecommunicationalltoall_i_ifunction, timecommunicationalltoallv_i_ifunction, and timecommunicationv_i_ifunction.
const std::string nest::NestModule::name (void) const virtual
Return name of the module.
Implements SLIModule.
void nest::NestModule::register_network (Network & net) static
Set pointer to network.
This function sets the pointer to the network which NestModule shall manage. It must be called once, and before NestModule is constructed.
Parameters
Network& Th network to manage
Note
One should find a cleaner solution, more in keeping with the initialization of dynamic modules. HEP
References assert(), and net_.
Member Data Documentation
SLIType nest::NestModule::ConnectionType static
Referenced by init(), and ~NestModule().
SLIType nest::NestModule::GIDCollectionType static
Referenced by init(), and ~NestModule().
Network * nest::NestModule::net_ = 0 static private
Pointer to network.
Note
- net must be initialized before NestModule is constructed.
net must be static, so that the execute() members of the SliFunction classes in the module can access the network.
net is, however, dynamic in order to avoid the static-initialization problem, i.e., the undefined initialization order of static variables across compilation units.
Referenced by get_network(), get_num_threads(), init(), NestModule(), and register_network().
The documentation for this class was generated from the following files:
nestmodule.h
nestmodule.cpp