NEST: GNUReadline Class Reference
GNUReadline Class Reference
#include <gnureadline.h>
Classes
class GNUAddhistoryFunction
class GNUReadlineFunction
Public Member Functions
GNUReadline ()
~GNUReadline ()
const std::string name (void) const
Return name of the module.
void init (SLIInterpreter *)
Initialise the module.
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
virtual const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Public Attributes
GNUReadlineFunction gnureadlinefunction
GNUAddhistoryFunction gnuaddhistoryfunction
Constructor & Destructor Documentation
GNUReadline::GNUReadline () inline
GNUReadline::~GNUReadline ()
References clear_history().
Member Function Documentation
void GNUReadline::init (SLIInterpreter *) virtual
Initialise the module.
When this function is called, most of the interpreter's fascilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialised, not all services may be available.
Implements SLIModule.
References SLIInterpreter::createcommand(), gnuaddhistoryfunction, gnureadlinefunction, read_history(), and using_history().
const std::string GNUReadline::name (void) const inline virtual
Return name of the module.
Implements SLIModule.
Member Data Documentation
GNUAddhistoryFunction GNUReadline::gnuaddhistoryfunction
Referenced by init().
GNUReadlineFunction GNUReadline::gnureadlinefunction
Referenced by init().
The documentation for this class was generated from the following files:
gnureadline.h
gnureadline.cc