NEST: Dictionary Class Reference
Dictionary Class Reference
Handling classes Token and Dictionary.
A class that associates names and tokens.
#include <dict.h>
Classes
class DictItemLexicalOrder
Helper class for lexicographical sorting of dictionary entries.
Public Types
typedef TokenMap::const_iterator const_iterator
Constant iterator for dictionary.
Public Member Functions
Dictionary ()
Dictionary (const Dictionary &d)
~Dictionary ()
void clear ()
const Token & lookup (const Name &n) const
Lookup and return Token with given name in dictionary.
const Token & lookup2 (const Name &n) const
lookup a name in the dictionary.
bool known (const Name &) const
bool known_but_not_accessed (const Name &) const
Returns true if name is known but token has not been accessed.
Token & insert (const Name &n, const Token &t)
Token & insert_move (const Name &, Token &)
void remove (const Name &n)
Remove entry from dictionary.
const Token & operator[] (const Name &) const
Token & operator[] (const Name &)
const Token & operator[] (const char *) const
Token & operator[] (const char *)
bool empty (void) const
void info (std::ostream &) const
bool operator== (const Dictionary &d) const
void add_dict (const std::string &, SLIInterpreter &)
Add the contents of this dictionary to another.
void remove_dict (const std::string &, SLIInterpreter &)
Remove entries found in another dictionary from this.
void clear_access_flags ()
Clear access flags on all dictionary elements.
bool all_accessed (std::string &missed) const
Check whether all elements have been accessed.
void initialize_property_array (Name propname)
First element in dictionary.
void add_dictstack_reference ()
This function is called when a dictionary is pushed to the dictionary stack.
void remove_dictstack_reference ()
This function is called when the dictionary is popped from the dictionary stack.
bool is_on_dictstack () const
Returns true, if the dictionary has references on the dictionary stack.
Private Member Functions
bool all_accessed_ (std::string &, std::string prefix=std::string()) const
Private Attributes
int refs_on_dictstack_
Worker function checking whether all elements have been accessed.
Static Private Attributes
static const Token VoidToken
Friends
std::ostream & operator<< (std::ostream &, const Dictionary &)
Detailed Description
A class that associates names and tokens.
Member Typedef Documentation
typedef TokenMap::const_iterator Dictionary::const_iterator
Constant iterator for dictionary.
Dictionary inherits privately from std::map to hide implementation details. To allow for inspection of all elements in a dictionary, we export the constant iterator type and begin() and end() methods.
Constructor & Destructor Documentation
Dictionary::Dictionary () inline
Dictionary::Dictionary (const Dictionary & d) inline
Dictionary::~Dictionary ()
Member Function Documentation
void Dictionary::add_dict (const std::string & target, SLIInterpreter & i)
Add the contents of this dictionary to another.
The target dictionary is given by names and must be retrieved via the interpreter.
Todo:
Allow for free formatting of target dictionary entries via functor, and add traits to allow duplicates.
See also
remove_dict
References SLIInterpreter::baselookup(), and nest::names::d.
void Dictionary::add_dictstack_reference () inline
This function is called when a dictionary is pushed to the dictionary stack.
The dictioray stack must keep track about which dictioraries are on the dictionary stack. If a dictionary is modified and it is on the dictionary stack, the cache of the dictionary stack must be adjusted. This is e.g. the case for the systemdict or the errordict.
References refs_on_dictstack_.
bool Dictionary::all_accessed (std::string & missed) const inline
Check whether all elements have been accessed.
Checks nested dictionaries recursively.
Parameters
std::string& contains string with names of non-accessed entries
Returns
true if all dictionary elements have been accessed
Note
this is just a wrapper, all_accessed_() does the work, hides recursion
See also
clear_access_flags(), all_accessed_()
References all_accessed_().
Referenced by nest::register_preconf_model().
bool Dictionary::all_accessed_ (std::string & missed, std::string prefix = std::string()) const private
Referenced by all_accessed().
void Dictionary::clear ()
References nest::names::clear, clear(), nest::names::d, nest::names::dt, lockPTR< D >::get(), and lockPTR< D >::unlock().
Referenced by clear(), and nest::Network::clear_models_().
void Dictionary::clear_access_flags ()
Clear access flags on all dictionary elements.
Flags for nested dictionaries are cleared recursively.
See also
all_accessed()
Referenced by nest::register_preconf_model().
bool Dictionary::empty (void) const inline
void Dictionary::info (std::ostream & out) const
void Dictionary::initialize_property_array (Name propname)
First element in dictionary.
Dictionary inherits privately from std::map to hide implementation details. To allow for inspection of all elements in a dictionary, we export the constant iterator type and begin() and end() methods. One-past-last element in dictionary. Dictionary inherits privately from std::map to hide implementation details. To allow for inspection of all elements in a dictionary, we export the constant iterator type and begin() and end() methods.
Token & Dictionary::insert (const Name & n, const Token & t) inline
Referenced by nest::Network::copy_model(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), RegexpModule::init(), Processes::init(), nest::Network::init_(), SLIInterpreter::raiseagain(), SLIInterpreter::raiseerror(), SLIInterpreter::raisesignal(), nest::Network::register_conn_builder(), nest::Network::register_model(), and SLIInterpreter::SLIInterpreter().
Token & Dictionary::insert_move (const Name & n, Token & t) inline
References Token::move().
Referenced by librandom::GslRandomGen::add_gsl_rngs(), SLIInterpreter::raiseerror(), and RandomNumbers::register_rdv_().
bool Dictionary::is_on_dictstack () const inline
Returns true, if the dictionary has references on the dictionary stack.
References refs_on_dictstack_.
bool Dictionary::known (const Name & n) const inline
Referenced by librandom::GslRandomGen::add_gsl_rngs(), nest::ConnBuilder::ConnBuilder(), nest::Network::connect(), nest::Network::copy_model(), nest::NestModule::CopyModel_l_l_DFunction::execute(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), SLIInterpreter::print_error(), SLIInterpreter::raiseagain(), nest::RandomParameter::RandomParameter(), nest::Network::register_basis_model(), nest::Network::register_conn_builder(), nest::Network::register_model(), and SLIInterpreter::terminate().
bool Dictionary::known_but_not_accessed (const Name & n) const inline
Returns true if name is known but token has not been accessed.
const Token & Dictionary::lookup (const Name & n) const inline
Lookup and return Token with given name in dictionary.
If the name is not found, an empty token is returned. This version of lookup is deprecated and will disappear in future versions. Please use lookup2() instead.
Note
The token returned should always be stored as a const &, so that the control flag for dictionary read-out is set on the Token in the dictionary, not its copy.
References VoidToken.
Referenced by nest::ConnectionCreator::ConnectionCreator(), nest::AbstractLayer::create_layer(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute(), SLIInterpreter::print_error(), SLIInterpreter::raiseagain(), SLIInterpreter::raiseerror(), and nest::Selector::Selector().
const Token & Dictionary::lookup2 (const Name & n) const inline
lookup a name in the dictionary.
If the name is not found an UndefinedName exception is thrown. lookup2 is the preferred way to retrieve entries from the dictionary.
Note
The token returned should always be stored as a const &, so that the control flag for dictionary read-out is set on the Token in the dictionary, not its copy.
References Name::toString().
bool Dictionary::operator== (const Dictionary & d) const inline
References operator==().
const Token & Dictionary::operator[] (const Name & n) const inline
References Name::toString().
Referenced by operator[]().
Token & Dictionary::operator[] (const Name & n) inline
const Token & Dictionary::operator[] (const char * n) const
References operator[]().
Token & Dictionary::operator[] (const char * n)
References operator[]().
void Dictionary::remove (const Name & n)
Remove entry from dictionary.
Referenced by nest::Network::unregister_model().
void Dictionary::remove_dict (const std::string & target, SLIInterpreter & i)
Remove entries found in another dictionary from this.
See also
add_dict
References SLIInterpreter::baselookup(), and nest::names::d.
void Dictionary::remove_dictstack_reference () inline
This function is called when the dictionary is popped from the dictionary stack.
References refs_on_dictstack_.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & out, const Dictionary & d) friend
Member Data Documentation
int Dictionary::refs_on_dictstack_ private
Worker function checking whether all elements have been accessed.
Checks nested dictionaries recursively.
Parameters
std::string& contains string with names of non-accessed entries
std::string prefix for nested dictionary entries, built during recursion
Returns
true if all dictionary elements have been accessed
Note
this is just the worker for all_accessed()
See also
clear_access_flags(), all_accessed()
Referenced by add_dictstack_reference(), is_on_dictstack(), and remove_dictstack_reference().
const Token Dictionary::VoidToken static private
Referenced by lookup().
The documentation for this class was generated from the following files:
dict.h
dict.cc