NEST: nest::STDPConnection< targetidentifierT > Class Template Reference
nest::STDPConnection< targetidentifierT > Class Template Reference
#include <stdp_connection.h>
Classes
class ConnTestDummyNode
Public Types
typedef CommonSynapseProperties CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
STDPConnection ()
Default Constructor.
STDPConnection (const STDPConnection &)
Copy constructor.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t t_lastspike, const CommonSynapseProperties &cp)
Send an event to the receiver of this connection.
void check_connection (Node &s, Node &t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &)
void set_weight (double_t w)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Member Functions
double_t facilitate_ (double_t w, double_t kplus)
double_t depress_ (double_t w, double_t kminus)
Private Attributes
double_t weight_
double_t tau_plus_
double_t lambda_
double_t alpha_
double_t mu_plus_
double_t mu_minus_
double_t Wmax_
double_t Kplus_
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Member Typedef Documentation
template<typename targetidentifierT> typedef CommonSynapseProperties nest::STDPConnection< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT> typedef Connection<targetidentifierT> nest::STDPConnection< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::STDPConnection< targetidentifierT >::STDPConnection ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::STDPConnection< targetidentifierT >::STDPConnection (const STDPConnection< targetidentifierT > & rhs)
Copy constructor.
Needs to be defined properly in order for GenericConnector to work.
Member Function Documentation
template<typename targetidentifierT> void nest::STDPConnection< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_(), nest::Connection< targetidentifierT >::get_delay(), and nest::Node::register_stdp_connection().
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::depress_ (double_t w, double_t kminus) inline private
References nest::STDPConnection< targetidentifierT >::alpha_, nest::STDPConnection< targetidentifierT >::lambda_, nest::STDPConnection< targetidentifierT >::mu_minus_, and nest::STDPConnection< targetidentifierT >::Wmax_.
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::facilitate_ (double_t w, double_t kplus) inline private
References nest::STDPConnection< targetidentifierT >::lambda_, nest::STDPConnection< targetidentifierT >::mu_plus_, and nest::STDPConnection< targetidentifierT >::Wmax_.
template<typename targetidentifierT > void nest::STDPConnection< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, nest::names::size_of, and nest::names::weight.
template<typename targetidentifierT > void nest::STDPConnection< targetidentifierT >::send (Event & e, thread t, double_t t_lastspike, const CommonSynapseProperties & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
t_lastspike Point in time of last spike sent.
cp common properties of all synapses (empty).
e The event to send
t The thread on which this connection is stored.
t_lastspike Time point of last spike emitted
cp Common properties object, containing the stdp parameters.
References numerics::e, nest::Node::get_history(), nest::Node::get_K_value(), nest::Time::get_ms(), nest::Event::get_stamp(), nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), nest::Event::set_weight(), nest::names::start, nest::names::t_spike, and nest::names::target.
template<typename targetidentifierT > void nest::STDPConnection< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties of this connection from the values given in dictionary.
References nest::names::d, and nest::names::weight.
template<typename targetidentifierT> void nest::STDPConnection< targetidentifierT >::set_weight (double_t w) inline
References nest::names::w, and nest::STDPConnection< targetidentifierT >::weight_.
Member Data Documentation
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::alpha_ private
Referenced by nest::STDPConnection< targetidentifierT >::depress_().
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::Kplus_ private
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::lambda_ private
Referenced by nest::STDPConnection< targetidentifierT >::depress_(), and nest::STDPConnection< targetidentifierT >::facilitate_().
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::mu_minus_ private
Referenced by nest::STDPConnection< targetidentifierT >::depress_().
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::mu_plus_ private
Referenced by nest::STDPConnection< targetidentifierT >::facilitate_().
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::tau_plus_ private
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::weight_ private
Referenced by nest::STDPConnection< targetidentifierT >::set_weight().
template<typename targetidentifierT> double_t nest::STDPConnection< targetidentifierT >::Wmax_ private
Referenced by nest::STDPConnection< targetidentifierT >::depress_(), and nest::STDPConnection< targetidentifierT >::facilitate_().
The documentation for this class was generated from the following file:
stdp_connection.h