NEST: nest::sinusoidal_gamma_generator Class Reference
nest::sinusoidal_gamma_generator Class Reference
AC Gamma Generator.
#include <sinusoidal_gamma_generator.h>
Classes
struct Buffers_
Buffers of the model.
struct Parameters_
struct State_
struct Variables_
Public Member Functions
sinusoidal_gamma_generator ()
sinusoidal_gamma_generator (const sinusoidal_gamma_generator &)
port send_test_event (Node &, rport, synindex, bool)
Send an event to the receiving_node passed as an argument.
void handle (DataLoggingRequest &)
Handler for universal data logging request.
port handles_test_event (DataLoggingRequest &, rport)
void get_status (DictionaryDatum &) const
void set_status (const DictionaryDatum &)
bool has_proxies () const
Model can be switched between proxies (single spike train) and not.
bool local_receiver () const
Allow multimeter to connect to local instances.
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
virtual std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void finalize ()
Finalize node.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port handles_test_event (SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (CurrentEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void register_stdp_connection (double_t)
Register a STDP connection.
virtual void unregister_stdp_connection (double_t)
Unregister a STDP connection.
virtual void handle (SpikeEvent &e)
Handle incoming spike events.
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (CurrentEvent &e)
Handler for current events.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
virtual void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
virtual void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike history for (t1,t2].
virtual void event_hook (DSCurrentEvent &)
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
virtual bool is_subnet () const
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Private Member Functions
void init_state_ (const Node &)
Private function to initialize the state of a node to model defaults.
void init_buffers_ ()
Private function to initialize the buffers of a node.
void calibrate ()
Re-calculate dependent parameters of the node.
void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
void update (Time const &, const long_t, const long_t)
Bring the node from state $t$ to $t+n*dt$.
double_t get_rate_ () const
double_t deltaLambda_ (const Parameters_ &, double_t, double_t) const
compute deltaLambda for given parameters from ta to tb
double_t hazard_ (port) const
compute hazard for given target index, including time-step factor
Private Attributes
StimulatingDevice< SpikeEvent > device_
Parameters_ P_
State_ S_
Variables_ V_
Buffers_ B_
Static Private Attributes
static RecordablesMap
< sinusoidal_gamma_generator > recordablesMap_
Friends
class RecordablesMap< sinusoidal_gamma_generator >
class UniversalDataLogger< sinusoidal_gamma_generator >
Additional Inherited Members
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Detailed Description
AC Gamma Generator.
Generates AC-modulated inhomogeneous gamma process.
Todo:
The implementation is very quick and dirty and not tuned for performance at all.
Note
The simulator works by calculating the hazard h(t) for each time step and comparing h(t) dt to a [0,1)-uniform number. The hazard is given by $[ h(t) = {a (t) (t)^{a-1} e^{-(t)}}{(a, (t))} $] with $[ (t) = dc + ac (2 f t +) $] $[ (t) = a {t_0}^t (s) ds $] and the incomplete Gamma function $(a,z)$; $a$ is the order of the gamma function and $t_0$ the time of the most recent spike.
Note
This implementation includes an additional $a$ factor in the calculation of $(t)$ and $h(t)$ in order to keep the mean rate constant with varying $a$
Let $t_0$ be the time of the most recent spike. If stimulus parameters are changed at $t_c > t_0$, then $(t)$ is integrated piecewise for $t>t_c$ as $[ (t) = {old} {t_0}^{t_c]} {old}(s) ds
{new} {t_c}^{t]} {new}(s) ds $] where "old" and "new" indicate old an new parameter values, respectively.
Todo:
This implementation assumes that outgoing connections are all made from the same synapse type, see #737. Once #681 is fixed, we need to add a check that his assumption holds.
Constructor & Destructor Documentation
nest::sinusoidal_gamma_generator::sinusoidal_gamma_generator ()
References recordablesMap_.
nest::sinusoidal_gamma_generator::sinusoidal_gamma_generator (const sinusoidal_gamma_generator & n)
Member Function Documentation
void nest::sinusoidal_gamma_generator::calibrate () private virtual
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
Implements nest::Node.
References nest::Time::get_ms(), and nest::Time::get_resolution().
nest::double_t nest::sinusoidal_gamma_generator::deltaLambda_ (const Parameters_ & p, double_t t_a, double_t t_b) const inline private
compute deltaLambda for given parameters from ta to tb
References nest::sinusoidal_gamma_generator::Parameters_::ac_, nest::sinusoidal_gamma_generator::Parameters_::dc_, nest::sinusoidal_gamma_generator::Parameters_::om_, nest::sinusoidal_gamma_generator::Parameters_::order_, and nest::sinusoidal_gamma_generator::Parameters_::phi_.
void nest::sinusoidal_gamma_generator::event_hook (DSSpikeEvent & e) private virtual
Modify Event object parameters during event delivery.
Some Nodes want to perform a function on an event for each of their targets. An example is the poisson_generator which needs to draw a random number for each target. The DSSpikeEvent, DirectSendingSpikeEvent, calls sender->event_hook(thread, *this) in its operator() function instead of calling target->handle(). The default implementation of Node::event_hook() just calls target->handle(DSSpikeEvent&). Any reimplementation must also execute this call. Otherwise the event will not be delivered. If needed, target->handle(DSSpikeEvent) may be called more than once.
Reimplemented from nest::Node.
References assert(), nest::Event::get_port(), nest::Event::get_receiver(), and nest::Node::handle().
double_t nest::sinusoidal_gamma_generator::get_rate_ () const inline private
References nest::sinusoidal_gamma_generator::State_::rate_, and S_.
Referenced by nest::RecordablesMap< HostNode >::create().
void nest::sinusoidal_gamma_generator::get_status (DictionaryDatum & d) const inline
References device_, nest::sinusoidal_gamma_generator::Parameters_::get(), nest::sinusoidal_gamma_generator::State_::get(), P_, nest::names::recordables, recordablesMap_, and S_.
void nest::sinusoidal_gamma_generator::handle (DataLoggingRequest & e) virtual
Handler for universal data logging request.
See also
handle(SpikeEvent&)
Exceptions
UnexpectedEvent
Reimplemented from nest::Node.
port nest::sinusoidal_gamma_generator::handles_test_event (DataLoggingRequest & dlr, rport receptor_type) inline virtual
Reimplemented from nest::Node.
References B_, nest::Node::get_name(), nest::sinusoidal_gamma_generator::Buffers_::logger_, and recordablesMap_.
bool nest::sinusoidal_gamma_generator::has_proxies () const inline virtual
Model can be switched between proxies (single spike train) and not.
Reimplemented from nest::Node.
References nest::sinusoidal_gamma_generator::Parameters_::individual_spike_trains_, and P_.
double nest::sinusoidal_gamma_generator::hazard_ (port tgt_idx) const private
compute hazard for given target index, including time-step factor
void nest::sinusoidal_gamma_generator::init_buffers_ () private virtual
Private function to initialize the buffers of a node.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the buffers of a node.
See also
Node::init_buffers()
Implements nest::Node.
References swap().
void nest::sinusoidal_gamma_generator::init_state_ (const Node &) private virtual
Private function to initialize the state of a node to model defaults.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the state of a node to the model defaults; the state is the set of observable dynamic variables.
Parameters
Reference to model prototype object.
See also
Node::init_state()
Note
To provide a reasonable behavior during the transition to the new scheme, init_state_() has a default implementation calling init_dynamic_state_().
Implements nest::Node.
References device_, nest::Node::init_state(), and S_.
bool nest::sinusoidal_gamma_generator::local_receiver () const inline virtual
Allow multimeter to connect to local instances.
Reimplemented from nest::Node.
port nest::sinusoidal_gamma_generator::send_test_event (Node & receiving_node, rport receptor_type, synindex syn_id, bool dummy_target) inline virtual
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws UnexpectedEvent.
This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node.
If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
Reimplemented from nest::Node.
References device_, numerics::e, nest::Node::handles_test_event(), nest::sinusoidal_gamma_generator::Parameters_::individual_spike_trains_, nest::invalid_port_, nest::Node::is_model_prototype(), nest::sinusoidal_gamma_generator::Parameters_::num_trains_, P_, and nest::Event::set_sender().
void nest::sinusoidal_gamma_generator::set_status (const DictionaryDatum & d) inline
References device_, P_, and nest::sinusoidal_gamma_generator::Parameters_::set().
void nest::sinusoidal_gamma_generator::update (Time const & , const long_t , const long_t) private virtual
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to.
Parameters
Time network time at beginning of time slice.
long_t initial step inside time slice
long_t post-final step inside time slice
Implements nest::Node.
References assert(), nest::Scheduler::get_min_delay(), nest::Time::get_ms(), and nest::Time::get_steps().
Friends And Related Function Documentation
friend class RecordablesMap< sinusoidal_gamma_generator > friend
friend class UniversalDataLogger< sinusoidal_gamma_generator > friend
Member Data Documentation
Buffers_ nest::sinusoidal_gamma_generator::B_ private
Referenced by handles_test_event().
StimulatingDevice<SpikeEvent> nest::sinusoidal_gamma_generator::device_ private
Referenced by get_status(), init_state_(), send_test_event(), and set_status().
Parameters_ nest::sinusoidal_gamma_generator::P_ private
Referenced by get_status(), has_proxies(), send_test_event(), and set_status().
RecordablesMap< sinusoidal_gamma_generator > nest::sinusoidal_gamma_generator::recordablesMap_ static private
Referenced by get_status(), handles_test_event(), and sinusoidal_gamma_generator().
State_ nest::sinusoidal_gamma_generator::S_ private
Referenced by get_rate_(), get_status(), and init_state_().
Variables_ nest::sinusoidal_gamma_generator::V_ private
The documentation for this class was generated from the following files:
sinusoidal_gamma_generator.h
sinusoidal_gamma_generator.cpp