NEST: Name Class Reference
Name Class Reference
Represent strings by ints to facilitate fast comparison.
#include <name.h>
Public Types
typedef unsigned int handle_t
Public Member Functions
Name ()
Create Name without value.
Name (const char s[])
Name (const std::string &s)
Name (const Name &n)
const std::string & toString (void) const
Return string represented by Name.
handle_t toIndex (void) const
Return table index for Name object.
bool operator== (const Name &n) const
bool operator!= (const Name &n) const
bool operator< (const Name &n) const
Non-alphabetic ordering of names.
void print_handle (std::ostream &) const
Static Public Member Functions
static bool lookup (const std::string &s)
static size_t capacity ()
static size_t num_handles ()
static void list_handles (std::ostream &)
static void list (std::ostream &)
static void info (std::ostream &)
Private Types
typedef std::map< std::string,
handle_t > HandleMap_
Datatype for map from strings to handles.
typedef std::deque< std::string > HandleTable_
Private Member Functions
handle_t insert (const std::string &)
Static Private Member Functions
static HandleMap_ & handleMapInstance_ ()
Function returning a reference to the single map instance.
static HandleTable_ & handleTableInstance_ ()
Private Attributes
handle_t handle_
Handle for the name represented by the Name object.
Detailed Description
Represent strings by ints to facilitate fast comparison.
Each Name object represents a string by a unique integer number. Comparing Name objects instead of comparing strings directly, reduces the complexity of string comparison to that of int comparison.
Each Name object contains a Handle to the string it represents. Strings are mapped to Handles via an associative array. Handles are stored in a table, and each Handle contains its own index into this table as unique ID, as well as the string represented. Fast comparison of Name objects is achieved by comparing the indices stored in the handles. Reference counting permits deletion of unused Handles.
Note
Any string read by the interpreter should be converted to a Name at once.
class Name maintains two static lookup tables and is thus not thread-safe.
Member Typedef Documentation
typedef unsigned int Name::handle_t
typedef std::map<std::string, handle_t> Name::HandleMap_ private
Datatype for map from strings to handles.
typedef std::deque<std::string> Name::HandleTable_ private
Constructor & Destructor Documentation
Name::Name () inline
Create Name without value.
Name::Name (const char s[]) inline
Name::Name (const std::string & s) inline
Name::Name (const Name & n) inline
Member Function Documentation
std::size_t Name::capacity () static
References handleTableInstance_().
Name::HandleMap_ & Name::handleMapInstance_ () inline static private
Function returning a reference to the single map instance.
Implementation akin to Meyers Singleton, see Alexandrescu, ch 6.4.
References handleTableInstance_().
Referenced by insert(), list(), and lookup().
Name::HandleTable_ & Name::handleTableInstance_ () inline static private
Referenced by capacity(), handleMapInstance_(), insert(), list_handles(), num_handles(), print_handle(), and toString().
void Name::info (std::ostream & out) static
References list_handles().
unsigned int Name::insert (const std::string & s) private
References handleMapInstance_(), and handleTableInstance_().
Referenced by nest::cg_create_masks().
void Name::list (std::ostream & out) static
References handleMapInstance_(), and list_handles().
void Name::list_handles (std::ostream & out) static
References handleTableInstance_(), nest::names::n, and num_handles().
Referenced by info(), and list().
static bool Name::lookup (const std::string & s) inline static
References handleMapInstance_().
Referenced by SLIType::settypename().
std::size_t Name::num_handles () static
References handleTableInstance_().
Referenced by DictionaryStack::basecache_token(), DictionaryStack::cache_token(), and list_handles().
bool Name::operator!= (const Name & n) const inline
References handle_.
bool Name::operator< (const Name & n) const inline
Non-alphabetic ordering of names.
Entering Name's into dictionaries requires ordering. Ordering based on string comparison would be very slow. We thus compare based on table indices.
References handle_.
bool Name::operator== (const Name & n) const inline
References handle_.
void Name::print_handle (std::ostream & o) const
References handle_, and handleTableInstance_().
handle_t Name::toIndex (void) const inline
Return table index for Name object.
References handle_.
Referenced by DictionaryStack::basecache_token(), DictionaryStack::baseknown(), DictionaryStack::baselookup(), DictionaryStack::cache_token(), DictionaryStack::clear_token_from_basecache(), DictionaryStack::clear_token_from_cache(), DictionaryStack::known(), and DictionaryStack::lookup2().
const std::string & Name::toString (void) const
Return string represented by Name.
References handle_, and handleTableInstance_().
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object(), nest::GenericFactory< BaseT >::create(), SLIInterpreter::createcommand(), nest::Network::divergent_connect(), MathLinkPutStringFunction::execute(), XIfstreamFunction::execute(), IfstreamFunction::execute(), OfstreamFunction::execute(), OfsopenFunction::execute(), IsstreamFunction::execute(), StrSStreamFunction::execute(), StrFunction::execute(), PrettyprintFunction::execute(), CloseistreamFunction::execute(), CloseostreamFunction::execute(), FlushFunction::execute(), EndlFunction::execute(), EndsFunction::execute(), EatwhiteFunction::execute(), SetwFunction::execute(), SetprecisionFunction::execute(), IOSFixedFunction::execute(), IOSScientificFunction::execute(), IOSDefaultFunction::execute(), IOSShowpointFunction::execute(), IOSNoshowpointFunction::execute(), IOSShowbaseFunction::execute(), IOSNoshowbaseFunction::execute(), IOSDecFunction::execute(), nest::NestModule::SetDefaults_l_DFunction::execute(), IOSHexFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), IOSOctFunction::execute(), IOSLeftFunction::execute(), IOSRightFunction::execute(), IOSInternalFunction::execute(), GetcFunction::execute(), GetsFunction::execute(), GetlineFunction::execute(), IGoodFunction::execute(), IClearFunction::execute(), OClearFunction::execute(), IFailFunction::execute(), OGoodFunction::execute(), IEofFunction::execute(), OEofFunction::execute(), In_AvailFunction::execute(), ReadDoubleFunction::execute(), ReadIntFunction::execute(), ReadWordFunction::execute(), nest::Network::execute_sli_protected(), nest::Time::ms::fromtoken(), getValue< bool >(), getValue< double >(), getValue< float >(), getValue< long >(), getValue< std::string >(), getValue< std::vector< double > >(), getValue< std::vector< long > >(), Dictionary::lookup2(), DictionaryStack::lookup2(), nest::UnknownModelName::message(), operator<<(), Dictionary::operator[](), setValue< bool >(), setValue< double >(), setValue< float >(), setValue< long >(), setValue< std::string >(), setValue< std::valarray< double > >(), setValue< std::valarray< long > >(), setValue< std::vector< double > >(), setValue< std::vector< long > >(), TokenArray::toValarray(), TokenArray::toVector(), and DictionaryStack::undef().
Member Data Documentation
handle_t Name::handle_ private
Handle for the name represented by the Name object.
Referenced by operator!=(), operator<(), operator==(), print_handle(), toIndex(), and toString().
The documentation for this class was generated from the following files:
name.h
name.cc