NEST: nest::iaf_psc_delta_canon Class Reference
nest::iaf_psc_delta_canon Class Reference
#include <iaf_psc_delta_canon.h>
Classes
struct Buffers_
Buffers of the model.
struct Parameters_
Independent parameters of the model.
struct State_
State variables of the model.
struct Variables_
Internal variables of the model.
Public Member Functions
iaf_psc_delta_canon ()
Basic constructor.
iaf_psc_delta_canon (const iaf_psc_delta_canon &)
Copy constructor.
port send_test_event (Node &, rport, synindex, bool)
Send an event to the receiving_node passed as an argument.
port handles_test_event (SpikeEvent &, rport)
Check if the node can handle a particular event and receptor type.
port handles_test_event (CurrentEvent &, rport)
port handles_test_event (DataLoggingRequest &, rport)
void handle (SpikeEvent &)
Handle incoming spike events.
void handle (CurrentEvent &)
Handler for current events.
void handle (DataLoggingRequest &)
Handler for universal data logging request.
bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
void get_status (DictionaryDatum &) const
void set_status (const DictionaryDatum &)
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool has_proxies () const
Returns true if the node has proxies on remote threads.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool local_receiver () const
Returns true if the node only receives events from nodes/devices on the same thread.
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
virtual std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void finalize ()
Finalize node.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void register_stdp_connection (double_t)
Register a STDP connection.
virtual void unregister_stdp_connection (double_t)
Unregister a STDP connection.
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
virtual void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
virtual void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike history for (t1,t2].
virtual void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
virtual void event_hook (DSCurrentEvent &)
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
virtual bool is_subnet () const
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Static Private Attributes
static RecordablesMap
< iaf_psc_delta_canon > recordablesMap_
Mapping of recordables names to access functions.
Interface functions
Note
These functions are private, so that they can be accessed only through a Node*.
class RecordablesMap< iaf_psc_delta_canon >
class UniversalDataLogger< iaf_psc_delta_canon >
Parameters_ P_
State_ S_
Variables_ V_
Buffers_ B_
void init_state_ (const Node &proto)
Private function to initialize the state of a node to model defaults.
void init_buffers_ ()
Private function to initialize the buffers of a node.
void calibrate ()
Re-calculate dependent parameters of the node.
void update (Time const &, const long_t, const long_t)
Bring the node from state $t$ to $t+n*dt$.
void set_spiketime (Time const &)
Time get_spiketime () const
void emit_spike_ (Time const &origin, const long_t lag, const double_t offset_U)
Emit a single spike caused by DC current in absence of spike input.
void emit_instant_spike_ (Time const &origin, const long_t lag, const double_t spike_offset)
Emit a single spike caused instantly by an input spike.
void propagate_ (const double_t dt)
Propagate neuron state.
double_t get_V_m_ () const
Read out the real membrane potential.
Additional Inherited Members
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Constructor & Destructor Documentation
nest::iaf_psc_delta_canon::iaf_psc_delta_canon ()
Basic constructor.
This constructor should only be used by GenericModel to create model prototype instances.
References recordablesMap_.
nest::iaf_psc_delta_canon::iaf_psc_delta_canon (const iaf_psc_delta_canon & n)
Copy constructor.
GenericModel::allocate_() uses the copy constructor to clone actual model instances from the prototype instance.
Note
The copy constructor MUST NOT be used to create nodes based on nodes that have been placed in the network.
Member Function Documentation
void nest::iaf_psc_delta_canon::calibrate () private virtual
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
Implements nest::Node.
References assert(), B_, nest::iaf_psc_delta_canon::Parameters_::c_m_, nest::iaf_psc_delta_canon::Variables_::exp_t_, numerics::expm1(), nest::iaf_psc_delta_canon::Variables_::expm1_t_, nest::Time::get_ms(), nest::Time::get_resolution(), nest::Time::get_steps(), nest::iaf_psc_delta_canon::Variables_::h_ms_, nest::iaf_psc_delta_canon::Variables_::I_contrib_, nest::iaf_psc_delta_canon::Parameters_::I_e_, nest::iaf_psc_delta_canon::Buffers_::logger_, P_, nest::iaf_psc_delta_canon::Variables_::refractory_steps_, nest::iaf_psc_delta_canon::Parameters_::t_ref_, nest::iaf_psc_delta_canon::Parameters_::tau_m_, V_, and nest::iaf_psc_delta_canon::Variables_::v_inf_.
void nest::iaf_psc_delta_canon::emit_instant_spike_ (Time const & origin, const long_t lag, const double_t spike_offset) private
Emit a single spike caused instantly by an input spike.
Parameters
origin Time stamp at beginning of slice
lag Time step within slice
spike_offset Time offset for spike
References assert(), nest::Time::get_steps(), and nest::Event::set_offset().
Referenced by update().
void nest::iaf_psc_delta_canon::emit_spike_ (Time const & origin, const long_t lag, const double_t offset_U) private
Emit a single spike caused by DC current in absence of spike input.
Emits a single spike and reset neuron given that the membrane potential was below threshold at the beginning of a mini-timestep and above afterwards.
Parameters
origin Time stamp at beginning of slice
lag Time step within slice
offset_U Time offset for U value, ie for time when threhold crossing was detected
References assert(), nest::names::dt, nest::Time::get_steps(), and nest::Event::set_offset().
Referenced by update().
Time nest::iaf_psc_delta_canon::get_spiketime () const inline private
References nest::iaf_psc_delta_canon::State_::last_spike_step_, S_, and nest::Time::step.
void nest::iaf_psc_delta_canon::get_status (DictionaryDatum & d) const inline
References nest::iaf_psc_delta_canon::Parameters_::get(), nest::iaf_psc_delta_canon::State_::get(), P_, nest::names::recordables, recordablesMap_, and S_.
double_t nest::iaf_psc_delta_canon::get_V_m_ () const inline private
Read out the real membrane potential.
References nest::iaf_psc_delta_canon::Parameters_::E_L_, P_, S_, and nest::iaf_psc_delta_canon::State_::U_.
Referenced by nest::RecordablesMap< HostNode >::create().
void nest::iaf_psc_delta_canon::handle (SpikeEvent & e) virtual
Handle incoming spike events.
Default implementation of event handlers just throws an UnexpectedEvent exception.
Parameters
thrd Id of the calling thread.
e Event object.
This handler has to be implemented if a Node should accept spike events.
See also
class SpikeEvent
class UnexpectedEvent
Exceptions
UnexpectedEvent This is the default event to throw.
Reimplemented from nest::Node.
References nest::SliceRingBuffer::add_spike(), assert(), B_, nest::iaf_psc_delta_canon::Buffers_::events_, nest::Event::get_delay(), nest::SpikeEvent::get_multiplicity(), nest::Event::get_offset(), nest::Event::get_rel_delivery_steps(), nest::Event::get_stamp(), nest::Time::get_steps(), nest::Event::get_weight(), and nest::Node::network().
void nest::iaf_psc_delta_canon::handle (CurrentEvent & e) virtual
Handler for current events.
See also
handle(thread, SpikeEvent&)
Exceptions
UnexpectedEvent
Reimplemented from nest::Node.
References nest::RingBuffer::add_value(), assert(), B_, nest::names::c, nest::iaf_psc_delta_canon::Buffers_::currents_, nest::CurrentEvent::get_current(), nest::Event::get_delay(), nest::Event::get_rel_delivery_steps(), nest::Event::get_weight(), nest::Node::network(), and nest::names::w.
void nest::iaf_psc_delta_canon::handle (DataLoggingRequest & e) virtual
Handler for universal data logging request.
See also
handle(SpikeEvent&)
Exceptions
UnexpectedEvent
Reimplemented from nest::Node.
port nest::iaf_psc_delta_canon::handles_test_event (SpikeEvent & , rport receptor_type) inline virtual
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event().
handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle.
See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3.
Note
The semantics of all other handles_test_event() functions is identical.
Exceptions
IllegalConnection
Reimplemented from nest::Node.
References nest::Node::get_name().
port nest::iaf_psc_delta_canon::handles_test_event (CurrentEvent & , rport receptor_type) inline virtual
Reimplemented from nest::Node.
References nest::Node::get_name().
port nest::iaf_psc_delta_canon::handles_test_event (DataLoggingRequest & dlr, rport receptor_type) inline virtual
Reimplemented from nest::Node.
References B_, nest::Node::get_name(), nest::iaf_psc_delta_canon::Buffers_::logger_, and recordablesMap_.
void nest::iaf_psc_delta_canon::init_buffers_ () private virtual
Private function to initialize the buffers of a node.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the buffers of a node.
See also
Node::init_buffers()
Implements nest::Node.
void nest::iaf_psc_delta_canon::init_state_ (const Node &) private virtual
Private function to initialize the state of a node to model defaults.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the state of a node to the model defaults; the state is the set of observable dynamic variables.
Parameters
Reference to model prototype object.
See also
Node::init_state()
Note
To provide a reasonable behavior during the transition to the new scheme, init_state_() has a default implementation calling init_dynamic_state_().
Implements nest::Node.
References S_.
bool nest::iaf_psc_delta_canon::is_off_grid () const inline virtual
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
Reimplemented from nest::Node.
void nest::iaf_psc_delta_canon::propagate_ (const double_t dt) private
Propagate neuron state.
Propagate the neuron's state by dt.
Parameters
dt Interval over which to propagate
References assert(), and numerics::expm1().
Referenced by update().
port nest::iaf_psc_delta_canon::send_test_event (Node & receiving_node, rport receptor_type, synindex syn_id, bool dummy_target) inline virtual
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws UnexpectedEvent.
This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node.
If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
Reimplemented from nest::Node.
References numerics::e, nest::Node::handles_test_event(), and nest::Event::set_sender().
void nest::iaf_psc_delta_canon::set_spiketime (Time const & now) private
References nest::Time::get_steps(), nest::iaf_psc_delta_canon::State_::last_spike_step_, and S_.
void nest::iaf_psc_delta_canon::set_status (const DictionaryDatum & d) inline
References P_, S_, nest::iaf_psc_delta_canon::Parameters_::set(), and nest::iaf_psc_delta_canon::State_::set().
void nest::iaf_psc_delta_canon::update (Time const & , const long_t , const long_t) private virtual
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to.
Parameters
Time network time at beginning of time slice.
long_t initial step inside time slice
long_t post-final step inside time slice
Implements nest::Node.
References nest::SliceRingBuffer::add_refractory(), assert(), B_, nest::iaf_psc_delta_canon::Parameters_::c_m_, nest::iaf_psc_delta_canon::Buffers_::currents_, emit_instant_spike_(), emit_spike_(), nest::iaf_psc_delta_canon::Buffers_::events_, nest::iaf_psc_delta_canon::Variables_::expm1_t_, nest::Scheduler::get_min_delay(), nest::SliceRingBuffer::get_next_spike(), nest::Time::get_steps(), nest::RingBuffer::get_value(), nest::iaf_psc_delta_canon::Variables_::h_ms_, nest::iaf_psc_delta_canon::State_::I_, nest::iaf_psc_delta_canon::Variables_::I_contrib_, nest::iaf_psc_delta_canon::State_::is_refractory_, nest::iaf_psc_delta_canon::State_::last_spike_offset_, nest::iaf_psc_delta_canon::State_::last_spike_step_, nest::iaf_psc_delta_canon::Buffers_::logger_, P_, nest::SliceRingBuffer::prepare_delivery(), propagate_(), nest::iaf_psc_delta_canon::Variables_::refr_spikes_buffer_, nest::iaf_psc_delta_canon::Variables_::refractory_steps_, S_, nest::iaf_psc_delta_canon::Parameters_::t_ref_, nest::iaf_psc_delta_canon::Parameters_::tau_m_, nest::iaf_psc_delta_canon::State_::U_, nest::iaf_psc_delta_canon::Parameters_::U_min_, nest::iaf_psc_delta_canon::Parameters_::U_th_, V_, and nest::iaf_psc_delta_canon::State_::with_refr_input_.
Friends And Related Function Documentation
friend class RecordablesMap< iaf_psc_delta_canon > friend
friend class UniversalDataLogger< iaf_psc_delta_canon > friend
The documentation for this class was generated from the following files:
iaf_psc_delta_canon.h
iaf_psc_delta_canon.cpp