NEST: array< T > Class Template Reference
array< T > Class Template Reference
#include <array.h>
Public Member Functions
array ()
array (size_t, const T &=T())
array (const array< T > &)
~array ()
T * begin (void)
T * end (void)
void resize (size_t, const T &=T())
size_t size (void) const
bool empty (void) const
T & operator[] (size_t)
const T & operator[] (size_t) const
void fill (const T &)
array< T > & operator= (const array< T > &)
Private Attributes
T * p
size_t n
Constructor & Destructor Documentation
template<class T> array< T >::array () inline
template<class T > array< T >::array (size_t n_s, const T & t = T())
References assert(), array< T >::fill(), array< T >::n, and array< T >::p.
template<class T > array< T >::array (const array< T > & a)
References assert(), array< T >::n, and array< T >::p.
template<class T > array< T >::~array ()
References nest::names::p.
Member Function Documentation
template<class T> T* array< T >::begin (void) inline
References array< T >::p.
template<class T> bool array< T >::empty (void) const inline
References array< T >::n.
template<class T> T* array< T >::end (void) inline
References array< T >::n, and array< T >::p.
template<class T > void array< T >::fill (const T & e)
References nest::names::n, and nest::names::p.
Referenced by array< T >::array().
template<class T > array< T > & array< T >::operator= (const array< T > & a)
References assert(), array< T >::n, nest::names::n, array< T >::p, and nest::names::p.
template<class T > T & array< T >::operator[] (size_t i)
References assert(), nest::names::n, and nest::names::p.
template<class T > const T & array< T >::operator[] (size_t i) const
References assert(), nest::names::n, and nest::names::p.
template<class T > void array< T >::resize (size_t n_s, const T & t = T())
References assert(), nest::names::h, nest::names::n, and nest::names::p.
template<class T> size_t array< T >::size (void) const inline
References array< T >::n.
Member Data Documentation
template<class T> size_t array< T >::n private
Referenced by array< T >::array(), array< T >::empty(), array< T >::end(), array< T >::operator=(), and array< T >::size().
template<class T> T* array< T >::p private
Referenced by array< T >::array(), array< T >::begin(), array< T >::end(), and array< T >::operator=().
The documentation for this class was generated from the following file:
array.h