NEST: SpecialFunctionsModule::GaussDiskConvFunction Class Reference
SpecialFunctionsModule::GaussDiskConvFunction Class Reference
#include <specialfunctionsmodule.h>
Public Member Functions
void execute (SLIInterpreter *) const
GaussDiskConvFunction (void)
~GaussDiskConvFunction (void)
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Static Private Member Functions
static double f_ (double, void *)
Integrand function.
Private Attributes
gsl_integration_workspace * w_
Static Private Attributes
static const int MAX_QUAD_SIZE = 5000
static const double QUAD_ERR_LIM = 1e-12
static const double QUAD_ERR_SCALE = 200.0
static gsl_function F_
Constructor & Destructor Documentation
SpecialFunctionsModule::GaussDiskConvFunction::GaussDiskConvFunction (void)
References f_().
SpecialFunctionsModule::GaussDiskConvFunction::~GaussDiskConvFunction (void)
Member Function Documentation
void SpecialFunctionsModule::GaussDiskConvFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), SLIInterpreter::raiseerror(), TokenStack::top(), and nest::names::y.
double SpecialFunctionsModule::GaussDiskConvFunction::f_ (double r, void * params) inline static private
Integrand function.
Note
This function must be static with C linkage so that it can be passed to the GSL. Alternatively, one could define it outside the class.
Referenced by GaussDiskConvFunction().
Member Data Documentation
gsl_function SpecialFunctionsModule::GaussDiskConvFunction::F_ static private
const int SpecialFunctionsModule::GaussDiskConvFunction::MAX_QUAD_SIZE = 5000 static private
const double SpecialFunctionsModule::GaussDiskConvFunction::QUAD_ERR_LIM = 1e-12 static private
const double SpecialFunctionsModule::GaussDiskConvFunction::QUAD_ERR_SCALE = 200.0 static private
gsl_integration_workspace* SpecialFunctionsModule::GaussDiskConvFunction::w_ private
The documentation for this class was generated from the following files:
specialfunctionsmodule.h
specialfunctionsmodule.cc