NEST: nest::MsgHandler Class Reference
nest::MsgHandler Class Reference
#include <music_message_in_proxy.h>
Public Member Functions
void get_status (DictionaryDatum &d) const
void clear ()
Private Member Functions
void operator() (double t, void *msg, size_t size)
Private Attributes
ArrayDatum messages
The buffer for incoming message.
std::vector< double > message_times
The buffer for incoming message.
Member Function Documentation
void nest::MsgHandler::clear () inline
References TokenArray::clear(), message_times, and messages.
Referenced by nest::music_message_in_proxy::set_status().
void nest::MsgHandler::get_status (DictionaryDatum & d) const inline
References message_times, messages, and TokenArray::size().
Referenced by nest::music_message_in_proxy::get_status().
void nest::MsgHandler::operator() (double t, void * msg, size_t size) inline private
References message_times, messages, and TokenArray::push_back().
Member Data Documentation
std::vector<double> nest::MsgHandler::message_times private
The buffer for incoming message.
Referenced by clear(), get_status(), and operator()().
ArrayDatum nest::MsgHandler::messages private
The buffer for incoming message.
Referenced by clear(), get_status(), and operator()().
The documentation for this class was generated from the following file:
music_message_in_proxy.h