NEST: FunctionDatum Class Reference
FunctionDatum Class Reference
#include <functiondatum.h>
Public Member Functions
FunctionDatum (FunctionDatum const &fd)
FunctionDatum (Name const &n, SLIFunction const *f)
void print (std::ostream &o) const
void pprint (std::ostream &o) const
void info (std::ostream &out) const
bool equals (Datum const *dat) const
const Name & getname (void) const
void backtrace (SLIInterpreter *, int) const
Public Member Functions inherited from TypedDatum<&SLIInterpreter::Functiontype >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
virtual void list (std::ostream &o, std::string prefix, int l) const
virtual void input_form (std::ostream &o) const
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
Datum * get_ptr ()
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
SLIFunction const & operator= (SLIFunction const &f)
Private Attributes
Name name
Static Private Attributes
static sli::pool memory
Additional Inherited Members
Protected Member Functions inherited from TypedDatum<&SLIInterpreter::Functiontype >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Constructor & Destructor Documentation
FunctionDatum::FunctionDatum (FunctionDatum const & fd) inline
References Datum::set_executable().
Referenced by clone().
FunctionDatum::FunctionDatum (Name const & n, SLIFunction const * f) inline
Here, we shortcut the default action of the type object and directly place the function pointer in the datum's action field. Thus, we avoid an extra virtual function call.
References Datum::action, and Datum::set_executable().
Member Function Documentation
void FunctionDatum::backtrace (SLIInterpreter * i, int p) const
References Datum::action, and SLIFunction::backtrace().
Referenced by SLIInterpreter::stack_backtrace().
Datum* FunctionDatum::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Implements Datum.
References FunctionDatum().
bool FunctionDatum::equals (Datum const * dat) const inline virtual
Reimplemented from Datum.
References Datum::action.
Datum* FunctionDatum::get_ptr () inline private virtual
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
The prefix const indicates that the pointer should be trated as const because changes affect all other references as well.
Reimplemented from Datum.
References Datum::addReference().
const Name& FunctionDatum::getname (void) const inline
References name.
Referenced by SLIInterpreter::getcurrentname().
void FunctionDatum::info (std::ostream & out) const inline virtual
Reimplemented from Datum.
References name.
static void FunctionDatum::operator delete (void * p, size_t size) inline static
References sli::pool::free(), memory, and nest::names::p.
static void* FunctionDatum::operator new (size_t size) inline static
References sli::pool::alloc(), and memory.
SLIFunction const& FunctionDatum::operator= (SLIFunction const & f) inline private
References Datum::action, and name.
void FunctionDatum::pprint (std::ostream & o) const inline virtual
Implements Datum.
References print().
Referenced by FunctiontypeFunction::execute().
void FunctionDatum::print (std::ostream & o) const inline virtual
Implements Datum.
References name.
Referenced by pprint().
Member Data Documentation
sli::pool FunctionDatum::memory static private
Referenced by operator delete(), and operator new().
Name FunctionDatum::name private
Referenced by getname(), info(), operator=(), and print().
The documentation for this class was generated from the following files:
functiondatum.h
functiondatum.cc