NEST: PgetrusageFunction Class Reference
PgetrusageFunction Class Reference
#include <slicontrol.h>
Public Member Functions
PgetrusageFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Private Member Functions
bool getinfo_ (int, DictionaryDatum &) const
Constructor & Destructor Documentation
PgetrusageFunction::PgetrusageFunction () inline
Member Function Documentation
void PgetrusageFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::EStack, getinfo_(), SLIInterpreter::M_ERROR, SLIInterpreter::message(), SLIInterpreter::OStack, TokenStack::pop(), TokenStack::push(), SLIInterpreter::raiseerror(), and Processes::systemerror().
bool PgetrusageFunction::getinfo_ (int who, DictionaryDatum & dict) const private
References assert(), and lockPTR< D >::valid().
Referenced by execute().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc