NEST: nest::RecordablesMap< HostNode > Class Template Reference
nest::RecordablesMap< HostNode > Class Template Reference
Devices
Map names of recordables to data access functions.
#include <recordables_map.h>
Public Types
typedef double_t(HostNode::* DataAccessFct)() const
Datatype for access functions.
Public Member Functions
virtual ~RecordablesMap ()
void create ()
Create the map.
ArrayDatum get_list () const
Obtain SLI list of all recordables, for use by get_status().
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
template<>
void create ()
Private Types
typedef std::map< Name,
double_t(HostNode::*)() const > Base_
Private Member Functions
void insert_ (const Name &n, const DataAccessFct f)
Insertion functions to be used in create(), adds entry to map and list.
Detailed Description
template<typename HostNode>
class nest::RecordablesMap< HostNode >
Map names of recordables to data access functions.
This map identifies the data access functions for recordable state variables in model neurons. Each neuron model shall have exactly one static instance of RecordablesMap.
Note
The map is initialized by the create() member function and not by the constructor because of the following conflict: The recordablesMap_ shall be a private static member of its host class, since the same map applies to all objects. Creation by a constructor leads to static initialization conflicts with the Name class. Thus, creation is deferred to the plain constructor of the host Node class, which is called only once to create the model prototype instance.
See also
multimeter, UniversalDataLogger
Member Typedef Documentation
template<typename HostNode> typedef std::map<Name, double_t (HostNode::*)() const> nest::RecordablesMap< HostNode >::Base_ private
template<typename HostNode> typedef double_t(HostNode::* nest::RecordablesMap< HostNode >::DataAccessFct)() const
Datatype for access functions.
Constructor & Destructor Documentation
template<typename HostNode> virtual nest::RecordablesMap< HostNode >::~RecordablesMap () inline virtual
Member Function Documentation
template<> void nest::RecordablesMap< ht_neuron >::create ()
References nest::ht_neuron::get_g_spike_(), nest::ht_neuron::get_I_h_(), nest::ht_neuron::get_I_KNa_(), nest::ht_neuron::get_I_NaP_(), nest::ht_neuron::get_I_T_(), nest::ht_neuron::get_r_potassium_(), and nest::names::V_m.
template<> void nest::RecordablesMap< sinusoidal_poisson_generator >::create ()
References nest::sinusoidal_poisson_generator::get_rate_(), and nest::names::rate.
template<> void nest::RecordablesMap< nest::mcculloch_pitts_neuron >::create ()
References nest::binary_neuron< TGainfunction >::get_input__(), nest::binary_neuron< TGainfunction >::get_output_state__(), nest::names::h, and nest::names::S.
template<> void nest::RecordablesMap< iaf_psc_alpha >::create ()
References nest::iaf_psc_alpha::get_input_currents_ex_(), nest::iaf_psc_alpha::get_input_currents_in_(), nest::iaf_psc_alpha::get_V_m_(), nest::iaf_psc_alpha::get_weighted_spikes_ex_(), nest::iaf_psc_alpha::get_weighted_spikes_in_(), nest::names::input_currents_ex, nest::names::input_currents_in, nest::names::V_m, nest::names::weighted_spikes_ex, and nest::names::weighted_spikes_in.
template<> void nest::RecordablesMap< sinusoidal_gamma_generator >::create ()
References nest::sinusoidal_gamma_generator::get_rate_(), and nest::names::rate.
template<> void nest::RecordablesMap< iaf_neuron >::create ()
References nest::iaf_neuron::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_psc_alpha_multisynapse >::create ()
References nest::names::currents, nest::iaf_psc_alpha_multisynapse::get_current_(), nest::iaf_psc_alpha_multisynapse::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_psc_exp >::create ()
References nest::iaf_psc_exp::get_input_currents_ex_(), nest::iaf_psc_exp::get_input_currents_in_(), nest::iaf_psc_exp::get_V_m_(), nest::iaf_psc_exp::get_weighted_spikes_ex_(), nest::iaf_psc_exp::get_weighted_spikes_in_(), nest::names::input_currents_ex, nest::names::input_currents_in, nest::names::V_m, nest::names::weighted_spikes_ex, and nest::names::weighted_spikes_in.
template<> void nest::RecordablesMap< iaf_psc_exp_multisynapse >::create ()
References nest::iaf_psc_exp_multisynapse::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_tum_2000 >::create ()
References nest::iaf_tum_2000::get_I_syn_ex_(), nest::iaf_tum_2000::get_I_syn_in_(), nest::iaf_tum_2000::get_V_m_(), nest::names::I_syn_ex, nest::names::I_syn_in, and nest::names::V_m.
template<> void nest::RecordablesMap< izhikevich >::create ()
References nest::izhikevich::get_U_m_(), nest::izhikevich::get_V_m_(), nest::names::U_m, and nest::names::V_m.
template<> void nest::RecordablesMap< aeif_cond_alpha_multisynapse >::create ()
References nest::aeif_cond_alpha_multisynapse::get_y_elem_(), nest::aeif_cond_alpha_multisynapse::State_::V_M, nest::names::V_m, nest::aeif_cond_alpha_multisynapse::State_::W, and nest::names::w.
template<> void nest::RecordablesMap< iaf_chs_2007 >::create ()
References nest::iaf_chs_2007::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< sli_neuron >::create ()
References nest::sli_neuron::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_psc_exp_ps >::create ()
References nest::iaf_psc_exp_ps::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_psc_delta >::create ()
References nest::iaf_psc_delta::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< nest::ginzburg_neuron >::create ()
References nest::binary_neuron< TGainfunction >::get_input__(), nest::binary_neuron< TGainfunction >::get_output_state__(), nest::names::h, and nest::names::S.
template<> void nest::RecordablesMap< iaf_psc_alpha_presc >::create ()
References nest::iaf_psc_alpha_presc::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_psc_alpha_canon >::create ()
References nest::iaf_psc_alpha_canon::get_V_m_(), nest::iaf_psc_alpha_canon::get_y1_(), nest::iaf_psc_alpha_canon::get_y2_(), and nest::names::V_m.
template<> void nest::RecordablesMap< amat2_psc_exp >::create ()
References nest::amat2_psc_exp::get_V_m_(), nest::amat2_psc_exp::get_V_th_(), nest::amat2_psc_exp::get_V_th_v_(), nest::names::V_m, nest::names::V_th, and nest::names::V_th_v.
template<> void nest::RecordablesMap< mat2_psc_exp >::create ()
References nest::mat2_psc_exp::get_V_m_(), nest::mat2_psc_exp::get_V_th_(), nest::names::V_m, and nest::names::V_th.
template<> void nest::RecordablesMap< hh_psc_alpha >::create ()
References nest::names::Act_h, nest::names::Act_m, nest::names::I_ex, nest::names::I_in, nest::names::Inact_n, and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_psc_delta_canon >::create ()
References nest::iaf_psc_delta_canon::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< aeif_cond_alpha_RK5 >::create ()
References nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
template<> void nest::RecordablesMap< iaf_cond_exp_sfa_rr >::create ()
References nest::names::g_ex, nest::names::g_in, nest::names::g_rr, nest::names::g_sfa, and nest::names::V_m.
template<> void nest::RecordablesMap< pp_pop_psc_delta >::create ()
References nest::pp_pop_psc_delta::get_n_events_(), nest::pp_pop_psc_delta::get_V_m_(), nest::names::n_events, and nest::names::V_m.
template<> void nest::RecordablesMap< pp_psc_delta >::create ()
References nest::names::E_sfa, nest::pp_psc_delta::get_E_sfa_(), nest::pp_psc_delta::get_V_m_(), and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_cond_exp >::create ()
References nest::names::g_ex, nest::names::g_in, and nest::names::V_m.
template<> void nest::RecordablesMap< hh_cond_exp_traub >::create ()
References nest::names::Act_h, nest::names::Act_m, nest::names::g_ex, nest::names::g_in, nest::names::Inact_n, and nest::names::V_m.
template<> void nest::RecordablesMap< iaf_chxk_2008 >::create ()
References nest::names::g_ahp, nest::iaf_chxk_2008::State_::G_AHP, nest::names::g_ex, nest::iaf_chxk_2008::State_::G_EXC, nest::names::g_in, nest::iaf_chxk_2008::State_::G_INH, nest::iaf_chxk_2008::get_I_ahp_(), nest::iaf_chxk_2008::get_I_syn_exc_(), nest::iaf_chxk_2008::get_I_syn_inh_(), nest::iaf_chxk_2008::get_y_elem_(), and nest::names::V_m.
template<> void nest::RecordablesMap< aeif_cond_alpha >::create ()
References nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
template<> void nest::RecordablesMap< iaf_cond_alpha >::create ()
References nest::names::g_ex, nest::names::g_in, nest::iaf_cond_alpha::get_r_(), nest::names::t_ref_remaining, and nest::names::V_m.
template<> void nest::RecordablesMap< aeif_cond_exp >::create ()
References nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
template<> void nest::RecordablesMap< iaf_cond_alpha_mc >::create ()
References nest::iaf_cond_alpha_mc::DIST, nest::iaf_cond_alpha_mc::State_::G_EXC, nest::iaf_cond_alpha_mc::State_::G_INH, nest::iaf_cond_alpha_mc::get_r_(), nest::iaf_cond_alpha_mc::get_y_elem_(), nest::iaf_cond_alpha_mc::PROX, nest::iaf_cond_alpha_mc::SOMA, nest::names::t_ref_remaining, and nest::iaf_cond_alpha_mc::State_::V_M.
template<typename HostNode > void nest::RecordablesMap< HostNode >::create ()
Create the map.
This function must be specialized for each class owning a Recordables map and must fill the map. This should happen as part of the original constructor for the Node.
References assert().
template<> void nest::RecordablesMap< mcculloch_pitts_neuron >::create ()
template<> void nest::RecordablesMap< ginzburg_neuron >::create ()
template<typename HostNode> ArrayDatum nest::RecordablesMap< HostNode >::get_list () const inline
Obtain SLI list of all recordables, for use by get_status().
Todo:
This fct should return the recordables_ entry, but since filling recordables_ leads to seg fault on exit, we just build the list every time, even though that beats the goal of being more efficient ...
template<typename HostNode> void nest::RecordablesMap< HostNode >::insert_ (const Name & n, const DataAccessFct f) inline private
Insertion functions to be used in create(), adds entry to map and list.
The documentation for this class was generated from the following file:
recordables_map.h