NEST: Cvlit_pFunction Class Reference
Cvlit_pFunction Class Reference
#include <slidata.h>
Public Member Functions
Cvlit_pFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
Cvlit_pFunction::Cvlit_pFunction () inline
Member Function Documentation
void Cvlit_pFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References assert(), Token::datum(), SLIInterpreter::EStack, TokenStack::load(), SLIInterpreter::OStack, TokenStack::pop(), Token::swap(), and TokenStack::top().
The documentation for this class was generated from the following files:
slidata.h
slidata.cc