NEST: Processes::GetPIDFunction Class Reference
Processes::GetPIDFunction Class Reference
#include <processes.h>
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void Processes::GetPIDFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::EStack, SLIInterpreter::OStack, TokenStack::pop(), TokenStack::push_move(), SLIInterpreter::raiseerror(), and Processes::systemerror().
The documentation for this class was generated from the following files:
processes.h
processes.cc