NEST: two_d_iterator< containertype > Class Template Reference
two_d_iterator< containertype > Class Template Reference
#include <sparsetable.h>
Public Types
typedef two_d_iterator iterator
typedef
std::bidirectional_iterator_tag iterator_category
typedef containertype::value_type _tmp_vt
typedef _tmp_vt::value_type value_type
typedef _tmp_vt::difference_type difference_type
typedef _tmp_vt::reference reference
typedef _tmp_vt::pointer pointer
Public Member Functions
two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr)
two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr, typename containertype::value_type::TWOD_ITER_ col)
two_d_iterator ()
reference operator* () const
pointer operator-> () const
void advance_past_end ()
iterator & operator++ ()
iterator & operator-- ()
iterator operator++ (int)
iterator operator-- (int)
bool operator== (const iterator &it) const
bool operator!= (const iterator &it) const
Public Attributes
containertype::iterator row_begin
containertype::iterator row_end
containertype::iterator row_current
containertype::value_type::TWOD_ITER_ col_current
Member Typedef Documentation
template<class containertype> typedef containertype::value_type two_d_iterator< containertype >::_tmp_vt
template<class containertype> typedef _tmp_vt::difference_type two_d_iterator< containertype >::difference_type
template<class containertype> typedef two_d_iterator two_d_iterator< containertype >::iterator
template<class containertype> typedef std::bidirectional_iterator_tag two_d_iterator< containertype >::iterator_category
template<class containertype> typedef _tmp_vt::pointer two_d_iterator< containertype >::pointer
template<class containertype> typedef _tmp_vt::reference two_d_iterator< containertype >::reference
template<class containertype> typedef _tmp_vt::value_type two_d_iterator< containertype >::value_type
Constructor & Destructor Documentation
template<class containertype> two_d_iterator< containertype >::two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr) inline
References two_d_iterator< containertype >::advance_past_end(), two_d_iterator< containertype >::col_current, two_d_iterator< containertype >::row_current, and two_d_iterator< containertype >::row_end.
template<class containertype> two_d_iterator< containertype >::two_d_iterator (typename containertype::iterator begin, typename containertype::iterator end, typename containertype::iterator curr, typename containertype::value_type::TWOD_ITER_ col) inline
References two_d_iterator< containertype >::advance_past_end().
template<class containertype> two_d_iterator< containertype >::two_d_iterator () inline
Member Function Documentation
template<class containertype> void two_d_iterator< containertype >::advance_past_end () inline
References two_d_iterator< containertype >::col_current, two_d_iterator< containertype >::row_current, and two_d_iterator< containertype >::row_end.
Referenced by two_d_iterator< containertype >::operator++(), and two_d_iterator< containertype >::two_d_iterator().
template<class containertype> bool two_d_iterator< containertype >::operator!= (const iterator & it) const inline
template<class containertype> reference two_d_iterator< containertype >::operator* () const inline
References two_d_iterator< containertype >::col_current.
Referenced by two_d_iterator< containertype >::operator->().
template<class containertype> iterator& two_d_iterator< containertype >::operator++ () inline
References two_d_iterator< containertype >::advance_past_end(), assert(), two_d_iterator< containertype >::col_current, two_d_iterator< containertype >::row_current, and two_d_iterator< containertype >::row_end.
template<class containertype> iterator two_d_iterator< containertype >::operator++ (int) inline
template<class containertype> iterator& two_d_iterator< containertype >::operator-- () inline
References assert(), two_d_iterator< containertype >::col_current, two_d_iterator< containertype >::row_begin, two_d_iterator< containertype >::row_current, and two_d_iterator< containertype >::row_end.
template<class containertype> iterator two_d_iterator< containertype >::operator-- (int) inline
template<class containertype> pointer two_d_iterator< containertype >::operator-> () const inline
References two_d_iterator< containertype >::operator*().
template<class containertype> bool two_d_iterator< containertype >::operator== (const iterator & it) const inline
References two_d_iterator< containertype >::col_current, two_d_iterator< containertype >::row_begin, two_d_iterator< containertype >::row_current, and two_d_iterator< containertype >::row_end.
Member Data Documentation
template<class containertype> containertype::value_type::TWOD_ITER_ two_d_iterator< containertype >::col_current
Referenced by two_d_iterator< containertype >::advance_past_end(), two_d_iterator< containertype >::operator*(), two_d_iterator< containertype >::operator++(), two_d_iterator< containertype >::operator--(), two_d_iterator< containertype >::operator==(), and two_d_iterator< containertype >::two_d_iterator().
template<class containertype> containertype::iterator two_d_iterator< containertype >::row_begin
Referenced by two_d_iterator< containertype >::operator--(), and two_d_iterator< containertype >::operator==().
template<class containertype> containertype::iterator two_d_iterator< containertype >::row_current
Referenced by two_d_iterator< containertype >::advance_past_end(), two_d_iterator< containertype >::operator++(), two_d_iterator< containertype >::operator--(), two_d_iterator< containertype >::operator==(), and two_d_iterator< containertype >::two_d_iterator().
template<class containertype> containertype::iterator two_d_iterator< containertype >::row_end
Referenced by two_d_iterator< containertype >::advance_past_end(), two_d_iterator< containertype >::operator++(), two_d_iterator< containertype >::operator--(), two_d_iterator< containertype >::operator==(), and two_d_iterator< containertype >::two_d_iterator().
The documentation for this class was generated from the following file:
sparsetable.h