NEST: TrieDatum Class Reference
TrieDatum Class Reference
#include <triedatum.h>
Public Member Functions
TrieDatum (TrieDatum const &fd)
TrieDatum (Name const &n)
TrieDatum (Name const &n, const TokenArray &ta)
void print (std::ostream &o) const
void pprint (std::ostream &o) const
void info (std::ostream &out) const
bool equals (Datum const *) const
const Name & getname (void) const
void insert (const TypeArray &a, const Token &t)
void insert_move (const TypeArray &a, Token &t)
const Token & lookup (const TokenStack &s) const
TypeTrie & get (void)
Public Member Functions inherited from TypedDatum<&SLIInterpreter::Trietype >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
virtual void list (std::ostream &o, std::string prefix, int l) const
virtual void input_form (std::ostream &o) const
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Static Protected Attributes
static sli::pool memory
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
Datum * get_ptr ()
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
Private Attributes
Name name
TypeTrie tree
Additional Inherited Members
Protected Member Functions inherited from TypedDatum<&SLIInterpreter::Trietype >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Constructor & Destructor Documentation
TrieDatum::TrieDatum (TrieDatum const & fd) inline
References Datum::set_executable().
Referenced by clone().
TrieDatum::TrieDatum (Name const & n) inline
References Datum::set_executable().
TrieDatum::TrieDatum (Name const & n, const TokenArray & ta) inline
References Datum::set_executable().
Member Function Documentation
Datum* TrieDatum::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Implements Datum.
References TrieDatum().
bool TrieDatum::equals (Datum const * dat) const virtual
Reimplemented from Datum.
References tree.
TypeTrie& TrieDatum::get (void) inline
References tree.
Referenced by TrieInfoFunction::execute(), Cva_tFunction::execute(), and SLIInterpreter::print_error().
Datum* TrieDatum::get_ptr () inline private virtual
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
The prefix const indicates that the pointer should be trated as const because changes affect all other references as well.
Reimplemented from Datum.
References Datum::addReference().
const Name& TrieDatum::getname (void) const inline
References name.
Referenced by AddtotrieFunction::execute(), Cva_tFunction::execute(), and SLIInterpreter::getcurrentname().
void TrieDatum::info (std::ostream & out) const inline virtual
Reimplemented from Datum.
References TypeTrie::info(), pprint(), and tree.
void TrieDatum::insert (const TypeArray & a, const Token & t) inline
References TypeTrie::insert(), and tree.
void TrieDatum::insert_move (const TypeArray & a, Token & t) inline
References TypeTrie::insert_move(), and tree.
Referenced by AddtotrieFunction::execute().
const Token& TrieDatum::lookup (const TokenStack & s) const inline
References TypeTrie::lookup(), and tree.
Referenced by TrietypeFunction::execute().
static void TrieDatum::operator delete (void * p, size_t size) inline static
References sli::pool::free(), memory, nest::names::p, and sli::pool::size_of().
static void* TrieDatum::operator new (size_t size) inline static
References sli::pool::alloc(), memory, and sli::pool::size_of().
void TrieDatum::pprint (std::ostream & o) const inline virtual
Implements Datum.
References print().
Referenced by info().
void TrieDatum::print (std::ostream & o) const inline virtual
Implements Datum.
References name.
Referenced by pprint(), and SLIInterpreter::stack_backtrace().
Member Data Documentation
sli::pool TrieDatum::memory static protected
Referenced by operator delete(), and operator new().
Name TrieDatum::name private
Referenced by getname(), and print().
TypeTrie TrieDatum::tree private
Referenced by equals(), get(), info(), insert(), insert_move(), and lookup().
The documentation for this class was generated from the following files:
triedatum.h
triedatum.cc