NEST: CharCode Class Reference
CharCode Class Reference
#include <charcode.h>
Public Member Functions
CharCode (size_t, size_t)
void Range (size_t, char, char)
void Group (size_t, const char *)
size_t operator() (char) const
Constructor & Destructor Documentation
CharCode::CharCode (size_t n, size_t def)
Member Function Documentation
void CharCode::Group (size_t code, const char * g)
References assert(), and nest::names::c.
Referenced by Scanner::Scanner().
size_t CharCode::operator() (char c) const
References assert(), and nest::names::c.
void CharCode::Range (size_t code, char lc, char uc)
References assert().
Referenced by Scanner::Scanner().
The documentation for this class was generated from the following files:
charcode.h
charcode.cc