NEST: RepeatFunction Class Reference
RepeatFunction Class Reference
#include <slicontrol.h>
Public Member Functions
RepeatFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
RepeatFunction::RepeatFunction () inline
Member Function Documentation
void RepeatFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::baselookup(), Token::datum(), SLIInterpreter::EStack, SLIInterpreter::inc_call_depth(), SLIInterpreter::irepeat_name, TokenStack::load(), SLIInterpreter::mark_name, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push_by_pointer(), TokenStack::push_by_ref(), TokenStack::push_move(), and TokenStack::top().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc