NEST: nest::TargetIdentifierIndex Class Reference
nest::TargetIdentifierIndex Class Reference
Class providing compact (hpc) target identified by index.
#include <target_identifier.h>
Public Member Functions
TargetIdentifierIndex ()
TargetIdentifierIndex (const TargetIdentifierIndex &t)
void get_status (DictionaryDatum &d) const
Node * get_target_ptr (thread t) const
rport get_rport () const
void set_target (Node *target)
void set_rport (rport rprt)
Private Attributes
targetindex target_
Target node.
Detailed Description
Class providing compact (hpc) target identified by index.
This class represents a connection target using a thread-local index, while fixing the rport to 0. Connection classes with this class as template argument provide "hpc" synapses with minimal memory requirement..
See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3.3.
Constructor & Destructor Documentation
nest::TargetIdentifierIndex::TargetIdentifierIndex () inline
nest::TargetIdentifierIndex::TargetIdentifierIndex (const TargetIdentifierIndex & t) inline
Member Function Documentation
rport nest::TargetIdentifierIndex::get_rport () const inline
void nest::TargetIdentifierIndex::get_status (DictionaryDatum & d) const inline
References nest::names::d, nest::invalid_targetindex, nest::names::rport, nest::names::target, and target_.
Node* nest::TargetIdentifierIndex::get_target_ptr (thread t) const inline
References assert(), nest::NestModule::get_network(), nest::invalid_targetindex, target_, and nest::Network::thread_lid_to_node().
void nest::TargetIdentifierIndex::set_rport (rport rprt) inline
void nest::TargetIdentifierIndex::set_target (Node * target) inline
References nest::Network::ensure_valid_thread_local_ids(), nest::NestModule::get_network(), nest::Node::get_thread_lid(), nest::max_targetindex, and target_.
Member Data Documentation
targetindex nest::TargetIdentifierIndex::target_ private
Target node.
Referenced by get_status(), get_target_ptr(), and set_target().
The documentation for this class was generated from the following file:
target_identifier.h