NEST: IforFunction Class Reference
IforFunction Class Reference
#include <slibuiltins.h>
Public Member Functions
IforFunction ()
void execute (SLIInterpreter *) const
void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
Constructor & Destructor Documentation
IforFunction::IforFunction () inline
Member Function Documentation
void IforFunction::backtrace (SLIInterpreter * , int) const virtual
Show stack backtrace information on error.
This function tries to extract and display useful information from the execution stack if an error occurs. This function should be implemented for all functions which store administrative information on the execution stack. Examples are: loops and procedure iterations. backtrace() is only called, if the interpreter flag show_backtrace is set.
Reimplemented from SLIFunction.
References assert(), Token::datum(), SLIInterpreter::EStack, GenericDatum< D, slt >::get(), AggregateDatum< C, slt >::list(), and TokenStack::pick().
void IforFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References Token::datum(), SLIInterpreter::dec_call_depth(), SLIInterpreter::EStack, GenericDatum< D, slt >::get(), Datum::is_executable(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), and TokenStack::push().
The documentation for this class was generated from the following files:
slibuiltins.h
slibuiltins.cc