NEST: CountFunction Class Reference
CountFunction Class Reference
#include <slistack.h>
Public Member Functions
CountFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
CountFunction::CountFunction () inline
Member Function Documentation
void CountFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::EStack, TokenStack::load(), SLIInterpreter::OStack, TokenStack::pop(), and TokenStack::push_move().
The documentation for this class was generated from the following files:
slistack.h
slistack.cc