NEST: DebugOnFunction Class Reference
DebugOnFunction Class Reference
#include <slicontrol.h>
Public Member Functions
DebugOnFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
DebugOnFunction::DebugOnFunction () inline
Member Function Documentation
void DebugOnFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::debug_mode_on(), SLIInterpreter::debug_options(), SLIInterpreter::EStack, SLIInterpreter::get_call_depth(), TokenStack::pop(), and SLIInterpreter::set_max_call_depth().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc