NEST: UnitStep_iaFunction Class Reference
UnitStep_iaFunction Class Reference
#include <slimath.h>
Public Member Functions
UnitStep_iaFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
UnitStep_iaFunction::UnitStep_iaFunction () inline
Member Function Documentation
void UnitStep_iaFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References nest::names::a, assert(), Token::datum(), SLIInterpreter::EStack, GenericDatum< D, slt >::get(), TokenStack::load(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push_by_pointer(), and nest::names::x.
The documentation for this class was generated from the following files:
slimath.h
slimath.cc