NEST: NumericDatum< D, slt > Class Template Reference
NumericDatum< D, slt > Class Template Reference
#include <numericdatum.h>
Public Member Functions
NumericDatum ()
NumericDatum (const D &d_s)
virtual ~NumericDatum ()
operator D () const
operator D & ()
void input_form (std::ostream &) const
void pprint (std::ostream &) const
template<>
void input_form (std::ostream &o) const
template<>
void pprint (std::ostream &o) const
template<>
void input_form (std::ostream &) const
template<>
void pprint (std::ostream &) const
Public Member Functions inherited from GenericDatum< D, slt >
GenericDatum ()
virtual ~GenericDatum ()
GenericDatum (const D &d_s)
GenericDatum (const GenericDatum< D, slt > &gd)
const D & operator= (const D &d_s)
const D & get (void) const
D & get (void)
D & get_lval ()
void print (std::ostream &o) const
void info (std::ostream &out) const
bool equals (const Datum *dat) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
virtual void list (std::ostream &o, std::string prefix, int l) const
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Protected Member Functions
template<>
sli::pool memory (sizeof(DoubleDatum), 1024, 1)
template<>
sli::pool memory
template<>
sli::pool memory (sizeof(IntegerDatum), 10240, 1)
template<>
sli::pool memory
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Static Protected Attributes
static sli::pool memory
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
Additional Inherited Members
Protected Attributes inherited from GenericDatum< D, slt >
D d
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Constructor & Destructor Documentation
template<class D, SLIType * slt> NumericDatum< D, slt >::NumericDatum () inline
References GenericDatum< D, slt >::d.
template<class D, SLIType * slt> NumericDatum< D, slt >::NumericDatum (const D & d_s) inline
References GenericDatum< D, slt >::d.
template<class D, SLIType * slt> virtual NumericDatum< D, slt >::~NumericDatum () inline virtual
Member Function Documentation
template<class D, SLIType * slt> Datum* NumericDatum< D, slt >::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Reimplemented from GenericDatum< D, slt >.
template<> void NumericDatum< double,&SLIInterpreter::Doubletype >::input_form (std::ostream & o) const virtual
Reimplemented from Datum.
References nest::names::d, and nest::names::scientific.
template<> void NumericDatum< double,&SLIInterpreter::Doubletype >::input_form (std::ostream &) const virtual
Reimplemented from Datum.
template<class D , SLIType * slt> void NumericDatum< D, slt >::input_form (std::ostream & o) const virtual
Reimplemented from Datum.
template<> sli::pool NumericDatum< long,&SLIInterpreter::Integertype >::memory (sizeof(IntegerDatum) , 10240 , 1) protected
template<> sli::pool NumericDatum< double,&SLIInterpreter::Doubletype >::memory (sizeof(DoubleDatum) , 1024 , 1) protected
template<> sli::pool NumericDatum< long,&SLIInterpreter::Integertype >::memory () protected
template<> sli::pool NumericDatum< double,&SLIInterpreter::Doubletype >::memory () protected
Referenced by NumericDatum< D, slt >::operator delete(), and NumericDatum< D, slt >::operator new().
template<class D, SLIType * slt> NumericDatum< D, slt >::operator D () const inline
References GenericDatum< D, slt >::d.
template<class D, SLIType * slt> NumericDatum< D, slt >::operator D & () inline
References GenericDatum< D, slt >::d.
template<class D, SLIType * slt> static void NumericDatum< D, slt >::operator delete (void * p, size_t size) inline static
References sli::pool::free(), NumericDatum< D, slt >::memory(), nest::names::p, and sli::pool::size_of().
template<class D, SLIType * slt> static void* NumericDatum< D, slt >::operator new (size_t size) inline static
References sli::pool::alloc(), NumericDatum< D, slt >::memory(), and sli::pool::size_of().
template<> void NumericDatum< double,&SLIInterpreter::Doubletype >::pprint (std::ostream & o) const virtual
Reimplemented from GenericDatum< D, slt >.
References nest::names::d, and nest::names::scientific.
template<> void NumericDatum< double,&SLIInterpreter::Doubletype >::pprint (std::ostream &) const virtual
Reimplemented from GenericDatum< D, slt >.
template<class D , SLIType * slt> void NumericDatum< D, slt >::pprint (std::ostream & o) const virtual
Reimplemented from GenericDatum< D, slt >.
Member Data Documentation
template<class D, SLIType * slt> sli::pool NumericDatum< D, slt >::memory static protected
The documentation for this class was generated from the following files:
numericdatum.h
numericdatum_impl.h