NEST: nest::DataLoggingReply Class Reference
nest::DataLoggingReply Class Reference
Event types for analog logging devices.
Provide logged data through request transmitting reference.
#include <event.h>
Classes
struct Item
Data item with pertaining time stamp.
Public Types
typedef std::vector< double_t > DataItem
Data type data at single recording time.
typedef std::vector< Item > Container
Container for entries.
Public Member Functions
DataLoggingReply (const Container &)
Construct with reference to data and time stamps to transmit.
void operator() ()
Deliver the event to receiver.
const Container & get_info () const
Access referenced data.
Public Member Functions inherited from nest::Event
Event ()
virtual ~Event ()
void set_receiver (Node &)
Change pointer to receiving Node.
Node & get_receiver () const
Return reference to receiving Node.
Node & get_sender () const
Return reference to sending Node.
void set_sender (Node &)
Change pointer to sending Node.
index get_sender_gid () const
Return GID of sending Node.
void set_sender_gid (index)
Change GID of sending Node.
Time const & get_stamp () const
Return time stamp of the event.
void set_delay (delay)
Set the transmission delay of the event.
delay get_delay () const
Return transmission delay of the event.
delay get_max_delay () const
long_t get_rel_delivery_steps (const Time &t) const
Relative spike delivery time in steps.
port get_port () const
Return the sender port number of the event.
rport get_rport () const
Return the receiver port number of the event.
void set_port (port p)
Set the port number.
void set_rport (rport p)
Set the receiver port number (r-port).
double_t get_offset () const
Return the creation time offset of the Event.
void set_offset (double_t t)
Set the creation time of the Event.
weight get_weight () const
Return the weight.
void set_weight (weight t)
Set weight of the event.
bool is_valid () const
Check integrity of the event.
void set_stamp (Time const &)
Set the time stamp of the event.
Private Member Functions
DataLoggingReply (const DataLoggingReply &)
Prohibit copying.
DataLoggingReply * clone () const
Prohibit cloning.
Private Attributes
const Container & info_
data to be transmitted, with time stamps
Additional Inherited Members
Protected Attributes inherited from nest::Event
index sender_gid_
GID of sender or -1.
Node * sender_
Pointer to sender or NULL.
Node * receiver_
Pointer to receiver or NULL.
port p_
Sender port number.
rport rp_
Receiver port number (r-port).
delay d_
Transmission delay.
Time stamp_
Time stamp.
double offset_
Offset for precise spike times.
weight w_
Weight of the connection.
Detailed Description
Provide logged data through request transmitting reference.
See also
DataLoggingRequest
Member Typedef Documentation
typedef std::vector<Item> nest::DataLoggingReply::Container
Container for entries.
typedef std::vector<double_t> nest::DataLoggingReply::DataItem
Data type data at single recording time.
Constructor & Destructor Documentation
nest::DataLoggingReply::DataLoggingReply (const Container & d) inline
Construct with reference to data and time stamps to transmit.
nest::DataLoggingReply::DataLoggingReply (const DataLoggingReply &) private
Prohibit copying.
Member Function Documentation
DataLoggingReply* nest::DataLoggingReply::clone () const inline private virtual
Prohibit cloning.
Implements nest::Event.
References assert().
const Container& nest::DataLoggingReply::get_info () const inline
Access referenced data.
References info_.
Referenced by nest::Multimeter::handle().
void nest::DataLoggingReply::operator() () virtual
Deliver the event to receiver.
This operator calls the handler for the specific event type at the receiver.
Implements nest::Event.
References nest::Node::handle(), and nest::Event::receiver_.
Member Data Documentation
const Container& nest::DataLoggingReply::info_ private
data to be transmitted, with time stamps
Referenced by get_info().
The documentation for this class was generated from the following files:
event.h
event.cpp