NEST: TokenStack Class Reference
TokenStack Class Reference
#include <tokenstack.h>
Public Member Functions
TokenStack (Index n)
TokenStack (const TokenArray &ta)
void clear (void)
void push (const Token &e)
void push_move (Token &e)
void push_by_ref (const Token &e)
Push a Token with a valid datum to the stack.
void push_by_pointer (Datum *rhs)
Push a valid datum to the stack.
void pop (void)
void pop_move (Token &e)
void pop (size_t n)
Token & top (void)
const Token & top (void) const
const Token & pick (size_t i) const
Token & pick (size_t i)
void swap (void)
void swap (Token &e)
void index (Index i)
void roll (size_t n, long k)
Index size (void) const
Index load (void) const
void dump (std::ostream &) const
TokenArray toArray (void) const
Additional Inherited Members
Private Member Functions inherited from TokenArrayObj
TokenArrayObj (void)
TokenArrayObj (size_t, const Token &=Token(), size_t=0)
TokenArrayObj (const TokenArrayObj &)
virtual ~TokenArrayObj ()
Token * begin () const
Token * end () const
size_t size (void) const
size_t capacity (void) const
Token & operator[] (size_t i)
const Token & operator[] (size_t i) const
const Token & get (long i) const
bool index_is_valid (long i) const
void rotate (Token *, Token *, Token *)
bool shrink (void)
bool reserve (size_t)
unsigned int references (void)
unsigned int remove_reference ()
unsigned int add_reference ()
void resize (size_t, size_t, const Token &=Token())
void resize (size_t, const Token &=Token())
void reserve_token (size_t n)
void push_back (const Token &t)
void push_back_move (Token &t)
void push_back_by_ref (const Token &t)
Push back a reference.
void push_back_by_pointer (Datum *rhs)
Push back a datum pointer.
void assign_move (Token *tp, Token &t)
void pop_back (void)
void erase (size_t, size_t)
void erase (Token *, Token *)
void erase (Token *tp)
void reduce (Token *, Token *)
void reduce (size_t, size_t)
void insert (size_t, size_t=1, const Token &=Token())
void insert (size_t i, const Token &t)
void insert_move (size_t, TokenArrayObj &)
void insert_move (size_t, Token &)
void assign_move (TokenArrayObj &, size_t, size_t)
void assign (const TokenArrayObj &, size_t, size_t)
void replace_move (size_t, size_t, TokenArrayObj &)
void append_move (TokenArrayObj &)
void clear (void)
const TokenArrayObj & operator= (const TokenArrayObj &)
bool operator== (const TokenArrayObj &) const
bool empty (void) const
void info (std::ostream &) const
bool valid (void) const
Static Private Member Functions inherited from TokenArrayObj
static size_t getallocations (void)
Constructor & Destructor Documentation
TokenStack::TokenStack (Index n) inline
TokenStack::TokenStack (const TokenArray & ta) inline
Member Function Documentation
void TokenStack::clear (void) inline
References TokenArrayObj::begin(), TokenArrayObj::end(), and TokenArrayObj::erase().
Referenced by QuitFunction::execute(), CloseinputFunction::execute(), ClearFunction::execute(), StopFunction::execute(), StartFunction::execute(), Parser::operator()(), and SLIInterpreter::~SLIInterpreter().
void TokenStack::dump (std::ostream & out) const
References load(), pick(), and Token::pprint().
Referenced by SLIInterpreter::debug_commandline(), OStackdumpFunction::execute(), EStackdumpFunction::execute(), SLIInterpreter::execute_(), and SLIInterpreter::execute_debug_().
void TokenStack::index (Index i) inline
References pick(), and push().
Referenced by DupFunction::execute(), IndexFunction::execute(), OverFunction::execute(), and CopyFunction::execute().
Index TokenStack::load (void) const inline
References TokenArrayObj::size().
Referenced by SLIInterpreter::assert_stack_load(), SLIInterpreter::debug_commandline(), dump(), eq_execute(), TrieFunction::execute(), PopFunction::execute(), Add_diFunction::execute(), Get_aFunction::execute(), NpopFunction::execute(), Add_iiFunction::execute(), AddtotrieFunction::execute(), Get_a_aFunction::execute(), DictputFunction::execute(), RegexpModule::RegcompFunction::execute(), SLIgraphics::ReadPGMFunction::execute(), SLIArrayModule::IMapFunction::execute(), DupFunction::execute(), Add_idFunction::execute(), RegexpModule::RegexecFunction::execute(), DictgetFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), ExchFunction::execute(), Add_ddFunction::execute(), SLIgraphics::WritePGMFunction::execute(), RegexpModule::RegerrorFunction::execute(), Get_pFunction::execute(), DictbeginFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), IndexFunction::execute(), TypeFunction::execute(), Sub_diFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), Get_lpFunction::execute(), LoopFunction::execute(), RollFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), SpecialFunctionsModule::GammaIncFunction::execute(), Sub_iiFunction::execute(), Append_aFunction::execute(), ExitFunction::execute(), RolluFunction::execute(), SpecialFunctionsModule::LambertW0Function::execute(), Append_pFunction::execute(), Sub_idFunction::execute(), RolldFunction::execute(), SLIArrayModule::IMapIndexedFunction::execute(), SpecialFunctionsModule::LambertWm1Function::execute(), DictinfoFunction::execute(), Append_sFunction::execute(), IfFunction::execute(), RotFunction::execute(), Sub_ddFunction::execute(), SLIArrayModule::RangeFunction::execute(), SpecialFunctionsModule::ErfFunction::execute(), DicttopinfoFunction::execute(), Prepend_aFunction::execute(), IfelseFunction::execute(), OverFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), SpecialFunctionsModule::ErfcFunction::execute(), WhoFunction::execute(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), Mul_diFunction::execute(), Prepend_pFunction::execute(), RepeatFunction::execute(), CountFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), DictconstructFunction::execute(), Prepend_sFunction::execute(), CloseinputFunction::execute(), Mul_iiFunction::execute(), SLIArrayModule::ArraycreateFunction::execute(), CopyFunction::execute(), Join_sFunction::execute(), StoppedFunction::execute(), Mul_idFunction::execute(), Join_aFunction::execute(), StopFunction::execute(), SLIArrayModule::FlattenFunction::execute(), Mul_ddFunction::execute(), Join_pFunction::execute(), CurrentnameFunction::execute(), RestoreestackFunction::execute(), Insert_sFunction::execute(), Div_diFunction::execute(), RestoreostackFunction::execute(), Length_dFunction::execute(), Insert_aFunction::execute(), SLIArrayModule::TransposeFunction::execute(), Div_iiFunction::execute(), Empty_DFunction::execute(), InsertElement_sFunction::execute(), SLIArrayModule::PartitionFunction::execute(), Div_idFunction::execute(), InsertElement_aFunction::execute(), SLIArrayModule::ValidFunction::execute(), Div_ddFunction::execute(), Replace_sFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), DefFunction::execute(), UndefFunction::execute(), Replace_aFunction::execute(), SetFunction::execute(), Mod_iiFunction::execute(), Erase_sFunction::execute(), Cva_dFunction::execute(), Erase_aFunction::execute(), LookupFunction::execute(), Sin_dFunction::execute(), KeysFunction::execute(), Erase_pFunction::execute(), Asin_dFunction::execute(), ValuesFunction::execute(), Length_sFunction::execute(), Cos_dFunction::execute(), SLIArrayModule::AreaFunction::execute(), Length_aFunction::execute(), Acos_dFunction::execute(), Length_pFunction::execute(), Length_lpFunction::execute(), Exp_dFunction::execute(), Processes::Sysexec_aFunction::execute(), Processes::WaitPIDFunction::execute(), Capacity_aFunction::execute(), Ln_dFunction::execute(), Processes::KillFunction::execute(), Size_aFunction::execute(), Log_dFunction::execute(), Reserve_aFunction::execute(), SLIArrayModule::Area2Function::execute(), Processes::Dup2_is_isFunction::execute(), Sqr_dFunction::execute(), Processes::Dup2_os_osFunction::execute(), SLIArrayModule::Cv1dFunction::execute(), Resize_aFunction::execute(), Processes::Dup2_is_osFunction::execute(), SLIArrayModule::Cv2dFunction::execute(), Empty_aFunction::execute(), Sqrt_dFunction::execute(), Processes::Dup2_os_isFunction::execute(), SLIArrayModule::GetMaxFunction::execute(), References_aFunction::execute(), Processes::AvailableFunction::execute(), Pow_ddFunction::execute(), SLIArrayModule::GetMinFunction::execute(), Shrink_aFunction::execute(), Pow_diFunction::execute(), Capacity_sFunction::execute(), SLIArrayModule::GaborFunction::execute(), Processes::MkfifoFunction::execute(), Modf_dFunction::execute(), Size_sFunction::execute(), Reserve_sFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), Frexp_dFunction::execute(), Resize_sFunction::execute(), Ldexp_diFunction::execute(), Processes::SetNonblockFunction::execute(), SLIArrayModule::Array2IntVectorFunction::execute(), Empty_sFunction::execute(), Dexp_iFunction::execute(), Getinterval_sFunction::execute(), Processes::Isatty_isFunction::execute(), SLIArrayModule::Array2DoubleVectorFunction::execute(), Processes::Isatty_osFunction::execute(), Getinterval_aFunction::execute(), SwitchFunction::execute(), SLIArrayModule::DoubleVector2ArrayFunction::execute(), Abs_iFunction::execute(), Cvx_aFunction::execute(), SLIArrayModule::IntVector2ArrayFunction::execute(), Abs_dFunction::execute(), Cvlit_nFunction::execute(), SLIArrayModule::Add_iv_ivFunction::execute(), SLIArrayModule::Add_i_ivFunction::execute(), Cvlit_pFunction::execute(), Neg_iFunction::execute(), SLIArrayModule::Neg_ivFunction::execute(), Cvlp_pFunction::execute(), Neg_dFunction::execute(), SLIArrayModule::Sub_iv_ivFunction::execute(), RangeIterator_aFunction::execute(), SLIArrayModule::Mul_iv_ivFunction::execute(), Inv_dFunction::execute(), IteratorSize_iterFunction::execute(), SLIArrayModule::Mul_i_ivFunction::execute(), SwitchdefaultFunction::execute(), Cvn_sFunction::execute(), EqFunction::execute(), SLIArrayModule::Mul_d_ivFunction::execute(), SLIArrayModule::Div_iv_ivFunction::execute(), Cvn_lFunction::execute(), NeqFunction::execute(), SLIArrayModule::Add_dv_dvFunction::execute(), AndFunction::execute(), SLIArrayModule::Add_d_dvFunction::execute(), SLIArrayModule::Sub_dv_dvFunction::execute(), OrFunction::execute(), SLIArrayModule::Mul_dv_dvFunction::execute(), And_iiFunction::execute(), SLIArrayModule::Mul_d_dvFunction::execute(), Cvi_sFunction::execute(), SLIArrayModule::Div_dv_dvFunction::execute(), CounttomarkFunction::execute(), Or_iiFunction::execute(), SLIArrayModule::Neg_dvFunction::execute(), SLIArrayModule::Inv_dvFunction::execute(), XorFunction::execute(), SLIArrayModule::Length_dvFunction::execute(), SLIArrayModule::Length_ivFunction::execute(), Not_bFunction::execute(), SLIArrayModule::Get_iv_iFunction::execute(), SLIArrayModule::Get_iv_ivFunction::execute(), Not_iFunction::execute(), Cvd_sFunction::execute(), SLIArrayModule::Get_dv_ivFunction::execute(), Get_sFunction::execute(), Geq_iiFunction::execute(), SLIArrayModule::Get_dv_iFunction::execute(), Put_sFunction::execute(), SLIArrayModule::Put_dv_i_dFunction::execute(), Geq_idFunction::execute(), Token_sFunction::execute(), Put_aFunction::execute(), SLIArrayModule::Zeros_ivFunction::execute(), Geq_diFunction::execute(), Put_pFunction::execute(), SLIArrayModule::Zeros_dvFunction::execute(), Geq_ddFunction::execute(), Symbol_sFunction::execute(), Put_lpFunction::execute(), SLIArrayModule::Ones_dvFunction::execute(), SLIArrayModule::Ones_ivFunction::execute(), Search_sFunction::execute(), Leq_iiFunction::execute(), SLIArrayModule::ArangeFunction::execute(), Search_aFunction::execute(), Leq_idFunction::execute(), MessageFunction::execute(), Leq_diFunction::execute(), SetVerbosityFunction::execute(), Leq_ddFunction::execute(), Gt_iiFunction::execute(), Gt_ddFunction::execute(), DebugFunction::execute(), Gt_idFunction::execute(), Gt_diFunction::execute(), Gt_ssFunction::execute(), Lt_iiFunction::execute(), Lt_ddFunction::execute(), Lt_idFunction::execute(), Lt_diFunction::execute(), Lt_ssFunction::execute(), IntegerFunction::execute(), DoubleFunction::execute(), UnitStep_iFunction::execute(), UnitStep_dFunction::execute(), UnitStep_iaFunction::execute(), UnitStep_daFunction::execute(), Round_dFunction::execute(), Floor_dFunction::execute(), Ceil_dFunction::execute(), Max_i_iFunction::execute(), Max_i_dFunction::execute(), Max_d_iFunction::execute(), Max_d_dFunction::execute(), Min_i_iFunction::execute(), Min_i_dFunction::execute(), Min_d_iFunction::execute(), Min_d_dFunction::execute(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), nest::Network::execute_sli_protected(), TypeTrie::lookup(), SLIInterpreter::stack_backtrace(), and SLIInterpreter::startup().
const Token& TokenStack::pick (size_t i) const inline
References TokenArrayObj::end().
Referenced by SLIArrayModule::IMapFunction::backtrace(), IiterateFunction::backtrace(), SLIArrayModule::IMap_ivFunction::backtrace(), SLIArrayModule::IMap_dvFunction::backtrace(), IloopFunction::backtrace(), IrepeatFunction::backtrace(), SLIArrayModule::IMapThreadFunction::backtrace(), IforFunction::backtrace(), SLIArrayModule::IMapIndexedFunction::backtrace(), IforallarrayFunction::backtrace(), IforalliterFunction::backtrace(), IforallindexedarrayFunction::backtrace(), IforallindexedstringFunction::backtrace(), IforallstringFunction::backtrace(), SLIArrayModule::Iforall_ivFunction::backtrace(), SLIArrayModule::Iforall_dvFunction::backtrace(), dump(), eq_execute(), OOSupportModule::CallMemberFunction::execute(), Add_diFunction::execute(), TrieInfoFunction::execute(), Get_aFunction::execute(), SLIArrayModule::MapFunction::execute(), Add_iiFunction::execute(), AddtotrieFunction::execute(), Get_a_aFunction::execute(), DictputFunction::execute(), RegexpModule::RegcompFunction::execute(), SLIArrayModule::IMapFunction::execute(), Add_idFunction::execute(), RegexpModule::RegexecFunction::execute(), IiterateFunction::execute(), DictgetFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), SLIgraphics::WritePGMFunction::execute(), Add_ddFunction::execute(), RegexpModule::RegerrorFunction::execute(), Cvt_aFunction::execute(), Get_pFunction::execute(), nest::ConnectionGeneratorModule::CGConnect_cg_i_i_D_lFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), IloopFunction::execute(), nest::ConnectionGeneratorModule::CGConnect_cg_iV_iV_D_lFunction::execute(), Sub_diFunction::execute(), nest::TopologyModule::CreateLayer_DFunction::execute(), OfsopenFunction::execute(), Get_lpFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), IrepeatFunction::execute(), RollFunction::execute(), nest::ConnectionGeneratorModule::CGParse_sFunction::execute(), nest::TopologyModule::GetPosition_iFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), Append_aFunction::execute(), Sub_iiFunction::execute(), nest::ConnectionGeneratorModule::CGParseFile_sFunction::execute(), ExitFunction::execute(), nest::TopologyModule::Displacement_a_iFunction::execute(), IforFunction::execute(), nest::ConnectionGeneratorModule::CGSelectImplementation_s_sFunction::execute(), SLIArrayModule::MapIndexedFunction::execute(), Append_pFunction::execute(), RandomNumbers::CreateRNGFunction::execute(), Sub_idFunction::execute(), nest::TopologyModule::Distance_a_iFunction::execute(), nest::ConnectionGeneratorModule::CGSetMask_cg_iV_iVFunction::execute(), SLIArrayModule::IMapIndexedFunction::execute(), DictinfoFunction::execute(), IforallarrayFunction::execute(), Append_sFunction::execute(), RandomNumbers::CreateRDVFunction::execute(), IfFunction::execute(), nest::TopologyModule::GetGlobalChildren_i_M_aFunction::execute(), nest::ConnectionGeneratorModule::CGStart_cgFunction::execute(), Sub_ddFunction::execute(), SLIArrayModule::RangeFunction::execute(), RandomNumbers::SetStatus_vdFunction::execute(), FilesystemModule::CompareFilesFunction::execute(), nest::ConnectionGeneratorModule::CGNext_cgFunction::execute(), IforalliterFunction::execute(), Prepend_aFunction::execute(), IfelseFunction::execute(), nest::TopologyModule::ConnectLayers_i_i_DFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), nest::TopologyModule::CreateMask_DFunction::execute(), Prepend_pFunction::execute(), Mul_diFunction::execute(), RepeatFunction::execute(), IforallindexedarrayFunction::execute(), SpecialFunctionsModule::GaussDiskConvFunction::execute(), RandomNumbers::IrandFunction::execute(), DictconstructFunction::execute(), nest::TopologyModule::Inside_a_MFunction::execute(), Prepend_sFunction::execute(), CloseinputFunction::execute(), SLIArrayModule::ArraycreateFunction::execute(), Mul_iiFunction::execute(), IforallindexedstringFunction::execute(), PrintFunction::execute(), nest::TopologyModule::And_M_MFunction::execute(), Join_sFunction::execute(), RandomNumbers::SeedFunction::execute(), PrettyprintFunction::execute(), nest::TopologyModule::Or_M_MFunction::execute(), IforallstringFunction::execute(), Mul_idFunction::execute(), SLIArrayModule::RotateFunction::execute(), Join_aFunction::execute(), StopFunction::execute(), RandomNumbers::RandomArrayFunction::execute(), nest::TopologyModule::Sub_M_MFunction::execute(), Mul_ddFunction::execute(), Join_pFunction::execute(), CurrentnameFunction::execute(), nest::TopologyModule::Mul_P_PFunction::execute(), Insert_sFunction::execute(), nest::TopologyModule::Div_P_PFunction::execute(), Div_diFunction::execute(), nest::TopologyModule::Add_P_PFunction::execute(), Insert_aFunction::execute(), Div_iiFunction::execute(), nest::TopologyModule::Sub_P_PFunction::execute(), InsertElement_sFunction::execute(), SLIArrayModule::PartitionFunction::execute(), EndsFunction::execute(), nest::TopologyModule::CreateParameter_DFunction::execute(), Div_idFunction::execute(), InsertElement_aFunction::execute(), IparseFunction::execute(), nest::TopologyModule::GetValue_a_PFunction::execute(), Replace_sFunction::execute(), Div_ddFunction::execute(), DefFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), nest::NestModule::ChangeSubnet_iFunction::execute(), nest::TopologyModule::DumpLayerNodes_os_iFunction::execute(), SetwFunction::execute(), UndefFunction::execute(), Replace_aFunction::execute(), SetFunction::execute(), nest::TopologyModule::DumpLayerConnections_os_i_lFunction::execute(), SetprecisionFunction::execute(), Mod_iiFunction::execute(), KnownFunction::execute(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), Erase_sFunction::execute(), nest::TopologyModule::GetElement_i_iaFunction::execute(), IOSFixedFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::TopologyModule::Cvdict_MFunction::execute(), Erase_aFunction::execute(), Sin_dFunction::execute(), IOSScientificFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), Erase_pFunction::execute(), ForFunction::execute(), Asin_dFunction::execute(), IOSDefaultFunction::execute(), nest::NestModule::GetStatus_iFunction::execute(), Forall_aFunction::execute(), nest::NestModule::GetStatus_CFunction::execute(), IOSShowpointFunction::execute(), Cos_dFunction::execute(), SLIArrayModule::AreaFunction::execute(), Forall_iterFunction::execute(), nest::NestModule::GetStatus_aFunction::execute(), IOSNoshowpointFunction::execute(), Acos_dFunction::execute(), nest::NestModule::SetStatus_idFunction::execute(), Forallindexed_aFunction::execute(), IOSShowbaseFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), Forallindexed_sFunction::execute(), Exp_dFunction::execute(), IOSNoshowbaseFunction::execute(), Processes::WaitPIDFunction::execute(), Forall_sFunction::execute(), Ln_dFunction::execute(), IOSDecFunction::execute(), nest::NestModule::SetStatus_aaFunction::execute(), Processes::KillFunction::execute(), nest::NestModule::SetDefaults_l_DFunction::execute(), IOSHexFunction::execute(), Log_dFunction::execute(), Reserve_aFunction::execute(), SLIArrayModule::Area2Function::execute(), Processes::Dup2_is_isFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), IOSOctFunction::execute(), Processes::Dup2_os_osFunction::execute(), Sqr_dFunction::execute(), SLIArrayModule::Cv1dFunction::execute(), Resize_aFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), IOSLeftFunction::execute(), Processes::Dup2_is_osFunction::execute(), SLIArrayModule::Cv2dFunction::execute(), nest::NestModule::GetConnections_DFunction::execute(), Sqrt_dFunction::execute(), Processes::Dup2_os_isFunction::execute(), IOSRightFunction::execute(), IOSInternalFunction::execute(), Pow_ddFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), Pow_diFunction::execute(), SLIArrayModule::GaborFunction::execute(), Modf_dFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), Reserve_sFunction::execute(), Frexp_dFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), Resize_sFunction::execute(), Ldexp_diFunction::execute(), Processes::SetNonblockFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), Dexp_iFunction::execute(), Processes::Isatty_isFunction::execute(), Getinterval_sFunction::execute(), nest::NestModule::Connect_g_g_D_DFunction::execute(), Processes::Isatty_osFunction::execute(), Getinterval_aFunction::execute(), SwitchFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), SLIArrayModule::Add_iv_ivFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), SLIArrayModule::Add_i_ivFunction::execute(), nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute(), SLIArrayModule::Neg_ivFunction::execute(), SLIArrayModule::Sub_iv_ivFunction::execute(), SLIArrayModule::Mul_iv_ivFunction::execute(), SLIArrayModule::Mul_i_ivFunction::execute(), SwitchdefaultFunction::execute(), nest::NestModule::PrintNetworkFunction::execute(), EqFunction::execute(), SLIArrayModule::Mul_d_ivFunction::execute(), SLIArrayModule::Div_iv_ivFunction::execute(), NeqFunction::execute(), SLIArrayModule::Add_dv_dvFunction::execute(), nest::NestModule::SetFakeNumProcessesFunction_i::execute(), AndFunction::execute(), nest::NestModule::SetNumRecProcessesFunction_i::execute(), SLIArrayModule::Add_d_dvFunction::execute(), SLIArrayModule::Sub_dv_dvFunction::execute(), OrFunction::execute(), nest::NestModule::TimeCommunication_i_i_bFunction::execute(), SLIArrayModule::Mul_dv_dvFunction::execute(), nest::NestModule::TimeCommunicationv_i_iFunction::execute(), CaseFunction::execute(), And_iiFunction::execute(), SLIArrayModule::Mul_d_dvFunction::execute(), nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute(), SLIArrayModule::Div_dv_dvFunction::execute(), CounttomarkFunction::execute(), nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute(), Or_iiFunction::execute(), XorFunction::execute(), nest::NestModule::MPIAbort_iFunction::execute(), nest::NestModule::GetVpRngFunction::execute(), SLIArrayModule::Get_iv_iFunction::execute(), nest::NestModule::Cvdict_CFunction::execute(), SLIArrayModule::Get_iv_ivFunction::execute(), nest::NestModule::Cvgidcollection_i_iFunction::execute(), SLIArrayModule::Get_dv_ivFunction::execute(), Sleep_iFunction::execute(), Get_sFunction::execute(), nest::NestModule::Cvgidcollection_iaFunction::execute(), Geq_iiFunction::execute(), SLIArrayModule::Get_dv_iFunction::execute(), nest::NestModule::Cvgidcollection_ivFunction::execute(), Put_sFunction::execute(), Sleep_dFunction::execute(), SLIArrayModule::Put_dv_i_dFunction::execute(), Geq_idFunction::execute(), nest::NestModule::Size_gFunction::execute(), SLIArrayModule::Put_iv_i_iFunction::execute(), Put_aFunction::execute(), nest::NestModule::SetAcceptableLatencyFunction::execute(), Geq_diFunction::execute(), Put_pFunction::execute(), nest::NestModule::SetMaxBufferedFunction::execute(), Put_lpFunction::execute(), Geq_ddFunction::execute(), Search_sFunction::execute(), Leq_iiFunction::execute(), SLIArrayModule::ArangeFunction::execute(), Search_aFunction::execute(), Leq_idFunction::execute(), MessageFunction::execute(), SLIArrayModule::FiniteQ_dFunction::execute(), Leq_diFunction::execute(), SLIArrayModule::Forall_ivFunction::execute(), IrepeatanyFunction::execute(), SLIArrayModule::Forall_dvFunction::execute(), Leq_ddFunction::execute(), RepeatanyFunction::execute(), SLIArrayModule::Iforall_ivFunction::execute(), Gt_iiFunction::execute(), SLIArrayModule::Iforall_dvFunction::execute(), Gt_ddFunction::execute(), Gt_idFunction::execute(), Gt_diFunction::execute(), Gt_ssFunction::execute(), Lt_iiFunction::execute(), Lt_ddFunction::execute(), Lt_idFunction::execute(), Lt_diFunction::execute(), Lt_ssFunction::execute(), IntegerFunction::execute(), DoubleFunction::execute(), UnitStep_iFunction::execute(), UnitStep_dFunction::execute(), UnitStep_iaFunction::execute(), UnitStep_daFunction::execute(), Round_dFunction::execute(), Floor_dFunction::execute(), Ceil_dFunction::execute(), Max_i_iFunction::execute(), Max_i_dFunction::execute(), Max_d_iFunction::execute(), Max_d_dFunction::execute(), Min_i_iFunction::execute(), Min_i_dFunction::execute(), Min_d_iFunction::execute(), Min_d_dFunction::execute(), index(), TypeTrie::lookup(), and SLIInterpreter::stack_backtrace().
Token& TokenStack::pick (size_t i) inline
References TokenArrayObj::end().
void TokenStack::pop (void) inline
References TokenArrayObj::pop_back().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_10pop(), eq_execute(), TrieFunction::execute(), DatatypeFunction::execute(), OOSupportModule::CallMemberFunction::execute(), PopFunction::execute(), Add_diFunction::execute(), TrieInfoFunction::execute(), FilesystemModule::FileNamesFunction::execute(), Get_aFunction::execute(), MathLinkPutStringFunction::execute(), DictFunction::execute(), IlookupFunction::execute(), Backtrace_onFunction::execute(), NpopFunction::execute(), SLIArrayModule::MapFunction::execute(), Add_iiFunction::execute(), AddtotrieFunction::execute(), Get_a_aFunction::execute(), XIfstreamFunction::execute(), DictputFunction::execute(), GNUReadline::GNUReadlineFunction::execute(), IsetcallbackFunction::execute(), Backtrace_offFunction::execute(), RegexpModule::RegcompFunction::execute(), SLIArrayModule::IMapFunction::execute(), SLIgraphics::ReadPGMFunction::execute(), DupFunction::execute(), Add_idFunction::execute(), FilesystemModule::DirectoryFunction::execute(), Cva_tFunction::execute(), Allocations_aFunction::execute(), GNUReadline::GNUAddhistoryFunction::execute(), IfstreamFunction::execute(), RegexpModule::RegexecFunction::execute(), LitproceduretypeFunction::execute(), DictgetFunction::execute(), IiterateFunction::execute(), OStackdumpFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), ExchFunction::execute(), SLIgraphics::WritePGMFunction::execute(), Add_ddFunction::execute(), RegexpModule::RegerrorFunction::execute(), Cvt_aFunction::execute(), nest::ConnectionGeneratorModule::CGConnect_cg_i_i_D_lFunction::execute(), Get_pFunction::execute(), OfstreamFunction::execute(), FunctiontypeFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), DictbeginFunction::execute(), EStackdumpFunction::execute(), IndexFunction::execute(), nest::ConnectionGeneratorModule::CGConnect_cg_iV_iV_D_lFunction::execute(), Sub_diFunction::execute(), TypeFunction::execute(), nest::TopologyModule::CreateLayer_DFunction::execute(), Get_lpFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), OfsopenFunction::execute(), DictendFunction::execute(), LoopFunction::execute(), nest::ConnectionGeneratorModule::CGParse_sFunction::execute(), IrepeatFunction::execute(), RollFunction::execute(), nest::TopologyModule::GetPosition_iFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), Append_aFunction::execute(), Sub_iiFunction::execute(), SpecialFunctionsModule::GammaIncFunction::execute(), nest::ConnectionGeneratorModule::CGParseFile_sFunction::execute(), ExitFunction::execute(), IsstreamFunction::execute(), RolluFunction::execute(), nest::TopologyModule::Displacement_a_iFunction::execute(), IforFunction::execute(), SLIArrayModule::MapIndexedFunction::execute(), nest::ConnectionGeneratorModule::CGSelectImplementation_s_sFunction::execute(), SpecialFunctionsModule::LambertW0Function::execute(), Append_pFunction::execute(), RandomNumbers::CreateRNGFunction::execute(), ToUppercase_sFunction::execute(), Sub_idFunction::execute(), OsstreamFunction::execute(), nest::TopologyModule::Distance_a_iFunction::execute(), RolldFunction::execute(), nest::ConnectionGeneratorModule::CGSetMask_cg_iV_iVFunction::execute(), SLIArrayModule::IMapIndexedFunction::execute(), DictinfoFunction::execute(), SpecialFunctionsModule::LambertWm1Function::execute(), nest::DynamicLoaderModule::LoadModuleFunction::execute(), FilesystemModule::TmpNamFunction::execute(), IforallarrayFunction::execute(), Append_sFunction::execute(), RandomNumbers::CreateRDVFunction::execute(), ToLowercase_sFunction::execute(), IfFunction::execute(), StrSStreamFunction::execute(), nest::ConnectionGeneratorModule::CGStart_cgFunction::execute(), nest::TopologyModule::GetGlobalChildren_i_M_aFunction::execute(), RotFunction::execute(), Sub_ddFunction::execute(), SLIArrayModule::RangeFunction::execute(), DicttopinfoFunction::execute(), SpecialFunctionsModule::ErfFunction::execute(), RandomNumbers::SetStatus_vdFunction::execute(), FilesystemModule::CompareFilesFunction::execute(), nest::ConnectionGeneratorModule::CGNext_cgFunction::execute(), Prepend_aFunction::execute(), IforalliterFunction::execute(), IfelseFunction::execute(), nest::TopologyModule::ConnectLayers_i_i_DFunction::execute(), OstrstreamFunction::execute(), OverFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), SpecialFunctionsModule::ErfcFunction::execute(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), WhoFunction::execute(), RandomNumbers::GetStatus_vFunction::execute(), Prepend_pFunction::execute(), Mul_diFunction::execute(), nest::TopologyModule::CreateMask_DFunction::execute(), RepeatFunction::execute(), IforallindexedarrayFunction::execute(), CountFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), StrFunction::execute(), SpecialFunctionsModule::GaussDiskConvFunction::execute(), DictconstructFunction::execute(), RandomNumbers::IrandFunction::execute(), SLIStartup::GetenvFunction::execute(), nest::TopologyModule::Inside_a_MFunction::execute(), Prepend_sFunction::execute(), CloseinputFunction::execute(), SLIArrayModule::ArraycreateFunction::execute(), Mul_iiFunction::execute(), IforallindexedstringFunction::execute(), CopyFunction::execute(), RandomNumbers::DrandFunction::execute(), PrintFunction::execute(), DictstackFunction::execute(), nest::TopologyModule::And_M_MFunction::execute(), Join_sFunction::execute(), SLIArrayModule::ReverseFunction::execute(), StoppedFunction::execute(), RandomNumbers::SeedFunction::execute(), ClearFunction::execute(), Mul_idFunction::execute(), nest::TopologyModule::Or_M_MFunction::execute(), IforallstringFunction::execute(), PrettyprintFunction::execute(), CurrentdictFunction::execute(), Join_aFunction::execute(), SLIArrayModule::RotateFunction::execute(), StopFunction::execute(), RandomNumbers::RandomArrayFunction::execute(), ExecstackFunction::execute(), nest::TopologyModule::Sub_M_MFunction::execute(), CloseistreamFunction::execute(), CountdictstackFunction::execute(), SLIArrayModule::FlattenFunction::execute(), Mul_ddFunction::execute(), Join_pFunction::execute(), CurrentnameFunction::execute(), RandomNumbers::RandomFunction::execute(), nest::TopologyModule::Mul_P_PFunction::execute(), RestoreestackFunction::execute(), CloseostreamFunction::execute(), SLIArrayModule::SortFunction::execute(), CleardictstackFunction::execute(), Insert_sFunction::execute(), IparsestdinFunction::execute(), nest::TopologyModule::Div_P_PFunction::execute(), Div_diFunction::execute(), RestoreostackFunction::execute(), FlushFunction::execute(), Length_dFunction::execute(), Insert_aFunction::execute(), nest::TopologyModule::Add_P_PFunction::execute(), SLIArrayModule::TransposeFunction::execute(), OperandstackFunction::execute(), EndlFunction::execute(), Div_iiFunction::execute(), Empty_DFunction::execute(), nest::TopologyModule::Sub_P_PFunction::execute(), InsertElement_sFunction::execute(), ParsestdinFunction::execute(), SLIArrayModule::PartitionFunction::execute(), EndsFunction::execute(), nest::TopologyModule::CreateParameter_DFunction::execute(), CleardictFunction::execute(), Div_idFunction::execute(), InsertElement_aFunction::execute(), IparseFunction::execute(), SLIArrayModule::ValidFunction::execute(), EatwhiteFunction::execute(), nest::TopologyModule::GetValue_a_PFunction::execute(), ClonedictFunction::execute(), Replace_sFunction::execute(), Div_ddFunction::execute(), DefFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), nest::NestModule::ChangeSubnet_iFunction::execute(), nest::TopologyModule::DumpLayerNodes_os_iFunction::execute(), SetwFunction::execute(), UndefFunction::execute(), Replace_aFunction::execute(), nest::NestModule::CurrentSubnetFunction::execute(), SetFunction::execute(), nest::TopologyModule::DumpLayerConnections_os_i_lFunction::execute(), Mod_iiFunction::execute(), SetprecisionFunction::execute(), KnownFunction::execute(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), Erase_sFunction::execute(), nest::TopologyModule::GetElement_i_iaFunction::execute(), LoadFunction::execute(), IOSFixedFunction::execute(), Cva_dFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), Erase_aFunction::execute(), nest::TopologyModule::Cvdict_MFunction::execute(), LookupFunction::execute(), Sin_dFunction::execute(), IOSScientificFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), KeysFunction::execute(), Erase_pFunction::execute(), ForFunction::execute(), Asin_dFunction::execute(), IOSDefaultFunction::execute(), nest::NestModule::GetStatus_iFunction::execute(), ValuesFunction::execute(), Length_sFunction::execute(), Forall_aFunction::execute(), nest::NestModule::GetStatus_CFunction::execute(), IOSShowpointFunction::execute(), RestoredstackFunction::execute(), Cos_dFunction::execute(), SLIArrayModule::AreaFunction::execute(), Forall_iterFunction::execute(), Length_aFunction::execute(), nest::NestModule::GetStatus_aFunction::execute(), IOSNoshowpointFunction::execute(), Acos_dFunction::execute(), Length_pFunction::execute(), nest::NestModule::SetStatus_idFunction::execute(), Forallindexed_aFunction::execute(), IOSShowbaseFunction::execute(), Processes::ForkFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), Length_lpFunction::execute(), Exp_dFunction::execute(), Forallindexed_sFunction::execute(), IOSNoshowbaseFunction::execute(), nest::NestModule::Cva_CFunction::execute(), Processes::WaitPIDFunction::execute(), Capacity_aFunction::execute(), Forall_sFunction::execute(), Ln_dFunction::execute(), IOSDecFunction::execute(), nest::NestModule::SetStatus_aaFunction::execute(), Processes::KillFunction::execute(), Size_aFunction::execute(), RaiseerrorFunction::execute(), IOSHexFunction::execute(), Processes::PipeFunction::execute(), nest::NestModule::SetDefaults_l_DFunction::execute(), Log_dFunction::execute(), Reserve_aFunction::execute(), PrinterrorFunction::execute(), SLIArrayModule::Area2Function::execute(), Processes::Dup2_is_isFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), IOSOctFunction::execute(), Processes::Dup2_os_osFunction::execute(), Sqr_dFunction::execute(), Resize_aFunction::execute(), SLIArrayModule::Cv1dFunction::execute(), RaiseagainFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), IOSLeftFunction::execute(), Processes::Dup2_is_osFunction::execute(), SLIArrayModule::Cv2dFunction::execute(), nest::NestModule::GetConnections_DFunction::execute(), Empty_aFunction::execute(), CyclesFunction::execute(), Sqrt_dFunction::execute(), Processes::Dup2_os_isFunction::execute(), IOSRightFunction::execute(), SLIArrayModule::GetMaxFunction::execute(), nest::NestModule::SimulateFunction::execute(), Processes::AvailableFunction::execute(), References_aFunction::execute(), CodeAccessedFunction::execute(), IOSInternalFunction::execute(), Pow_ddFunction::execute(), SLIArrayModule::GetMinFunction::execute(), Processes::GetPIDFunction::execute(), nest::NestModule::ResumeSimulationFunction::execute(), CodeExecutedFunction::execute(), Shrink_aFunction::execute(), GetcFunction::execute(), Processes::GetPPIDFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), Pow_diFunction::execute(), ExecFunction::execute(), Processes::GetPGRPFunction::execute(), Capacity_sFunction::execute(), GetsFunction::execute(), nest::NestModule::RestoreNodes_aFunction::execute(), SLIArrayModule::GaborFunction::execute(), Processes::MkfifoFunction::execute(), Modf_dFunction::execute(), Size_sFunction::execute(), TypeinfoFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), GetlineFunction::execute(), Processes::MemoryThisjobBgFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), nest::NestModule::DataConnect_aFunction::execute(), Reserve_sFunction::execute(), Frexp_dFunction::execute(), IGoodFunction::execute(), Processes::MemoryThisjobDarwinFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), Resize_sFunction::execute(), IClearFunction::execute(), Ldexp_diFunction::execute(), Processes::SetNonblockFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), SLIArrayModule::Array2IntVectorFunction::execute(), Empty_sFunction::execute(), OClearFunction::execute(), Processes::CtermidFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), Dexp_iFunction::execute(), Getinterval_sFunction::execute(), Processes::Isatty_isFunction::execute(), IFailFunction::execute(), SLIArrayModule::Array2DoubleVectorFunction::execute(), nest::NestModule::Connect_g_g_D_DFunction::execute(), Processes::Isatty_osFunction::execute(), Getinterval_aFunction::execute(), SwitchFunction::execute(), OGoodFunction::execute(), SLIArrayModule::DoubleVector2ArrayFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), Abs_iFunction::execute(), Cvx_aFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), Cvx_fFunction::execute(), SLIArrayModule::IntVector2ArrayFunction::execute(), Abs_dFunction::execute(), nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), Cvlit_nFunction::execute(), SLIArrayModule::Add_iv_ivFunction::execute(), IEofFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), SLIArrayModule::Add_i_ivFunction::execute(), Cvlit_pFunction::execute(), Neg_iFunction::execute(), OEofFunction::execute(), nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute(), SLIArrayModule::Neg_ivFunction::execute(), Cvlp_pFunction::execute(), In_AvailFunction::execute(), Neg_dFunction::execute(), nest::NestModule::ResetKernelFunction::execute(), SLIArrayModule::Sub_iv_ivFunction::execute(), RangeIterator_aFunction::execute(), ReadDoubleFunction::execute(), SLIArrayModule::Mul_iv_ivFunction::execute(), nest::NestModule::ResetNetworkFunction::execute(), Inv_dFunction::execute(), IteratorSize_iterFunction::execute(), nest::NestModule::MemoryInfoFunction::execute(), ReadIntFunction::execute(), SLIArrayModule::Mul_i_ivFunction::execute(), SwitchdefaultFunction::execute(), nest::NestModule::PrintNetworkFunction::execute(), EqFunction::execute(), Cvn_sFunction::execute(), SLIArrayModule::Mul_d_ivFunction::execute(), ReadWordFunction::execute(), nest::NestModule::RankFunction::execute(), Cvn_lFunction::execute(), SLIArrayModule::Div_iv_ivFunction::execute(), NeqFunction::execute(), nest::NestModule::NumProcessesFunction::execute(), SLIArrayModule::Add_dv_dvFunction::execute(), nest::NestModule::SetFakeNumProcessesFunction_i::execute(), AndFunction::execute(), nest::NestModule::SetNumRecProcessesFunction_i::execute(), SLIArrayModule::Add_d_dvFunction::execute(), nest::NestModule::SyncProcessesFunction::execute(), SLIArrayModule::Sub_dv_dvFunction::execute(), OrFunction::execute(), nest::NestModule::TimeCommunication_i_i_bFunction::execute(), SLIArrayModule::Mul_dv_dvFunction::execute(), nest::NestModule::TimeCommunicationv_i_iFunction::execute(), CaseFunction::execute(), And_iiFunction::execute(), SLIArrayModule::Mul_d_dvFunction::execute(), nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute(), Cvi_sFunction::execute(), SLIArrayModule::Div_dv_dvFunction::execute(), CounttomarkFunction::execute(), nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute(), Or_iiFunction::execute(), SLIArrayModule::Neg_dvFunction::execute(), PclocksFunction::execute(), nest::NestModule::ProcessorNameFunction::execute(), SLIArrayModule::Inv_dvFunction::execute(), XorFunction::execute(), nest::NestModule::MPIAbort_iFunction::execute(), PclockspersecFunction::execute(), SLIArrayModule::Length_dvFunction::execute(), SLIArrayModule::Length_ivFunction::execute(), nest::NestModule::GetVpRngFunction::execute(), Not_bFunction::execute(), PgetrusageFunction::execute(), nest::NestModule::GetGlobalRngFunction::execute(), SLIArrayModule::Get_iv_iFunction::execute(), nest::NestModule::Cvdict_CFunction::execute(), SLIArrayModule::Get_iv_ivFunction::execute(), Not_iFunction::execute(), TimeFunction::execute(), Cvd_sFunction::execute(), nest::NestModule::Cvgidcollection_i_iFunction::execute(), SLIArrayModule::Get_dv_ivFunction::execute(), Sleep_iFunction::execute(), Get_sFunction::execute(), nest::NestModule::Cvgidcollection_iaFunction::execute(), Geq_iiFunction::execute(), SLIArrayModule::Get_dv_iFunction::execute(), nest::NestModule::Cvgidcollection_ivFunction::execute(), Put_sFunction::execute(), Sleep_dFunction::execute(), SLIArrayModule::Put_dv_i_dFunction::execute(), Geq_idFunction::execute(), nest::NestModule::Size_gFunction::execute(), SLIArrayModule::Put_iv_i_iFunction::execute(), Put_aFunction::execute(), Token_sFunction::execute(), nest::NestModule::SetAcceptableLatencyFunction::execute(), Geq_diFunction::execute(), SLIArrayModule::Zeros_ivFunction::execute(), Put_pFunction::execute(), Token_isFunction::execute(), nest::NestModule::SetMaxBufferedFunction::execute(), SLIArrayModule::Zeros_dvFunction::execute(), Geq_ddFunction::execute(), Symbol_sFunction::execute(), Put_lpFunction::execute(), SLIArrayModule::Ones_dvFunction::execute(), SLIArrayModule::Ones_ivFunction::execute(), SetGuardFunction::execute(), Search_sFunction::execute(), Leq_iiFunction::execute(), SLIArrayModule::ArangeFunction::execute(), RemoveGuardFunction::execute(), Search_aFunction::execute(), Leq_idFunction::execute(), MessageFunction::execute(), SLIArrayModule::FiniteQ_dFunction::execute(), Leq_diFunction::execute(), SetVerbosityFunction::execute(), SLIArrayModule::Forall_ivFunction::execute(), IrepeatanyFunction::execute(), VerbosityFunction::execute(), SLIArrayModule::Forall_dvFunction::execute(), Leq_ddFunction::execute(), RepeatanyFunction::execute(), SLIArrayModule::Iforall_ivFunction::execute(), NoopFunction::execute(), Gt_iiFunction::execute(), SLIArrayModule::Iforall_dvFunction::execute(), DebugOnFunction::execute(), DebugOffFunction::execute(), Gt_ddFunction::execute(), DebugFunction::execute(), Gt_idFunction::execute(), Gt_diFunction::execute(), Gt_ssFunction::execute(), Lt_iiFunction::execute(), Lt_ddFunction::execute(), Lt_idFunction::execute(), Lt_diFunction::execute(), Lt_ssFunction::execute(), IntegerFunction::execute(), DoubleFunction::execute(), UnitStep_iFunction::execute(), UnitStep_dFunction::execute(), UnitStep_iaFunction::execute(), UnitStep_daFunction::execute(), Round_dFunction::execute(), Floor_dFunction::execute(), Ceil_dFunction::execute(), Max_i_iFunction::execute(), Max_i_dFunction::execute(), Max_d_iFunction::execute(), Max_d_dFunction::execute(), Min_i_iFunction::execute(), Min_i_dFunction::execute(), Min_d_iFunction::execute(), Min_d_dFunction::execute(), and SLIInterpreter::raiseerror().
void TokenStack::pop (size_t n) inline
References TokenArrayObj::end(), and TokenArrayObj::erase().
void TokenStack::pop_move (Token & e) inline
References TokenArrayObj::end(), Token::move(), and TokenArrayObj::pop_back().
Referenced by IsetcallbackFunction::execute(), Processes::Sysexec_aFunction::execute(), RaiseerrorFunction::execute(), and Parser::operator()().
void TokenStack::push (const Token & e) inline
References TokenArrayObj::push_back().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), SLIInterpreter::debug_commandline(), OOSupportModule::CallMemberFunction::execute(), DictFunction::execute(), SLIArrayModule::MapFunction::execute(), Get_a_aFunction::execute(), XIfstreamFunction::execute(), GNUReadline::GNUReadlineFunction::execute(), RegexpModule::RegcompFunction::execute(), SLIArrayModule::IMapFunction::execute(), SLIgraphics::ReadPGMFunction::execute(), Cva_tFunction::execute(), IfstreamFunction::execute(), IiterateFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), OfstreamFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), IloopFunction::execute(), nest::TopologyModule::CreateLayer_DFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), OfsopenFunction::execute(), CallbacktypeFunction::execute(), nest::ConnectionGeneratorModule::CGParse_sFunction::execute(), IrepeatFunction::execute(), nest::TopologyModule::GetPosition_iFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), nest::ConnectionGeneratorModule::CGParseFile_sFunction::execute(), XIstreamtypeFunction::execute(), IsstreamFunction::execute(), nest::TopologyModule::Displacement_a_iFunction::execute(), IforFunction::execute(), SLIArrayModule::MapIndexedFunction::execute(), ToUppercase_sFunction::execute(), RandomNumbers::CreateRNGFunction::execute(), XIfstreamtypeFunction::execute(), OsstreamFunction::execute(), nest::TopologyModule::Distance_a_iFunction::execute(), SLIArrayModule::IMapIndexedFunction::execute(), nest::DynamicLoaderModule::LoadModuleFunction::execute(), IforallarrayFunction::execute(), ToLowercase_sFunction::execute(), RandomNumbers::CreateRDVFunction::execute(), nest::TopologyModule::GetGlobalChildren_i_M_aFunction::execute(), FilesystemModule::CompareFilesFunction::execute(), nest::ConnectionGeneratorModule::CGNext_cgFunction::execute(), IforalliterFunction::execute(), OstrstreamFunction::execute(), RandomNumbers::GetStatus_vFunction::execute(), nest::TopologyModule::CreateMask_DFunction::execute(), IforallindexedarrayFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), SLIStartup::GetenvFunction::execute(), RandomNumbers::IrandFunction::execute(), nest::TopologyModule::Inside_a_MFunction::execute(), CloseinputFunction::execute(), IforallindexedstringFunction::execute(), RandomNumbers::DrandFunction::execute(), nest::TopologyModule::And_M_MFunction::execute(), IforallstringFunction::execute(), nest::TopologyModule::Or_M_MFunction::execute(), StopFunction::execute(), RandomNumbers::RandomArrayFunction::execute(), nest::TopologyModule::Sub_M_MFunction::execute(), CurrentnameFunction::execute(), RandomNumbers::RandomFunction::execute(), nest::TopologyModule::Mul_P_PFunction::execute(), SLIArrayModule::SortFunction::execute(), nest::TopologyModule::Div_P_PFunction::execute(), nest::TopologyModule::Add_P_PFunction::execute(), nest::TopologyModule::Sub_P_PFunction::execute(), SLIArrayModule::PartitionFunction::execute(), nest::TopologyModule::CreateParameter_DFunction::execute(), SLIArrayModule::ValidFunction::execute(), nest::TopologyModule::GetValue_a_PFunction::execute(), ClonedictFunction::execute(), nest::NestModule::CurrentSubnetFunction::execute(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), nest::TopologyModule::GetElement_i_iaFunction::execute(), Cva_dFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::TopologyModule::Cvdict_MFunction::execute(), LookupFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), KeysFunction::execute(), nest::NestModule::GetStatus_iFunction::execute(), ValuesFunction::execute(), nest::NestModule::GetStatus_CFunction::execute(), Forall_iterFunction::execute(), nest::NestModule::GetStatus_aFunction::execute(), Forallindexed_aFunction::execute(), Forallindexed_sFunction::execute(), Processes::WaitPIDFunction::execute(), Forall_sFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), nest::NestModule::GetConnections_DFunction::execute(), Empty_aFunction::execute(), CyclesFunction::execute(), SLIInterpreter::execute(), SLIArrayModule::GetMaxFunction::execute(), Processes::AvailableFunction::execute(), CodeAccessedFunction::execute(), SLIArrayModule::GetMinFunction::execute(), CodeExecutedFunction::execute(), Shrink_aFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), SLIArrayModule::GaborFunction::execute(), GetlineFunction::execute(), Processes::MemoryThisjobBgFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), Frexp_dFunction::execute(), IGoodFunction::execute(), Processes::MemoryThisjobDarwinFunction::execute(), SLIArrayModule::Array2IntVectorFunction::execute(), Empty_sFunction::execute(), Processes::CtermidFunction::execute(), Processes::Isatty_isFunction::execute(), SLIArrayModule::Array2DoubleVectorFunction::execute(), IFailFunction::execute(), Processes::Isatty_osFunction::execute(), SwitchFunction::execute(), SLIArrayModule::DoubleVector2ArrayFunction::execute(), OGoodFunction::execute(), SLIArrayModule::IntVector2ArrayFunction::execute(), SLIArrayModule::Add_iv_ivFunction::execute(), IEofFunction::execute(), SLIArrayModule::Add_i_ivFunction::execute(), OEofFunction::execute(), SLIArrayModule::Neg_ivFunction::execute(), SLIArrayModule::Sub_iv_ivFunction::execute(), ReadDoubleFunction::execute(), SLIArrayModule::Mul_iv_ivFunction::execute(), SLIArrayModule::Mul_i_ivFunction::execute(), ReadIntFunction::execute(), SwitchdefaultFunction::execute(), SLIArrayModule::Mul_d_ivFunction::execute(), ReadWordFunction::execute(), nest::NestModule::RankFunction::execute(), SLIArrayModule::Div_iv_ivFunction::execute(), nest::NestModule::NumProcessesFunction::execute(), SLIArrayModule::Add_dv_dvFunction::execute(), SLIArrayModule::Add_d_dvFunction::execute(), SLIArrayModule::Sub_dv_dvFunction::execute(), nest::NestModule::TimeCommunication_i_i_bFunction::execute(), SLIArrayModule::Mul_dv_dvFunction::execute(), nest::NestModule::TimeCommunicationv_i_iFunction::execute(), SLIArrayModule::Mul_d_dvFunction::execute(), nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute(), SLIArrayModule::Div_dv_dvFunction::execute(), nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute(), SLIArrayModule::Neg_dvFunction::execute(), PclocksFunction::execute(), nest::NestModule::ProcessorNameFunction::execute(), SLIArrayModule::Inv_dvFunction::execute(), SLIArrayModule::Length_dvFunction::execute(), PclockspersecFunction::execute(), SLIArrayModule::Length_ivFunction::execute(), PgetrusageFunction::execute(), SLIArrayModule::Get_iv_iFunction::execute(), nest::NestModule::Cvdict_CFunction::execute(), SLIArrayModule::Get_iv_ivFunction::execute(), nest::NestModule::Cvgidcollection_i_iFunction::execute(), SLIArrayModule::Get_dv_ivFunction::execute(), nest::NestModule::Cvgidcollection_iaFunction::execute(), SLIArrayModule::Get_dv_iFunction::execute(), nest::NestModule::Cvgidcollection_ivFunction::execute(), nest::NestModule::Size_gFunction::execute(), Token_sFunction::execute(), SLIArrayModule::Zeros_ivFunction::execute(), Token_isFunction::execute(), SLIArrayModule::Zeros_dvFunction::execute(), Symbol_sFunction::execute(), SLIArrayModule::Ones_dvFunction::execute(), SLIArrayModule::Ones_ivFunction::execute(), Search_sFunction::execute(), SLIArrayModule::ArangeFunction::execute(), Search_aFunction::execute(), SLIArrayModule::FiniteQ_dFunction::execute(), IrepeatanyFunction::execute(), RepeatanyFunction::execute(), SLIArrayModule::Iforall_ivFunction::execute(), SLIArrayModule::Iforall_dvFunction::execute(), DebugFunction::execute(), nest::Network::execute_sli_protected(), index(), SLIStartup::init(), Parser::operator()(), SLIInterpreter::raiseagain(), and SLIInterpreter::raiseerror().
void TokenStack::push_by_pointer (Datum * rhs) inline
Push a valid datum to the stack.
This function expects that sufficient space is on the stack to fit the datum. This function increases the reference count of the datum.
References TokenArrayObj::push_back_by_pointer().
Referenced by eq_execute(), SLIArrayModule::MapFunction::execute(), ProceduretypeFunction::execute(), LitproceduretypeFunction::execute(), LoopFunction::execute(), RepeatFunction::execute(), IforallindexedarrayFunction::execute(), StoppedFunction::execute(), IforallstringFunction::execute(), Empty_DFunction::execute(), ForFunction::execute(), Forall_aFunction::execute(), SLIArrayModule::AreaFunction::execute(), SLIArrayModule::Area2Function::execute(), Modf_dFunction::execute(), EqFunction::execute(), NeqFunction::execute(), Geq_iiFunction::execute(), Geq_idFunction::execute(), Geq_diFunction::execute(), Geq_ddFunction::execute(), Leq_iiFunction::execute(), Leq_idFunction::execute(), Leq_diFunction::execute(), SLIArrayModule::Forall_ivFunction::execute(), Leq_ddFunction::execute(), SLIArrayModule::Forall_dvFunction::execute(), Gt_iiFunction::execute(), Gt_ddFunction::execute(), Gt_idFunction::execute(), Gt_diFunction::execute(), Gt_ssFunction::execute(), Lt_iiFunction::execute(), Lt_ddFunction::execute(), Lt_idFunction::execute(), Lt_diFunction::execute(), Lt_ssFunction::execute(), UnitStep_iFunction::execute(), UnitStep_dFunction::execute(), UnitStep_iaFunction::execute(), and UnitStep_daFunction::execute().
void TokenStack::push_by_ref (const Token & e) inline
Push a Token with a valid datum to the stack.
This function expects that sufficient space is on the stack to fit the datum. This function increases the reference count of the datum.
References TokenArrayObj::push_back_by_ref().
Referenced by ProceduretypeFunction::execute(), LoopFunction::execute(), RepeatFunction::execute(), ForFunction::execute(), Forall_aFunction::execute(), SLIArrayModule::Forall_ivFunction::execute(), and SLIArrayModule::Forall_dvFunction::execute().
void TokenStack::push_move (Token & e) inline
References TokenArrayObj::push_back_move().
Referenced by TrieFunction::execute(), DatatypeFunction::execute(), OOSupportModule::CallMemberFunction::execute(), FilesystemModule::FileNamesFunction::execute(), Get_aFunction::execute(), SLIArrayModule::MapFunction::execute(), XIfstreamFunction::execute(), RegexpModule::RegcompFunction::execute(), SLIArrayModule::IMapFunction::execute(), FilesystemModule::DirectoryFunction::execute(), Allocations_aFunction::execute(), IfstreamFunction::execute(), RegexpModule::RegexecFunction::execute(), DictgetFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), RegexpModule::RegerrorFunction::execute(), Cvt_aFunction::execute(), OfstreamFunction::execute(), Get_pFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), TypeFunction::execute(), Get_lpFunction::execute(), OfsopenFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), CallbacktypeFunction::execute(), LoopFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), SLIArrayModule::MapIndexedFunction::execute(), SLIArrayModule::IMapIndexedFunction::execute(), nest::DynamicLoaderModule::LoadModuleFunction::execute(), FilesystemModule::TmpNamFunction::execute(), IfFunction::execute(), StrSStreamFunction::execute(), IfelseFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), RepeatFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), StrFunction::execute(), CountFunction::execute(), SLIStartup::GetenvFunction::execute(), SLIArrayModule::ArraycreateFunction::execute(), DictstackFunction::execute(), StoppedFunction::execute(), CurrentdictFunction::execute(), ExecstackFunction::execute(), CountdictstackFunction::execute(), SLIArrayModule::FlattenFunction::execute(), IparsestdinFunction::execute(), Length_dFunction::execute(), SLIArrayModule::TransposeFunction::execute(), OperandstackFunction::execute(), ParsestdinFunction::execute(), IparseFunction::execute(), LoadFunction::execute(), LookupFunction::execute(), ForFunction::execute(), Forall_aFunction::execute(), Length_sFunction::execute(), Length_aFunction::execute(), Forall_iterFunction::execute(), Length_pFunction::execute(), Forallindexed_aFunction::execute(), Processes::ForkFunction::execute(), Length_lpFunction::execute(), Forallindexed_sFunction::execute(), Processes::Sysexec_aFunction::execute(), Capacity_aFunction::execute(), Processes::WaitPIDFunction::execute(), Forall_sFunction::execute(), Size_aFunction::execute(), Processes::PipeFunction::execute(), References_aFunction::execute(), Processes::GetPIDFunction::execute(), GetcFunction::execute(), Processes::GetPPIDFunction::execute(), Processes::GetPGRPFunction::execute(), ExecFunction::execute(), Capacity_sFunction::execute(), GetsFunction::execute(), Size_sFunction::execute(), TypeinfoFunction::execute(), GetlineFunction::execute(), SwitchFunction::execute(), Cvx_fFunction::execute(), In_AvailFunction::execute(), ReadDoubleFunction::execute(), IteratorSize_iterFunction::execute(), ReadIntFunction::execute(), SwitchdefaultFunction::execute(), ReadWordFunction::execute(), CounttomarkFunction::execute(), nest::NestModule::GetVpRngFunction::execute(), nest::NestModule::GetGlobalRngFunction::execute(), TimeFunction::execute(), Get_sFunction::execute(), Token_sFunction::execute(), Token_isFunction::execute(), Symbol_sFunction::execute(), Search_sFunction::execute(), Search_aFunction::execute(), SLIArrayModule::Forall_ivFunction::execute(), VerbosityFunction::execute(), SLIArrayModule::Forall_dvFunction::execute(), RepeatanyFunction::execute(), DebugFunction::execute(), SLIStartup::init(), Parser::operator()(), and SLIInterpreter::raiseagain().
void TokenStack::roll (size_t n, long k) inline
References TokenArrayObj::end(), and TokenArrayObj::rotate().
Referenced by RollFunction::execute(), RolluFunction::execute(), RolldFunction::execute(), and RotFunction::execute().
Index TokenStack::size (void) const inline
References TokenArrayObj::capacity().
Referenced by TrieInfoFunction::execute(), Cva_tFunction::execute(), and Cvt_aFunction::execute().
void TokenStack::swap (void) inline
References TokenArrayObj::end().
Referenced by Add_idFunction::execute(), ExchFunction::execute(), Sub_idFunction::execute(), Mul_idFunction::execute(), Div_idFunction::execute(), IparseFunction::execute(), CaseFunction::execute(), Max_i_iFunction::execute(), Max_i_dFunction::execute(), Max_d_iFunction::execute(), Max_d_dFunction::execute(), Min_i_iFunction::execute(), Min_i_dFunction::execute(), Min_d_iFunction::execute(), Min_d_dFunction::execute(), and swap().
void TokenStack::swap (Token & e) inline
References TokenArrayObj::end(), and swap().
TokenArray TokenStack::toArray (void) const inline
Referenced by ExecstackFunction::execute(), OperandstackFunction::execute(), and SLIInterpreter::raiseerror().
Token& TokenStack::top (void) inline
References TokenArrayObj::end().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_10pop(), TrieFunction::execute(), DatatypeFunction::execute(), TrieInfoFunction::execute(), FilesystemModule::FileNamesFunction::execute(), Get_aFunction::execute(), MathLinkPutStringFunction::execute(), NametypeFunction::execute(), NpopFunction::execute(), SLIArrayModule::MapFunction::execute(), AddtotrieFunction::execute(), XIfstreamFunction::execute(), Get_a_aFunction::execute(), GNUReadline::GNUReadlineFunction::execute(), ProceduretypeFunction::execute(), DictputFunction::execute(), IsetcallbackFunction::execute(), SLIArrayModule::IMapFunction::execute(), SLIgraphics::ReadPGMFunction::execute(), Cva_tFunction::execute(), IfstreamFunction::execute(), GNUReadline::GNUAddhistoryFunction::execute(), LitproceduretypeFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), OfstreamFunction::execute(), Get_pFunction::execute(), FunctiontypeFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), DictbeginFunction::execute(), IndexFunction::execute(), TypeFunction::execute(), Get_lpFunction::execute(), OfsopenFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), LoopFunction::execute(), RollFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), Append_aFunction::execute(), SpecialFunctionsModule::GammaIncFunction::execute(), IsstreamFunction::execute(), SLIArrayModule::MapIndexedFunction::execute(), SpecialFunctionsModule::LambertW0Function::execute(), Append_pFunction::execute(), ToUppercase_sFunction::execute(), RandomNumbers::CreateRNGFunction::execute(), DictinfoFunction::execute(), SLIArrayModule::IMapIndexedFunction::execute(), SpecialFunctionsModule::LambertWm1Function::execute(), nest::DynamicLoaderModule::LoadModuleFunction::execute(), RandomNumbers::CreateRDVFunction::execute(), ToLowercase_sFunction::execute(), IfFunction::execute(), TrietypeFunction::execute(), StrSStreamFunction::execute(), DicttopinfoFunction::execute(), SpecialFunctionsModule::ErfFunction::execute(), RandomNumbers::SetStatus_vdFunction::execute(), Prepend_aFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), WhoFunction::execute(), SpecialFunctionsModule::ErfcFunction::execute(), RandomNumbers::GetStatus_vFunction::execute(), Prepend_pFunction::execute(), RepeatFunction::execute(), StrFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), SpecialFunctionsModule::GaussDiskConvFunction::execute(), RandomNumbers::IrandFunction::execute(), DictconstructFunction::execute(), SLIStartup::GetenvFunction::execute(), CloseinputFunction::execute(), CopyFunction::execute(), RandomNumbers::DrandFunction::execute(), PrintFunction::execute(), StoppedFunction::execute(), SLIArrayModule::ReverseFunction::execute(), RandomNumbers::SeedFunction::execute(), PrettyprintFunction::execute(), IforallstringFunction::execute(), StopFunction::execute(), CloseistreamFunction::execute(), SLIArrayModule::FlattenFunction::execute(), CurrentnameFunction::execute(), RandomNumbers::RandomFunction::execute(), RestoreestackFunction::execute(), CloseostreamFunction::execute(), SLIArrayModule::SortFunction::execute(), RestoreostackFunction::execute(), FlushFunction::execute(), Length_dFunction::execute(), SLIArrayModule::TransposeFunction::execute(), EndlFunction::execute(), Empty_DFunction::execute(), CleardictFunction::execute(), InsertElement_aFunction::execute(), SLIArrayModule::ValidFunction::execute(), EatwhiteFunction::execute(), ClonedictFunction::execute(), DefFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), SetwFunction::execute(), SetFunction::execute(), SetprecisionFunction::execute(), KnownFunction::execute(), LoadFunction::execute(), Cva_dFunction::execute(), LookupFunction::execute(), IOSScientificFunction::execute(), KeysFunction::execute(), ForFunction::execute(), IOSDefaultFunction::execute(), ValuesFunction::execute(), Forall_aFunction::execute(), Length_sFunction::execute(), IOSShowpointFunction::execute(), RestoredstackFunction::execute(), Forall_iterFunction::execute(), Length_aFunction::execute(), IOSNoshowpointFunction::execute(), nest::NestModule::SetStatus_idFunction::execute(), Length_pFunction::execute(), Forallindexed_aFunction::execute(), IOSShowbaseFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), Length_lpFunction::execute(), Forallindexed_sFunction::execute(), IOSNoshowbaseFunction::execute(), nest::NestModule::Cva_CFunction::execute(), Processes::WaitPIDFunction::execute(), Capacity_aFunction::execute(), Forall_sFunction::execute(), IOSDecFunction::execute(), nest::NestModule::SetStatus_aaFunction::execute(), Processes::KillFunction::execute(), Size_aFunction::execute(), IOSHexFunction::execute(), PrinterrorFunction::execute(), Processes::Dup2_is_isFunction::execute(), IOSOctFunction::execute(), Processes::Dup2_os_osFunction::execute(), IOSLeftFunction::execute(), Processes::Dup2_is_osFunction::execute(), Empty_aFunction::execute(), Processes::Dup2_os_isFunction::execute(), IOSRightFunction::execute(), SLIArrayModule::GetMaxFunction::execute(), nest::NestModule::SimulateFunction::execute(), Processes::AvailableFunction::execute(), References_aFunction::execute(), IOSInternalFunction::execute(), SLIArrayModule::GetMinFunction::execute(), Shrink_aFunction::execute(), GetcFunction::execute(), ExecFunction::execute(), Capacity_sFunction::execute(), GetsFunction::execute(), nest::NestModule::RestoreNodes_aFunction::execute(), Processes::MkfifoFunction::execute(), Size_sFunction::execute(), TypeinfoFunction::execute(), GetlineFunction::execute(), nest::NestModule::DataConnect_aFunction::execute(), IGoodFunction::execute(), IClearFunction::execute(), Processes::SetNonblockFunction::execute(), SLIArrayModule::Array2IntVectorFunction::execute(), Empty_sFunction::execute(), OClearFunction::execute(), Dexp_iFunction::execute(), IFailFunction::execute(), SLIArrayModule::Array2DoubleVectorFunction::execute(), OGoodFunction::execute(), SLIArrayModule::DoubleVector2ArrayFunction::execute(), Abs_iFunction::execute(), Cvx_aFunction::execute(), Cvx_fFunction::execute(), SLIArrayModule::IntVector2ArrayFunction::execute(), Abs_dFunction::execute(), Cvlit_nFunction::execute(), SLIArrayModule::Add_iv_ivFunction::execute(), IEofFunction::execute(), Cvlit_pFunction::execute(), Neg_iFunction::execute(), OEofFunction::execute(), Cvlp_pFunction::execute(), In_AvailFunction::execute(), Neg_dFunction::execute(), SLIArrayModule::Sub_iv_ivFunction::execute(), RangeIterator_aFunction::execute(), ReadDoubleFunction::execute(), SLIArrayModule::Mul_iv_ivFunction::execute(), Inv_dFunction::execute(), IteratorSize_iterFunction::execute(), ReadIntFunction::execute(), Cvn_sFunction::execute(), ReadWordFunction::execute(), SLIArrayModule::Div_iv_ivFunction::execute(), Cvn_lFunction::execute(), SLIArrayModule::Add_dv_dvFunction::execute(), SLIArrayModule::Sub_dv_dvFunction::execute(), SLIArrayModule::Mul_dv_dvFunction::execute(), Cvi_sFunction::execute(), SLIArrayModule::Div_dv_dvFunction::execute(), SLIArrayModule::Neg_dvFunction::execute(), SLIArrayModule::Inv_dvFunction::execute(), SLIArrayModule::Length_dvFunction::execute(), SLIArrayModule::Length_ivFunction::execute(), Not_bFunction::execute(), Not_iFunction::execute(), Cvd_sFunction::execute(), Get_sFunction::execute(), Token_sFunction::execute(), Put_aFunction::execute(), SLIArrayModule::Zeros_ivFunction::execute(), Put_pFunction::execute(), Token_isFunction::execute(), SLIArrayModule::Zeros_dvFunction::execute(), Symbol_sFunction::execute(), Put_lpFunction::execute(), SLIArrayModule::Ones_dvFunction::execute(), SLIArrayModule::Ones_ivFunction::execute(), SetGuardFunction::execute(), SetVerbosityFunction::execute(), SLIArrayModule::Forall_ivFunction::execute(), SLIArrayModule::Forall_dvFunction::execute(), DebugFunction::execute(), IntegerFunction::execute(), DoubleFunction::execute(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), SLIInterpreter::getcurrentname(), Parser::operator()(), and SLIInterpreter::raiseerror().
const Token& TokenStack::top (void) const inline
References TokenArrayObj::end().
The documentation for this class was generated from the following files:
tokenstack.h
tokenstack.cc