NEST: SLIType Class Reference
SLIType Class Reference
#include <slitype.h>
Public Member Functions
SLIType (void)
~SLIType ()
void settypename (const std::string &s)
void deletetypename (void)
const Name & gettypename (void) const
void setdefaultaction (SLIFunction &)
SLIFunction * getaction (void) const
Private Member Functions
SLIType & operator= (const SLIType &)
SLIType (const SLIType &)
Private Attributes
unsigned int count
Name * name
SLIFunction * defaultaction
Constructor & Destructor Documentation
SLIType::SLIType (const SLIType &) private
SLIType::SLIType (void) inline
SLIType::~SLIType () inline
Member Function Documentation
void SLIType::deletetypename (void)
References assert(), count, and name.
Referenced by nest::NestModule::~NestModule(), RandomNumbers::~RandomNumbers(), RegexpModule::~RegexpModule(), and SLIInterpreter::~SLIInterpreter().
SLIFunction* SLIType::getaction (void) const inline
References defaultaction.
const Name& SLIType::gettypename (void) const inline
References name.
Referenced by Datum::gettypename().
SLIType& SLIType::operator= (const SLIType &) private
void SLIType::setdefaultaction (SLIFunction & c)
References assert(), nest::names::c, and defaultaction.
Referenced by nest::NestModule::init(), RandomNumbers::init(), RegexpModule::init(), SLIInterpreter::inittypes(), and nest::TopologyModule::TopologyModule().
void SLIType::settypename (const std::string & s)
References assert(), count, Name::lookup(), and name.
Referenced by nest::NestModule::init(), RandomNumbers::init(), RegexpModule::init(), SLIInterpreter::inittypes(), and nest::TopologyModule::TopologyModule().
Member Data Documentation
unsigned int SLIType::count private
Referenced by deletetypename(), and settypename().
SLIFunction* SLIType::defaultaction private
Referenced by getaction(), and setdefaultaction().
Name* SLIType::name private
Referenced by deletetypename(), gettypename(), and settypename().
The documentation for this class was generated from the following files:
slitype.h
slitype.cc