NEST: nest::aeif_cond_alpha_multisynapse Class Reference
nest::aeif_cond_alpha_multisynapse Class Reference
Conductance based exponential integrate-and-fire neuron model according to Brette and Gerstner (2005) with multiple ports.
#include <aeif_cond_alpha_multisynapse.h>
Classes
struct Buffers_
Buffers of the model.
struct Parameters_
Independent parameters of the model.
struct State_
State variables of the model.
struct Variables_
Internal variables of the model.
Public Member Functions
aeif_cond_alpha_multisynapse ()
aeif_cond_alpha_multisynapse (const aeif_cond_alpha_multisynapse &)
virtual ~aeif_cond_alpha_multisynapse ()
port send_test_event (Node &, rport, synindex, bool)
Send an event to the receiving_node passed as an argument.
void handle (SpikeEvent &)
Handle incoming spike events.
void handle (CurrentEvent &)
Handler for current events.
void handle (DataLoggingRequest &)
Handler for universal data logging request.
port handles_test_event (SpikeEvent &, rport)
Check if the node can handle a particular event and receptor type.
port handles_test_event (CurrentEvent &, rport)
port handles_test_event (DataLoggingRequest &, rport)
void get_status (DictionaryDatum &) const
void set_status (const DictionaryDatum &)
Public Member Functions inherited from nest::Archiving_Node
Archiving_Node ()
Constructor.
Archiving_Node (const Archiving_Node &)
double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
double_t get_triplet_K_value (const std::deque< histentry >::iterator &iter)
return the triplet Kminus value for the associated iterator.
void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike times (in steps) of spikes which occurred in the range (t1,t2].
void register_stdp_connection (double_t t_first_read)
Register a new incoming STDP connection.
void unregister_stdp_connection (double_t t_last_read)
Unregister this incoming connection.
void get_status (DictionaryDatum &d) const
void set_status (const DictionaryDatum &d)
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool has_proxies () const
Returns true if the node has proxies on remote threads.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool local_receiver () const
Returns true if the node only receives events from nodes/devices on the same thread.
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
virtual std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void finalize ()
Finalize node.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
virtual void event_hook (DSCurrentEvent &)
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
virtual bool is_subnet () const
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Private Member Functions
void init_state_ (const Node &proto)
Private function to initialize the state of a node to model defaults.
void init_buffers_ ()
Private function to initialize the buffers of a node.
void calibrate ()
Re-calculate dependent parameters of the node.
void update (Time const &, const long_t, const long_t)
Bring the node from state $t$ to $t+n*dt$.
void aeif_cond_alpha_multisynapse_dynamics (const std::vector< double_t > &y, std::vector< double_t > &f)
Function computing right-hand side of ODE for the ODE solver.
template<State_::StateVecElems elem>
double_t get_y_elem_ () const
Read out state vector elements, used by UniversalDataLogger.
Private Attributes
Parameters_ P_
State_ S_
Variables_ V_
Buffers_ B_
Static Private Attributes
static RecordablesMap
< aeif_cond_alpha_multisynapse > recordablesMap_
Mapping of recordables names to access functions.
Friends
class RecordablesMap< aeif_cond_alpha_multisynapse >
class UniversalDataLogger< aeif_cond_alpha_multisynapse >
Additional Inherited Members
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Protected Member Functions inherited from nest::Archiving_Node
void set_spiketime (Time const &t_sp)
record spike history
double_t get_spiketime_ms () const
void clear_history ()
clear spike history
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Detailed Description
Conductance based exponential integrate-and-fire neuron model according to Brette and Gerstner (2005) with multiple ports.
Constructor & Destructor Documentation
nest::aeif_cond_alpha_multisynapse::aeif_cond_alpha_multisynapse ()
References recordablesMap_.
nest::aeif_cond_alpha_multisynapse::aeif_cond_alpha_multisynapse (const aeif_cond_alpha_multisynapse & n)
nest::aeif_cond_alpha_multisynapse::~aeif_cond_alpha_multisynapse () virtual
Member Function Documentation
void nest::aeif_cond_alpha_multisynapse::aeif_cond_alpha_multisynapse_dynamics (const std::vector< double_t > & y, std::vector< double_t > & f) inline private
Function computing right-hand side of ODE for the ODE solver.
Parameters
y State vector (input).
f Derivatives (output).
References nest::aeif_cond_alpha_multisynapse::Parameters_::a, B_, nest::aeif_cond_alpha_multisynapse::Parameters_::C_m, nest::aeif_cond_alpha_multisynapse::Parameters_::Delta_T, nest::aeif_cond_alpha_multisynapse::Parameters_::E_ex, nest::aeif_cond_alpha_multisynapse::Parameters_::E_in, nest::aeif_cond_alpha_multisynapse::Parameters_::E_L, nest::aeif_cond_alpha_multisynapse::Parameters_::g_L, nest::aeif_cond_alpha_multisynapse::Parameters_::I_e, nest::aeif_cond_alpha_multisynapse::Buffers_::I_stim_, nest::aeif_cond_alpha_multisynapse::Parameters_::num_of_receptors_, P_, nest::names::S, nest::aeif_cond_alpha_multisynapse::Parameters_::tau_w, nest::aeif_cond_alpha_multisynapse::Parameters_::taus_syn, nest::aeif_cond_alpha_multisynapse::Parameters_::V_th, and nest::names::w.
Referenced by update().
void nest::aeif_cond_alpha_multisynapse::calibrate () private virtual
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
Implements nest::Node.
References assert(), B_, numerics::e, nest::aeif_cond_alpha_multisynapse::Variables_::g0_ex_, nest::aeif_cond_alpha_multisynapse::Variables_::g0_in_, nest::Time::get_steps(), nest::aeif_cond_alpha_multisynapse::State_::k1, nest::aeif_cond_alpha_multisynapse::State_::k2, nest::aeif_cond_alpha_multisynapse::State_::k3, nest::aeif_cond_alpha_multisynapse::State_::k4, nest::aeif_cond_alpha_multisynapse::State_::k5, nest::aeif_cond_alpha_multisynapse::State_::k6, nest::aeif_cond_alpha_multisynapse::State_::k7, nest::aeif_cond_alpha_multisynapse::Buffers_::logger_, nest::aeif_cond_alpha_multisynapse::Parameters_::num_of_receptors_, nest::aeif_cond_alpha_multisynapse::State_::NUMBER_OF_FIXED_STATES_ELEMENTS, nest::aeif_cond_alpha_multisynapse::State_::NUMBER_OF_STATES_ELEMENTS_PER_RECEPTOR, P_, nest::aeif_cond_alpha_multisynapse::Parameters_::receptor_types_, nest::aeif_cond_alpha_multisynapse::Variables_::RefractoryCounts_, S_, nest::aeif_cond_alpha_multisynapse::Buffers_::spike_exc_, nest::aeif_cond_alpha_multisynapse::Buffers_::spike_inh_, nest::aeif_cond_alpha_multisynapse::Parameters_::t_ref_, nest::aeif_cond_alpha_multisynapse::Parameters_::taus_syn, V_, nest::aeif_cond_alpha_multisynapse::State_::y_, nest::aeif_cond_alpha_multisynapse::State_::yin, nest::aeif_cond_alpha_multisynapse::State_::ynew, and nest::aeif_cond_alpha_multisynapse::State_::yref.
void nest::aeif_cond_alpha_multisynapse::get_status (DictionaryDatum & d) const inline
References nest::aeif_cond_alpha_multisynapse::Parameters_::get(), nest::aeif_cond_alpha_multisynapse::State_::get(), nest::Archiving_Node::get_status(), P_, nest::names::recordables, recordablesMap_, and S_.
template<State_::StateVecElems elem> double_t nest::aeif_cond_alpha_multisynapse::get_y_elem_ () const inline private
Read out state vector elements, used by UniversalDataLogger.
References S_, and nest::aeif_cond_alpha_multisynapse::State_::y_.
Referenced by nest::RecordablesMap< HostNode >::create().
void nest::aeif_cond_alpha_multisynapse::handle (SpikeEvent & e) virtual
Handle incoming spike events.
Default implementation of event handlers just throws an UnexpectedEvent exception.
Parameters
thrd Id of the calling thread.
e Event object.
This handler has to be implemented if a Node should accept spike events.
See also
class SpikeEvent
class UnexpectedEvent
Exceptions
UnexpectedEvent This is the default event to throw.
Reimplemented from nest::Node.
References assert(), B_, nest::Event::get_delay(), nest::SpikeEvent::get_multiplicity(), nest::Event::get_rel_delivery_steps(), nest::Event::get_rport(), nest::Event::get_weight(), nest::Node::network(), nest::aeif_cond_alpha_multisynapse::Parameters_::num_of_receptors_, P_, nest::aeif_cond_alpha_multisynapse::Buffers_::spike_exc_, and nest::aeif_cond_alpha_multisynapse::Buffers_::spike_inh_.
void nest::aeif_cond_alpha_multisynapse::handle (CurrentEvent & e) virtual
Handler for current events.
See also
handle(thread, SpikeEvent&)
Exceptions
UnexpectedEvent
Reimplemented from nest::Node.
References nest::RingBuffer::add_value(), assert(), B_, nest::aeif_cond_alpha_multisynapse::Buffers_::currents_, nest::CurrentEvent::get_current(), nest::Event::get_delay(), nest::Event::get_rel_delivery_steps(), nest::Event::get_weight(), nest::names::I, nest::Node::network(), and nest::names::w.
void nest::aeif_cond_alpha_multisynapse::handle (DataLoggingRequest & e) virtual
Handler for universal data logging request.
See also
handle(SpikeEvent&)
Exceptions
UnexpectedEvent
Reimplemented from nest::Node.
References B_, and nest::aeif_cond_alpha_multisynapse::Buffers_::logger_.
port nest::aeif_cond_alpha_multisynapse::handles_test_event (SpikeEvent & , rport receptor_type) virtual
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event().
handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle.
See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3.
Note
The semantics of all other handles_test_event() functions is identical.
Exceptions
IllegalConnection
Reimplemented from nest::Node.
References nest::Node::get_name(), nest::aeif_cond_alpha_multisynapse::Parameters_::has_connections_, nest::aeif_cond_alpha_multisynapse::Parameters_::num_of_receptors_, P_, and nest::names::receptor_type.
port nest::aeif_cond_alpha_multisynapse::handles_test_event (CurrentEvent & , rport receptor_type) inline virtual
Reimplemented from nest::Node.
References nest::Node::get_name().
port nest::aeif_cond_alpha_multisynapse::handles_test_event (DataLoggingRequest & dlr, rport receptor_type) inline virtual
Reimplemented from nest::Node.
References B_, nest::Node::get_name(), nest::aeif_cond_alpha_multisynapse::Buffers_::logger_, and recordablesMap_.
void nest::aeif_cond_alpha_multisynapse::init_buffers_ () private virtual
Private function to initialize the buffers of a node.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the buffers of a node.
See also
Node::init_buffers()
Implements nest::Node.
References B_, nest::RingBuffer::clear(), nest::Archiving_Node::clear_history(), nest::aeif_cond_alpha_multisynapse::Buffers_::currents_, nest::Time::get_ms(), nest::Time::get_resolution(), nest::aeif_cond_alpha_multisynapse::Buffers_::I_stim_, nest::aeif_cond_alpha_multisynapse::Buffers_::IntegrationStep_, nest::aeif_cond_alpha_multisynapse::Buffers_::logger_, nest::names::min, nest::aeif_cond_alpha_multisynapse::Buffers_::spike_exc_, nest::aeif_cond_alpha_multisynapse::Buffers_::spike_inh_, and nest::aeif_cond_alpha_multisynapse::Buffers_::step_.
void nest::aeif_cond_alpha_multisynapse::init_state_ (const Node &) private virtual
Private function to initialize the state of a node to model defaults.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the state of a node to the model defaults; the state is the set of observable dynamic variables.
Parameters
Reference to model prototype object.
See also
Node::init_state()
Note
To provide a reasonable behavior during the transition to the new scheme, init_state_() has a default implementation calling init_dynamic_state_().
Implements nest::Node.
References nest::Node::downcast(), and S_.
port nest::aeif_cond_alpha_multisynapse::send_test_event (Node & receiving_node, rport receptor_type, synindex syn_id, bool dummy_target) inline virtual
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws UnexpectedEvent.
This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node.
If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
Reimplemented from nest::Node.
References numerics::e, nest::Node::handles_test_event(), and nest::Event::set_sender().
void nest::aeif_cond_alpha_multisynapse::set_status (const DictionaryDatum & d) inline
References P_, S_, nest::aeif_cond_alpha_multisynapse::Parameters_::set(), nest::aeif_cond_alpha_multisynapse::State_::set(), and nest::Archiving_Node::set_status().
void nest::aeif_cond_alpha_multisynapse::update (Time const & , const long_t , const long_t) private virtual
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to.
Parameters
Time network time at beginning of time slice.
long_t initial step inside time slice
long_t post-final step inside time slice
Implements nest::Node.
References aeif_cond_alpha_multisynapse_dynamics(), assert(), nest::aeif_cond_alpha_multisynapse::Parameters_::b, B_, nest::aeif_cond_alpha_multisynapse::Buffers_::currents_, nest::aeif_cond_alpha_multisynapse::State_::DG_EXC, nest::aeif_cond_alpha_multisynapse::State_::DG_INH, nest::aeif_cond_alpha_multisynapse::Variables_::g0_ex_, nest::aeif_cond_alpha_multisynapse::Variables_::g0_in_, nest::Scheduler::get_min_delay(), nest::Node::get_name(), nest::Time::get_steps(), nest::RingBuffer::get_value(), nest::names::h, nest::names::HMIN, nest::aeif_cond_alpha_multisynapse::Parameters_::HMIN, nest::aeif_cond_alpha_multisynapse::Buffers_::I_stim_, nest::aeif_cond_alpha_multisynapse::Buffers_::IntegrationStep_, nest::aeif_cond_alpha_multisynapse::State_::k1, nest::aeif_cond_alpha_multisynapse::State_::k2, nest::aeif_cond_alpha_multisynapse::State_::k3, nest::aeif_cond_alpha_multisynapse::State_::k4, nest::aeif_cond_alpha_multisynapse::State_::k5, nest::aeif_cond_alpha_multisynapse::State_::k6, nest::aeif_cond_alpha_multisynapse::State_::k7, nest::aeif_cond_alpha_multisynapse::Buffers_::logger_, nest::names::max, nest::aeif_cond_alpha_multisynapse::Parameters_::MAXERR, nest::names::MAXERR, nest::Node::network(), nest::aeif_cond_alpha_multisynapse::Parameters_::num_of_receptors_, nest::aeif_cond_alpha_multisynapse::State_::NUMBER_OF_STATES_ELEMENTS_PER_RECEPTOR, P_, nest::aeif_cond_alpha_multisynapse::State_::r_, nest::aeif_cond_alpha_multisynapse::Variables_::RefractoryCounts_, S_, nest::Network::send(), nest::Archiving_Node::set_spiketime(), nest::aeif_cond_alpha_multisynapse::Buffers_::spike_exc_, nest::aeif_cond_alpha_multisynapse::Buffers_::spike_inh_, nest::aeif_cond_alpha_multisynapse::Buffers_::step_, V_, nest::aeif_cond_alpha_multisynapse::State_::V_M, nest::aeif_cond_alpha_multisynapse::Parameters_::V_peak_, nest::aeif_cond_alpha_multisynapse::Parameters_::V_reset_, nest::aeif_cond_alpha_multisynapse::State_::W, nest::aeif_cond_alpha_multisynapse::State_::y_, nest::aeif_cond_alpha_multisynapse::State_::yin, nest::aeif_cond_alpha_multisynapse::State_::ynew, and nest::aeif_cond_alpha_multisynapse::State_::yref.
Friends And Related Function Documentation
friend class RecordablesMap< aeif_cond_alpha_multisynapse > friend
friend class UniversalDataLogger< aeif_cond_alpha_multisynapse > friend
Member Data Documentation
nest::RecordablesMap< nest::aeif_cond_alpha_multisynapse > nest::aeif_cond_alpha_multisynapse::recordablesMap_ static private
Mapping of recordables names to access functions.
Referenced by aeif_cond_alpha_multisynapse(), get_status(), and handles_test_event().
The documentation for this class was generated from the following files:
aeif_cond_alpha_multisynapse.h
aeif_cond_alpha_multisynapse.cpp