NEST: librandom::GammaRandomDev Class Reference
librandom::GammaRandomDev Class Reference
Random Deviate Generators.
Class GammaRandomDev Create gamma distributed random numbers.
#include <gamma_randomdev.h>
Public Member Functions
GammaRandomDev (RngPtr, double a_in=1.0)
create with fixed RNG
GammaRandomDev (double a_in=1.0)
create w/o fixed RNG for threaded simulations
void set_order (double)
set order
void set_scale (double)
set scale parameter
void set_status (const DictionaryDatum &)
set distribution parameters from SLI dict
void get_status (DictionaryDatum &) const
get distribution parameters from SLI dict
double operator() (RngPtr) const
draw number, threaded
double operator() (RngPtr, double)
draw number, threaded, explicit order
Public Member Functions inherited from librandom::RandomDev
RandomDev (RngPtr rng=RngPtr(0))
Construct with (single-threaded) or without (multithreaded) RNG.
virtual ~RandomDev ()
ensure proper clean-up
virtual double operator() (void)
Operator delivering doubles.
virtual long ldev (void)
integer valued functions for discrete distributions
virtual long ldev (RngPtr) const
virtual bool has_ldev () const
true if RDG implements ldev function
void set_rng (RngPtr rng)
set RNG
Private Member Functions
double unscaled_gamma (RngPtr r) const
Private Attributes
double a
worker function creating Gamma(x; order, 1) number
double b_
double bb
double bc
double ju
double jv
Additional Inherited Members
Protected Attributes inherited from librandom::RandomDev
RngPtr rng_
store underlying RNG
Detailed Description
Class GammaRandomDev Create gamma distributed random numbers.
Constructor & Destructor Documentation
librandom::GammaRandomDev::GammaRandomDev (RngPtr r_source, double a_in = 1.0)
create with fixed RNG
References a, and set_order().
librandom::GammaRandomDev::GammaRandomDev (double a_in = 1.0)
create w/o fixed RNG for threaded simulations
References a, and set_order().
Member Function Documentation
void librandom::GammaRandomDev::get_status (DictionaryDatum & d) const virtual
get distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::a, and nest::names::d.
double librandom::GammaRandomDev::operator() (RngPtr r) const inline virtual
draw number, threaded
Implements librandom::RandomDev.
References b_, and unscaled_gamma().
double librandom::GammaRandomDev::operator() (RngPtr rthrd, double a) inline
draw number, threaded, explicit order
References set_order().
void librandom::GammaRandomDev::set_order (double a_in = 1.0) inline
set order
References a, assert(), bb, bc, ju, and jv.
Referenced by GammaRandomDev(), and operator()().
void librandom::GammaRandomDev::set_scale (double)
set scale parameter
void librandom::GammaRandomDev::set_status (const DictionaryDatum & d) virtual
set distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::a, and nest::names::d.
double librandom::GammaRandomDev::unscaled_gamma (RngPtr r) const private
References nest::names::a, librandom::RandomGen::drand(), librandom::RandomGen::drandpos(), and nest::names::S.
Referenced by operator()().
Member Data Documentation
double librandom::GammaRandomDev::a private
worker function creating Gamma(x; order, 1) number
Referenced by GammaRandomDev(), and set_order().
double librandom::GammaRandomDev::b_ private
Referenced by operator()().
double librandom::GammaRandomDev::bb private
Referenced by set_order().
double librandom::GammaRandomDev::bc private
Referenced by set_order().
double librandom::GammaRandomDev::ju private
Referenced by set_order().
double librandom::GammaRandomDev::jv private
Referenced by set_order().
The documentation for this class was generated from the following files:
gamma_randomdev.h
gamma_randomdev.cpp