NEST: nest::Network Class Reference
nest::Network Class Reference
Model developer interface. | Network access and administration
Main administrative interface to the network.
#include <network.h>
Classes
struct MusicPortData
Data structure to hold variables and parameters associated with a port.
Public Member Functions
Network (SLIInterpreter &)
~Network ()
void reset ()
Reset deletes all nodes and reallocates all memory pools for nodes.
void reset_kernel ()
Reset number of threads to one, reset device prefix to the empty string and call reset().
void reset_network ()
Reset the network to the state at T = 0.
void register_basis_model (Model &m, bool private_model=false)
Registers a fundamental model for use with the network.
index register_model (Model &m, bool private_model=false)
Register a built-in model for use with the network.
void unregister_model (index m_id)
Unregister a previously registered model.
void try_unregister_model (index m_id)
Try unregistering model prototype.
index copy_model (index old_id, std::string new_name)
Copy an existing model and register it as a new model.
synindex register_synapse_prototype (ConnectorModel *cf)
Register a synapse prototype at the connection manager.
int copy_synapse_prototype (index sc, std::string)
Copy an existing synapse type.
template<typename ConnBuilder >
void register_conn_builder (const std::string &name)
Add a connectivity rule, i.e.
int get_model_id (const char[]) const
Return the model id for a given model name.
Model * get_model (index) const
Return the Model for a given model ID.
Model * get_model_of_gid (index)
Return the Model for a given GID.
index get_model_id_of_gid (index)
Return the Model ID for a given GID.
const modelrange & get_contiguous_gid_range (index gid) const
Return the contiguous range of ids of nodes with the same model than the node with the given GID.
index add_node (index m, long_t n=1)
Add a number of nodes to the network.
void restore_nodes (ArrayDatum &)
Restore nodes from an array of status dictionaries.
void init_state (index)
Set the state (observable dynamic variables) of a node to model defaults.
index size () const
Return total number of network nodes.
void connect (index s, Node *target, thread target_thread, index syn, double_t d=NAN, double_t w=NAN)
Connect two nodes.
void connect (index s, Node *target, thread target_thread, index syn, DictionaryDatum &params, double_t d=NAN, double_t w=NAN)
Connect two nodes.
bool connect (index s, index r, DictionaryDatum &params, index syn)
Connect two nodes.
void subnet_connect (Subnet &, Subnet &, int, index syn)
void connect (ArrayDatum &connectome)
Connect from an array of dictionaries.
void divergent_connect (index s, const TokenArray r, const TokenArray weights, const TokenArray delays, index syn)
void divergent_connect (index s, DictionaryDatum d, index syn)
Connect one source node with many targets.
void random_divergent_connect (index s, const TokenArray r, index n, const TokenArray w, const TokenArray d, bool, bool, index syn)
void convergent_connect (const TokenArray s, index r, const TokenArray weights, const TokenArray delays, index syn)
void convergent_connect (const std::vector< index > &s_id, index r, const TokenArray &weight, const TokenArray &delays, index syn)
Specialized version of convegent_connect called by random_convergent_connect threaded.
void random_convergent_connect (const TokenArray s, index t, index n, const TokenArray w, const TokenArray d, bool, bool, index syn)
void random_convergent_connect (TokenArray s, TokenArray t, TokenArray n, TokenArray w, TokenArray d, bool, bool, index syn)
Use openmp threaded parallelization to speed up connection.
void connect (const GIDCollection &, const GIDCollection &, const DictionaryDatum &, const DictionaryDatum &)
Create connections.
DictionaryDatum get_connector_defaults (index sc)
void set_connector_defaults (index sc, DictionaryDatum &d)
DictionaryDatum get_synapse_status (index gid, index syn, port p, thread tid)
void set_synapse_status (index gid, index syn, port p, thread tid, DictionaryDatum &d)
ArrayDatum get_connections (DictionaryDatum dict)
Subnet * get_root () const
return root subnet.
Subnet * get_cwn () const
current working node.
void go_to (index)
Change current working node.
void simulate (Time const &)
void resume ()
Resume the simulation after it was terminated.
void terminate ()
Terminate the simulation after the time-slice is finished.
bool quit_by_error () const
Return true if NEST will be quit because of an error, false otherwise.
int get_exitcode () const
Return the exitcode that would be returned to the calling shell if NEST would quit now.
void memory_info ()
void print (index, int)
void trigger_update_weight (const long_t vt_gid, const vector< spikecounter > &dopa_spikes, const double_t t_trig)
Triggered by volume transmitter in update.
template<class EventT >
void send (Node &source, EventT &e, const long_t lag=0)
Standard routine for sending events.
void send_local (thread t, Node &source, Event &e)
Send event e to all targets of node source on thread t.
void send_to_node (Event &e)
Send event e directly to its target node.
delay get_min_delay () const
Return minimal connection delay.
delay get_max_delay () const
Return maximal connection delay.
Time const & get_slice_origin () const
Get the time at the beginning of the current time slice.
Time get_previous_slice_origin () const
Get the time at the beginning of the previous time slice.
Time const get_time () const
Get the current simulation time.
librandom::RngPtr get_rng (thread thrd=0) const
Get random number client of a thread.
librandom::RngPtr get_grng () const
Get global random number client.
thread get_num_threads () const
Get number of threads.
thread suggest_vp (index) const
Suggest a VP for a given global node ID.
thread suggest_rec_vp (index) const
Suggest a VP for a given global recording node ID.
thread vp_to_thread (thread vp) const
Convert a given VP ID to the corresponding thread ID.
thread thread_to_vp (thread t) const
Convert a given thread ID to the corresponding VP ID.
thread get_num_processes () const
Get number of processes.
thread get_num_rec_processes () const
Get number of recording processes.
thread get_num_sim_processes () const
Get number of simulating processes.
void set_num_rec_processes (int nrp)
Set number of recording processes.
bool is_local_node (Node *) const
Return true, if the given Node is on the local machine.
bool is_local_gid (index gid) const
Return true, if the given gid is on the local machine.
bool is_local_vp (thread) const
Return true, if the given VP is on the local machine.
bool get_simulated () const
See Scheduler::get_simulated()
Node * get_node (index, thread thr=0)
Return pointer of the specified Node.
const SiblingContainer * get_thread_siblings (index n) const
Return the Subnet that contains the thread siblings.
bool model_in_use (index i)
Check, if there are instances of a given model.
const std::string & get_data_prefix () const
The prefix for files written by devices.
const std::string & get_data_path () const
The path for files written by devices.
bool overwrite_files () const
Indicate if existing data files should be overwritten.
bool get_off_grid_communication () const
return current communication style.
void set_status (index, const DictionaryDatum &)
Set properties of a Node.
DictionaryDatum get_status (index)
Get properties of a node.
int execute_sli_protected (DictionaryDatum, Name)
Execute a SLI command in the neuron's namespace.
const Dictionary & get_modeldict ()
Return a reference to the model dictionary.
const Dictionary & get_synapsedict () const
Return the synapse dictionary.
void calibrate_clock ()
Recalibrate scheduler clock.
size_t write_toggle () const
Return 0 for even, 1 for odd time slices.
size_t read_toggle () const
Return 1 - write_toggle().
bool has_user_models () const
Does the network contain copies of models created using CopyModel?
void ensure_valid_thread_local_ids ()
Ensure that all nodes in the network have valid thread-local IDs.
void message (int level, const char from[], const char text[])
Display a message.
void message (int level, const std::string &loc, const std::string &msg)
bool dict_miss_is_error () const
Returns true if unread dictionary items should be treated as error.
void register_music_in_port (std::string portname)
Register a MUSIC input port (portname) with the port list.
void unregister_music_in_port (std::string portname)
Unregister a MUSIC input port (portname) from the port list.
void register_music_event_in_proxy (std::string portname, int channel, nest::Node *mp)
Register a node (of type music_input_proxy) with a given MUSIC port (portname) and a specific channel.
void set_music_in_port_acceptable_latency (std::string portname, double_t latency)
Set the acceptable latency (latency) for a music input port (portname).
void set_music_in_port_max_buffered (std::string portname, int_t maxbuffered)
void publish_music_in_ports_ ()
Publish all MUSIC input ports that were registered using Network::register_music_event_in_proxy().
void update_music_event_handlers_ (Time const &, const long_t, const long_t)
Call update() for each of the registered MUSIC event handlers to deliver all queued events to the target music_in_proxies.
int get_thread_id () const
Gets ID of local thread.
void set_model_defaults_modified ()
bool model_defaults_modified () const
Node * thread_lid_to_node (thread t, targetindex thread_local_id) const
template<>
void send (Node &source, SpikeEvent &e, const long_t lag)
template<>
void send (Node &source, DSSpikeEvent &e, const long_t lag)
Public Attributes
std::map< std::string,
MusicPortData > music_in_portlist_
The mapping between MUSIC input ports identified by portname and the corresponding port variables and parameters.
std::map< std::string,
MusicEventHandler > music_in_portmap_
The mapping between MUSIC input ports identified by portname and the corresponding MUSIC event handler.
Private Member Functions
void init_ ()
Initialize the network data structures.
void destruct_nodes_ ()
void clear_models_ (bool called_from_destructor=false)
void set_status_single_node_ (Node &, const DictionaryDatum &, bool clear_flags=true)
Helper function to set properties on single node.
void set_data_path_prefix_ (const DictionaryDatum &d)
Helper function to set device data path and prefix.
Private Attributes
SLIInterpreter & interpreter_
SparseNodeArray local_nodes_
The network as sparse array of local nodes.
Scheduler scheduler_
ConnectionManager connection_manager_
Subnet * root_
Root node.
Subnet * current_
Current working node (for insertion).
Dictionary * synapsedict_
Dictionary for synapse models.
Dictionary * modeldict_
Dictionary for models.
Dictionary * connruledict_
Dictionary for connection rules.
Model * siblingcontainer_model
The model for the SiblingContainer class.
std::string data_path_
Path for all files written by devices.
std::string data_prefix_
Prefix for all files written by devices.
bool overwrite_files_
If true, overwrite existing data files.
std::vector< std::pair< Model
*, bool > > pristine_models_
The list of clean models.
std::vector< Model * > models_
The list of available models.
std::vector< std::vector< Node * > > proxy_nodes_
Placeholders for remote nodes, one per thread.
std::vector< Node * > dummy_spike_sources_
Placeholders for spiking remote nodes, one per thread.
std::vector
< GenericConnBuilderFactory * > connbuilder_factories_
Modelrangemanager node_model_ids_
ConnBuilder factories, indexed by connruledict_ elements.
bool dict_miss_is_error_
whether to throw exception on missed dictionary entries
bool model_defaults_modified_
whether any model defaults have been modified
Friends
class Scheduler
Detailed Description
Main administrative interface to the network.
Class Network is responsible for
Administration of Model objects.
Administration of network Nodes.
Administration of the simulation time.
Update and scheduling during simulation.
Memory cleanup at exit.
See also
Node
Model
Constructor & Destructor Documentation
nest::Network::Network (SLIInterpreter & i)
References connection_manager_, connruledict_, SLIInterpreter::def(), nest::ConnectionManager::init(), init_(), interpreter_, nest::names::model, modeldict_, nest::Communicator::net_, nest::Node::net_, register_basis_model(), nest::Model::set_type_id(), siblingcontainer_model, and synapsedict_.
nest::Network::~Network ()
References clear_models_(), destruct_nodes_(), and pristine_models_.
Member Function Documentation
index nest::Network::add_node (index m, long_t n = 1)
Add a number of nodes to the network.
This function creates n Node objects of Model m and adds them to the Network at the current position.
Parameters
m valid Model ID.
n Number of Nodes to be created. Defaults to 1 if not specified.
Exceptions
nest::UnknownModelID
References nest::SparseNodeArray::add_local_node(), nest::Subnet::add_node(), nest::Modelrangemanager::add_range(), nest::SparseNodeArray::add_remote_node(), nest::Subnet::add_remote_node(), nest::Model::allocate(), assert(), current_, nest::Node::get_gid(), nest::SparseNodeArray::get_max_gid(), nest::Scheduler::get_n_gsd(), nest::SparseNodeArray::get_node_by_gid(), nest::Scheduler::get_num_rec_processes(), nest::Scheduler::get_num_sim_processes(), get_num_threads(), nest::Communicator::get_rank(), nest::SiblingContainer::get_thread_sibling_(), nest::Model::has_proxies(), nest::Scheduler::increment_n_gsd(), is_local_vp(), nest::Model::is_off_grid(), local_nodes_, SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, nest::SparseNodeArray::max_size(), message(), nest::mod(), nest::names::model, models_, nest::names::n, node_model_ids_, nest::SiblingContainer::num_thread_siblings_(), nest::Model::one_node_per_process(), nest::Model::potential_global_receiver(), nest::SiblingContainer::push_back(), nest::SiblingContainer::reserve(), nest::SparseNodeArray::reserve(), nest::Model::reserve_additional(), root_, scheduler_, nest::Node::set_gid_(), nest::Node::set_has_proxies(), nest::Node::set_local_receiver(), nest::Node::set_model_id(), nest::Scheduler::set_off_grid_communication(), nest::Node::set_thread(), nest::Node::set_vp(), siblingcontainer_model, suggest_rec_vp(), suggest_vp(), thread_to_vp(), nest::names::vp, and vp_to_thread().
Referenced by nest::AbstractLayer::create_layer(), nest::NestModule::Create_l_iFunction::execute(), and restore_nodes().
void nest::Network::calibrate_clock () inline
Recalibrate scheduler clock.
References nest::Scheduler::calibrate_clock(), and scheduler_.
Referenced by nest::NestModule::init().
void nest::Network::clear_models_ (bool called_from_destructor = false) private
References Dictionary::clear(), SLIInterpreter::M_INFO, message(), model_defaults_modified_, modeldict_, and models_.
Referenced by reset(), and ~Network().
void nest::Network::connect (index s, Node * target, thread target_thread, index syn, double_t d = NAN, double_t w = NAN)
Connect two nodes.
The source node is defined by its global ID. The target node is defined by the node. The connection is established on the thread/process that owns the target node.
The parameters delay and weight have the default value NAN. NAN is a special value in cmath, which describes double values that are not a number. If delay or weight is omitted in a connect call, NAN indicates this and weight/delay are set only, if they are valid.
Parameters
s GID of the sending Node.
target Pointer to target Node.
target_thread Thread that hosts the target node.
syn The synapse model to use.
d Delay of the connection (in ms).
w Weight of the connection.
References nest::ConnectionManager::connect(), connection_manager_, nest::Node::get_gid(), get_node(), get_num_threads(), nest::Node::get_thread(), nest::Node::has_proxies(), nest::Node::is_proxy(), nest::Node::local_receiver(), nest::names::source, and nest::names::target_thread.
Referenced by nest::cg_connect(), nest::ConnectionCreator::connect_(), nest::ConnectionCreator::convergent_connect_(), divergent_connect(), nest::ConnectionCreator::divergent_connect_(), nest::NestModule::DataConnect_aFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), nest::NestModule::Connect_g_g_D_DFunction::execute(), and nest::ConnectionCreator::source_driven_connect_().
void nest::Network::connect (index s, Node * target, thread target_thread, index syn, DictionaryDatum & params, double_t d = NAN, double_t w = NAN)
Connect two nodes.
The source node is defined by its global ID. The target node is defined by the node. The connection is established on the thread/process that owns the target node.
The parameters delay and weight have the default value NAN. NAN is a special value in cmath, which describes double values that are not a number. If delay or weight is omitted in an connect call, NAN indicates this and weight/delay are set only, if they are valid.
Parameters
s GID of the sending Node.
target Pointer to target Node.
target_thread Thread that hosts the target node.
syn The synapse model to use.
params parameter dict to configure the synapse
d Delay of the connection (in ms).
w Weight of the connection.
References nest::ConnectionManager::connect(), connection_manager_, nest::Node::get_gid(), get_node(), get_num_threads(), nest::Node::get_thread(), nest::Node::has_proxies(), nest::Node::is_proxy(), nest::Node::local_receiver(), nest::names::source, and nest::names::target_thread.
bool nest::Network::connect (index s, index r, DictionaryDatum & params, index syn)
Connect two nodes.
The source node is defined by its global ID. The target node is defined by the node. The connection is established on the thread/process that owns the target node.
Parameters
s GID of the sending Node.
target pointer to target Node.
target_thread thread that hosts the target node
params parameter dict to configure the synapse
syn The synapse model to use.
References nest::ConnectionManager::connect(), connection_manager_, get_node(), get_num_threads(), nest::Node::get_thread(), nest::Node::has_proxies(), is_local_gid(), nest::Node::is_proxy(), nest::Node::local_receiver(), and nest::names::target_thread.
void nest::Network::connect (ArrayDatum & connectome) inline
Connect from an array of dictionaries.
References nest::ConnectionManager::connect(), and connection_manager_.
void nest::Network::connect (const GIDCollection & sources, const GIDCollection & targets, const DictionaryDatum & conn_spec, const DictionaryDatum & syn_spec)
Create connections.
References assert(), connbuilder_factories_, nest::ConnBuilder::connect(), connruledict_, dict_miss_is_error(), Dictionary::known(), SLIInterpreter::M_WARNING, message(), and nest::names::rule.
void nest::Network::convergent_connect (const TokenArray s, index r, const TokenArray weights, const TokenArray delays, index syn)
References nest::LocalNodeListBase< ListIterator >::begin(), nest::ConnectionManager::connect(), connection_manager_, nest::names::delays, numerics::e, nest::LocalNodeListBase< ListIterator >::end(), TokenArray::get(), nest::Node::get_gid(), get_node(), nest::Node::get_thread(), getValue< long >(), nest::Node::has_proxies(), is_local_gid(), nest::Node::is_proxy(), SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, SLIInterpreter::M_WARNING, TypeMismatch::message(), nest::UnknownReceptorType::message(), nest::IllegalConnection::message(), message(), TokenArray::size(), nest::names::source, nest::names::target, nest::names::target_thread, and nest::names::weights.
Referenced by nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), and random_convergent_connect().
void nest::Network::convergent_connect (const std::vector< index > & s_id, index r, const TokenArray & weight, const TokenArray & delays, index syn)
Specialized version of convegent_connect called by random_convergent_connect threaded.
New and specialized variant of the convergent_connect() function, which takes a vector<Node*> for sources and relies on the fact that target is guaranteed to be on this thread.
References nest::ConnectionManager::connect(), connection_manager_, numerics::e, TokenArray::get(), nest::Node::get_gid(), get_node(), nest::Node::get_thread(), nest::Node::has_proxies(), nest::Node::is_proxy(), SLIInterpreter::M_WARNING, TypeMismatch::message(), nest::UnknownReceptorType::message(), nest::IllegalConnection::message(), message(), TokenArray::size(), nest::names::source, nest::names::target, and nest::names::target_thread.
index nest::Network::copy_model (index old_id, std::string new_name)
Copy an existing model and register it as a new model.
This function allows users to create their own, cloned models.
Parameters
old_id The id of the existing model.
new_name The name of the new model.
Return values
Index,identifying the new Model object.
See also
copy_synapse_prototype()
Todo:
Not fully compatible with thread number changes and unregister_model() yet.
References nest::Model::allocate(), assert(), nest::Model::clone(), get_model(), get_model_id(), get_num_threads(), Dictionary::insert(), Dictionary::known(), modeldict_, models_, proxy_nodes_, and nest::Node::set_model_id().
Referenced by nest::NestModule::CopyModel_l_l_DFunction::execute().
int nest::Network::copy_synapse_prototype (index sc, std::string name) inline
Copy an existing synapse type.
See also
copy_model(), ConnectionManager::copy_synapse_prototype()
References connection_manager_, and nest::ConnectionManager::copy_synapse_prototype().
Referenced by nest::NestModule::CopyModel_l_l_DFunction::execute().
void nest::Network::destruct_nodes_ () private
References assert(), nest::Modelrangemanager::clear(), nest::SparseNodeArray::clear(), dummy_spike_sources_, nest::SparseNodeArray::get_node_by_index(), nest::Node::get_thread_sibling_(), local_nodes_, nest::names::n, node_model_ids_, nest::Node::num_thread_siblings_(), proxy_nodes_, nest::SparseNodeArray::size(), and nest::Node::~Node().
Referenced by reset(), and ~Network().
bool nest::Network::dict_miss_is_error () const inline
Returns true if unread dictionary items should be treated as error.
References dict_miss_is_error_.
Referenced by connect(), nest::TopologyModule::CreateLayer_DFunction::execute(), nest::TopologyModule::ConnectLayers_i_i_DFunction::execute(), nest::TopologyModule::CreateMask_DFunction::execute(), nest::TopologyModule::CreateParameter_DFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), nest::NestModule::SetStatus_aaFunction::execute(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::NestModule::GetConnections_DFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), and set_status_single_node_().
void nest::Network::divergent_connect (index s, const TokenArray r, const TokenArray weights, const TokenArray delays, index syn)
References nest::Communicator::communicate(), nest::ConnectionManager::connect(), connection_manager_, nest::names::delays, numerics::e, TokenArray::get(), nest::Node::get_gid(), get_node(), nest::Node::get_thread(), getValue< long >(), is_local_gid(), nest::Node::is_proxy(), SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, SLIInterpreter::M_WARNING, TypeMismatch::message(), nest::UnknownReceptorType::message(), nest::IllegalConnection::message(), message(), TokenArray::size(), nest::names::source, nest::names::target_thread, nest::names::targets, and nest::names::weights.
Referenced by divergent_connect(), nest::NestModule::DataConnect_i_D_sFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), and random_divergent_connect().
void nest::Network::divergent_connect (index s, DictionaryDatum d, index syn)
Connect one source node with many targets.
The dictionary d contains arrays for all the connections of type syn.
References ad, nest::Communicator::communicate(), connect(), Token::datum(), nest::names::delay, nest::names::delays, divergent_connect(), numerics::e, get_node(), Datum::gettypename(), SLIInterpreter::M_DEBUG, SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, SLIInterpreter::M_WARNING, nest::UnknownNode::message(), nest::UnknownReceptorType::message(), nest::IllegalConnection::message(), nest::UnexpectedEvent::message(), message(), nest::names::source, nest::names::target, Name::toString(), TokenArray::toVector(), nest::names::weight, and nest::names::weights.
void nest::Network::ensure_valid_thread_local_ids () inline
Ensure that all nodes in the network have valid thread-local IDs.
References nest::Scheduler::ensure_valid_thread_local_ids(), and scheduler_.
Referenced by nest::TargetIdentifierIndex::set_target().
int nest::Network::execute_sli_protected (DictionaryDatum state, Name cmd)
Execute a SLI command in the neuron's namespace.
This function is not thread save and has to be called inside a omp critical region, e.g.
sli_neuron.
References assert(), SLIInterpreter::DStack, SLIInterpreter::EStack, SLIInterpreter::execute_(), nest::names::global_id, interpreter_, TokenStack::load(), SLIInterpreter::M_ERROR, message(), nest::names::model, DictionaryStack::pop(), TokenStack::push(), DictionaryStack::push(), scheduler_, nest::Scheduler::terminate(), and Name::toString().
ArrayDatum nest::Network::get_connections (DictionaryDatum dict) inline
References connection_manager_, and nest::ConnectionManager::get_connections().
Referenced by nest::NestModule::GetConnections_DFunction::execute().
DictionaryDatum nest::Network::get_connector_defaults (index sc) inline
References connection_manager_, and nest::ConnectionManager::get_prototype_status().
Referenced by nest::ConnBuilder::ConnBuilder(), nest::ConnectionCreator::ConnectionCreator(), and nest::NestModule::GetDefaults_lFunction::execute().
const modelrange & nest::Network::get_contiguous_gid_range (index gid) const inline
Return the contiguous range of ids of nodes with the same model than the node with the given GID.
References nest::Modelrangemanager::get_range(), and node_model_ids_.
Subnet * nest::Network::get_cwn (void) const inline
current working node.
References current_.
Referenced by nest::AbstractLayer::create_layer(), nest::NestModule::CurrentSubnetFunction::execute(), and restore_nodes().
const std::string & nest::Network::get_data_path () const inline
The path for files written by devices.
It may be the empty string (use current directory).
See also
get_data_prefix(), overwrite_files()
References data_path_.
Referenced by nest::RecordingDevice::build_filename_().
const std::string & nest::Network::get_data_prefix () const inline
The prefix for files written by devices.
The prefix must not contain any part of a path.
See also
get_data_dir(), overwrite_files()
References data_prefix_.
Referenced by nest::RecordingDevice::build_filename_().
int nest::Network::get_exitcode () const inline
Return the exitcode that would be returned to the calling shell if NEST would quit now.
References SLIInterpreter::baselookup(), getValue< long >(), and interpreter_.
librandom::RngPtr nest::Network::get_grng () const inline
Get global random number client.
This grng must be used synchronized from all threads.
References nest::Scheduler::get_grng(), and scheduler_.
Referenced by nest::ConnectionCreator::divergent_connect_(), nest::TopologyModule::GetValue_a_PFunction::execute(), nest::NestModule::GetGlobalRngFunction::execute(), and random_divergent_connect().
delay nest::Network::get_max_delay () const inline
Return maximal connection delay.
References nest::Scheduler::get_max_delay(), and scheduler_.
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), and nest::ConnectorModel::assert_valid_delay_ms().
delay nest::Network::get_min_delay () const inline
Return minimal connection delay.
References nest::Scheduler::get_min_delay(), and scheduler_.
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), and nest::ConnectorModel::assert_valid_delay_ms().
Model * nest::Network::get_model (index m) const inline
Return the Model for a given model ID.
References models_.
Referenced by copy_model(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::Node::get_model_(), nest::Node::get_name(), nest::Node::init_state(), nest::proxynode::send_test_event(), try_unregister_model(), and unregister_model().
int nest::Network::get_model_id (const char name[]) const
Return the model id for a given model name.
References assert(), and models_.
Referenced by copy_model(), init_(), register_model(), and restore_nodes().
index nest::Network::get_model_id_of_gid (index gid) inline
Return the Model ID for a given GID.
References nest::Modelrangemanager::get_model_id(), nest::Modelrangemanager::is_in_range(), and node_model_ids_.
Referenced by get_model_of_gid().
Model * nest::Network::get_model_of_gid (index gid) inline
Return the Model for a given GID.
References get_model_id_of_gid(), and models_.
const Dictionary & nest::Network::get_modeldict () inline
Return a reference to the model dictionary.
References assert(), and modeldict_.
Referenced by nest::AbstractLayer::create_layer(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), and nest::Selector::Selector().
thread nest::Network::get_num_processes () const inline
Get number of processes.
References nest::Scheduler::get_num_processes(), and scheduler_.
thread nest::Network::get_num_rec_processes () const inline
Get number of recording processes.
References nest::Scheduler::get_num_rec_processes(), and scheduler_.
thread nest::Network::get_num_sim_processes () const inline
Get number of simulating processes.
References nest::Scheduler::get_num_sim_processes(), and scheduler_.
thread nest::Network::get_num_threads () const inline
Get number of threads.
This function returns the total number of threads per process.
References nest::Scheduler::get_num_threads(), and scheduler_.
Referenced by add_node(), nest::ConnBuilder::ConnBuilder(), connect(), copy_model(), nest::NestModule::get_num_threads(), init_(), register_model(), and unregister_model().
bool nest::Network::get_off_grid_communication () const inline
return current communication style.
A result of true means off_grid, false means on_grid communication.
References nest::Scheduler::get_off_grid_communication(), and scheduler_.
Time nest::Network::get_previous_slice_origin () const inline
Get the time at the beginning of the previous time slice.
References nest::Scheduler::get_previous_slice_origin(), and scheduler_.
librandom::RngPtr nest::Network::get_rng (thread thrd = 0) const inline
Get random number client of a thread.
Defaults to thread 0 to allow use in non-threaded context. One may consider to introduce an additional RNG just for the non-threaded context.
References nest::Scheduler::get_rng(), and scheduler_.
Referenced by nest::ConnectionCreator::connect_to_target_(), nest::ConnectionCreator::convergent_connect_(), nest::NestModule::GetVpRngFunction::execute(), random_convergent_connect(), nest::Quantal_StpConnection< targetidentifierT >::send(), and nest::ConnectionCreator::source_driven_connect_().
Subnet * nest::Network::get_root () const inline
return root subnet.
References root_.
bool nest::Network::get_simulated () const inline
See Scheduler::get_simulated()
References nest::Scheduler::get_simulated(), and scheduler_.
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), and nest::ConnectorModel::assert_valid_delay_ms().
Time const & nest::Network::get_slice_origin () const inline
Get the time at the beginning of the current time slice.
References nest::Scheduler::get_slice_origin(), and scheduler_.
Referenced by send().
DictionaryDatum nest::Network::get_status (index idx)
Get properties of a node.
The specified node must exist.
Exceptions
nest::UnknownNode Target does not exist in the network.
References assert(), connection_manager_, nest::names::d, data_path_, data_prefix_, dict_miss_is_error_, get_node(), nest::ConnectionManager::get_status(), nest::Scheduler::get_status(), nest::Node::get_status_base(), nest::SparseNodeArray::get_step_ctr(), local_nodes_, overwrite_files_, root_, scheduler_, size(), and nest::names::target.
Referenced by nest::Communicator::communicate(), and nest::NestModule::GetStatus_iFunction::execute().
DictionaryDatum nest::Network::get_synapse_status (index gid, index syn, port p, thread tid) inline
References connection_manager_, and nest::ConnectionManager::get_synapse_status().
Referenced by nest::NestModule::GetStatus_CFunction::execute(), and nest::NestModule::GetStatus_aFunction::execute().
const Dictionary & nest::Network::get_synapsedict () const inline
Return the synapse dictionary.
References assert(), and synapsedict_.
Referenced by nest::ConnBuilder::ConnBuilder(), nest::ConnectionCreator::ConnectionCreator(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), and nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute().
int nest::Network::get_thread_id () const inline
Gets ID of local thread.
Returns thread ID if OPENMP is installed and zero otherwise.
Referenced by nest::ConnectionCreator::connect_(), random_convergent_connect(), and nest::ConnectionCreator::target_driven_connect_().
Time const nest::Network::get_time () const inline
Get the current simulation time.
Defined only while no simulation in progress.
References nest::Scheduler::get_time(), and scheduler_.
void nest::Network::go_to (index n)
Change current working node.
The specified node must exist and be a subnet.
Exceptions
nest::IllegalOperation Target is no subnet.
References current_, get_node(), and nest::names::target.
Referenced by nest::AbstractLayer::create_layer(), nest::NestModule::ChangeSubnet_iFunction::execute(), and restore_nodes().
bool nest::Network::has_user_models () const inline
Does the network contain copies of models created using CopyModel?
References models_, and pristine_models_.
Referenced by nest::DynamicLoaderModule::UnloadModuleFunction::execute().
void nest::Network::init_ () private
Initialize the network data structures.
init_() is used by the constructor and by reset().
See also
reset()
Build modeldict, list of models and list of proxy nodes from clean prototypes.
References nest::SparseNodeArray::add_local_node(), nest::Modelrangemanager::add_range(), nest::Model::allocate(), assert(), current_, dummy_spike_sources_, get_model_id(), get_num_threads(), Dictionary::insert(), local_nodes_, modeldict_, models_, music_in_portlist_, node_model_ids_, pristine_models_, proxy_nodes_, nest::SiblingContainer::push_back(), nest::SiblingContainer::reserve(), nest::SparseNodeArray::reserve(), root_, set_data_path_prefix_(), nest::Node::set_gid_(), nest::Node::set_model_id(), nest::Node::set_thread(), nest::Node::set_vp(), siblingcontainer_model, and thread_to_vp().
Referenced by Network(), and reset().
void nest::Network::init_state (index GID)
Set the state (observable dynamic variables) of a node to model defaults.
See also
Node::init_state()
References get_node(), nest::Node::init_state(), and nest::names::n.
bool nest::Network::is_local_gid (index gid) const inline
Return true, if the given gid is on the local machine.
References nest::SparseNodeArray::get_node_by_gid(), and local_nodes_.
Referenced by nest::cg_connect(), connect(), nest::ConnectionCreator::connect_(), convergent_connect(), divergent_connect(), nest::TopologyModule::GetPosition_iFunction::execute(), nest::TopologyModule::Displacement_a_iFunction::execute(), nest::TopologyModule::Distance_a_iFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), and random_convergent_connect().
bool nest::Network::is_local_node (Node * n) const inline
Return true, if the given Node is on the local machine.
References nest::Node::is_proxy().
bool nest::Network::is_local_vp (thread t) const inline
Return true, if the given VP is on the local machine.
References nest::Scheduler::is_local_vp(), and scheduler_.
Referenced by add_node().
void nest::Network::memory_info ()
References nest::Model::get_element_size(), nest::Model::get_name(), nest::Model::mem_available(), nest::Model::mem_capacity(), nest::mod(), and models_.
Referenced by nest::NestModule::MemoryInfoFunction::execute().
void nest::Network::message (int level, const std::string & loc, const std::string & msg)
References message().
bool nest::Network::model_defaults_modified () const inline
References model_defaults_modified_.
bool nest::Network::model_in_use (index i)
Check, if there are instances of a given model.
Parameters
i index of the model to check for
Returns
true, if model is instantiated at least once.
References nest::Modelrangemanager::model_in_use(), and node_model_ids_.
Referenced by try_unregister_model(), and unregister_model().
bool nest::Network::overwrite_files () const inline
Indicate if existing data files should be overwritten.
Returns
true if existing data files should be overwritten by devices. Default: false.
References overwrite_files_.
Referenced by nest::RecordingDevice::calibrate().
void nest::Network::print (index p, int depth)
References get_node(), nest::Subnet::print_network(), and nest::names::target.
Referenced by nest::NestModule::PrintNetworkFunction::execute().
void nest::Network::publish_music_in_ports_ ()
Publish all MUSIC input ports that were registered using Network::register_music_event_in_proxy().
References music_in_portmap_.
bool nest::Network::quit_by_error () const inline
Return true if NEST will be quit because of an error, false otherwise.
References SLIInterpreter::baselookup(), getValue< bool >(), and interpreter_.
void nest::Network::random_convergent_connect (const TokenArray s, index t, index n, const TokenArray w, const TokenArray d, bool allow_multapses, bool allow_autapses, index syn)
References nest::names::allow_autapses, nest::names::allow_multapses, nest::LocalNodeListBase< ListIterator >::begin(), convergent_connect(), nest::names::delays, nest::LocalNodeListBase< ListIterator >::end(), get_node(), get_rng(), nest::Node::get_thread(), is_local_gid(), SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, message(), nest::names::n, TokenArray::size(), nest::names::target, and nest::names::weights.
Referenced by nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), and nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute().
void nest::Network::random_convergent_connect (TokenArray s, TokenArray t, TokenArray n, TokenArray w, TokenArray d, bool allow_multapses, bool allow_autapses, index syn)
Use openmp threaded parallelization to speed up connection.
Parallelize over target list.
References convergent_connect(), numerics::e, GenericDatum< D, slt >::get(), TokenArray::get(), get_node(), get_rng(), nest::Node::get_thread(), get_thread_id(), getValue< long >(), is_local_gid(), SLIInterpreter::M_ERROR, message(), nest::names::n, TokenArray::size(), and nest::names::target.
void nest::Network::random_divergent_connect (index s, const TokenArray r, index n, const TokenArray w, const TokenArray d, bool allow_multapses, bool allow_autapses, index syn)
References nest::names::allow_autapses, nest::names::allow_multapses, nest::Communicator::communicate(), nest::names::delays, divergent_connect(), TokenArray::get(), get_grng(), get_node(), SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, message(), nest::names::n, TokenArray::push_back(), TokenArray::size(), nest::names::source, and nest::names::weights.
Referenced by nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute().
size_t nest::Network::read_toggle () const inline
Return 1 - write_toggle().
This is useful for buffers that need to be read alternatingly by slice. The value is given by 1-write_toggle().
See also
write_toggle
References write_toggle().
void nest::Network::register_basis_model (Model & m, bool private_model = false)
Registers a fundamental model for use with the network.
Parameters
m Model object.
private_model If true, model is not entered in modeldict.
Returns
void
Note
The Network calls the Model object's destructor at exit.
See also
register_model, unregister_model, register_user_model
References nest::Model::get_name(), Dictionary::known(), modeldict_, and pristine_models_.
Referenced by Network().
template<typename ConnBuilder > void nest::Network::register_conn_builder (const std::string & name)
Add a connectivity rule, i.e.
the respective ConnBuilderFactory.
References assert(), connbuilder_factories_, connruledict_, Dictionary::insert(), and Dictionary::known().
Referenced by nest::NestModule::init().
index nest::Network::register_model (Model & m, bool private_model = false)
Register a built-in model for use with the network.
Also enters the model in modeldict, unless private_model is true.
Parameters
m Model object.
private_model If true, model is not entered in modeldict.
Returns
Model ID assigned by network
Note
The Network calls the Model object's destructor at exit.
See also
unregister_model, register_user_model
References nest::Model::allocate(), assert(), nest::Model::clone(), get_model_id(), nest::Model::get_name(), get_num_threads(), Dictionary::insert(), Dictionary::known(), modeldict_, models_, pristine_models_, proxy_nodes_, nest::Model::set_model_id(), nest::Node::set_model_id(), and nest::Model::set_type_id().
Referenced by nest::register_model(), and nest::register_preconf_model().
void nest::Network::register_music_event_in_proxy (std::string portname, int channel, nest::Node * mp)
Register a node (of type music_input_proxy) with a given MUSIC port (portname) and a specific channel.
The proxy will be notified, if a MUSIC event is being received on the respective channel and port.
References music_in_portlist_, music_in_portmap_, and nest::MusicEventHandler::register_channel().
void nest::Network::register_music_in_port (std::string portname)
Register a MUSIC input port (portname) with the port list.
This will increment the counter of the respective entry in the music_in_portlist.
References music_in_portlist_.
Referenced by nest::music_event_in_proxy::music_event_in_proxy().
synindex nest::Network::register_synapse_prototype (ConnectorModel * cf) inline
Register a synapse prototype at the connection manager.
References connection_manager_, and nest::ConnectionManager::register_synapse_prototype().
Referenced by nest::register_connection_model().
void nest::Network::reset ()
Reset deletes all nodes and reallocates all memory pools for nodes.
References clear_models_(), connection_manager_, destruct_nodes_(), init_(), pristine_models_, nest::ConnectionManager::reset(), nest::Scheduler::reset(), and scheduler_.
Referenced by reset_kernel().
void nest::Network::reset_kernel ()
Reset number of threads to one, reset device prefix to the empty string and call reset().
References data_path_, data_prefix_, dict_miss_is_error_, overwrite_files_, reset(), scheduler_, nest::Scheduler::set_num_rec_processes(), and nest::Scheduler::set_num_threads().
Referenced by nest::NestModule::ResetKernelFunction::execute().
void nest::Network::reset_network ()
Reset the network to the state at T = 0.
References assert(), nest::SiblingContainer::begin(), nest::names::c, nest::Scheduler::clear_pending_spikes(), nest::SiblingContainer::end(), nest::Node::get_model_id(), nest::SparseNodeArray::get_node_by_index(), nest::Scheduler::get_simulated(), nest::Node::init_state(), local_nodes_, SLIInterpreter::M_WARNING, message(), nest::names::n, nest::Node::num_thread_siblings_(), scheduler_, nest::Node::set_buffers_initialized(), and nest::SparseNodeArray::size().
Referenced by nest::NestModule::ResetNetworkFunction::execute().
void nest::Network::restore_nodes (ArrayDatum & node_list)
Restore nodes from an array of status dictionaries.
The following entries must be present in each dictionary: /model - with the name or index of a neuron mode.
The following entries are optional: /parent - the node is created in the parent subnet
Restore nodes uses the current working node as root. Thus, all GIDs in the status dictionaties are offset by the GID of the current working node. This allows entire subnetworks to be copied.
References add_node(), TokenArray::begin(), current_, TokenArray::end(), get_cwn(), get_model_id(), get_node(), nest::names::global_id, go_to(), nest::names::model, nest::names::parent, nest::Node::set_status_base(), and size().
Referenced by nest::NestModule::RestoreNodes_aFunction::execute().
void nest::Network::resume ()
Resume the simulation after it was terminated.
References nest::Scheduler::resume(), and scheduler_.
Referenced by nest::NestModule::ResumeSimulationFunction::execute().
template<class EventT > void nest::Network::send (Node & source, EventT & e, const long_t lag = 0) inline
Standard routine for sending events.
This method decides if the event has to be delivered locally or globally. It exists to keep a clean and unitary interface for the event sending mechanism.
Note
Only specialization for SpikeEvent does remote sending. Specialized for DSSpikeEvent to avoid that these events are sent to remote processes.
See also
send_local()
References assert(), connection_manager_, nest::Node::get_gid(), get_slice_origin(), nest::Node::get_thread(), nest::Node::has_proxies(), and nest::ConnectionManager::send().
Referenced by nest::iaf_psc_exp_multisynapse::update(), nest::iaf_psc_alpha_multisynapse::update(), nest::parrot_neuron_ps::update(), nest::parrot_neuron::update(), nest::aeif_cond_alpha_multisynapse::update(), nest::iaf_psc_alpha::update(), nest::ht_neuron::update(), and nest::Multimeter::update().
template<> void nest::Network::send (Node & source, SpikeEvent & e, const long_t lag) inline
References numerics::e, and nest::names::source.
template<> void nest::Network::send (Node & source, DSSpikeEvent & e, const long_t lag) inline
References assert(), numerics::e, and nest::names::source.
void nest::Network::send_local (thread t, Node & source, Event & e) inline
Send event e to all targets of node source on thread t.
References connection_manager_, nest::Node::get_gid(), nest::ConnectionManager::send(), and nest::Event::set_sender_gid().
void nest::Network::send_to_node (Event & e) inline
Send event e directly to its target node.
This should be used only where necessary, e.g. if a node wants to reply to a *RequestEvent immediately.
References numerics::e.
void nest::Network::set_connector_defaults (index sc, DictionaryDatum & d) inline
References connection_manager_, and nest::ConnectionManager::set_prototype_status().
Referenced by nest::NestModule::SetDefaults_l_DFunction::execute(), and nest::NestModule::CopyModel_l_l_DFunction::execute().
void nest::Network::set_data_path_prefix_ (const DictionaryDatum & d) private
Helper function to set device data path and prefix.
References data_path_, data_prefix_, SLIInterpreter::M_ERROR, and message().
Referenced by init_(), and set_status().
void nest::Network::set_model_defaults_modified () inline
References model_defaults_modified_.
Referenced by nest::NestModule::SetDefaults_l_DFunction::execute().
void nest::Network::set_music_in_port_acceptable_latency (std::string portname, double_t latency)
Set the acceptable latency (latency) for a music input port (portname).
References music_in_portlist_.
Referenced by nest::NestModule::SetAcceptableLatencyFunction::execute().
void nest::Network::set_music_in_port_max_buffered (std::string portname, int_t maxbuffered)
References music_in_portlist_.
Referenced by nest::NestModule::SetMaxBufferedFunction::execute().
void nest::Network::set_num_rec_processes (int nrp) inline
Set number of recording processes.
References scheduler_, and nest::Scheduler::set_num_rec_processes().
Referenced by nest::NestModule::SetNumRecProcessesFunction_i::execute().
void nest::Network::set_status (index gid, const DictionaryDatum & d)
Set properties of a Node.
The specified node must exist.
Exceptions
nest::UnknownNode Target does not exist in the network.
nest::UnaccessedDictionaryEntry Non-proxy target did not read dict entry.
TypeMismatch Array is not a flat & homogeneous array of integers.
References assert(), nest::names::d, dict_miss_is_error_, nest::SparseNodeArray::get_node_by_gid(), nest::Node::get_thread_sibling_(), local_nodes_, nest::Node::num_thread_siblings_(), overwrite_files_, scheduler_, set_data_path_prefix_(), nest::Scheduler::set_status(), set_status_single_node_(), and nest::names::target.
Referenced by nest::NestModule::SetStatus_idFunction::execute().
void nest::Network::set_status_single_node_ (Node & target, const DictionaryDatum & d, bool clear_flags = true) private
Helper function to set properties on single node.
Parameters
node to set properties for
dictionary containing properties
if true (default), access flags are called before each call so Node::set_status_()
Exceptions
UnaccessedDictionaryEntry
References dict_miss_is_error(), nest::Node::is_proxy(), SLIInterpreter::M_WARNING, message(), and nest::Node::set_status_base().
Referenced by set_status().
void nest::Network::set_synapse_status (index gid, index syn, port p, thread tid, DictionaryDatum & d) inline
References connection_manager_, and nest::ConnectionManager::set_synapse_status().
Referenced by nest::NestModule::SetStatus_CDFunction::execute(), and nest::NestModule::SetStatus_aaFunction::execute().
void nest::Network::simulate (Time const & t)
References scheduler_, and nest::Scheduler::simulate().
Referenced by nest::NestModule::SimulateFunction::execute().
index nest::Network::size (void) const inline
Return total number of network nodes.
The size also includes all Subnet objects.
References nest::SparseNodeArray::get_max_gid(), and local_nodes_.
Referenced by get_status(), and restore_nodes().
void nest::Network::subnet_connect (Subnet & , Subnet & , int , index syn)
int nest::Network::suggest_rec_vp (index gid) const inline
Suggest a VP for a given global recording node ID.
References scheduler_, and nest::Scheduler::suggest_rec_vp().
Referenced by add_node().
int nest::Network::suggest_vp (index gid) const inline
Suggest a VP for a given global node ID.
References scheduler_, and nest::Scheduler::suggest_vp().
Referenced by add_node().
void nest::Network::terminate () inline
Terminate the simulation after the time-slice is finished.
References scheduler_, and nest::Scheduler::terminate().
Node * nest::Network::thread_lid_to_node (thread t, targetindex thread_local_id) const inline
References scheduler_, and nest::Scheduler::thread_lid_to_node().
Referenced by nest::TargetIdentifierIndex::get_target_ptr().
thread nest::Network::thread_to_vp (thread t) const inline
Convert a given thread ID to the corresponding VP ID.
References scheduler_, and nest::Scheduler::thread_to_vp().
Referenced by add_node(), and init_().
void nest::Network::trigger_update_weight (const long_t vt_gid, const vector< spikecounter > & dopa_spikes, const double_t t_trig) inline
Triggered by volume transmitter in update.
Triggeres updates for all connectors of dopamine synapses that are registered with the volume transmitter with gid vt_gid.
References connection_manager_, and nest::ConnectionManager::trigger_update_weight().
void nest::Network::try_unregister_model (index m_id)
Try unregistering model prototype.
Throws ModelInUseException, if not possible, does not unregister.
References get_model(), nest::Model::get_name(), and model_in_use().
void nest::Network::unregister_model (index m_id)
Unregister a previously registered model.
References get_model(), nest::Model::get_name(), get_num_threads(), model_in_use(), modeldict_, models_, pristine_models_, proxy_nodes_, and Dictionary::remove().
void nest::Network::unregister_music_in_port (std::string portname)
Unregister a MUSIC input port (portname) from the port list.
This will decrement the counter of the respective entry in the music_in_portlist and remove the entry if the counter is 0 after decrementing it.
References music_in_portlist_.
void nest::Network::update_music_event_handlers_ (Time const & origin, const long_t from, const long_t to)
Call update() for each of the registered MUSIC event handlers to deliver all queued events to the target music_in_proxies.
References music_in_portmap_.
thread nest::Network::vp_to_thread (thread vp) const inline
Convert a given VP ID to the corresponding thread ID.
References scheduler_, and nest::Scheduler::vp_to_thread().
Referenced by add_node().
size_t nest::Network::write_toggle () const inline
Return 0 for even, 1 for odd time slices.
This is useful for buffers that need to be written alternatingly by time slice. The value is given by Scheduler::get_slice_() % 2.
See also
read_toggle
References nest::Scheduler::get_slice(), and scheduler_.
Referenced by read_toggle().
Friends And Related Function Documentation
friend class Scheduler friend
Member Data Documentation
std::vector<GenericConnBuilderFactory*> nest::Network::connbuilder_factories_ private
Referenced by connect(), and register_conn_builder().
ConnectionManager nest::Network::connection_manager_ private
Referenced by connect(), convergent_connect(), copy_synapse_prototype(), divergent_connect(), get_connections(), get_connector_defaults(), get_status(), get_synapse_status(), Network(), register_synapse_prototype(), reset(), send(), send_local(), set_connector_defaults(), set_synapse_status(), and trigger_update_weight().
Dictionary* nest::Network::connruledict_ private
Dictionary for connection rules.
Referenced by connect(), Network(), and register_conn_builder().
Subnet* nest::Network::current_ private
Current working node (for insertion).
Referenced by add_node(), get_cwn(), go_to(), init_(), and restore_nodes().
std::string nest::Network::data_path_ private
Path for all files written by devices.
Referenced by get_data_path(), get_status(), reset_kernel(), and set_data_path_prefix_().
std::string nest::Network::data_prefix_ private
Prefix for all files written by devices.
Referenced by get_data_prefix(), get_status(), reset_kernel(), and set_data_path_prefix_().
bool nest::Network::dict_miss_is_error_ private
whether to throw exception on missed dictionary entries
Referenced by dict_miss_is_error(), get_status(), reset_kernel(), and set_status().
std::vector<Node*> nest::Network::dummy_spike_sources_ private
Placeholders for spiking remote nodes, one per thread.
Referenced by destruct_nodes_(), and init_().
SLIInterpreter& nest::Network::interpreter_ private
Referenced by execute_sli_protected(), get_exitcode(), message(), Network(), and quit_by_error().
SparseNodeArray nest::Network::local_nodes_ private
The network as sparse array of local nodes.
Referenced by add_node(), destruct_nodes_(), get_node(), get_status(), get_thread_siblings(), init_(), is_local_gid(), reset_network(), set_status(), and size().
bool nest::Network::model_defaults_modified_ private
whether any model defaults have been modified
Referenced by clear_models_(), model_defaults_modified(), and set_model_defaults_modified().
Dictionary* nest::Network::modeldict_ private
Dictionary for models.
Referenced by clear_models_(), copy_model(), get_modeldict(), init_(), Network(), register_basis_model(), register_model(), and unregister_model().
std::vector<Model *> nest::Network::models_ private
The list of available models.
Referenced by add_node(), clear_models_(), copy_model(), get_model(), get_model_id(), get_model_of_gid(), has_user_models(), init_(), memory_info(), register_model(), and unregister_model().
std::map< std::string, MusicPortData > nest::Network::music_in_portlist_
The mapping between MUSIC input ports identified by portname and the corresponding port variables and parameters.
See also
register_music_in_port()
unregister_music_in_port()
Referenced by init_(), register_music_event_in_proxy(), register_music_in_port(), set_music_in_port_acceptable_latency(), set_music_in_port_max_buffered(), and unregister_music_in_port().
std::map< std::string, MusicEventHandler > nest::Network::music_in_portmap_
The mapping between MUSIC input ports identified by portname and the corresponding MUSIC event handler.
Referenced by publish_music_in_ports_(), register_music_event_in_proxy(), and update_music_event_handlers_().
Modelrangemanager nest::Network::node_model_ids_ private
ConnBuilder factories, indexed by connruledict_ elements.
Records the model id of each neuron in the network
Referenced by add_node(), destruct_nodes_(), get_contiguous_gid_range(), get_model_id_of_gid(), get_node(), init_(), and model_in_use().
bool nest::Network::overwrite_files_ private
If true, overwrite existing data files.
Referenced by get_status(), overwrite_files(), reset_kernel(), and set_status().
std::vector< std::pair<Model *, bool> > nest::Network::pristine_models_ private
The list of clean models.
The first component of the pair is a pointer to the actual Model, the second is a flag indicating if the model is private. Private models are not entered into the modeldict.
Referenced by has_user_models(), init_(), register_basis_model(), register_model(), reset(), unregister_model(), and ~Network().
std::vector< std::vector<Node*> > nest::Network::proxy_nodes_ private
Placeholders for remote nodes, one per thread.
Referenced by copy_model(), destruct_nodes_(), get_node(), init_(), register_model(), and unregister_model().
Subnet* nest::Network::root_ private
Root node.
Referenced by add_node(), get_root(), get_status(), and init_().
Scheduler nest::Network::scheduler_ private
Referenced by add_node(), calibrate_clock(), ensure_valid_thread_local_ids(), execute_sli_protected(), get_grng(), get_max_delay(), get_min_delay(), get_num_processes(), get_num_rec_processes(), get_num_sim_processes(), get_num_threads(), get_off_grid_communication(), get_previous_slice_origin(), get_rng(), get_simulated(), get_slice_origin(), get_status(), get_time(), is_local_vp(), reset(), reset_kernel(), reset_network(), resume(), set_num_rec_processes(), set_status(), simulate(), suggest_rec_vp(), suggest_vp(), terminate(), thread_lid_to_node(), thread_to_vp(), vp_to_thread(), and write_toggle().
Model* nest::Network::siblingcontainer_model private
The model for the SiblingContainer class.
Referenced by add_node(), init_(), and Network().
Dictionary* nest::Network::synapsedict_ private
Dictionary for synapse models.
Referenced by get_synapsedict(), and Network().
The documentation for this class was generated from the following files:
network.h
network.cpp
network_impl.h