NEST: nest::LocalLeafListIterator Class Reference
nest::LocalLeafListIterator Class Reference
Iterator for traversal of only local leaf nodes in a subnet.
#include <nodelist.h>
Public Member Functions
LocalLeafListIterator operator++ ()
Node * operator* ()
Node const * operator* () const
bool operator== (const LocalLeafListIterator &i) const
bool operator!= (const LocalLeafListIterator &i) const
Private Member Functions
LocalLeafListIterator (std::vector< Node * >::iterator const &node, std::vector< Node * >::iterator const &list_end)
Create iterator from pointer to Node in subnet.
Static Private Member Functions
static bool is_leaf_ (Node *n)
Private Attributes
LocalNodeListIterator base_it_
Friends
class LocalNodeListBase< LocalLeafListIterator >
Detailed Description
Iterator for traversal of only local leaf nodes in a subnet.
Note
Leaf nodes are those children that are not subnets. Empty subnets are not considered leaves.
Constructor & Destructor Documentation
nest::LocalLeafListIterator::LocalLeafListIterator (std::vector< Node * >::iterator const & node, std::vector< Node * >::iterator const & list_end) inline private
Create iterator from pointer to Node in subnet.
References base_it_, nest::LocalNodeListIterator::is_end_(), and is_leaf_().
Member Function Documentation
static bool nest::LocalLeafListIterator::is_leaf_ (Node * n) inline static private
References nest::names::n.
Referenced by LocalLeafListIterator(), and operator++().
bool nest::LocalLeafListIterator::operator!= (const LocalLeafListIterator & i) const inline
Node* nest::LocalLeafListIterator::operator* () inline
References base_it_.
Node const* nest::LocalLeafListIterator::operator* () const inline
References base_it_.
LocalLeafListIterator nest::LocalLeafListIterator::operator++ ()
References base_it_, nest::LocalNodeListIterator::is_end_(), and is_leaf_().
bool nest::LocalLeafListIterator::operator== (const LocalLeafListIterator & i) const inline
References base_it_.
Friends And Related Function Documentation
friend class LocalNodeListBase< LocalLeafListIterator > friend
Member Data Documentation
LocalNodeListIterator nest::LocalLeafListIterator::base_it_ private
Referenced by LocalLeafListIterator(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following files:
nodelist.h
nodelist.cpp