NEST: TypeTrie::TypeNode Class Reference
TypeTrie::TypeNode Class Reference
Public Member Functions
void addreference (void)
void removereference (void)
TypeNode (const Name &n)
TypeNode (const Name &n, Token f)
~TypeNode ()
void toTokenArray (TokenArray &) const
void info (std::ostream &, std::vector< TypeNode const * > &) const
Public Attributes
Name type
Token func
TypeNode * alt
TypeNode * next
Private Attributes
unsigned int refs
Constructor & Destructor Documentation
TypeTrie::TypeNode::TypeNode (const Name & n) inline
TypeTrie::TypeNode::TypeNode (const Name & n, Token f) inline
TypeTrie::TypeNode::~TypeNode () inline
References alt, next, and removereference().
Member Function Documentation
void TypeTrie::TypeNode::addreference (void) inline
References refs.
Referenced by TypeTrie::TypeTrie().
void TypeTrie::TypeNode::info (std::ostream & out, std::vector< TypeNode const * > & tl) const
References assert().
Referenced by TypeTrie::info().
void TypeTrie::TypeNode::removereference (void) inline
References refs.
Referenced by ~TypeNode(), and TypeTrie::~TypeTrie().
void TypeTrie::TypeNode::toTokenArray (TokenArray & a) const
References alt, assert(), func, next, TokenArray::push_back(), TokenArray::size(), toTokenArray(), and type.
Referenced by toTokenArray(), and TypeTrie::toTokenArray().
Member Data Documentation
TypeNode* TypeTrie::TypeNode::alt
Referenced by TypeTrie::getalternative(), TypeTrie::lookup(), toTokenArray(), and ~TypeNode().
Token TypeTrie::TypeNode::func
Referenced by TypeTrie::getalternative(), TypeTrie::insert_move(), TypeTrie::lookup(), and toTokenArray().
TypeNode* TypeTrie::TypeNode::next
Referenced by TypeTrie::getalternative(), TypeTrie::insert_move(), TypeTrie::lookup(), toTokenArray(), and ~TypeNode().
unsigned int TypeTrie::TypeNode::refs private
Referenced by addreference(), and removereference().
Name TypeTrie::TypeNode::type
Referenced by TypeTrie::getalternative(), TypeTrie::insert_move(), TypeTrie::lookup(), and toTokenArray().
The documentation for this class was generated from the following files:
typechk.h
typechk.cc