NEST: librandom::MT19937 Class Reference
librandom::MT19937 Class Reference
Mersenne Twister MT19937.
#include <mt19937.h>
Public Member Functions
MT19937 (unsigned long)
Create generator with given seed.
~MT19937 ()
RngPtr clone (unsigned long s)
clone a random number generator of same type initialized with given seed
Public Member Functions inherited from librandom::RandomGen
RandomGen ()
virtual ~RandomGen ()
double drand (void)
The following functions implement the user interface of the RandomGen class, including buffer management.
double operator() (void)
draw from [0, 1)
double drandpos (void)
draw from (0, 1)
unsigned long ulrand (const unsigned long)
draw from [0, n-1]
void seed (const unsigned long)
set random seed to a new value
size_t get_buffsize (void) const
returns buffer size
void set_buffsize (const size_t)
set buffer size
Private Member Functions
void seed_ (unsigned long)
implements seeding for RandomGen
double drand_ ()
implements drawing a single [0,1) number for RandomGen
void init_genrand (unsigned long)
unsigned long genrand_int32 ()
double genrand_real2 ()
Private Attributes
std::vector< unsigned long > mt
int mti
Static Private Attributes
static const unsigned int N = 624
static const unsigned int M = 397
static const unsigned long MATRIX_A = 0x9908b0dfUL
static const unsigned long UPPER_MASK = 0x80000000UL
static const unsigned long LOWER_MASK = 0x7fffffffUL
static const double I2DFactor_ = 1.0/4294967296.0
int to double factor
Additional Inherited Members
Static Public Member Functions inherited from librandom::RandomGen
static RngPtr create_knuthlfg_rng (unsigned long)
Create built-in Knuth Lagged Fibonacci random generator.
Static Public Attributes inherited from librandom::RandomGen
static const unsigned long DefaultSeed = 0xd37ca59fUL
Default value for seeding generators in places where no seed is supplied.
Detailed Description
Mersenne Twister MT19937.
This class implements the 32-bit MT19937 Mersenne Twister RNG by Matsumoto and Nishimura. The implementation wraps a C++ class around the originial code.
Constructor & Destructor Documentation
librandom::MT19937::MT19937 (unsigned long s) explicit
Create generator with given seed.
References init_genrand().
Referenced by clone().
librandom::MT19937::~MT19937 () inline
Member Function Documentation
RngPtr librandom::MT19937::clone (unsigned long long) inline virtual
clone a random number generator of same type initialized with given seed
Implements librandom::RandomGen.
References MT19937().
double librandom::MT19937::drand_ (void) inline private virtual
implements drawing a single [0,1) number for RandomGen
Implements librandom::RandomGen.
References genrand_real2().
unsigned long librandom::MT19937::genrand_int32 () private
References nest::names::N, and nest::names::y.
double librandom::MT19937::genrand_real2 () inline private
Referenced by drand_().
void librandom::MT19937::init_genrand (unsigned long s) private
References nest::names::N.
Referenced by MT19937().
void librandom::MT19937::seed_ (unsigned long s) private virtual
implements seeding for RandomGen
Implements librandom::RandomGen.
Member Data Documentation
const double librandom::MT19937::I2DFactor_ = 1.0/4294967296.0 static private
int to double factor
const unsigned long librandom::MT19937::LOWER_MASK = 0x7fffffffUL static private
const unsigned int librandom::MT19937::M = 397 static private
const unsigned long librandom::MT19937::MATRIX_A = 0x9908b0dfUL static private
std::vector<unsigned long> librandom::MT19937::mt private
int librandom::MT19937::mti private
const unsigned int librandom::MT19937::N = 624 static private
const unsigned long librandom::MT19937::UPPER_MASK = 0x80000000UL static private
The documentation for this class was generated from the following files:
mt19937.h
mt19937.cpp