NEST: nest::noise_generator Class Reference
nest::noise_generator Class Reference
Gaussian white noise generator.
#include <noise_generator.h>
Classes
struct Buffers_
struct Parameters_
Store independent parameters of the model.
struct State_
struct Variables_
Public Member Functions
noise_generator ()
noise_generator (const noise_generator &)
bool has_proxies () const
Returns true if the node has proxies on remote threads.
port send_test_event (Node &, rport, synindex, bool)
Send an event to the receiving_node passed as an argument.
void get_status (DictionaryDatum &) const
void set_status (const DictionaryDatum &)
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool local_receiver () const
Returns true if the node only receives events from nodes/devices on the same thread.
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
virtual std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void finalize ()
Finalize node.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port handles_test_event (SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (DataLoggingRequest &, rport receptor_type)
virtual port handles_test_event (CurrentEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void register_stdp_connection (double_t)
Register a STDP connection.
virtual void unregister_stdp_connection (double_t)
Unregister a STDP connection.
virtual void handle (SpikeEvent &e)
Handle incoming spike events.
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingRequest &e)
Handler for universal data logging request.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (CurrentEvent &e)
Handler for current events.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
virtual void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
virtual void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike history for (t1,t2].
virtual void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
virtual bool is_subnet () const
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Private Types
typedef std::vector< double_t > AmpVec_
Private Member Functions
void init_state_ (const Node &)
Private function to initialize the state of a node to model defaults.
void init_buffers_ ()
Private function to initialize the buffers of a node.
void calibrate ()
Recalculates parameters and forces reinitialization of amplitudes if number of targets has changed.
void update (Time const &, const long_t, const long_t)
Bring the node from state $t$ to $t+n*dt$.
void event_hook (DSCurrentEvent &)
Private Attributes
StimulatingDevice< CurrentEvent > device_
Parameters_ P_
Variables_ V_
Buffers_ B_
State_ S_
Additional Inherited Members
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Detailed Description
Gaussian white noise generator.
Provide Gaussian "white" noise input current
Member Typedef Documentation
typedef std::vector<double_t> nest::noise_generator::AmpVec_ private
Constructor & Destructor Documentation
nest::noise_generator::noise_generator ()
References nest::names::dt, nest::noise_generator::Parameters_::dt_, nest::Node::get_name(), nest::Time::is_step(), and P_.
nest::noise_generator::noise_generator (const noise_generator & n)
References nest::names::dt, nest::noise_generator::Parameters_::dt_, nest::Node::get_name(), nest::Time::is_step(), and P_.
Member Function Documentation
void nest::noise_generator::calibrate () private virtual
Recalculates parameters and forces reinitialization of amplitudes if number of targets has changed.
Implements nest::Node.
References nest::Time::get_ms(), nest::Time::get_resolution(), nest::names::h, SLIInterpreter::M_INFO, nest::names::omega, and numerics::pi.
void nest::noise_generator::event_hook (DSCurrentEvent & e) private virtual
Reimplemented from nest::Node.
References assert(), nest::Event::get_port(), nest::Event::get_receiver(), nest::Node::handle(), and nest::CurrentEvent::set_current().
void nest::noise_generator::get_status (DictionaryDatum & d) const inline
References device_, nest::noise_generator::Parameters_::get(), nest::noise_generator::State_::get(), P_, and S_.
bool nest::noise_generator::has_proxies () const inline virtual
Returns true if the node has proxies on remote threads.
This is used to discriminate between different types of nodes, when adding new nodes to the network.
Reimplemented from nest::Node.
void nest::noise_generator::init_buffers_ () private virtual
Private function to initialize the buffers of a node.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the buffers of a node.
See also
Node::init_buffers()
Implements nest::Node.
void nest::noise_generator::init_state_ (const Node &) private virtual
Private function to initialize the state of a node to model defaults.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the state of a node to the model defaults; the state is the set of observable dynamic variables.
Parameters
Reference to model prototype object.
See also
Node::init_state()
Note
To provide a reasonable behavior during the transition to the new scheme, init_state_() has a default implementation calling init_dynamic_state_().
Implements nest::Node.
References device_, and nest::Node::init_state().
nest::port nest::noise_generator::send_test_event (Node & receiving_node, rport receptor_type, synindex syn_id, bool dummy_target) virtual
Send an event to the receiving_node passed as an argument.
Default implementation of check_connection just throws UnexpectedEvent.
This is required during the connection handshaking to test, if the receiving_node can handle the event type and receptor_type sent by the source node.
If dummy_target is true, this indicates that receiving_node is derived from ConnTestDummyNodeBase and used in the first call to send_test_event(). This can be ignored in most cases, but Nodes sending DS*Events to their own event hooks and then *Events to their proper targets must send DS*Events when called with the dummy target, and *Events when called with the real target, see #478.
Reimplemented from nest::Node.
References numerics::e, nest::Node::handles_test_event(), nest::invalid_port_, nest::names::p, and nest::Event::set_sender().
void nest::noise_generator::set_status (const DictionaryDatum & d) inline
References device_, nest::noise_generator::Parameters_::num_targets_, P_, and nest::noise_generator::Parameters_::set().
void nest::noise_generator::update (Time const & , const long_t , const long_t) private virtual
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to.
Parameters
Time network time at beginning of time slice.
long_t initial step inside time slice
long_t post-final step inside time slice
Implements nest::Node.
References nest::Time::get_steps(), and nest::names::start.
Member Data Documentation
Buffers_ nest::noise_generator::B_ private
StimulatingDevice<CurrentEvent> nest::noise_generator::device_ private
Referenced by get_status(), init_state_(), and set_status().
Parameters_ nest::noise_generator::P_ private
Referenced by get_status(), noise_generator(), and set_status().
State_ nest::noise_generator::S_ private
Referenced by get_status().
Variables_ nest::noise_generator::V_ private
The documentation for this class was generated from the following files:
noise_generator.h
noise_generator.cpp