NEST: SLIModule Class Reference
SLIModule Class Reference abstract
Base class for all SLI Interpreter modules.
#include <slimodule.h>
Public Member Functions
virtual ~SLIModule ()
virtual void init (SLIInterpreter *)=0
Initialise the module.
virtual const std::string name (void) const =0
Return name of the module.
virtual const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Detailed Description
Base class for all SLI Interpreter modules.
Constructor & Destructor Documentation
virtual SLIModule::~SLIModule () inline virtual
Member Function Documentation
const std::string SLIModule::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Reimplemented in SLIArrayModule, Processes, RegexpModule, FilesystemModule, SLIgraphics, nest::NestModule, nest::DynamicLoaderModule, RandomNumbers, nest::ConnectionGeneratorModule, nest::TopologyModule, nest::ModelsModule, nest::PreciseModule, and OOSupportModule.
Referenced by SLIInterpreter::addmodule().
virtual void SLIModule::init (SLIInterpreter *) pure virtual
Initialise the module.
When this function is called, most of the interpreter's fascilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialised, not all services may be available.
Implemented in SLIArrayModule, Processes, SLIStartup, RegexpModule, FilesystemModule, RandomNumbers, SLIgraphics, nest::NestModule, nest::DynamicLoaderModule, SpecialFunctionsModule, nest::ConnectionGeneratorModule, nest::TopologyModule, nest::ModelsModule, nest::PreciseModule, GNUReadline, and OOSupportModule.
Referenced by install().
void SLIModule::install (std::ostream & , SLIInterpreter * i)
Print installation message via interpreter message command.
References init(), SLIInterpreter::message(), and name().
Referenced by SLIInterpreter::addmodule().
virtual const std::string SLIModule::name (void) const pure virtual
Return name of the module.
Implemented in SLIArrayModule, Processes, SLIStartup, RegexpModule, FilesystemModule, nest::NestModule, SLIgraphics, nest::DynamicLoaderModule, SpecialFunctionsModule, nest::ConnectionGeneratorModule, RandomNumbers, nest::TopologyModule, nest::ModelsModule, nest::PreciseModule, OOSupportModule, and GNUReadline.
Referenced by SLIInterpreter::addmodule(), and install().
The documentation for this class was generated from the following files:
slimodule.h
slimodule.cc