NEST: const_table_iterator< tabletype > Class Template Reference
const_table_iterator< tabletype > Class Template Reference
#include <sparsetable.h>
Public Types
typedef table_iterator< tabletype > iterator
typedef const_table_iterator const_iterator
typedef
std::random_access_iterator_tag iterator_category
typedef tabletype::value_type value_type
typedef tabletype::difference_type difference_type
typedef tabletype::size_type size_type
typedef tabletype::const_reference reference
typedef tabletype::const_pointer pointer
Public Member Functions
const_table_iterator (const tabletype *tbl, size_type p)
const_table_iterator ()
const_table_iterator (const iterator &from)
reference operator* () const
pointer operator-> () const
void check () const
const_iterator & operator+= (size_type t)
const_iterator & operator-= (size_type t)
const_iterator & operator++ ()
const_iterator & operator-- ()
const_iterator operator++ (int)
const_iterator operator-- (int)
const_iterator operator+ (difference_type i) const
const_iterator operator- (difference_type i) const
difference_type operator- (const_iterator it) const
reference operator[] (difference_type n) const
bool operator== (const const_iterator &it) const
bool operator< (const const_iterator &it) const
bool operator!= (const const_iterator &it) const
bool operator<= (const const_iterator &it) const
bool operator> (const const_iterator &it) const
bool operator>= (const const_iterator &it) const
Public Attributes
const tabletype * table
size_type pos
Member Typedef Documentation
template<class tabletype> typedef const_table_iterator const_table_iterator< tabletype >::const_iterator
template<class tabletype> typedef tabletype::difference_type const_table_iterator< tabletype >::difference_type
template<class tabletype> typedef table_iterator<tabletype> const_table_iterator< tabletype >::iterator
template<class tabletype> typedef std::random_access_iterator_tag const_table_iterator< tabletype >::iterator_category
template<class tabletype> typedef tabletype::const_pointer const_table_iterator< tabletype >::pointer
template<class tabletype> typedef tabletype::const_reference const_table_iterator< tabletype >::reference
template<class tabletype> typedef tabletype::size_type const_table_iterator< tabletype >::size_type
template<class tabletype> typedef tabletype::value_type const_table_iterator< tabletype >::value_type
Constructor & Destructor Documentation
template<class tabletype> const_table_iterator< tabletype >::const_table_iterator (const tabletype * tbl, size_type p) inline
template<class tabletype> const_table_iterator< tabletype >::const_table_iterator () inline
template<class tabletype> const_table_iterator< tabletype >::const_table_iterator (const iterator & from) inline
Member Function Documentation
template<class tabletype> void const_table_iterator< tabletype >::check () const inline
References assert(), and const_table_iterator< tabletype >::table.
Referenced by const_table_iterator< tabletype >::operator++(), const_table_iterator< tabletype >::operator+=(), const_table_iterator< tabletype >::operator--(), and const_table_iterator< tabletype >::operator-=().
template<class tabletype> bool const_table_iterator< tabletype >::operator!= (const const_iterator & it) const inline
template<class tabletype> reference const_table_iterator< tabletype >::operator* () const inline
References const_table_iterator< tabletype >::pos, and const_table_iterator< tabletype >::table.
Referenced by const_table_iterator< tabletype >::operator->().
template<class tabletype> const_iterator const_table_iterator< tabletype >::operator+ (difference_type i) const inline
template<class tabletype> const_iterator& const_table_iterator< tabletype >::operator++ () inline
References const_table_iterator< tabletype >::check(), and const_table_iterator< tabletype >::pos.
template<class tabletype> const_iterator const_table_iterator< tabletype >::operator++ (int) inline
References const_table_iterator< tabletype >::check(), and const_table_iterator< tabletype >::pos.
template<class tabletype> const_iterator& const_table_iterator< tabletype >::operator+= (size_type t) inline
References const_table_iterator< tabletype >::check(), and const_table_iterator< tabletype >::pos.
template<class tabletype> const_iterator const_table_iterator< tabletype >::operator- (difference_type i) const inline
template<class tabletype> difference_type const_table_iterator< tabletype >::operator- (const_iterator it) const inline
References assert(), const_table_iterator< tabletype >::pos, and const_table_iterator< tabletype >::table.
template<class tabletype> const_iterator& const_table_iterator< tabletype >::operator-- () inline
References const_table_iterator< tabletype >::check(), and const_table_iterator< tabletype >::pos.
template<class tabletype> const_iterator const_table_iterator< tabletype >::operator-- (int) inline
References const_table_iterator< tabletype >::check(), and const_table_iterator< tabletype >::pos.
template<class tabletype> const_iterator& const_table_iterator< tabletype >::operator-= (size_type t) inline
References const_table_iterator< tabletype >::check(), and const_table_iterator< tabletype >::pos.
template<class tabletype> pointer const_table_iterator< tabletype >::operator-> () const inline
References const_table_iterator< tabletype >::operator*().
template<class tabletype> bool const_table_iterator< tabletype >::operator< (const const_iterator & it) const inline
References assert(), const_table_iterator< tabletype >::pos, and const_table_iterator< tabletype >::table.
template<class tabletype> bool const_table_iterator< tabletype >::operator<= (const const_iterator & it) const inline
template<class tabletype> bool const_table_iterator< tabletype >::operator== (const const_iterator & it) const inline
References const_table_iterator< tabletype >::pos, and const_table_iterator< tabletype >::table.
template<class tabletype> bool const_table_iterator< tabletype >::operator> (const const_iterator & it) const inline
template<class tabletype> bool const_table_iterator< tabletype >::operator>= (const const_iterator & it) const inline
template<class tabletype> reference const_table_iterator< tabletype >::operator[] (difference_type n) const inline
References nest::names::n.
Member Data Documentation
template<class tabletype> size_type const_table_iterator< tabletype >::pos
Referenced by const_table_iterator< tabletype >::operator*(), const_table_iterator< tabletype >::operator++(), const_table_iterator< tabletype >::operator+=(), const_table_iterator< tabletype >::operator-(), const_table_iterator< tabletype >::operator--(), const_table_iterator< tabletype >::operator-=(), const_table_iterator< tabletype >::operator<(), const_table_iterator< tabletype >::operator==(), and sparsetable< T, GROUP_SIZE, Alloc >::test().
template<class tabletype> const tabletype* const_table_iterator< tabletype >::table
Referenced by const_table_iterator< tabletype >::check(), const_table_iterator< tabletype >::operator*(), const_table_iterator< tabletype >::operator-(), const_table_iterator< tabletype >::operator<(), and const_table_iterator< tabletype >::operator==().
The documentation for this class was generated from the following file:
sparsetable.h