NEST: nest::Communicator::OffGridSpike Class Reference
nest::Communicator::OffGridSpike Class Reference
Combined storage of GID and offset information for off-grid spikes.
#include <communicator.h>
Public Types
typedef uint_t gid_external_type
We defined this type explicitly, so that the assert function below always tests the correct type.
Public Member Functions
OffGridSpike ()
OffGridSpike (gid_external_type gidv, double_t offsetv)
uint_t get_gid () const
void set_gid (gid_external_type gid)
double_t get_offset () const
OffGridSpike ()
OffGridSpike (uint_t gidv, double_t offsetv)
uint_t get_gid () const
void set_gid (uint_t gid)
double_t get_offset () const
Static Private Member Functions
static void assert_datatype_compatibility ()
This function asserts that doubles can hold GIDs without loss.
Private Attributes
double_t gid_
GID of neuron that spiked.
double_t offset_
offset of spike from grid
Friends
class Communicator
Detailed Description
Combined storage of GID and offset information for off-grid spikes.
Note
This class actually stores the GID as double_t internally. This is done so that the user-defined MPI type MPI_OFFGRID_SPIKE, which we use to communicate off-grid spikes, is homogeneous. Otherwise, OpenMPI spends extreme amounts of time on packing and unpacking the data, see #458.
Member Typedef Documentation
typedef uint_t nest::Communicator::OffGridSpike::gid_external_type
We defined this type explicitly, so that the assert function below always tests the correct type.
Constructor & Destructor Documentation
nest::Communicator::OffGridSpike::OffGridSpike () inline
nest::Communicator::OffGridSpike::OffGridSpike (gid_external_type gidv, double_t offsetv) inline
nest::Communicator::OffGridSpike::OffGridSpike () inline
nest::Communicator::OffGridSpike::OffGridSpike (uint_t gidv, double_t offsetv) inline
Member Function Documentation
static void nest::Communicator::OffGridSpike::assert_datatype_compatibility () inline static private
This function asserts that doubles can hold GIDs without loss.
References assert(), get_gid(), and nest::names::max.
Referenced by nest::Communicator::init().
uint_t nest::Communicator::OffGridSpike::get_gid () const inline
References gid_.
Referenced by assert_datatype_compatibility().
uint_t nest::Communicator::OffGridSpike::get_gid () const inline
References gid_.
double_t nest::Communicator::OffGridSpike::get_offset () const inline
References offset_.
double_t nest::Communicator::OffGridSpike::get_offset () const inline
References offset_.
void nest::Communicator::OffGridSpike::set_gid (gid_external_type gid) inline
References gid_.
void nest::Communicator::OffGridSpike::set_gid (uint_t gid) inline
References gid_.
Friends And Related Function Documentation
Communicator friend
Member Data Documentation
double_t nest::Communicator::OffGridSpike::gid_ private
GID of neuron that spiked.
Referenced by get_gid(), nest::Communicator::init(), and set_gid().
double_t nest::Communicator::OffGridSpike::offset_ private
offset of spike from grid
Referenced by get_offset(), and nest::Communicator::init().
The documentation for this class was generated from the following file:
communicator.h