NEST: nest::AbstractLayer Class Reference
nest::AbstractLayer Class Reference abstract
Abstract base class for Layers of unspecified dimension.
#include <layer.h>
Public Member Functions
AbstractLayer ()
Constructor.
virtual ~AbstractLayer ()
Virtual destructor.
virtual std::vector< double_t > get_position_vector (const index sind) const =0
Get position of node.
virtual std::vector< double_t > compute_displacement (const std::vector< double_t > &from_pos, const index to) const =0
Returns displacement of node from given position.
virtual double_t compute_distance (const std::vector< double_t > &from_pos, const index to) const =0
Returns distance to node from given position.
virtual void connect (AbstractLayer &target, ConnectionCreator &connector)=0
Connect this layer to the given target layer.
virtual std::vector< index > get_global_nodes (const MaskDatum &mask, const std::vector< double_t > &anchor, bool allow_oversized)=0
Return a vector with the GIDs of the nodes inside the mask.
virtual void dump_nodes (std::ostream &os) const =0
Write layer data to stream.
virtual void dump_connections (std::ostream &out, const Token &syn_model)=0
Dumps information about all connections of the given type having their source in the given layer to the given output stream.
std::vector< Node * >::iterator local_begin (int_t depth)
Start of local children at given depth.
std::vector< Node * >::iterator local_end (int_t depth)
End of local children at given depth.
std::vector< Node * >
::const_iterator local_begin (int_t depth) const
Start of local children at given depth.
std::vector< Node * >
::const_iterator local_end (int_t depth) const
End of local children at given depth.
Public Member Functions inherited from nest::Subnet
Subnet ()
Subnet (const Subnet &)
virtual ~Subnet ()
void set_status (const DictionaryDatum &)
void get_status (DictionaryDatum &) const
bool has_proxies () const
Returns true if the node has proxies on remote threads.
size_t global_size () const
Returns total number of children.
size_t local_size () const
Returns number of childern in local process.
bool global_empty () const
returns true if subnet is empty globally
bool local_empty () const
returns true if subnet has no local nodes
void reserve (size_t)
index add_node (Node *)
Add a local node to the subnet.
index add_remote_node (index gid, index mid)
Add a remote node to the subnet.
vector< Node * >::iterator local_begin ()
Return iterator to the first local child node.
vector< Node * >::iterator local_end ()
Return iterator to the end of the local child-list.
vector< Node * >::const_iterator local_begin () const
Return const iterator to the first local child node.
vector< Node * >::const_iterator local_end () const
Return const iterator to the end of the local child-list.
Node * at_lid (index) const
Return pointer to Node at given LID if it is local.
std::string get_label () const
Return the subnets's user label.
void set_label (std::string const)
Set the subnet's user label.
DictionaryDatum get_customdict () const
Set the subnet's custom dictionary.
void set_customdict (DictionaryDatum const dict)
Return pointer to the subnet's custom dictionary.
std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_subnet () const
bool is_homogeneous () const
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool local_receiver () const
Returns true if the node only receives events from nodes/devices on the same thread.
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void finalize ()
Finalize node.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port send_test_event (Node &receiving_node, rport receptor_type, synindex syn_id, bool dummy_target)
Send an event to the receiving_node passed as an argument.
virtual port handles_test_event (SpikeEvent &, rport receptor_type)
Check if the node can handle a particular event and receptor type.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (DataLoggingRequest &, rport receptor_type)
virtual port handles_test_event (CurrentEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void register_stdp_connection (double_t)
Register a STDP connection.
virtual void unregister_stdp_connection (double_t)
Unregister a STDP connection.
virtual void handle (SpikeEvent &e)
Handle incoming spike events.
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingRequest &e)
Handler for universal data logging request.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (CurrentEvent &e)
Handler for current events.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
virtual void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
virtual void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike history for (t1,t2].
virtual void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
virtual void event_hook (DSCurrentEvent &)
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Static Public Member Functions
static index create_layer (const DictionaryDatum &)
Factory function for layers.
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Protected Member Functions
virtual void clear_ntree_cache_ () const =0
Clear the cache for global position information.
virtual void clear_vector_cache_ () const =0
Clear the cache for global position information.
Protected Member Functions inherited from nest::Subnet
void init_node_ (const Node &)
void init_state_ (const Node &)
Private function to initialize the state of a node to model defaults.
void init_buffers_ ()
Private function to initialize the buffers of a node.
void calibrate ()
Re-calculate dependent parameters of the node.
void update (Time const &, const long_t, const long_t)
Bring the node from state $t$ to $t+n*dt$.
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Protected Attributes
int_t depth_
number of neurons at each position
Protected Attributes inherited from nest::Subnet
vector< Node * > nodes_
Pointer to child nodes.
Multirange gids_
GIDs of global child nodes.
Static Protected Attributes
static index cached_ntree_layer_ = -1
GID for the single layer for which we cache global position information.
static index cached_vector_layer_ = -1
GID for the single layer for which we cache global position information.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Detailed Description
Abstract base class for Layers of unspecified dimension.
Constructor & Destructor Documentation
nest::AbstractLayer::AbstractLayer () inline
Constructor.
nest::AbstractLayer::~AbstractLayer () virtual
Virtual destructor.
Member Function Documentation
virtual void nest::AbstractLayer::clear_ntree_cache_ () const protected pure virtual
Clear the cache for global position information.
Implemented in nest::Layer< D >.
virtual void nest::AbstractLayer::clear_vector_cache_ () const protected pure virtual
Clear the cache for global position information.
Implemented in nest::Layer< D >.
virtual std::vector<double_t> nest::AbstractLayer::compute_displacement (const std::vector< double_t > & from_pos, const index to) const pure virtual
Returns displacement of node from given position.
When using periodic boundary conditions, will return minimum displacement.
Parameters
from_pos position vector in layer
to node in layer to which displacement is to be computed
Returns
vector pointing from from_pos to node to's position
Implemented in nest::Layer< D >.
Referenced by nest::TopologyModule::Displacement_a_iFunction::execute().
virtual double_t nest::AbstractLayer::compute_distance (const std::vector< double_t > & from_pos, const index to) const pure virtual
Returns distance to node from given position.
When using periodic boundary conditions, will return minimum distance.
Parameters
from_pos position vector in layer
to node in layer to which displacement is to be computed
Returns
length of vector pointing from from_pos to node to's position
Implemented in nest::Layer< D >.
Referenced by nest::TopologyModule::Distance_a_iFunction::execute().
virtual void nest::AbstractLayer::connect (AbstractLayer & target, ConnectionCreator & connector) pure virtual
Connect this layer to the given target layer.
The actual connections are made in class ConnectionCreator.
Parameters
target target layer to connect to. Must have same dimension as this layer.
connector connection properties
Implemented in nest::Layer< D >.
index nest::AbstractLayer::create_layer (const DictionaryDatum & layer_dict) static
Factory function for layers.
The supplied dictionary contains parameters which specify the layer type and type-specific parameters.
Returns
pointer to new layer
References ad, nest::Network::add_node(), assert(), TokenArray::begin(), nest::names::columns, Token::datum(), depth_, nest::names::elements, Token::empty(), TokenArray::end(), nest::Network::get_cwn(), nest::Node::get_gid(), nest::Network::get_modeldict(), nest::Network::get_node(), nest::Network::go_to(), nest::names::layer, nest::names::layers, Dictionary::lookup(), nest::names::n, nest::Node::net_, nest::names::positions, nest::names::rows, nest::Subnet::set_status(), and TokenArray::size().
Referenced by nest::TopologyModule::CreateLayer_DFunction::execute().
virtual void nest::AbstractLayer::dump_connections (std::ostream & out, const Token & syn_model) pure virtual
Dumps information about all connections of the given type having their source in the given layer to the given output stream.
For distributed simulations this function will dump the connections with local targets only.
Parameters
out output stream
synapse_id type of connection
Implemented in nest::Layer< D >.
Referenced by nest::TopologyModule::DumpLayerConnections_os_i_lFunction::execute().
virtual void nest::AbstractLayer::dump_nodes (std::ostream & os) const pure virtual
Write layer data to stream.
For each node in layer, write one line to stream containing: GID x-position y-position [z-position]
Parameters
os output stream
Implemented in nest::Layer< D >.
Referenced by nest::TopologyModule::DumpLayerNodes_os_iFunction::execute().
virtual std::vector<index> nest::AbstractLayer::get_global_nodes (const MaskDatum & mask, const std::vector< double_t > & anchor, bool allow_oversized) pure virtual
Return a vector with the GIDs of the nodes inside the mask.
Parameters
mask mask to apply.
anchor position to center mask in.
allow_oversized allow mask to be greater than layer
Returns
nodes in layer inside mask.
Implemented in nest::Layer< D >.
Referenced by nest::TopologyModule::GetGlobalChildren_i_M_aFunction::execute().
virtual std::vector<double_t> nest::AbstractLayer::get_position_vector (const index sind) const pure virtual
Get position of node.
Only possible for local nodes.
Parameters
sind subnet index of node
Returns
position of node as std::vector
Implemented in nest::Layer< D >.
Referenced by nest::TopologyModule::GetPosition_iFunction::execute().
std::vector< Node * >::iterator nest::AbstractLayer::local_begin (int_t depth)
Start of local children at given depth.
Parameters
depth layer depth
Returns
iterator for local nodes pointing to first node at given depth
References depth_, nest::Subnet::gids_, nest::Subnet::global_size(), nest::Subnet::local_begin(), nest::Subnet::local_end(), and nest::Subnet::local_size().
Referenced by nest::ConnectionCreator::convergent_connect_(), nest::ConnectionCreator::source_driven_connect_(), and nest::ConnectionCreator::target_driven_connect_().
std::vector< Node * >::const_iterator nest::AbstractLayer::local_begin (int_t depth) const
Start of local children at given depth.
Parameters
depth layer depth
Returns
iterator for local nodes pointing to first node at given depth
References depth_, nest::Subnet::gids_, nest::Subnet::global_size(), nest::Subnet::local_begin(), nest::Subnet::local_end(), and nest::Subnet::local_size().
std::vector< Node * >::iterator nest::AbstractLayer::local_end (int_t depth)
End of local children at given depth.
Parameters
depth layer depth
Returns
iterator for local nodes pointing to the end of the given depth
References depth_, nest::Subnet::gids_, nest::Subnet::global_size(), nest::Subnet::local_begin(), nest::Subnet::local_end(), and nest::Subnet::local_size().
Referenced by nest::ConnectionCreator::convergent_connect_(), nest::ConnectionCreator::source_driven_connect_(), and nest::ConnectionCreator::target_driven_connect_().
std::vector< Node * >::const_iterator nest::AbstractLayer::local_end (int_t depth) const
End of local children at given depth.
Parameters
depth layer depth
Returns
iterator for local nodes pointing to the end of the given depth
References depth_, nest::Subnet::gids_, nest::Subnet::global_size(), nest::Subnet::local_begin(), nest::Subnet::local_end(), and nest::Subnet::local_size().
Member Data Documentation
index nest::AbstractLayer::cached_ntree_layer_ = -1 static protected
GID for the single layer for which we cache global position information.
index nest::AbstractLayer::cached_vector_layer_ = -1 static protected
GID for the single layer for which we cache global position information.
int_t nest::AbstractLayer::depth_ protected
number of neurons at each position
Referenced by create_layer(), local_begin(), local_end(), nest::GridLayer< D >::masked_iterator::masked_iterator(), nest::GridLayer< D >::masked_iterator::operator*(), and nest::GridLayer< D >::masked_iterator::operator++().
The documentation for this class was generated from the following files:
layer.h
layer.cpp