NEST: nest::Communicator Class Reference
nest::Communicator Class Reference
#include <communicator.h>
Classes
class NodeAddressingData
class OffGridSpike
Combined storage of GID and offset information for off-grid spikes.
Public Member Functions
Communicator ()
~Communicator ()
Communicator ()
~Communicator ()
Static Public Member Functions
static void enter_runtime (double_t h_min_delay)
Enter the runtime mode.
static MUSIC::Setup * get_music_setup ()
static MUSIC::Runtime * get_music_runtime ()
static void advance_music_time (long_t num_steps)
Advance the time of music by num_steps simulation steps.
static void register_music_event_in_proxy (std::string portname, int channel, nest::Node *mp)
Register a music_event_in_proxy for a given port and a given channel.
static void init (int *argc, char **argv[])
Set up MPI and establish number of processes and rank.
static void finalize ()
Finish off MPI routines.
static void mpi_abort (int exitcode)
static void communicate (std::vector< uint_t > &send_buffer, std::vector< uint_t > &recv_buffer, std::vector< int > &displacements)
communicate (on-grid) if compiled without MPI
static void communicate (std::vector< OffGridSpike > &send_buffer, std::vector< OffGridSpike > &recv_buffer, std::vector< int > &displacements)
communicate (off-grid) if compiled without MPI
static void communicate (std::vector< double_t > &send_buffer, std::vector< double_t > &recv_buffer, std::vector< int > &displacements)
static void communicate (double_t, std::vector< double_t > &)
static void communicate (std::vector< int_t > &)
communicate function for sending set-up information
static void communicate (std::vector< long_t > &)
template<typename NodeListType >
static void communicate (const NodeListType &local_nodes, std::vector< NodeAddressingData > &all_nodes, bool remote=false)
Collect GIDs for all nodes in a given node list across processes.
template<typename NodeListType >
static void communicate (const NodeListType &local_nodes, std::vector< NodeAddressingData > &all_nodes, Network &net, DictionaryDatum params, bool remote=false)
static void communicate_connector_properties (DictionaryDatum &dict)
static void synchronize ()
Ensure all processes have reached the same stage by waiting until all processes have sent a dummy message to process 0.
static void test_link (int, int)
static void test_links ()
static bool grng_synchrony (unsigned long)
static double_t time_communicate (int num_bytes, int samples=1000)
static double_t time_communicatev (int num_bytes, int samples=1000)
static double_t time_communicate_offgrid (int num_bytes, int samples=1000)
static double_t time_communicate_alltoall (int num_bytes, int samples=1000)
static double_t time_communicate_alltoallv (int num_bytes, int samples=1000)
static std::string get_processor_name ()
static int get_rank ()
static int get_num_processes ()
static void set_num_processes (int)
static int get_num_virtual_processes ()
static int get_send_buffer_size ()
static int get_recv_buffer_size ()
static bool get_use_Allgather ()
static bool get_initialized ()
static void set_num_threads (thread num_threads)
static void set_buffer_sizes (int send_buffer_size, int recv_buffer_size)
static void set_use_Allgather (bool use_Allgather)
static void communicate (std::vector< uint_t > &send_buffer, std::vector< uint_t > &recv_buffer, std::vector< int > &displacements)
static void communicate (std::vector< OffGridSpike > &send_buffer, std::vector< OffGridSpike > &recv_buffer, std::vector< int > &displacements)
static void communicate (std::vector< double_t > &send_buffer, std::vector< double_t > &recv_buffer, std::vector< int > &displacements)
static void communicate (double_t, std::vector< double_t > &)
static void communicate (std::vector< int_t > &)
static void communicate (std::vector< long_t > &)
template<typename NodeListType >
static void communicate (const NodeListType &local_nodes, std::vector< NodeAddressingData > &all_nodes, bool remote=false)
Collect GIDs for all nodes in a given node list across processes.
template<typename NodeListType >
static void communicate (const NodeListType &local_nodes, std::vector< NodeAddressingData > &all_nodes, Network &net, DictionaryDatum params, bool remote=false)
static void communicate_connector_properties (DictionaryDatum &)
static void synchronize ()
static bool grng_synchrony (unsigned long)
static double_t time_communicate (int, int)
static double_t time_communicatev (int, int)
static double_t time_communicate_offgrid (int, int)
static double_t time_communicate_alltoall (int, int)
static double_t time_communicate_alltoallv (int, int)
static std::string get_processor_name ()
static int get_rank ()
static int get_num_processes ()
static void set_num_processes (int)
static int get_num_virtual_processes ()
static int get_send_buffer_size ()
static int get_recv_buffer_size ()
static bool get_use_Allgather ()
static bool get_initialized ()
static void set_num_threads (thread num_threads)
static void set_buffer_sizes (int send_buffer_size, int recv_buffer_size)
static void set_use_Allgather (bool use_Allgather)
Static Public Attributes
static MUSIC::Setup * music_setup =0
pointer to a MUSIC setup object
static MUSIC::Runtime * music_runtime =0
pointer to a MUSIC runtime object
Static Private Member Functions
static void init_communication ()
Perform the CPEX algorithm to determine the communication partner of the process for each communication step.
static void communicate_Allgather (std::vector< uint_t > &send_buffer, std::vector< uint_t > &recv_buffer, std::vector< int > &displacements)
static void communicate_Allgather (std::vector< OffGridSpike > &send_buffer, std::vector< OffGridSpike > &recv_buffer, std::vector< int > &displacements)
static void communicate_Allgather (std::vector< int_t > &)
static void communicate_Allgather (std::vector< long_t > &)
template<typename T >
static void communicate_Allgatherv (std::vector< T > &send_buffer, std::vector< T > &recv_buffer, std::vector< int > &displacements, std::vector< int > &recv_counts)
template<typename T >
static void communicate_Allgather (std::vector< T > &send_buffer, std::vector< T > &recv_buffer, std::vector< int > &displacements)
static void communicate_CPEX (std::vector< uint_t > &send_buffer, std::vector< uint_t > &recv_buffer, std::vector< int > &displacements)
static void communicate_CPEX (std::vector< OffGridSpike > &send_buffer, std::vector< OffGridSpike > &recv_buffer, std::vector< int > &displacements)
static void communicate_CPEX (std::vector< int_t > &)
static void communicate_CPEX (std::vector< long_t > &)
Static Private Attributes
static Network * net_ = 0
Pointer to the Network class.
static int rank_ = 0
the rank of the machine
static int num_processes_ = 1
the number of mpi-processes
static int n_vps_ = 1
the number of virtual processes
static int send_buffer_size_ = 1
expected size of send buffer
static int recv_buffer_size_ = 1
size of receive buffer
static bool initialized_ = false
whether MPI is initialized
static bool use_Allgather_ = true
using Allgather communication
static std::vector< int > comm_step_ = std::vector<int>()
array containing communication partner for each step.
static uint_t COMM_OVERFLOW_ERROR = std::numeric_limits<unsigned int>::max()
Friends
class Network
Constructor & Destructor Documentation
nest::Communicator::Communicator () inline
nest::Communicator::~Communicator () inline
nest::Communicator::Communicator () inline
nest::Communicator::~Communicator () inline
Member Function Documentation
void nest::Communicator::advance_music_time (long_t num_steps) static
Advance the time of music by num_steps simulation steps.
Parameters
num_steps number of simulation steps, the time to propagate. /TODO: put this into scheduler.
Referenced by nest::Scheduler::update().
void nest::Communicator::communicate (std::vector< uint_t > & send_buffer, std::vector< uint_t > & recv_buffer, std::vector< int > & displacements) static
communicate (on-grid) if compiled without MPI
Referenced by nest::FreeLayer< D >::communicate_positions_(), nest::Network::divergent_connect(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), nest::Scheduler::prepare_nodes(), nest::Network::random_divergent_connect(), and nest::Scheduler::update_delay_extrema_().
void nest::Communicator::communicate (std::vector< OffGridSpike > & send_buffer, std::vector< OffGridSpike > & recv_buffer, std::vector< int > & displacements) static
communicate (off-grid) if compiled without MPI
void nest::Communicator::communicate (std::vector< double_t > & send_buffer, std::vector< double_t > & recv_buffer, std::vector< int > & displacements) static
void nest::Communicator::communicate (double_t send_val, std::vector< double_t > & recv_buffer) static
References comm.
void nest::Communicator::communicate (std::vector< int_t > & buffer) static
communicate function for sending set-up information
void nest::Communicator::communicate (std::vector< long_t > & buffer) static
template<typename NodeListType > void nest::Communicator::communicate (const NodeListType & local_nodes, std::vector< NodeAddressingData > & all_nodes, bool remote = false) static
Collect GIDs for all nodes in a given node list across processes.
The NodeListType should be one of LocalNodeList, LocalLeafList, LocalChildList.
References assert(), nest::names::n, num_processes_, and rank_.
template<typename NodeListType > void nest::Communicator::communicate (const NodeListType & local_nodes, std::vector< NodeAddressingData > & all_nodes, Network & net, DictionaryDatum params, bool remote = false) static
References assert(), nest::Network::get_status(), Token::matches_as_string(), nest::names::n, num_processes_, and rank_.
static void nest::Communicator::communicate (std::vector< uint_t > & send_buffer, std::vector< uint_t > & recv_buffer, std::vector< int > & displacements) static
static void nest::Communicator::communicate (std::vector< OffGridSpike > & send_buffer, std::vector< OffGridSpike > & recv_buffer, std::vector< int > & displacements) static
static void nest::Communicator::communicate (std::vector< double_t > & send_buffer, std::vector< double_t > & recv_buffer, std::vector< int > & displacements) static
static void nest::Communicator::communicate (double_t , std::vector< double_t > &) static
static void nest::Communicator::communicate (std::vector< int_t > &) inline static
static void nest::Communicator::communicate (std::vector< long_t > &) inline static
template<typename NodeListType > static void nest::Communicator::communicate (const NodeListType & local_nodes, std::vector< NodeAddressingData > & all_nodes, bool remote = false) static
Collect GIDs for all nodes in a given node list across processes.
The NodeListType should be one of LocalNodeList, LocalLeafList, LocalChildList. Collect GIDs for all nodes in a given node list across processes. The NodeListType should be one of LocalNodeList, LocalLeafList, LocalChildList.
template<typename NodeListType > static void nest::Communicator::communicate (const NodeListType & local_nodes, std::vector< NodeAddressingData > & all_nodes, Network & net, DictionaryDatum params, bool remote = false) static
void nest::Communicator::communicate_Allgather (std::vector< uint_t > & send_buffer, std::vector< uint_t > & recv_buffer, std::vector< int > & displacements) static private
References comm.
void nest::Communicator::communicate_Allgather (std::vector< OffGridSpike > & send_buffer, std::vector< OffGridSpike > & recv_buffer, std::vector< int > & displacements) static private
References comm, and MPI_OFFGRID_SPIKE.
void nest::Communicator::communicate_Allgather (std::vector< int_t > & buffer) static private
References comm.
void nest::Communicator::communicate_Allgather (std::vector< long_t > & buffer) static private
References comm.
template<typename T > void nest::Communicator::communicate_Allgather (std::vector< T > & send_buffer, std::vector< T > & recv_buffer, std::vector< int > & displacements) static private
References comm.
template<typename T > void nest::Communicator::communicate_Allgatherv (std::vector< T > & send_buffer, std::vector< T > & recv_buffer, std::vector< int > & displacements, std::vector< int > & recv_counts) static private
References comm.
void nest::Communicator::communicate_connector_properties (DictionaryDatum & dict) static
References nest::names::delays, nest::names::targets, and nest::names::weights.
static void nest::Communicator::communicate_connector_properties (DictionaryDatum &) inline static
void nest::Communicator::communicate_CPEX (std::vector< uint_t > & send_buffer, std::vector< uint_t > & recv_buffer, std::vector< int > & displacements) static private
References comm.
void nest::Communicator::communicate_CPEX (std::vector< OffGridSpike > & send_buffer, std::vector< OffGridSpike > & recv_buffer, std::vector< int > & displacements) static private
References comm, and MPI_OFFGRID_SPIKE.
void nest::Communicator::communicate_CPEX (std::vector< int_t > & buffer) static private
References comm.
void nest::Communicator::communicate_CPEX (std::vector< long_t > & buffer) static private
References comm.
void nest::Communicator::enter_runtime (double_t h_min_delay) static
Enter the runtime mode.
This must be done before simulating. After having entered runtime mode ports cannot be published anymore.
Parameters
h_min_delay is the length of a time slice, after which commmunication should take place.
References numerics::e.
Referenced by nest::Scheduler::prepare_simulation().
void nest::Communicator::finalize () static
Finish off MPI routines.
References numerics::e, SLIInterpreter::M_INFO, and MPI_OFFGRID_SPIKE.
Referenced by nestshutdown().
bool nest::Communicator::get_initialized () inline static
References initialized_.
Referenced by nest::NestModule::init().
static bool nest::Communicator::get_initialized () static
MUSIC::Runtime * nest::Communicator::get_music_runtime () static
MUSIC::Setup * nest::Communicator::get_music_setup () static
Referenced by nest::music_cont_in_proxy::calibrate(), nest::music_event_out_proxy::calibrate(), nest::music_message_in_proxy::calibrate(), and nest::MusicEventHandler::publish_port().
int nest::Communicator::get_num_processes () inline static
References num_processes_.
Referenced by nest::cg_create_masks(), nest::cg_set_masks(), nest::Scheduler::configure_spike_buffers_(), nest::NestModule::NumProcessesFunction::execute(), nest::Scheduler::finalize_simulation(), nest::Scheduler::get_num_processes(), nest::Scheduler::init_(), nest::Scheduler::prepare_nodes(), nest::Scheduler::prepare_simulation(), and nest::Scheduler::update_delay_extrema_().
static int nest::Communicator::get_num_processes () static
int nest::Communicator::get_num_virtual_processes () inline static
References n_vps_.
Referenced by nest::RecordingDevice::build_filename_(), nest::FixedTotalNumberBuilder::connect_(), and nest::Scheduler::prepare_nodes().
static int nest::Communicator::get_num_virtual_processes () static
std::string nest::Communicator::get_processor_name () inline static
Referenced by nest::NestModule::ProcessorNameFunction::execute().
static std::string nest::Communicator::get_processor_name () static
int nest::Communicator::get_rank () inline static
References rank_.
Referenced by nest::Network::add_node(), nest::cg_set_masks(), nest::NestModule::RankFunction::execute(), nest::Scheduler::is_local_vp(), nest::Scheduler::thread_to_vp(), nest::Scheduler::update_delay_extrema_(), and nest::Scheduler::vp_to_thread().
static int nest::Communicator::get_rank () static
int nest::Communicator::get_recv_buffer_size () inline static
References recv_buffer_size_.
Referenced by nest::Scheduler::prepare_nodes().
static int nest::Communicator::get_recv_buffer_size () static
int nest::Communicator::get_send_buffer_size () inline static
References send_buffer_size_.
Referenced by nest::Scheduler::prepare_nodes().
static int nest::Communicator::get_send_buffer_size () static
bool nest::Communicator::get_use_Allgather () inline static
References use_Allgather_.
Referenced by nest::Scheduler::prepare_nodes().
static bool nest::Communicator::get_use_Allgather () static
bool nest::Communicator::grng_synchrony (unsigned long process_rnd_number) static
References comm.
Referenced by nest::Scheduler::finalize_simulation(), and nest::Scheduler::prepare_simulation().
static bool nest::Communicator::grng_synchrony (unsigned long) inline static
void nest::Communicator::init (int * argc, char ** argv[]) static
Set up MPI and establish number of processes and rank.
References nest::names::address, nest::Communicator::OffGridSpike::assert_datatype_compatibility(), comm, nest::Communicator::OffGridSpike::gid_, init_communication(), initialized_, MPI_OFFGRID_SPIKE, music_setup, num_processes_, nest::Communicator::OffGridSpike::offset_, nest::names::offsets, rank_, recv_buffer_size_, send_buffer_size_, and use_Allgather_.
void nest::Communicator::init_communication () static private
Perform the CPEX algorithm to determine the communication partner of the process for each communication step.
See: A. Tam and C. Wang: Efficient scheduling of complete exchange on clusters. In 13th International Conference on Parallel and Distributed Computing Systems (PDCS 2000), Las Vegas, 2000
Referenced by init(), and set_use_Allgather().
void nest::Communicator::mpi_abort (int exitcode) static
Referenced by nest::NestModule::MPIAbort_iFunction::execute().
static void nest::Communicator::register_music_event_in_proxy (std::string portname, int channel, nest::Node * mp) static
Register a music_event_in_proxy for a given port and a given channel.
As a consequence, the proxy will be informed, whenever an event over this port and channel comes in.
void nest::Communicator::set_buffer_sizes (int send_buffer_size, int recv_buffer_size) inline static
References recv_buffer_size_, and send_buffer_size_.
Referenced by nest::Scheduler::configure_spike_buffers_().
static void nest::Communicator::set_buffer_sizes (int send_buffer_size, int recv_buffer_size) static
void nest::Communicator::set_num_processes (int np) inline static
References num_processes_.
Referenced by nest::NestModule::SetFakeNumProcessesFunction_i::execute().
static void nest::Communicator::set_num_processes (int) static
void nest::Communicator::set_num_threads (thread num_threads) inline static
References n_vps_, and num_processes_.
Referenced by nest::Scheduler::prepare_nodes().
static void nest::Communicator::set_num_threads (thread num_threads) static
void nest::Communicator::set_use_Allgather (bool use_Allgather) inline static
References init_communication(), and use_Allgather_.
Referenced by nest::Scheduler::prepare_nodes().
static void nest::Communicator::set_use_Allgather (bool use_Allgather) static
void nest::Communicator::synchronize () static
Ensure all processes have reached the same stage by waiting until all processes have sent a dummy message to process 0.
References comm.
Referenced by nest::NestModule::SyncProcessesFunction::execute(), and nest::Scheduler::resume().
static void nest::Communicator::synchronize () inline static
void nest::Communicator::test_link (int sender, int receiver) static
References assert(), and comm.
void nest::Communicator::test_links () static
nest::double_t nest::Communicator::time_communicate (int num_bytes, int samples = 1000) static
References nest::Stopwatch::elapsed(), nest::Stopwatch::start(), and nest::Stopwatch::stop().
Referenced by nest::NestModule::TimeCommunication_i_i_bFunction::execute().
static double_t nest::Communicator::time_communicate (int , int) inline static
nest::double_t nest::Communicator::time_communicate_alltoall (int num_bytes, int samples = 1000) static
References nest::Stopwatch::elapsed(), nest::Stopwatch::start(), and nest::Stopwatch::stop().
Referenced by nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute().
static double_t nest::Communicator::time_communicate_alltoall (int , int) inline static
nest::double_t nest::Communicator::time_communicate_alltoallv (int num_bytes, int samples = 1000) static
References nest::Stopwatch::elapsed(), nest::Stopwatch::start(), and nest::Stopwatch::stop().
Referenced by nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute().
static double_t nest::Communicator::time_communicate_alltoallv (int , int) inline static
nest::double_t nest::Communicator::time_communicate_offgrid (int num_bytes, int samples = 1000) static
References nest::Stopwatch::elapsed(), MPI_OFFGRID_SPIKE, nest::Stopwatch::start(), and nest::Stopwatch::stop().
Referenced by nest::NestModule::TimeCommunication_i_i_bFunction::execute().
static double_t nest::Communicator::time_communicate_offgrid (int , int) inline static
nest::double_t nest::Communicator::time_communicatev (int num_bytes, int samples = 1000) static
References nest::Stopwatch::elapsed(), nest::Stopwatch::start(), and nest::Stopwatch::stop().
Referenced by nest::NestModule::TimeCommunicationv_i_iFunction::execute().
static double_t nest::Communicator::time_communicatev (int , int) inline static
Friends And Related Function Documentation
Network friend
Member Data Documentation
unsigned int nest::Communicator::COMM_OVERFLOW_ERROR = std::numeric_limits<unsigned int>::max() static private
std::vector< int > nest::Communicator::comm_step_ = std::vector<int>() static private
array containing communication partner for each step.
static bool nest::Communicator::initialized_ = false static private
whether MPI is initialized
Referenced by get_initialized(), and init().
MUSIC::Runtime * nest::Communicator::music_runtime =0 static
pointer to a MUSIC runtime object
MUSIC::Setup * nest::Communicator::music_setup =0 static
pointer to a MUSIC setup object
Referenced by init().
static int nest::Communicator::n_vps_ = 1 static private
the number of virtual processes
Referenced by get_num_virtual_processes(), and set_num_threads().
static Network * nest::Communicator::net_ = 0 static private
Pointer to the Network class.
Referenced by nest::Network::Network().
static int nest::Communicator::num_processes_ = 1 static private
the number of mpi-processes
Referenced by communicate(), get_num_processes(), init(), set_num_processes(), and set_num_threads().
static int nest::Communicator::rank_ = 0 static private
the rank of the machine
Referenced by communicate(), get_rank(), and init().
static int nest::Communicator::recv_buffer_size_ = 1 static private
size of receive buffer
Referenced by get_recv_buffer_size(), init(), and set_buffer_sizes().
static int nest::Communicator::send_buffer_size_ = 1 static private
expected size of send buffer
Referenced by get_send_buffer_size(), init(), and set_buffer_sizes().
static bool nest::Communicator::use_Allgather_ = true static private
using Allgather communication
Referenced by get_use_Allgather(), init(), and set_use_Allgather().
The documentation for this class was generated from the following files:
communicator.h
communicator.cpp
communicator_impl.h