NEST: TypeTrie Class Reference
TypeTrie Class Reference
#include <typechk.h>
Classes
class TypeNode
Public Member Functions
TypeTrie ()
TypeTrie (const TokenArray &ta)
TypeTrie (const TypeTrie &tt)
~TypeTrie ()
void insert_move (const TypeArray &, Token &)
void insert (const TypeArray &a, const Token &t)
const Token & lookup (const TokenStack &st) const
bool operator== (const TypeTrie &) const
bool equals (const Name &, const Name &) const
void toTokenArray (TokenArray &) const
void info (std::ostream &) const
Private Member Functions
TypeNode * getalternative (TypeNode *, const Name &)
TypeNode * newnode (const TokenArray &) const
Private Attributes
TypeNode * root
Constructor & Destructor Documentation
TypeTrie::TypeTrie () inline
TypeTrie::TypeTrie (const TokenArray & ta) inline
References newnode(), and root.
TypeTrie::TypeTrie (const TypeTrie & tt) inline
References TypeTrie::TypeNode::addreference(), and root.
TypeTrie::~TypeTrie () inline
References TypeTrie::TypeNode::removereference(), and root.
Member Function Documentation
bool TypeTrie::equals (const Name & t1, const Name & t2) const inline
References sli::any.
Referenced by lookup().
TypeTrie::TypeNode * TypeTrie::getalternative (TypeTrie::TypeNode * pos, const Name & type) private
References TypeTrie::TypeNode::alt, sli::any, TypeTrie::TypeNode::func, TypeTrie::TypeNode::next, Token::swap(), and TypeTrie::TypeNode::type.
Referenced by insert_move().
void TypeTrie::info (std::ostream & out) const
References TypeTrie::TypeNode::info(), and root.
Referenced by TrieInfoFunction::execute(), TrieDatum::info(), and SLIInterpreter::print_error().
void TypeTrie::insert (const TypeArray & a, const Token & t) inline
References insert_move().
Referenced by TrieDatum::insert().
void TypeTrie::insert_move (const TypeArray & a, Token & f)
References assert(), TypeTrie::TypeNode::func, getalternative(), Token::move(), TypeTrie::TypeNode::next, sli::object, root, and TypeTrie::TypeNode::type.
Referenced by insert(), and TrieDatum::insert_move().
const Token & TypeTrie::lookup (const TokenStack & st) const inline
References TypeTrie::TypeNode::alt, equals(), TypeTrie::TypeNode::func, Datum::gettypename(), TokenStack::load(), TypeTrie::TypeNode::next, sli::object, TokenStack::pick(), root, and TypeTrie::TypeNode::type.
Referenced by TrieDatum::lookup().
TypeTrie::TypeNode * TypeTrie::newnode (const TokenArray & ta) const private
References assert(), nest::names::n, sli::object, and TokenArray::size().
Referenced by TypeTrie().
bool TypeTrie::operator== (const TypeTrie & tt) const inline
References root.
void TypeTrie::toTokenArray (TokenArray & a) const
References TokenArray::clear(), root, and TypeTrie::TypeNode::toTokenArray().
Referenced by Cva_tFunction::execute().
Member Data Documentation
TypeNode* TypeTrie::root private
Referenced by info(), insert_move(), lookup(), operator==(), toTokenArray(), TypeTrie(), and ~TypeTrie().
The documentation for this class was generated from the following files:
typechk.h
typechk.cc