NEST: nest::Parameter Class Reference
nest::Parameter Class Reference abstract
Abstract base class for parameters.
#include <parameter.h>
Public Member Functions
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
virtual double_t raw_value (const Position< 2 > &, librandom::RngPtr &) const
Raw value disregarding cutoff.
virtual double_t raw_value (const Position< 3 > &, librandom::RngPtr &) const
Raw value disregarding cutoff.
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * clone () const =0
Clone method.
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Private Attributes
double_t cutoff_
Detailed Description
Abstract base class for parameters.
Constructor & Destructor Documentation
nest::Parameter::Parameter () inline
Default constructor.
nest::Parameter::Parameter (double_t cutoff) inline
Constructor.
Parameters
cutoff Values less than the cutoff are set to zero.
nest::Parameter::Parameter (const DictionaryDatum & d) inline
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
Parameters
d dictionary with parameter values
References nest::names::cutoff, cutoff_, and nest::names::d.
virtual nest::Parameter::~Parameter () inline virtual
Virtual destructor.
Member Function Documentation
Parameter * nest::Parameter::add_parameter (const Parameter & other) const inline virtual
Create the sum of this parameter with another.
Returns
a new dynamically allocated parameter.
virtual Parameter* nest::Parameter::clone () const pure virtual
Clone method.
Returns
dynamically allocated copy of parameter object
Implemented in nest::ConverseParameter, nest::DifferenceParameter, nest::SumParameter, nest::QuotientParameter, nest::ProductParameter, nest::AnchoredParameter< D >, nest::LognormalParameter, nest::NormalParameter, nest::UniformParameter, nest::Gaussian2DParameter, nest::GaussianParameter, nest::ExponentialParameter, nest::LinearParameter, and nest::ConstantParameter.
Parameter * nest::Parameter::divide_parameter (const Parameter & other) const inline virtual
Create the quotient of this parameter with another.
Returns
a new dynamically allocated parameter.
Parameter * nest::Parameter::multiply_parameter (const Parameter & other) const inline virtual
Create the product of this parameter with another.
Returns
a new dynamically allocated parameter.
virtual double_t nest::Parameter::raw_value (const Position< 2 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented in nest::ConverseParameter, nest::DifferenceParameter, nest::SumParameter, nest::QuotientParameter, nest::ProductParameter, nest::LognormalParameter, nest::NormalParameter, nest::UniformParameter, nest::Gaussian2DParameter, nest::RadialParameter, and nest::ConstantParameter.
Referenced by nest::AnchoredParameter< D >::raw_value(), nest::ConverseParameter::raw_value(), and value().
virtual double_t nest::Parameter::raw_value (const Position< 3 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented in nest::ConverseParameter, nest::DifferenceParameter, nest::SumParameter, nest::QuotientParameter, nest::ProductParameter, nest::LognormalParameter, nest::NormalParameter, nest::UniformParameter, nest::Gaussian2DParameter, nest::RadialParameter, and nest::ConstantParameter.
Parameter * nest::Parameter::subtract_parameter (const Parameter & other) const inline virtual
Create the difference of this parameter with another.
Returns
a new dynamically allocated parameter.
double_t nest::Parameter::value (const Position< 2 > & p, librandom::RngPtr & rng) const inline
Returns
the value of the parameter at the given point.
References cutoff_, and raw_value().
Referenced by nest::ProductParameter::raw_value(), nest::QuotientParameter::raw_value(), nest::SumParameter::raw_value(), nest::DifferenceParameter::raw_value(), and value().
double_t nest::Parameter::value (const Position< 3 > & p, librandom::RngPtr & rng) const inline
Returns
the value of the parameter at the given point.
References cutoff_, and raw_value().
double_t nest::Parameter::value (const std::vector< double_t > & pt, librandom::RngPtr & rng) const
Returns
the value of the parameter at the given point.
References value().
Member Data Documentation
double_t nest::Parameter::cutoff_ private
Referenced by Parameter(), and value().
The documentation for this class was generated from the following files:
parameter.h
parameter.cpp