NEST: nest::RadialParameter Class Reference
nest::RadialParameter Class Reference abstract
Abstract base class for parameters only depending on distance.
#include <parameter.h>
Public Member Functions
RadialParameter ()
RadialParameter (double_t cutoff)
RadialParameter (const DictionaryDatum &d)
virtual double_t raw_value (double_t) const =0
double_t raw_value (const Position< 2 > &p, librandom::RngPtr &) const
Raw value disregarding cutoff.
double_t raw_value (const Position< 3 > &p, librandom::RngPtr &) const
Raw value disregarding cutoff.
Public Member Functions inherited from nest::Parameter
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * clone () const =0
Clone method.
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Detailed Description
Abstract base class for parameters only depending on distance.
Constructor & Destructor Documentation
nest::RadialParameter::RadialParameter () inline
nest::RadialParameter::RadialParameter (double_t cutoff) inline
nest::RadialParameter::RadialParameter (const DictionaryDatum & d) inline
Member Function Documentation
virtual double_t nest::RadialParameter::raw_value (double_t) const pure virtual
Implemented in nest::GaussianParameter, nest::ExponentialParameter, and nest::LinearParameter.
Referenced by raw_value().
double_t nest::RadialParameter::raw_value (const Position< 2 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References nest::Position< D, T >::length(), and raw_value().
double_t nest::RadialParameter::raw_value (const Position< 3 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References nest::Position< D, T >::length(), and raw_value().
The documentation for this class was generated from the following file:
parameter.h