NEST: librandom::GSL_BinomialRandomDev Class Reference
librandom::GSL_BinomialRandomDev Class Reference
Random Deviate Generators.
Class GSL_BinomialRandomDev.
#include <gsl_binomial_randomdev.h>
Public Member Functions
GSL_BinomialRandomDev (RngPtr, double p_s=0.5, unsigned int n_s=1)
GSL_BinomialRandomDev (double p_s=0.5, unsigned int n_s=1)
void set_p_n (double, unsigned int)
set parameters for p and n p - success probability for single trial n - number of trials
void set_p (double)
set p
void set_n (unsigned int)
set n
long ldev ()
draw integer
long ldev (RngPtr) const
draw integer, threaded
bool has_ldev () const
true if RDG implements ldev function
double operator() (RngPtr) const
return as double, threaded
void set_status (const DictionaryDatum &)
set distribution parameters from SLI dict
void get_status (DictionaryDatum &) const
get distribution parameters from SLI dict
Public Member Functions inherited from librandom::RandomDev
RandomDev (RngPtr rng=RngPtr(0))
Construct with (single-threaded) or without (multithreaded) RNG.
virtual ~RandomDev ()
ensure proper clean-up
virtual double operator() (void)
Operator delivering doubles.
void set_rng (RngPtr rng)
set RNG
Private Attributes
double p_
probability p of binomial distribution
unsigned int n_
parameter n in binomial distribution
gsl_rng * rng_
Additional Inherited Members
Protected Attributes inherited from librandom::RandomDev
RngPtr rng_
store underlying RNG
Detailed Description
Class GSL_BinomialRandomDev.
Generates an RNG which returns Binomial(k;p;n) distributed random numbers out of an RNG which returns binomially distributed random numbers:
p(k) = (n! / k!(n-k)!) p^k (1-p)^(n-k) , 0<=k<=n, n<0
Arguments:
pointer to an RNG
parameter p (optional, default = 0.5)
parameter n (optional, default = 1)
See also
http://www.gnu.org/software/gsl/manual/html_node/The-Binomial-Distribution.html
Constructor & Destructor Documentation
librandom::GSL_BinomialRandomDev::GSL_BinomialRandomDev (RngPtr r_s, double p_s = 0.5, unsigned int n_s = 1)
References librandom::GslRandomGen::rng_, and rng_.
librandom::GSL_BinomialRandomDev::GSL_BinomialRandomDev (double p_s = 0.5, unsigned int n_s = 1)
Member Function Documentation
void librandom::GSL_BinomialRandomDev::get_status (DictionaryDatum & d) const virtual
get distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::d.
bool librandom::GSL_BinomialRandomDev::has_ldev () const inline virtual
true if RDG implements ldev function
Reimplemented from librandom::RandomDev.
long librandom::GSL_BinomialRandomDev::ldev (void) virtual
draw integer
Reimplemented from librandom::RandomDev.
Referenced by operator()().
long librandom::GSL_BinomialRandomDev::ldev (RngPtr rng) const virtual
draw integer, threaded
Reimplemented from librandom::RandomDev.
References librandom::GslRandomGen::rng_.
double librandom::GSL_BinomialRandomDev::operator() (RngPtr rthrd) const inline virtual
return as double, threaded
Implements librandom::RandomDev.
References ldev().
void librandom::GSL_BinomialRandomDev::set_n (unsigned int n_s)
set n
void librandom::GSL_BinomialRandomDev::set_p (double p_s)
set p
References assert().
void librandom::GSL_BinomialRandomDev::set_p_n (double p_s, unsigned int)
set parameters for p and n p - success probability for single trial n - number of trials
void librandom::GSL_BinomialRandomDev::set_status (const DictionaryDatum & d) virtual
set distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::d, and nest::names::max.
Member Data Documentation
unsigned int librandom::GSL_BinomialRandomDev::n_ private
parameter n in binomial distribution
double librandom::GSL_BinomialRandomDev::p_ private
probability p of binomial distribution
gsl_rng* librandom::GSL_BinomialRandomDev::rng_ private
Referenced by GSL_BinomialRandomDev().
The documentation for this class was generated from the following files:
gsl_binomial_randomdev.h
gsl_binomial_randomdev.cpp