NEST: nest::ConnBuilder Class Reference
nest::ConnBuilder Class Reference abstract
Abstract base class for ConnBuilders.
#include <conn_builder.h>
Public Member Functions
virtual void connect ()
Connect sources to targets according to specifications in dictionary.
ConnBuilder (Network &, const GIDCollection &, const GIDCollection &, const DictionaryDatum &, const DictionaryDatum &)
parameters: sources, targets, specifications
virtual ~ConnBuilder ()
Protected Member Functions
virtual void connect_ ()=0
Implements the actual connection algorithm.
void single_connect_ (index, Node &, thread, librandom::RngPtr &)
Create connection between given nodes, fill parameter values.
Protected Attributes
Network & net_
const GIDCollection & sources_
const GIDCollection & targets_
bool autapses_
bool multapses_
std::vector< lockPTR
< WrappedThreadException > > exceptions_raised_
buffer for exceptions raised in threads
Private Types
typedef std::map< Name,
ConnParameter * > ConnParameterMap
Private Member Functions
void check_synapse_params_ (std::string, const DictionaryDatum &)
Private Attributes
index synapse_model_
bool default_weight_and_delay_
indicate that weight and delay should not be set per synapse
bool default_weight_
indicate that weight should not be set per synapse
ConnParameter * weight_
ConnParameter * delay_
ConnParameterMap synapse_params_
all other parameters, mapping name to value representation
std::vector< DictionaryDatum > param_dicts_
dictionaries to pass to connect function, one per thread
Detailed Description
Abstract base class for ConnBuilders.
The base class extracts and holds parameters and provides the connect interface. Derived classes implement the connect method.
Note
Naming classes *Builder to avoid name confusion with Connector classes.
Member Typedef Documentation
typedef std::map<Name, ConnParameter*> nest::ConnBuilder::ConnParameterMap private
Constructor & Destructor Documentation
nest::ConnBuilder::ConnBuilder (Network & net, const GIDCollection & sources, const GIDCollection & targets, const DictionaryDatum & conn_spec, const DictionaryDatum & syn_spec)
parameters: sources, targets, specifications
References nest::names::autapses, autapses_, check_synapse_params_(), nest::ConnParameter::create(), default_weight_, default_weight_and_delay_, nest::names::delay, delay_, nest::Network::get_connector_defaults(), nest::Network::get_num_threads(), nest::Network::get_synapsedict(), Dictionary::known(), nest::names::model, nest::names::multapses, multapses_, nest::names::music_channel, net_, param_dicts_, nest::names::receptor_type, synapse_model_, synapse_params_, nest::names::weight, and weight_.
nest::ConnBuilder::~ConnBuilder () virtual
Member Function Documentation
void nest::ConnBuilder::check_synapse_params_ (std::string syn_name, const DictionaryDatum & syn_spec) inline private
References nest::names::a, nest::names::c, nest::names::delay, SLIInterpreter::M_WARNING, NotImplemented::message(), nest::names::n, and nest::names::weight.
Referenced by ConnBuilder().
void nest::ConnBuilder::connect () virtual
Connect sources to targets according to specifications in dictionary.
To create a connection, call
cb.connect();
where conn_spec_dict speficies connection type and its parameters.
Referenced by nest::Network::connect().
virtual void nest::ConnBuilder::connect_ () protected pure virtual
Implements the actual connection algorithm.
Implemented in nest::BernoulliBuilder, nest::FixedTotalNumberBuilder, nest::FixedOutDegreeBuilder, nest::FixedInDegreeBuilder, nest::AllToAllBuilder, and nest::OneToOneBuilder.
void nest::ConnBuilder::single_connect_ (index sgid, Node & target, thread target_thread, librandom::RngPtr & rng) inline protected
Create connection between given nodes, fill parameter values.
References assert(), numerics::e, nest::Node::get_gid(), nest::names::music_channel, nest::names::receptor_type, and nest::names::target_thread.
Member Data Documentation
bool nest::ConnBuilder::autapses_ protected
Referenced by ConnBuilder().
bool nest::ConnBuilder::default_weight_ private
indicate that weight should not be set per synapse
Referenced by ConnBuilder().
bool nest::ConnBuilder::default_weight_and_delay_ private
indicate that weight and delay should not be set per synapse
Referenced by ConnBuilder().
ConnParameter* nest::ConnBuilder::delay_ private
Referenced by ConnBuilder().
std::vector<lockPTR<WrappedThreadException> > nest::ConnBuilder::exceptions_raised_ protected
buffer for exceptions raised in threads
bool nest::ConnBuilder::multapses_ protected
Referenced by ConnBuilder(), nest::FixedInDegreeBuilder::FixedInDegreeBuilder(), nest::FixedOutDegreeBuilder::FixedOutDegreeBuilder(), and nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder().
Network& nest::ConnBuilder::net_ protected
Referenced by ConnBuilder().
std::vector<DictionaryDatum> nest::ConnBuilder::param_dicts_ private
dictionaries to pass to connect function, one per thread
Referenced by ConnBuilder().
const GIDCollection& nest::ConnBuilder::sources_ protected
Referenced by nest::FixedInDegreeBuilder::FixedInDegreeBuilder(), and nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder().
index nest::ConnBuilder::synapse_model_ private
Referenced by ConnBuilder().
ConnParameterMap nest::ConnBuilder::synapse_params_ private
all other parameters, mapping name to value representation
Referenced by ConnBuilder().
const GIDCollection& nest::ConnBuilder::targets_ protected
Referenced by nest::FixedOutDegreeBuilder::FixedOutDegreeBuilder(), and nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder().
ConnParameter* nest::ConnBuilder::weight_ private
Referenced by ConnBuilder().
The documentation for this class was generated from the following files:
conn_builder.h
conn_builder.cpp