NEST: SLIArrayModule::FiniteQ_dFunction Class Reference
SLIArrayModule::FiniteQ_dFunction Class Reference
SLI array functions
Test single double for finiteness.
Public Member Functions
FiniteQ_dFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Detailed Description
Test single double for finiteness.
Todo:
This class does not really belong into sliarray, but is placed here since it is a Mathematica-style Q function.
Constructor & Destructor Documentation
SLIArrayModule::FiniteQ_dFunction::FiniteQ_dFunction () inline
Member Function Documentation
void SLIArrayModule::FiniteQ_dFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, getValue< double >(), nest::names::max, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push(), and nest::names::x.
The documentation for this class was generated from the following files:
sliarray.h
sliarray.cc