NEST: LiteralDatum Class Reference
LiteralDatum Class Reference
#include <namedatum.h>
Public Member Functions
LiteralDatum (const Name &n)
LiteralDatum (const LiteralDatum &n)
~LiteralDatum ()
void pprint (std::ostream &) const
Public Member Functions inherited from AggregateDatum< Name,&SLIInterpreter::Literaltype >
AggregateDatum ()
AggregateDatum (const AggregateDatum< Name, slt > &d)
AggregateDatum (const Name &c)
virtual ~AggregateDatum ()
bool equals (const Datum *dat) const
virtual void print (std::ostream &out) const
virtual void list (std::ostream &out, std::string prefix, int l) const
virtual void input_form (std::ostream &out) const
virtual void info (std::ostream &out) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Public Member Functions inherited from Name
Name ()
Create Name without value.
Name (const char s[])
Name (const std::string &s)
Name (const Name &n)
const std::string & toString (void) const
Return string represented by Name.
handle_t toIndex (void) const
Return table index for Name object.
bool operator== (const Name &n) const
bool operator!= (const Name &n) const
bool operator< (const Name &n) const
Non-alphabetic ordering of names.
void print_handle (std::ostream &) const
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
Datum * get_ptr ()
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
Additional Inherited Members
Public Types inherited from Name
typedef unsigned int handle_t
Static Public Member Functions inherited from AggregateDatum< Name,&SLIInterpreter::Literaltype >
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Static Public Member Functions inherited from Name
static bool lookup (const std::string &s)
static size_t capacity ()
static size_t num_handles ()
static void list_handles (std::ostream &)
static void list (std::ostream &)
static void info (std::ostream &)
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Static Protected Attributes inherited from AggregateDatum< Name,&SLIInterpreter::Literaltype >
static sli::pool memory
Constructor & Destructor Documentation
LiteralDatum::LiteralDatum (const Name & n) inline
References Datum::set_executable().
Referenced by clone().
LiteralDatum::LiteralDatum (const LiteralDatum & n) inline
References Datum::set_executable().
LiteralDatum::~LiteralDatum () inline
Member Function Documentation
Datum* LiteralDatum::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Reimplemented from AggregateDatum< Name,&SLIInterpreter::Literaltype >.
References LiteralDatum().
Datum* LiteralDatum::get_ptr () inline private virtual
Returns a reference counted pointer to the datum, or a new pointer, if the type does not support reference counting.
The prefix const indicates that the pointer should be trated as const because changes affect all other references as well.
Reimplemented from Datum.
References Datum::addReference().
void LiteralDatum::pprint (std::ostream & out) const virtual
Reimplemented from AggregateDatum< Name,&SLIInterpreter::Literaltype >.
References AggregateDatum< Name,&SLIInterpreter::Literaltype >::print().
The documentation for this class was generated from the following files:
namedatum.h
literaldatum.cc