NEST: SLIException Class Reference
SLIException Class Reference abstract
Exception classes | SLI exception classes
Base class for all SLI exceptions.
#include <sliexceptions.h>
Public Member Functions
SLIException (char const *const what)
virtual ~SLIException () throw ()
virtual const char * what () const throw ()
Returns the SLI error name, used by raiseerror.
virtual std::string message ()=0
Returns a diagnostic message or empty string.
Private Attributes
std::string what_
Detailed Description
Base class for all SLI exceptions.
Constructor & Destructor Documentation
SLIException::SLIException (char const *const what) inline
virtual SLIException::~SLIException () throw () inline virtual
Member Function Documentation
virtual std::string SLIException::message () pure virtual
Returns a diagnostic message or empty string.
This function is not const, because it may clear internal data fields.
Implemented in nest::MUSICChannelAlreadyMapped, nest::MUSICPortUnknown, nest::MUSICChannelUnknown, nest::MUSICSimulationHasRun, nest::MUSICPortAlreadyPublished, nest::MUSICPortHasNoWidth, nest::MUSICPortUnconnected, nest::NumericalInstability, nest::GSLSolverFailure, nest::TimeMultipleRequired, nest::StepMultipleRequired, nest::InvalidTimeInModel, nest::InvalidDefaultResolution, nest::SimulationError, nest::SubnetExpected, nest::DistributionError, nest::DimensionMismatch, nest::BadParameter, nest::BadProperty, nest::UnsupportedEvent, NotImplemented, nest::UnexpectedEvent, NamingConflict, nest::BadDelay, DynamicModuleManagementError, nest::UnknownThread, UnaccessedDictionaryEntry, nest::IllegalConnection, IOError, nest::LayerExpected, StackUnderflow, nest::UnknownPort, EntryTypeMismatch, nest::IncompatibleReceptorType, UndefinedName, nest::UnknownReceptorType, nest::NodeWithProxiesExpected, BadParameterValue, nest::LocalNodeExpected, nest::NoThreadSiblingsAvailable, ArgumentType, RangeCheck, nest::UnknownNode, SystemSignal, TypeMismatch, nest::UnknownSynapseType, nest::ModelInUse, DivisionByZero, WrappedThreadException, nest::UnknownModelID, nest::NewModelNameExists, nest::UnknownModelName, librandom::UnsuitableRNG, nest::KernelException, and librandom::MissingRNG.
Referenced by SLIInterpreter::addmodule(), SLIInterpreter::raiseerror(), and WrappedThreadException::WrappedThreadException().
virtual const char* SLIException::what () const throw () inline virtual
Returns the SLI error name, used by raiseerror.
Return name of the exception as C-style string. Use this name to translate the exception to a SLI error. For example:
catch(IllegalOperation &e)
{
    i->error("ChangeSubnet","Target node must be a subnet.");
    i->raiseerror(e.what());
  return;
}
Note
The catch clause must be terminated with a return statement, if raiseerror was called.
References what_.
Referenced by SLIInterpreter::addmodule(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), and SLIInterpreter::raiseerror().
Member Data Documentation
std::string SLIException::what_ private
Referenced by what().
The documentation for this class was generated from the following file:
sliexceptions.h