NEST: IteratorDatum Class Reference
IteratorDatum Class Reference
#include <iteratordatum.h>
Public Member Functions
IteratorDatum ()
IteratorDatum (long start_s, long stop_s, long di_s)
IteratorDatum (const IteratorDatum &d_s)
virtual ~IteratorDatum ()
void incr (void)
void decr (void)
long begin (void)
long end (void)
long pos (void)
long size (void)
bool operator== (const IteratorDatum &i) const
void print (std::ostream &out) const
void pprint (std::ostream &out) const
Public Member Functions inherited from GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >
GenericDatum ()
GenericDatum (const IteratorState &d_s)
GenericDatum (const GenericDatum< IteratorState, slt > &gd)
virtual ~GenericDatum ()
const IteratorState & operator= (const IteratorState &d_s)
const IteratorState & get (void) const
IteratorState & get (void)
IteratorState & get_lval ()
void print (std::ostream &o) const
void pprint (std::ostream &o) const
void info (std::ostream &out) const
bool equals (const Datum *dat) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
virtual void list (std::ostream &o, std::string prefix, int l) const
virtual void input_form (std::ostream &o) const
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Static Protected Attributes
static sli::pool memory
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
Additional Inherited Members
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Protected Attributes inherited from GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >
IteratorState d
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Constructor & Destructor Documentation
IteratorDatum::IteratorDatum () inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, IteratorState::di, IteratorState::pos, IteratorState::start, and IteratorState::stop.
Referenced by clone().
IteratorDatum::IteratorDatum (long start_s, long stop_s, long di_s) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, IteratorState::di, IteratorState::pos, IteratorState::start, and IteratorState::stop.
IteratorDatum::IteratorDatum (const IteratorDatum & d_s) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, and GenericDatum< D, slt >::d.
virtual IteratorDatum::~IteratorDatum () inline virtual
Member Function Documentation
long IteratorDatum::begin (void) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, and IteratorState::start.
Datum* IteratorDatum::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Reimplemented from GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >.
References IteratorDatum().
void IteratorDatum::decr (void) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, IteratorState::di, and IteratorState::pos.
long IteratorDatum::end (void) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, and IteratorState::stop.
Referenced by IforalliterFunction::execute().
void IteratorDatum::incr (void) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, IteratorState::di, and IteratorState::pos.
Referenced by IforalliterFunction::execute().
static void IteratorDatum::operator delete (void * p, size_t size) inline static
References sli::pool::free(), memory, nest::names::p, size(), and sli::pool::size_of().
static void* IteratorDatum::operator new (size_t size) inline static
References sli::pool::alloc(), memory, size(), and sli::pool::size_of().
bool IteratorDatum::operator== (const IteratorDatum & i) const inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, and GenericDatum< D, slt >::d.
long IteratorDatum::pos (void) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, and IteratorState::pos.
Referenced by IforalliterFunction::backtrace(), and IforalliterFunction::execute().
void IteratorDatum::pprint (std::ostream & out) const inline virtual
Implements Datum.
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d.
void IteratorDatum::print (std::ostream & out) const inline virtual
Implements Datum.
References Datum::gettypename().
long IteratorDatum::size (void) inline
References GenericDatum< IteratorState,&SLIInterpreter::Iteratortype >::d, IteratorState::di, and IteratorState::stop.
Referenced by operator delete(), and operator new().
Member Data Documentation
sli::pool IteratorDatum::memory static protected
Referenced by operator delete(), and operator new().
The documentation for this class was generated from the following files:
iteratordatum.h
iteratordatum.cc