NEST: RandomNumbers::CreateRNGFunction Class Reference
RandomNumbers::CreateRNGFunction Class Reference
#include <random_numbers.h>
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void RandomNumbers::CreateRNGFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, getValue< long >(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push(), seed, and TokenStack::top().
The documentation for this class was generated from the following files:
random_numbers.h
random_numbers.cpp