NEST: ParserDatum Class Reference
ParserDatum Class Reference
#include <parserdatum.h>
Public Member Functions
ParserDatum (Scanner *s)
Public Member Functions inherited from AggregateDatum< Parser,&SLIInterpreter::Parsertype >
AggregateDatum ()
AggregateDatum (const AggregateDatum< Parser, slt > &d)
AggregateDatum (const Parser &c)
virtual ~AggregateDatum ()
bool equals (const Datum *dat) const
virtual void print (std::ostream &out) const
virtual void pprint (std::ostream &out) const
virtual void list (std::ostream &out, std::string prefix, int l) const
virtual void input_form (std::ostream &out) const
virtual void info (std::ostream &out) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Public Member Functions inherited from Parser
Parser (void)
Parser (std::istream &)
bool operator() (Token &)
bool readToken (std::istream &is, Token &t)
bool readSymbol (std::istream &is, Token &t)
Scanner const * scan (void) const
void clear_context ()
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
ParserDatum (void)
Additional Inherited Members
Static Public Member Functions inherited from AggregateDatum< Parser,&SLIInterpreter::Parsertype >
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Static Protected Attributes inherited from AggregateDatum< Parser,&SLIInterpreter::Parsertype >
static sli::pool memory
Constructor & Destructor Documentation
ParserDatum::ParserDatum (void) inline private
References Datum::set_executable().
Referenced by clone().
ParserDatum::ParserDatum (Scanner * s) inline
References Datum::set_executable().
Member Function Documentation
Datum* ParserDatum::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Reimplemented from AggregateDatum< Parser,&SLIInterpreter::Parsertype >.
References ParserDatum().
The documentation for this class was generated from the following file:
parserdatum.h