NEST: nest::QuotientParameter Class Reference
nest::QuotientParameter Class Reference
Parameter class representing the quotient of two parameters.
#include <parameter.h>
Public Member Functions
QuotientParameter (const Parameter &m1, const Parameter &m2)
Construct the quotient of the two given parameters.
QuotientParameter (const QuotientParameter &p)
Copy constructor.
~QuotientParameter ()
double_t raw_value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t raw_value (const Position< 3 > &p, librandom::RngPtr &rng) const
Raw value disregarding cutoff.
Parameter * clone () const
Clone method.
Public Member Functions inherited from nest::Parameter
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Protected Attributes
Parameter * parameter1_
Parameter * parameter2_
Detailed Description
Parameter class representing the quotient of two parameters.
Constructor & Destructor Documentation
nest::QuotientParameter::QuotientParameter (const Parameter & m1, const Parameter & m2) inline
Construct the quotient of the two given parameters.
Copies are made of the supplied Parameter objects.
Referenced by clone().
nest::QuotientParameter::QuotientParameter (const QuotientParameter & p) inline
Copy constructor.
nest::QuotientParameter::~QuotientParameter () inline
References parameter1_, and parameter2_.
Member Function Documentation
Parameter* nest::QuotientParameter::clone () const inline virtual
Clone method.
Returns
dynamically allocated copy of parameter object
Implements nest::Parameter.
References QuotientParameter().
double_t nest::QuotientParameter::raw_value (const Position< 2 > & p, librandom::RngPtr & rng) const inline virtual
Returns
the value of the product.
Reimplemented from nest::Parameter.
References parameter1_, parameter2_, and nest::Parameter::value().
double_t nest::QuotientParameter::raw_value (const Position< 3 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References parameter1_, parameter2_, and nest::Parameter::value().
Member Data Documentation
Parameter* nest::QuotientParameter::parameter1_ protected
Referenced by raw_value(), and ~QuotientParameter().
Parameter * nest::QuotientParameter::parameter2_ protected
Referenced by raw_value(), and ~QuotientParameter().
The documentation for this class was generated from the following file:
parameter.h