NEST: IforalliterFunction Class Reference
IforalliterFunction Class Reference
#include <slibuiltins.h>
Public Member Functions
IforalliterFunction ()
void execute (SLIInterpreter *) const
void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
Constructor & Destructor Documentation
IforalliterFunction::IforalliterFunction () inline
Member Function Documentation
void IforalliterFunction::backtrace (SLIInterpreter * , int) const virtual
Show stack backtrace information on error.
This function tries to extract and display useful information from the execution stack if an error occurs. This function should be implemented for all functions which store administrative information on the execution stack. Examples are: loops and procedure iterations. backtrace() is only called, if the interpreter flag show_backtrace is set.
Reimplemented from SLIFunction.
References Token::datum(), SLIInterpreter::EStack, TokenStack::pick(), and IteratorDatum::pos().
void IforalliterFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References Token::datum(), SLIInterpreter::dec_call_depth(), IteratorDatum::end(), SLIInterpreter::EStack, IteratorDatum::incr(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), IteratorDatum::pos(), Token::pprint(), TokenStack::push(), and SLIInterpreter::step_mode().
The documentation for this class was generated from the following files:
slibuiltins.h
slibuiltins.cc