NEST: nest::ConnectionGeneratorModule Class Reference
nest::ConnectionGeneratorModule Class Reference
#include <conngenmodule.h>
Classes
class CGConnect_cg_i_i_D_lFunction
class CGConnect_cg_iV_iV_D_lFunction
class CGNext_cgFunction
class CGParse_sFunction
class CGParseFile_sFunction
class CGSelectImplementation_s_sFunction
class CGSetMask_cg_iV_iVFunction
class CGStart_cgFunction
Public Member Functions
ConnectionGeneratorModule (Network &)
~ConnectionGeneratorModule ()
void init (SLIInterpreter *)
Initialize module by registering models with the network.
const std::string name () const
Return name of the module.
const std::string commandstring () const
Return sli command sequence to be executed for initialisation.
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Static Public Member Functions
static Network & get_network ()
Public Attributes
nest::ConnectionGeneratorModule::CGConnect_cg_i_i_D_lFunction cgconnect_cg_i_i_D_lfunction
nest::ConnectionGeneratorModule::CGConnect_cg_iV_iV_D_lFunction cgconnect_cg_iV_iV_D_lfunction
nest::ConnectionGeneratorModule::CGParse_sFunction cgparse_sfunction
nest::ConnectionGeneratorModule::CGParseFile_sFunction cgparsefile_sfunction
nest::ConnectionGeneratorModule::CGSelectImplementation_s_sFunction cgselectimplementation_s_sfunction
nest::ConnectionGeneratorModule::CGSetMask_cg_iV_iVFunction cgsetmask_cg_iV_iVfunction
nest::ConnectionGeneratorModule::CGStart_cgFunction cgstart_cgfunction
nest::ConnectionGeneratorModule::CGNext_cgFunction cgnext_cgfunction
Static Public Attributes
static SLIType ConnectionGeneratorType
Static Private Attributes
static Network * net_ = 0
Constructor & Destructor Documentation
nest::ConnectionGeneratorModule::ConnectionGeneratorModule (Network & net)
nest::ConnectionGeneratorModule::~ConnectionGeneratorModule ()
Member Function Documentation
const std::string nest::ConnectionGeneratorModule::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Reimplemented from SLIModule.
Network & nest::ConnectionGeneratorModule::get_network () inline static
References assert(), and net_.
Referenced by nest::cg_connect().
void nest::ConnectionGeneratorModule::init (SLIInterpreter * i) virtual
Initialize module by registering models with the network.
Parameters
SLIInterpreter* SLI interpreter, must know modeldict
Implements SLIModule.
References SLIInterpreter::createcommand(), and SLIInterpreter::datatypefunction.
const std::string nest::ConnectionGeneratorModule::name () const virtual
Return name of the module.
Implements SLIModule.
Member Data Documentation
nest::ConnectionGeneratorModule::CGConnect_cg_i_i_D_lFunction nest::ConnectionGeneratorModule::cgconnect_cg_i_i_D_lfunction
nest::ConnectionGeneratorModule::CGConnect_cg_iV_iV_D_lFunction nest::ConnectionGeneratorModule::cgconnect_cg_iV_iV_D_lfunction
nest::ConnectionGeneratorModule::CGNext_cgFunction nest::ConnectionGeneratorModule::cgnext_cgfunction
nest::ConnectionGeneratorModule::CGParse_sFunction nest::ConnectionGeneratorModule::cgparse_sfunction
nest::ConnectionGeneratorModule::CGParseFile_sFunction nest::ConnectionGeneratorModule::cgparsefile_sfunction
nest::ConnectionGeneratorModule::CGSelectImplementation_s_sFunction nest::ConnectionGeneratorModule::cgselectimplementation_s_sfunction
nest::ConnectionGeneratorModule::CGSetMask_cg_iV_iVFunction nest::ConnectionGeneratorModule::cgsetmask_cg_iV_iVfunction
nest::ConnectionGeneratorModule::CGStart_cgFunction nest::ConnectionGeneratorModule::cgstart_cgfunction
SLIType nest::ConnectionGeneratorModule::ConnectionGeneratorType static
Network * nest::ConnectionGeneratorModule::net_ = 0 static private
net must be static, so that the execute() members of the SliFunction classes in the module can access the network.
Referenced by get_network().
The documentation for this class was generated from the following files:
conngenmodule.h
conngenmodule.cpp