NEST: nest::ConnectionCreator::PoolWrapper_< D > Class Template Reference
nest::ConnectionCreator::PoolWrapper_< D > Class Template Reference
Wrapper for masked and unmasked pools.
Public Member Functions
PoolWrapper_ ()
~PoolWrapper_ ()
void define (MaskedLayer< D > *)
void define (std::vector< std::pair< Position< D >, index > > *)
Ntree< D, index >::masked_iterator masked_begin (const Position< D > &pos) const
Ntree< D, index >::masked_iterator masked_end () const
std::vector< std::pair
< Position< D >, index >
>::iterator begin () const
std::vector< std::pair
< Position< D >, index >
>::iterator end () const
Private Attributes
MaskedLayer< D > * masked_layer_
std::vector< std::pair
< Position< D >, index > > * positions_
Detailed Description
template<int D>
class nest::ConnectionCreator::PoolWrapper_< D >
Wrapper for masked and unmasked pools.
The purpose is to avoid code doubling for cases with and without masks. Essentially, the class works as a fancy union.
Constructor & Destructor Documentation
template<int D> nest::ConnectionCreator::PoolWrapper_< D >::PoolWrapper_ ()
template<int D> nest::ConnectionCreator::PoolWrapper_< D >::~PoolWrapper_ ()
Member Function Documentation
template<int D> std::vector< std::pair< Position< D >, index > >::iterator nest::ConnectionCreator::PoolWrapper_< D >::begin (void) const
Referenced by nest::ConnectionCreator::target_driven_connect_().
template<int D> void nest::ConnectionCreator::PoolWrapper_< D >::define (MaskedLayer< D > * ml)
References assert().
Referenced by nest::ConnectionCreator::target_driven_connect_().
template<int D> void nest::ConnectionCreator::PoolWrapper_< D >::define (std::vector< std::pair< Position< D >, index > > * pos)
References assert().
template<int D> std::vector< std::pair< Position< D >, index > >::iterator nest::ConnectionCreator::PoolWrapper_< D >::end (void) const
Referenced by nest::ConnectionCreator::target_driven_connect_().
template<int D> Ntree< D, index >::masked_iterator nest::ConnectionCreator::PoolWrapper_< D >::masked_begin (const Position< D > & pos) const
Referenced by nest::ConnectionCreator::target_driven_connect_().
template<int D> Ntree< D, index >::masked_iterator nest::ConnectionCreator::PoolWrapper_< D >::masked_end () const
Referenced by nest::ConnectionCreator::target_driven_connect_().
Member Data Documentation
template<int D> MaskedLayer<D>* nest::ConnectionCreator::PoolWrapper_< D >::masked_layer_ private
template<int D> std::vector<std::pair<Position<D>,index> >* nest::ConnectionCreator::PoolWrapper_< D >::positions_ private
The documentation for this class was generated from the following files:
connection_creator.h
connection_creator_impl.h