NEST: nest::TsodyksConnection< targetidentifierT > Class Template Reference
nest::TsodyksConnection< targetidentifierT > Class Template Reference
#include <tsodyks_connection.h>
Classes
class ConnTestDummyNode
Public Types
typedef CommonSynapseProperties CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
TsodyksConnection ()
Default Constructor.
TsodyksConnection (const TsodyksConnection &)
Copy constructor from a property object.
~TsodyksConnection ()
Default Destructor.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t t_lastspike, const CommonSynapseProperties &cp)
Send an event to the receiver of this connection.
void check_connection (Node &s, Node &t, rport receptor_type, double_t, const CommonPropertiesType &)
void set_weight (double_t w)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Attributes
double_t weight_
double_t tau_psc_
[ms] time constant of postsyn current
double_t tau_fac_
[ms] time constant for fascilitation
double_t tau_rec_
[ms] time constant for recovery
double_t U_
asymptotic value of probability of release
double_t x_
amount of resources in recovered state
double_t y_
amount of resources in active state
double_t u_
actual probability of release
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Member Typedef Documentation
template<typename targetidentifierT > typedef CommonSynapseProperties nest::TsodyksConnection< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::TsodyksConnection< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::TsodyksConnection< targetidentifierT >::TsodyksConnection ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::TsodyksConnection< targetidentifierT >::TsodyksConnection (const TsodyksConnection< targetidentifierT > & rhs)
Copy constructor from a property object.
Needs to be defined properly in order for GenericConnector to work.
template<typename targetidentifierT > nest::TsodyksConnection< targetidentifierT >::~TsodyksConnection () inline
Default Destructor.
Member Function Documentation
template<typename targetidentifierT > void nest::TsodyksConnection< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t , const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_().
template<typename targetidentifierT > void nest::TsodyksConnection< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, nest::names::size_of, and nest::names::weight.
template<typename targetidentifierT > void nest::TsodyksConnection< targetidentifierT >::send (Event & e, thread t, double_t t_lastspike, const CommonSynapseProperties & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
t_lastspike Point in time of last spike sent.
cp Common properties to all synapses (empty).
e The event to send
p The port under which this connection is stored in the Connector.
t_lastspike Time point of last spike emitted
References numerics::e, nest::Time::get_ms(), nest::Event::get_stamp(), nest::names::h, nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), nest::Event::set_weight(), and nest::names::target.
template<typename targetidentifierT > void nest::TsodyksConnection< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties of this connection from the values given in dictionary.
References nest::names::d, nest::names::weight, nest::names::x, and nest::names::y.
template<typename targetidentifierT > void nest::TsodyksConnection< targetidentifierT >::set_weight (double_t w) inline
References nest::names::w, and nest::TsodyksConnection< targetidentifierT >::weight_.
Member Data Documentation
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::tau_fac_ private
[ms] time constant for fascilitation
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::tau_psc_ private
[ms] time constant of postsyn current
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::tau_rec_ private
[ms] time constant for recovery
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::U_ private
asymptotic value of probability of release
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::u_ private
actual probability of release
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::weight_ private
Referenced by nest::TsodyksConnection< targetidentifierT >::set_weight().
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::x_ private
amount of resources in recovered state
template<typename targetidentifierT > double_t nest::TsodyksConnection< targetidentifierT >::y_ private
amount of resources in active state
The documentation for this class was generated from the following file:
tsodyks_connection.h