NEST: nest::correlation_detector Class Reference
nest::correlation_detector Class Reference
Correlation detector class.
#include <correlation_detector.h>
Classes
struct Parameters_
struct Spike_
Spike structure to store in the deque of recently received events.
struct State_
Public Member Functions
correlation_detector ()
correlation_detector (const correlation_detector &)
bool has_proxies () const
This device has proxies, so that it will receive spikes also from sources which live on other threads.
void handle (SpikeEvent &)
port handles_test_event (SpikeEvent &, rport)
Check if the node can handle a particular event and receptor type.
void get_status (DictionaryDatum &) const
void set_status (const DictionaryDatum &)
Public Member Functions inherited from nest::Node
Node ()
Node (Node const &)
virtual ~Node ()
virtual Node * clone () const
Virtual copy constructor.
virtual bool potential_global_receiver () const
Returns true for potential global receivers (e.g.
virtual void set_has_proxies (const bool)
Sets has_proxies_ member variable (to switch to global spike detection mode)
virtual void set_local_receiver (const bool)
Sets local_receiver_ member variable (to switch to global spike detection mode)
virtual bool local_receiver () const
Returns true if the node only receives events from nodes/devices on the same thread.
virtual bool one_node_per_process () const
Returns true if the node exists only once per process, but does not have proxies on remote threads.
virtual bool is_off_grid () const
Returns true if the node if it sends/receives -grid events This is used to discriminate between different types of nodes, when adding new nodes to the network.
virtual bool is_proxy () const
Returns true if the node is a proxy node.
std::string get_name () const
Return class name.
index get_gid () const
Return global Network ID.
index get_lid () const
Return local node ID.
index get_subnet_index () const
Return the index to the node in the node array of the parent subnet.
int get_model_id () const
Return model ID of the node.
Subnet * get_parent () const
Return pointer to parent subnet.
virtual std::string print_network (int, int, std::string="")
Prints out one line of the tree view of the network.
bool is_frozen () const
Returns true if node is frozen, i.e., shall not be updated.
bool is_local () const
Returns true if the node is allocated in the local process.
void init_state ()
Set state variables to the default values for the model.
void init_buffers ()
Initialize buffers of a node.
virtual void finalize ()
Finalize node.
virtual void set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
virtual port send_test_event (Node &receiving_node, rport receptor_type, synindex syn_id, bool dummy_target)
Send an event to the receiving_node passed as an argument.
virtual port handles_test_event (RateEvent &, rport receptor_type)
virtual port handles_test_event (DataLoggingRequest &, rport receptor_type)
virtual port handles_test_event (CurrentEvent &, rport receptor_type)
virtual port handles_test_event (ConductanceEvent &, rport receptor_type)
virtual port handles_test_event (DoubleDataEvent &, rport receptor_type)
virtual port handles_test_event (DSSpikeEvent &, rport receptor_type)
virtual port handles_test_event (DSCurrentEvent &, rport receptor_type)
virtual void register_stdp_connection (double_t)
Register a STDP connection.
virtual void unregister_stdp_connection (double_t)
Unregister a STDP connection.
virtual void handle (RateEvent &e)
Handler for rate events.
virtual void handle (DataLoggingRequest &e)
Handler for universal data logging request.
virtual void handle (DataLoggingReply &e)
Handler for universal data logging request.
virtual void handle (CurrentEvent &e)
Handler for current events.
virtual void handle (ConductanceEvent &e)
Handler for conductance events.
virtual void handle (DoubleDataEvent &e)
Handler for DoubleData events.
virtual double_t get_K_value (double_t t)
return the Kminus value at t (in ms).
virtual void get_K_values (double_t t, double_t &Kminus, double_t &triplet_Kminus)
write the Kminus and triplet_Kminus values at t (in ms) to the provided locations.
virtual void get_history (double_t t1, double_t t2, std::deque< histentry >::iterator *start, std::deque< histentry >::iterator *finish)
return the spike history for (t1,t2].
virtual void event_hook (DSSpikeEvent &)
Modify Event object parameters during event delivery.
virtual void event_hook (DSCurrentEvent &)
void set_thread (thread)
Store the number of the thread to which the node is assigned.
thread get_thread () const
Retrieve the number of the thread to which the node is assigned.
void set_vp (thread)
Store the number of the virtual process to which the node is assigned.
thread get_vp () const
Retrieve the number of the virtual process to which the node is assigned.
void set_model_id (int)
Set the model id.
virtual bool is_subnet () const
DictionaryDatum get_status_base ()
Return a dictionary with the node's properties.
void set_status_base (const DictionaryDatum &)
Set status dictionary of a node.
bool is_model_prototype () const
Returns true if node is model prototype.
void set_thread_lid (const index)
set thread local index
index get_thread_lid () const
get thread local index
bool buffers_initialized () const
True if buffers have been initialized.
void set_buffers_initialized (bool initialized)
Private Types
typedef std::deque< Spike_ > SpikelistType
Private Member Functions
void init_state_ (Node const &)
Private function to initialize the state of a node to model defaults.
void init_buffers_ ()
Private function to initialize the buffers of a node.
void calibrate ()
Re-calculate dependent parameters of the node.
void update (Time const &, const long_t, const long_t)
Bring the node from state $t$ to $t+n*dt$.
Private Attributes
PseudoRecordingDevice device_
Parameters_ P_
State_ S_
Additional Inherited Members
Static Public Member Functions inherited from nest::Node
static Network * network ()
Return pointer to network driver class.
Protected Member Functions inherited from nest::Node
virtual size_t num_thread_siblings_ () const
Return the number of thread siblings in SiblingContainer.
virtual Node * get_thread_sibling_ (index) const
Return the specified member of a SiblingContainer.
virtual Node * get_thread_sibling_safe_ (index) const
Return specified member of a SiblingContainer, with access control.
Model & get_model_ () const
void set_frozen_ (bool frozen)
Mark node as frozen.
template<typename ConcreteNode >
const ConcreteNode & downcast (const Node &)
Auxiliary function to downcast a Node to a concrete class derived from Node.
Static Protected Attributes inherited from nest::Node
static Network * net_ =NULL
Pointer to global network driver.
Detailed Description
Correlation detector class.
Note
Correlation detectors IGNORE any connection delays.
Correlation detector breaks with the persistence scheme as follows: the internal buffers for storing spikes are part of State_, but are initialized by init_buffers_().
Todo:
The correlation detector could be made more efficient as follows (HEP 2008-07-01):
incoming_ is vector of two deques
let handle() push_back() entries in incoming_ and do nothing else
keep index to last "old spike" in each incoming_; cannot be iterator since that may change
update() deletes all entries before now-tau_max, sorts the new entries, then registers new entries in histogram
Member Typedef Documentation
typedef std::deque<Spike_> nest::correlation_detector::SpikelistType private
Constructor & Destructor Documentation
nest::correlation_detector::correlation_detector ()
References nest::names::delta_tau, nest::correlation_detector::Parameters_::delta_tau_, nest::Node::get_name(), nest::Time::is_step(), and P_.
nest::correlation_detector::correlation_detector (const correlation_detector & n)
References nest::names::delta_tau, nest::correlation_detector::Parameters_::delta_tau_, nest::Node::get_name(), nest::Time::is_step(), and P_.
Member Function Documentation
void nest::correlation_detector::calibrate () private virtual
Re-calculate dependent parameters of the node.
This function is called each time a simulation is begun/resumed. It must re-calculate all internal Variables of the node required for spike handling or updating the node.
Implements nest::Node.
void nest::correlation_detector::get_status (DictionaryDatum & d) const inline
References nest::names::element_type, and nest::names::recorder.
void nest::correlation_detector::handle (SpikeEvent & e) virtual
Todo:
implement if-else in term of function
Reimplemented from nest::Node.
References assert(), nest::SpikeEvent::get_multiplicity(), nest::Event::get_rport(), nest::Event::get_stamp(), nest::Time::get_steps(), nest::Event::get_weight(), nest::names::other, and nest::names::y.
port nest::correlation_detector::handles_test_event (SpikeEvent & , rport receptor_type) inline virtual
Check if the node can handle a particular event and receptor type.
This function is called upon connection setup by send_test_event().
handles_test_event() function is used to verify that the receiver can handle the event. It can also be used by the receiver to return information to the sender in form of the returned port. The default implementation throws an IllegalConnection exception. Any node class should define handles_test_event() functions for all those event types it can handle.
See Kunkel et al, Front Neuroinform 8:78 (2014), Sec 3.
Note
The semantics of all other handles_test_event() functions is identical.
Exceptions
IllegalConnection
Reimplemented from nest::Node.
References nest::Node::get_name(), and nest::names::receptor_type.
bool nest::correlation_detector::has_proxies () const inline virtual
This device has proxies, so that it will receive spikes also from sources which live on other threads.
Reimplemented from nest::Node.
void nest::correlation_detector::init_buffers_ () private virtual
Private function to initialize the buffers of a node.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the buffers of a node.
See also
Node::init_buffers()
Implements nest::Node.
void nest::correlation_detector::init_state_ (Node const &) private virtual
Private function to initialize the state of a node to model defaults.
This function, which must be overloaded by all derived classes, provides the implementation for initializing the state of a node to the model defaults; the state is the set of observable dynamic variables.
Parameters
Reference to model prototype object.
See also
Node::init_state()
Note
To provide a reasonable behavior during the transition to the new scheme, init_state_() has a default implementation calling init_dynamic_state_().
Implements nest::Node.
References device_, nest::Node::init_state(), and S_.
void nest::correlation_detector::set_status (const DictionaryDatum & d) inline
References nest::correlation_detector::Parameters_::set(), and nest::correlation_detector::State_::set().
void nest::correlation_detector::update (Time const & , const long_t , const long_t) private virtual
Bring the node from state $t$ to $t+n*dt$.
n->update(T, from, to) performs the update steps beginning at T+from .. T+to-1, ie, emitting events with time stamps T+from+1 .. T+to.
Parameters
Time network time at beginning of time slice.
long_t initial step inside time slice
long_t post-final step inside time slice
Implements nest::Node.
Member Data Documentation
PseudoRecordingDevice nest::correlation_detector::device_ private
Referenced by init_state_().
Parameters_ nest::correlation_detector::P_ private
Referenced by correlation_detector().
State_ nest::correlation_detector::S_ private
Referenced by init_state_().
The documentation for this class was generated from the following files:
correlation_detector.h
correlation_detector.cpp