NEST: nest::DynamicLoaderModule::LoadModuleFunction Class Reference
nest::DynamicLoaderModule::LoadModuleFunction Class Reference
#include <dynamicloader.h>
Public Member Functions
LoadModuleFunction (Network *pNet, vecDynModules &dyn_modules)
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Private Member Functions
void execute (SLIInterpreter *) const
Private Attributes
Network * pNet_
vecDynModules & dyn_modules_
Constructor & Destructor Documentation
nest::DynamicLoaderModule::LoadModuleFunction::LoadModuleFunction (Network * pNet, vecDynModules & dyn_modules)
Member Function Documentation
void nest::DynamicLoaderModule::LoadModuleFunction::execute (SLIInterpreter * i) const private virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), nest::names::c, DynModule::commandstring(), numerics::e, SLIInterpreter::EStack, nest::DynamicLoaderModule::getLinkedModules(), nest::sDynModule::handle, nest::has_name(), DynModule::install(), SLIInterpreter::M_INFO, SLIInterpreter::message(), nest::sDynModule::name, DynModule::name(), SLIInterpreter::OStack, nest::sDynModule::pModule, nest::DynamicLoaderModule::pNet_, TokenStack::pop(), TokenStack::push(), TokenStack::push_move(), and TokenStack::top().
Member Data Documentation
vecDynModules& nest::DynamicLoaderModule::LoadModuleFunction::dyn_modules_ private
Network* nest::DynamicLoaderModule::LoadModuleFunction::pNet_ private
The documentation for this class was generated from the following files:
dynamicloader.h
dynamicloader.cpp