NEST: nest::STDPDopaConnection< targetidentifierT > Class Template Reference
nest::STDPDopaConnection< targetidentifierT > Class Template Reference
Class representing an STDPDopaConnection with homogeneous parameters, i.e.
#include <stdp_dopa_connection.h>
Classes
class ConnTestDummyNode
Public Types
typedef STDPDopaCommonProperties CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
STDPDopaConnection ()
Default Constructor.
STDPDopaConnection (const STDPDopaConnection &)
Copy constructor from a property object.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t, const STDPDopaCommonProperties &cp)
Send an event to the receiver of this connection.
void trigger_update_weight (thread t, const vector< spikecounter > &dopa_spikes, double_t t_trig, const STDPDopaCommonProperties &cp)
void check_connection (Node &s, Node &t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType &cp)
void set_weight (double_t w)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Member Functions
void update_dopamine_ (const vector< spikecounter > &dopa_spikes, const STDPDopaCommonProperties &cp)
void update_weight_ (double_t c0, double_t n0, double_t minus_dt, const STDPDopaCommonProperties &cp)
void process_dopa_spikes_ (const vector< spikecounter > &dopa_spikes, double_t t0, double_t t1, const STDPDopaCommonProperties &cp)
void facilitate_ (double_t kplus, const STDPDopaCommonProperties &cp)
void depress_ (double_t kminus, const STDPDopaCommonProperties &cp)
Private Attributes
double_t weight_
double_t Kplus_
double_t c_
double_t n_
index dopa_spikes_idx_
double_t t_last_update_
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Detailed Description
template<typename targetidentifierT>
class nest::STDPDopaConnection< targetidentifierT >
Class representing an STDPDopaConnection with homogeneous parameters, i.e.
parameters are the same for all synapses.
Member Typedef Documentation
template<typename targetidentifierT > typedef STDPDopaCommonProperties nest::STDPDopaConnection< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::STDPDopaConnection< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::STDPDopaConnection< targetidentifierT >::STDPDopaConnection ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::STDPDopaConnection< targetidentifierT >::STDPDopaConnection (const STDPDopaConnection< targetidentifierT > & rhs)
Copy constructor from a property object.
Needs to be defined properly in order for GenericConnector to work.
Member Function Documentation
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t t_lastspike, const CommonPropertiesType & cp) inline
References nest::Connection< targetidentifierT >::check_connection_(), nest::Connection< targetidentifierT >::get_delay(), nest::Node::register_stdp_connection(), and nest::STDPDopaCommonProperties::vt_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::depress_ (double_t kminus, const STDPDopaCommonProperties & cp) inline private
References nest::STDPDopaCommonProperties::A_minus_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::facilitate_ (double_t kplus, const STDPDopaCommonProperties & cp) inline private
References nest::STDPDopaCommonProperties::A_plus_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, and nest::names::weight.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::process_dopa_spikes_ (const vector< spikecounter > & dopa_spikes, double_t t0, double_t t1, const STDPDopaCommonProperties & cp) inline private
References nest::STDPDopaCommonProperties::tau_c_, and nest::STDPDopaCommonProperties::tau_n_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::send (Event & e, thread t, double_t , const STDPDopaCommonProperties & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
e The event to send
p The port under which this connection is stored in the Connector.
t_lastspike Time point of last spike emitted
References nest::volume_transmitter::deliver_spikes(), numerics::e, nest::Node::get_history(), nest::Node::get_K_value(), nest::Time::get_ms(), nest::Event::get_stamp(), nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), nest::Event::set_weight(), nest::names::start, nest::names::t_spike, nest::names::target, nest::STDPDopaCommonProperties::tau_plus_, and nest::STDPDopaCommonProperties::vt_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties of this connection from the values given in dictionary.
References nest::names::d, and nest::names::weight.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::set_weight (double_t w) inline
References nest::names::w, and nest::STDPDopaConnection< targetidentifierT >::weight_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::trigger_update_weight (thread t, const vector< spikecounter > & dopa_spikes, double_t t_trig, const STDPDopaCommonProperties & cp) inline
References nest::names::start, nest::STDPDopaCommonProperties::tau_n_, and nest::STDPDopaCommonProperties::tau_plus_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::update_dopamine_ (const vector< spikecounter > & dopa_spikes, const STDPDopaCommonProperties & cp) inline private
References nest::STDPDopaCommonProperties::tau_n_.
template<typename targetidentifierT > void nest::STDPDopaConnection< targetidentifierT >::update_weight_ (double_t c0, double_t n0, double_t minus_dt, const STDPDopaCommonProperties & cp) inline private
References nest::STDPDopaCommonProperties::b_, numerics::expm1(), nest::STDPDopaCommonProperties::tau_c_, nest::STDPDopaCommonProperties::tau_n_, nest::STDPDopaCommonProperties::Wmax_, and nest::STDPDopaCommonProperties::Wmin_.
Member Data Documentation
template<typename targetidentifierT > double_t nest::STDPDopaConnection< targetidentifierT >::c_ private
template<typename targetidentifierT > index nest::STDPDopaConnection< targetidentifierT >::dopa_spikes_idx_ private
template<typename targetidentifierT > double_t nest::STDPDopaConnection< targetidentifierT >::Kplus_ private
template<typename targetidentifierT > double_t nest::STDPDopaConnection< targetidentifierT >::n_ private
template<typename targetidentifierT > double_t nest::STDPDopaConnection< targetidentifierT >::t_last_update_ private
template<typename targetidentifierT > double_t nest::STDPDopaConnection< targetidentifierT >::weight_ private
Referenced by nest::STDPDopaConnection< targetidentifierT >::set_weight().
The documentation for this class was generated from the following file:
stdp_dopa_connection.h