NEST: SLIgraphics::ReadPGMFunction Class Reference
SLIgraphics::ReadPGMFunction Class Reference
Public Member Functions
virtual void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Private Member Functions
std::istream * openPGMFile (StringDatum *) const
opens the file
void readMagicNumber (std::istream *, char[2]) const
reads the magic number into string magic
void initRead (std::istream *, int &, int &, int &) const
reads width, height, maxval
void readImage (std::istream *, char[2], vector< long > &, int, int, int) const
reads the image
Member Function Documentation
void SLIgraphics::ReadPGMFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::ArgumentTypeError, SLIInterpreter::BadIOError, Token::datum(), SLIInterpreter::EStack, initRead(), TokenStack::load(), SLIInterpreter::M_ERROR, SLIInterpreter::message(), openPGMFile(), SLIInterpreter::OStack, TokenStack::pop(), TokenStack::push(), SLIInterpreter::raiseerror(), readImage(), readMagicNumber(), SLIInterpreter::StackUnderflowError, and TokenStack::top().
void SLIgraphics::ReadPGMFunction::initRead (std::istream * in, int & width, int & height, int & maxval) const private
reads width, height, maxval
References numerics::e.
Referenced by execute().
std::istream * SLIgraphics::ReadPGMFunction::openPGMFile (StringDatum * filename) const private
opens the file
Referenced by execute().
void SLIgraphics::ReadPGMFunction::readImage (std::istream * in, char magic[2], vector< long > & image, int width, int height, int maxval) const private
reads the image
References numerics::e.
Referenced by execute().
void SLIgraphics::ReadPGMFunction::readMagicNumber (std::istream * , char [2]) const private
reads the magic number into string magic
References numerics::e.
Referenced by execute().
The documentation for this class was generated from the following files:
sligraphics.h
sligraphics.cc