NEST: librandom::PoissonRandomDev Class Reference
librandom::PoissonRandomDev Class Reference
Random Deviate Generators.
Class PoissonRandomDev Create Poisson distributed random numbers.
#include <poisson_randomdev.h>
Public Member Functions
PoissonRandomDev (RngPtr, double lambda=0.0)
PoissonRandomDev (double lambda=0.0)
void set_lambda (double)
void set_status (const DictionaryDatum &)
set distribution parameters from SLI dict
void get_status (DictionaryDatum &) const
get distribution parameters from SLI dict
long ldev (RngPtr) const
draw integer, threaded
bool has_ldev () const
true if RDG implements ldev function
double operator() (RngPtr) const
return as double, threaded
Public Member Functions inherited from librandom::RandomDev
RandomDev (RngPtr rng=RngPtr(0))
Construct with (single-threaded) or without (multithreaded) RNG.
virtual ~RandomDev ()
ensure proper clean-up
virtual double operator() (void)
Operator delivering doubles.
virtual long ldev (void)
integer valued functions for discrete distributions
void set_rng (RngPtr rng)
set RNG
Private Member Functions
void init_ ()
re-compute internal parameters
void proc_f_ (const unsigned k, double &px, double &py, double &fx, double &fy) const
Procedure F from Ahrens & Dieter.
Private Attributes
RngPtr r
double mu_
Poisson parameter, aka lambda.
double s_
sqrt(mu_)
double d_
6 mu_^2
unsigned long L_
floor(mu-1.1484)
double c_
0.1069 / mu_
double om_
double c0_
double c1_
double c2_
double c3_
std::vector< double > P_
PoissonCDF.
Static Private Attributes
static const unsigned n_tab_ = 46
tabulate P_0 ... P_{n_tab_-1}
static const unsigned fact_ []
array of factorials 0! .. 10!
static const double a_ []
array of a_i coeffs
static const unsigned n_a_ = 10
length of array
Additional Inherited Members
Protected Attributes inherited from librandom::RandomDev
RngPtr rng_
store underlying RNG
Detailed Description
Class PoissonRandomDev Create Poisson distributed random numbers.
Constructor & Destructor Documentation
librandom::PoissonRandomDev::PoissonRandomDev (RngPtr r_source, double lambda = 0.0)
References init_().
librandom::PoissonRandomDev::PoissonRandomDev (double lambda = 0.0)
References init_().
Member Function Documentation
void librandom::PoissonRandomDev::get_status (DictionaryDatum & d) const virtual
get distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::d.
bool librandom::PoissonRandomDev::has_ldev () const inline virtual
true if RDG implements ldev function
Reimplemented from librandom::RandomDev.
void librandom::PoissonRandomDev::init_ () private
re-compute internal parameters
References assert(), nest::names::min, nest::names::p, and numerics::pi.
Referenced by PoissonRandomDev().
long librandom::PoissonRandomDev::ldev (RngPtr r) const virtual
draw integer, threaded
Reimplemented from librandom::RandomDev.
References assert(), and lockPTR< D >::valid().
double librandom::PoissonRandomDev::operator() (RngPtr rthrd) const inline virtual
return as double, threaded
Implements librandom::RandomDev.
References librandom::RandomDev::ldev().
void librandom::PoissonRandomDev::proc_f_ (const unsigned k, double & px, double & py, double & fx, double & fy) const private
Procedure F from Ahrens & Dieter.
References numerics::pi.
void librandom::PoissonRandomDev::set_lambda (double lambda)
void librandom::PoissonRandomDev::set_status (const DictionaryDatum & d) virtual
set distribution parameters from SLI dict
Implements librandom::RandomDev.
References nest::names::max.
Member Data Documentation
const double librandom::PoissonRandomDev::a_ static private
Initial value:
= { -0.5000000002,
    0.3333333343,
    -0.2499998565,
    0.1999997049,
    -0.1666848753,
    0.1428833286,
    -0.1241963125,
    0.1101687109,
    -0.1142650302,
    0.1055093006
}
array of a_i coeffs
double librandom::PoissonRandomDev::c0_ private
double librandom::PoissonRandomDev::c1_ private
double librandom::PoissonRandomDev::c2_ private
double librandom::PoissonRandomDev::c3_ private
double librandom::PoissonRandomDev::c_ private
0.1069 / mu_
double librandom::PoissonRandomDev::d_ private
6 mu_^2
const unsigned librandom::PoissonRandomDev::fact_ static private
Initial value:
=
  { 1, 1, 2, 6, 24, 120, 720, 5040, 40320, 362880 }
array of factorials 0! .. 10!
unsigned long librandom::PoissonRandomDev::L_ private
floor(mu-1.1484)
double librandom::PoissonRandomDev::mu_ private
Poisson parameter, aka lambda.
const unsigned librandom::PoissonRandomDev::n_a_ = 10 static private
length of array
const unsigned librandom::PoissonRandomDev::n_tab_ = 46 static private
tabulate P_0 ... P_{n_tab_-1}
double librandom::PoissonRandomDev::om_ private
std::vector<double> librandom::PoissonRandomDev::P_ private
PoissonCDF.
RngPtr librandom::PoissonRandomDev::r private
double librandom::PoissonRandomDev::s_ private
sqrt(mu_)
The documentation for this class was generated from the following files:
poisson_randomdev.h
poisson_randomdev.cpp