NEST: nest::GenericModel< ElementT > Class Template Reference
nest::GenericModel< ElementT > Class Template Reference
Model developer interface.
Generic Model template.
#include <genericmodel.h>
Public Member Functions
GenericModel (const std::string &)
GenericModel (const char[])
GenericModel (const GenericModel &, const std::string &)
Create copy of model with new name.
Model * clone (const std::string &) const
Return pointer to cloned model with same name.
bool has_proxies ()
bool potential_global_receiver ()
bool one_node_per_process ()
bool is_off_grid ()
port send_test_event (Node &, rport, synindex, bool)
Node const & get_prototype () const
Return const reference to the prototype.
void set_model_id (int)
Set the model id on the prototype.
Public Member Functions inherited from nest::Model
Model (const std::string &name)
Model (const Model &m)
virtual ~Model ()
void set_threads ()
Set number of threads based on number set in network.
Node * allocate (thread t)
Allocate new Node and return its pointer.
void free (thread t, Node *)
void clear ()
Deletes all nodes which belong to this model.
void reserve_additional (thread t, size_t n)
Reserve memory for at least n additional Nodes.
std::string get_name () const
Return name of the Model.
size_t mem_available ()
Return the available memory.
size_t mem_capacity ()
Return the memory capacity.
void set_status (DictionaryDatum)
Change properties of the prototype node according to the entries in the dictionary.
DictionaryDatum get_status (void)
Export properties of the prototype node by setting entries in the status dictionary.
void set_type_id (index id)
Set the model id on the prototype.
index get_type_id () const
Private Member Functions
void set_status_ (DictionaryDatum)
DictionaryDatum get_status_ ()
size_t get_element_size () const
Return the size of the prototype.
Node * allocate_ (void *)
Call placement new on the supplied memory position.
void init_memory_ (sli::pool &)
Initialize the pool allocator with the node specific properties.
Private Attributes
ElementT proto_
Prototype node from which all instances are constructed.
Detailed Description
template<typename ElementT>
class nest::GenericModel< ElementT >
Generic Model template.
The template GenericModel should be used as base class for custom model classes. It already includes the element factory functionality, as well as a pool based memory manager, so that the user can concentrate on the "real" model aspects.
Constructor & Destructor Documentation
template<typename ElementT > nest::GenericModel< ElementT >::GenericModel (const std::string & name)
References nest::Model::set_threads().
template<typename ElementT > nest::GenericModel< ElementT >::GenericModel (const char name[])
References nest::Model::set_threads().
template<typename ElementT > nest::GenericModel< ElementT >::GenericModel (const GenericModel< ElementT > & oldmod, const std::string & newname)
Create copy of model with new name.
References nest::Model::get_type_id(), nest::Model::set_threads(), and nest::Model::set_type_id().
Member Function Documentation
template<typename ElementT > Node * nest::GenericModel< ElementT >::allocate_ (void * adr) private virtual
Call placement new on the supplied memory position.
Implements nest::Model.
References nest::names::n.
template<typename ElementT > Model * nest::GenericModel< ElementT >::clone (const std::string & newname) const virtual
Return pointer to cloned model with same name.
Implements nest::Model.
template<typename ElementT > size_t nest::GenericModel< ElementT >::get_element_size () const private virtual
Return the size of the prototype.
Implements nest::Model.
template<typename ElementT > Node const & nest::GenericModel< ElementT >::get_prototype () const virtual
Return const reference to the prototype.
Implements nest::Model.
template<typename ElementT > DictionaryDatum nest::GenericModel< ElementT >::get_status_ () private virtual
Implements nest::Model.
References nest::names::d.
template<typename ElementT > bool nest::GenericModel< ElementT >::has_proxies () inline virtual
Implements nest::Model.
template<typename ElementT > void nest::GenericModel< ElementT >::init_memory_ (sli::pool & mem) private virtual
Initialize the pool allocator with the node specific properties.
Implements nest::Model.
References sli::pool::init().
template<typename ElementT > bool nest::GenericModel< ElementT >::is_off_grid () inline virtual
Implements nest::Model.
template<typename ElementT > bool nest::GenericModel< ElementT >::one_node_per_process () inline virtual
Implements nest::Model.
template<typename ElementT > bool nest::GenericModel< ElementT >::potential_global_receiver () inline virtual
Implements nest::Model.
template<typename ElementT > port nest::GenericModel< ElementT >::send_test_event (Node & target, rport receptor, synindex syn_id, bool dummy_target) inline virtual
Note
The decision of whether one node can receive a certain event was originally in the node. But in the distributed case, it may be that you only have a proxy node and not he real thing. Thus, you need to be able to make this decision without having the node. Since the model now takes responsibility for a lot of general node properties, it was a natural place to put this function.
Model::send_test_event() is a forwarding function that calls send_test_event() from the prototype. Since proxies know the model they represent, they can now answer a call to check connection by referring back to the model.
Implements nest::Model.
template<typename ElementT > void nest::GenericModel< ElementT >::set_model_id (int) virtual
Set the model id on the prototype.
Implements nest::Model.
template<typename ElementT > void nest::GenericModel< ElementT >::set_status_ (DictionaryDatum d) private virtual
Implements nest::Model.
Member Data Documentation
template<typename ElementT> ElementT nest::GenericModel< ElementT >::proto_ private
Prototype node from which all instances are constructed.
The documentation for this class was generated from the following file:
genericmodel.h