NEST: Forallindexed_aFunction Class Reference
Forallindexed_aFunction Class Reference
#include <slicontrol.h>
Public Member Functions
Forallindexed_aFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
Forallindexed_aFunction::Forallindexed_aFunction () inline
Member Function Documentation
void Forallindexed_aFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References ad, assert(), SLIInterpreter::baselookup(), Token::datum(), SLIInterpreter::EStack, SLIInterpreter::iforallindexedarray_name, SLIInterpreter::inc_call_depth(), SLIInterpreter::mark_name, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push(), TokenStack::push_move(), TokenArray::size(), and TokenStack::top().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc