NEST: TokenArrayObj Class Reference
TokenArrayObj Class Reference
#include <tarrayobj.h>
Public Member Functions
TokenArrayObj (void)
TokenArrayObj (size_t, const Token &=Token(), size_t=0)
TokenArrayObj (const TokenArrayObj &)
virtual ~TokenArrayObj ()
Token * begin () const
Token * end () const
size_t size (void) const
size_t capacity (void) const
Token & operator[] (size_t i)
const Token & operator[] (size_t i) const
const Token & get (long i) const
bool index_is_valid (long i) const
void rotate (Token *, Token *, Token *)
bool shrink (void)
bool reserve (size_t)
unsigned int references (void)
unsigned int remove_reference ()
unsigned int add_reference ()
void resize (size_t, size_t, const Token &=Token())
void resize (size_t, const Token &=Token())
void reserve_token (size_t n)
void push_back (const Token &t)
void push_back_move (Token &t)
void push_back_by_ref (const Token &t)
Push back a reference.
void push_back_by_pointer (Datum *rhs)
Push back a datum pointer.
void assign_move (Token *tp, Token &t)
void pop_back (void)
void erase (size_t, size_t)
void erase (Token *, Token *)
void erase (Token *tp)
void reduce (Token *, Token *)
void reduce (size_t, size_t)
void insert (size_t, size_t=1, const Token &=Token())
void insert (size_t i, const Token &t)
void insert_move (size_t, TokenArrayObj &)
void insert_move (size_t, Token &)
void assign_move (TokenArrayObj &, size_t, size_t)
void assign (const TokenArrayObj &, size_t, size_t)
void replace_move (size_t, size_t, TokenArrayObj &)
void append_move (TokenArrayObj &)
void clear (void)
const TokenArrayObj & operator= (const TokenArrayObj &)
bool operator== (const TokenArrayObj &) const
bool empty (void) const
void info (std::ostream &) const
bool valid (void) const
Static Public Member Functions
static size_t getallocations (void)
Private Member Functions
void allocate (size_t, size_t, size_t, const Token &=Token())
Private Attributes
Token * p
Token * begin_of_free_storage
Token * end_of_free_storage
unsigned int alloc_block_size
unsigned int refs_
Static Private Attributes
static size_t allocations =0
Constructor & Destructor Documentation
TokenArrayObj::TokenArrayObj (void) inline
TokenArrayObj::TokenArrayObj (size_t s, const Token & t = Token(), size_t alloc = 0)
References nest::names::a, and resize().
TokenArrayObj::TokenArrayObj (const TokenArrayObj & a)
References alloc_block_size, begin_of_free_storage, p, resize(), and size().
TokenArrayObj::~TokenArrayObj () virtual
References p.
Member Function Documentation
unsigned int TokenArrayObj::add_reference () inline
References refs_.
Referenced by TokenArray::operator=(), and TokenArray::TokenArray().
void TokenArrayObj::allocate (size_t new_s, size_t new_c, size_t new_a, const Token & t = Token()) private
References alloc_block_size, allocations, assert(), begin_of_free_storage, end_of_free_storage, nest::names::h, p, and size().
Referenced by reserve(), resize(), and shrink().
void TokenArrayObj::append_move (TokenArrayObj & a)
References assert(), begin_of_free_storage, end(), end_of_free_storage, p, reserve(), and size().
Referenced by TokenArray::append_move().
void TokenArrayObj::assign (const TokenArrayObj & a, size_t i, size_t n)
References begin(), begin_of_free_storage, end(), nest::names::n, p, and reserve().
Referenced by TokenArray::assign_move().
void TokenArrayObj::assign_move (Token * tp, Token & t) inline
Referenced by TokenArray::assign_move().
void TokenArrayObj::assign_move (TokenArrayObj & a, size_t i, size_t n)
References begin(), begin_of_free_storage, end(), nest::names::n, p, and reserve().
Token* TokenArrayObj::begin (void) const inline
References p.
Referenced by assign(), assign_move(), TokenArray::assign_move(), TokenArray::begin(), TokenStack::clear(), TokenArray::erase(), operator<<(), operator=(), operator==(), reduce(), replace_move(), and TokenArray::rotate().
size_t TokenArrayObj::capacity (void) const inline
References end_of_free_storage, and p.
Referenced by TokenArray::capacity(), operator=(), push_back(), push_back_by_pointer(), push_back_by_ref(), push_back_move(), reserve(), reserve_token(), shrink(), and TokenStack::size().
void TokenArrayObj::clear (void)
References alloc_block_size, begin_of_free_storage, end_of_free_storage, and p.
Referenced by pop_back().
bool TokenArrayObj::empty (void) const inline
References size().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_10pop(), and Parser::operator()().
Token* TokenArrayObj::end (void) const inline
References begin_of_free_storage.
Referenced by append_move(), assign(), assign_move(), TokenStack::clear(), TokenArray::end(), erase(), insert_move(), operator<<(), operator=(), operator==(), TokenStack::pick(), TokenStack::pop(), TokenStack::pop_move(), reduce(), replace_move(), TokenStack::roll(), TokenStack::swap(), and TokenStack::top().
void TokenArrayObj::erase (size_t i, size_t n)
References p, and size().
Referenced by TokenStack::clear(), erase(), TokenArray::erase(), and TokenStack::pop().
void TokenArrayObj::erase (Token * first, Token * last)
References begin_of_free_storage, end(), and Datum::removeReference().
void TokenArrayObj::erase (Token * tp) inline
References erase().
const Token& TokenArrayObj::get (long i) const inline
References p.
Referenced by TokenArray::get().
static size_t TokenArrayObj::getallocations (void) inline static
References allocations.
Referenced by Allocations_aFunction::execute().
bool TokenArrayObj::index_is_valid (long i) const inline
References begin_of_free_storage, and p.
Referenced by TokenArray::index_is_valid().
void TokenArrayObj::info (std::ostream & out) const
References alloc_block_size, begin_of_free_storage, end_of_free_storage, and p.
void TokenArrayObj::insert (size_t i, size_t n = 1, const Token & t = Token())
References begin_of_free_storage, nest::names::n, p, reserve(), and size().
Referenced by insert().
void TokenArrayObj::insert (size_t i, const Token & t) inline
References insert().
void TokenArrayObj::insert_move (size_t i, TokenArrayObj & a)
References assert(), begin_of_free_storage, end(), end_of_free_storage, p, reserve(), and size().
Referenced by TokenArray::insert_move().
void TokenArrayObj::insert_move (size_t i, Token & t)
References assert(), begin_of_free_storage, end_of_free_storage, p, Token::p, reserve(), and size().
const TokenArrayObj & TokenArrayObj::operator= (const TokenArrayObj & a)
References alloc_block_size, assert(), begin(), begin_of_free_storage, capacity(), end(), end_of_free_storage, p, resize(), and size().
bool TokenArrayObj::operator== (const TokenArrayObj & a) const
References begin(), end(), p, and size().
Token& TokenArrayObj::operator[] (size_t i) inline
References p.
const Token& TokenArrayObj::operator[] (size_t i) const inline
References p.
void TokenArrayObj::pop_back (void) inline
References begin_of_free_storage, and clear().
Referenced by TokenStack::pop(), TokenArray::pop_back(), and TokenStack::pop_move().
void TokenArrayObj::push_back (const Token & t) inline
References alloc_block_size, begin_of_free_storage, capacity(), reserve(), and size().
Referenced by TokenStack::push(), and TokenArray::push_back().
void TokenArrayObj::push_back_by_pointer (Datum * rhs) inline
Push back a datum pointer.
This function assumes that enough space on the stack has been reserved. This function expects a valid datum pointer and increases the reference count of the datum.
References alloc_block_size, begin_of_free_storage, capacity(), reserve(), and size().
Referenced by TokenStack::push_by_pointer().
void TokenArrayObj::push_back_by_ref (const Token & t) inline
Push back a reference.
This function expects that enough space on the stack has been reserved and that the token points to a valid datum object.
References alloc_block_size, begin_of_free_storage, capacity(), reserve(), and size().
Referenced by TokenStack::push_by_ref().
void TokenArrayObj::push_back_move (Token & t) inline
References alloc_block_size, begin_of_free_storage, capacity(), reserve(), and size().
Referenced by TokenArray::push_back(), TokenArray::push_back_dont_clone(), TokenArray::push_back_move(), and TokenStack::push_move().
void TokenArrayObj::reduce (Token * first, Token * last)
References assert(), begin(), begin_of_free_storage, end(), and p.
Referenced by reduce(), and TokenArray::reduce().
void TokenArrayObj::reduce (size_t i, size_t n)
References p, reduce(), and size().
unsigned int TokenArrayObj::references (void) inline
References refs_.
Referenced by TokenArray::clone(), TokenArray::detach(), and TokenArray::references().
unsigned int TokenArrayObj::remove_reference () inline
References refs_.
Referenced by TokenArray::clone(), TokenArray::detach(), TokenArray::operator=(), and TokenArray::~TokenArray().
void TokenArrayObj::replace_move (size_t i, size_t n, TokenArrayObj & a)
References assert(), begin(), begin_of_free_storage, nest::names::d, end(), nest::names::n, p, Datum::removeReference(), reserve(), and size().
Referenced by TokenArray::replace_move().
bool TokenArrayObj::reserve (size_t new_capacity)
References alloc_block_size, allocate(), capacity(), and size().
Referenced by append_move(), assign(), assign_move(), insert(), insert_move(), push_back(), push_back_by_pointer(), push_back_by_ref(), push_back_move(), replace_move(), TokenArray::reserve(), and reserve_token().
void TokenArrayObj::reserve_token (size_t n) inline
References capacity(), reserve(), and size().
Referenced by SLIArrayModule::ArrayloadFunction::execute().
void TokenArrayObj::resize (size_t s, size_t alloc, const Token & t = Token())
References alloc_block_size, allocate(), and size().
Referenced by operator=(), resize(), TokenArray::resize(), and TokenArrayObj().
void TokenArrayObj::resize (size_t s, const Token & t = Token())
References alloc_block_size, and resize().
void TokenArrayObj::rotate (Token * first, Token * middle, Token * last)
Referenced by TokenStack::roll(), and TokenArray::rotate().
bool TokenArrayObj::shrink (void)
References alloc_block_size, allocate(), capacity(), and size().
Referenced by TokenArray::shrink().
size_t TokenArrayObj::size (void) const inline
References begin_of_free_storage, and p.
Referenced by allocate(), append_move(), empty(), erase(), insert(), insert_move(), TokenStack::load(), operator=(), operator==(), push_back(), push_back_by_pointer(), push_back_by_ref(), push_back_move(), reduce(), replace_move(), reserve(), reserve_token(), resize(), shrink(), TokenArray::size(), and TokenArrayObj().
bool TokenArrayObj::valid (void) const
References begin_of_free_storage, end_of_free_storage, and p.
Referenced by TokenArray::valid().
Member Data Documentation
unsigned int TokenArrayObj::alloc_block_size private
Referenced by allocate(), clear(), info(), operator=(), push_back(), push_back_by_pointer(), push_back_by_ref(), push_back_move(), reserve(), resize(), shrink(), and TokenArrayObj().
size_t TokenArrayObj::allocations =0 static private
Referenced by allocate(), and getallocations().
Token* TokenArrayObj::begin_of_free_storage private
Referenced by allocate(), append_move(), assign(), assign_move(), clear(), end(), erase(), index_is_valid(), info(), insert(), insert_move(), operator=(), pop_back(), push_back(), push_back_by_pointer(), push_back_by_ref(), push_back_move(), reduce(), replace_move(), size(), TokenArrayObj(), and valid().
Token* TokenArrayObj::end_of_free_storage private
Referenced by allocate(), append_move(), capacity(), clear(), info(), insert_move(), operator=(), and valid().
Token* TokenArrayObj::p private
Referenced by allocate(), append_move(), assign(), assign_move(), begin(), capacity(), clear(), erase(), get(), index_is_valid(), info(), insert(), insert_move(), operator=(), operator==(), operator[](), reduce(), replace_move(), size(), TokenArrayObj(), valid(), and ~TokenArrayObj().
unsigned int TokenArrayObj::refs_ private
Referenced by add_reference(), references(), and remove_reference().
The documentation for this class was generated from the following files:
tarrayobj.h
tarrayobj.cc