NEST: nest::ContDelayConnection< targetidentifierT > Class Template Reference
nest::ContDelayConnection< targetidentifierT > Class Template Reference
#include <cont_delay_connection.h>
Classes
class ConnTestDummyNode
Public Types
typedef CommonSynapseProperties CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
ContDelayConnection ()
Default Constructor.
ContDelayConnection (const ContDelayConnection &)
Copy constructor.
~ContDelayConnection ()
Default Destructor.
void set_weight (double_t w)
Used by ConnectorModel::add_connection() for fast initialization.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t t_lastspike, const CommonSynapseProperties &cp)
Send an event to the receiver of this connection.
void check_connection (Node &s, Node &t, rport receptor_type, double_t, const CommonPropertiesType &)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Attributes
double_t weight_
synaptic weight
double_t delay_offset_
fractional delay < h, total delay = delay_ - delay_offset_
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Member Typedef Documentation
template<typename targetidentifierT > typedef CommonSynapseProperties nest::ContDelayConnection< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::ContDelayConnection< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::ContDelayConnection< targetidentifierT >::ContDelayConnection ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::ContDelayConnection< targetidentifierT >::ContDelayConnection (const ContDelayConnection< targetidentifierT > & rhs)
Copy constructor.
Needs to be defined properly in order for GenericConnector to work.
template<typename targetidentifierT > nest::ContDelayConnection< targetidentifierT >::~ContDelayConnection () inline
Default Destructor.
Member Function Documentation
template<typename targetidentifierT > void nest::ContDelayConnection< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t , const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_().
template<typename targetidentifierT > void nest::ContDelayConnection< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::d, nest::names::delay, nest::Time::get_ms(), and nest::names::weight.
template<typename targetidentifierT > void nest::ContDelayConnection< targetidentifierT >::send (Event & e, thread t, double_t t_lastspike, const CommonSynapseProperties & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
t_lastspike Point in time of last spike sent.
cp common properties of all synapses (empty).
e The event to send
p The port under which this connection is stored in the Connector.
t_lastspike Time point of last spike emitted
References numerics::e, nest::Event::get_offset(), nest::Time::get_resolution(), nest::Event::set_delay(), nest::Event::set_offset(), nest::Event::set_receiver(), nest::Event::set_rport(), and nest::Event::set_weight().
template<typename targetidentifierT > void nest::ContDelayConnection< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties of this connection from the values given in dictionary.
References nest::ConnectorModel::assert_two_valid_delays_steps(), nest::ConnectorModel::assert_valid_delay_ms(), nest::names::d, nest::names::delay, nest::Time::delay_ms_to_steps(), nest::Time::get_ms(), nest::Time::get_resolution(), nest::names::h, and nest::names::weight.
template<typename targetidentifierT > void nest::ContDelayConnection< targetidentifierT >::set_weight (double_t w) inline
Used by ConnectorModel::add_connection() for fast initialization.
References nest::names::w, and nest::ContDelayConnection< targetidentifierT >::weight_.
Member Data Documentation
template<typename targetidentifierT > double_t nest::ContDelayConnection< targetidentifierT >::delay_offset_ private
fractional delay < h, total delay = delay_ - delay_offset_
template<typename targetidentifierT > double_t nest::ContDelayConnection< targetidentifierT >::weight_ private
synaptic weight
Referenced by nest::ContDelayConnection< targetidentifierT >::set_weight().
The documentation for this class was generated from the following files:
cont_delay_connection.h
cont_delay_connection_impl.h