NEST: librandom::RandomDev Class Reference
librandom::RandomDev Class Reference abstract
Abstract base class for access to non-uniform random deviate generators.
#include <randomdev.h>
Public Member Functions
RandomDev (RngPtr rng=RngPtr(0))
Construct with (single-threaded) or without (multithreaded) RNG.
virtual ~RandomDev ()
ensure proper clean-up
virtual double operator() (void)
Operator delivering doubles.
virtual double operator() (RngPtr) const =0
multi-threaded
virtual long ldev (void)
integer valued functions for discrete distributions
virtual long ldev (RngPtr) const
virtual bool has_ldev () const
true if RDG implements ldev function
void set_rng (RngPtr rng)
set RNG
virtual void set_status (const DictionaryDatum &)=0
set distribution parameters from SLI interface
virtual void get_status (DictionaryDatum &) const =0
get distribution parameters from SLI interface
Protected Attributes
RngPtr rng_
store underlying RNG
Detailed Description
Abstract base class for access to non-uniform random deviate generators.
See also
RandomGen
HEP 2002-07-09, 2004-06-28
Constructor & Destructor Documentation
librandom::RandomDev::RandomDev (RngPtr rng = RngPtr(0)) inline
Construct with (single-threaded) or without (multithreaded) RNG.
virtual librandom::RandomDev::~RandomDev () inline virtual
ensure proper clean-up
Member Function Documentation
virtual void librandom::RandomDev::get_status (DictionaryDatum &) const pure virtual
get distribution parameters from SLI interface
Note
RDGs with parameters will usually implement functions to manipulate the parameters directly, without use of a SLI dictionary. This function is meant only to provide access from the SLI interface.
Implemented in librandom::BinomialRandomDev, librandom::PoissonRandomDev, librandom::GSL_BinomialRandomDev, librandom::GammaRandomDev, librandom::UniformIntRandomDev, librandom::UniformRandomDev, librandom::LognormalRandomDev, librandom::NormalRandomDev, and librandom::ExpRandomDev.
virtual bool librandom::RandomDev::has_ldev () const inline virtual
true if RDG implements ldev function
Reimplemented in librandom::PoissonRandomDev, librandom::BinomialRandomDev, librandom::GSL_BinomialRandomDev, and librandom::UniformIntRandomDev.
long librandom::RandomDev::ldev (void) inline virtual
integer valued functions for discrete distributions
Reimplemented in librandom::GSL_BinomialRandomDev.
References assert(), rng_, and lockPTR< D >::valid().
Referenced by librandom::UniformIntRandomDev::operator()(), librandom::BinomialRandomDev::operator()(), and librandom::PoissonRandomDev::operator()().
long librandom::RandomDev::ldev (RngPtr) const virtual
Reimplemented in librandom::PoissonRandomDev, librandom::BinomialRandomDev, librandom::GSL_BinomialRandomDev, and librandom::UniformIntRandomDev.
References assert().
double librandom::RandomDev::operator() (void) inline virtual
Operator delivering doubles.
All random deviates must deliver doubles
Note
Operator varieties with and without RngPtr as argument are implemented explicitly instead of via default value of the argument to force all derived classes to implement both varieties.single-threaded
References assert(), rng_, and lockPTR< D >::valid().
virtual double librandom::RandomDev::operator() (RngPtr) const pure virtual
multi-threaded
Implemented in librandom::PoissonRandomDev, librandom::BinomialRandomDev, librandom::GSL_BinomialRandomDev, librandom::GammaRandomDev, librandom::UniformIntRandomDev, librandom::UniformRandomDev, librandom::LognormalRandomDev, librandom::NormalRandomDev, and librandom::ExpRandomDev.
void librandom::RandomDev::set_rng (RngPtr rng) inline
set RNG
References rng_.
virtual void librandom::RandomDev::set_status (const DictionaryDatum &) pure virtual
set distribution parameters from SLI interface
Note
RDGs with parameters will usually implement functions to manipulate the parameters directly, without use of a SLI dictionary. This function is meant only to provide access from the SLI interface.
Implemented in librandom::BinomialRandomDev, librandom::PoissonRandomDev, librandom::GSL_BinomialRandomDev, librandom::GammaRandomDev, librandom::UniformIntRandomDev, librandom::UniformRandomDev, librandom::LognormalRandomDev, librandom::NormalRandomDev, and librandom::ExpRandomDev.
Member Data Documentation
RngPtr librandom::RandomDev::rng_ protected
store underlying RNG
Referenced by ldev(), operator()(), and set_rng().
The documentation for this class was generated from the following files:
randomdev.h
randomdev.cpp