NEST: RolluFunction Class Reference
RolluFunction Class Reference
#include <slistack.h>
Public Member Functions
RolluFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
RolluFunction::RolluFunction () inline
Member Function Documentation
void RolluFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::EStack, TokenStack::load(), SLIInterpreter::OStack, TokenStack::pop(), SLIInterpreter::raiseerror(), TokenStack::roll(), and SLIInterpreter::StackUnderflowError.
The documentation for this class was generated from the following files:
slistack.h
slistack.cc