NEST: ParsestdinFunction Class Reference
ParsestdinFunction Class Reference
#include <slicontrol.h>
Public Member Functions
ParsestdinFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
ParsestdinFunction::ParsestdinFunction () inline
Member Function Documentation
void ParsestdinFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References Token::contains(), Scanner::EndSymbol, SLIInterpreter::EStack, SLIInterpreter::parse, TokenStack::pop(), TokenStack::push_move(), Parser::readToken(), and Parser::scan().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc