NEST: nest::NestModule::SimulateFunction Class Reference
nest::NestModule::SimulateFunction Class Reference
SLI Interface functions of the NEST kernel.
#include <nestmodule.h>
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void nest::NestModule::SimulateFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::EStack, nest::NestModule::get_network(), SLIInterpreter::M_INFO, SLIInterpreter::message(), nest::Time::ms, SLIInterpreter::OStack, TokenStack::pop(), nest::Network::simulate(), and TokenStack::top().
The documentation for this class was generated from the following files:
nestmodule.h
nestmodule.cpp