NEST: CloseinputFunction Class Reference
CloseinputFunction Class Reference
#include <slicontrol.h>
Public Member Functions
CloseinputFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
CloseinputFunction::CloseinputFunction () inline
Member Function Documentation
void CloseinputFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::baselookup(), nest::names::c, SLIInterpreter::catch_errors(), TokenStack::clear(), SLIInterpreter::debug_commandline(), SLIInterpreter::debug_mode_on(), SLIInterpreter::EStack, SLIInterpreter::get_debug_mode(), Datum::isoftype(), TokenStack::load(), SLIInterpreter::message(), nest::names::n, TokenStack::pick(), TokenStack::pop(), TokenStack::push(), SLIInterpreter::show_backtrace(), SLIInterpreter::stack_backtrace(), TokenStack::top(), and SLIInterpreter::XIstreamtype.
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc