NEST: nest::CommonSynapseProperties Class Reference
nest::CommonSynapseProperties Class Reference
Class containing the common properties for all connections of a certain type.
#include <common_synapse_properties.h>
Public Member Functions
CommonSynapseProperties ()
Standard constructor.
~CommonSynapseProperties ()
Destructor.
void get_status (DictionaryDatum &d) const
Get all properties and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate all time objects, which might be contained in this object.
Node * get_node ()
get reference to registering node
long_t get_vt_gid () const
Detailed Description
Class containing the common properties for all connections of a certain type.
Everything that needs to be stored commonly for all synapses goes into a CommonProperty class derived by this base class. Base class for all CommonProperty classes. If the synapse type does not have any common properties, this class may be used as a placeholder.
Constructor & Destructor Documentation
nest::CommonSynapseProperties::CommonSynapseProperties ()
Standard constructor.
Default implementation of an empty CommonSynapseProperties object.
Sets all common properties to default values.
nest::CommonSynapseProperties::~CommonSynapseProperties ()
Destructor.
Member Function Documentation
void nest::CommonSynapseProperties::calibrate (const TimeConverter &)
Calibrate all time objects, which might be contained in this object.
Node * nest::CommonSynapseProperties::get_node ()
get reference to registering node
void nest::CommonSynapseProperties::get_status (DictionaryDatum & d) const
Get all properties and put them into a dictionary.
Referenced by nest::CommonPropertiesHomW::get_status(), nest::STDPPLHomCommonProperties::get_status(), nest::STDPHomCommonProperties::get_status(), nest::STDPDopaCommonProperties::get_status(), and nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::get_status().
long_t nest::CommonSynapseProperties::get_vt_gid () const inline
void nest::CommonSynapseProperties::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set properties from the values given in dictionary.
Referenced by nest::CommonPropertiesHomW::set_status(), nest::STDPPLHomCommonProperties::set_status(), nest::STDPHomCommonProperties::set_status(), nest::STDPDopaCommonProperties::set_status(), and nest::STDPFACETSHWHomCommonProperties< targetidentifierT >::set_status().
The documentation for this class was generated from the following files:
common_synapse_properties.h
common_synapse_properties.cpp