NEST: BoolDatum Class Reference
BoolDatum Class Reference
#include <booldatum.h>
Public Member Functions
BoolDatum ()
BoolDatum (const BoolDatum &val)
BoolDatum (bool val)
BoolDatum (const Name &)
operator bool () const
operator Name () const
operator std::string () const
void input_form (std::ostream &) const
void print (std::ostream &) const
void pprint (std::ostream &) const
Public Member Functions inherited from GenericDatum< bool,&SLIInterpreter::Booltype >
GenericDatum ()
GenericDatum (const bool &d_s)
GenericDatum (const GenericDatum< bool, slt > &gd)
virtual ~GenericDatum ()
const bool & operator= (const bool &d_s)
const bool & get (void) const
bool & get (void)
bool & get_lval ()
void print (std::ostream &o) const
void pprint (std::ostream &o) const
void info (std::ostream &out) const
bool equals (const Datum *dat) const
Public Member Functions inherited from TypedDatum< slt >
TypedDatum (void)
Public Member Functions inherited from Datum
virtual ~Datum ()
void addReference () const
void removeReference ()
size_t numReferences () const
bool is_executable () const
void set_executable ()
void unset_executable ()
virtual void list (std::ostream &o, std::string prefix, int l) const
const Name & gettypename (void) const
bool isoftype (SLIType const &t) const
void execute (SLIInterpreter *i)
Static Public Member Functions
static void * operator new (size_t size)
static void operator delete (void *p, size_t size)
Static Public Attributes
static const char * true_string ="true"
static const char * false_string ="false"
Static Protected Attributes
static sli::pool memory
Private Member Functions
Datum * clone (void) const
Virtual copy constructor.
Additional Inherited Members
Protected Member Functions inherited from TypedDatum< slt >
TypedDatum (const TypedDatum< slt > &d)
const TypedDatum< slt > & operator= (const TypedDatum< slt > &)
Protected Member Functions inherited from Datum
Datum ()
Datum (const SLIType *t)
Datum (const Datum &d)
Protected Attributes inherited from GenericDatum< bool,&SLIInterpreter::Booltype >
bool d
Protected Attributes inherited from Datum
const SLIType * type
Pointer to type object.
const SLIFunction * action
Shortcut to the SLIType default action.
unsigned int reference_count_
bool executable_
Constructor & Destructor Documentation
BoolDatum::BoolDatum () inline
Referenced by clone().
BoolDatum::BoolDatum (const BoolDatum & val) inline
BoolDatum::BoolDatum (bool val) inline
BoolDatum::BoolDatum (const Name & val)
References GenericDatum< bool,&SLIInterpreter::Booltype >::d, and true_string.
Member Function Documentation
Datum* BoolDatum::clone (void) const inline private virtual
Virtual copy constructor.
Use this function to lazily copy a datum.
Reimplemented from GenericDatum< bool,&SLIInterpreter::Booltype >.
References BoolDatum().
void BoolDatum::input_form (std::ostream & out) const virtual
Reimplemented from Datum.
References print().
BoolDatum::operator bool () const inline
References GenericDatum< bool,&SLIInterpreter::Booltype >::d.
void BoolDatum::operator delete (void * p, size_t size) static
References nest::names::memory, and nest::names::p.
BoolDatum::operator Name () const
References nest::names::d.
void * BoolDatum::operator new (size_t size) static
References nest::names::memory.
BoolDatum::operator std::string () const
References nest::names::d.
void BoolDatum::pprint (std::ostream & out) const virtual
Implements Datum.
References print().
void BoolDatum::print (std::ostream & out) const virtual
Implements Datum.
References GenericDatum< bool,&SLIInterpreter::Booltype >::d, false_string, and true_string.
Referenced by input_form(), and pprint().
Member Data Documentation
const char * BoolDatum::false_string ="false" static
Referenced by print().
sli::pool BoolDatum::memory static protected
const char * BoolDatum::true_string ="true" static
Referenced by BoolDatum(), and print().
The documentation for this class was generated from the following files:
booldatum.h
booldatum.cc