NEST: lockPTR< D >::PointerObject Class Reference
lockPTR< D >::PointerObject Class Reference
Public Member Functions
PointerObject (D *p=NULL)
PointerObject (D &p_o)
~PointerObject ()
D * get (void) const
void addReference (void)
void removeReference (void)
size_t references (void) const
bool islocked (void) const
bool isdeletable (void) const
void lock (void)
void unlock (void)
Private Member Functions
PointerObject (PointerObject const &)
Private Attributes
D * pointee
size_t number_of_references
bool deletable
bool locked
Constructor & Destructor Documentation
template<class D> lockPTR< D >::PointerObject::PointerObject (PointerObject const &) private
template<class D> lockPTR< D >::PointerObject::PointerObject (D * p = NULL) inline
template<class D> lockPTR< D >::PointerObject::PointerObject (D & p_o) inline
template<class D> lockPTR< D >::PointerObject::~PointerObject () inline
References assert(), lockPTR< D >::PointerObject::deletable, lockPTR< D >::PointerObject::locked, lockPTR< D >::PointerObject::number_of_references, and lockPTR< D >::PointerObject::pointee.
Member Function Documentation
template<class D> void lockPTR< D >::PointerObject::addReference (void) inline
References lockPTR< D >::PointerObject::number_of_references.
Referenced by lockPTR< nest::Ntree< D, index > >::lockPTR(), and lockPTR< nest::Ntree< D, index > >::operator=().
template<class D> D* lockPTR< D >::PointerObject::get (void) const inline
References lockPTR< D >::PointerObject::pointee.
Referenced by lockPTR< nest::Ntree< D, index > >::get(), lockPTR< nest::Ntree< D, index > >::operator!(), lockPTR< nest::Ntree< D, index > >::operator*(), lockPTR< nest::Ntree< D, index > >::operator->(), and lockPTR< nest::Ntree< D, index > >::valid().
template<class D> bool lockPTR< D >::PointerObject::isdeletable (void) const inline
References lockPTR< D >::PointerObject::deletable.
Referenced by lockPTR< nest::Ntree< D, index > >::deletable(), and lockPTR< nest::Ntree< D, index > >::operator=().
template<class D> bool lockPTR< D >::PointerObject::islocked (void) const inline
References lockPTR< D >::PointerObject::locked.
Referenced by lockPTR< nest::Ntree< D, index > >::get(), and lockPTR< nest::Ntree< D, index > >::islocked().
template<class D> void lockPTR< D >::PointerObject::lock (void) inline
References assert(), and lockPTR< D >::PointerObject::locked.
Referenced by lockPTR< nest::Ntree< D, index > >::get(), and lockPTR< nest::Ntree< D, index > >::lock().
template<class D> size_t lockPTR< D >::PointerObject::references (void) const inline
References lockPTR< D >::PointerObject::number_of_references.
Referenced by lockPTR< nest::Ntree< D, index > >::references().
template<class D> void lockPTR< D >::PointerObject::removeReference (void) inline
References lockPTR< D >::PointerObject::number_of_references.
Referenced by lockPTR< nest::Ntree< D, index > >::operator=(), and lockPTR< nest::Ntree< D, index > >::~lockPTR().
template<class D> void lockPTR< D >::PointerObject::unlock (void) inline
References assert(), and lockPTR< D >::PointerObject::locked.
Referenced by lockPTR< nest::Ntree< D, index > >::unlock().
Member Data Documentation
template<class D> bool lockPTR< D >::PointerObject::deletable private
Referenced by lockPTR< D >::PointerObject::isdeletable(), and lockPTR< D >::PointerObject::~PointerObject().
template<class D> bool lockPTR< D >::PointerObject::locked private
Referenced by lockPTR< D >::PointerObject::islocked(), lockPTR< D >::PointerObject::lock(), lockPTR< D >::PointerObject::unlock(), and lockPTR< D >::PointerObject::~PointerObject().
template<class D> size_t lockPTR< D >::PointerObject::number_of_references private
Referenced by lockPTR< D >::PointerObject::addReference(), lockPTR< D >::PointerObject::references(), lockPTR< D >::PointerObject::removeReference(), and lockPTR< D >::PointerObject::~PointerObject().
template<class D> D* lockPTR< D >::PointerObject::pointee private
Referenced by lockPTR< D >::PointerObject::get(), and lockPTR< D >::PointerObject::~PointerObject().
The documentation for this class was generated from the following file:
lockptr.h