NEST: SLIArrayModule::PartitionFunction Class Reference
SLIArrayModule::PartitionFunction Class Reference
SLI array functions
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void SLIArrayModule::PartitionFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References ad, assert(), nest::names::b, TokenArray::begin(), nest::names::d, Token::datum(), numerics::e, TokenArray::end(), SLIInterpreter::EStack, GenericDatum< D, slt >::get(), TokenStack::load(), nest::names::max, nest::names::n, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push(), TokenArray::push_back(), SLIInterpreter::raiseerror(), TokenArray::reserve(), TokenArray::size(), nest::names::source, and nest::names::target.
The documentation for this class was generated from the following files:
sliarray.h
sliarray.cc