NEST: nest::SpikeEvent Class Reference
nest::SpikeEvent Class Reference
Event for spike information.
#include <event.h>
Public Member Functions
SpikeEvent ()
void operator() ()
Deliver the event to receiver.
SpikeEvent * clone () const
Virtual copy constructor.
void set_multiplicity (int_t)
int_t get_multiplicity () const
Public Member Functions inherited from nest::Event
Event ()
virtual ~Event ()
void set_receiver (Node &)
Change pointer to receiving Node.
Node & get_receiver () const
Return reference to receiving Node.
Node & get_sender () const
Return reference to sending Node.
void set_sender (Node &)
Change pointer to sending Node.
index get_sender_gid () const
Return GID of sending Node.
void set_sender_gid (index)
Change GID of sending Node.
Time const & get_stamp () const
Return time stamp of the event.
void set_delay (delay)
Set the transmission delay of the event.
delay get_delay () const
Return transmission delay of the event.
delay get_max_delay () const
long_t get_rel_delivery_steps (const Time &t) const
Relative spike delivery time in steps.
port get_port () const
Return the sender port number of the event.
rport get_rport () const
Return the receiver port number of the event.
void set_port (port p)
Set the port number.
void set_rport (rport p)
Set the receiver port number (r-port).
double_t get_offset () const
Return the creation time offset of the Event.
void set_offset (double_t t)
Set the creation time of the Event.
weight get_weight () const
Return the weight.
void set_weight (weight t)
Set weight of the event.
bool is_valid () const
Check integrity of the event.
void set_stamp (Time const &)
Set the time stamp of the event.
Protected Attributes
int_t multiplicity_
Protected Attributes inherited from nest::Event
index sender_gid_
GID of sender or -1.
Node * sender_
Pointer to sender or NULL.
Node * receiver_
Pointer to receiver or NULL.
port p_
Sender port number.
rport rp_
Receiver port number (r-port).
delay d_
Transmission delay.
Time stamp_
Time stamp.
double offset_
Offset for precise spike times.
weight w_
Weight of the connection.
Detailed Description
Event for spike information.
Used to send a spike from one node to the next.
Constructor & Destructor Documentation
nest::SpikeEvent::SpikeEvent () inline
Referenced by clone().
Member Function Documentation
SpikeEvent * nest::SpikeEvent::clone () const inline virtual
Virtual copy constructor.
Implements nest::Event.
References SpikeEvent().
Referenced by nest::spin_detector::handle(), and nest::spike_detector::handle().
int_t nest::SpikeEvent::get_multiplicity () const inline
References multiplicity_.
Referenced by nest::mip_generator::event_hook(), nest::binary_neuron< TGainfunction >::handle(), nest::iaf_psc_exp_multisynapse::handle(), nest::iaf_psc_alpha_multisynapse::handle(), nest::music_event_out_proxy::handle(), nest::parrot_neuron_ps::handle(), nest::parrot_neuron::handle(), nest::aeif_cond_alpha_multisynapse::handle(), nest::sli_neuron::handle(), nest::izhikevich::handle(), nest::iaf_chs_2007::handle(), nest::spin_detector::handle(), nest::iaf_cond_exp::handle(), nest::spike_detector::handle(), nest::aeif_cond_alpha_RK5::handle(), nest::volume_transmitter::handle(), nest::hh_cond_exp_traub::handle(), nest::iaf_chxk_2008::handle(), nest::iaf_cond_exp_sfa_rr::handle(), nest::iaf_psc_exp::handle(), nest::aeif_cond_alpha::handle(), nest::iaf_cond_alpha::handle(), nest::iaf_neuron::handle(), nest::ht_neuron::handle(), nest::iaf_psc_alpha_presc::handle(), nest::hh_psc_alpha::handle(), nest::iaf_psc_delta::handle(), nest::iaf_psc_alpha::handle(), nest::aeif_cond_exp::handle(), nest::iaf_tum_2000::handle(), nest::correlomatrix_detector::handle(), nest::mat2_psc_exp::handle(), nest::iaf_psc_exp_ps::handle(), nest::correlation_detector::handle(), nest::amat2_psc_exp::handle(), nest::pp_psc_delta::handle(), nest::pp_pop_psc_delta::handle(), nest::iaf_psc_alpha_canon::handle(), nest::iaf_cond_alpha_mc::handle(), nest::iaf_psc_delta_canon::handle(), nest::Scheduler::send_offgrid_remote(), and nest::Scheduler::send_remote().
void nest::SpikeEvent::operator() () virtual
Deliver the event to receiver.
This operator calls the handler for the specific event type at the receiver.
Implements nest::Event.
Reimplemented in nest::DSSpikeEvent.
References nest::Node::handle(), and nest::Event::receiver_.
void nest::SpikeEvent::set_multiplicity (int_t multiplicity) inline
References multiplicity_.
Referenced by nest::gamma_sup_generator::event_hook(), nest::sinusoidal_poisson_generator::event_hook(), nest::ppd_sup_generator::event_hook(), nest::poisson_generator::event_hook(), nest::mip_generator::event_hook(), nest::binary_neuron< TGainfunction >::update(), nest::pulsepacket_generator::update(), nest::sinusoidal_poisson_generator::update(), nest::mip_generator::update(), nest::pp_psc_delta::update(), and nest::pp_pop_psc_delta::update().
Member Data Documentation
int_t nest::SpikeEvent::multiplicity_ protected
Referenced by get_multiplicity(), and set_multiplicity().
The documentation for this class was generated from the following files:
event.h
event.cpp