NEST: Processes Class Reference
Processes Class Reference
#include <processes.h>
Classes
class AvailableFunction
class CtermidFunction
class Dup2_is_isFunction
class Dup2_is_osFunction
class Dup2_os_isFunction
class Dup2_os_osFunction
class ForkFunction
class GetPGRPFunction
class GetPIDFunction
class GetPPIDFunction
class Isatty_isFunction
class Isatty_osFunction
class KillFunction
class MemoryThisjobBgFunction
class MemoryThisjobDarwinFunction
class MkfifoFunction
class PipeFunction
class SetNonblockFunction
class Sysexec_aFunction
class WaitPIDFunction
Public Member Functions
Processes (void)
~Processes (void)
void init (SLIInterpreter *)
Initialise the module.
const std::string name (void) const
Return name of the module.
const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Static Public Member Functions
static const std::string systemerror (SLIInterpreter *)
static int fd (std::istream *s)
static int fd (std::ostream *s)
static int fd (std::ostream &s)
static int fd (std::istream &s)
Public Attributes
const Name signaldict_name
const Name SIGABRT_name
const Name SIGALRM_name
const Name SIGFPE_name
const Name SIGHUP_name
const Name SIGILL_name
const Name SIGINT_name
const Name SIGKILL_name
const Name SIGPIPE_name
const Name SIGQUIT_name
const Name SIGSEGV_name
const Name SIGTERM_name
const Name SIGUSR1_name
const Name SIGUSR2_name
const Name SIGCHLD_name
const Name SIGCONT_name
const Name SIGSTOP_name
const Name SIGTSTP_name
const Name SIGTTIN_name
const Name SIGTTOU_name
const Name sys_errname
const Name sys_errno
const Name E2BIG_name
const Name EACCES_name
const Name EAGAIN_name
const Name EBADF_name
const Name EBUSY_name
const Name ECHILD_name
const Name EDEADLK_name
const Name EDOM_name
const Name EEXIST_name
const Name EFAULT_name
const Name EFBIG_name
const Name EINTR_name
const Name EINVAL_name
const Name EIO_name
const Name EISDIR_name
const Name EMFILE_name
const Name EMLINK_name
const Name ENAMETOOLONG_name
const Name ENFILE_name
const Name ENODEV_name
const Name ENOENT_name
const Name ENOEXEC_name
const Name ENOLCK_name
const Name ENOMEM_name
const Name ENOSPC_name
const Name ENOSYS_name
const Name ENOTDIR_name
const Name ENOTEMPTY_name
const Name ENOTTY_name
const Name ENXIO_name
const Name EPERM_name
const Name EPIPE_name
const Name ERANGE_name
const Name EROFS_name
const Name ESPIPE_name
const Name ESRCH_name
const Name EXDEV_name
ForkFunction forkfunction
Sysexec_aFunction sysexec_afunction
WaitPIDFunction waitPIDfunction
KillFunction killfunction
PipeFunction pipefunction
Dup2_is_isFunction dup2_is_isfunction
Dup2_os_osFunction dup2_os_osfunction
Dup2_is_osFunction dup2_is_osfunction
Dup2_os_isFunction dup2_os_isfunction
AvailableFunction availablefunction
GetPIDFunction getpidfunction
GetPPIDFunction getppidfunction
GetPGRPFunction getpgrpfunction
MkfifoFunction mkfifofunction
MemoryThisjobBgFunction memorythisjobbgfunction
MemoryThisjobDarwinFunction memorythisjobdarwinfunction
SetNonblockFunction setnonblockfunction
CtermidFunction ctermidfunction
Isatty_osFunction isatty_osfunction
Isatty_isFunction isatty_isfunction
Static Public Attributes
static pid_t children_group = 0
Constructor & Destructor Documentation
Processes::Processes (void) inline
Processes::~Processes (void)
Member Function Documentation
const std::string Processes::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Reimplemented from SLIModule.
int Processes::fd (std::istream * s) static
References assert(), fdbuf::fd(), and ifdstream::rdbuf().
Referenced by Processes::Dup2_is_isFunction::execute(), Processes::Dup2_os_osFunction::execute(), Processes::Dup2_is_osFunction::execute(), Processes::Dup2_os_isFunction::execute(), Processes::AvailableFunction::execute(), Processes::SetNonblockFunction::execute(), Processes::Isatty_isFunction::execute(), and Processes::Isatty_osFunction::execute().
int Processes::fd (std::ostream * s) static
References assert(), fdbuf::fd(), and ofdstream::rdbuf().
static int Processes::fd (std::ostream & s) inline static
References fd().
Referenced by fd().
static int Processes::fd (std::istream & s) inline static
References fd().
Referenced by fd().
void Processes::init (SLIInterpreter *) virtual
Initialise the module.
When this function is called, most of the interpreter's fascilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialised, not all services may be available.
Implements SLIModule.
References assert(), availablefunction, SLIInterpreter::baselookup(), SLIInterpreter::createcommand(), ctermidfunction, SLIInterpreter::def(), dup2_is_isfunction, dup2_is_osfunction, dup2_os_isfunction, dup2_os_osfunction, E2BIG_name, EACCES_name, EAGAIN_name, EBADF_name, EBUSY_name, ECHILD_name, EDEADLK_name, EDOM_name, EEXIST_name, EFAULT_name, EFBIG_name, EINTR_name, EINVAL_name, EIO_name, EISDIR_name, EMFILE_name, EMLINK_name, ENAMETOOLONG_name, ENFILE_name, ENODEV_name, ENOENT_name, ENOEXEC_name, ENOLCK_name, ENOMEM_name, ENOSPC_name, ENOSYS_name, ENOTDIR_name, ENOTEMPTY_name, ENOTTY_name, ENXIO_name, EPERM_name, EPIPE_name, ERANGE_name, EROFS_name, SLIInterpreter::errordict_name, ESPIPE_name, ESRCH_name, EXDEV_name, forkfunction, getpgrpfunction, getpidfunction, getppidfunction, Dictionary::insert(), isatty_isfunction, isatty_osfunction, killfunction, memorythisjobbgfunction, memorythisjobdarwinfunction, mkfifofunction, pipefunction, setnonblockfunction, SIGABRT_name, SIGALRM_name, SIGCHLD_name, SIGCONT_name, SIGFPE_name, SIGHUP_name, SIGILL_name, SIGINT_name, SIGKILL_name, signaldict_name, SIGPIPE_name, SIGQUIT_name, SIGSEGV_name, SIGSTOP_name, SIGTERM_name, SIGTSTP_name, SIGTTIN_name, SIGTTOU_name, SIGUSR1_name, SIGUSR2_name, sys_errname, sys_errno, sysexec_afunction, and waitPIDfunction.
const std::string Processes::name (void) const virtual
Return name of the module.
Implements SLIModule.
const std::string Processes::systemerror (SLIInterpreter * i) static
References assert(), SLIInterpreter::baselookup(), and SLIInterpreter::errordict_name.
Referenced by Processes::ForkFunction::execute(), Processes::Sysexec_aFunction::execute(), Processes::WaitPIDFunction::execute(), Processes::KillFunction::execute(), Processes::PipeFunction::execute(), Processes::Dup2_is_isFunction::execute(), Processes::Dup2_os_osFunction::execute(), Processes::Dup2_is_osFunction::execute(), Processes::Dup2_os_isFunction::execute(), Processes::GetPIDFunction::execute(), Processes::GetPPIDFunction::execute(), Processes::GetPGRPFunction::execute(), Processes::MkfifoFunction::execute(), Processes::SetNonblockFunction::execute(), PclocksFunction::execute(), and PgetrusageFunction::execute().
Member Data Documentation
AvailableFunction Processes::availablefunction
Referenced by init().
pid_t Processes::children_group = 0 static
CtermidFunction Processes::ctermidfunction
Referenced by init().
Dup2_is_isFunction Processes::dup2_is_isfunction
Referenced by init().
Dup2_is_osFunction Processes::dup2_is_osfunction
Referenced by init().
Dup2_os_isFunction Processes::dup2_os_isfunction
Referenced by init().
Dup2_os_osFunction Processes::dup2_os_osfunction
Referenced by init().
const Name Processes::E2BIG_name
Referenced by init().
const Name Processes::EACCES_name
Referenced by init().
const Name Processes::EAGAIN_name
Referenced by init().
const Name Processes::EBADF_name
Referenced by init().
const Name Processes::EBUSY_name
Referenced by init().
const Name Processes::ECHILD_name
Referenced by init().
const Name Processes::EDEADLK_name
Referenced by init().
const Name Processes::EDOM_name
Referenced by init().
const Name Processes::EEXIST_name
Referenced by init().
const Name Processes::EFAULT_name
Referenced by init().
const Name Processes::EFBIG_name
Referenced by init().
const Name Processes::EINTR_name
Referenced by init().
const Name Processes::EINVAL_name
Referenced by init().
const Name Processes::EIO_name
Referenced by init().
const Name Processes::EISDIR_name
Referenced by init().
const Name Processes::EMFILE_name
Referenced by init().
const Name Processes::EMLINK_name
Referenced by init().
const Name Processes::ENAMETOOLONG_name
Referenced by init().
const Name Processes::ENFILE_name
Referenced by init().
const Name Processes::ENODEV_name
Referenced by init().
const Name Processes::ENOENT_name
Referenced by init().
const Name Processes::ENOEXEC_name
Referenced by init().
const Name Processes::ENOLCK_name
Referenced by init().
const Name Processes::ENOMEM_name
Referenced by init().
const Name Processes::ENOSPC_name
Referenced by init().
const Name Processes::ENOSYS_name
Referenced by init().
const Name Processes::ENOTDIR_name
Referenced by init().
const Name Processes::ENOTEMPTY_name
Referenced by init().
const Name Processes::ENOTTY_name
Referenced by init().
const Name Processes::ENXIO_name
Referenced by init().
const Name Processes::EPERM_name
Referenced by init().
const Name Processes::EPIPE_name
Referenced by init().
const Name Processes::ERANGE_name
Referenced by init().
const Name Processes::EROFS_name
Referenced by init().
const Name Processes::ESPIPE_name
Referenced by init().
const Name Processes::ESRCH_name
Referenced by init().
const Name Processes::EXDEV_name
Referenced by init().
ForkFunction Processes::forkfunction
Referenced by init().
GetPGRPFunction Processes::getpgrpfunction
Referenced by init().
GetPIDFunction Processes::getpidfunction
Referenced by init().
GetPPIDFunction Processes::getppidfunction
Referenced by init().
Isatty_isFunction Processes::isatty_isfunction
Referenced by init().
Isatty_osFunction Processes::isatty_osfunction
Referenced by init().
KillFunction Processes::killfunction
Referenced by init().
MemoryThisjobBgFunction Processes::memorythisjobbgfunction
Referenced by init().
MemoryThisjobDarwinFunction Processes::memorythisjobdarwinfunction
Referenced by init().
MkfifoFunction Processes::mkfifofunction
Referenced by init().
PipeFunction Processes::pipefunction
Referenced by init().
SetNonblockFunction Processes::setnonblockfunction
Referenced by init().
const Name Processes::SIGABRT_name
Referenced by init().
const Name Processes::SIGALRM_name
Referenced by init().
const Name Processes::SIGCHLD_name
Referenced by init().
const Name Processes::SIGCONT_name
Referenced by init().
const Name Processes::SIGFPE_name
Referenced by init().
const Name Processes::SIGHUP_name
Referenced by init().
const Name Processes::SIGILL_name
Referenced by init().
const Name Processes::SIGINT_name
Referenced by init().
const Name Processes::SIGKILL_name
Referenced by init().
const Name Processes::signaldict_name
Referenced by init().
const Name Processes::SIGPIPE_name
Referenced by init().
const Name Processes::SIGQUIT_name
Referenced by init().
const Name Processes::SIGSEGV_name
Referenced by init().
const Name Processes::SIGSTOP_name
Referenced by init().
const Name Processes::SIGTERM_name
Referenced by init().
const Name Processes::SIGTSTP_name
Referenced by init().
const Name Processes::SIGTTIN_name
Referenced by init().
const Name Processes::SIGTTOU_name
Referenced by init().
const Name Processes::SIGUSR1_name
Referenced by init().
const Name Processes::SIGUSR2_name
Referenced by init().
const Name Processes::sys_errname
Referenced by init().
const Name Processes::sys_errno
Referenced by init().
Sysexec_aFunction Processes::sysexec_afunction
Referenced by init().
WaitPIDFunction Processes::waitPIDfunction
Referenced by init().
The documentation for this class was generated from the following files:
processes.h
processes.cc