NEST: nest::GIDCollection Class Reference
nest::GIDCollection Class Reference
#include <gid_collection.h>
Classes
class const_iterator
Public Member Functions
GIDCollection ()
GIDCollection (index first, index last)
GIDCollection (IntVectorDatum gids)
GIDCollection (TokenArray gids)
void print_me (std::ostream &out) const
index operator[] (const size_t pos) const
bool operator== (const GIDCollection &rhs) const
const_iterator begin () const
const_iterator end () const
size_t size () const
Private Attributes
std::vector< index > gid_array_
std::pair< index, index > gid_range_
bool is_range_
Constructor & Destructor Documentation
nest::GIDCollection::GIDCollection () inline
nest::GIDCollection::GIDCollection (index first, index last)
References gid_range_.
nest::GIDCollection::GIDCollection (IntVectorDatum gids)
References gid_array_.
nest::GIDCollection::GIDCollection (TokenArray gids)
References gid_array_, and TokenArray::size().
Member Function Documentation
GIDCollection::const_iterator nest::GIDCollection::begin () const inline
GIDCollection::const_iterator nest::GIDCollection::end () const inline
References size().
bool nest::GIDCollection::operator== (const GIDCollection & rhs) const inline
References gid_array_, gid_range_, and is_range_.
index nest::GIDCollection::operator[] (const size_t pos) const inline
References gid_array_, gid_range_, and is_range_.
void nest::GIDCollection::print_me (std::ostream & out) const
References gid_array_, gid_range_, is_range_, and size().
size_t nest::GIDCollection::size (void) const inline
References gid_array_, gid_range_, and is_range_.
Referenced by end(), nest::FixedInDegreeBuilder::FixedInDegreeBuilder(), nest::FixedOutDegreeBuilder::FixedOutDegreeBuilder(), nest::FixedTotalNumberBuilder::FixedTotalNumberBuilder(), and print_me().
Member Data Documentation
std::vector<index> nest::GIDCollection::gid_array_ private
Referenced by GIDCollection(), operator==(), operator[](), print_me(), and size().
std::pair<index, index> nest::GIDCollection::gid_range_ private
Referenced by GIDCollection(), operator==(), operator[](), print_me(), and size().
bool nest::GIDCollection::is_range_ private
Referenced by operator==(), operator[](), print_me(), and size().
The documentation for this class was generated from the following files:
gid_collection.h
gid_collection.cpp