NEST: nest::TopologyModule Class Reference
nest::TopologyModule Class Reference
#include <topologymodule.h>
Classes
class Add_P_PFunction
class And_M_MFunction
class ConnectLayers_i_i_DFunction
class CreateLayer_DFunction
class CreateMask_DFunction
class CreateParameter_DFunction
class Cvdict_MFunction
class Displacement_a_iFunction
class Distance_a_iFunction
class Div_P_PFunction
class DumpLayerConnections_os_i_lFunction
class DumpLayerNodes_os_iFunction
class GetElement_i_iaFunction
class GetGlobalChildren_i_M_aFunction
class GetPosition_iFunction
class GetValue_a_PFunction
class Inside_a_MFunction
class Mul_P_PFunction
class Or_M_MFunction
class Sub_M_MFunction
class Sub_P_PFunction
Public Types
typedef GenericFactory
< AbstractMask > MaskFactory
typedef GenericFactory
< AbstractMask >
::CreatorFunction MaskCreatorFunction
typedef GenericFactory< Parameter > ParameterFactory
typedef GenericFactory
< Parameter >::CreatorFunction ParameterCreatorFunction
Public Member Functions
TopologyModule (Network &)
~TopologyModule ()
void init (SLIInterpreter *)
Initialize module by registering models with the network.
const std::string name (void) const
Return name of the module.
const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Static Public Member Functions
static Network & get_network ()
Return a reference to the network managed by the topology module.
template<class T >
static bool register_mask ()
Register an AbstractMask subclass as a new mask type.
template<class T >
static bool register_mask (const Name &name)
Register an AbstractMask subclass as a new mask type with the given name.
static bool register_mask (const Name &name, MaskCreatorFunction creator)
Register a new mask type with the given name, with a supplied function to create mask objects of this type.
static lockPTRDatum
< AbstractMask,&TopologyModule::MaskType > create_mask (const Token &t)
Return a Mask object.
static AbstractMask * create_mask (const Name &name, const DictionaryDatum &d)
Create a new Mask object using the mask factory.
template<class T >
static bool register_parameter (const Name &name)
Register an Parameter subclass as a new parameter type with the given name.
static bool register_parameter (const Name &name, ParameterCreatorFunction creator)
Register a new parameter type with the given name, with a supplied function to create parameter objects of this type.
static lockPTRDatum< Parameter,&TopologyModule::ParameterType > create_parameter (const Token &)
Return a Parameter object.
static Parameter * create_parameter (const Name &name, const DictionaryDatum &d)
Create a new Parameter object using the parameter factory.
Public Attributes
nest::TopologyModule::CreateLayer_DFunction createlayer_Dfunction
nest::TopologyModule::GetPosition_iFunction getposition_ifunction
nest::TopologyModule::Displacement_a_iFunction displacement_a_ifunction
nest::TopologyModule::Distance_a_iFunction distance_a_ifunction
nest::TopologyModule::GetGlobalChildren_i_M_aFunction getglobalchildren_i_M_afunction
nest::TopologyModule::ConnectLayers_i_i_DFunction connectlayers_i_i_Dfunction
nest::TopologyModule::CreateMask_DFunction createmask_Dfunction
nest::TopologyModule::Inside_a_MFunction inside_a_Mfunction
nest::TopologyModule::And_M_MFunction and_M_Mfunction
nest::TopologyModule::Or_M_MFunction or_M_Mfunction
nest::TopologyModule::Sub_M_MFunction sub_M_Mfunction
nest::TopologyModule::Mul_P_PFunction mul_P_Pfunction
nest::TopologyModule::Div_P_PFunction div_P_Pfunction
nest::TopologyModule::Add_P_PFunction add_P_Pfunction
nest::TopologyModule::Sub_P_PFunction sub_P_Pfunction
nest::TopologyModule::CreateParameter_DFunction createparameter_Dfunction
nest::TopologyModule::GetValue_a_PFunction getvalue_a_Pfunction
nest::TopologyModule::DumpLayerNodes_os_iFunction dumplayernodes_os_ifunction
nest::TopologyModule::DumpLayerConnections_os_i_lFunction dumplayerconnections_os_i_lfunction
nest::TopologyModule::GetElement_i_iaFunction getelement_i_iafunction
nest::TopologyModule::Cvdict_MFunction cvdict_Mfunction
Static Public Attributes
static SLIType MaskType
SLI type for masks.
static SLIType ParameterType
SLI type for parameters.
Static Private Member Functions
static MaskFactory & mask_factory_ ()
Return a reference to the mask factory class.
static ParameterFactory & parameter_factory_ ()
Return a reference to the parameter factory class.
Static Private Attributes
static Network * net_
Member Typedef Documentation
typedef GenericFactory<AbstractMask>::CreatorFunction nest::TopologyModule::MaskCreatorFunction
typedef GenericFactory<AbstractMask> nest::TopologyModule::MaskFactory
typedef GenericFactory<Parameter>::CreatorFunction nest::TopologyModule::ParameterCreatorFunction
typedef GenericFactory<Parameter> nest::TopologyModule::ParameterFactory
Constructor & Destructor Documentation
nest::TopologyModule::TopologyModule (Network & net)
References SLIInterpreter::datatypefunction, MaskType, net_, ParameterType, SLIType::setdefaultaction(), and SLIType::settypename().
nest::TopologyModule::~TopologyModule ()
Member Function Documentation
const std::string nest::TopologyModule::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Reimplemented from SLIModule.
MaskDatum nest::TopologyModule::create_mask (const Token & t) static
Return a Mask object.
Parameters
t Either an existing MaskDatum, or a Dictionary containing mask parameters. The dictionary should contain a key with the name of the mask type, with a dictionary of parameters as value, and optionally an anchor.
Returns
Either the MaskDatum given as argument, or a new mask.
References ad, nest::names::anchor, nest::names::column, Token::datum(), numerics::e, getValue< long >(), nest::names::layer, nest::names::mask, nest::names::row, and nest::GridMask< D >::set_anchor().
Referenced by nest::ConnectionCreator::ConnectionCreator(), and nest::TopologyModule::CreateMask_DFunction::execute().
AbstractMask * nest::TopologyModule::create_mask (const Name & name, const DictionaryDatum & d) inline static
Create a new Mask object using the mask factory.
Parameters
name Mask type to create.
d Dictionary with parameters specific for this mask type.
Returns
dynamically allocated new Mask object.
References nest::GenericFactory< BaseT >::create(), and mask_factory_().
ParameterDatum nest::TopologyModule::create_parameter (const Token & t) static
Return a Parameter object.
Parameters
t Either an existing ParameterDatum, or a DoubleDatum containing a constant value for this parameter, or a Dictionary containing parameters. The dictionary should contain a single key with the name of the parameter type, with a dictionary of parameters as value.
Returns
Either the ParameterDatum given as argument, or a new parameter.
References Token::datum(), and nest::names::n.
Referenced by nest::ConnectionCreator::ConnectionCreator(), and nest::TopologyModule::CreateParameter_DFunction::execute().
Parameter * nest::TopologyModule::create_parameter (const Name & name, const DictionaryDatum & d) static
Create a new Parameter object using the parameter factory.
Parameters
name Parameter type to create.
d Dictionary with parameters specific for this parameter type.
Returns
dynamically allocated new Parameter object.
References nest::names::anchor, nest::GenericFactory< BaseT >::create(), nest::names::d, and parameter_factory_().
Network & nest::TopologyModule::get_network () inline static
Return a reference to the network managed by the topology module.
References assert(), and net_.
Referenced by nest::TopologyModule::GetPosition_iFunction::execute(), nest::TopologyModule::Displacement_a_iFunction::execute(), nest::TopologyModule::Distance_a_iFunction::execute(), nest::TopologyModule::GetGlobalChildren_i_M_aFunction::execute(), nest::TopologyModule::ConnectLayers_i_i_DFunction::execute(), nest::TopologyModule::CreateMask_DFunction::execute(), nest::TopologyModule::CreateParameter_DFunction::execute(), nest::TopologyModule::GetValue_a_PFunction::execute(), and init().
void nest::TopologyModule::init (SLIInterpreter * i) virtual
Initialize module by registering models with the network.
Parameters
SLIInterpreter* SLI interpreter, must know modeldict
Implements SLIModule.
References add_P_Pfunction, and_M_Mfunction, connectlayers_i_i_Dfunction, nest::create_doughnut(), SLIInterpreter::createcommand(), createlayer_Dfunction, createmask_Dfunction, createparameter_Dfunction, cvdict_Mfunction, displacement_a_ifunction, distance_a_ifunction, div_P_Pfunction, dumplayerconnections_os_i_lfunction, dumplayernodes_os_ifunction, get_network(), getelement_i_iafunction, getglobalchildren_i_M_afunction, getposition_ifunction, getvalue_a_Pfunction, inside_a_Mfunction, mul_P_Pfunction, or_M_Mfunction, register_mask(), sub_M_Mfunction, and sub_P_Pfunction.
GenericFactory< AbstractMask > & nest::TopologyModule::mask_factory_ (void) static private
Return a reference to the mask factory class.
Referenced by create_mask(), and register_mask().
const std::string nest::TopologyModule::name (void) const virtual
Return name of the module.
Implements SLIModule.
Referenced by register_mask(), and register_parameter().
GenericFactory< Parameter > & nest::TopologyModule::parameter_factory_ (void) static private
Return a reference to the parameter factory class.
Referenced by create_parameter(), and register_parameter().
template<class T > bool nest::TopologyModule::register_mask () inline static
Register an AbstractMask subclass as a new mask type.
The name will be found using the function T::get_name()
Returns
true if the new type was successfully registered, or false if a mask type with the same name already exists.
References mask_factory_(), and nest::GenericFactory< BaseT >::register_subtype().
Referenced by init().
template<class T > bool nest::TopologyModule::register_mask (const Name & name) inline static
Register an AbstractMask subclass as a new mask type with the given name.
Parameters
name name of the new mask type.
Returns
true if the new type was successfully registered, or false if a mask type with the same name already exists.
References mask_factory_(), name(), and nest::GenericFactory< BaseT >::register_subtype().
bool nest::TopologyModule::register_mask (const Name & name, MaskCreatorFunction creator) inline static
Register a new mask type with the given name, with a supplied function to create mask objects of this type.
Parameters
name name of the new mask type.
creator function creating objects of this type. The function will be called with the parameter dictionary as argument and should return a pointer to a new Mask object.
Returns
true if the new type was successfully registered, or false if a mask type with the same name already exists.
References mask_factory_(), and nest::GenericFactory< BaseT >::register_subtype().
template<class T > bool nest::TopologyModule::register_parameter (const Name & name) inline static
Register an Parameter subclass as a new parameter type with the given name.
Parameters
name name of the new parameter type.
Returns
true if the new type was successfully registered, or false if a parameter type with the same name already exists.
References name(), parameter_factory_(), and nest::GenericFactory< BaseT >::register_subtype().
bool nest::TopologyModule::register_parameter (const Name & name, ParameterCreatorFunction creator) inline static
Register a new parameter type with the given name, with a supplied function to create parameter objects of this type.
Parameters
name name of the new parameter type.
creator function creating objects of this type. The function will be called with the parameter dictionary as argument and should return a pointer to a new Parameter object.
Returns
true if the new type was successfully registered, or false if a parameter type with the same name already exists.
References parameter_factory_(), and nest::GenericFactory< BaseT >::register_subtype().
Member Data Documentation
nest::TopologyModule::Add_P_PFunction nest::TopologyModule::add_P_Pfunction
Referenced by init().
nest::TopologyModule::And_M_MFunction nest::TopologyModule::and_M_Mfunction
Referenced by init().
nest::TopologyModule::ConnectLayers_i_i_DFunction nest::TopologyModule::connectlayers_i_i_Dfunction
Referenced by init().
nest::TopologyModule::CreateLayer_DFunction nest::TopologyModule::createlayer_Dfunction
Referenced by init().
nest::TopologyModule::CreateMask_DFunction nest::TopologyModule::createmask_Dfunction
Referenced by init().
nest::TopologyModule::CreateParameter_DFunction nest::TopologyModule::createparameter_Dfunction
Referenced by init().
nest::TopologyModule::Cvdict_MFunction nest::TopologyModule::cvdict_Mfunction
Referenced by init().
nest::TopologyModule::Displacement_a_iFunction nest::TopologyModule::displacement_a_ifunction
Referenced by init().
nest::TopologyModule::Distance_a_iFunction nest::TopologyModule::distance_a_ifunction
Referenced by init().
nest::TopologyModule::Div_P_PFunction nest::TopologyModule::div_P_Pfunction
Referenced by init().
nest::TopologyModule::DumpLayerConnections_os_i_lFunction nest::TopologyModule::dumplayerconnections_os_i_lfunction
Referenced by init().
nest::TopologyModule::DumpLayerNodes_os_iFunction nest::TopologyModule::dumplayernodes_os_ifunction
Referenced by init().
nest::TopologyModule::GetElement_i_iaFunction nest::TopologyModule::getelement_i_iafunction
Referenced by init().
nest::TopologyModule::GetGlobalChildren_i_M_aFunction nest::TopologyModule::getglobalchildren_i_M_afunction
Referenced by init().
nest::TopologyModule::GetPosition_iFunction nest::TopologyModule::getposition_ifunction
Referenced by init().
nest::TopologyModule::GetValue_a_PFunction nest::TopologyModule::getvalue_a_Pfunction
Referenced by init().
nest::TopologyModule::Inside_a_MFunction nest::TopologyModule::inside_a_Mfunction
Referenced by init().
SLIType nest::TopologyModule::MaskType static
SLI type for masks.
Referenced by TopologyModule().
nest::TopologyModule::Mul_P_PFunction nest::TopologyModule::mul_P_Pfunction
Referenced by init().
Network * nest::TopologyModule::net_ static private
net must be static, so that the execute() members of the SliFunction classes in the module can access the network.
Referenced by nest::TopologyModule::CreateLayer_DFunction::execute(), nest::TopologyModule::DumpLayerNodes_os_iFunction::execute(), nest::TopologyModule::DumpLayerConnections_os_i_lFunction::execute(), nest::TopologyModule::GetElement_i_iaFunction::execute(), get_network(), and TopologyModule().
nest::TopologyModule::Or_M_MFunction nest::TopologyModule::or_M_Mfunction
Referenced by init().
SLIType nest::TopologyModule::ParameterType static
SLI type for parameters.
Referenced by TopologyModule().
nest::TopologyModule::Sub_M_MFunction nest::TopologyModule::sub_M_Mfunction
Referenced by init().
nest::TopologyModule::Sub_P_PFunction nest::TopologyModule::sub_P_Pfunction
Referenced by init().
The documentation for this class was generated from the following files:
topologymodule.h
topologymodule.cpp