NEST: ofdstream Class Reference
ofdstream Class Reference
#include <fdstream.h>
Public Member Functions
ofdstream ()
ofdstream (const char *s, std::ios_base::openmode mode=std::ios_base::out)
ofdstream (int fd)
fdbuf * rdbuf () const
bool is_open ()
void open (const char *s, std::ios_base::openmode mode=std::ios_base::out)
void close ()
Private Attributes
fdbuf sb
Constructor & Destructor Documentation
ofdstream::ofdstream () inline
Note
In this an all other constructors, we initialize the stream with a 0-pointer to a stream buffer first and then set the pointer through a call to rdbuf() in the constructor body. This is necessary because the stream buffer sb is constructed after the stream object, which is inherited from the base class. This causes problems at least when using the PGI compiler.
References sb.
ofdstream::ofdstream (const char * s, std::ios_base::openmode mode = std::ios_base::out) inline explicit
References assert(), open(), and sb.
ofdstream::ofdstream (int fd) inline explicit
References sb.
Member Function Documentation
void ofdstream::close ()
References rdbuf().
Referenced by CloseostreamFunction::execute().
bool ofdstream::is_open () inline
References fdbuf::is_open(), and rdbuf().
void ofdstream::open (const char * s, std::ios_base::openmode mode = std::ios_base::out) inline
References rdbuf().
Referenced by ofdstream().
fdbuf* ofdstream::rdbuf () const inline
References sb.
Referenced by close(), Processes::fd(), is_open(), and open().
Member Data Documentation
fdbuf ofdstream::sb private
Referenced by ofdstream(), and rdbuf().
The documentation for this class was generated from the following files:
fdstream.h
fdstream.cc