NEST: nest::DynamicLoaderModule Class Reference
nest::DynamicLoaderModule Class Reference
SLI interface of the Ddynamic module loader.
#include <dynamicloader.h>
Classes
class LoadModuleFunction
class UnloadModuleFunction
Public Member Functions
DynamicLoaderModule (Network *pNet, SLIInterpreter &interpreter)
~DynamicLoaderModule ()
void init (SLIInterpreter *)
Initialise the module.
const std::string commandstring (void) const
Return sli command sequence to be executed for initialisation.
const std::string name (void) const
Return name of the module.
void initLinkedModules (SLIInterpreter &)
Public Member Functions inherited from SLIModule
virtual ~SLIModule ()
void install (std::ostream &, SLIInterpreter *)
Print installation message via interpreter message command.
Static Public Member Functions
static int registerLinkedModule (DynModule *pModule)
This static member is called by the constructor of a loadable module that was linked at compile time into the application to circumvent dynamic loading problems.
Public Attributes
LoadModuleFunction loadmodule_function
UnloadModuleFunction unloadmodule_function
Static Private Member Functions
static vecLinkedModules & getLinkedModules ()
Provide access to the list of linked modules managed DynamicLoader.
Private Attributes
vecDynModules dyn_modules
Network * pNet_
Static Private Attributes
static Dictionary * moduledict_ = new Dictionary()
Dictionary for dynamically loaded modules.
Detailed Description
SLI interface of the Ddynamic module loader.
This class implements the SLI functions which allow for loading dynamic modules into the kernel to extend its functionality.
Constructor & Destructor Documentation
nest::DynamicLoaderModule::DynamicLoaderModule (Network * pNet, SLIInterpreter & interpreter)
At the time when DynamicLoaderModule is constructed, the SLI Interpreter and NestModule must be already constructed and initialized. DynamicLoaderModule relies on the presence of the following SLI datastructures: Name, Dictionary and on the nest::NestModule::net.
References assert(), SLIInterpreter::def(), moduledict_, pNet, and pNet_.
nest::DynamicLoaderModule::~DynamicLoaderModule ()
References dyn_modules.
Member Function Documentation
const std::string nest::DynamicLoaderModule::commandstring (void) const virtual
Return sli command sequence to be executed for initialisation.
Reimplemented from SLIModule.
vecLinkedModules & nest::DynamicLoaderModule::getLinkedModules () static private
Provide access to the list of linked modules managed DynamicLoader.
This function controls access to the list of linked modules managed by DynamicLoaderModule via a Meyers' Singleton (Alexandrescu, ch 6.4). The list is filled by calls to registerLinkedModule().
Referenced by nest::DynamicLoaderModule::LoadModuleFunction::execute(), initLinkedModules(), and registerLinkedModule().
void nest::DynamicLoaderModule::init (SLIInterpreter *) virtual
Initialise the module.
When this function is called, most of the interpreter's fascilities are up and running. However, depending on where in the interpreter's bootstrap sequence the module is initialised, not all services may be available.
Implements SLIModule.
References SLIInterpreter::createcommand(), loadmodule_function, SLIInterpreter::M_ERROR, SLIInterpreter::M_INFO, SLIInterpreter::message(), and unloadmodule_function.
void nest::DynamicLoaderModule::initLinkedModules (SLIInterpreter & interpreter)
References SLIInterpreter::addlinkeddynmodule(), getLinkedModules(), SLIInterpreter::M_STATUS, SLIInterpreter::message(), and pNet_.
const std::string nest::DynamicLoaderModule::name (void) const virtual
Return name of the module.
Implements SLIModule.
int nest::DynamicLoaderModule::registerLinkedModule (DynModule * pModule) static
This static member is called by the constructor of a loadable module that was linked at compile time into the application to circumvent dynamic loading problems.
Typically, the constructor of the global instance of the module calls this method to register itself. Later, DynamicLoader will go through all registered modules and initialize them.
References assert(), and getLinkedModules().
Member Data Documentation
vecDynModules nest::DynamicLoaderModule::dyn_modules private
Referenced by ~DynamicLoaderModule().
LoadModuleFunction nest::DynamicLoaderModule::loadmodule_function
Referenced by init().
Dictionary * nest::DynamicLoaderModule::moduledict_ = new Dictionary() static private
Dictionary for dynamically loaded modules.
Referenced by DynamicLoaderModule().
Network* nest::DynamicLoaderModule::pNet_ private
Referenced by DynamicLoaderModule(), nest::DynamicLoaderModule::LoadModuleFunction::execute(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), and initLinkedModules().
UnloadModuleFunction nest::DynamicLoaderModule::unloadmodule_function
Referenced by init().
The documentation for this class was generated from the following files:
dynamicloader.h
dynamicloader.cpp