NEST: nest::AnchoredParameter< D > Class Template Reference
nest::AnchoredParameter< D > Class Template Reference
Parameter class representing a parameter centered at an anchor position.
#include <parameter.h>
Public Member Functions
AnchoredParameter (const Parameter &p, const Position< D > &anchor)
AnchoredParameter (const AnchoredParameter &p)
~AnchoredParameter ()
double_t raw_value (const Position< D xor 1 > &, librandom::RngPtr &) const
double_t raw_value (const Position< D > &p, librandom::RngPtr &rng) const
Parameter * clone () const
Clone method.
Public Member Functions inherited from nest::Parameter
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
virtual double_t raw_value (const Position< 2 > &, librandom::RngPtr &) const
Raw value disregarding cutoff.
virtual double_t raw_value (const Position< 3 > &, librandom::RngPtr &) const
Raw value disregarding cutoff.
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Private Attributes
Parameter * p_
Position< D > anchor_
Detailed Description
template<int D>
class nest::AnchoredParameter< D >
Parameter class representing a parameter centered at an anchor position.
Constructor & Destructor Documentation
template<int D> nest::AnchoredParameter< D >::AnchoredParameter (const Parameter & p, const Position< D > & anchor) inline
Referenced by nest::AnchoredParameter< D >::clone().
template<int D> nest::AnchoredParameter< D >::AnchoredParameter (const AnchoredParameter< D > & p) inline
template<int D> nest::AnchoredParameter< D >::~AnchoredParameter () inline
References nest::AnchoredParameter< D >::p_.
Member Function Documentation
template<int D> Parameter* nest::AnchoredParameter< D >::clone () const inline virtual
Clone method.
Returns
dynamically allocated copy of parameter object
Implements nest::Parameter.
References nest::AnchoredParameter< D >::AnchoredParameter().
template<int D> double_t nest::AnchoredParameter< D >::raw_value (const Position< D xor 1 > & , librandom::RngPtr &) const inline
template<int D> double_t nest::AnchoredParameter< D >::raw_value (const Position< D > & p, librandom::RngPtr & rng) const inline
References nest::AnchoredParameter< D >::anchor_, nest::AnchoredParameter< D >::p_, and nest::Parameter::raw_value().
Member Data Documentation
template<int D> Position<D> nest::AnchoredParameter< D >::anchor_ private
Referenced by nest::AnchoredParameter< D >::raw_value().
template<int D> Parameter* nest::AnchoredParameter< D >::p_ private
Referenced by nest::AnchoredParameter< D >::raw_value(), and nest::AnchoredParameter< D >::~AnchoredParameter().
The documentation for this class was generated from the following file:
parameter.h