NEST: nest::TopologyModule::Distance_a_iFunction Class Reference
nest::TopologyModule::Distance_a_iFunction Class Reference
#include <topologymodule.h>
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void nest::TopologyModule::Distance_a_iFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), nest::AbstractLayer::compute_distance(), SLIInterpreter::EStack, nest::Node::get_lid(), nest::TopologyModule::get_network(), nest::Network::get_node(), nest::Node::get_parent(), nest::Network::is_local_gid(), nest::names::layer, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), and TokenStack::push().
The documentation for this class was generated from the following files:
topologymodule.h
topologymodule.cpp