NEST: Erase_pFunction Class Reference
Erase_pFunction Class Reference
#include <slidata.h>
Public Member Functions
Erase_pFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
Erase_pFunction::Erase_pFunction () inline
Member Function Documentation
void Erase_pFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References assert(), Token::datum(), SLIInterpreter::EStack, GenericDatum< D, slt >::get(), TokenStack::load(), nest::names::n, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), SLIInterpreter::PositiveIntegerExpectedError, SLIInterpreter::raiseerror(), and SLIInterpreter::RangeCheckError.
The documentation for this class was generated from the following files:
slidata.h
slidata.cc