NEST: nest::ConnectorBase Class Reference
nest::ConnectorBase Class Reference abstract
#include <connector_base.h>
Public Member Functions
ConnectorBase ()
virtual void get_synapse_status (synindex syn_id, DictionaryDatum &d, port p) const =0
virtual void set_synapse_status (synindex syn_id, ConnectorModel &cm, const DictionaryDatum &d, port p)=0
virtual size_t get_num_connections ()=0
virtual size_t get_num_connections (synindex syn_id)=0
virtual void get_connections (size_t source_gid, size_t thrd, synindex synapse_id, ArrayDatum &conns) const =0
virtual void get_connections (size_t source_gid, size_t target_gid, size_t thrd, size_t synapse_id, ArrayDatum &conns) const =0
virtual void send (Event &e, thread t, const std::vector< ConnectorModel * > &cm)=0
virtual void trigger_update_weight (long_t vt_gid, thread t, const vector< spikecounter > &dopa_spikes, double_t t_trig, const std::vector< ConnectorModel * > &cm)=0
virtual synindex get_syn_id () const =0
virtual bool homogeneous_model ()=0
virtual ~ConnectorBase ()
double_t get_t_lastspike () const
void set_t_lastspike (const double_t t_lastspike)
Private Attributes
double_t t_lastspike_
Constructor & Destructor Documentation
nest::ConnectorBase::ConnectorBase ()
virtual nest::ConnectorBase::~ConnectorBase () inline virtual
Member Function Documentation
virtual void nest::ConnectorBase::get_connections (size_t source_gid, size_t thrd, synindex synapse_id, ArrayDatum & conns) const pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
virtual void nest::ConnectorBase::get_connections (size_t source_gid, size_t target_gid, size_t thrd, size_t synapse_id, ArrayDatum & conns) const pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
virtual size_t nest::ConnectorBase::get_num_connections () pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
virtual size_t nest::ConnectorBase::get_num_connections (synindex syn_id) pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
virtual synindex nest::ConnectorBase::get_syn_id () const pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection().
virtual void nest::ConnectorBase::get_synapse_status (synindex syn_id, DictionaryDatum & d, port p) const pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
double_t nest::ConnectorBase::get_t_lastspike () const inline
References t_lastspike_.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection(), nest::Connector< K, ConnectionT >::send(), nest::Connector< 1, ConnectionT >::send(), and nest::Connector< K_cutoff, ConnectionT >::send().
virtual bool nest::ConnectorBase::homogeneous_model () pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
Referenced by nest::GenericConnectorModel< ConnectionT >::add_connection().
virtual void nest::ConnectorBase::send (Event & e, thread t, const std::vector< ConnectorModel * > & cm) pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
virtual void nest::ConnectorBase::set_synapse_status (synindex syn_id, ConnectorModel & cm, const DictionaryDatum & d, port p) pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
void nest::ConnectorBase::set_t_lastspike (const double_t t_lastspike) inline
References t_lastspike_.
Referenced by nest::Connector< K, ConnectionT >::send(), nest::Connector< 1, ConnectionT >::send(), and nest::Connector< K_cutoff, ConnectionT >::send().
virtual void nest::ConnectorBase::trigger_update_weight (long_t vt_gid, thread t, const vector< spikecounter > & dopa_spikes, double_t t_trig, const std::vector< ConnectorModel * > & cm) pure virtual
Implemented in nest::HetConnector, nest::Connector< K_cutoff, ConnectionT >, nest::Connector< 1, ConnectionT >, and nest::Connector< K, ConnectionT >.
Member Data Documentation
double_t nest::ConnectorBase::t_lastspike_ private
Referenced by get_t_lastspike(), and set_t_lastspike().
The documentation for this class was generated from the following files:
connector_base.h
connector_base.cpp