NEST: Parser Class Reference
Parser Class Reference
#include <parser.h>
Public Member Functions
Parser (void)
Parser (std::istream &)
bool operator() (Token &)
bool readToken (std::istream &is, Token &t)
bool readSymbol (std::istream &is, Token &t)
Scanner const * scan (void) const
void clear_context ()
Private Types
enum ParseResult {
tokencontinue, scancontinue, tokencompleted, noopenproc,
endprocexpected, noopenarray, endarrayexpected, unexpectedeof
}
Private Member Functions
void init (std::istream &)
Private Attributes
Scanner * s
Token arraytoken
Token proctoken
TokenStack ParseStack
Member Enumeration Documentation
enum Parser::ParseResult private
Enumerator
tokencontinue
scancontinue
tokencompleted
noopenproc
endprocexpected
noopenarray
endarrayexpected
unexpectedeof
Constructor & Destructor Documentation
Parser::Parser (void)
References assert(), init(), and s.
Parser::Parser (std::istream & is)
References assert(), init(), and s.
Member Function Documentation
void Parser::clear_context () inline
References Scanner::clear_context(), and s.
Referenced by Token_sFunction::execute(), and Symbol_sFunction::execute().
void Parser::init (std::istream & is) private
References arraytoken, and s.
Referenced by Parser().
bool Parser::operator() (Token & t)
References SLIInterpreter::Arraytype, assert(), Scanner::BeginArraySymbol, Scanner::BeginProcedureSymbol, TokenStack::clear(), Token::contains(), Token::datum(), TokenArrayObj::empty(), endarrayexpected, Scanner::EndArraySymbol, Scanner::EndProcedureSymbol, endprocexpected, Scanner::EndSymbol, Datum::isoftype(), SLIInterpreter::Litproceduretype, Token::move(), noopenarray, noopenproc, ParseStack, TokenStack::pop_move(), Scanner::print_error(), TokenStack::push(), TokenArray::push_back(), TokenStack::push_move(), s, scancontinue, Datum::set_executable(), SLIInterpreter::Symboltype, tokencompleted, tokencontinue, TokenStack::top(), and unexpectedeof.
Referenced by readToken().
bool Parser::readSymbol (std::istream & is, Token & t) inline
References s, and Scanner::source().
Referenced by Symbol_sFunction::execute().
bool Parser::readToken (std::istream & is, Token & t) inline
References operator()(), s, and Scanner::source().
Referenced by IparsestdinFunction::execute(), ParsestdinFunction::execute(), IparseFunction::execute(), Token_sFunction::execute(), and Token_isFunction::execute().
Scanner const* Parser::scan (void) const inline
References s.
Referenced by IparsestdinFunction::execute(), ParsestdinFunction::execute(), IparseFunction::execute(), Token_sFunction::execute(), Token_isFunction::execute(), Symbol_sFunction::execute(), and operator<<().
Member Data Documentation
Token Parser::arraytoken private
Referenced by init().
TokenStack Parser::ParseStack private
Referenced by operator()().
Token Parser::proctoken private
Scanner* Parser::s private
Referenced by clear_context(), init(), operator()(), Parser(), readSymbol(), readToken(), and scan().
The documentation for this class was generated from the following files:
parser.h
parser.cc