NEST: nest::Quantal_StpConnection< targetidentifierT > Class Template Reference
nest::Quantal_StpConnection< targetidentifierT > Class Template Reference
#include <quantal_stp_connection.h>
Classes
class ConnTestDummyNode
Public Types
typedef CommonSynapseProperties CommonPropertiesType
typedef Connection
< targetidentifierT > ConnectionBase
Public Member Functions
Quantal_StpConnection ()
Default Constructor.
Quantal_StpConnection (const Quantal_StpConnection &)
Copy constructor to propagate common properties.
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set default properties of this connection from the values given in dictionary.
void send (Event &e, thread t, double_t t_lastspike, const CommonSynapseProperties &cp)
Send an event to the receiver of this connection.
void check_connection (Node &s, Node &t, rport receptor_type, double_t, const CommonPropertiesType &)
void set_weight (double_t w)
Public Member Functions inherited from nest::Connection< targetidentifierT >
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Private Attributes
double_t weight_
synaptic weight
double_t U_
unit increment of a facilitating synapse (U)
double_t u_
dynamic value of probability of release
double_t tau_rec_
[ms] time constant for recovery from depression (D)
double_t tau_fac_
[ms] time constant for facilitation (F)
int n_
Number of release sites.
int a_
Number of available release sites.
Additional Inherited Members
Protected Member Functions inherited from nest::Connection< targetidentifierT >
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes inherited from nest::Connection< targetidentifierT >
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Member Typedef Documentation
template<typename targetidentifierT > typedef CommonSynapseProperties nest::Quantal_StpConnection< targetidentifierT >::CommonPropertiesType
template<typename targetidentifierT > typedef Connection<targetidentifierT> nest::Quantal_StpConnection< targetidentifierT >::ConnectionBase
Constructor & Destructor Documentation
template<typename targetidentifierT > nest::Quantal_StpConnection< targetidentifierT >::Quantal_StpConnection ()
Default Constructor.
Sets default values for all parameters. Needed by GenericConnectorModel.
template<typename targetidentifierT > nest::Quantal_StpConnection< targetidentifierT >::Quantal_StpConnection (const Quantal_StpConnection< targetidentifierT > & rhs)
Copy constructor to propagate common properties.
Member Function Documentation
template<typename targetidentifierT > void nest::Quantal_StpConnection< targetidentifierT >::check_connection (Node & s, Node & t, rport receptor_type, double_t , const CommonPropertiesType &) inline
References nest::Connection< targetidentifierT >::check_connection_().
template<typename targetidentifierT > void nest::Quantal_StpConnection< targetidentifierT >::get_status (DictionaryDatum & d) const
Get all properties of this connection and put them into a dictionary.
References nest::names::a, nest::names::d, nest::names::dU, nest::names::n, nest::names::tau_fac, nest::names::tau_rec, nest::names::u, and nest::names::weight.
template<typename targetidentifierT > void nest::Quantal_StpConnection< targetidentifierT >::send (Event & e, thread t, double_t t_lastspike, const CommonSynapseProperties & cp) inline
Send an event to the receiver of this connection.
Parameters
e The event to send
t_lastspike Point in time of last spike sent.
cp Common properties to all synapses (empty).
e The event to send
t The thread on which this connection is stored.
t_lastspike Time point of last spike emitted
cp Common properties object, containing the quantal_stp parameters.
References numerics::e, nest::Time::get_ms(), nest::Network::get_rng(), nest::Event::get_stamp(), nest::names::h, nest::Node::network(), nest::Event::set_delay(), nest::Event::set_receiver(), nest::Event::set_rport(), nest::Event::set_weight(), and nest::names::vp.
template<typename targetidentifierT > void nest::Quantal_StpConnection< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm)
Set default properties of this connection from the values given in dictionary.
References nest::names::a, nest::names::d, nest::names::dU, nest::names::n, nest::names::tau_fac, nest::names::tau_rec, nest::names::u, nest::update_value_int(), and nest::names::weight.
template<typename targetidentifierT > void nest::Quantal_StpConnection< targetidentifierT >::set_weight (double_t w) inline
References nest::names::w, and nest::Quantal_StpConnection< targetidentifierT >::weight_.
Member Data Documentation
template<typename targetidentifierT > int nest::Quantal_StpConnection< targetidentifierT >::a_ private
Number of available release sites.
template<typename targetidentifierT > int nest::Quantal_StpConnection< targetidentifierT >::n_ private
Number of release sites.
template<typename targetidentifierT > double_t nest::Quantal_StpConnection< targetidentifierT >::tau_fac_ private
[ms] time constant for facilitation (F)
template<typename targetidentifierT > double_t nest::Quantal_StpConnection< targetidentifierT >::tau_rec_ private
[ms] time constant for recovery from depression (D)
template<typename targetidentifierT > double_t nest::Quantal_StpConnection< targetidentifierT >::U_ private
unit increment of a facilitating synapse (U)
template<typename targetidentifierT > double_t nest::Quantal_StpConnection< targetidentifierT >::u_ private
dynamic value of probability of release
template<typename targetidentifierT > double_t nest::Quantal_StpConnection< targetidentifierT >::weight_ private
synaptic weight
Referenced by nest::Quantal_StpConnection< targetidentifierT >::set_weight().
The documentation for this class was generated from the following files:
quantal_stp_connection.h
quantal_stp_connection_impl.h