NEST: FilesystemModule::FileNamesFunction Class Reference
FilesystemModule::FileNamesFunction Class Reference
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void FilesystemModule::FileNamesFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References nest::names::a, assert(), SLIInterpreter::BadIOError, Token::datum(), SLIInterpreter::EStack, SLIInterpreter::OStack, TokenStack::pop(), TokenArray::push_back_move(), TokenStack::push_move(), SLIInterpreter::raiseerror(), and TokenStack::top().
The documentation for this class was generated from the following files:
filesystem.h
filesystem.cc