NEST: nest::GridMask< D > Class Template Reference
nest::GridMask< D > Class Template Reference
Mask defined in terms of grid points rather than spacial coordinates.
#include <grid_mask.h>
Public Member Functions
GridMask (const DictionaryDatum &d)
Parameters: columns - horizontal size in grid coordinates rows - vertical size in grid coordinates layers - z-size in grid coordinates (for 3D layers)
bool inside (const std::vector< double_t > &) const
void set_anchor (const Position< D, int_t > &)
DictionaryDatum get_dict () const
GridMask< D > * clone () const
AbstractMask * intersect_mask (const AbstractMask &) const
Create the intersection of this mask with another.
AbstractMask * union_mask (const AbstractMask &) const
Create the union of this mask with another.
AbstractMask * minus_mask (const AbstractMask &) const
Create the difference of this mask and another.
Position< D, int_t > get_upper_left () const
Position< D, int_t > get_lower_right () const
template<>
Name get_name ()
template<>
Name get_name ()
Public Member Functions inherited from nest::AbstractMask
virtual ~AbstractMask ()
Virtual destructor.
Static Public Member Functions
static Name get_name ()
Protected Attributes
Position< D, int_t > upper_left_
Position< D, int_t > lower_right_
Detailed Description
template<int D>
class nest::GridMask< D >
Mask defined in terms of grid points rather than spacial coordinates.
Only suitable for grid layers.
Constructor & Destructor Documentation
template<int D> nest::GridMask< D >::GridMask (const DictionaryDatum & d)
Parameters: columns - horizontal size in grid coordinates rows - vertical size in grid coordinates layers - z-size in grid coordinates (for 3D layers)
References nest::names::columns, nest::names::d, getValue< long >(), nest::names::layers, and nest::names::rows.
Referenced by nest::GridMask< D >::clone().
Member Function Documentation
template<int D> GridMask<D>* nest::GridMask< D >::clone (void) const inline
References nest::GridMask< D >::GridMask().
template<int D> DictionaryDatum nest::GridMask< D >::get_dict () const virtual
Returns
a dictionary with the definition for this mask.
Reimplemented from nest::AbstractMask.
References nest::names::columns, nest::names::d, nest::names::layers, and nest::names::rows.
template<int D> Position<D,int_t> nest::GridMask< D >::get_lower_right () const inline
References nest::GridMask< D >::lower_right_.
Referenced by nest::MaskedLayer< D >::check_mask_().
template<int D> static Name nest::GridMask< D >::get_name () static
Returns
the name of this mask type.
template<> Name nest::GridMask< 2 >::get_name () inline
References nest::names::grid.
template<> Name nest::GridMask< 3 >::get_name () inline
References nest::names::grid3d.
template<int D> Position<D,int_t> nest::GridMask< D >::get_upper_left () const inline
References nest::GridMask< D >::upper_left_.
Referenced by nest::MaskedLayer< D >::check_mask_().
template<int D> bool nest::GridMask< D >::inside (const std::vector< double_t > &) const inline virtual
Returns
true if point is inside mask.
Implements nest::AbstractMask.
template<int D> AbstractMask* nest::GridMask< D >::intersect_mask (const AbstractMask & other) const inline virtual
Create the intersection of this mask with another.
Masks must have the same dimension
Returns
a new dynamically allocated mask.
Implements nest::AbstractMask.
template<int D> AbstractMask* nest::GridMask< D >::minus_mask (const AbstractMask & other) const inline virtual
Create the difference of this mask and another.
Masks must have the same dimension.
Returns
a new dynamically allocated mask.
Implements nest::AbstractMask.
template<int D> void nest::GridMask< D >::set_anchor (const Position< D, int_t > & anchor)
References nest::names::anchor.
Referenced by nest::TopologyModule::create_mask().
template<int D> AbstractMask* nest::GridMask< D >::union_mask (const AbstractMask & other) const inline virtual
Create the union of this mask with another.
Masks must have the same dimension.
Returns
a new dynamically allocated mask.
Implements nest::AbstractMask.
Member Data Documentation
template<int D> Position<D,int_t> nest::GridMask< D >::lower_right_ protected
Referenced by nest::GridMask< D >::get_lower_right().
template<int D> Position<D,int_t> nest::GridMask< D >::upper_left_ protected
Referenced by nest::GridMask< D >::get_upper_left().
The documentation for this class was generated from the following file:
grid_mask.h