NEST: nest::NestModule::Connect_i_i_D_lFunction Class Reference
nest::NestModule::Connect_i_i_D_lFunction Class Reference
SLI Interface functions of the NEST kernel.
#include <nestmodule.h>
Public Member Functions
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Member Function Documentation
void nest::NestModule::Connect_i_i_D_lFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), nest::Network::connect(), SLIInterpreter::EStack, nest::NestModule::get_network(), nest::Network::get_node(), nest::Network::get_synapsedict(), nest::Node::get_thread(), getValue< long >(), nest::Network::is_local_gid(), Dictionary::lookup(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), nest::names::source, nest::names::target, and nest::names::target_thread.
The documentation for this class was generated from the following files:
nestmodule.h
nestmodule.cpp