NEST: nest::ConverseParameter Class Reference
nest::ConverseParameter Class Reference
Parameter class for a parameter oriented in the opposite direction.
#include <parameter.h>
Public Member Functions
ConverseParameter (const Parameter &p)
Construct the converse of the given parameter.
ConverseParameter (const ConverseParameter &p)
Copy constructor.
~ConverseParameter ()
double_t raw_value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t raw_value (const Position< 3 > &p, librandom::RngPtr &rng) const
Raw value disregarding cutoff.
Parameter * clone () const
Clone method.
Public Member Functions inherited from nest::Parameter
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Protected Attributes
Parameter * p_
Detailed Description
Parameter class for a parameter oriented in the opposite direction.
Constructor & Destructor Documentation
nest::ConverseParameter::ConverseParameter (const Parameter & p) inline
Construct the converse of the given parameter.
A copy is made of the supplied Parameter object.
Referenced by clone().
nest::ConverseParameter::ConverseParameter (const ConverseParameter & p) inline
Copy constructor.
nest::ConverseParameter::~ConverseParameter () inline
References p_.
Member Function Documentation
Parameter* nest::ConverseParameter::clone () const inline virtual
Clone method.
Returns
dynamically allocated copy of parameter object
Implements nest::Parameter.
References ConverseParameter().
double_t nest::ConverseParameter::raw_value (const Position< 2 > & p, librandom::RngPtr & rng) const inline virtual
Returns
the value of the parameter.
Reimplemented from nest::Parameter.
References p_, and nest::Parameter::raw_value().
double_t nest::ConverseParameter::raw_value (const Position< 3 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References p_, and nest::Parameter::raw_value().
Member Data Documentation
Parameter* nest::ConverseParameter::p_ protected
Referenced by raw_value(), and ~ConverseParameter().
The documentation for this class was generated from the following file:
parameter.h