NEST: nest::Multirange Class Reference
nest::Multirange Class Reference
Class for sequences of ranges acting like a compressed vector.
#include <multirange.h>
Classes
class iterator
Public Types
typedef std::pair< index, index > Range
typedef std::vector< Range > RangeVector
Public Member Functions
Multirange ()
void push_back (index x)
void clear ()
index operator[] (index n) const
index size () const
bool empty () const
iterator begin () const
iterator end () const
Private Attributes
RangeVector ranges_
index size_
Detailed Description
Class for sequences of ranges acting like a compressed vector.
Member Typedef Documentation
typedef std::pair<index,index> nest::Multirange::Range
typedef std::vector<Range> nest::Multirange::RangeVector
Constructor & Destructor Documentation
nest::Multirange::Multirange () inline
Member Function Documentation
Multirange::iterator nest::Multirange::begin () const inline
References ranges_.
void nest::Multirange::clear () inline
References ranges_, and size_.
bool nest::Multirange::empty () const inline
References size_.
Referenced by nest::Subnet::global_empty().
Multirange::iterator nest::Multirange::end () const inline
References ranges_.
nest::index nest::Multirange::operator[] (index n) const
References nest::names::n, and ranges_.
void nest::Multirange::push_back (index x) inline
References ranges_, size_, and nest::names::x.
Referenced by nest::Subnet::add_node(), and nest::Subnet::add_remote_node().
index nest::Multirange::size (void) const inline
References size_.
Referenced by nest::Subnet::add_node(), nest::Subnet::add_remote_node(), and nest::Subnet::global_size().
Member Data Documentation
RangeVector nest::Multirange::ranges_ private
Referenced by begin(), clear(), end(), operator[](), and push_back().
index nest::Multirange::size_ private
Referenced by clear(), empty(), push_back(), and size().
The documentation for this class was generated from the following files:
multirange.h
multirange.cpp