NEST: IOSShowbaseFunction Class Reference
IOSShowbaseFunction Class Reference
#include <sli_io.h>
Public Member Functions
IOSShowbaseFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
IOSShowbaseFunction::IOSShowbaseFunction () inline
Member Function Documentation
void IOSShowbaseFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::assert_stack_load(), SLIInterpreter::BadIOError, nest::names::d, Token::datum(), SLIInterpreter::EStack, Datum::gettypename(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), SLIInterpreter::raiseerror(), TokenStack::top(), Name::toString(), and lockPTR< D >::valid().
The documentation for this class was generated from the following files:
sli_io.h
sli_io.cc