NEST: nest::PseudoRecordingDevice Class Reference
nest::PseudoRecordingDevice Class Reference
Devices
Base class for all pseudo recording devices.
#include <pseudo_recording_device.h>
Public Member Functions
PseudoRecordingDevice ()
PseudoRecordingDevice (const PseudoRecordingDevice &)
virtual ~PseudoRecordingDevice ()
bool is_active (Time const &T) const
Indicate if recording device is active.
Public Member Functions inherited from nest::Device
Device ()
Device (const Device &n)
virtual ~Device ()
virtual void init_parameters (const Device &)
Reset parameters to those of model; also resets state.
virtual void init_state (const Device &)
Reset dynamic state to that of model.
virtual void init_buffers ()
Reset buffers.
virtual void calibrate ()
Set internal variables, including opening files.
virtual void finalize ()
Housekeeping at end of simulation, eg close files.
virtual void get_status (DictionaryDatum &) const
virtual void set_status (const DictionaryDatum &)
long_t get_t_min_ () const
Return lower limit in steps.
long_t get_t_max_ () const
Return upper limit in steps.
Time const & get_origin () const
Time const & get_start () const
Time const & get_stop () const
Detailed Description
Base class for all pseudo recording devices.
Pseudo-recording devices collect data. The data is only collected in memory an only available through GetStatus.
If the device is configured to record from start to stop, this is interpreted as (start, stop], i.e., the earliest recorded event will have time stamp start+1, as it was generated during the update step (start, start+1].
Note
The sole purpose of this class is to provide an implementation of is_active().
Author
HEP 2002-07-22, 2008-03-21, 2008-07-01
Constructor & Destructor Documentation
nest::PseudoRecordingDevice::PseudoRecordingDevice () inline
nest::PseudoRecordingDevice::PseudoRecordingDevice (const PseudoRecordingDevice & prd) inline
virtual nest::PseudoRecordingDevice::~PseudoRecordingDevice () inline virtual
Member Function Documentation
bool nest::PseudoRecordingDevice::is_active (Time const & T) const inline virtual
Indicate if recording device is active.
The argument is the time stamp of the event, and the device is active if start_ < T <= stop_.
Implements nest::Device.
References nest::Time::get_steps(), nest::Device::get_t_max_(), and nest::Device::get_t_min_().
The documentation for this class was generated from the following file:
pseudo_recording_device.h