NEST: nest::Connector< K_cutoff, ConnectionT > Class Template Reference
nest::Connector< K_cutoff, ConnectionT > Class Template Reference
#include <connector_base.h>
Public Member Functions
Connector (const Connector< K_cutoff-1, ConnectionT > &C, const ConnectionT &c)
~Connector ()
void get_synapse_status (synindex syn_id, DictionaryDatum &d, port p) const
void set_synapse_status (synindex syn_id, ConnectorModel &cm, const DictionaryDatum &d, port p)
size_t get_num_connections ()
size_t get_num_connections (synindex syn_id)
Connector< K_cutoff,
ConnectionT > & push_back (const ConnectionT &c)
void get_connections (size_t source_gid, size_t thrd, synindex synapse_id, ArrayDatum &conns) const
void get_connections (size_t source_gid, size_t target_gid, size_t thrd, size_t synapse_id, ArrayDatum &conns) const
void send (Event &e, thread t, const std::vector< ConnectorModel * > &cm)
void trigger_update_weight (long_t vt_gid, thread t, const vector< spikecounter > &dopa_spikes, double_t t_trig, const std::vector< ConnectorModel * > &cm)
synindex get_syn_id () const
bool homogeneous_model ()
Public Member Functions inherited from nest::ConnectorBase
ConnectorBase ()
virtual ~ConnectorBase ()
double_t get_t_lastspike () const
void set_t_lastspike (const double_t t_lastspike)
Private Attributes
std::vector< ConnectionT > C_
Constructor & Destructor Documentation
template<typename ConnectionT > nest::Connector< K_cutoff, ConnectionT >::Connector (const Connector< K_cutoff-1, ConnectionT > & C, const ConnectionT & c) inline
References nest::names::c, nest::Connector< K, ConnectionT >::C_, and nest::Connector< K, ConnectionT >::get_C().
template<typename ConnectionT > nest::Connector< K_cutoff, ConnectionT >::~Connector () inline
Member Function Documentation
template<typename ConnectionT > void nest::Connector< K_cutoff, ConnectionT >::get_connections (size_t source_gid, size_t thrd, synindex synapse_id, ArrayDatum & conns) const inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and TokenArray::push_back().
template<typename ConnectionT > void nest::Connector< K_cutoff, ConnectionT >::get_connections (size_t source_gid, size_t target_gid, size_t thrd, size_t synapse_id, ArrayDatum & conns) const inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and TokenArray::push_back().
template<typename ConnectionT > size_t nest::Connector< K_cutoff, ConnectionT >::get_num_connections () inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_.
template<typename ConnectionT > size_t nest::Connector< K_cutoff, ConnectionT >::get_num_connections (synindex syn_id) inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, and nest::Connector< K, ConnectionT >::get_syn_id().
template<typename ConnectionT > synindex nest::Connector< K_cutoff, ConnectionT >::get_syn_id () const inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_.
template<typename ConnectionT > void nest::Connector< K_cutoff, ConnectionT >::get_synapse_status (synindex syn_id, DictionaryDatum & d, port p) const inline virtual
Implements nest::ConnectorBase.
References assert(), nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and nest::names::p.
template<typename ConnectionT > bool nest::Connector< K_cutoff, ConnectionT >::homogeneous_model () inline virtual
Implements nest::ConnectorBase.
template<typename ConnectionT > Connector<K_cutoff, ConnectionT>& nest::Connector< K_cutoff, ConnectionT >::push_back (const ConnectionT & c) inline virtual
Implements nest::vector_like< ConnectionT >.
References nest::Connector< K, ConnectionT >::C_.
template<typename ConnectionT > void nest::Connector< K_cutoff, ConnectionT >::send (Event & e, thread t, const std::vector< ConnectorModel * > & cm) inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::Time::get_ms(), nest::Event::get_stamp(), nest::ConnectorBase::get_t_lastspike(), nest::Event::set_port(), and nest::ConnectorBase::set_t_lastspike().
template<typename ConnectionT > void nest::Connector< K_cutoff, ConnectionT >::set_synapse_status (synindex syn_id, ConnectorModel & cm, const DictionaryDatum & d, port p) inline virtual
Implements nest::ConnectorBase.
References assert(), nest::Connector< K, ConnectionT >::C_, nest::Connector< K, ConnectionT >::get_syn_id(), and nest::names::p.
template<typename ConnectionT > void nest::Connector< K_cutoff, ConnectionT >::trigger_update_weight (long_t vt_gid, thread t, const vector< spikecounter > & dopa_spikes, double_t t_trig, const std::vector< ConnectorModel * > & cm) inline virtual
Implements nest::ConnectorBase.
References nest::Connector< K, ConnectionT >::C_, nest::GenericConnectorModel< ConnectionT >::get_common_properties(), and nest::Connector< K, ConnectionT >::trigger_update_weight().
Member Data Documentation
template<typename ConnectionT > std::vector<ConnectionT> nest::Connector< K_cutoff, ConnectionT >::C_ private
The documentation for this class was generated from the following file:
connector_base.h