NEST: CounttomarkFunction Class Reference
CounttomarkFunction Class Reference
#include <slicontrol.h>
Public Member Functions
CounttomarkFunction ()
void execute (SLIInterpreter *) const
Public Member Functions inherited from SLIFunction
SLIFunction ()
virtual ~SLIFunction ()
virtual void backtrace (SLIInterpreter *, int) const
Show stack backtrace information on error.
Constructor & Destructor Documentation
CounttomarkFunction::CounttomarkFunction () inline
Member Function Documentation
void CounttomarkFunction::execute (SLIInterpreter * i) const virtual
Implements SLIFunction.
References SLIInterpreter::baselookup(), nest::names::depth, SLIInterpreter::EStack, SLIInterpreter::getcurrentname(), TokenStack::load(), SLIInterpreter::mark_name, SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push_move(), and SLIInterpreter::raiseerror().
The documentation for this class was generated from the following files:
slicontrol.h
slicontrol.cc