NEST: nest::GenericConnectorModel< ConnectionT > Class Template Reference
nest::GenericConnectorModel< ConnectionT > Class Template Reference
#include <connector_model.h>
Public Member Functions
GenericConnectorModel (Network &net, const std::string name)
GenericConnectorModel (const GenericConnectorModel &cm, const std::string name)
ConnectorBase * add_connection (Node &src, Node &tgt, ConnectorBase *conn, synindex syn_id, double_t weight, double_t delay)
delay and weight have the default value NAN.
ConnectorBase * add_connection (Node &src, Node &tgt, ConnectorBase *conn, synindex syn_id, DictionaryDatum &d, double_t weight, double_t delay)
delay and weight have the default value NAN.
ConnectorModel * clone (std::string) const
void calibrate (const TimeConverter &tc)
void get_status (DictionaryDatum &) const
void set_status (const DictionaryDatum &)
ConnectionT::CommonPropertiesType
const & get_common_properties () const
void set_syn_id (synindex syn_id)
ConnectionT const & get_default_connection () const
Public Member Functions inherited from nest::ConnectorModel
ConnectorModel (Network &net, const std::string)
ConnectorModel (const ConnectorModel &, const std::string)
virtual ~ConnectorModel ()
size_t get_num_connections () const
const Time & get_min_delay () const
const Time & get_max_delay () const
void update_delay_extrema (const double_t mindelay_cand, const double_t maxdelay_cand)
void assert_valid_delay_ms (double_t)
Raise exception if delay value in milliseconds is invalid.
void assert_two_valid_delays_steps (long_t, long_t)
Raise exception if either of the two delays in steps is invalid.
std::string get_name () const
bool get_user_set_delay_extrema () const
Network & network () const
Private Member Functions
void used_default_delay ()
ConnectorBase * add_connection (Node &src, Node &tgt, ConnectorBase *conn, synindex syn_id, ConnectionT &c, rport receptor_type)
Private Attributes
ConnectionT::CommonPropertiesType cp_
ConnectionT default_connection_
rport receptor_type_
Additional Inherited Members
Protected Attributes inherited from nest::ConnectorModel
Network & net_
The Network instance.
Time min_delay_
Minimal delay of all created synapses.
Time max_delay_
Maximal delay of all created synapses.
size_t num_connections_
The number of connections registered with this type.
bool default_delay_needs_check_
Flag indicating, that the default delay must be checked.
bool user_set_delay_extrema_
Flag indicating if the user set the delay extrema.
bool used_default_delay_
std::string name_
Constructor & Destructor Documentation
template<typename ConnectionT > nest::GenericConnectorModel< ConnectionT >::GenericConnectorModel (Network & net, const std::string name) inline
template<typename ConnectionT > nest::GenericConnectorModel< ConnectionT >::GenericConnectorModel (const GenericConnectorModel< ConnectionT > & cm, const std::string name) inline
Member Function Documentation
template<typename ConnectionT > ConnectorBase * nest::GenericConnectorModel< ConnectionT >::add_connection (Node & src, Node & tgt, ConnectorBase * conn, synindex syn_id, double_t delay, double_t weight) virtual
delay and weight have the default value NAN.
NAN is a special value in cmath, which describes double values that are not a number. If delay or weight is omitted in an add_connection call, NAN indicates this and weight/delay are set only, if they are valid.
Implements nest::ConnectorModel.
References nest::names::c.
template<typename ConnectionT > ConnectorBase * nest::GenericConnectorModel< ConnectionT >::add_connection (Node & src, Node & tgt, ConnectorBase * conn, synindex syn_id, DictionaryDatum & p, double_t delay, double_t weight) virtual
delay and weight have the default value NAN.
NAN is a special value in cmath, which describes double values that are not a number. If delay or weight is omitted in an add_connection call, NAN indicates this and weight/delay are set only, if they are valid.
Implements nest::ConnectorModel.
References nest::names::c, nest::names::delay, nest::names::music_channel, nest::names::p, and nest::names::receptor_type.
template<typename ConnectionT > ConnectorBase * nest::GenericConnectorModel< ConnectionT >::add_connection (Node & src, Node & tgt, ConnectorBase * conn, synindex syn_id, ConnectionT & c, rport receptor_type) private
References nest::names::c, nest::ConnectorBase::get_syn_id(), nest::ConnectorBase::get_t_lastspike(), nest::ConnectorBase::homogeneous_model(), and nest::vector_like< ConnectionT >::push_back().
template<typename ConnectionT > void nest::GenericConnectorModel< ConnectionT >::calibrate (const TimeConverter & tc) virtual
Implements nest::ConnectorModel.
References nest::TimeConverter::from_old_steps().
template<typename ConnectionT > ConnectorModel * nest::GenericConnectorModel< ConnectionT >::clone (std::string name) const virtual
Implements nest::ConnectorModel.
template<typename ConnectionT > ConnectionT::CommonPropertiesType const& nest::GenericConnectorModel< ConnectionT >::get_common_properties () const inline virtual
Implements nest::ConnectorModel.
References nest::GenericConnectorModel< ConnectionT >::cp_.
Referenced by nest::Connector< K_cutoff, ConnectionT >::trigger_update_weight().
template<typename ConnectionT > ConnectionT const& nest::GenericConnectorModel< ConnectionT >::get_default_connection () const inline
References nest::GenericConnectorModel< ConnectionT >::default_connection_.
template<typename ConnectionT > void nest::GenericConnectorModel< ConnectionT >::get_status (DictionaryDatum & d) const virtual
Implements nest::ConnectorModel.
References nest::names::receptor_type.
template<typename ConnectionT > void nest::GenericConnectorModel< ConnectionT >::set_status (const DictionaryDatum & d) virtual
Implements nest::ConnectorModel.
References nest::names::d, nest::Time::get_resolution(), SLIInterpreter::M_ERROR, nest::names::music_channel, and nest::names::receptor_type.
template<typename ConnectionT > void nest::GenericConnectorModel< ConnectionT >::set_syn_id (synindex syn_id) virtual
Implements nest::ConnectorModel.
template<typename ConnectionT > void nest::GenericConnectorModel< ConnectionT >::used_default_delay () private
Member Data Documentation
template<typename ConnectionT > ConnectionT::CommonPropertiesType nest::GenericConnectorModel< ConnectionT >::cp_ private
Referenced by nest::GenericConnectorModel< ConnectionT >::get_common_properties().
template<typename ConnectionT > ConnectionT nest::GenericConnectorModel< ConnectionT >::default_connection_ private
Referenced by nest::GenericConnectorModel< ConnectionT >::get_default_connection().
template<typename ConnectionT > rport nest::GenericConnectorModel< ConnectionT >::receptor_type_ private
The documentation for this class was generated from the following files:
connector_model.h
connector_model_impl.h