NEST: nest::Connection< targetidentifierT > Class Template Reference
nest::Connection< targetidentifierT > Class Template Reference
Base class for representing connections.
#include <connection.h>
Public Member Functions
Connection ()
Connection (const Connection< targetidentifierT > &rhs)
void get_status (DictionaryDatum &d) const
Get all properties of this connection and put them into a dictionary.
void set_status (const DictionaryDatum &d, ConnectorModel &cm)
Set properties of this connection from the values given in dictionary.
void calibrate (const TimeConverter &)
Calibrate the delay of this connection to the desired resolution.
double_t get_delay () const
Return the delay of the connection in ms.
long_t get_delay_steps () const
Return the delay of the connection in steps.
void set_delay (const double_t delay)
Set the delay of the connection.
void set_delay_steps (const long_t delay)
Set the delay of the connection in steps.
void set_syn_id (synindex syn_id)
Set the synapse id of the connection.
synindex get_syn_id () const
Get the synapse id of the connection.
void trigger_update_weight (const thread, const std::vector< spikecounter > &, const double_t, const CommonSynapseProperties &)
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Node * get_target (thread t) const
rport get_rport () const
Protected Member Functions
void check_connection_ (Node &dummy_target, Node &source, Node &target, rport receptor_type)
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Protected Attributes
targetidentifierT target_
SynIdDelay syn_id_delay_
syn_id (char) and delay (24 bit) in timesteps of this connection
Detailed Description
template<typename targetidentifierT>
class nest::Connection< targetidentifierT >
Base class for representing connections.
It provides the mandatory properties receiver port and target, as well as the functions get_status() and set_status() to read and write them. A suitable Connector containing these connections can be obtained from the template GenericConnector.
Constructor & Destructor Documentation
template<typename targetidentifierT> nest::Connection< targetidentifierT >::Connection () inline
template<typename targetidentifierT> nest::Connection< targetidentifierT >::Connection (const Connection< targetidentifierT > & rhs) inline
Member Function Documentation
template<typename targetidentifierT > void nest::Connection< targetidentifierT >::calibrate (const TimeConverter & tc) inline
Calibrate the delay of this connection to the desired resolution.
References nest::TimeConverter::from_old_steps(), and nest::Time::get_steps().
template<typename targetidentifierT > void nest::Connection< targetidentifierT >::check_connection_ (Node & dummy_target, Node & source, Node & target, rport receptor_type) inline protected
This function calls check_connection() on the sender to check if the receiver accepts the event type and receptor type requested by the sender.
Parameters
s The source node
r The target node
receptor The ID of the requested receptor type
the last spike produced by the presynaptic neuron (for STDP and maturing connections)
References nest::Node::send_test_event().
Referenced by nest::StaticConnectionHomW< targetidentifierT >::check_connection(), nest::StaticConnection< targetidentifierT >::check_connection(), nest::ContDelayConnection< targetidentifierT >::check_connection(), nest::HTConnection< targetidentifierT >::check_connection(), nest::Quantal_StpConnection< targetidentifierT >::check_connection(), nest::Tsodyks2Connection< targetidentifierT >::check_connection(), nest::STDPConnection< targetidentifierT >::check_connection(), nest::TsodyksConnection< targetidentifierT >::check_connection(), nest::STDPPLConnectionHom< targetidentifierT >::check_connection(), nest::STDPConnectionHom< targetidentifierT >::check_connection(), nest::STDPDopaConnection< targetidentifierT >::check_connection(), and nest::STDPFACETSHWConnectionHom< targetidentifierT >::check_connection().
template<typename targetidentifierT> double_t nest::Connection< targetidentifierT >::get_delay () const inline
Return the delay of the connection in ms.
References nest::SynIdDelay::get_delay_ms(), and nest::Connection< targetidentifierT >::syn_id_delay_.
Referenced by nest::STDPConnection< targetidentifierT >::check_connection(), nest::STDPPLConnectionHom< targetidentifierT >::check_connection(), nest::STDPConnectionHom< targetidentifierT >::check_connection(), nest::STDPDopaConnection< targetidentifierT >::check_connection(), and nest::STDPFACETSHWConnectionHom< targetidentifierT >::check_connection().
template<typename targetidentifierT> long_t nest::Connection< targetidentifierT >::get_delay_steps () const inline
Return the delay of the connection in steps.
References nest::SynIdDelay::delay, and nest::Connection< targetidentifierT >::syn_id_delay_.
Referenced by nest::StaticConnectionHomW< targetidentifierT >::send(), and nest::StaticConnection< targetidentifierT >::send().
template<typename targetidentifierT> rport nest::Connection< targetidentifierT >::get_rport () const inline
References nest::Connection< targetidentifierT >::target_.
Referenced by nest::StaticConnectionHomW< targetidentifierT >::send(), and nest::StaticConnection< targetidentifierT >::send().
template<typename targetidentifierT > void nest::Connection< targetidentifierT >::get_status (DictionaryDatum & d) const inline
Get all properties of this connection and put them into a dictionary.
References nest::names::d, and nest::names::delay.
template<typename targetidentifierT> synindex nest::Connection< targetidentifierT >::get_syn_id () const inline
Get the synapse id of the connection.
References nest::SynIdDelay::syn_id, and nest::Connection< targetidentifierT >::syn_id_delay_.
template<typename targetidentifierT> Node* nest::Connection< targetidentifierT >::get_target (thread t) const inline
References nest::Connection< targetidentifierT >::target_.
Referenced by nest::StaticConnectionHomW< targetidentifierT >::send(), and nest::StaticConnection< targetidentifierT >::send().
template<typename targetidentifierT> void nest::Connection< targetidentifierT >::set_delay (const double_t delay) inline
Set the delay of the connection.
References nest::SynIdDelay::set_delay_ms(), and nest::Connection< targetidentifierT >::syn_id_delay_.
template<typename targetidentifierT> void nest::Connection< targetidentifierT >::set_delay_steps (const long_t delay) inline
Set the delay of the connection in steps.
References nest::SynIdDelay::delay, and nest::Connection< targetidentifierT >::syn_id_delay_.
template<typename targetidentifierT > void nest::Connection< targetidentifierT >::set_status (const DictionaryDatum & d, ConnectorModel & cm) inline
Set properties of this connection from the values given in dictionary.
Note
Target and Rport cannot be changed after a connection has been created.
References nest::ConnectorModel::assert_valid_delay_ms(), and nest::names::delay.
template<typename targetidentifierT> void nest::Connection< targetidentifierT >::set_syn_id (synindex syn_id) inline
Set the synapse id of the connection.
References nest::SynIdDelay::syn_id, and nest::Connection< targetidentifierT >::syn_id_delay_.
template<typename targetidentifierT > void nest::Connection< targetidentifierT >::trigger_update_weight (const thread , const std::vector< spikecounter > & , const double_t , const CommonSynapseProperties &) inline
triggers an update of a synaptic weight this function is needed for neuromodulated synaptic plasticity
Member Data Documentation
template<typename targetidentifierT> SynIdDelay nest::Connection< targetidentifierT >::syn_id_delay_ protected
syn_id (char) and delay (24 bit) in timesteps of this connection
Referenced by nest::Connection< targetidentifierT >::get_delay(), nest::Connection< targetidentifierT >::get_delay_steps(), nest::Connection< targetidentifierT >::get_syn_id(), nest::Connection< targetidentifierT >::set_delay(), nest::Connection< targetidentifierT >::set_delay_steps(), and nest::Connection< targetidentifierT >::set_syn_id().
template<typename targetidentifierT> targetidentifierT nest::Connection< targetidentifierT >::target_ protected
Referenced by nest::Connection< targetidentifierT >::get_rport(), and nest::Connection< targetidentifierT >::get_target().
The documentation for this class was generated from the following file:
connection.h