NEST: nest::NormalParameter Class Reference
nest::NormalParameter Class Reference
Random parameter with normal distribution, optionally truncated to [min,max).
#include <parameter.h>
Public Member Functions
NormalParameter (const DictionaryDatum &d)
Parameters: mean - mean value sigma - standard distribution min - minimum value max - maximum value.
double_t raw_value (librandom::RngPtr &rng) const
double_t raw_value (const Position< 2 > &, librandom::RngPtr &rng) const
Raw value disregarding cutoff.
double_t raw_value (const Position< 3 > &, librandom::RngPtr &rng) const
Raw value disregarding cutoff.
Parameter * clone () const
Clone method.
Public Member Functions inherited from nest::Parameter
Parameter ()
Default constructor.
Parameter (double_t cutoff)
Constructor.
Parameter (const DictionaryDatum &d)
Constructor Parameter that can be set in the Dictionary: cutoff - Values less than the cutoff are set to zero.
virtual ~Parameter ()
Virtual destructor.
double_t value (const Position< 2 > &p, librandom::RngPtr &rng) const
double_t value (const Position< 3 > &p, librandom::RngPtr &rng) const
double_t value (const std::vector< double_t > &pt, librandom::RngPtr &rng) const
virtual Parameter * multiply_parameter (const Parameter &other) const
Create the product of this parameter with another.
virtual Parameter * divide_parameter (const Parameter &other) const
Create the quotient of this parameter with another.
virtual Parameter * add_parameter (const Parameter &other) const
Create the sum of this parameter with another.
virtual Parameter * subtract_parameter (const Parameter &other) const
Create the difference of this parameter with another.
Private Attributes
double_t mean_
double_t sigma_
double_t min_
double_t max_
librandom::NormalRandomDev rdev
Detailed Description
Random parameter with normal distribution, optionally truncated to [min,max).
Truncation is implemented by rejection.
Constructor & Destructor Documentation
nest::NormalParameter::NormalParameter (const DictionaryDatum & d) inline
Parameters: mean - mean value sigma - standard distribution min - minimum value max - maximum value.
References nest::names::d, nest::names::max, max_, nest::names::mean, mean_, nest::names::min, min_, nest::names::sigma, and sigma_.
Referenced by clone().
Member Function Documentation
Parameter* nest::NormalParameter::clone () const inline virtual
Clone method.
Returns
dynamically allocated copy of parameter object
Implements nest::Parameter.
References NormalParameter().
double_t nest::NormalParameter::raw_value (librandom::RngPtr & rng) const inline
References max_, mean_, min_, rdev, and sigma_.
Referenced by raw_value().
double_t nest::NormalParameter::raw_value (const Position< 2 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References raw_value().
double_t nest::NormalParameter::raw_value (const Position< 3 > & , librandom::RngPtr &) const inline virtual
Raw value disregarding cutoff.
Returns
the value of the parameter at the given point.
Reimplemented from nest::Parameter.
References raw_value().
Member Data Documentation
double_t nest::NormalParameter::max_ private
Referenced by NormalParameter(), and raw_value().
double_t nest::NormalParameter::mean_ private
Referenced by NormalParameter(), and raw_value().
double_t nest::NormalParameter::min_ private
Referenced by NormalParameter(), and raw_value().
librandom::NormalRandomDev nest::NormalParameter::rdev private
Referenced by raw_value().
double_t nest::NormalParameter::sigma_ private
Referenced by NormalParameter(), and raw_value().
The documentation for this class was generated from the following file:
parameter.h