NEST: fdbuf Class Reference
fdbuf Class Reference
#include <fdstream.h>
Public Member Functions
fdbuf ()
fdbuf (int fd)
~fdbuf ()
bool is_open () const
fdbuf * open (const char *, std::ios_base::openmode)
fdbuf * close ()
int fd ()
Return the underlying file descriptor.
Protected Member Functions
int_type underflow ()
int_type overflow (int_type c)
int sync ()
Private Attributes
int m_fd
bool m_isopen
char m_inbuf [s_bufsiz]
char m_outbuf [s_bufsiz]
Static Private Attributes
static std::streamsize const s_bufsiz =1024
Constructor & Destructor Documentation
fdbuf::fdbuf () inline
References m_outbuf, and s_bufsiz.
fdbuf::fdbuf (int fd) inline
References m_outbuf, and s_bufsiz.
fdbuf::~fdbuf () inline
References close().
Member Function Documentation
fdbuf * fdbuf::close ()
References is_open(), m_fd, m_isopen, overflow(), and nest::names::success.
Referenced by open(), and ~fdbuf().
int fdbuf::fd () inline
Return the underlying file descriptor.
Now this is why we are doing all this!!
References m_fd.
Referenced by Processes::fd().
bool fdbuf::is_open () const inline
References m_isopen.
Referenced by close(), ofdstream::is_open(), ifdstream::is_open(), fdstream::is_open(), and open().
fdbuf * fdbuf::open (const char * s, std::ios_base::openmode mode)
References nest::names::binary, close(), is_open(), m_fd, m_isopen, and nest::names::std.
int_type fdbuf::overflow (int_type c) inline protected
References nest::names::c, and sync().
Referenced by close().
int fdbuf::sync () inline protected
References m_fd, m_outbuf, and s_bufsiz.
Referenced by overflow().
int_type fdbuf::underflow () inline protected
References m_fd, m_inbuf, and s_bufsiz.
Member Data Documentation
int fdbuf::m_fd private
Referenced by close(), fd(), open(), sync(), and underflow().
char fdbuf::m_inbuf[s_bufsiz] private
Referenced by underflow().
bool fdbuf::m_isopen private
Referenced by close(), is_open(), and open().
char fdbuf::m_outbuf[s_bufsiz] private
Referenced by fdbuf(), and sync().
std::streamsize const fdbuf::s_bufsiz =1024 static private
Referenced by fdbuf(), sync(), and underflow().
The documentation for this class was generated from the following files:
fdstream.h
fdstream.cc