NEST: nest::ListRingBuffer Class Reference
nest::ListRingBuffer Class Reference
#include <ring_buffer.h>
Public Member Functions
ListRingBuffer ()
void append_value (const long_t offs, const double_t)
Append a value to the ring buffer list.
std::list< double_t > & get_list (const long_t offs)
void clear ()
Initialize the buffer with empty lists.
void resize ()
Resize the buffer according to max_thread and max_delay.
size_t size () const
Returns buffer size, for memory measurement.
Private Member Functions
size_t get_index_ (const delay d) const
Obtain buffer index.
Private Attributes
std::vector< std::list
< double_t > > buffer_
Buffered data.
Constructor & Destructor Documentation
nest::ListRingBuffer::ListRingBuffer ()
Member Function Documentation
void nest::ListRingBuffer::append_value (const long_t offs, const double_t v) inline
Append a value to the ring buffer list.
Parameters
offs Arrival time relative to beginning of slice.
double_t Value to append.
References buffer_, and get_index_().
void nest::ListRingBuffer::clear ()
Initialize the buffer with empty lists.
Also resizes the buffer if necessary.
References resize().
size_t nest::ListRingBuffer::get_index_ (const delay d) const inline private
Obtain buffer index.
Parameters
delay delivery delay for event
Returns
index to buffer element into which event should be recorded.
References assert(), buffer_, and nest::Scheduler::get_modulo().
Referenced by append_value(), and get_list().
std::list< double_t > & nest::ListRingBuffer::get_list (const long_t offs) inline
References assert(), buffer_, get_index_(), and nest::Scheduler::get_min_delay().
void nest::ListRingBuffer::resize ()
Resize the buffer according to max_thread and max_delay.
New elements are filled with empty lists.
Note
resize() has no effect if the buffer has the correct size.
References nest::Scheduler::get_max_delay(), and nest::Scheduler::get_min_delay().
size_t nest::ListRingBuffer::size (void) const inline
Returns buffer size, for memory measurement.
References buffer_.
Member Data Documentation
std::vector<std::list<double_t> > nest::ListRingBuffer::buffer_ private
Buffered data.
Referenced by append_value(), get_index_(), get_list(), and size().
The documentation for this class was generated from the following files:
ring_buffer.h
ring_buffer.cpp