NEST: nest::Time Class Reference
nest::Time Class Reference
#include <nest_time.h>
Classes
struct Limit
struct LimitNegInf
struct LimitPosInf
struct ms
struct ms_stamp
struct Range
struct step
struct tic
Public Member Functions
Time ()
Time (tic t)
Time (step t)
Time (ms t)
Time (ms_stamp t)
void set_to_zero ()
void advance ()
Time succ () const
Time pred () const
bool is_finite () const
bool is_neg_inf () const
bool is_grid_time () const
bool is_step () const
bool is_multiple_of (const Time &divisor) const
void range ()
void calibrate ()
Time & operator+= (const Time &t)
tic_t get_tics () const
double_t get_ms () const
delay get_steps () const
Static Public Member Functions
static tic_t compute_max ()
static tic_t fromstamp (ms_stamp)
static void set_resolution (double_t tics_per_ms)
static void set_resolution (double_t tics_per_ms, double_t ms_per_step)
static void reset_resolution ()
static void reset_to_defaults ()
static Time get_resolution ()
static bool resolution_is_default ()
static Time max ()
static Time min ()
static double_t get_ms_per_tic ()
static Time neg_inf ()
static Time pos_inf ()
static tic_t get_tics_per_step ()
static double_t get_tics_per_ms ()
static double_t delay_steps_to_ms (delay steps)
Convert between delays given in steps and milliseconds.
static delay delay_ms_to_steps (double_t ms)
Protected Member Functions
Time::Limit limit (const tic_t &)
Time (tic_t tics)
Protected Attributes
tic_t tics
Static Protected Attributes
static Limit LIM_MAX
static Limit LIM_MIN
static struct
nest::Time::LimitPosInf LIM_POS_INF
static struct
nest::Time::LimitNegInf LIM_NEG_INF
Friends
struct step
struct tic
struct ms
struct ms_stamp
bool operator== (const Time &t1, const Time &t2)
bool operator!= (const Time &t1, const Time &t2)
bool operator< (const Time &t1, const Time &t2)
bool operator> (const Time &t1, const Time &t2)
bool operator<= (const Time &t1, const Time &t2)
bool operator>= (const Time &t1, const Time &t2)
Time operator+ (const Time &t1, const Time &t2)
Time operator- (const Time &t1, const Time &t2)
Time operator* (const long_t factor, const Time &t)
Time operator* (const Time &t, long_t factor)
std::ostream & operator<<) (std::ostream &, const Time &)
Constructor & Destructor Documentation
nest::Time::Time (tic_t tics) inline explicit protected
nest::Time::Time () inline
Referenced by get_resolution(), max(), min(), neg_inf(), and pos_inf().
nest::Time::Time (tic t) inline
nest::Time::Time (step t) inline
nest::Time::Time (ms t) inline
nest::Time::Time (ms_stamp t) inline
Member Function Documentation
void nest::Time::advance () inline
References range(), tics, and nest::Time::Range::TICS_PER_STEP.
Referenced by nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_().
void nest::Time::calibrate () inline
References range().
Referenced by nest::Scheduler::calibrate_clock(), nest::ConnectorModel::ConnectorModel(), nest::noise_generator::Parameters_::Parameters_(), nest::Device::Parameters_::Parameters_(), nest::correlomatrix_detector::Parameters_::Parameters_(), nest::correlation_detector::Parameters_::Parameters_(), and nest::Multimeter::Parameters_::Parameters_().
tic_t Time::compute_max () static
References nest::Time::Range::INF_MARGIN, nest::names::max, tics, and nest::Time::Range::TICS_PER_STEP.
Referenced by reset_resolution(), and set_resolution().
static delay nest::Time::delay_ms_to_steps (double_t ms) inline static
References ld_round(), and nest::Time::Range::STEPS_PER_MS.
Referenced by nest::SynIdDelay::set_delay_ms(), and nest::ContDelayConnection< targetidentifierT >::set_status().
static double_t nest::Time::delay_steps_to_ms (delay steps) inline static
Convert between delays given in steps and milliseconds.
This is not a reversible operation, since steps have a finite rounding resolution. This is not a truncation, but rounding as per ld_round, which is different from ms_stamp –> Time mapping, which rounds up. See #903.
References nest::Time::Range::MS_PER_STEP.
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), and nest::SynIdDelay::get_delay_ms().
tic_t Time::fromstamp (Time::ms_stamp t) static
References LIM_MAX, LIM_MIN, LIM_NEG_INF, LIM_POS_INF, nest::Time::Limit::ms, nest::Time::Range::MS_PER_STEP, nest::names::n, nest::Time::ms_stamp::t, nest::Time::LimitPosInf::tics, nest::Time::LimitNegInf::tics, nest::Time::Range::TICS_PER_MS, and nest::Time::Range::TICS_PER_STEP.
double_t nest::Time::get_ms () const inline
References LIM_NEG_INF, LIM_POS_INF, nest::Time::Range::MS_PER_TIC, tics, nest::Time::LimitPosInf::tics, and nest::Time::LimitNegInf::tics.
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), nest::ConnectorModel::assert_valid_delay_ms(), nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_(), nest::ac_generator::calibrate(), nest::iaf_psc_exp_multisynapse::calibrate(), nest::iaf_psc_alpha_multisynapse::calibrate(), nest::gamma_sup_generator::calibrate(), nest::ppd_sup_generator::calibrate(), nest::sinusoidal_poisson_generator::calibrate(), nest::iaf_chs_2007::calibrate(), nest::noise_generator::calibrate(), nest::sinusoidal_gamma_generator::calibrate(), nest::iaf_psc_exp::calibrate(), nest::iaf_neuron::calibrate(), nest::iaf_psc_delta::calibrate(), nest::mat2_psc_exp::calibrate(), nest::iaf_psc_alpha::calibrate(), nest::iaf_tum_2000::calibrate(), nest::iaf_psc_alpha_presc::calibrate(), nest::amat2_psc_exp::calibrate(), nest::iaf_psc_exp_ps::calibrate(), nest::pp_psc_delta::calibrate(), nest::pp_pop_psc_delta::calibrate(), nest::iaf_psc_alpha_canon::calibrate(), nest::iaf_psc_delta_canon::calibrate(), nest::poisson_generator_ps::event_hook(), nest::iaf_psc_alpha_presc::State_::get(), nest::iaf_psc_exp_ps::State_::get(), nest::iaf_psc_delta_canon::State_::get(), nest::iaf_psc_alpha_canon::State_::get(), nest::iaf_chxk_2008::get_r_(), nest::iaf_cond_alpha::get_r_(), nest::iaf_cond_alpha_mc::get_r_(), nest::ContDelayConnection< targetidentifierT >::get_status(), nest::music_event_out_proxy::handle(), nest::aeif_cond_alpha_multisynapse::init_buffers_(), nest::iaf_cond_exp::init_buffers_(), nest::aeif_cond_alpha_RK5::init_buffers_(), nest::iaf_chxk_2008::init_buffers_(), nest::hh_cond_exp_traub::init_buffers_(), nest::iaf_cond_exp_sfa_rr::init_buffers_(), nest::iaf_cond_alpha::init_buffers_(), nest::aeif_cond_alpha::init_buffers_(), nest::aeif_cond_exp::init_buffers_(), nest::ht_neuron::init_buffers_(), nest::hh_psc_alpha::init_buffers_(), nest::iaf_cond_alpha_mc::init_buffers_(), operator<<(), nest::Scheduler::prepare_nodes(), nest::Scheduler::prepare_simulation(), nest::RecordingDevice::print_time_(), nest::HTConnection< targetidentifierT >::send(), nest::Quantal_StpConnection< targetidentifierT >::send(), nest::Tsodyks2Connection< targetidentifierT >::send(), nest::STDPConnection< targetidentifierT >::send(), nest::STDPPLConnectionHom< targetidentifierT >::send(), nest::TsodyksConnection< targetidentifierT >::send(), nest::STDPConnectionHom< targetidentifierT >::send(), nest::STDPDopaConnection< targetidentifierT >::send(), nest::Connector< K, ConnectionT >::send(), nest::STDPFACETSHWConnectionHom< targetidentifierT >::send(), nest::Connector< 1, ConnectionT >::send(), nest::Connector< K_cutoff, ConnectionT >::send(), nest::Archiving_Node::set_spiketime(), nest::ContDelayConnection< targetidentifierT >::set_status(), nest::RecordingDevice::store_data_(), nest::MusicEventHandler::update(), nest::ppd_sup_generator::update(), nest::izhikevich::update(), nest::volume_transmitter::update(), nest::sinusoidal_gamma_generator::update(), and nest::iaf_psc_delta::update().
static double_t nest::Time::get_ms_per_tic () inline static
References nest::Time::Range::MS_PER_TIC.
Referenced by nest::Scheduler::prepare_nodes().
static Time nest::Time::get_resolution () inline static
References nest::Time::Range::TICS_PER_STEP, and Time().
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), nest::ConnectorModel::assert_valid_delay_ms(), nest::ac_generator::calibrate(), nest::iaf_psc_exp_multisynapse::calibrate(), nest::iaf_psc_alpha_multisynapse::calibrate(), nest::gamma_sup_generator::calibrate(), nest::ppd_sup_generator::calibrate(), nest::sinusoidal_poisson_generator::calibrate(), nest::iaf_chs_2007::calibrate(), nest::noise_generator::calibrate(), nest::poisson_generator::calibrate(), nest::mip_generator::calibrate(), nest::sinusoidal_gamma_generator::calibrate(), nest::iaf_psc_exp::calibrate(), nest::iaf_neuron::calibrate(), nest::iaf_psc_delta::calibrate(), nest::mat2_psc_exp::calibrate(), nest::iaf_psc_alpha::calibrate(), nest::iaf_tum_2000::calibrate(), nest::iaf_psc_alpha_presc::calibrate(), nest::amat2_psc_exp::calibrate(), nest::iaf_psc_exp_ps::calibrate(), nest::pp_psc_delta::calibrate(), nest::pp_pop_psc_delta::calibrate(), nest::iaf_psc_alpha_canon::calibrate(), nest::iaf_psc_delta_canon::calibrate(), nest::iaf_chxk_2008::get_r_(), nest::iaf_cond_alpha::get_r_(), nest::iaf_cond_alpha_mc::get_r_(), nest::aeif_cond_alpha_multisynapse::init_buffers_(), nest::iaf_cond_exp::init_buffers_(), nest::aeif_cond_alpha_RK5::init_buffers_(), nest::iaf_chxk_2008::init_buffers_(), nest::hh_cond_exp_traub::init_buffers_(), nest::iaf_cond_exp_sfa_rr::init_buffers_(), nest::iaf_cond_alpha::init_buffers_(), nest::aeif_cond_alpha::init_buffers_(), nest::aeif_cond_exp::init_buffers_(), nest::ht_neuron::init_buffers_(), nest::hh_psc_alpha::init_buffers_(), nest::iaf_cond_alpha_mc::init_buffers_(), nest::InvalidDefaultResolution::message(), nest::InvalidTimeInModel::message(), nest::StepMultipleRequired::message(), nest::Scheduler::prepare_nodes(), nest::Scheduler::prepare_simulation(), nest::ContDelayConnection< targetidentifierT >::send(), nest::Multimeter::Parameters_::set(), nest::ContDelayConnection< targetidentifierT >::set_status(), nest::GenericConnectorModel< ConnectionT >::set_status(), nest::Scheduler::simulate(), nest::izhikevich::update(), nest::iaf_psc_delta::update(), and nest::Scheduler::update_delay_extrema_().
delay nest::Time::get_steps () const inline
References LIM_NEG_INF, LIM_POS_INF, nest::Time::LimitPosInf::steps, nest::Time::LimitNegInf::steps, tics, nest::Time::LimitPosInf::tics, nest::Time::LimitNegInf::tics, nest::Time::Range::TICS_PER_STEP, and nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::ConnectorModel::assert_two_valid_delays_steps(), nest::iaf_psc_exp_multisynapse::calibrate(), nest::iaf_psc_alpha_multisynapse::calibrate(), nest::Connection< targetidentifierT >::calibrate(), nest::aeif_cond_alpha_multisynapse::calibrate(), nest::iaf_cond_exp::calibrate(), nest::aeif_cond_alpha_RK5::calibrate(), nest::iaf_cond_exp_sfa_rr::calibrate(), nest::iaf_cond_alpha::calibrate(), nest::iaf_psc_exp::calibrate(), nest::aeif_cond_alpha::calibrate(), nest::iaf_neuron::calibrate(), nest::mat2_psc_exp::calibrate(), nest::aeif_cond_exp::calibrate(), nest::iaf_psc_alpha::calibrate(), nest::iaf_tum_2000::calibrate(), nest::ht_neuron::calibrate(), nest::iaf_psc_alpha_presc::calibrate(), nest::amat2_psc_exp::calibrate(), nest::iaf_psc_exp_ps::calibrate(), nest::hh_psc_alpha::calibrate(), nest::pp_psc_delta::calibrate(), nest::iaf_cond_alpha_mc::calibrate(), nest::iaf_psc_alpha_canon::calibrate(), nest::iaf_psc_delta_canon::calibrate(), nest::iaf_psc_exp_ps::emit_instant_spike_(), nest::iaf_psc_delta_canon::emit_instant_spike_(), nest::iaf_psc_alpha_canon::emit_instant_spike_(), nest::iaf_psc_exp_ps::emit_spike_(), nest::iaf_psc_delta_canon::emit_spike_(), nest::iaf_psc_alpha_canon::emit_spike_(), nest::Event::get_rel_delivery_steps(), nest::parrot_neuron_ps::handle(), nest::correlomatrix_detector::handle(), nest::iaf_psc_exp_ps::handle(), nest::correlation_detector::handle(), nest::iaf_psc_alpha_canon::handle(), nest::iaf_psc_delta_canon::handle(), nest::pp_psc_delta::init_state_(), nest::PseudoRecordingDevice::is_active(), nest::StimulatingDevice< EmittedEvent >::is_active(), nest::Multimeter::is_active(), nest::RecordingDevice::is_active(), nest::operator<(), operator<<(), nest::RecordingDevice::print_time_(), nest::correlomatrix_detector::State_::reset(), nest::correlation_detector::State_::reset(), nest::iaf_psc_alpha_presc::set_spiketime(), nest::iaf_psc_exp_ps::set_spiketime(), nest::iaf_psc_delta_canon::set_spiketime(), nest::iaf_psc_alpha_canon::set_spiketime(), nest::Scheduler::simulate(), nest::RecordingDevice::store_data_(), nest::MusicEventHandler::update(), nest::ac_generator::update(), nest::step_current_generator::update(), nest::binary_neuron< TGainfunction >::update(), nest::dc_generator::update(), nest::iaf_psc_exp_multisynapse::update(), nest::pulsepacket_generator::update(), nest::iaf_psc_alpha_multisynapse::update(), nest::parrot_neuron_ps::update(), nest::parrot_neuron::update(), nest::sinusoidal_poisson_generator::update(), nest::aeif_cond_alpha_multisynapse::update(), nest::iaf_chs_2007::update(), nest::iaf_cond_exp::update(), nest::izhikevich::update(), nest::noise_generator::update(), nest::sli_neuron::update(), nest::aeif_cond_alpha_RK5::update(), nest::iaf_chxk_2008::update(), nest::hh_cond_exp_traub::update(), nest::iaf_cond_exp_sfa_rr::update(), nest::iaf_cond_alpha::update(), nest::iaf_psc_exp::update(), nest::sinusoidal_gamma_generator::update(), nest::aeif_cond_alpha::update(), nest::iaf_neuron::update(), nest::mat2_psc_exp::update(), nest::iaf_psc_delta::update(), nest::aeif_cond_exp::update(), nest::iaf_psc_alpha::update(), nest::iaf_tum_2000::update(), nest::ht_neuron::update(), nest::amat2_psc_exp::update(), nest::hh_psc_alpha::update(), nest::pp_psc_delta::update(), nest::pp_pop_psc_delta::update(), nest::iaf_psc_alpha_presc::update(), nest::iaf_cond_alpha_mc::update(), nest::iaf_psc_exp_ps::update(), nest::Multimeter::update(), nest::spike_generator::update(), nest::iaf_psc_alpha_canon::update(), nest::iaf_psc_delta_canon::update(), and nest::Scheduler::update_delay_extrema_().
tic_t nest::Time::get_tics () const inline
References tics.
Referenced by operator<<().
static double_t nest::Time::get_tics_per_ms () inline static
References nest::Time::Range::TICS_PER_MS.
Referenced by nest::Scheduler::prepare_nodes(), and nest::TimeConverter::TimeConverter().
static tic_t nest::Time::get_tics_per_step () inline static
References nest::Time::Range::TICS_PER_STEP.
Referenced by nest::Scheduler::prepare_nodes(), and nest::TimeConverter::TimeConverter().
bool nest::Time::is_finite () const inline
References LIM_NEG_INF, LIM_POS_INF, tics, nest::Time::LimitPosInf::tics, and nest::Time::LimitNegInf::tics.
Referenced by nest::DataLoggingRequest::get_recording_interval(), and nest::Scheduler::simulate().
bool nest::Time::is_grid_time () const inline
References tics, and nest::Time::Range::TICS_PER_STEP.
Referenced by nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_(), and is_step().
bool nest::Time::is_multiple_of (const Time & divisor) const inline
References assert(), and tics.
Referenced by nest::correlomatrix_detector::State_::reset(), and nest::correlation_detector::State_::reset().
bool nest::Time::is_neg_inf () const inline
References LIM_NEG_INF, tics, and nest::Time::LimitNegInf::tics.
bool nest::Time::is_step () const inline
References is_grid_time(), and tics.
Referenced by nest::correlation_detector::correlation_detector(), nest::correlomatrix_detector::correlomatrix_detector(), and nest::noise_generator::noise_generator().
Time::Limit nest::Time::limit (const tic_t &) protected
static Time nest::Time::max () inline static
References LIM_MAX, nest::Time::Limit::tics, and Time().
Referenced by nest::Scheduler::prepare_nodes(), reset_resolution(), set_resolution(), and nest::Scheduler::simulate().
static Time nest::Time::min () inline static
References LIM_MIN, nest::Time::Limit::tics, and Time().
Referenced by nest::Scheduler::prepare_nodes().
static Time nest::Time::neg_inf () inline static
References LIM_NEG_INF, nest::Time::LimitNegInf::tics, and Time().
Referenced by nest::poisson_generator_ps::calibrate(), and nest::poisson_generator_ps::init_buffers_().
Time& nest::Time::operator+= (const Time & t) inline
References range(), and tics.
static Time nest::Time::pos_inf () inline static
References LIM_POS_INF, nest::Time::LimitPosInf::tics, and Time().
Referenced by nest::Scheduler::update_delay_extrema_().
Time nest::Time::pred () const inline
References tic, tics, and nest::Time::Range::TICS_PER_STEP.
void nest::Time::range () inline
References LIM_MAX, LIM_NEG_INF, LIM_POS_INF, tics, nest::Time::Limit::tics, nest::Time::LimitPosInf::tics, nest::Time::LimitNegInf::tics, and nest::time_abs().
Referenced by advance(), calibrate(), and operator+=().
void Time::reset_resolution () static
References compute_max(), LIM_MAX, LIM_MIN, max(), nest::Time::Range::OLD_TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_DEFAULT, and nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::NestModule::init().
void Time::reset_to_defaults () static
References nest::Time::Range::MS_PER_STEP, nest::Time::Range::MS_PER_TIC, nest::Time::Range::STEPS_PER_MS, nest::Time::Range::TICS_PER_MS, nest::Time::Range::TICS_PER_MS_DEFAULT, nest::Time::Range::TICS_PER_STEP, nest::Time::Range::TICS_PER_STEP_DEFAULT, and nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::TimeModifier::reset_to_defaults().
static bool nest::Time::resolution_is_default () inline static
References nest::Time::Range::TICS_PER_STEP, and nest::Time::Range::TICS_PER_STEP_DEFAULT.
Referenced by nest::Scheduler::prepare_nodes().
void Time::set_resolution (double_t tics_per_ms) static
References assert(), compute_max(), dround(), LIM_MAX, LIM_MIN, max(), nest::Time::Range::MS_PER_STEP, nest::Time::Range::OLD_TICS_PER_STEP, nest::Time::Range::STEPS_PER_MS, nest::Time::Range::TICS_PER_MS, nest::Time::Range::TICS_PER_STEP, and nest::Time::Range::TICS_PER_STEP_RND.
Referenced by nest::Scheduler::prepare_nodes(), set_resolution(), and nest::TimeModifier::set_time_representation().
void Time::set_resolution (double_t tics_per_ms, double_t ms_per_step) static
References nest::Time::Range::MS_PER_TIC, set_resolution(), and nest::Time::Range::TICS_PER_MS.
void nest::Time::set_to_zero () inline
References tics.
Time nest::Time::succ () const inline
References tic, tics, and nest::Time::Range::TICS_PER_STEP.
Friends And Related Function Documentation
friend struct ms friend
Referenced by nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_(), nest::iaf_psc_alpha_multisynapse::calibrate(), nest::NestModule::SimulateFunction::execute(), nest::TimeConverter::from_old_steps(), nest::TimeConverter::from_old_tics(), nest::Device::Parameters_::set(), nest::correlomatrix_detector::Parameters_::set(), nest::correlation_detector::Parameters_::set(), nest::spike_generator::set_status(), nest::MusicEventHandler::update(), and nest::binary_neuron< TGainfunction >::update().
friend struct ms_stamp friend
Referenced by nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_(), and nest::poisson_generator_ps::event_hook().
bool operator!= (const Time & t1, const Time & t2) friend
Time operator* (const long_t factor, const Time & t) friend
Time operator* (const Time & t, long_t factor) friend
Time operator+ (const Time & t1, const Time & t2) friend
Time operator- (const Time & t1, const Time & t2) friend
bool operator< (const Time & t1, const Time & t2) friend
std::ostream& operator<<) (std::ostream & , const Time &) friend
bool operator<= (const Time & t1, const Time & t2) friend
bool operator== (const Time & t1, const Time & t2) friend
bool operator> (const Time & t1, const Time & t2) friend
bool operator>= (const Time & t1, const Time & t2) friend
friend struct step friend
Referenced by nest::ConnectorModel::assert_valid_delay_ms(), nest::Scheduler::get_previous_slice_origin(), nest::iaf_psc_alpha_presc::get_spiketime(), nest::iaf_psc_delta_canon::get_spiketime(), nest::Scheduler::get_time(), nest::Scheduler::prepare_nodes(), nest::Multimeter::Parameters_::set(), nest::gamma_sup_generator::update(), nest::ppd_sup_generator::update(), and nest::spike_generator::update().
friend struct tic friend
Referenced by nest::operator*(), nest::operator+(), nest::operator-(), pred(), and succ().
Member Data Documentation
Time::Limit Time::LIM_MAX static protected
Referenced by fromstamp(), max(), range(), reset_resolution(), and set_resolution().
Time::Limit Time::LIM_MIN static protected
Referenced by fromstamp(), min(), reset_resolution(), and set_resolution().
struct nest::Time::LimitNegInf nest::Time::LIM_NEG_INF static protected
Referenced by fromstamp(), get_ms(), get_steps(), is_finite(), is_neg_inf(), neg_inf(), nest::operator*(), operator<<(), and range().
struct nest::Time::LimitPosInf nest::Time::LIM_POS_INF static protected
Referenced by fromstamp(), get_ms(), get_steps(), is_finite(), nest::operator*(), operator<<(), pos_inf(), and range().
tic_t nest::Time::tics protected
Referenced by advance(), compute_max(), get_ms(), get_steps(), get_tics(), is_finite(), is_grid_time(), is_multiple_of(), is_neg_inf(), is_step(), nest::operator!=(), nest::operator*(), nest::operator+(), operator+=(), nest::operator-(), nest::operator<(), operator<<(), nest::operator<=(), nest::operator==(), nest::operator>(), nest::operator>=(), pred(), range(), set_to_zero(), and succ().
The documentation for this class was generated from the following files:
nest_time.h
nest_time.cpp