NEST: get_mem.c File Reference
get_mem.c File Reference
Typedefs
typedef uint32_t bgmemsize_t
Functions
unsigned long bg_get_heap_mem ()
unsigned long bg_get_stack_mem ()
unsigned long darwin_get_used_mem ()
Typedef Documentation
typedef uint64_t bgmemsize_t
Function Documentation
unsigned long bg_get_heap_mem ()
References nest::names::memory.
Referenced by Processes::MemoryThisjobBgFunction::execute().
unsigned long bg_get_stack_mem ()
References nest::names::memory.
Referenced by Processes::MemoryThisjobBgFunction::execute().
unsigned long darwin_get_used_mem ()
References assert().
Referenced by Processes::MemoryThisjobDarwinFunction::execute().