NEST: gnureadline.cc File Reference
gnureadline.cc File Reference
Functions
char * readline (const char *)
void add_history (const char *)
int read_history (const char *)
int write_history (const char *)
void using_history ()
void clear_history ()
Function Documentation
void add_history (const char *)
Referenced by GNUReadline::GNUAddhistoryFunction::execute().
void clear_history ()
Referenced by nest::Archiving_Node::set_status(), and GNUReadline::~GNUReadline().
int read_history (const char *)
Referenced by GNUReadline::init().
char* readline (const char *)
Referenced by GNUReadline::GNUReadlineFunction::execute().
void using_history ()
Referenced by GNUReadline::init().
int write_history (const char *)
Referenced by GNUReadline::GNUAddhistoryFunction::execute().