NEST: Displaying messages to the user
Displaying messages to the user
How to notify the SLI user
Functions
void nest::Network::message (int level, const char from[], const char text[])
Display a message.
void SLIInterpreter::verbosity (int)
Set the verbosity level of the SLI messaging mechanism.
int SLIInterpreter::verbosity (void) const
Retrieve the current verbosity level of the SLI messaging mechanism.
void SLIInterpreter::message (int level, const char from[], const char text[], const char errorname[]="") const
Display a message.
Detailed Description
Function Documentation
void nest::Network::message (int level, const char from[], const char text[])
Display a message.
This function displays a message at a specific error level. Messages with an error level above M_ERROR will be written to std::cerr in addition to std::cout.
The message will ony be displayed if the current verbosity level is greater than or equal to the input level.
References nest::Network::interpreter_, and SLIInterpreter::message().
Referenced by nest::Network::add_node(), nest::RecordingDevice::calibrate(), nest::cg_connect(), nest::Network::clear_models_(), nest::Network::connect(), nest::Network::convergent_connect(), nest::Network::divergent_connect(), nest::TopologyModule::CreateLayer_DFunction::execute(), nest::TopologyModule::ConnectLayers_i_i_DFunction::execute(), nest::TopologyModule::CreateMask_DFunction::execute(), nest::TopologyModule::CreateParameter_DFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), nest::NestModule::SetStatus_aaFunction::execute(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::NestModule::GetConnections_DFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), nest::Network::execute_sli_protected(), nest::RecordingDevice::finalize(), nest::Network::message(), nest::MusicEventHandler::publish_port(), nest::Network::random_convergent_connect(), nest::Network::random_divergent_connect(), nest::Network::reset_network(), nest::RecordingDevice::Parameters_::set(), nest::Network::set_data_path_prefix_(), and nest::Network::set_status_single_node_().
void SLIInterpreter::message (int level, const char from[], const char text[], const char errorname[] = "") const
Display a message.
Parameters
level The error level that shall be associated with the message. You may use any poitive integer here. For conveniency, there exist five predifined error levels:
(SLIInterpreter::M_ALL=0, for use with verbosity(int) only, see there),
SLIInterpreter::M_DEBUG=5, a debugging message
SLIInterpreter::M_DEBUG=7, a status message
SLIInterpreter::M_INFO=10, an informational message
SLIInterpreter::M_WARNING=20, a warning message
SLIInterpreter::M_ERROR=30, an error message
SLIInterpreter::M_FATAL=40, a failure message. (SLIInterpreter::M_QUIET=100, for use with verbosity(int) only, see there),
from A string specifying the name of the function that sends the message.
test A string specifying the message text.
The message will ony be displayed if the current verbosity level is greater than or equal to the specified level.
If two or more messages are issued after each other, that have the same from and level argument, the messages will be grouped toghether in the output.
See also
verbosity(void), verbosity(int)
References SLIInterpreter::M_ALL_NAME, SLIInterpreter::M_DEBUG, SLIInterpreter::M_DEBUG_NAME, SLIInterpreter::M_ERROR, SLIInterpreter::M_ERROR_NAME, SLIInterpreter::M_FATAL, SLIInterpreter::M_FATAL_NAME, SLIInterpreter::M_INFO, SLIInterpreter::M_INFO_NAME, SLIInterpreter::M_STATUS, SLIInterpreter::M_STATUS_NAME, SLIInterpreter::M_WARNING, SLIInterpreter::M_WARNING_NAME, and SLIInterpreter::verbositylevel.
Referenced by SLIInterpreter::addmodule(), SLIInterpreter::backtrace_off(), SLIInterpreter::backtrace_on(), SLIStartup::checkenvpath(), AddtotrieFunction::execute(), Get_a_aFunction::execute(), SLIgraphics::ReadPGMFunction::execute(), SLIArrayModule::IMap_ivFunction::execute(), SLIgraphics::WritePGMFunction::execute(), nest::ConnectionGeneratorModule::CGConnect_cg_i_i_D_lFunction::execute(), SLIArrayModule::IMap_dvFunction::execute(), nest::DynamicLoaderModule::LoadModuleFunction::execute(), nest::DynamicLoaderModule::UnloadModuleFunction::execute(), DictconstructFunction::execute(), CloseinputFunction::execute(), SLIArrayModule::ArraycreateFunction::execute(), Join_sFunction::execute(), StopFunction::execute(), SLIArrayModule::SortFunction::execute(), StartFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), SLIArrayModule::AreaFunction::execute(), Processes::ForkFunction::execute(), RaiseerrorFunction::execute(), SLIArrayModule::Area2Function::execute(), SLIArrayModule::Cv1dFunction::execute(), SLIArrayModule::Cv2dFunction::execute(), SLIArrayModule::GetMaxFunction::execute(), nest::NestModule::SimulateFunction::execute(), SLIArrayModule::GetMinFunction::execute(), SLIArrayModule::GaborFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), SLIArrayModule::Add_iv_ivFunction::execute(), SLIArrayModule::Sub_iv_ivFunction::execute(), SLIArrayModule::Mul_iv_ivFunction::execute(), nest::NestModule::ResetNetworkFunction::execute(), SLIArrayModule::Div_iv_ivFunction::execute(), SLIArrayModule::Add_dv_dvFunction::execute(), SLIArrayModule::Sub_dv_dvFunction::execute(), SLIArrayModule::Mul_dv_dvFunction::execute(), SLIArrayModule::Div_dv_dvFunction::execute(), PclocksFunction::execute(), SLIArrayModule::Inv_dvFunction::execute(), PclockspersecFunction::execute(), PgetrusageFunction::execute(), MessageFunction::execute(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), nest::DynamicLoaderModule::init(), SLIStartup::init(), nest::DynamicLoaderModule::initLinkedModules(), SLIModule::install(), DynModule::install(), nest::Network::message(), SLIInterpreter::print_error(), SLIInterpreter::terminate(), and SLIInterpreter::toggle_stack_display().
void SLIInterpreter::verbosity (int l)
Set the verbosity level of the SLI messaging mechanism.
Only messages having an error level that is equal to or greater than this level will be displayed by the interpreter.
See also
verbosity(void), message(), debug(), status(), info(), warning(), error(), fatal()
References SLIInterpreter::verbositylevel.
Referenced by SetVerbosityFunction::execute(), VerbosityFunction::execute(), and SLIStartup::init().
int SLIInterpreter::verbosity (void) const
Retrieve the current verbosity level of the SLI messaging mechanism.
Only messages having an error level that is equal to or greater than this level will be displayed by the interpreter.
You may use any positive integer here. For conveniency, there exist five predifined error levels:
SLIInterpreter::M_ALL=0, display all messages
SLIInterpreter::M_DEBUG=5, display debugging messages and above
SLIInterpreter::M_DEBUG=7, display status messages and above
SLIInterpreter::M_INFO=10, display information messages and above
SLIInterpreter::M_WARNING=20, display warning messages and above
SLIInterpreter::M_ERROR=30, display error messages and above
SLIInterpreter::M_FATAL=40, display failure messages and above
SLIInterpreter::M_QUIET=100, suppress all messages
Thus, by calling verbosity(SLIInterpreter::M_WARNING) you indicate that you are interested in seeing error messages and more important messages only.
See also
verbosity(void), message(), debug(), status(), info(), warning(), error(), fatal()
References SLIInterpreter::verbositylevel.