NEST: Network access
Network access
Functions to access network nodes.
Functions
Node * nest::Network::get_node (index, thread thr=0)
Return pointer of the specified Node.
const SiblingContainer * nest::Network::get_thread_siblings (index n) const
Return the Subnet that contains the thread siblings.
Detailed Description
Functions to access network nodes.
Function Documentation
Node * nest::Network::get_node (index n, thread thr = 0)
Return pointer of the specified Node.
Parameters
i Index of the specified Node.
thr global thread index of the Node.
Exceptions
nest::UnknownNode Target does not exist in the network.
References nest::Modelrangemanager::get_model_id(), nest::SparseNodeArray::get_node_by_gid(), nest::Node::get_thread_sibling_(), nest::Network::local_nodes_, nest::Network::node_model_ids_, nest::Node::num_thread_siblings_(), and nest::Network::proxy_nodes_.
Referenced by nest::cg_connect(), nest::Network::connect(), nest::Network::convergent_connect(), nest::AbstractLayer::create_layer(), nest::Network::divergent_connect(), nest::ConnectionCreator::divergent_connect_(), nest::TopologyModule::GetPosition_iFunction::execute(), nest::TopologyModule::Displacement_a_iFunction::execute(), nest::TopologyModule::Distance_a_iFunction::execute(), nest::TopologyModule::GetGlobalChildren_i_M_aFunction::execute(), nest::TopologyModule::ConnectLayers_i_i_DFunction::execute(), nest::NestModule::ChangeSubnet_iFunction::execute(), nest::TopologyModule::DumpLayerNodes_os_iFunction::execute(), nest::TopologyModule::DumpLayerConnections_os_i_lFunction::execute(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), nest::TopologyModule::GetElement_i_iaFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), nest::NestModule::GetStatus_CFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), nest::NestModule::GetVpRngFunction::execute(), nest::Network::get_status(), nest::Network::go_to(), nest::Network::init_state(), nest::Network::print(), nest::proxynode::proxynode(), nest::Network::random_convergent_connect(), nest::Network::random_divergent_connect(), nest::Network::restore_nodes(), and nest::STDPDopaCommonProperties::set_status().
const SiblingContainer * nest::Network::get_thread_siblings (index n) const
Return the Subnet that contains the thread siblings.
Parameters
i Index of the specified Node.
Exceptions
nest::NoThreadSiblingsAvailable Node does not have thread siblings.
References assert(), nest::SparseNodeArray::get_node_by_gid(), nest::Network::local_nodes_, and nest::Node::num_thread_siblings_().