NEST: Configuration interface.
Configuration interface.
Functions and infrastructure, responsible for the configuration of Nodes from the SLI Interpreter level.
Functions
void nest::Model::set_status (DictionaryDatum)
Change properties of the prototype node according to the entries in the dictionary.
DictionaryDatum nest::Model::get_status (void)
Export properties of the prototype node by setting entries in the status dictionary.
virtual void nest::Node::set_status (const DictionaryDatum &)=0
Change properties of the node according to the entries in the dictionary.
virtual void nest::Node::get_status (DictionaryDatum &) const =0
Export properties of the node by setting entries in the status dictionary.
Detailed Description
Functions and infrastructure, responsible for the configuration of Nodes from the SLI Interpreter level.
Each node can be configured from the SLI level through a named parameter interface. In order to change parameters, the user can specify name value pairs for each parameter. These pairs are stored in a data structure which is called Dictionary. Likewise, the user can query the configuration of any node by requesting a dictionary with name value pairs.
The configuration interface consists of four functions which implement storage and retrieval of named parameter sets.
Function Documentation
DictionaryDatum nest::Model::get_status (void)
Export properties of the prototype node by setting entries in the status dictionary.
Parameters
d Dictionary.
References nest::names::d, nest::Model::get_name(), nest::Model::get_status_(), nest::Model::memory_, nest::Node::network(), and nest::Model::type_id_.
Referenced by nest::NestModule::GetDefaults_lFunction::execute().
virtual void nest::Node::get_status (DictionaryDatum &) const pure virtual
Export properties of the node by setting entries in the status dictionary.
Parameters
d Dictionary.
Referenced by nest::Node::get_status_base().
void nest::Model::set_status (DictionaryDatum d)
Change properties of the prototype node according to the entries in the dictionary.
Parameters
d Dictionary with named parameter settings.
References numerics::e, nest::Model::get_name(), nest::BadProperty::message(), and nest::Model::set_status_().
Referenced by nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), and nest::register_preconf_model().
virtual void nest::Node::set_status (const DictionaryDatum &) pure virtual
Change properties of the node according to the entries in the dictionary.
Parameters
d Dictionary with named parameter settings.
Referenced by nest::Node::set_status_base().