NEST: Helper functions for nestmodule.
Helper functions for nestmodule.
Functions
static Network & nest::NestModule::get_network ()
Return a reference to the network managed by nestmodule.
static index nest::NestModule::get_num_threads ()
Get number of threads.
Detailed Description
Function Documentation
Network & nest::NestModule::get_network () inline static
Return a reference to the network managed by nestmodule.
References assert(), and nest::NestModule::net_.
Referenced by nest::NestModule::ChangeSubnet_iFunction::execute(), nest::NestModule::CurrentSubnetFunction::execute(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), nest::NestModule::GetStatus_iFunction::execute(), nest::NestModule::GetStatus_CFunction::execute(), nest::NestModule::GetStatus_aFunction::execute(), nest::NestModule::SetStatus_idFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), nest::NestModule::SetStatus_aaFunction::execute(), nest::NestModule::SetDefaults_l_DFunction::execute(), nest::NestModule::GetDefaults_lFunction::execute(), nest::NestModule::CopyModel_l_l_DFunction::execute(), nest::NestModule::GetConnections_DFunction::execute(), nest::NestModule::SimulateFunction::execute(), nest::NestModule::ResumeSimulationFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), nest::NestModule::RestoreNodes_aFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), nest::NestModule::DataConnect_aFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), nest::NestModule::Connect_g_g_D_DFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute(), nest::NestModule::ResetKernelFunction::execute(), nest::NestModule::ResetNetworkFunction::execute(), nest::NestModule::MemoryInfoFunction::execute(), nest::NestModule::PrintNetworkFunction::execute(), nest::NestModule::SetNumRecProcessesFunction_i::execute(), nest::NestModule::GetVpRngFunction::execute(), nest::NestModule::GetGlobalRngFunction::execute(), nest::NestModule::SetAcceptableLatencyFunction::execute(), nest::NestModule::SetMaxBufferedFunction::execute(), nest::TargetIdentifierIndex::get_target_ptr(), nest::RecordingDevice::Parameters_::set(), nest::STDPDopaCommonProperties::set_status(), and nest::TargetIdentifierIndex::set_target().
index nest::NestModule::get_num_threads () inline static
Get number of threads.
Todo:
This functions is a hack, to make the number of threads globally available. It should obviously be part of Scheduler or Network, but implementing it there would require a major re-design of the class.
References nest::Network::get_num_threads(), and nest::NestModule::net_.
Referenced by nest::Model::set_threads().