NEST: sparsehash_internal Namespace Reference
sparsehash_internal Namespace Reference
Classes
struct pod_serializer
class sh_hashtable_settings
Functions
template<typename Ignored >
bool read_data_internal (Ignored *, FILE *fp, void *data, size_t length)
template<typename Ignored >
bool write_data_internal (Ignored *, FILE *fp, const void *data, size_t length)
template<typename ISTREAM >
bool read_data_internal_for_istream (ISTREAM *fp, void *data, size_t length)
template<typename Ignored >
bool read_data_internal (Ignored *, std::istream *fp, void *data, size_t length)
template<typename OSTREAM >
bool write_data_internal_for_ostream (OSTREAM *fp, const void *data, size_t length)
template<typename Ignored >
bool write_data_internal (Ignored *, std::ostream *fp, const void *data, size_t length)
template<typename INPUT >
bool read_data_internal (INPUT *fp, void *, void *data, size_t length)
template<typename OUTPUT >
bool write_data_internal (OUTPUT *fp, void *, const void *data, size_t length)
template<typename INPUT >
bool read_data (INPUT *fp, void *data, size_t length)
template<typename OUTPUT >
bool write_data (OUTPUT *fp, const void *data, size_t length)
template<typename INPUT , typename IntType >
bool read_bigendian_number (INPUT *fp, IntType *value, size_t length)
template<typename OUTPUT , typename IntType >
bool write_bigendian_number (OUTPUT *fp, IntType value, size_t length)
Function Documentation
template<typename INPUT , typename IntType > bool sparsehash_internal::read_bigendian_number (INPUT * fp, IntType * value, size_t length)
References read_data().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::read_32_or_64(), and sparsegroup< T, GROUP_SIZE, Alloc >::read_metadata().
template<typename INPUT > bool sparsehash_internal::read_data (INPUT * fp, void * data, size_t length) inline
References read_data_internal().
Referenced by sparsehash_internal::pod_serializer< value_type >::operator()(), read_bigendian_number(), sparsegroup< T, GROUP_SIZE, Alloc >::read_metadata(), and sparsegroup< T, GROUP_SIZE, Alloc >::read_nopointer_data().
template<typename Ignored > bool sparsehash_internal::read_data_internal (Ignored * , FILE * fp, void * data, size_t length) inline
Referenced by read_data().
template<typename Ignored > bool sparsehash_internal::read_data_internal (Ignored * , std::istream * fp, void * data, size_t length) inline
References read_data_internal_for_istream().
template<typename INPUT > bool sparsehash_internal::read_data_internal (INPUT * fp, void * , void * data, size_t length) inline
template<typename ISTREAM > bool sparsehash_internal::read_data_internal_for_istream (ISTREAM * fp, void * data, size_t length) inline
Referenced by read_data_internal().
template<typename OUTPUT , typename IntType > bool sparsehash_internal::write_bigendian_number (OUTPUT * fp, IntType value, size_t length)
References write_data().
Referenced by sparsetable< T, GROUP_SIZE, Alloc >::write_32_or_64(), and sparsegroup< T, GROUP_SIZE, Alloc >::write_metadata().
template<typename OUTPUT > bool sparsehash_internal::write_data (OUTPUT * fp, const void * data, size_t length) inline
References write_data_internal().
Referenced by sparsehash_internal::pod_serializer< value_type >::operator()(), write_bigendian_number(), sparsegroup< T, GROUP_SIZE, Alloc >::write_metadata(), and sparsegroup< T, GROUP_SIZE, Alloc >::write_nopointer_data().
template<typename Ignored > bool sparsehash_internal::write_data_internal (Ignored * , FILE * fp, const void * data, size_t length) inline
Referenced by write_data().
template<typename Ignored > bool sparsehash_internal::write_data_internal (Ignored * , std::ostream * fp, const void * data, size_t length) inline
References write_data_internal_for_ostream().
template<typename OUTPUT > bool sparsehash_internal::write_data_internal (OUTPUT * fp, void * , const void * data, size_t length) inline
template<typename OSTREAM > bool sparsehash_internal::write_data_internal_for_ostream (OSTREAM * fp, const void * data, size_t length) inline
Referenced by write_data_internal().