NEST: neststartup.h File Reference
neststartup.h File Reference
Namespaces
nest
Class representing a synapse with Hill short term plasticity.
Functions
Datum * CYTHON_unpackConnectionGeneratorDatum (PyObject *)
int neststartup (int argc, char **argv, SLIInterpreter &engine, nest::Network *&pNet, std::string modulepath="")
int neststartup (int argc, char **argv, SLIInterpreter &engine, nest::Network *&pNet)
void nestshutdown (void)
Function Documentation
Datum* CYTHON_unpackConnectionGeneratorDatum (PyObject *)
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
void nestshutdown (void)
References nest::Communicator::finalize().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), and main().
int neststartup (int argc, char ** argv, SLIInterpreter & engine, nest::Network *& pNet, std::string modulepath = "")
int neststartup (int argc, char ** argv, SLIInterpreter & engine, nest::Network *& pNet)
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_4init(), and main().