NEST: neststartup.cpp File Reference
neststartup.cpp File Reference
Functions
int neststartup (int argc, char **argv, SLIInterpreter &engine, nest::Network *&pNet) int neststartup(int argc
omp_set_dynamic (false)
omp_set_num_threads (1)
addmodule< OOSupportModule > (engine)
addmodule< RandomNumbers > (engine)
addmodule< GNUReadline > (engine)
addmodule< SLIArrayModule > (engine)
addmodule< SpecialFunctionsModule > (engine)
addmodule< SLIgraphics > (engine)
engine addmodule (new SLIStartup(argc, argv))
addmodule< Processes > (engine)
addmodule< RegexpModule > (engine)
addmodule< FilesystemModule > (engine)
assert (pNet!=0)
addmodule< nest::NestModule > (engine)
add_static_modules (engine,*pNet)
pDynLoader initLinkedModules (engine)
engine addmodule (pDynLoader)
assert (ad!=NULL)
ad push_back (new StringDatum("("+modulepath+"/pynest-init.sli) run"))
return engine startup ()
void nestshutdown (void)
Datum * CYTHON_unpackConnectionGeneratorDatum (PyObject *obj)
Variables
int char ** argv
int char SLIInterpreter & engine
int char SLIInterpreter
nest::Network *& pNet = new nest::Network(engine)
int char SLIInterpreter
nest::Network std::string
modulepath
nest::Communicator::init & argc
nest::DynamicLoaderModule * pDynLoader = new nest::DynamicLoaderModule(pNet, engine)
ArrayDatum * ad = dynamic_cast<ArrayDatum *>(engine.baselookup(engine.commandstring_name).datum())
Function Documentation
add_static_modules (engine , * pNet)
engine addmodule (new SLIStartupargc, argv)
engine addmodule (pDynLoader)
addmodule< FilesystemModule > (engine)
Referenced by main().
addmodule< GNUReadline > (engine)
Referenced by main().
addmodule< nest::NestModule > (engine)
addmodule< OOSupportModule > (engine)
Referenced by main().
addmodule< Processes > (engine)
Referenced by main().
addmodule< RandomNumbers > (engine)
addmodule< RegexpModule > (engine)
Referenced by main().
addmodule< SLIArrayModule > (engine)
Referenced by main().
addmodule< SLIgraphics > (engine)
addmodule< SpecialFunctionsModule > (engine)
assert (pNet! = 0)
Referenced by accumulate_property(), nest::Multimeter::add_data_(), librandom::GslRandomGen::add_gsl_rngs(), nest::SparseNodeArray::add_local_node(), nest::Network::add_node(), nest::Modelrangemanager::add_range(), nest::SliceRingBuffer::add_refractory(), nest::SparseNodeArray::add_remote_node(), nest::SliceRingBuffer::add_spike(), nest::MultRBuffer::add_value(), SLIInterpreter::addlinkeddynmodule(), SLIInterpreter::addmodule(), TokenArrayObj::allocate(), nest::Model::allocate(), TokenArrayObj::append_move(), append_property(), append_property< std::vector< double > >(), append_property< std::vector< long > >(), array< T >::array(), nest::Communicator::OffGridSpike::assert_datatype_compatibility(), nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_(), Token::assign_by_pointer(), nest::Subnet::at_lid(), SLIArrayModule::IMapFunction::backtrace(), IiterateFunction::backtrace(), SLIArrayModule::IMap_ivFunction::backtrace(), SLIArrayModule::IMap_dvFunction::backtrace(), IloopFunction::backtrace(), IrepeatFunction::backtrace(), SLIArrayModule::IMapThreadFunction::backtrace(), IforFunction::backtrace(), SLIArrayModule::IMapIndexedFunction::backtrace(), IforallarrayFunction::backtrace(), IforallindexedarrayFunction::backtrace(), IforallindexedstringFunction::backtrace(), IforallstringFunction::backtrace(), SLIArrayModule::Iforall_ivFunction::backtrace(), SLIArrayModule::Iforall_dvFunction::backtrace(), nest::LocalNodeListBase< ListIterator >::begin(), nest::pulsepacket_generator::calibrate(), nest::aeif_cond_alpha_multisynapse::calibrate(), nest::iaf_cond_exp::calibrate(), nest::aeif_cond_alpha_RK5::calibrate(), nest::iaf_cond_exp_sfa_rr::calibrate(), nest::iaf_cond_alpha::calibrate(), nest::iaf_psc_exp::calibrate(), nest::aeif_cond_alpha::calibrate(), nest::iaf_neuron::calibrate(), nest::iaf_psc_delta::calibrate(), nest::iaf_psc_alpha::calibrate(), nest::aeif_cond_exp::calibrate(), nest::ht_neuron::calibrate(), nest::iaf_psc_alpha_presc::calibrate(), nest::iaf_psc_exp_ps::calibrate(), nest::hh_psc_alpha::calibrate(), nest::pp_psc_delta::calibrate(), nest::iaf_cond_alpha_mc::calibrate(), nest::iaf_psc_alpha_canon::calibrate(), nest::iaf_psc_delta_canon::calibrate(), nest::RecordingDevice::calibrate(), nest::cg_get_right_border(), table_iterator< tabletype >::check(), const_table_iterator< tabletype >::check(), librandom::ClippedRedrawContinuousRandomDev< BaseRDV >::ClippedRedrawContinuousRandomDev(), librandom::ClippedRedrawDiscreteRandomDev< BaseRDV >::ClippedRedrawDiscreteRandomDev(), librandom::ClippedToBoundaryContinuousRandomDev< BaseRDV >::ClippedToBoundaryContinuousRandomDev(), librandom::ClippedToBoundaryDiscreteRandomDev< BaseRDV >::ClippedToBoundaryDiscreteRandomDev(), nest::DataLoggingReply::clone(), nest::Communicator::communicate(), nest::FreeLayer< D >::communicate_positions_(), nest::Scheduler::compute_moduli_(), nest::Scheduler::configure_spike_buffers_(), nest::Network::connect(), nest::OneToOneBuilder::connect_(), nest::Network::copy_model(), nest::RecordablesMap< HostNode >::create(), nest::AbstractLayer::create_layer(), darwin_get_used_mem(), nest::ConnectionCreator::PoolWrapper_< D >::define(), lockPTR< nest::Ntree< D, index > >::deletable(), SLIType::deletetypename(), nest::Network::destruct_nodes_(), nest::Node::downcast(), nest::Layer< D >::dump_connections(), nest::DynamicLoaderModule::DynamicLoaderModule(), nest::Stopwatch::elapsed(), nest::iaf_psc_exp_ps::emit_instant_spike_(), nest::iaf_psc_delta_canon::emit_instant_spike_(), nest::iaf_psc_alpha_canon::emit_instant_spike_(), nest::iaf_psc_delta_canon::emit_spike_(), sparsetable< T, GROUP_SIZE, Alloc >::erase(), sparsegroup< T, GROUP_SIZE, Alloc >::erase_aux(), nest::gamma_sup_generator::event_hook(), nest::poisson_generator_ps::event_hook(), nest::ppd_sup_generator::event_hook(), nest::noise_generator::event_hook(), nest::sinusoidal_gamma_generator::event_hook(), OOSupportModule::CallMemberFunction::execute(), Add_diFunction::execute(), TrieInfoFunction::execute(), FilesystemModule::FileNamesFunction::execute(), Get_aFunction::execute(), NpopFunction::execute(), SLIArrayModule::MapFunction::execute(), Add_iiFunction::execute(), FilesystemModule::SetDirectoryFunction::execute(), Get_a_aFunction::execute(), GNUReadline::GNUReadlineFunction::execute(), IsetcallbackFunction::execute(), RegexpModule::RegcompFunction::execute(), FilesystemModule::DirectoryFunction::execute(), Add_idFunction::execute(), Cva_tFunction::execute(), RegexpModule::RegexecFunction::execute(), GNUReadline::GNUAddhistoryFunction::execute(), FilesystemModule::MoveFileFunction::execute(), Add_ddFunction::execute(), RegexpModule::RegerrorFunction::execute(), Cvt_aFunction::execute(), Get_pFunction::execute(), FilesystemModule::CopyFileFunction::execute(), IndexFunction::execute(), Sub_diFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), Get_lpFunction::execute(), FilesystemModule::DeleteFileFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), FilesystemModule::MakeDirectoryFunction::execute(), Append_aFunction::execute(), Sub_iiFunction::execute(), FilesystemModule::RemoveDirectoryFunction::execute(), SLIArrayModule::MapIndexedFunction::execute(), Append_pFunction::execute(), Sub_idFunction::execute(), DictinfoFunction::execute(), Append_sFunction::execute(), StrSStreamFunction::execute(), Sub_ddFunction::execute(), SLIArrayModule::RangeFunction::execute(), DicttopinfoFunction::execute(), FilesystemModule::CompareFilesFunction::execute(), Prepend_aFunction::execute(), OstrstreamFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), RandomNumbers::GetStatus_vFunction::execute(), WhoFunction::execute(), Prepend_pFunction::execute(), Mul_diFunction::execute(), StrFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), SLIStartup::GetenvFunction::execute(), Prepend_sFunction::execute(), Mul_iiFunction::execute(), CopyFunction::execute(), PrintFunction::execute(), Join_sFunction::execute(), SLIArrayModule::ReverseFunction::execute(), Mul_idFunction::execute(), Join_aFunction::execute(), SLIArrayModule::FlattenFunction::execute(), Mul_ddFunction::execute(), Join_pFunction::execute(), CurrentnameFunction::execute(), RestoreestackFunction::execute(), Insert_sFunction::execute(), Div_diFunction::execute(), RestoreostackFunction::execute(), Length_dFunction::execute(), Insert_aFunction::execute(), SLIArrayModule::TransposeFunction::execute(), Div_iiFunction::execute(), Empty_DFunction::execute(), InsertElement_sFunction::execute(), SLIArrayModule::PartitionFunction::execute(), CleardictFunction::execute(), Div_idFunction::execute(), InsertElement_aFunction::execute(), IparseFunction::execute(), SLIArrayModule::ValidFunction::execute(), ClonedictFunction::execute(), Replace_sFunction::execute(), Div_ddFunction::execute(), SLIArrayModule::Put_a_a_tFunction::execute(), Replace_aFunction::execute(), nest::NestModule::CurrentSubnetFunction::execute(), Erase_sFunction::execute(), Cva_dFunction::execute(), Erase_aFunction::execute(), Sin_dFunction::execute(), KeysFunction::execute(), Erase_pFunction::execute(), ForFunction::execute(), Asin_dFunction::execute(), ValuesFunction::execute(), Forall_aFunction::execute(), Length_sFunction::execute(), RestoredstackFunction::execute(), Cos_dFunction::execute(), Forall_iterFunction::execute(), Length_aFunction::execute(), Acos_dFunction::execute(), Length_pFunction::execute(), Forallindexed_aFunction::execute(), Length_lpFunction::execute(), Exp_dFunction::execute(), Forallindexed_sFunction::execute(), Processes::Sysexec_aFunction::execute(), Processes::WaitPIDFunction::execute(), Capacity_aFunction::execute(), Forall_sFunction::execute(), Ln_dFunction::execute(), Processes::KillFunction::execute(), Size_aFunction::execute(), Log_dFunction::execute(), Reserve_aFunction::execute(), Processes::Dup2_is_isFunction::execute(), Processes::Dup2_os_osFunction::execute(), Sqr_dFunction::execute(), Resize_aFunction::execute(), Processes::Dup2_is_osFunction::execute(), Empty_aFunction::execute(), Sqrt_dFunction::execute(), Processes::Dup2_os_isFunction::execute(), Processes::AvailableFunction::execute(), References_aFunction::execute(), Pow_ddFunction::execute(), Shrink_aFunction::execute(), Pow_diFunction::execute(), Capacity_sFunction::execute(), SLIArrayModule::GaborFunction::execute(), Processes::MkfifoFunction::execute(), Modf_dFunction::execute(), Size_sFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), Reserve_sFunction::execute(), Frexp_dFunction::execute(), Resize_sFunction::execute(), Ldexp_diFunction::execute(), Processes::SetNonblockFunction::execute(), Empty_sFunction::execute(), Dexp_iFunction::execute(), Processes::Isatty_isFunction::execute(), Getinterval_sFunction::execute(), Processes::Isatty_osFunction::execute(), Getinterval_aFunction::execute(), Abs_iFunction::execute(), Cvx_aFunction::execute(), Abs_dFunction::execute(), Cvlit_nFunction::execute(), Cvlit_pFunction::execute(), Neg_iFunction::execute(), Cvlp_pFunction::execute(), Neg_dFunction::execute(), RangeIterator_aFunction::execute(), IteratorSize_iterFunction::execute(), Cvn_sFunction::execute(), EqFunction::execute(), Cvn_lFunction::execute(), NeqFunction::execute(), AndFunction::execute(), OrFunction::execute(), And_iiFunction::execute(), Cvi_sFunction::execute(), Or_iiFunction::execute(), XorFunction::execute(), Not_bFunction::execute(), Not_iFunction::execute(), Cvd_sFunction::execute(), Get_sFunction::execute(), Geq_iiFunction::execute(), Put_sFunction::execute(), Geq_idFunction::execute(), Token_sFunction::execute(), Put_aFunction::execute(), Geq_diFunction::execute(), Put_pFunction::execute(), Geq_ddFunction::execute(), Symbol_sFunction::execute(), Put_lpFunction::execute(), SetGuardFunction::execute(), Search_sFunction::execute(), Leq_iiFunction::execute(), SLIArrayModule::ArangeFunction::execute(), Search_aFunction::execute(), Leq_idFunction::execute(), MessageFunction::execute(), Leq_diFunction::execute(), SetVerbosityFunction::execute(), Leq_ddFunction::execute(), Gt_iiFunction::execute(), Gt_ddFunction::execute(), Gt_idFunction::execute(), Gt_diFunction::execute(), Gt_ssFunction::execute(), Lt_iiFunction::execute(), Lt_ddFunction::execute(), Lt_idFunction::execute(), Lt_diFunction::execute(), Lt_ssFunction::execute(), IntegerFunction::execute(), DoubleFunction::execute(), UnitStep_iFunction::execute(), UnitStep_dFunction::execute(), UnitStep_iaFunction::execute(), UnitStep_daFunction::execute(), Round_dFunction::execute(), Floor_dFunction::execute(), Ceil_dFunction::execute(), Max_i_iFunction::execute(), Max_i_dFunction::execute(), Max_d_iFunction::execute(), Max_d_dFunction::execute(), Min_i_iFunction::execute(), Min_i_dFunction::execute(), Min_d_iFunction::execute(), Min_d_dFunction::execute(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), nest::Network::execute_sli_protected(), Processes::fd(), nest::Model::free(), nest::spike_generator::Parameters_::get(), lockPTR< nest::Ntree< D, index > >::get(), nest::iaf_cond_alpha_mc::State_::get(), nest::RecordingDevice::State_::get(), sparsetable< T, GROUP_SIZE, Alloc >::get(), nest::Layer< D >::get_global_positions_ntree(), nest::Layer< D >::get_global_positions_vector(), nest::RingBuffer::get_index_(), nest::MultRBuffer::get_index_(), nest::ListRingBuffer::get_index_(), sparsetable< T, GROUP_SIZE, Alloc >::get_iter(), nest::ListRingBuffer::get_list(), nest::Modelrangemanager::get_model_id(), nest::Network::get_model_id(), nest::Network::get_modeldict(), nest::Scheduler::get_modulo(), nest::NestModule::get_network(), nest::ConnectionGeneratorModule::get_network(), nest::TopologyModule::get_network(), nest::SliceRingBuffer::get_next_spike(), nest::SparseNodeArray::get_node_by_gid(), nest::SparseNodeArray::get_node_by_index(), RandomNumbers::get_rdvdict(), nest::DataLoggingRequest::get_recording_interval(), nest::Scheduler::get_rng(), RandomNumbers::get_rngdict(), nest::Event::get_sender_gid(), nest::Scheduler::get_slice_modulo(), nest::SiblingContainer::get_status(), nest::Network::get_status(), nest::Node::get_status_base(), nest::Connector< K, ConnectionT >::get_synapse_status(), nest::Connector< 1, ConnectionT >::get_synapse_status(), nest::Connector< K_cutoff, ConnectionT >::get_synapse_status(), nest::Network::get_synapsedict(), nest::TargetIdentifierIndex::get_target_ptr(), nest::Node::get_thread_sibling_(), nest::Node::get_thread_sibling_safe_(), nest::Network::get_thread_siblings(), nest::Scheduler::get_time(), nest::RingBuffer::get_value(), nest::MultRBuffer::get_value(), PgetrusageFunction::getinfo_(), CharCode::Group(), librandom::GslRandomGen::GslRandomGen(), librandom::GslRNGFactory::GslRNGFactory(), nest::binary_neuron< TGainfunction >::handle(), nest::iaf_psc_exp_multisynapse::handle(), nest::iaf_psc_alpha_multisynapse::handle(), nest::music_event_out_proxy::handle(), nest::parrot_neuron_ps::handle(), nest::aeif_cond_alpha_multisynapse::handle(), nest::sli_neuron::handle(), nest::izhikevich::handle(), nest::iaf_chs_2007::handle(), nest::spin_detector::handle(), nest::iaf_cond_exp::handle(), nest::spike_detector::handle(), nest::aeif_cond_alpha_RK5::handle(), nest::hh_cond_exp_traub::handle(), nest::iaf_chxk_2008::handle(), nest::iaf_cond_exp_sfa_rr::handle(), nest::iaf_psc_exp::handle(), nest::iaf_cond_alpha::handle(), nest::aeif_cond_alpha::handle(), nest::iaf_neuron::handle(), nest::iaf_psc_alpha_presc::handle(), nest::ht_neuron::handle(), nest::hh_psc_alpha::handle(), nest::iaf_psc_delta::handle(), nest::iaf_psc_alpha::handle(), nest::aeif_cond_exp::handle(), nest::iaf_tum_2000::handle(), nest::correlomatrix_detector::handle(), nest::mat2_psc_exp::handle(), nest::iaf_psc_exp_ps::handle(), nest::correlation_detector::handle(), nest::amat2_psc_exp::handle(), nest::pp_psc_delta::handle(), nest::pp_pop_psc_delta::handle(), nest::iaf_psc_alpha_canon::handle(), nest::iaf_cond_alpha_mc::handle(), nest::Multimeter::handle(), nest::iaf_psc_delta_canon::handle(), nest::ht_neuron::handles_test_event(), nest::hh_cond_exp_traub_dynamics(), nest::hh_psc_alpha_dynamics(), nest::ht_neuron_dynamics(), TypeTrie::TypeNode::info(), nest::NestModule::init(), RandomNumbers::init(), sli::pool::init(), SLIStartup::init(), Processes::init(), librandom::BinomialRandomDev::init_(), librandom::PoissonRandomDev::init_(), nest::Scheduler::init_(), nest::Network::init_(), nest::Scheduler::init_moduli_(), nest::Node::init_state(), SLIInterpreter::initdictionaries(), nest::Ntree< D, T, max_capacity, max_depth >::insert(), nest::FreeLayer< D >::insert_local_positions_ntree_(), TypeTrie::insert_move(), TokenArrayObj::insert_move(), nest::Time::is_multiple_of(), lockPTR< nest::Ntree< D, index > >::islocked(), nest::Ntree< D, T, max_capacity, max_depth >::iterator::iterator(), librandom::UniformIntRandomDev::ldev(), librandom::BinomialRandomDev::ldev(), librandom::PoissonRandomDev::ldev(), librandom::RandomDev::ldev(), nest::GridLayer< D >::lid_to_position(), lockPTR< D >::PointerObject::lock(), lockPTR< nest::Ntree< D, index > >::lock(), lockPTR< nest::Ntree< D, index > >::lockPTR(), sparsetable< T, GROUP_SIZE, Alloc >::mutating_get(), nest::NestModule::NestModule(), TypeTrie::newnode(), nest::Ntree< D, T, max_capacity, max_depth >::iterator::next_leaf_(), nest::Ntree< D, T, max_capacity, max_depth >::masked_iterator::next_leaf_(), nest::SparseNodeArray::NodeEntry_::NodeEntry_(), ofdstream::ofdstream(), CharCode::operator()(), Parser::operator()(), nest::MusicEventHandler::operator()(), librandom::RandomDev::operator()(), Scanner::operator()(), nest::GridLayer< D >::masked_iterator::operator*(), lockPTR< nest::Ntree< D, index > >::operator*(), nest::LocalNodeListIterator::operator++(), two_d_iterator< containertype >::operator++(), const_two_d_iterator< containertype >::operator++(), destructive_two_d_iterator< containertype >::operator++(), table_iterator< tabletype >::operator-(), const_table_iterator< tabletype >::operator-(), two_d_iterator< containertype >::operator--(), const_two_d_iterator< containertype >::operator--(), lockPTR< nest::Ntree< D, index > >::operator->(), table_iterator< tabletype >::operator<(), const_table_iterator< tabletype >::operator<(), array< T >::operator=(), nest::iaf_cond_exp::State_::operator=(), nest::hh_cond_exp_traub::State_::operator=(), nest::aeif_cond_alpha_multisynapse::State_::operator=(), lockPTR< nest::Ntree< D, index > >::operator=(), nest::iaf_cond_exp_sfa_rr::State_::operator=(), TokenArrayObj::operator=(), nest::aeif_cond_alpha_RK5::State_::operator=(), nest::aeif_cond_alpha::State_::operator=(), nest::aeif_cond_exp::State_::operator=(), nest::hh_psc_alpha::State_::operator=(), nest::iaf_cond_alpha_mc::Parameters_::operator=(), nest::iaf_cond_alpha_mc::State_::operator=(), array< T >::operator[](), Parser::Parser(), nest::Position< D, T >::Position(), nest::Scheduler::prepare_nodes(), nest::Stopwatch::print(), SLIInterpreter::print_error(), nest::iaf_psc_delta_canon::propagate_(), provide_property(), nest::proxynode::proxynode(), DictionaryStack::push(), SLIInterpreter::raiseagain(), SLIInterpreter::raiseerror(), CharCode::Range(), nest::DataLoggingRequest::record_from(), TokenArrayObj::reduce(), nest::Network::register_conn_builder(), nest::Network::register_model(), nest::register_model(), nest::NestModule::register_network(), nest::register_preconf_model(), nest::DynamicLoaderModule::registerLinkedModule(), TokenArrayObj::replace_move(), nest::Model::reserve_additional(), nest::correlomatrix_detector::State_::reset(), nest::correlation_detector::State_::reset(), nest::Network::reset_network(), array< T >::resize(), nest::Scheduler::resume(), librandom::KnuthLFG::self_test_(), nest::Network::send(), sparsetable< T, GROUP_SIZE, Alloc >::set(), librandom::RandomGen::set_buffsize(), nest::Subnet::set_label(), librandom::GammaRandomDev::set_order(), librandom::GSL_BinomialRandomDev::set_p(), sparsehash_internal::sh_hashtable_settings< Key, HashFunc, SizeType, HT_MIN_BUCKETS >::set_resizing_parameters(), nest::Time::set_resolution(), nest::SiblingContainer::set_status(), nest::proxynode::set_status(), nest::Network::set_status(), nest::Node::set_status_base(), nest::Connector< K, ConnectionT >::set_synapse_status(), nest::Connector< 1, ConnectionT >::set_synapse_status(), nest::Connector< K_cutoff, ConnectionT >::set_synapse_status(), SLIType::setdefaultaction(), SLIType::settypename(), nest::Scheduler::simulate(), nest::ConnBuilder::single_connect_(), SLIStartup::SLIStartup(), nest::Ntree< D, T, max_capacity, max_depth >::split_(), Processes::systemerror(), SLIInterpreter::terminate(), sparsetable< T, GROUP_SIZE, Alloc >::test(), nest::Communicator::test_link(), TokenArray::TokenArray(), TypeTrie::TypeNode::toTokenArray(), lockPTR< D >::PointerObject::unlock(), lockPTR< nest::Ntree< D, index > >::unlock(), sparsegroup< T, GROUP_SIZE, Alloc >::unsafe_get(), sparsetable< T, GROUP_SIZE, Alloc >::unsafe_get(), nest::step_current_generator::update(), nest::binary_neuron< TGainfunction >::update(), nest::iaf_psc_exp_multisynapse::update(), nest::pulsepacket_generator::update(), nest::iaf_psc_alpha_multisynapse::update(), nest::gamma_sup_generator::update(), nest::poisson_generator_ps::update(), nest::parrot_neuron_ps::update(), nest::ppd_sup_generator::update(), nest::parrot_neuron::update(), nest::sinusoidal_poisson_generator::update(), nest::aeif_cond_alpha_multisynapse::update(), nest::iaf_chs_2007::update(), nest::iaf_cond_exp::update(), nest::poisson_generator::update(), nest::izhikevich::update(), nest::sli_neuron::update(), nest::mip_generator::update(), nest::spin_detector::update(), nest::spike_detector::update(), nest::aeif_cond_alpha_RK5::update(), nest::iaf_chxk_2008::update(), nest::hh_cond_exp_traub::update(), nest::iaf_cond_exp_sfa_rr::update(), nest::iaf_cond_alpha::update(), nest::iaf_psc_exp::update(), nest::sinusoidal_gamma_generator::update(), nest::aeif_cond_alpha::update(), nest::iaf_neuron::update(), nest::iaf_psc_delta::update(), nest::mat2_psc_exp::update(), nest::aeif_cond_exp::update(), nest::iaf_psc_alpha::update(), nest::iaf_tum_2000::update(), nest::ht_neuron::update(), nest::amat2_psc_exp::update(), nest::hh_psc_alpha::update(), nest::pp_psc_delta::update(), nest::pp_pop_psc_delta::update(), nest::iaf_cond_alpha_mc::update(), nest::iaf_psc_alpha_presc::update(), nest::iaf_psc_exp_ps::update(), nest::spike_generator::update(), nest::iaf_psc_alpha_canon::update(), nest::iaf_psc_delta_canon::update(), lockPTR< nest::Ntree< D, index > >::valid(), nest::Vose::Vose(), sparsegroup< T, GROUP_SIZE, Alloc >::write_metadata(), librandom::GslRandomGen::~GslRandomGen(), lockPTR< nest::Ntree< D, index > >::~lockPTR(), and lockPTR< D >::PointerObject::~PointerObject().
assert (ad! = NULL)
Datum* CYTHON_unpackConnectionGeneratorDatum (PyObject * obj)
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
pDynLoader initLinkedModules (engine)
void nestshutdown (void)
References nest::Communicator::finalize().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), and main().
int neststartup (int argc, char ** argv, SLIInterpreter & engine, nest::Network *& pNet)
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_4init(), and main().
omp_set_dynamic (false)
omp_set_num_threads (1)
Referenced by nest::Scheduler::prepare_nodes().
ad push_back (new StringDatum"("+modulepath+"/pynest-init.sli) run")
Referenced by nest::Scheduler::send_offgrid_remote(), and nest::Scheduler::send_remote().
return engine startup ()
Variable Documentation
ArrayDatum* ad = dynamic_cast<ArrayDatum *>(engine.baselookup(engine.commandstring_name).datum())
Referenced by SLIInterpreter::addlinkeddynmodule(), SLIInterpreter::addmodule(), nest::AbstractLayer::create_layer(), nest::TopologyModule::create_mask(), nest::Network::divergent_connect(), AddtotrieFunction::execute(), SLIArrayModule::MapThreadFunction::execute(), SLIArrayModule::IMapThreadFunction::execute(), IforallarrayFunction::execute(), SLIArrayModule::RangeFunction::execute(), SLIArrayModule::ArraystoreFunction::execute(), SLIArrayModule::ArrayloadFunction::execute(), SLIArrayModule::ArraycreateFunction::execute(), SLIArrayModule::ReverseFunction::execute(), SLIArrayModule::RotateFunction::execute(), SLIArrayModule::FlattenFunction::execute(), RestoreestackFunction::execute(), RestoreostackFunction::execute(), SLIArrayModule::PartitionFunction::execute(), SLIArrayModule::ValidFunction::execute(), Cva_dFunction::execute(), KeysFunction::execute(), ValuesFunction::execute(), RestoredstackFunction::execute(), Forallindexed_aFunction::execute(), nest::NestModule::Cva_CFunction::execute(), Reserve_aFunction::execute(), Resize_aFunction::execute(), Empty_aFunction::execute(), References_aFunction::execute(), Shrink_aFunction::execute(), Reserve_sFunction::execute(), Resize_sFunction::execute(), Empty_sFunction::execute(), SLIArrayModule::DoubleVector2ArrayFunction::execute(), SLIArrayModule::IntVector2ArrayFunction::execute(), Put_aFunction::execute(), Put_pFunction::execute(), Put_lpFunction::execute(), SLIArrayModule::ArangeFunction::execute(), SLIArrayModule::Iforall_ivFunction::execute(), SLIArrayModule::Iforall_dvFunction::execute(), nest::Multimeter::Parameters_::get(), nest::RecordingDevice::Parameters_::get(), getValue< std::vector< double > >(), getValue< std::vector< long > >(), nest::ModelsModule::init(), SLIInterpreter::initexternals(), nest::Scheduler::prepare_nodes(), nest::Multimeter::Parameters_::set(), nest::RecordingDevice::Parameters_::set(), setValue< std::valarray< double > >(), setValue< std::valarray< long > >(), setValue< std::vector< double > >(), setValue< std::vector< long > >(), SLIStartup::SLIStartup(), and nest::ConnectionID::to_ArrayDatum().
int char SLIInterpreter nest::Network std::string modulepath nest::Communicator::init& argc
Referenced by SLIStartup::SLIStartup().
int char** argv
Referenced by Processes::Sysexec_aFunction::execute().
int char SLIInterpreter& engine
Referenced by main().
nest::DynamicLoaderModule* pDynLoader = new nest::DynamicLoaderModule(pNet, engine)
nest::NestModule::register_network * pNet = new nest::Network(engine)
Referenced by nest::DynamicLoaderModule::DynamicLoaderModule(), and main().