NEST: nest_time.h File Reference
nest_time.h File Reference
Classes
class nest::Time
struct nest::Time::Range
struct nest::Time::Limit
struct nest::Time::LimitPosInf
struct nest::Time::LimitNegInf
struct nest::Time::tic
struct nest::Time::step
struct nest::Time::ms
struct nest::Time::ms_stamp
Namespaces
nest
Class representing a synapse with Hill short term plasticity.
Functions
std::ostream & operator<< (std::ostream &, const nest::Time &)
template<class N >
N nest::time_abs (const N n)
Class to handle simulation time and realtime.
template<>
long long nest::time_abs (long long n)
bool nest::operator== (const Time &t1, const Time &t2)
bool nest::operator!= (const Time &t1, const Time &t2)
bool nest::operator< (const Time &t1, const Time &t2)
bool nest::operator> (const Time &t1, const Time &t2)
bool nest::operator<= (const Time &t1, const Time &t2)
bool nest::operator>= (const Time &t1, const Time &t2)
Time nest::operator+ (const Time &t1, const Time &t2)
Time nest::operator- (const Time &t1, const Time &t2)
Time nest::operator* (const long_t factor, const Time &t)
Time nest::operator* (const Time &t, long_t factor)
Variables
const Time nest::TimeZero
Function Documentation
std::ostream& operator<< (std::ostream & , const nest::Time &)
References nest::Time::get_ms(), nest::Time::get_steps(), nest::Time::get_tics(), nest::Time::LIM_NEG_INF, nest::Time::LIM_POS_INF, nest::Time::tics, nest::Time::LimitPosInf::tics, and nest::Time::LimitNegInf::tics.