NEST: nest_time.cpp File Reference
nest_time.cpp File Reference
Functions
std::ostream & operator<< (std::ostream &strm, const Time &t)
Function Documentation
std::ostream & operator<< (std::ostream & strm, const Time & t)
References nest::Time::get_ms(), nest::Time::get_steps(), nest::Time::get_tics(), nest::Time::LIM_NEG_INF, nest::Time::LIM_POS_INF, nest::Time::tics, nest::Time::LimitPosInf::tics, and nest::Time::LimitNegInf::tics.