NEST: processes.cc File Reference
processes.cc File Reference
Functions
long bg_get_heap_mem ()
long bg_get_stack_mem ()
unsigned long darwin_get_used_mem ()
Function Documentation
long bg_get_heap_mem ()
References nest::names::memory.
Referenced by Processes::MemoryThisjobBgFunction::execute().
long bg_get_stack_mem ()
References nest::names::memory.
Referenced by Processes::MemoryThisjobBgFunction::execute().
unsigned long darwin_get_used_mem ()
References assert().
Referenced by Processes::MemoryThisjobDarwinFunction::execute().