NEST: puresli.cc File Reference
puresli.cc File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
We disable synchronization between stdio and istd::ostreams this has to be done before any in- or output has been done.
References SLIInterpreter::addmodule(), addmodule< FilesystemModule >(), addmodule< GNUReadline >(), addmodule< OOSupportModule >(), addmodule< Processes >(), addmodule< RegexpModule >(), addmodule< SLIArrayModule >(), engine, and SLIInterpreter::execute().