NEST: pynestkernel.cpp File Reference
pynestkernel.cpp File Reference
Classes
struct Py_buffer
struct __Pyx_StringTabEntry
struct __Pyx_memviewslice
struct __Pyx_TypeInfo
struct __Pyx_StructField_
struct __Pyx_BufFmt_StackElem
struct __Pyx_BufFmt_Context
struct __pyx_fuse_0_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_0_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_1_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_1_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_2_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_2_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_3_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_3_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_4_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_4_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum
struct __pyx_fuse_0_0__pyx_opt_args_12pynestkernel_sli_vector_to_object
struct __pyx_fuse_0_1__pyx_opt_args_12pynestkernel_sli_vector_to_object
struct __pyx_fuse_1_0__pyx_opt_args_12pynestkernel_sli_vector_to_object
struct __pyx_fuse_1_1__pyx_opt_args_12pynestkernel_sli_vector_to_object
struct __pyx_obj_12pynestkernel_SLIDatum
struct __pyx_obj_12pynestkernel_SLILiteral
struct __pyx_obj_12pynestkernel_NESTEngine
struct __pyx_array_obj
struct __pyx_MemviewEnum_obj
struct __pyx_memoryview_obj
struct __pyx_memoryviewslice_obj
struct __pyx_vtabstruct_12pynestkernel_SLIDatum
struct __pyx_vtabstruct_memoryview
struct __pyx_vtabstruct__memoryviewslice
struct __Pyx_RefNannyAPIStruct
struct __Pyx_Buf_DimInfo
struct __Pyx_Buffer
struct __Pyx_LocalBuf_ND
struct arraydescr
struct arrayobject
struct __Pyx_CodeObjectCacheEntry
struct __Pyx_CodeObjectCache
Typedefs
typedef int Py_ssize_t
typedef int(* getbufferproc)(PyObject *, Py_buffer *, int)
typedef void(* releasebufferproc)(PyObject *, Py_buffer *)
typedef long Py_hash_t
typedef struct __Pyx_StructField_ __Pyx_StructField
typedef volatile
__pyx_atomic_int_type __pyx_atomic_int
typedef struct arrayobject arrayobject
typedef IntVectorDatum * __pyx_t_12pynestkernel_sli_vector_int_ptr_t
typedef DoubleVectorDatum * __pyx_t_12pynestkernel_sli_vector_double_ptr_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_int_1d_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_long_1d_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_float_1d_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_double_1d_t
typedef struct arraydescr arraydescr
Functions
static CYTHON_INLINE float __PYX_NAN ()
template<typename T >
void __Pyx_call_destructor (T *x)
static CYTHON_INLINE char * __Pyx_PyObject_AsString (PyObject *)
static CYTHON_INLINE char * __Pyx_PyObject_AsStringAndSize (PyObject *, Py_ssize_t *length)
static CYTHON_INLINE PyObject * __Pyx_PyUnicode_FromString (const char *)
static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen (const Py_UNICODE *u)
static CYTHON_INLINE int __Pyx_PyObject_IsTrue (PyObject *)
static CYTHON_INLINE PyObject * __Pyx_PyNumber_Int (PyObject *x)
static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t (PyObject *)
static CYTHON_INLINE PyObject * __Pyx_PyInt_FromSize_t (size_t)
static int __Pyx_init_sys_getdefaultencoding_params (void)
static __Pyx_RefNannyAPIStruct * __Pyx_RefNannyImportAPI (const char *modname)
static CYTHON_INLINE PyObject * __Pyx_PyObject_GetAttrStr (PyObject *obj, PyObject *attr_name)
static PyObject * __Pyx_GetBuiltinName (PyObject *name)
static void __Pyx_RaiseArgtupleInvalid (const char *func_name, int exact, Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found)
static CYTHON_INLINE int __Pyx_CheckKeywordStrings (PyObject *kwdict, const char *function_name, int kw_allowed)
static CYTHON_INLINE PyObject * __Pyx_PyObject_Call (PyObject *func, PyObject *arg, PyObject *kw)
static void __Pyx_RaiseDoubleKeywordsError (const char *func_name, PyObject *kw_name)
static int __Pyx_ParseOptionalKeywords (PyObject *kwds, PyObject **argnames[],\PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,\const char *function_name)
static CYTHON_INLINE void __Pyx_ErrRestore (PyObject *type, PyObject *value, PyObject *tb)
static CYTHON_INLINE void __Pyx_ErrFetch (PyObject **type, PyObject **value, PyObject **tb)
static void __Pyx_WriteUnraisable (const char *name, int clineno, int lineno, const char *filename, int full_traceback)
static CYTHON_INLINE PyObject * __Pyx_GetModuleGlobalName (PyObject *name)
static void __Pyx_Raise (PyObject *type, PyObject *value, PyObject *tb, PyObject *cause)
static CYTHON_INLINE PyObject * __Pyx_GetItemInt_List_Fast (PyObject *o, Py_ssize_t i, int wraparound, int boundscheck)
static CYTHON_INLINE PyObject * __Pyx_GetItemInt_Tuple_Fast (PyObject *o, Py_ssize_t i, int wraparound, int boundscheck)
static CYTHON_INLINE PyObject * __Pyx_GetItemInt_Generic (PyObject *o, PyObject *j)
static CYTHON_INLINE PyObject * __Pyx_GetItemInt_Fast (PyObject *o, Py_ssize_t i, int is_list, int wraparound, int boundscheck)
static int __Pyx_GetException (PyObject **type, PyObject **value, PyObject **tb)
static CYTHON_INLINE void __Pyx_ExceptionSwap (PyObject **type, PyObject **value, PyObject **tb)
static CYTHON_INLINE void __Pyx_ExceptionSave (PyObject **type, PyObject **value, PyObject **tb)
static void __Pyx_ExceptionReset (PyObject *type, PyObject *value, PyObject *tb)
static CYTHON_INLINE void __Pyx_RaiseTooManyValuesError (Py_ssize_t expected)
static CYTHON_INLINE void __Pyx_RaiseNeedMoreValuesError (Py_ssize_t index)
static CYTHON_INLINE int __Pyx_IterFinish (void)
static int __Pyx_IternextUnpackEndCheck (PyObject *retval, Py_ssize_t expected)
static CYTHON_INLINE PyObject * __Pyx_decode_c_bytes (const char *cstring, Py_ssize_t length, Py_ssize_t start, Py_ssize_t stop, const char *encoding, const char *errors, PyObject *(*decode_func)(const char *s, Py_ssize_t size, const char *errors))
static CYTHON_INLINE PyObject * __Pyx_decode_cpp_string (std::string cppstring, Py_ssize_t start, Py_ssize_t stop, const char *encoding, const char *errors, PyObject *(*decode_func)(const char *s, Py_ssize_t size, const char *errors))
static CYTHON_INLINE int __Pyx_PyBytes_Equals (PyObject *s1, PyObject *s2, int equals)
static CYTHON_INLINE int __Pyx_PyUnicode_Equals (PyObject *s1, PyObject *s2, int equals)
static CYTHON_INLINE int __Pyx_GetBufferAndValidate (Py_buffer *buf, PyObject *obj, __Pyx_TypeInfo *dtype, int flags, int nd, int cast, __Pyx_BufFmt_StackElem *stack)
static CYTHON_INLINE void __Pyx_SafeReleaseBuffer (Py_buffer *info)
static int __Pyx_init_memviewslice (struct __pyx_memoryview_obj *memview, int ndim, __Pyx_memviewslice *memviewslice, int memview_is_new_reference)
static CYTHON_INLINE int __pyx_add_acquisition_count_locked (__pyx_atomic_int *acquisition_count, PyThread_type_lock lock)
static CYTHON_INLINE int __pyx_sub_acquisition_count_locked (__pyx_atomic_int *acquisition_count, PyThread_type_lock lock)
static CYTHON_INLINE void __Pyx_INC_MEMVIEW (__Pyx_memviewslice *, int, int)
static CYTHON_INLINE void __Pyx_XDEC_MEMVIEW (__Pyx_memviewslice *, int, int)
static CYTHON_INLINE int __Pyx_SetItemInt_Generic (PyObject *o, PyObject *j, PyObject *v)
static CYTHON_INLINE int __Pyx_SetItemInt_Fast (PyObject *o, Py_ssize_t i, PyObject *v, int is_list, int wraparound, int boundscheck)
static CYTHON_INLINE int __Pyx_TypeTest (PyObject *obj, PyTypeObject *type)
static CYTHON_INLINE void __Pyx_RaiseUnboundLocalError (const char *varname)
static CYTHON_INLINE int __Pyx_ArgTypeTest (PyObject *obj, PyTypeObject *type, int none_allowed, const char *name, int exact)
static CYTHON_INLINE Py_ssize_t __Pyx_div_Py_ssize_t (Py_ssize_t, Py_ssize_t)
static CYTHON_UNUSED int __pyx_array_getbuffer (PyObject *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags)
static PyObject * get_memview (PyObject *__pyx_v_self)
static CYTHON_INLINE PyObject * __Pyx_GetAttr (PyObject *, PyObject *)
static CYTHON_INLINE PyObject * __Pyx_decode_c_string (const char *cstring, Py_ssize_t start, Py_ssize_t stop, const char *encoding, const char *errors, PyObject *(*decode_func)(const char *s, Py_ssize_t size, const char *errors))
static CYTHON_INLINE void __Pyx_RaiseNoneNotIterableError (void)
static CYTHON_UNUSED int __pyx_memoryview_getbuffer (PyObject *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags)
static PyObject * __pyx_memoryview_transpose (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview__get__base (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_get_shape (PyObject *__pyx_v_self)
static CYTHON_INLINE int __Pyx_ListComp_Append (PyObject *list, PyObject *x)
static PyObject * __pyx_memoryview_get_strides (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_get_suboffsets (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_get_ndim (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_get_itemsize (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_get_nbytes (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_get_size (PyObject *__pyx_v_self)
static CYTHON_INLINE int __Pyx_PyList_Extend (PyObject *L, PyObject *v)
static CYTHON_INLINE int __Pyx_PyList_Append (PyObject *list, PyObject *x)
static CYTHON_INLINE long __Pyx_div_long (long, long)
static PyObject * __pyx_memoryviewslice__get__base (PyObject *__pyx_v_self)
static int __Pyx_SetVtable (PyObject *dict, void *vtable)
static PyObject * __Pyx_CalculateMetaclass (PyTypeObject *metaclass, PyObject *bases)
static PyObject * __Pyx_Py3MetaclassPrepare (PyObject *metaclass, PyObject *bases, PyObject *name, PyObject *qualname, PyObject *mkw, PyObject *modname, PyObject *doc)
static PyObject * __Pyx_Py3ClassCreate (PyObject *metaclass, PyObject *name, PyObject *bases, PyObject *dict, PyObject *mkw, int calculate_metaclass, int allow_py2_metaclass)
static int __Pyx_GetBuffer (PyObject *obj, Py_buffer *view, int flags)
static void __Pyx_ReleaseBuffer (Py_buffer *view)
static CYTHON_INLINE PyObject * newarrayobject (PyTypeObject *type, Py_ssize_t size, struct arraydescr *descr)
static CYTHON_INLINE int resize (arrayobject *self, Py_ssize_t n)
static CYTHON_INLINE int resize_smart (arrayobject *self, Py_ssize_t n)
static PyObject * __Pyx_Import (PyObject *name, PyObject *from_list, int level)
static CYTHON_INLINE int __Pyx_PyInt_As_int (PyObject *)
static void __Pyx_CppExn2PyErr ()
static CYTHON_INLINE size_t __Pyx_PyInt_As_size_t (PyObject *)
static CYTHON_INLINE long __Pyx_PyInt_As_long (PyObject *)
static CYTHON_INLINE PyObject * __Pyx_PyInt_From_long (long value)
static CYTHON_INLINE PyObject * __Pyx_PyInt_From_int (int value)
static PyObject * __pyx_memview_get_int (const char *itemp)
static int __pyx_memview_set_int (const char *itemp, PyObject *obj)
static PyObject * __pyx_memview_get_long (const char *itemp)
static int __pyx_memview_set_long (const char *itemp, PyObject *obj)
static PyObject * __pyx_memview_get_float (const char *itemp)
static int __pyx_memview_set_float (const char *itemp, PyObject *obj)
static PyObject * __pyx_memview_get_double (const char *itemp)
static int __pyx_memview_set_double (const char *itemp, PyObject *obj)
static int __pyx_memviewslice_is_contig (const __Pyx_memviewslice *mvs, char order, int ndim)
static int __pyx_slices_overlap (__Pyx_memviewslice *slice1, __Pyx_memviewslice *slice2, int ndim, size_t itemsize)
static __Pyx_memviewslice __pyx_memoryview_copy_new_contig (const __Pyx_memviewslice *from_mvs, const char *mode, int ndim, size_t sizeof_dtype, int contig_flag, int dtype_is_object)
static CYTHON_INLINE PyObject * __pyx_capsule_create (void *p, const char *sig)
static CYTHON_INLINE char __Pyx_PyInt_As_char (PyObject *)
static int __pyx_typeinfo_cmp (__Pyx_TypeInfo *a, __Pyx_TypeInfo *b)
static int __Pyx_ValidateAndInit_memviewslice (int *axes_specs, int c_or_f_flag, int buf_flags, int ndim, __Pyx_TypeInfo *dtype, __Pyx_BufFmt_StackElem stack[], __Pyx_memviewslice *memviewslice, PyObject *original_obj)
static CYTHON_INLINE
__Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_int (PyObject *)
static CYTHON_INLINE
__Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_long (PyObject *)
static CYTHON_INLINE
__Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_float (PyObject *)
static CYTHON_INLINE
__Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_double (PyObject *)
static int __Pyx_check_binary_version (void)
static PyObject * __Pyx_ImportModule (const char *name)
static PyTypeObject * __Pyx_ImportType (const char *module_name, const char *class_name, size_t size, int strict)
static int __pyx_bisect_code_objects (__Pyx_CodeObjectCacheEntry *entries, int count, int code_line)
static PyCodeObject * __pyx_find_code_object (int code_line)
static void __pyx_insert_code_object (int code_line, PyCodeObject *code_object)
static void __Pyx_AddTraceback (const char *funcname, int c_line, int py_line, const char *filename)
static int __Pyx_InitStrings (__Pyx_StringTabEntry *t)
static CYTHON_INLINE arrayobject * __pyx_f_7cpython_5array_clone (arrayobject *, Py_ssize_t, int)
static CYTHON_INLINE int __pyx_f_7cpython_5array_extend_buffer (arrayobject *, char *, Py_ssize_t)
static CYTHON_INLINE Datum * __pyx_f_12pynestkernel_python_object_to_datum (PyObject *)
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_datum_to_object (Datum *)
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_array_to_object (ArrayDatum *)
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_dict_to_object (DictionaryDatum *)
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_connection_to_object (ConnectionDatum *)
static CYTHON_INLINE Datum * __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum (PyObject *, struct __pyx_fuse_0_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum *__pyx_optional_args)
static CYTHON_INLINE Datum * __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum (PyObject *, struct __pyx_fuse_0_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum *__pyx_optional_args)
static CYTHON_INLINE Datum * __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_int_1d_t, struct __pyx_fuse_1_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum *__pyx_optional_args)
static CYTHON_INLINE Datum * __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_long_1d_t, struct __pyx_fuse_2_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum *__pyx_optional_args)
static CYTHON_INLINE Datum * __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_float_1d_t, struct __pyx_fuse_3_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum *__pyx_optional_args)
static CYTHON_INLINE Datum * __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_double_1d_t, struct __pyx_fuse_4_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum *__pyx_optional_args)
static CYTHON_INLINE PyObject * __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object (__pyx_t_12pynestkernel_sli_vector_int_ptr_t, struct __pyx_fuse_0_0__pyx_opt_args_12pynestkernel_sli_vector_to_object *__pyx_optional_args)
static CYTHON_INLINE PyObject * __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object (__pyx_t_12pynestkernel_sli_vector_double_ptr_t, struct __pyx_fuse_1_1__pyx_opt_args_12pynestkernel_sli_vector_to_object *__pyx_optional_args)
static struct __pyx_array_obj * __pyx_array_new (PyObject *, Py_ssize_t, char *, char *, char *)
static void * __pyx_align_pointer (void *, size_t)
static PyObject * __pyx_memoryview_new (PyObject *, int, int, __Pyx_TypeInfo *)
static CYTHON_INLINE int __pyx_memoryview_check (PyObject *)
static PyObject * _unellipsify (PyObject *, int)
static PyObject * assert_direct_dimensions (Py_ssize_t *, int)
static struct
__pyx_memoryview_obj * __pyx_memview_slice (struct __pyx_memoryview_obj *, PyObject *)
static int __pyx_memoryview_slice_memviewslice (__Pyx_memviewslice *, Py_ssize_t, Py_ssize_t, Py_ssize_t, int, int, int *, Py_ssize_t, Py_ssize_t, Py_ssize_t, int, int, int, int)
static char * __pyx_pybuffer_index (Py_buffer *, char *, Py_ssize_t, Py_ssize_t)
static int __pyx_memslice_transpose (__Pyx_memviewslice *)
static PyObject * __pyx_memoryview_fromslice (__Pyx_memviewslice, int, PyObject *(*)(char *), int(*)(char *, PyObject *), int)
static __Pyx_memviewslice * __pyx_memoryview_get_slice_from_memoryview (struct __pyx_memoryview_obj *, __Pyx_memviewslice *)
static void __pyx_memoryview_slice_copy (struct __pyx_memoryview_obj *, __Pyx_memviewslice *)
static PyObject * __pyx_memoryview_copy_object (struct __pyx_memoryview_obj *)
static PyObject * __pyx_memoryview_copy_object_from_slice (struct __pyx_memoryview_obj *, __Pyx_memviewslice *)
static Py_ssize_t abs_py_ssize_t (Py_ssize_t)
static char __pyx_get_best_slice_order (__Pyx_memviewslice *, int)
static void _copy_strided_to_strided (char *, Py_ssize_t *, char *, Py_ssize_t *, Py_ssize_t *, Py_ssize_t *, int, size_t)
static void copy_strided_to_strided (__Pyx_memviewslice *, __Pyx_memviewslice *, int, size_t)
static Py_ssize_t __pyx_memoryview_slice_get_size (__Pyx_memviewslice *, int)
static Py_ssize_t __pyx_fill_contig_strides_array (Py_ssize_t *, Py_ssize_t *, Py_ssize_t, int, char)
static void * __pyx_memoryview_copy_data_to_temp (__Pyx_memviewslice *, __Pyx_memviewslice *, char, int)
static int __pyx_memoryview_err_extents (int, Py_ssize_t, Py_ssize_t)
static int __pyx_memoryview_err_dim (PyObject *, char *, int)
static int __pyx_memoryview_err (PyObject *, char *)
static int __pyx_memoryview_copy_contents (__Pyx_memviewslice, __Pyx_memviewslice, int, int, int)
static void __pyx_memoryview_broadcast_leading (__Pyx_memviewslice *, int, int)
static void __pyx_memoryview_refcount_copying (__Pyx_memviewslice *, int, int, int)
static void __pyx_memoryview_refcount_objects_in_slice_with_gil (char *, Py_ssize_t *, Py_ssize_t *, int, int)
static void __pyx_memoryview_refcount_objects_in_slice (char *, Py_ssize_t *, Py_ssize_t *, int, int)
static void __pyx_memoryview_slice_assign_scalar (__Pyx_memviewslice *, int, size_t, void *, int)
static void __pyx_memoryview__slice_assign_scalar (char *, Py_ssize_t *, Py_ssize_t *, int, size_t, void *)
static std::string __pyx_convert_string_from_py_ (PyObject *)
static PyObject * __pyx_convert_string_to_py_ (const std::string &)
static int __pyx_pf_12pynestkernel_8SLIDatum___cinit__ (struct __pyx_obj_12pynestkernel_SLIDatum *__pyx_v_self)
static void __pyx_pf_12pynestkernel_8SLIDatum_2__dealloc__ (struct __pyx_obj_12pynestkernel_SLIDatum *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_8SLIDatum_4__repr__ (struct __pyx_obj_12pynestkernel_SLIDatum *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_8SLIDatum_5dtype___get__ (struct __pyx_obj_12pynestkernel_SLIDatum *__pyx_v_self)
static int __pyx_pf_12pynestkernel_10SLILiteral___init__ (struct __pyx_obj_12pynestkernel_SLILiteral *__pyx_v_self, PyObject *__pyx_v_name)
static Py_hash_t __pyx_pf_12pynestkernel_10SLILiteral_2__hash__ (struct __pyx_obj_12pynestkernel_SLILiteral *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_4__repr__ (struct __pyx_obj_12pynestkernel_SLILiteral *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_6__str__ (struct __pyx_obj_12pynestkernel_SLILiteral *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__ (PyObject *__pyx_v_self, PyObject *__pyx_v_other, int __pyx_v_op)
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_4name___get__ (struct __pyx_obj_12pynestkernel_SLILiteral *__pyx_v_self)
static int __pyx_pf_12pynestkernel_10NESTEngine___cinit__ (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self)
static void __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__ (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_4init (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self, PyObject *__pyx_v_argv, PyObject *__pyx_v_modulepath)
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_6run (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self, PyObject *__pyx_v_cmd)
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_8push (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self, PyObject *__pyx_v_obj)
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_10pop (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self)
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums (struct __pyx_obj_12pynestkernel_NESTEngine *__pyx_v_self, PyObject *__pyx_v_conns)
static int __pyx_pf_7cpython_5array_5array___getbuffer__ (arrayobject *__pyx_v_self, Py_buffer *__pyx_v_info, CYTHON_UNUSED int __pyx_v_flags)
static void __pyx_pf_7cpython_5array_5array_2__releasebuffer__ (CYTHON_UNUSED arrayobject *__pyx_v_self, Py_buffer *__pyx_v_info)
static int __pyx_array_MemoryView_5array___cinit__ (struct __pyx_array_obj *__pyx_v_self, PyObject *__pyx_v_shape, Py_ssize_t __pyx_v_itemsize, PyObject *__pyx_v_format, PyObject *__pyx_v_mode, int __pyx_v_allocate_buffer)
static int __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__ (struct __pyx_array_obj *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags)
static void __pyx_array_MemoryView_5array_4__dealloc__ (struct __pyx_array_obj *__pyx_v_self)
static PyObject * get_memview_MemoryView_5array_7memview___get__ (struct __pyx_array_obj *__pyx_v_self)
static PyObject * __pyx_array_MemoryView_5array_6__getattr__ (struct __pyx_array_obj *__pyx_v_self, PyObject *__pyx_v_attr)
static PyObject * __pyx_array_MemoryView_5array_8__getitem__ (struct __pyx_array_obj *__pyx_v_self, PyObject *__pyx_v_item)
static int __pyx_array_MemoryView_5array_10__setitem__ (struct __pyx_array_obj *__pyx_v_self, PyObject *__pyx_v_item, PyObject *__pyx_v_value)
static int __pyx_MemviewEnum_MemoryView_4Enum___init__ (struct __pyx_MemviewEnum_obj *__pyx_v_self, PyObject *__pyx_v_name)
static PyObject * __pyx_MemviewEnum_MemoryView_4Enum_2__repr__ (struct __pyx_MemviewEnum_obj *__pyx_v_self)
static int __pyx_memoryview_MemoryView_10memoryview___cinit__ (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_obj, int __pyx_v_flags, int __pyx_v_dtype_is_object)
static void __pyx_memoryview_MemoryView_10memoryview_2__dealloc__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_4__getitem__ (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_index)
static int __pyx_memoryview_MemoryView_10memoryview_6__setitem__ (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value)
static int __pyx_memoryview_getbuffer_MemoryView_10memoryview_8__getbuffer__ (struct __pyx_memoryview_obj *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags)
static PyObject * __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview__get__base_MemoryView_10memoryview_4base___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__ (struct __pyx_memoryview_obj *__pyx_v_self)
static Py_ssize_t __pyx_memoryview_MemoryView_10memoryview_10__len__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_12__repr__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_14__str__ (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_16is_c_contig (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_18is_f_contig (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_20copy (struct __pyx_memoryview_obj *__pyx_v_self)
static PyObject * __pyx_memoryview_MemoryView_10memoryview_22copy_fortran (struct __pyx_memoryview_obj *__pyx_v_self)
static void __pyx_memoryviewslice_MemoryView_16_memoryviewslice___dealloc__ (struct __pyx_memoryviewslice_obj *__pyx_v_self)
static PyObject * __pyx_memoryviewslice__get__base_MemoryView_16_memoryviewslice_4base___get__ (struct __pyx_memoryviewslice_obj *__pyx_v_self)
static PyObject * __pyx_tp_new_12pynestkernel_SLIDatum (PyTypeObject *t, PyObject *a, PyObject *k)
static PyObject * __pyx_tp_new_12pynestkernel_SLILiteral (PyTypeObject *t, PyObject *a, PyObject *k)
static PyObject * __pyx_tp_new_12pynestkernel_NESTEngine (PyTypeObject *t, PyObject *a, PyObject *k)
static PyObject * __pyx_tp_new_array (PyTypeObject *t, PyObject *a, PyObject *k)
static PyObject * __pyx_tp_new_Enum (PyTypeObject *t, PyObject *a, PyObject *k)
static PyObject * __pyx_tp_new_memoryview (PyTypeObject *t, PyObject *a, PyObject *k)
static PyObject * __pyx_tp_new__memoryviewslice (PyTypeObject *t, PyObject *a, PyObject *k)
static int __pyx_pw_12pynestkernel_8SLIDatum_1__cinit__ (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static void __pyx_pw_12pynestkernel_8SLIDatum_3__dealloc__ (PyObject *__pyx_v_self)
static PyObject * __pyx_pw_12pynestkernel_8SLIDatum_5__repr__ (PyObject *__pyx_v_self)
static PyObject * __pyx_f_12pynestkernel_8SLIDatum__set_datum (struct __pyx_obj_12pynestkernel_SLIDatum *__pyx_v_self, Datum *__pyx_v_dat, PyObject *__pyx_v_dtype)
static PyObject * __pyx_pw_12pynestkernel_8SLIDatum_5dtype_1__get__ (PyObject *__pyx_v_self)
static int __pyx_pw_12pynestkernel_10SLILiteral_1__init__ (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static Py_hash_t __pyx_pw_12pynestkernel_10SLILiteral_3__hash__ (PyObject *__pyx_v_self)
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_5__repr__ (PyObject *__pyx_v_self)
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_7__str__ (PyObject *__pyx_v_self)
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_9__richcmp__ (PyObject *__pyx_v_self, PyObject *__pyx_v_other, int __pyx_v_op)
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_4name_1__get__ (PyObject *__pyx_v_self)
static int __pyx_pw_12pynestkernel_10NESTEngine_1__cinit__ (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static void __pyx_pw_12pynestkernel_10NESTEngine_3__dealloc__ (PyObject *__pyx_v_self)
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_5init (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_7run (PyObject *__pyx_v_self, PyObject *__pyx_v_cmd)
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_9push (PyObject *__pyx_v_self, PyObject *__pyx_v_obj)
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_11pop (PyObject *__pyx_v_self, CYTHON_UNUSED PyObject *unused)
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_13push_connection_datums (PyObject *__pyx_v_self, PyObject *__pyx_v_conns)
static CYTHON_UNUSED int __pyx_pw_7cpython_5array_5array_1__getbuffer__ (PyObject *__pyx_v_self, Py_buffer *__pyx_v_info, int __pyx_v_flags)
static CYTHON_UNUSED void __pyx_pw_7cpython_5array_5array_3__releasebuffer__ (PyObject *__pyx_v_self, Py_buffer *__pyx_v_info)
static CYTHON_INLINE arrayobject * __pyx_f_7cpython_5array_copy (arrayobject *__pyx_v_self)
static CYTHON_INLINE int __pyx_f_7cpython_5array_extend (arrayobject *__pyx_v_self, arrayobject *__pyx_v_other)
static CYTHON_INLINE void __pyx_f_7cpython_5array_zero (arrayobject *__pyx_v_self)
static int __pyx_array___cinit__ (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static void __pyx_array___dealloc__ (PyObject *__pyx_v_self)
static PyObject * __pyx_array___getattr__ (PyObject *__pyx_v_self, PyObject *__pyx_v_attr)
static PyObject * __pyx_array___getitem__ (PyObject *__pyx_v_self, PyObject *__pyx_v_item)
static int __pyx_array___setitem__ (PyObject *__pyx_v_self, PyObject *__pyx_v_item, PyObject *__pyx_v_value)
static int __pyx_MemviewEnum___init__ (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static PyObject * __pyx_MemviewEnum___repr__ (PyObject *__pyx_v_self)
static int __pyx_memoryview___cinit__ (PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds)
static void __pyx_memoryview___dealloc__ (PyObject *__pyx_v_self)
static char * __pyx_memoryview_get_item_pointer (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_index)
static PyObject * __pyx_memoryview___getitem__ (PyObject *__pyx_v_self, PyObject *__pyx_v_index)
static int __pyx_memoryview___setitem__ (PyObject *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value)
static PyObject * __pyx_memoryview_is_slice (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_obj)
static PyObject * __pyx_memoryview_setitem_slice_assignment (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_dst, PyObject *__pyx_v_src)
static PyObject * __pyx_memoryview_setitem_slice_assign_scalar (struct __pyx_memoryview_obj *__pyx_v_self, struct __pyx_memoryview_obj *__pyx_v_dst, PyObject *__pyx_v_value)
static PyObject * __pyx_memoryview_setitem_indexed (struct __pyx_memoryview_obj *__pyx_v_self, PyObject *__pyx_v_index, PyObject *__pyx_v_value)
static PyObject * __pyx_memoryview_convert_item_to_object (struct __pyx_memoryview_obj *__pyx_v_self, char *__pyx_v_itemp)
static PyObject * __pyx_memoryview_assign_item_from_object (struct __pyx_memoryview_obj *__pyx_v_self, char *__pyx_v_itemp, PyObject *__pyx_v_value)
static Py_ssize_t __pyx_memoryview___len__ (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview___repr__ (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview___str__ (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryview_is_c_contig (PyObject *__pyx_v_self, CYTHON_UNUSED PyObject *unused)
static PyObject * __pyx_memoryview_is_f_contig (PyObject *__pyx_v_self, CYTHON_UNUSED PyObject *unused)
static PyObject * __pyx_memoryview_copy (PyObject *__pyx_v_self, CYTHON_UNUSED PyObject *unused)
static PyObject * __pyx_memoryview_copy_fortran (PyObject *__pyx_v_self, CYTHON_UNUSED PyObject *unused)
static void __pyx_memoryviewslice___dealloc__ (PyObject *__pyx_v_self)
static PyObject * __pyx_memoryviewslice_convert_item_to_object (struct __pyx_memoryviewslice_obj *__pyx_v_self, char *__pyx_v_itemp)
static PyObject * __pyx_memoryviewslice_assign_item_from_object (struct __pyx_memoryviewslice_obj *__pyx_v_self, char *__pyx_v_itemp, PyObject *__pyx_v_value)
static PyObject * __pyx_memoryview_fromslice (__Pyx_memviewslice __pyx_v_memviewslice, int __pyx_v_ndim, PyObject *(*__pyx_v_to_object_func)(char *), int(*__pyx_v_to_dtype_func)(char *, PyObject *), int __pyx_v_dtype_is_object)
static PyObject * __pyx_tp_new_12pynestkernel_SLIDatum (PyTypeObject *t, CYTHON_UNUSED PyObject *a, CYTHON_UNUSED PyObject *k)
static void __pyx_tp_dealloc_12pynestkernel_SLIDatum (PyObject *o)
static PyObject * __pyx_getprop_12pynestkernel_8SLIDatum_dtype (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_tp_new_12pynestkernel_SLILiteral (PyTypeObject *t, CYTHON_UNUSED PyObject *a, CYTHON_UNUSED PyObject *k)
static void __pyx_tp_dealloc_12pynestkernel_SLILiteral (PyObject *o)
static int __pyx_tp_traverse_12pynestkernel_SLILiteral (PyObject *o, visitproc v, void *a)
static int __pyx_tp_clear_12pynestkernel_SLILiteral (PyObject *o)
static PyObject * __pyx_getprop_12pynestkernel_10SLILiteral_name (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_tp_new_12pynestkernel_NESTEngine (PyTypeObject *t, CYTHON_UNUSED PyObject *a, CYTHON_UNUSED PyObject *k)
static void __pyx_tp_dealloc_12pynestkernel_NESTEngine (PyObject *o)
static void __pyx_tp_dealloc_array (PyObject *o)
static PyObject * __pyx_sq_item_array (PyObject *o, Py_ssize_t i)
static int __pyx_mp_ass_subscript_array (PyObject *o, PyObject *i, PyObject *v)
static PyObject * __pyx_tp_getattro_array (PyObject *o, PyObject *n)
static PyObject * __pyx_getprop___pyx_array_memview (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_tp_new_Enum (PyTypeObject *t, CYTHON_UNUSED PyObject *a, CYTHON_UNUSED PyObject *k)
static void __pyx_tp_dealloc_Enum (PyObject *o)
static int __pyx_tp_traverse_Enum (PyObject *o, visitproc v, void *a)
static int __pyx_tp_clear_Enum (PyObject *o)
static void __pyx_tp_dealloc_memoryview (PyObject *o)
static int __pyx_tp_traverse_memoryview (PyObject *o, visitproc v, void *a)
static int __pyx_tp_clear_memoryview (PyObject *o)
static PyObject * __pyx_sq_item_memoryview (PyObject *o, Py_ssize_t i)
static int __pyx_mp_ass_subscript_memoryview (PyObject *o, PyObject *i, PyObject *v)
static PyObject * __pyx_getprop___pyx_memoryview_T (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_base (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_shape (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_strides (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_suboffsets (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_ndim (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_itemsize (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_nbytes (PyObject *o, CYTHON_UNUSED void *x)
static PyObject * __pyx_getprop___pyx_memoryview_size (PyObject *o, CYTHON_UNUSED void *x)
static void __pyx_tp_dealloc__memoryviewslice (PyObject *o)
static int __pyx_tp_traverse__memoryviewslice (PyObject *o, visitproc v, void *a)
static int __pyx_tp_clear__memoryviewslice (PyObject *o)
static PyObject * __pyx_getprop___pyx_memoryviewslice_base (PyObject *o, CYTHON_UNUSED void *x)
static int __Pyx_InitCachedBuiltins (void)
static int __Pyx_InitCachedConstants (void)
static int __Pyx_InitGlobals (void)
PyMODINIT_FUNC initpynestkernel (void)
PyMODINIT_FUNC PyInit_pynestkernel (void)
static int __Pyx_ParseOptionalKeywords (PyObject *kwds, PyObject **argnames[], PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args, const char *function_name)
static void __Pyx_WriteUnraisable (const char *name, CYTHON_UNUSED int clineno, CYTHON_UNUSED int lineno, CYTHON_UNUSED const char *filename, int full_traceback)
Variables
static int __Pyx_sys_getdefaultencoding_not_ascii
static char * __PYX_DEFAULT_STRING_ENCODING
static PyObject * __pyx_m
static PyObject * __pyx_d
static PyObject * __pyx_b
static PyObject * __pyx_empty_tuple
static PyObject * __pyx_empty_bytes
static int __pyx_lineno
static int __pyx_clineno = 0
static const char * __pyx_cfilenm = __FILE__
static const char * __pyx_filename
static const char * __pyx_f []
static struct
__pyx_vtabstruct_12pynestkernel_SLIDatum * __pyx_vtabptr_12pynestkernel_SLIDatum
static struct
__pyx_vtabstruct_memoryview * __pyx_vtabptr_memoryview
static struct
__pyx_vtabstruct__memoryviewslice * __pyx_vtabptr__memoryviewslice
static __Pyx_RefNannyAPIStruct * __Pyx_RefNanny = NULL
static Py_ssize_t __Pyx_zeros [] = {0, 0, 0, 0, 0, 0, 0, 0}
static Py_ssize_t __Pyx_minusones [] = {-1, -1, -1, -1, -1, -1, -1, -1}
static struct __Pyx_CodeObjectCache __pyx_code_cache = {0,0,NULL}
static PyTypeObject * __pyx_ptype_7cpython_4type_type = 0
static PyTypeObject * __pyx_ptype_7cpython_4bool_bool = 0
static PyTypeObject * __pyx_ptype_7cpython_7complex_complex = 0
static PyTypeObject * __pyx_ptype_7cpython_5array_array = 0
static PyTypeObject * __pyx_ptype_12pynestkernel_SLIDatum = 0
static PyTypeObject * __pyx_ptype_12pynestkernel_SLILiteral = 0
static PyTypeObject * __pyx_ptype_12pynestkernel_NESTEngine = 0
static PyTypeObject * __pyx_array_type = 0
static PyTypeObject * __pyx_MemviewEnum_type = 0
static PyTypeObject * __pyx_memoryview_type = 0
static PyTypeObject * __pyx_memoryviewslice_type = 0
static std::string __pyx_v_12pynestkernel_SLI_TYPE_BOOL
static std::string __pyx_v_12pynestkernel_SLI_TYPE_INTEGER
static std::string __pyx_v_12pynestkernel_SLI_TYPE_DOUBLE
static std::string __pyx_v_12pynestkernel_SLI_TYPE_STRING
static std::string __pyx_v_12pynestkernel_SLI_TYPE_LITERAL
static std::string __pyx_v_12pynestkernel_SLI_TYPE_ARRAY
static std::string __pyx_v_12pynestkernel_SLI_TYPE_DICTIONARY
static std::string __pyx_v_12pynestkernel_SLI_TYPE_CONNECTION
static std::string __pyx_v_12pynestkernel_SLI_TYPE_VECTOR_INT
static std::string __pyx_v_12pynestkernel_SLI_TYPE_VECTOR_DOUBLE
static std::string __pyx_v_12pynestkernel_SLI_TYPE_MASK
static std::string __pyx_v_12pynestkernel_SLI_TYPE_PARAMETER
static PyObject * __pyx_v_12pynestkernel_CONN_NAME_SRC = 0
static PyObject * __pyx_v_12pynestkernel_CONN_NAME_SYN = 0
static PyObject * __pyx_v_12pynestkernel_CONN_NAME_PRT = 0
static PyObject * __pyx_v_12pynestkernel_CONN_NAME_THREAD = 0
static PyObject * __pyx_v_12pynestkernel_ARRAY_LONG = 0
static PyObject * __pyx_v_12pynestkernel_ARRAY_DOUBLE = 0
static int __pyx_v_12pynestkernel_HAVE_NUMPY
static PyObject * generic = 0
static PyObject * strided = 0
static PyObject * indirect = 0
static PyObject * contiguous = 0
static PyObject * indirect_contiguous = 0
static __Pyx_TypeInfo __Pyx_TypeInfo_int = { "int", NULL, sizeof(int), { 0 }, 0, IS_UNSIGNED(int) ? 'U' : 'I', IS_UNSIGNED(int), 0 }
static __Pyx_TypeInfo __Pyx_TypeInfo_long = { "long", NULL, sizeof(long), { 0 }, 0, IS_UNSIGNED(long) ? 'U' : 'I', IS_UNSIGNED(long), 0 }
static __Pyx_TypeInfo __Pyx_TypeInfo_float = { "float", NULL, sizeof(float), { 0 }, 0, 'R', 0, 0 }
static __Pyx_TypeInfo __Pyx_TypeInfo_double = { "double", NULL, sizeof(double), { 0 }, 0, 'R', 0, 0 }
int __pyx_module_is_main_pynestkernel = 0
static PyObject * __pyx_builtin_ImportError
static PyObject * __pyx_builtin_Exception
static PyObject * __pyx_builtin_range
static PyObject * __pyx_builtin_xrange
static PyObject * __pyx_builtin_ValueError
static PyObject * __pyx_builtin_TypeError
static PyObject * __pyx_builtin_MemoryError
static PyObject * __pyx_builtin_enumerate
static PyObject * __pyx_builtin_Ellipsis
static PyObject * __pyx_builtin_id
static PyObject * __pyx_builtin_IndexError
static char __pyx_k_ [] = ""
static char __pyx_k_0 [] = "{0}"
static char __pyx_k_O [] = "O"
static char __pyx_k_c [] = "c"
static char __pyx_k_d [] = "d"
static char __pyx_k_l [] = "l"
static char __pyx_k_id [] = "id"
static char __pyx_k_doc [] = "__doc__"
static char __pyx_k_int [] = "int_"
static char __pyx_k_obj [] = "obj"
static char __pyx_k_argv [] = "argv"
static char __pyx_k_base [] = "base"
static char __pyx_k_item [] = "item"
static char __pyx_k_main [] = "__main__"
static char __pyx_k_mode [] = "mode"
static char __pyx_k_name [] = "name"
static char __pyx_k_ndim [] = "ndim"
static char __pyx_k_pack [] = "pack"
static char __pyx_k_port [] = "port"
static char __pyx_k_size [] = "size"
static char __pyx_k_step [] = "step"
static char __pyx_k_stop [] = "stop"
static char __pyx_k_test [] = "__test__"
static char __pyx_k_array [] = "array"
static char __pyx_k_class [] = "__class__"
static char __pyx_k_dtype [] = "dtype"
static char __pyx_k_error [] = "error"
static char __pyx_k_flags [] = "flags"
static char __pyx_k_float [] = "float_"
static char __pyx_k_items [] = "items"
static char __pyx_k_numpy [] = "numpy"
static char __pyx_k_range [] = "range"
static char __pyx_k_shape [] = "shape"
static char __pyx_k_start [] = "start"
static char __pyx_k_encode [] = "encode"
static char __pyx_k_format [] = "format"
static char __pyx_k_import [] = "__import__"
static char __pyx_k_module [] = "__module__"
static char __pyx_k_name_2 [] = "__name__"
static char __pyx_k_pynest [] = "pynest\000"
static char __pyx_k_source [] = "source"
static char __pyx_k_struct [] = "struct"
static char __pyx_k_unpack [] = "unpack"
static char __pyx_k_xrange [] = "xrange"
static char __pyx_k_fortran [] = "fortran"
static char __pyx_k_integer [] = "integer"
static char __pyx_k_memview [] = "memview"
static char __pyx_k_ndarray [] = "ndarray"
static char __pyx_k_prepare [] = "__prepare__"
static char __pyx_k_CONN_LEN [] = "CONN_LEN"
static char __pyx_k_Ellipsis [] = "Ellipsis"
static char __pyx_k_booltype [] = "booltype"
static char __pyx_k_floating [] = "floating"
static char __pyx_k_itemsize [] = "itemsize"
static char __pyx_k_masktype [] = "masktype"
static char __pyx_k_qualname [] = "__qualname__"
static char __pyx_k_Exception [] = "Exception"
static char __pyx_k_NESTError [] = "NESTError"
static char __pyx_k_TypeError [] = "TypeError"
static char __pyx_k_arraytype [] = "arraytype"
static char __pyx_k_enumerate [] = "enumerate"
static char __pyx_k_metaclass [] = "__metaclass__"
static char __pyx_k_IndexError [] = "IndexError"
static char __pyx_k_SLIDatum_0 [] = "<SLIDatum: {0}>"
static char __pyx_k_ValueError [] = "ValueError"
static char __pyx_k_doubletype [] = "doubletype"
static char __pyx_k_frombuffer [] = "frombuffer"
static char __pyx_k_issubdtype [] = "issubdtype"
static char __pyx_k_modulepath [] = "modulepath"
static char __pyx_k_pyx_vtable [] = "__pyx_vtable__"
static char __pyx_k_stringtype [] = "stringtype"
static char __pyx_k_ImportError [] = "ImportError"
static char __pyx_k_MemoryError [] = "MemoryError"
static char __pyx_k_integertype [] = "integertype"
static char __pyx_k_literaltype [] = "literaltype"
static char __pyx_k_SLILiteral_0 [] = "<SLILiteral: {0}>"
static char __pyx_k_pynestkernel [] = "pynestkernel"
static char __pyx_k_intvectortype [] = "intvectortype"
static char __pyx_k_parametertype [] = "parametertype"
static char __pyx_k_pyx_getbuffer [] = "__pyx_getbuffer"
static char __pyx_k_target_thread [] = "target_thread"
static char __pyx_k_connectiontype [] = "connectiontype"
static char __pyx_k_dictionarytype [] = "dictionarytype"
static char __pyx_k_allocate_buffer [] = "allocate_buffer"
static char __pyx_k_dtype_is_object [] = "dtype_is_object"
static char __pyx_k_synapse_modelid [] = "synapse_modelid"
static char __pyx_k_doublevectortype [] = "doublevectortype"
static char __pyx_k_pyx_releasebuffer [] = "__pyx_releasebuffer"
static char __pyx_k_strided_and_direct [] = "<strided and direct>"
static char __pyx_k_unknown_SLI_type_0 [] = "unknown SLI type: {0}"
static char __pyx_k_argv_can_t_be_empty [] = "argv can't be empty"
static char __pyx_k_engine_uninitialized [] = "engine uninitialized"
static char __pyx_k_strided_and_indirect [] = "<strided and indirect>"
static char __pyx_k_SLIDatum_unassociated [] = "<SLIDatum: unassociated>"
static char __pyx_k_contiguous_and_direct [] = "<contiguous and direct>"
static char __pyx_k_unknown_Python_type_0 [] = "unknown Python type: {0}"
static char __pyx_k_MemoryView_of_r_object [] = "<MemoryView of %r object>"
static char __pyx_k_MemoryView_of_r_at_0x_x [] = "<MemoryView of %r at 0x%x>"
static char __pyx_k_contiguous_and_indirect [] = "<contiguous and indirect>"
static char __pyx_k_datum_is_a_null_pointer [] = "datum is a null pointer"
static char __pyx_k_Cannot_index_with_type_s [] = "Cannot index with type '%s'"
static char __pyx_k_getbuffer_obj_view_flags [] = "getbuffer(obj, view, flags)"
static char __pyx_k_unknown_SLI_datum_type_0 [] = "unknown SLI datum type: {0}"
static char __pyx_k_Dimension_d_is_not_direct [] = "Dimension %d is not direct"
static char __pyx_k_Invalid_shape_in_axis_d_d [] = "Invalid shape in axis %d: %d."
static char __pyx_k_Index_out_of_bounds_axis_d [] = "Index out of bounds (axis %d)"
static char __pyx_k_engine_already_initialized [] = "engine already initialized"
static char __pyx_k_interpreter_stack_is_empty [] = "interpreter stack is empty"
static char __pyx_k_Step_may_not_be_zero_axis_d [] = "Step may not be zero (axis %d)"
static char __pyx_k_itemsize_0_for_cython_array [] = "itemsize <= 0 for cython.array"
static char __pyx_k_couldn_t_allocate_argv_bytes [] = "couldn't allocate argv_bytes"
static char __pyx_k_unable_to_allocate_array_data [] = "unable to allocate array data."
static char __pyx_k_strided_and_direct_or_indirect [] = "<strided and direct or indirect>"
static char __pyx_k_All_dimensions_preceding_dimensi [] = "All dimensions preceding dimension %d must be indexed and not sliced"
static char __pyx_k_Buffer_view_does_not_expose_stri [] = "Buffer view does not expose strides"
static char __pyx_k_Can_only_create_a_buffer_that_is [] = "Can only create a buffer that is contiguous in memory."
static char __pyx_k_Cannot_transpose_memoryview_with [] = "Cannot transpose memoryview with indirect dimensions"
static char __pyx_k_Empty_shape_tuple_for_cython_arr [] = "Empty shape tuple for cython.array"
static char __pyx_k_Indirect_dimensions_not_supporte [] = "Indirect dimensions not supported"
static char __pyx_k_Invalid_mode_expected_c_or_fortr [] = "Invalid mode, expected 'c' or 'fortran', got %s"
static char __pyx_k_Out_of_bounds_on_buffer_access_a [] = "Out of bounds on buffer access (axis %d)"
static char __pyx_k_Unable_to_convert_item_to_object [] = "Unable to convert item to object"
static char __pyx_k_conversion_resulted_in_a_None_ob [] = "conversion resulted in a None object"
static char __pyx_k_conversion_resulted_in_a_null_po [] = "conversion resulted in a null pointer"
static char __pyx_k_failed_to_unpack_passed_connecti [] = "failed to unpack passed connection generator object"
static char __pyx_k_got_differing_extents_in_dimensi [] = "got differing extents in dimension %d (got %d and %d)"
static char __pyx_k_only_vectors_of_integers_or_floa [] = "only vectors of integers or floats are supported"
static char __pyx_k_unable_to_allocate_shape_and_str [] = "unable to allocate shape and strides."
static PyObject * __pyx_kp_u_
static PyObject * __pyx_kp_s_0
static PyObject * __pyx_kp_s_Buffer_view_does_not_expose_stri
static PyObject * __pyx_n_s_CONN_LEN
static PyObject * __pyx_kp_s_Can_only_create_a_buffer_that_is
static PyObject * __pyx_kp_s_Cannot_index_with_type_s
static PyObject * __pyx_n_s_Ellipsis
static PyObject * __pyx_kp_s_Empty_shape_tuple_for_cython_arr
static PyObject * __pyx_n_s_Exception
static PyObject * __pyx_n_s_ImportError
static PyObject * __pyx_n_s_IndexError
static PyObject * __pyx_kp_s_Indirect_dimensions_not_supporte
static PyObject * __pyx_kp_s_Invalid_mode_expected_c_or_fortr
static PyObject * __pyx_kp_s_Invalid_shape_in_axis_d_d
static PyObject * __pyx_n_s_MemoryError
static PyObject * __pyx_kp_s_MemoryView_of_r_at_0x_x
static PyObject * __pyx_kp_s_MemoryView_of_r_object
static PyObject * __pyx_n_s_NESTError
static PyObject * __pyx_n_b_O
static PyObject * __pyx_kp_s_Out_of_bounds_on_buffer_access_a
static PyObject * __pyx_kp_s_SLIDatum_0
static PyObject * __pyx_kp_s_SLIDatum_unassociated
static PyObject * __pyx_kp_s_SLILiteral_0
static PyObject * __pyx_n_s_TypeError
static PyObject * __pyx_kp_s_Unable_to_convert_item_to_object
static PyObject * __pyx_n_s_ValueError
static PyObject * __pyx_n_s_allocate_buffer
static PyObject * __pyx_n_s_argv
static PyObject * __pyx_kp_s_argv_can_t_be_empty
static PyObject * __pyx_n_s_array
static PyObject * __pyx_n_b_arraytype
static PyObject * __pyx_n_s_base
static PyObject * __pyx_n_b_booltype
static PyObject * __pyx_n_s_c
static PyObject * __pyx_n_u_c
static PyObject * __pyx_n_s_class
static PyObject * __pyx_n_b_connectiontype
static PyObject * __pyx_kp_s_contiguous_and_direct
static PyObject * __pyx_kp_s_contiguous_and_indirect
static PyObject * __pyx_kp_s_conversion_resulted_in_a_None_ob
static PyObject * __pyx_kp_s_conversion_resulted_in_a_null_po
static PyObject * __pyx_kp_s_couldn_t_allocate_argv_bytes
static PyObject * __pyx_n_s_d
static PyObject * __pyx_kp_s_datum_is_a_null_pointer
static PyObject * __pyx_n_b_dictionarytype
static PyObject * __pyx_n_s_doc
static PyObject * __pyx_n_b_doubletype
static PyObject * __pyx_n_b_doublevectortype
static PyObject * __pyx_n_s_dtype
static PyObject * __pyx_n_s_dtype_is_object
static PyObject * __pyx_n_s_encode
static PyObject * __pyx_kp_s_engine_already_initialized
static PyObject * __pyx_kp_s_engine_uninitialized
static PyObject * __pyx_n_s_enumerate
static PyObject * __pyx_n_s_error
static PyObject * __pyx_kp_s_failed_to_unpack_passed_connecti
static PyObject * __pyx_n_s_flags
static PyObject * __pyx_n_s_float
static PyObject * __pyx_n_s_floating
static PyObject * __pyx_n_s_format
static PyObject * __pyx_n_s_fortran
static PyObject * __pyx_n_u_fortran
static PyObject * __pyx_n_s_frombuffer
static PyObject * __pyx_kp_s_got_differing_extents_in_dimensi
static PyObject * __pyx_n_s_id
static PyObject * __pyx_n_s_import
static PyObject * __pyx_n_s_int
static PyObject * __pyx_n_s_integer
static PyObject * __pyx_n_b_integertype
static PyObject * __pyx_kp_s_interpreter_stack_is_empty
static PyObject * __pyx_n_b_intvectortype
static PyObject * __pyx_n_s_issubdtype
static PyObject * __pyx_n_s_item
static PyObject * __pyx_n_s_items
static PyObject * __pyx_n_s_itemsize
static PyObject * __pyx_kp_s_itemsize_0_for_cython_array
static PyObject * __pyx_n_s_l
static PyObject * __pyx_n_b_literaltype
static PyObject * __pyx_n_s_main
static PyObject * __pyx_n_b_masktype
static PyObject * __pyx_n_s_memview
static PyObject * __pyx_n_s_metaclass
static PyObject * __pyx_n_s_mode
static PyObject * __pyx_n_s_module
static PyObject * __pyx_n_s_modulepath
static PyObject * __pyx_n_s_name
static PyObject * __pyx_n_s_name_2
static PyObject * __pyx_n_s_ndarray
static PyObject * __pyx_n_s_ndim
static PyObject * __pyx_n_s_numpy
static PyObject * __pyx_n_s_obj
static PyObject * __pyx_kp_s_only_vectors_of_integers_or_floa
static PyObject * __pyx_n_s_pack
static PyObject * __pyx_n_b_parametertype
static PyObject * __pyx_n_u_port
static PyObject * __pyx_n_s_prepare
static PyObject * __pyx_n_s_pynestkernel
static PyObject * __pyx_n_s_pyx_getbuffer
static PyObject * __pyx_n_s_pyx_releasebuffer
static PyObject * __pyx_n_s_pyx_vtable
static PyObject * __pyx_n_s_qualname
static PyObject * __pyx_n_s_range
static PyObject * __pyx_n_s_shape
static PyObject * __pyx_n_s_size
static PyObject * __pyx_n_u_source
static PyObject * __pyx_n_s_start
static PyObject * __pyx_n_s_step
static PyObject * __pyx_n_s_stop
static PyObject * __pyx_kp_s_strided_and_direct
static PyObject * __pyx_kp_s_strided_and_direct_or_indirect
static PyObject * __pyx_kp_s_strided_and_indirect
static PyObject * __pyx_n_b_stringtype
static PyObject * __pyx_n_s_struct
static PyObject * __pyx_n_u_synapse_modelid
static PyObject * __pyx_n_u_target_thread
static PyObject * __pyx_n_s_test
static PyObject * __pyx_kp_s_unable_to_allocate_array_data
static PyObject * __pyx_kp_s_unable_to_allocate_shape_and_str
static PyObject * __pyx_kp_s_unknown_Python_type_0
static PyObject * __pyx_kp_s_unknown_SLI_datum_type_0
static PyObject * __pyx_kp_s_unknown_SLI_type_0
static PyObject * __pyx_n_s_unpack
static PyObject * __pyx_n_s_xrange
static PyObject * __pyx_int_0
static PyObject * __pyx_int_1
static PyObject * __pyx_int_5
static PyObject * __pyx_int_neg_1
static long __pyx_k__27
static double __pyx_k__28
static long __pyx_k__29
static double __pyx_k__30
static long __pyx_k__31
static double __pyx_k__32
static long __pyx_k__33
static double __pyx_k__34
static long __pyx_k__35
static double __pyx_k__36
static long __pyx_k__37
static double __pyx_k__38
static long __pyx_k__39
static double __pyx_k__40
static PyObject * __pyx_tuple__2
static PyObject * __pyx_tuple__3
static PyObject * __pyx_tuple__4
static PyObject * __pyx_tuple__5
static PyObject * __pyx_tuple__6
static PyObject * __pyx_tuple__7
static PyObject * __pyx_tuple__8
static PyObject * __pyx_tuple__9
static PyObject * __pyx_tuple__10
static PyObject * __pyx_tuple__11
static PyObject * __pyx_tuple__12
static PyObject * __pyx_tuple__13
static PyObject * __pyx_tuple__14
static PyObject * __pyx_tuple__15
static PyObject * __pyx_tuple__16
static PyObject * __pyx_tuple__17
static PyObject * __pyx_tuple__18
static PyObject * __pyx_tuple__19
static PyObject * __pyx_tuple__20
static PyObject * __pyx_tuple__21
static PyObject * __pyx_tuple__22
static PyObject * __pyx_tuple__23
static PyObject * __pyx_tuple__24
static PyObject * __pyx_tuple__25
static PyObject * __pyx_tuple__26
static PyObject * __pyx_tuple__41
static PyObject * __pyx_tuple__42
static PyObject * __pyx_tuple__43
static PyObject * __pyx_tuple__44
static PyObject * __pyx_tuple__45
static struct
__pyx_vtabstruct_12pynestkernel_SLIDatum __pyx_vtable_12pynestkernel_SLIDatum
static PyMethodDef __pyx_methods_12pynestkernel_SLIDatum []
static struct PyGetSetDef __pyx_getsets_12pynestkernel_SLIDatum []
static PyTypeObject __pyx_type_12pynestkernel_SLIDatum
static PyMethodDef __pyx_methods_12pynestkernel_SLILiteral []
static struct PyGetSetDef __pyx_getsets_12pynestkernel_SLILiteral []
static PyTypeObject __pyx_type_12pynestkernel_SLILiteral
static PyMethodDef __pyx_methods_12pynestkernel_NESTEngine []
static PyTypeObject __pyx_type_12pynestkernel_NESTEngine
static PyMethodDef __pyx_methods_array []
static struct PyGetSetDef __pyx_getsets_array []
static PySequenceMethods __pyx_tp_as_sequence_array
static PyMappingMethods __pyx_tp_as_mapping_array
static PyBufferProcs __pyx_tp_as_buffer_array
static PyTypeObject __pyx_type___pyx_array
static PyMethodDef __pyx_methods_Enum []
static PyTypeObject __pyx_type___pyx_MemviewEnum
static struct
__pyx_vtabstruct_memoryview __pyx_vtable_memoryview
static PyMethodDef __pyx_methods_memoryview []
static struct PyGetSetDef __pyx_getsets_memoryview []
static PySequenceMethods __pyx_tp_as_sequence_memoryview
static PyMappingMethods __pyx_tp_as_mapping_memoryview
static PyBufferProcs __pyx_tp_as_buffer_memoryview
static PyTypeObject __pyx_type___pyx_memoryview
static struct
__pyx_vtabstruct__memoryviewslice __pyx_vtable__memoryviewslice
static PyMethodDef __pyx_methods__memoryviewslice []
static struct PyGetSetDef __pyx_getsets__memoryviewslice []
static PyTypeObject __pyx_type___pyx_memoryviewslice
static PyMethodDef __pyx_methods []
static struct PyModuleDef __pyx_moduledef
static __Pyx_StringTabEntry __pyx_string_tab []
Typedef Documentation
typedef volatile __pyx_atomic_int_type __pyx_atomic_int
typedef struct __Pyx_StructField_ __Pyx_StructField
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_double_1d_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_float_1d_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_int_1d_t
typedef __Pyx_memviewslice __pyx_t_12pynestkernel_buffer_long_1d_t
typedef DoubleVectorDatum* __pyx_t_12pynestkernel_sli_vector_double_ptr_t
typedef IntVectorDatum* __pyx_t_12pynestkernel_sli_vector_int_ptr_t
typedef struct arraydescr arraydescr
typedef struct arrayobject arrayobject
typedef int(* getbufferproc)(PyObject *, Py_buffer *, int)
typedef long Py_hash_t
typedef int Py_ssize_t
typedef void(* releasebufferproc)(PyObject *, Py_buffer *)
Function Documentation
static CYTHON_INLINE int __pyx_add_acquisition_count_locked (__pyx_atomic_int * acquisition_count, PyThread_type_lock lock) static
Referenced by __Pyx_GetModuleGlobalName().
static void __Pyx_AddTraceback (const char * funcname, int c_line, int py_line, const char * filename) static
Referenced by __pyx_array___cinit__(), __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array_10__setitem__(), __pyx_array_MemoryView_5array_6__getattr__(), __pyx_array_MemoryView_5array_8__getitem__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_array_new(), __pyx_convert_string_from_py_(), __pyx_convert_string_to_py_(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_f_7cpython_5array_clone(), __pyx_f_7cpython_5array_copy(), __pyx_f_7cpython_5array_extend(), __pyx_f_7cpython_5array_extend_buffer(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_GetModuleGlobalName(), __pyx_memoryview___cinit__(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_copy_object(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_item_pointer(), __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__(), __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__(), __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__(), __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__(), __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_MemoryView_10memoryview_14__str__(), __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), __pyx_memoryview_MemoryView_10memoryview_18is_f_contig(), __pyx_memoryview_MemoryView_10memoryview_20copy(), __pyx_memoryview_MemoryView_10memoryview_22copy_fortran(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_memoryview_new(), __pyx_memoryview_setitem_indexed(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_slice_memviewslice(), __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__(), __pyx_memoryviewslice_assign_item_from_object(), __pyx_memoryviewslice_convert_item_to_object(), __pyx_memslice_transpose(), __pyx_memview_slice(), __pyx_MemviewEnum___init__(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pf_12pynestkernel_10SLILiteral_2__hash__(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), __pyx_pf_12pynestkernel_8SLIDatum_4__repr__(), __pyx_pf_7cpython_5array_5array___getbuffer__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), __pyx_pw_12pynestkernel_10SLILiteral_1__init__(), __pyx_pybuffer_index(), _unellipsify(), assert_direct_dimensions(), get_memview_MemoryView_5array_7memview___get__(), and PyInit_pynestkernel().
static void * __pyx_align_pointer (void * __pyx_v_memory, size_t __pyx_v_alignment) static
Referenced by __pyx_memoryview_MemoryView_10memoryview___cinit__().
static CYTHON_INLINE int __Pyx_ArgTypeTest (PyObject * obj, PyTypeObject * type, int none_allowed, const char * name, int exact) static
Referenced by __pyx_array___cinit__(), and __Pyx_GetModuleGlobalName().
static int __pyx_array___cinit__ (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_AddTraceback(), __Pyx_ArgTypeTest(), __pyx_array_MemoryView_5array___cinit__(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_n_s_allocate_buffer, __pyx_n_s_format, __pyx_n_s_itemsize, __pyx_n_s_mode, __pyx_n_s_shape, __Pyx_ParseOptionalKeywords(), __Pyx_PyIndex_AsSsize_t(), __Pyx_PyObject_IsTrue(), and __Pyx_RaiseArgtupleInvalid().
Referenced by __pyx_tp_new_array().
static void __pyx_array___dealloc__ (PyObject * __pyx_v_self) static
References __pyx_array_MemoryView_5array_4__dealloc__().
Referenced by __pyx_tp_dealloc_array().
static PyObject * __pyx_array___getattr__ (PyObject * __pyx_v_self, PyObject * __pyx_v_attr) static
References __pyx_array_MemoryView_5array_6__getattr__().
Referenced by __pyx_tp_getattro_array().
static PyObject * __pyx_array___getitem__ (PyObject * __pyx_v_self, PyObject * __pyx_v_item) static
References __pyx_array_MemoryView_5array_8__getitem__().
static int __pyx_array___setitem__ (PyObject * __pyx_v_self, PyObject * __pyx_v_item, PyObject * __pyx_v_value) static
References __pyx_array_MemoryView_5array_10__setitem__().
Referenced by __pyx_mp_ass_subscript_array().
static CYTHON_UNUSED int __pyx_array_getbuffer (PyObject * __pyx_v_self, Py_buffer * __pyx_v_info, int __pyx_v_flags) static
References __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__().
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static int __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__ (struct __pyx_array_obj * __pyx_v_self, Py_buffer * __pyx_v_info, int __pyx_v_flags) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyUnicode_Equals(), __Pyx_Raise(), __pyx_array_obj::_shape, __pyx_array_obj::_strides, Py_buffer::buf, __pyx_array_obj::data, Py_buffer::format, __pyx_array_obj::format, Py_buffer::itemsize, __pyx_array_obj::itemsize, Py_buffer::len, __pyx_array_obj::len, __pyx_array_obj::mode, Py_buffer::ndim, __pyx_array_obj::ndim, Py_buffer::obj, Py_buffer::readonly, Py_buffer::shape, Py_buffer::strides, and Py_buffer::suboffsets.
Referenced by __pyx_array_getbuffer().
static int __pyx_array_MemoryView_5array_10__setitem__ (struct __pyx_array_obj * __pyx_v_self, PyObject * __pyx_v_item, PyObject * __pyx_v_value) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, and __Pyx_PyObject_GetAttrStr().
Referenced by __pyx_array___setitem__().
static void __pyx_array_MemoryView_5array_4__dealloc__ (struct __pyx_array_obj * __pyx_v_self) static
References __pyx_memoryview_refcount_objects_in_slice(), __pyx_array_obj::_shape, __pyx_array_obj::_strides, __pyx_array_obj::callback_free_data, __pyx_array_obj::data, __pyx_array_obj::dtype_is_object, __pyx_array_obj::free_data, and __pyx_array_obj::ndim.
Referenced by __pyx_array___dealloc__().
static PyObject * __pyx_array_MemoryView_5array_6__getattr__ (struct __pyx_array_obj * __pyx_v_self, PyObject * __pyx_v_attr) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __Pyx_GetAttr(), __pyx_lineno, and __Pyx_PyObject_GetAttrStr().
Referenced by __pyx_array___getattr__().
static PyObject * __pyx_array_MemoryView_5array_8__getitem__ (struct __pyx_array_obj * __pyx_v_self, PyObject * __pyx_v_item) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, and __Pyx_PyObject_GetAttrStr().
Referenced by __pyx_array___getitem__().
static int __pyx_array_MemoryView_5array___cinit__ (struct __pyx_array_obj * __pyx_v_self, PyObject * __pyx_v_shape, Py_ssize_t __pyx_v_itemsize, PyObject * __pyx_v_format, PyObject * __pyx_v_mode, int __pyx_v_allocate_buffer) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_div_Py_ssize_t(), __pyx_f, __pyx_filename, __pyx_fill_contig_strides_array(), __pyx_lineno, __pyx_n_u_c, __pyx_n_u_fortran, __Pyx_PyIndex_AsSsize_t(), __Pyx_PyInt_From_int(), __Pyx_PyObject_AsString(), __Pyx_PyObject_Call(), __Pyx_PyObject_IsTrue(), __Pyx_Raise(), __pyx_array_obj::_format, __pyx_array_obj::_shape, __pyx_array_obj::_strides, __pyx_array_obj::data, __pyx_array_obj::dtype_is_object, __pyx_array_obj::format, __pyx_array_obj::free_data, __pyx_array_obj::itemsize, __pyx_array_obj::len, __pyx_array_obj::mode, and __pyx_array_obj::ndim.
Referenced by __pyx_array___cinit__().
static struct __pyx_array_obj * __pyx_array_new (PyObject * __pyx_v_shape, Py_ssize_t __pyx_v_itemsize, char * __pyx_v_format, char * __pyx_v_mode, char * __pyx_v_buf) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_decode_c_string(), __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), and __pyx_array_obj::data.
Referenced by __Pyx_GetModuleGlobalName().
static int __pyx_bisect_code_objects (__Pyx_CodeObjectCacheEntry * entries, int count, int code_line) static
Referenced by __Pyx_GetModuleGlobalName().
static PyObject* __Pyx_CalculateMetaclass (PyTypeObject * metaclass, PyObject * bases) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
template<typename T > void __Pyx_call_destructor (T * x)
static CYTHON_INLINE PyObject* __pyx_capsule_create (void * p, const char * sig) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static int __Pyx_check_binary_version (void) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static CYTHON_INLINE int __Pyx_CheckKeywordStrings (PyObject * kwdict, const char * function_name, int kw_allowed) static
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_1__cinit__(), and __pyx_pw_12pynestkernel_8SLIDatum_1__cinit__().
static std::string __pyx_convert_string_from_py_ (PyObject * __pyx_v_o) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, and __Pyx_PyObject_AsStringAndSize().
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), and PyInit_pynestkernel().
static PyObject * __pyx_convert_string_to_py_ (const std::string & __pyx_v_s) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, and __pyx_lineno.
static void __Pyx_CppExn2PyErr () static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), and __pyx_pf_12pynestkernel_10NESTEngine_8push().
static CYTHON_INLINE PyObject* __Pyx_decode_c_bytes (const char * cstring, Py_ssize_t length, Py_ssize_t start, Py_ssize_t stop, const char * encoding, const char * errors, PyObject *(*)(const char *s, Py_ssize_t size, const char *errors) decode_func) static
Referenced by __Pyx_decode_cpp_string(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject* __Pyx_decode_c_string (const char * cstring, Py_ssize_t start, Py_ssize_t stop, const char * encoding, const char * errors, PyObject *(*)(const char *s, Py_ssize_t size, const char *errors) decode_func) static
Referenced by __pyx_array_new(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_err(), and __pyx_memoryview_err_dim().
static CYTHON_INLINE PyObject* __Pyx_decode_cpp_string (std::string cppstring, Py_ssize_t start, Py_ssize_t stop, const char * encoding, const char * errors, PyObject *(*)(const char *s, Py_ssize_t size, const char *errors) decode_func) static
References __Pyx_decode_c_bytes(), nest::names::start, and nest::names::stop.
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_datum_to_object(), and __pyx_f_12pynestkernel_sli_dict_to_object().
static CYTHON_INLINE long __Pyx_div_long (long , long) static
Referenced by __Pyx_GetModuleGlobalName(), and __pyx_memslice_transpose().
static CYTHON_INLINE Py_ssize_t __Pyx_div_Py_ssize_t (Py_ssize_t , Py_ssize_t) static
Referenced by __pyx_array_MemoryView_5array___cinit__(), __Pyx_GetModuleGlobalName(), and __pyx_pybuffer_index().
static CYTHON_INLINE void __Pyx_ErrFetch (PyObject ** type, PyObject ** value, PyObject ** tb) static
Referenced by __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), and __Pyx_WriteUnraisable().
static CYTHON_INLINE void __Pyx_ErrRestore (PyObject * type, PyObject * value, PyObject * tb) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), and __Pyx_WriteUnraisable().
static void __Pyx_ExceptionReset (PyObject * type, PyObject * value, PyObject * tb) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_is_slice(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), and PyInit_pynestkernel().
static CYTHON_INLINE void __Pyx_ExceptionSave (PyObject ** type, PyObject ** value, PyObject ** tb) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_is_slice(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), and PyInit_pynestkernel().
static CYTHON_INLINE void __Pyx_ExceptionSwap (PyObject ** type, PyObject ** value, PyObject ** tb) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_setitem_slice_assign_scalar(), and __pyx_pf_12pynestkernel_10NESTEngine_4init().
static PyObject* __pyx_f_12pynestkernel_8SLIDatum__set_datum (struct __pyx_obj_12pynestkernel_SLIDatum * __pyx_v_self, Datum * __pyx_v_dat, PyObject * __pyx_v_dtype) static
References __pyx_obj_12pynestkernel_SLIDatum::dtype, and __pyx_obj_12pynestkernel_SLIDatum::thisptr.
Referenced by PyInit_pynestkernel().
static CYTHON_INLINE Datum * __pyx_f_12pynestkernel_python_object_to_datum (PyObject * __pyx_v_obj) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_convert_string_from_py_(), __Pyx_CppExn2PyErr(), __Pyx_decode_cpp_string(), __pyx_empty_tuple, __Pyx_ExceptionReset(), __Pyx_ExceptionSave(), __pyx_f, __pyx_filename, __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_GetModuleGlobalName(), __Pyx_IterFinish(), __Pyx_IternextUnpackEndCheck(), __pyx_lineno, __Pyx_PyInt_As_long(), __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_PyObject_IsTrue(), __Pyx_PyObject_to_MemoryviewSlice_ds_double(), __Pyx_PyObject_to_MemoryviewSlice_ds_float(), __Pyx_PyObject_to_MemoryviewSlice_ds_int(), __Pyx_PyObject_to_MemoryviewSlice_ds_long(), __Pyx_PyUnicode_Equals(), __Pyx_Raise(), __Pyx_RaiseNeedMoreValuesError(), __Pyx_RaiseTooManyValuesError(), __pyx_v_12pynestkernel_HAVE_NUMPY, CYTHON_unpackConnectionGeneratorDatum(), __Pyx_memviewslice::memview, TokenArray::push_back(), and TokenArray::reserve().
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_8push().
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_array_to_object (ArrayDatum * __pyx_v_dat) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_filename, __pyx_lineno, __Pyx_PyInt_FromSize_t(), __Pyx_PyObject_Call(), TokenArray::begin(), and TokenArray::size().
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_connection_to_object (ConnectionDatum * __pyx_v_dat) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_f_7cpython_5array_clone(), __pyx_filename, __pyx_lineno, __Pyx_TypeTest(), __pyx_v_12pynestkernel_ARRAY_LONG, arrayobject::as_longs, and arrayobject::data.
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_datum_to_object (Datum * __pyx_v_dat) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __Pyx_decode_cpp_string(), __pyx_empty_tuple, __pyx_f, __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_filename, __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __Pyx_GetModuleGlobalName(), __pyx_lineno, __Pyx_PyInt_From_long(), __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_Raise(), __pyx_v_12pynestkernel_SLI_TYPE_ARRAY, __pyx_v_12pynestkernel_SLI_TYPE_BOOL, __pyx_v_12pynestkernel_SLI_TYPE_CONNECTION, __pyx_v_12pynestkernel_SLI_TYPE_DICTIONARY, __pyx_v_12pynestkernel_SLI_TYPE_DOUBLE, __pyx_v_12pynestkernel_SLI_TYPE_INTEGER, __pyx_v_12pynestkernel_SLI_TYPE_LITERAL, __pyx_v_12pynestkernel_SLI_TYPE_MASK, __pyx_v_12pynestkernel_SLI_TYPE_PARAMETER, __pyx_v_12pynestkernel_SLI_TYPE_STRING, __pyx_v_12pynestkernel_SLI_TYPE_VECTOR_DOUBLE, __pyx_v_12pynestkernel_SLI_TYPE_VECTOR_INT, Datum::gettypename(), and Name::toString().
Referenced by __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), and __pyx_pf_12pynestkernel_10NESTEngine_10pop().
static CYTHON_INLINE PyObject * __pyx_f_12pynestkernel_sli_dict_to_object (DictionaryDatum * __pyx_v_dat) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __Pyx_decode_cpp_string(), __pyx_f, __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_filename, and __pyx_lineno.
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
static CYTHON_INLINE arrayobject * __pyx_f_7cpython_5array_clone (arrayobject * __pyx_v_template, Py_ssize_t __pyx_v_length, int __pyx_v_zero) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, arrayobject::as_chars, arrayobject::data, arraydescr::itemsize, newarrayobject(), and arrayobject::ob_descr.
Referenced by __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), and __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object().
static CYTHON_INLINE arrayobject* __pyx_f_7cpython_5array_copy (arrayobject * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, arrayobject::as_chars, arrayobject::data, arraydescr::itemsize, newarrayobject(), and arrayobject::ob_descr.
static CYTHON_INLINE int __pyx_f_7cpython_5array_extend (arrayobject * __pyx_v_self, arrayobject * __pyx_v_other) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_f_7cpython_5array_extend_buffer(), __pyx_filename, __pyx_lineno, arrayobject::as_chars, arrayobject::data, arrayobject::ob_descr, and arraydescr::typecode.
static CYTHON_INLINE int __pyx_f_7cpython_5array_extend_buffer (arrayobject * __pyx_v_self, char * __pyx_v_stuff, Py_ssize_t __pyx_v_n) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, arrayobject::as_chars, arrayobject::data, arraydescr::itemsize, arrayobject::ob_descr, and resize_smart().
Referenced by __pyx_f_7cpython_5array_extend().
static CYTHON_INLINE void __pyx_f_7cpython_5array_zero (arrayobject * __pyx_v_self) static
References arrayobject::as_chars, arrayobject::data, arraydescr::itemsize, and arrayobject::ob_descr.
static Py_ssize_t __pyx_fill_contig_strides_array (Py_ssize_t * __pyx_v_shape, Py_ssize_t * __pyx_v_strides, Py_ssize_t __pyx_v_stride, int __pyx_v_ndim, char __pyx_v_order) static
Referenced by __pyx_array_MemoryView_5array___cinit__(), and __pyx_memoryview_copy_data_to_temp().
static PyCodeObject* __pyx_find_code_object (int code_line) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE Datum * __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum (PyObject * __pyx_v_buff, struct __pyx_fuse_0_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyInt_As_long(), and __Pyx_PyInt_FromSize_t().
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
static CYTHON_INLINE PyObject * __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object (__pyx_t_12pynestkernel_sli_vector_int_ptr_t __pyx_v_dat, struct __pyx_fuse_0_0__pyx_opt_args_12pynestkernel_sli_vector_to_object * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_f_7cpython_5array_clone(), __pyx_filename, __Pyx_GetModuleGlobalName(), __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_RaiseUnboundLocalError(), __Pyx_TypeTest(), __pyx_v_12pynestkernel_ARRAY_LONG, arrayobject::as_longs, and arrayobject::data.
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
static CYTHON_INLINE Datum * __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum (PyObject * __pyx_v_buff, struct __pyx_fuse_0_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, and __Pyx_PyInt_FromSize_t().
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
static CYTHON_INLINE Datum * __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_int_1d_t __pyx_v_buff, struct __pyx_fuse_1_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_fromslice(), __pyx_memview_get_int(), __pyx_memview_set_int(), __Pyx_memviewslice::data, and __Pyx_memviewslice::strides.
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
static CYTHON_INLINE PyObject * __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object (__pyx_t_12pynestkernel_sli_vector_double_ptr_t __pyx_v_dat, struct __pyx_fuse_1_1__pyx_opt_args_12pynestkernel_sli_vector_to_object * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_f_7cpython_5array_clone(), __pyx_filename, __Pyx_GetModuleGlobalName(), __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_RaiseUnboundLocalError(), __Pyx_TypeTest(), __pyx_v_12pynestkernel_ARRAY_DOUBLE, arrayobject::as_doubles, and arrayobject::data.
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
static CYTHON_INLINE Datum * __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_long_1d_t __pyx_v_buff, struct __pyx_fuse_2_0__pyx_opt_args_12pynestkernel_python_buffer_to_datum * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_fromslice(), __pyx_memview_get_long(), __pyx_memview_set_long(), __Pyx_memviewslice::data, and __Pyx_memviewslice::strides.
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
static CYTHON_INLINE Datum * __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_float_1d_t __pyx_v_buff, struct __pyx_fuse_3_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_fromslice(), __pyx_memview_get_float(), __pyx_memview_set_float(), __Pyx_memviewslice::data, and __Pyx_memviewslice::strides.
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
static CYTHON_INLINE Datum * __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum (__pyx_t_12pynestkernel_buffer_double_1d_t __pyx_v_buff, struct __pyx_fuse_4_1__pyx_opt_args_12pynestkernel_python_buffer_to_datum * __pyx_optional_args) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_fromslice(), __pyx_memview_get_double(), __pyx_memview_set_double(), __Pyx_memviewslice::data, and __Pyx_memviewslice::strides.
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
static char __pyx_get_best_slice_order (__Pyx_memviewslice * __pyx_v_mslice, int __pyx_v_ndim) static
References abs_py_ssize_t(), __Pyx_memviewslice::shape, and __Pyx_memviewslice::strides.
Referenced by __pyx_memoryview_copy_contents().
static CYTHON_INLINE PyObject* __Pyx_GetAttr (PyObject * , PyObject *) static
Referenced by __pyx_array_MemoryView_5array_6__getattr__(), and __Pyx_GetModuleGlobalName().
static int __Pyx_GetBuffer (PyObject * obj, Py_buffer * view, int flags) static
Referenced by __Pyx_GetModuleGlobalName(), and __pyx_memoryview_MemoryView_10memoryview___cinit__().
static CYTHON_INLINE int __Pyx_GetBufferAndValidate (Py_buffer * buf, PyObject * obj, __Pyx_TypeInfo * dtype, int flags, int nd, int cast, __Pyx_BufFmt_StackElem * stack) static
Referenced by __Pyx_GetModuleGlobalName().
static PyObject * __Pyx_GetBuiltinName (PyObject * name) static
References __pyx_b, and __Pyx_PyObject_GetAttrStr().
Referenced by __Pyx_GetModuleGlobalName(), and __Pyx_InitCachedBuiltins().
static int __Pyx_GetException (PyObject ** type, PyObject ** value, PyObject ** tb) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_is_slice(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), and __pyx_pf_12pynestkernel_10NESTEngine_4init().
static CYTHON_INLINE PyObject* __Pyx_GetItemInt_Fast (PyObject * o, Py_ssize_t i, int is_list, int wraparound, int boundscheck) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject* __Pyx_GetItemInt_Generic (PyObject * o, PyObject * j) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject* __Pyx_GetItemInt_List_Fast (PyObject * o, Py_ssize_t i, int wraparound, int boundscheck) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject* __Pyx_GetItemInt_Tuple_Fast (PyObject * o, Py_ssize_t i, int wraparound, int boundscheck) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject * __Pyx_GetModuleGlobalName (PyObject * name) static
References __pyx_add_acquisition_count_locked(), __Pyx_AddTraceback(), __Pyx_ArgTypeTest(), __pyx_array_getbuffer(), __pyx_array_new(), __pyx_b, __pyx_bisect_code_objects(), __Pyx_CalculateMetaclass(), __pyx_capsule_create(), __pyx_cfilenm, __Pyx_check_binary_version(), __pyx_d, __Pyx_decode_c_bytes(), __Pyx_decode_c_string(), __Pyx_div_long(), __Pyx_div_Py_ssize_t(), __pyx_empty_bytes, __pyx_empty_tuple, __Pyx_ErrRestore(), __Pyx_ExceptionReset(), __Pyx_ExceptionSave(), __Pyx_ExceptionSwap(), __pyx_find_code_object(), __Pyx_GetAttr(), __Pyx_GetBuffer(), __Pyx_GetBufferAndValidate(), __Pyx_GetBuiltinName(), __Pyx_GetException(), __Pyx_GetItemInt_Fast(), __Pyx_GetItemInt_Generic(), __Pyx_GetItemInt_List_Fast(), __Pyx_GetItemInt_Tuple_Fast(), __Pyx_Import(), __Pyx_ImportModule(), __Pyx_ImportType(), __Pyx_INC_MEMVIEW(), __Pyx_init_memviewslice(), __Pyx_InitStrings(), __pyx_insert_code_object(), __Pyx_IterFinish(), __Pyx_IternextUnpackEndCheck(), __pyx_m, __pyx_memoryview_check(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_new_contig(), __pyx_memoryview_getbuffer(), __pyx_memoryview_new(), __pyx_memview_get_double(), __pyx_memview_get_float(), __pyx_memview_get_int(), __pyx_memview_get_long(), __pyx_memview_set_double(), __pyx_memview_set_float(), __pyx_memview_set_int(), __pyx_memview_set_long(), __pyx_memviewslice_is_contig(), __Pyx_minusones, __pyx_pw_7cpython_5array_5array_1__getbuffer__(), __pyx_pw_7cpython_5array_5array_3__releasebuffer__(), __Pyx_Py3ClassCreate(), __Pyx_Py3MetaclassPrepare(), __Pyx_PyBytes_Equals(), __Pyx_PyIndex_AsSsize_t(), __Pyx_PyInt_As_char(), __Pyx_PyInt_As_int(), __Pyx_PyInt_As_long(), __Pyx_PyInt_As_size_t(), __Pyx_PyInt_From_int(), __Pyx_PyInt_From_long(), __Pyx_PyInt_FromSize_t(), __Pyx_PyNumber_Int(), __Pyx_PyObject_AsString(), __Pyx_PyObject_AsStringAndSize(), __Pyx_PyObject_GetAttrStr(), __Pyx_PyObject_IsTrue(), __Pyx_PyObject_to_MemoryviewSlice_ds_double(), __Pyx_PyObject_to_MemoryviewSlice_ds_float(), __Pyx_PyObject_to_MemoryviewSlice_ds_int(), __Pyx_PyObject_to_MemoryviewSlice_ds_long(), __Pyx_PyUnicode_Equals(), __Pyx_PyUnicode_FromString(), __Pyx_Raise(), __Pyx_RaiseNeedMoreValuesError(), __Pyx_RaiseNoneNotIterableError(), __Pyx_RaiseTooManyValuesError(), __Pyx_RaiseUnboundLocalError(), __Pyx_ReleaseBuffer(), __Pyx_SafeReleaseBuffer(), __Pyx_SetItemInt_Fast(), __Pyx_SetItemInt_Generic(), __Pyx_SetVtable(), __pyx_slices_overlap(), __pyx_sub_acquisition_count_locked(), __Pyx_sys_getdefaultencoding_not_ascii, __pyx_typeinfo_cmp(), __Pyx_TypeTest(), __Pyx_ValidateAndInit_memviewslice(), __Pyx_XDEC_MEMVIEW(), __Pyx_zeros, nest::names::a, __Pyx_TypeInfo::arraysize, nest::names::b, Py_buffer::buf, nest::names::c, __Pyx_CodeObjectCacheEntry::code_line, __Pyx_CodeObjectCacheEntry::code_object, __Pyx_CodeObjectCache::count, __Pyx_memviewslice::data, __Pyx_BufFmt_Context::enc_count, __Pyx_BufFmt_Context::enc_packmode, __Pyx_BufFmt_Context::enc_type, __Pyx_StringTabEntry::encoding, __Pyx_CodeObjectCache::entries, nest::names::extent, __Pyx_BufFmt_StackElem::field, __Pyx_TypeInfo::fields, nest::names::filename, __Pyx_TypeInfo::flags, __Pyx_BufFmt_Context::fmt_offset, Py_buffer::format, __Pyx_BufFmt_Context::head, __Pyx_StringTabEntry::intern, __Pyx_BufFmt_Context::is_complex, __Pyx_StringTabEntry::is_str, __Pyx_StringTabEntry::is_unicode, __Pyx_TypeInfo::is_unsigned, __Pyx_BufFmt_Context::is_valid_array, Py_buffer::itemsize, __Pyx_CodeObjectCache::max_count, __Pyx_memviewslice::memview, nest::names::n, __Pyx_StringTabEntry::n, __Pyx_TypeInfo::name, __Pyx_StructField_::name, Py_buffer::ndim, __Pyx_TypeInfo::ndim, __Pyx_BufFmt_Context::new_count, __Pyx_BufFmt_Context::new_packmode, nest::names::ns, Py_buffer::obj, nest::names::offset, __Pyx_StructField_::offset, nest::names::order, nest::names::p, __Pyx_StringTabEntry::p, nest::names::parent, __Pyx_BufFmt_StackElem::parent_offset, __Pyx_BufFmt_Context::root, __Pyx_StringTabEntry::s, Py_buffer::shape, __Pyx_memviewslice::shape, __Pyx_TypeInfo::size, nest::names::start, Py_buffer::strides, __Pyx_memviewslice::strides, __Pyx_BufFmt_Context::struct_alignment, Py_buffer::suboffsets, __Pyx_memviewslice::suboffsets, __Pyx_StructField_::type, __Pyx_TypeInfo::typegroup, __pyx_memoryview_obj::typeinfo, __pyx_memoryview_obj::view, and nest::names::x.
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), and __pyx_pf_12pynestkernel_10NESTEngine_8push().
static PyObject* __pyx_getprop_12pynestkernel_10SLILiteral_name (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_pw_12pynestkernel_10SLILiteral_4name_1__get__().
static PyObject* __pyx_getprop_12pynestkernel_8SLIDatum_dtype (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_pw_12pynestkernel_8SLIDatum_5dtype_1__get__().
static PyObject* __pyx_getprop___pyx_array_memview (PyObject * o, CYTHON_UNUSED void * x) static
References get_memview().
static PyObject* __pyx_getprop___pyx_memoryview_base (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview__get__base().
static PyObject* __pyx_getprop___pyx_memoryview_itemsize (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_itemsize().
static PyObject* __pyx_getprop___pyx_memoryview_nbytes (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_nbytes().
static PyObject* __pyx_getprop___pyx_memoryview_ndim (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_ndim().
static PyObject* __pyx_getprop___pyx_memoryview_shape (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_shape().
static PyObject* __pyx_getprop___pyx_memoryview_size (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_size().
static PyObject* __pyx_getprop___pyx_memoryview_strides (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_strides().
static PyObject* __pyx_getprop___pyx_memoryview_suboffsets (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_get_suboffsets().
static PyObject* __pyx_getprop___pyx_memoryview_T (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryview_transpose().
static PyObject* __pyx_getprop___pyx_memoryviewslice_base (PyObject * o, CYTHON_UNUSED void * x) static
References __pyx_memoryviewslice__get__base().
static PyObject* __Pyx_Import (PyObject * name, PyObject * from_list, int level) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), and PyInit_pynestkernel().
static PyObject* __Pyx_ImportModule (const char * name) static
Referenced by __Pyx_GetModuleGlobalName().
static PyTypeObject* __Pyx_ImportType (const char * module_name, const char * class_name, size_t size, int strict) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static CYTHON_INLINE void __Pyx_INC_MEMVIEW (__Pyx_memviewslice * , int , int) static
Referenced by __Pyx_GetModuleGlobalName().
static int __Pyx_init_memviewslice (struct __pyx_memoryview_obj * memview, int ndim, __Pyx_memviewslice * memviewslice, int memview_is_new_reference) static
Referenced by __Pyx_GetModuleGlobalName().
static int __Pyx_init_sys_getdefaultencoding_params (void) static
References __Pyx_sys_getdefaultencoding_not_ascii, and nest::names::c.
Referenced by PyInit_pynestkernel().
static int __Pyx_InitCachedBuiltins (void) static
References __pyx_clineno, __pyx_f, __pyx_filename, __Pyx_GetBuiltinName(), and __pyx_lineno.
Referenced by PyInit_pynestkernel().
static int __Pyx_InitCachedConstants (void) static
References __pyx_clineno, __pyx_f, __pyx_filename, and __pyx_lineno.
Referenced by PyInit_pynestkernel().
static int __Pyx_InitGlobals (void) static
References __pyx_clineno, __pyx_f, __pyx_filename, __Pyx_InitStrings(), and __pyx_lineno.
Referenced by PyInit_pynestkernel().
static int __Pyx_InitStrings (__Pyx_StringTabEntry * t) static
Referenced by __Pyx_GetModuleGlobalName(), and __Pyx_InitGlobals().
static void __pyx_insert_code_object (int code_line, PyCodeObject * code_object) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_IterFinish (void) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static int __Pyx_IternextUnpackEndCheck (PyObject * retval, Py_ssize_t expected) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_ListComp_Append (PyObject * list, PyObject * x) static
Referenced by __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), and __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__().
static int __pyx_memoryview___cinit__ (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_n_s_dtype_is_object, __pyx_n_s_flags, __pyx_n_s_obj, __Pyx_ParseOptionalKeywords(), __Pyx_PyInt_As_int(), __Pyx_PyObject_IsTrue(), and __Pyx_RaiseArgtupleInvalid().
Referenced by __pyx_tp_new_memoryview().
static void __pyx_memoryview___dealloc__ (PyObject * __pyx_v_self) static
References __pyx_memoryview_MemoryView_10memoryview_2__dealloc__().
Referenced by __pyx_tp_dealloc_memoryview().
static PyObject * __pyx_memoryview___getitem__ (PyObject * __pyx_v_self, PyObject * __pyx_v_index) static
References __pyx_memoryview_MemoryView_10memoryview_4__getitem__().
static Py_ssize_t __pyx_memoryview___len__ (PyObject * __pyx_v_self) static
References __pyx_memoryview_MemoryView_10memoryview_10__len__().
static PyObject * __pyx_memoryview___repr__ (PyObject * __pyx_v_self) static
References __pyx_memoryview_MemoryView_10memoryview_12__repr__().
static int __pyx_memoryview___setitem__ (PyObject * __pyx_v_self, PyObject * __pyx_v_index, PyObject * __pyx_v_value) static
References __pyx_memoryview_MemoryView_10memoryview_6__setitem__().
Referenced by __pyx_mp_ass_subscript_memoryview().
static PyObject * __pyx_memoryview___str__ (PyObject * __pyx_v_self) static
References __pyx_memoryview_MemoryView_10memoryview_14__str__().
static PyObject * __pyx_memoryview__get__base (PyObject * __pyx_v_self) static
References __pyx_memoryview__get__base_MemoryView_10memoryview_4base___get__().
Referenced by __pyx_getprop___pyx_memoryview_base().
static PyObject * __pyx_memoryview__get__base_MemoryView_10memoryview_4base___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __pyx_memoryview_obj::obj.
Referenced by __pyx_memoryview__get__base().
static void __pyx_memoryview__slice_assign_scalar (char * __pyx_v_data, Py_ssize_t * __pyx_v_shape, Py_ssize_t * __pyx_v_strides, int __pyx_v_ndim, size_t __pyx_v_itemsize, void * __pyx_v_item) static
Referenced by __pyx_memoryview_slice_assign_scalar().
static PyObject* __pyx_memoryview_assign_item_from_object (struct __pyx_memoryview_obj * __pyx_v_self, char * __pyx_v_itemp, PyObject * __pyx_v_value) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __Pyx_Import(), __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), Py_buffer::format, and __pyx_memoryview_obj::view.
Referenced by PyInit_pynestkernel().
static void __pyx_memoryview_broadcast_leading (__Pyx_memviewslice * __pyx_v_slice, int __pyx_v_ndim, int __pyx_v_ndim_other) static
References __Pyx_memviewslice::shape, __Pyx_memviewslice::strides, and __Pyx_memviewslice::suboffsets.
Referenced by __pyx_memoryview_copy_contents().
static CYTHON_INLINE int __pyx_memoryview_check (PyObject * __pyx_v_o) static
Referenced by __Pyx_GetModuleGlobalName().
static PyObject* __pyx_memoryview_convert_item_to_object (struct __pyx_memoryview_obj * __pyx_v_self, char * __pyx_v_itemp) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_ExceptionReset(), __Pyx_ExceptionSave(), __pyx_f, __pyx_filename, __Pyx_GetException(), __Pyx_Import(), __pyx_lineno, __Pyx_PyInt_From_long(), __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_Raise(), Py_buffer::format, Py_buffer::itemsize, and __pyx_memoryview_obj::view.
Referenced by PyInit_pynestkernel().
static PyObject * __pyx_memoryview_copy (PyObject * __pyx_v_self, CYTHON_UNUSED PyObject * unused) static
References __pyx_memoryview_MemoryView_10memoryview_20copy().
static int __pyx_memoryview_copy_contents (__Pyx_memviewslice __pyx_v_src, __Pyx_memviewslice __pyx_v_dst, int __pyx_v_src_ndim, int __pyx_v_dst_ndim, int __pyx_v_dtype_is_object) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_get_best_slice_order(), __pyx_lineno, __pyx_memoryview_broadcast_leading(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_refcount_copying(), __pyx_memoryview_slice_get_size(), __pyx_memslice_transpose(), __pyx_memviewslice_is_contig(), __pyx_slices_overlap(), copy_strided_to_strided(), __Pyx_memviewslice::data, Py_buffer::itemsize, __Pyx_memviewslice::memview, __Pyx_memviewslice::shape, __Pyx_memviewslice::strides, __Pyx_memviewslice::suboffsets, and __pyx_memoryview_obj::view.
Referenced by __Pyx_GetModuleGlobalName(), and __pyx_memoryview_setitem_slice_assignment().
static void * __pyx_memoryview_copy_data_to_temp (__Pyx_memviewslice * __pyx_v_src, __Pyx_memviewslice * __pyx_v_tmpslice, char __pyx_v_order, int __pyx_v_ndim) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_fill_contig_strides_array(), __pyx_lineno, __pyx_memoryview_err(), __pyx_memoryview_slice_get_size(), __pyx_memviewslice_is_contig(), copy_strided_to_strided(), __Pyx_memviewslice::data, Py_buffer::itemsize, __Pyx_memviewslice::memview, __Pyx_memviewslice::shape, __Pyx_memviewslice::strides, __Pyx_memviewslice::suboffsets, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy_contents().
static PyObject * __pyx_memoryview_copy_fortran (PyObject * __pyx_v_self, CYTHON_UNUSED PyObject * unused) static
References __pyx_memoryview_MemoryView_10memoryview_22copy_fortran().
static __Pyx_memviewslice __pyx_memoryview_copy_new_contig (const __Pyx_memviewslice * from_mvs, const char * mode, int ndim, size_t sizeof_dtype, int contig_flag, int dtype_is_object) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_MemoryView_10memoryview_20copy(), and __pyx_memoryview_MemoryView_10memoryview_22copy_fortran().
static PyObject * __pyx_memoryview_copy_object (struct __pyx_memoryview_obj * __pyx_v_memview) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_copy_object_from_slice(), and __pyx_memoryview_slice_copy().
Referenced by __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__().
static PyObject * __pyx_memoryview_copy_object_from_slice (struct __pyx_memoryview_obj * __pyx_v_memview, __Pyx_memviewslice * __pyx_v_memviewslice) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_fromslice(), __pyx_memoryview_obj::dtype_is_object, Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy_object(), __pyx_memoryview_MemoryView_10memoryview_20copy(), and __pyx_memoryview_MemoryView_10memoryview_22copy_fortran().
static int __pyx_memoryview_err (PyObject * __pyx_v_error, char * __pyx_v_msg) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_decode_c_string(), __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), and __Pyx_Raise().
Referenced by __pyx_memoryview_copy_data_to_temp(), and __pyx_memslice_transpose().
static int __pyx_memoryview_err_dim (PyObject * __pyx_v_error, char * __pyx_v_msg, int __pyx_v_dim) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_decode_c_string(), __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyInt_From_int(), __Pyx_PyObject_Call(), and __Pyx_Raise().
Referenced by __pyx_memoryview_copy_contents(), and __pyx_memoryview_slice_memviewslice().
static int __pyx_memoryview_err_extents (int __pyx_v_i, Py_ssize_t __pyx_v_extent1, Py_ssize_t __pyx_v_extent2) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyInt_From_int(), __Pyx_PyObject_Call(), and __Pyx_Raise().
Referenced by __pyx_memoryview_copy_contents().
static PyObject* __pyx_memoryview_fromslice (__Pyx_memviewslice , int , PyObject * *)(char *, int(*)(char *, PyObject *) , int) static
Referenced by __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_memoryview_copy_object_from_slice(), and __pyx_memview_slice().
static PyObject* __pyx_memoryview_fromslice (__Pyx_memviewslice __pyx_v_memviewslice, int __pyx_v_ndim, PyObject *(*)(char *) __pyx_v_to_object_func, int(*)(char *, PyObject *) __pyx_v_to_dtype_func, int __pyx_v_dtype_is_object) static
References __Pyx_AddTraceback(), __pyx_memoryviewslice_obj::__pyx_base, __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), Py_buffer::buf, __Pyx_memviewslice::data, __pyx_memoryview_obj::flags, __pyx_memoryviewslice_obj::from_object, __pyx_memoryviewslice_obj::from_slice, Py_buffer::itemsize, Py_buffer::len, __Pyx_memviewslice::memview, Py_buffer::ndim, Py_buffer::shape, __Pyx_memviewslice::shape, Py_buffer::strides, __Pyx_memviewslice::strides, Py_buffer::suboffsets, __Pyx_memviewslice::suboffsets, __pyx_memoryviewslice_obj::to_dtype_func, __pyx_memoryviewslice_obj::to_object_func, __pyx_memoryview_obj::typeinfo, and __pyx_memoryview_obj::view.
static char* __pyx_memoryview_get_item_pointer (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_index) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_pybuffer_index(), __Pyx_PyIndex_AsSsize_t(), Py_buffer::buf, and __pyx_memoryview_obj::view.
Referenced by PyInit_pynestkernel().
static PyObject * __pyx_memoryview_get_itemsize (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__().
Referenced by __pyx_getprop___pyx_memoryview_itemsize().
static PyObject * __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, Py_buffer::itemsize, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_get_itemsize().
static PyObject * __pyx_memoryview_get_nbytes (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__().
Referenced by __pyx_getprop___pyx_memoryview_nbytes().
static PyObject * __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_GetAttrStr(), Py_buffer::itemsize, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_get_nbytes().
static PyObject * __pyx_memoryview_get_ndim (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__().
Referenced by __pyx_getprop___pyx_memoryview_ndim().
static PyObject * __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyInt_From_int(), Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_get_ndim().
static PyObject * __pyx_memoryview_get_shape (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__().
Referenced by __pyx_getprop___pyx_memoryview_shape().
static PyObject * __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_ListComp_Append(), Py_buffer::ndim, Py_buffer::shape, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_get_shape().
static PyObject * __pyx_memoryview_get_size (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__().
Referenced by __pyx_getprop___pyx_memoryview_size().
static PyObject * __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_int_1, __pyx_lineno, __Pyx_PyObject_GetAttrStr(), and __pyx_memoryview_obj::_size.
Referenced by __pyx_memoryview_get_size().
static __Pyx_memviewslice * __pyx_memoryview_get_slice_from_memoryview (struct __pyx_memoryview_obj * __pyx_v_memview, __Pyx_memviewslice * __pyx_v_mslice) static
References __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_slice_copy(), __Pyx_TypeTest(), __Pyx_WriteUnraisable(), and __pyx_memoryviewslice_obj::from_slice.
Referenced by __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), __pyx_memoryview_MemoryView_10memoryview_18is_f_contig(), __pyx_memoryview_setitem_slice_assign_scalar(), and __pyx_memoryview_setitem_slice_assignment().
static PyObject * __pyx_memoryview_get_strides (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__().
Referenced by __pyx_getprop___pyx_memoryview_strides().
static PyObject * __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_ListComp_Append(), __Pyx_PyObject_Call(), __Pyx_Raise(), Py_buffer::ndim, Py_buffer::strides, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_get_strides().
static PyObject * __pyx_memoryview_get_suboffsets (PyObject * __pyx_v_self) static
References __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__().
Referenced by __pyx_getprop___pyx_memoryview_suboffsets().
static PyObject * __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_ListComp_Append(), Py_buffer::ndim, Py_buffer::suboffsets, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_get_suboffsets().
static CYTHON_UNUSED int __pyx_memoryview_getbuffer (PyObject * __pyx_v_self, Py_buffer * __pyx_v_info, int __pyx_v_flags) static
References __pyx_memoryview_getbuffer_MemoryView_10memoryview_8__getbuffer__().
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static int __pyx_memoryview_getbuffer_MemoryView_10memoryview_8__getbuffer__ (struct __pyx_memoryview_obj * __pyx_v_self, Py_buffer * __pyx_v_info, int __pyx_v_flags) static
References Py_buffer::buf, Py_buffer::format, Py_buffer::itemsize, Py_buffer::len, Py_buffer::ndim, Py_buffer::obj, Py_buffer::readonly, Py_buffer::shape, Py_buffer::strides, Py_buffer::suboffsets, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_getbuffer().
static PyObject * __pyx_memoryview_is_c_contig (PyObject * __pyx_v_self, CYTHON_UNUSED PyObject * unused) static
References __pyx_memoryview_MemoryView_10memoryview_16is_c_contig().
static PyObject * __pyx_memoryview_is_f_contig (PyObject * __pyx_v_self, CYTHON_UNUSED PyObject * unused) static
References __pyx_memoryview_MemoryView_10memoryview_18is_f_contig().
static PyObject* __pyx_memoryview_is_slice (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_obj) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_ExceptionReset(), __Pyx_ExceptionSave(), __pyx_f, __pyx_filename, __Pyx_GetException(), __pyx_lineno, __Pyx_PyInt_From_int(), __Pyx_PyObject_Call(), __pyx_memoryview_obj::dtype_is_object, and __pyx_memoryview_obj::flags.
Referenced by PyInit_pynestkernel().
static Py_ssize_t __pyx_memoryview_MemoryView_10memoryview_10__len__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References Py_buffer::ndim, Py_buffer::shape, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview___len__().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_12__repr__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), and __Pyx_PyObject_GetAttrStr().
Referenced by __pyx_memoryview___repr__().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_14__str__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, and __Pyx_PyObject_GetAttrStr().
Referenced by __pyx_memoryview___str__().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_16is_c_contig (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_get_slice_from_memoryview(), __pyx_memviewslice_is_contig(), Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_is_c_contig().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_18is_f_contig (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_get_slice_from_memoryview(), __pyx_memviewslice_is_contig(), Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_is_f_contig().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_20copy (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_copy_new_contig(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_slice_copy(), __pyx_memoryview_obj::dtype_is_object, __pyx_memoryview_obj::flags, Py_buffer::itemsize, Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_22copy_fortran (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_copy_new_contig(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_slice_copy(), __pyx_memoryview_obj::dtype_is_object, __pyx_memoryview_obj::flags, Py_buffer::itemsize, Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy_fortran().
static void __pyx_memoryview_MemoryView_10memoryview_2__dealloc__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_ReleaseBuffer(), __pyx_memoryview_obj::lock, __pyx_memoryview_obj::obj, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview___dealloc__().
static PyObject * __pyx_memoryview_MemoryView_10memoryview_4__getitem__ (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_index) static
References __Pyx_AddTraceback(), __pyx_builtin_Ellipsis, __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memview_slice(), __Pyx_PyObject_IsTrue(), __Pyx_RaiseNeedMoreValuesError(), __Pyx_RaiseNoneNotIterableError(), __Pyx_RaiseTooManyValuesError(), __pyx_memoryview_obj::__pyx_vtab, _unellipsify(), Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview___getitem__().
static int __pyx_memoryview_MemoryView_10memoryview_6__setitem__ (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_index, PyObject * __pyx_v_value) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_IsTrue(), __Pyx_RaiseNeedMoreValuesError(), __Pyx_RaiseNoneNotIterableError(), __Pyx_RaiseTooManyValuesError(), __Pyx_TypeTest(), __pyx_memoryview_obj::__pyx_vtab, _unellipsify(), Py_buffer::ndim, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview___setitem__().
static int __pyx_memoryview_MemoryView_10memoryview___cinit__ (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_obj, int __pyx_v_flags, int __pyx_v_dtype_is_object) static
References __Pyx_AddTraceback(), __pyx_align_pointer(), __pyx_clineno, __pyx_f, __pyx_filename, __Pyx_GetBuffer(), __pyx_lineno, __pyx_memoryview_type, __Pyx_PyObject_IsTrue(), __pyx_memoryview_obj::acquisition_count, __pyx_memoryview_obj::acquisition_count_aligned_p, __pyx_memoryview_obj::dtype_is_object, __pyx_memoryview_obj::flags, Py_buffer::format, __pyx_memoryview_obj::lock, Py_buffer::obj, __pyx_memoryview_obj::obj, __pyx_memoryview_obj::typeinfo, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview___cinit__().
static PyObject * __pyx_memoryview_new (PyObject * __pyx_v_o, int __pyx_v_flags, int __pyx_v_dtype_is_object, __Pyx_TypeInfo * __pyx_v_typeinfo) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyInt_From_int(), __Pyx_PyObject_Call(), and __pyx_memoryview_obj::typeinfo.
Referenced by __Pyx_GetModuleGlobalName().
static void __pyx_memoryview_refcount_copying (__Pyx_memviewslice * __pyx_v_dst, int __pyx_v_dtype_is_object, int __pyx_v_ndim, int __pyx_v_inc) static
References __pyx_memoryview_refcount_objects_in_slice_with_gil(), __Pyx_memviewslice::data, __Pyx_memviewslice::shape, and __Pyx_memviewslice::strides.
Referenced by __pyx_memoryview_copy_contents(), and __pyx_memoryview_slice_assign_scalar().
static void __pyx_memoryview_refcount_objects_in_slice (char * __pyx_v_data, Py_ssize_t * __pyx_v_shape, Py_ssize_t * __pyx_v_strides, int __pyx_v_ndim, int __pyx_v_inc) static
Referenced by __pyx_array_MemoryView_5array_4__dealloc__(), and __pyx_memoryview_refcount_objects_in_slice_with_gil().
static void __pyx_memoryview_refcount_objects_in_slice_with_gil (char * __pyx_v_data, Py_ssize_t * __pyx_v_shape, Py_ssize_t * __pyx_v_strides, int __pyx_v_ndim, int __pyx_v_inc) static
References __pyx_memoryview_refcount_objects_in_slice().
Referenced by __pyx_memoryview_refcount_copying().
static PyObject* __pyx_memoryview_setitem_indexed (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_index, PyObject * __pyx_v_value) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, and __pyx_memoryview_obj::__pyx_vtab.
Referenced by PyInit_pynestkernel().
static PyObject* __pyx_memoryview_setitem_slice_assign_scalar (struct __pyx_memoryview_obj * __pyx_v_self, struct __pyx_memoryview_obj * __pyx_v_dst, PyObject * __pyx_v_value) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_ErrFetch(), __Pyx_ErrRestore(), __Pyx_ExceptionReset(), __Pyx_ExceptionSwap(), __pyx_f, __pyx_filename, __Pyx_GetException(), __pyx_lineno, __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_slice_assign_scalar(), __pyx_memoryview_obj::__pyx_vtab, assert_direct_dimensions(), __pyx_memoryview_obj::dtype_is_object, Py_buffer::itemsize, Py_buffer::ndim, Py_buffer::suboffsets, and __pyx_memoryview_obj::view.
Referenced by PyInit_pynestkernel().
static PyObject* __pyx_memoryview_setitem_slice_assignment (struct __pyx_memoryview_obj * __pyx_v_self, PyObject * __pyx_v_dst, PyObject * __pyx_v_src) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_copy_contents(), __pyx_memoryview_get_slice_from_memoryview(), __Pyx_PyInt_As_int(), __Pyx_PyObject_GetAttrStr(), __Pyx_TypeTest(), and __pyx_memoryview_obj::dtype_is_object.
Referenced by PyInit_pynestkernel().
static void __pyx_memoryview_slice_assign_scalar (__Pyx_memviewslice * __pyx_v_dst, int __pyx_v_ndim, size_t __pyx_v_itemsize, void * __pyx_v_item, int __pyx_v_dtype_is_object) static
References __pyx_memoryview__slice_assign_scalar(), __pyx_memoryview_refcount_copying(), __Pyx_memviewslice::data, __Pyx_memviewslice::shape, and __Pyx_memviewslice::strides.
Referenced by __pyx_memoryview_setitem_slice_assign_scalar().
static void __pyx_memoryview_slice_copy (struct __pyx_memoryview_obj * __pyx_v_memview, __Pyx_memviewslice * __pyx_v_dst) static
References Py_buffer::buf, __Pyx_memviewslice::data, __Pyx_memviewslice::memview, Py_buffer::ndim, Py_buffer::shape, __Pyx_memviewslice::shape, Py_buffer::strides, __Pyx_memviewslice::strides, Py_buffer::suboffsets, __Pyx_memviewslice::suboffsets, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy_object(), __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_MemoryView_10memoryview_20copy(), __pyx_memoryview_MemoryView_10memoryview_22copy_fortran(), and __pyx_memview_slice().
static Py_ssize_t __pyx_memoryview_slice_get_size (__Pyx_memviewslice * __pyx_v_src, int __pyx_v_ndim) static
References Py_buffer::itemsize, __Pyx_memviewslice::memview, __Pyx_memviewslice::shape, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy_contents(), and __pyx_memoryview_copy_data_to_temp().
static int __pyx_memoryview_slice_memviewslice (__Pyx_memviewslice * __pyx_v_dst, Py_ssize_t __pyx_v_shape, Py_ssize_t __pyx_v_stride, Py_ssize_t __pyx_v_suboffset, int __pyx_v_dim, int __pyx_v_new_ndim, int * __pyx_v_suboffset_dim, Py_ssize_t __pyx_v_start, Py_ssize_t __pyx_v_stop, Py_ssize_t __pyx_v_step, int __pyx_v_have_start, int __pyx_v_have_stop, int __pyx_v_have_step, int __pyx_v_is_slice) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_err_dim(), __Pyx_memviewslice::data, __Pyx_memviewslice::shape, __Pyx_memviewslice::strides, and __Pyx_memviewslice::suboffsets.
Referenced by __pyx_memview_slice().
static PyObject * __pyx_memoryview_transpose (PyObject * __pyx_v_self) static
References __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__().
Referenced by __pyx_getprop___pyx_memoryview_T().
static PyObject * __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__ (struct __pyx_memoryview_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_copy_object(), __pyx_memslice_transpose(), __Pyx_TypeTest(), and __pyx_memoryviewslice_obj::from_slice.
Referenced by __pyx_memoryview_transpose().
static void __pyx_memoryviewslice___dealloc__ (PyObject * __pyx_v_self) static
References __pyx_memoryviewslice_MemoryView_16_memoryviewslice___dealloc__().
Referenced by __pyx_tp_dealloc__memoryviewslice().
static PyObject * __pyx_memoryviewslice__get__base (PyObject * __pyx_v_self) static
References __pyx_memoryviewslice__get__base_MemoryView_16_memoryviewslice_4base___get__().
Referenced by __pyx_getprop___pyx_memoryviewslice_base().
static PyObject * __pyx_memoryviewslice__get__base_MemoryView_16_memoryviewslice_4base___get__ (struct __pyx_memoryviewslice_obj * __pyx_v_self) static
References __pyx_memoryviewslice_obj::from_object.
Referenced by __pyx_memoryviewslice__get__base().
static PyObject* __pyx_memoryviewslice_assign_item_from_object (struct __pyx_memoryviewslice_obj * __pyx_v_self, char * __pyx_v_itemp, PyObject * __pyx_v_value) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_vtabstruct_memoryview::assign_item_from_object, and __pyx_memoryviewslice_obj::to_dtype_func.
Referenced by PyInit_pynestkernel().
static PyObject* __pyx_memoryviewslice_convert_item_to_object (struct __pyx_memoryviewslice_obj * __pyx_v_self, char * __pyx_v_itemp) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_vtabstruct_memoryview::convert_item_to_object, and __pyx_memoryviewslice_obj::to_object_func.
Referenced by PyInit_pynestkernel().
static void __pyx_memoryviewslice_MemoryView_16_memoryviewslice___dealloc__ (struct __pyx_memoryviewslice_obj * __pyx_v_self) static
References __pyx_memoryviewslice_obj::from_slice.
Referenced by __pyx_memoryviewslice___dealloc__().
static int __pyx_memslice_transpose (__Pyx_memviewslice * __pyx_v_memslice) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_div_long(), __pyx_f, __pyx_filename, __pyx_lineno, __pyx_memoryview_err(), __Pyx_memviewslice::memview, Py_buffer::ndim, __Pyx_memviewslice::shape, __Pyx_memviewslice::strides, __Pyx_memviewslice::suboffsets, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_copy_contents(), and __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__().
static PyObject* __pyx_memview_get_double (const char * itemp) static
Referenced by __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static PyObject* __pyx_memview_get_float (const char * itemp) static
Referenced by __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static PyObject* __pyx_memview_get_int (const char * itemp) static
Referenced by __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static PyObject* __pyx_memview_get_long (const char * itemp) static
Referenced by __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static int __pyx_memview_set_double (const char * itemp, PyObject * obj) static
Referenced by __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static int __pyx_memview_set_float (const char * itemp, PyObject * obj) static
Referenced by __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static int __pyx_memview_set_int (const char * itemp, PyObject * obj) static
Referenced by __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static int __pyx_memview_set_long (const char * itemp, PyObject * obj) static
Referenced by __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), and __Pyx_GetModuleGlobalName().
static struct __pyx_memoryview_obj * __pyx_memview_slice (struct __pyx_memoryview_obj * __pyx_v_memview, PyObject * __pyx_v_indices) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_int_0, __pyx_lineno, __pyx_memoryview_fromslice(), __pyx_memoryview_slice_copy(), __pyx_memoryview_slice_memviewslice(), __Pyx_PyIndex_AsSsize_t(), __Pyx_PyObject_GetAttrStr(), __Pyx_PyObject_IsTrue(), __Pyx_RaiseUnboundLocalError(), __Pyx_TypeTest(), __Pyx_memviewslice::data, __pyx_memoryview_obj::dtype_is_object, __pyx_memoryviewslice_obj::from_slice, __Pyx_memviewslice::memview, Py_buffer::ndim, __Pyx_memviewslice::shape, __Pyx_memviewslice::strides, __Pyx_memviewslice::suboffsets, __pyx_memoryviewslice_obj::to_dtype_func, __pyx_memoryviewslice_obj::to_object_func, and __pyx_memoryview_obj::view.
Referenced by __pyx_memoryview_MemoryView_10memoryview_4__getitem__().
static int __pyx_MemviewEnum___init__ (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_MemviewEnum_MemoryView_4Enum___init__(), __pyx_n_s_name, __Pyx_ParseOptionalKeywords(), and __Pyx_RaiseArgtupleInvalid().
static PyObject * __pyx_MemviewEnum___repr__ (PyObject * __pyx_v_self) static
References __pyx_MemviewEnum_MemoryView_4Enum_2__repr__().
static PyObject * __pyx_MemviewEnum_MemoryView_4Enum_2__repr__ (struct __pyx_MemviewEnum_obj * __pyx_v_self) static
References __pyx_MemviewEnum_obj::name.
Referenced by __pyx_MemviewEnum___repr__().
static int __pyx_MemviewEnum_MemoryView_4Enum___init__ (struct __pyx_MemviewEnum_obj * __pyx_v_self, PyObject * __pyx_v_name) static
References __pyx_MemviewEnum_obj::name.
Referenced by __pyx_MemviewEnum___init__().
static int __pyx_memviewslice_is_contig (const __Pyx_memviewslice * mvs, char order, int ndim) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), and __pyx_memoryview_MemoryView_10memoryview_18is_f_contig().
static int __pyx_mp_ass_subscript_array (PyObject * o, PyObject * i, PyObject * v) static
References __pyx_array___setitem__().
static int __pyx_mp_ass_subscript_memoryview (PyObject * o, PyObject * i, PyObject * v) static
References __pyx_memoryview___setitem__().
static CYTHON_INLINE float __PYX_NAN () static
static int __Pyx_ParseOptionalKeywords (PyObject * kwds, PyObject ** argnames[], \PyObject * kwds2, PyObject * values[], Py_ssize_t num_pos_args, \const char * function_name) static
Referenced by __pyx_array___cinit__(), __pyx_memoryview___cinit__(), __pyx_MemviewEnum___init__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), and __pyx_pw_12pynestkernel_10SLILiteral_1__init__().
static int __Pyx_ParseOptionalKeywords (PyObject * kwds, PyObject ** argnames[], PyObject * kwds2, PyObject * values[], Py_ssize_t num_pos_args, const char * function_name) static
References __Pyx_RaiseDoubleKeywordsError().
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_10pop (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_filename, __Pyx_GetModuleGlobalName(), __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_Raise(), TokenArrayObj::empty(), SLIInterpreter::OStack, __pyx_obj_12pynestkernel_NESTEngine::pEngine, TokenStack::pop(), and TokenStack::top().
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_11pop().
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self, PyObject * __pyx_v_conns) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __Pyx_ErrRestore(), __Pyx_ExceptionReset(), __Pyx_ExceptionSave(), __pyx_f, __pyx_filename, __Pyx_GetException(), __pyx_lineno, __Pyx_PyInt_As_long(), __Pyx_PyInt_From_long(), SLIInterpreter::OStack, __pyx_obj_12pynestkernel_NESTEngine::pEngine, TokenStack::push(), TokenArray::push_back(), and TokenArray::reserve().
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_13push_connection_datums().
static void __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__ (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self) static
References __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_WriteUnraisable(), nestshutdown(), __pyx_obj_12pynestkernel_NESTEngine::pEngine, and __pyx_obj_12pynestkernel_NESTEngine::pNet.
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_3__dealloc__().
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_4init (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self, PyObject * __pyx_v_argv, PyObject * __pyx_v_modulepath) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_convert_string_from_py_(), __Pyx_CppExn2PyErr(), __pyx_empty_tuple, __Pyx_ErrFetch(), __Pyx_ErrRestore(), __Pyx_ExceptionReset(), __Pyx_ExceptionSwap(), __pyx_f, __pyx_filename, __Pyx_GetException(), __Pyx_GetModuleGlobalName(), __pyx_k_pynest, __pyx_lineno, __Pyx_PyInt_FromSize_t(), __Pyx_PyObject_AsString(), __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_Raise(), neststartup(), __pyx_obj_12pynestkernel_NESTEngine::pEngine, and __pyx_obj_12pynestkernel_NESTEngine::pNet.
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_5init().
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_6run (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self, PyObject * __pyx_v_cmd) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_convert_string_from_py_(), __Pyx_CppExn2PyErr(), __pyx_empty_tuple, __pyx_f, __pyx_filename, __Pyx_GetModuleGlobalName(), __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __Pyx_Raise(), SLIInterpreter::execute(), and __pyx_obj_12pynestkernel_NESTEngine::pEngine.
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_7run().
static PyObject * __pyx_pf_12pynestkernel_10NESTEngine_8push (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self, PyObject * __pyx_v_obj) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_CppExn2PyErr(), __pyx_f, __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_filename, __Pyx_GetModuleGlobalName(), __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_Raise(), SLIInterpreter::OStack, __pyx_obj_12pynestkernel_NESTEngine::pEngine, and TokenStack::push().
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_9push().
static int __pyx_pf_12pynestkernel_10NESTEngine___cinit__ (struct __pyx_obj_12pynestkernel_NESTEngine * __pyx_v_self) static
References __pyx_obj_12pynestkernel_NESTEngine::pEngine, and __pyx_obj_12pynestkernel_NESTEngine::pNet.
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_1__cinit__().
static Py_hash_t __pyx_pf_12pynestkernel_10SLILiteral_2__hash__ (struct __pyx_obj_12pynestkernel_SLILiteral * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_obj_12pynestkernel_SLILiteral::_hash, and __pyx_obj_12pynestkernel_SLILiteral::name.
Referenced by __pyx_pw_12pynestkernel_10SLILiteral_3__hash__().
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_4__repr__ (struct __pyx_obj_12pynestkernel_SLILiteral * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), and __pyx_obj_12pynestkernel_SLILiteral::name.
Referenced by __pyx_pw_12pynestkernel_10SLILiteral_5__repr__().
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_4name___get__ (struct __pyx_obj_12pynestkernel_SLILiteral * __pyx_v_self) static
References __pyx_obj_12pynestkernel_SLILiteral::name.
Referenced by __pyx_pw_12pynestkernel_10SLILiteral_4name_1__get__().
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_6__str__ (struct __pyx_obj_12pynestkernel_SLILiteral * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), and __pyx_obj_12pynestkernel_SLILiteral::name.
Referenced by __pyx_pw_12pynestkernel_10SLILiteral_7__str__().
static PyObject * __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__ (PyObject * __pyx_v_self, PyObject * __pyx_v_other, int __pyx_v_op) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, and __Pyx_PyObject_GetAttrStr().
Referenced by __pyx_pw_12pynestkernel_10SLILiteral_9__richcmp__().
static int __pyx_pf_12pynestkernel_10SLILiteral___init__ (struct __pyx_obj_12pynestkernel_SLILiteral * __pyx_v_self, PyObject * __pyx_v_name) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), __pyx_obj_12pynestkernel_SLILiteral::_hash, and __pyx_obj_12pynestkernel_SLILiteral::name.
Referenced by __pyx_pw_12pynestkernel_10SLILiteral_1__init__().
static void __pyx_pf_12pynestkernel_8SLIDatum_2__dealloc__ (struct __pyx_obj_12pynestkernel_SLIDatum * __pyx_v_self) static
References __pyx_obj_12pynestkernel_SLIDatum::thisptr.
Referenced by __pyx_pw_12pynestkernel_8SLIDatum_3__dealloc__().
static PyObject * __pyx_pf_12pynestkernel_8SLIDatum_4__repr__ (struct __pyx_obj_12pynestkernel_SLIDatum * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_kp_s_SLIDatum_unassociated, __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_PyObject_GetAttrStr(), __pyx_obj_12pynestkernel_SLIDatum::dtype, and __pyx_obj_12pynestkernel_SLIDatum::thisptr.
Referenced by __pyx_pw_12pynestkernel_8SLIDatum_5__repr__().
static PyObject * __pyx_pf_12pynestkernel_8SLIDatum_5dtype___get__ (struct __pyx_obj_12pynestkernel_SLIDatum * __pyx_v_self) static
References __pyx_obj_12pynestkernel_SLIDatum::dtype.
Referenced by __pyx_pw_12pynestkernel_8SLIDatum_5dtype_1__get__().
static int __pyx_pf_12pynestkernel_8SLIDatum___cinit__ (struct __pyx_obj_12pynestkernel_SLIDatum * __pyx_v_self) static
References __pyx_kp_u_, __pyx_obj_12pynestkernel_SLIDatum::dtype, and __pyx_obj_12pynestkernel_SLIDatum::thisptr.
Referenced by __pyx_pw_12pynestkernel_8SLIDatum_1__cinit__().
static void __pyx_pf_7cpython_5array_5array_2__releasebuffer__ (CYTHON_UNUSED arrayobject * __pyx_v_self, Py_buffer * __pyx_v_info) static
References Py_buffer::shape.
Referenced by __pyx_pw_7cpython_5array_5array_3__releasebuffer__().
static int __pyx_pf_7cpython_5array_5array___getbuffer__ (arrayobject * __pyx_v_self, Py_buffer * __pyx_v_info, CYTHON_UNUSED int __pyx_v_flags) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyIndex_AsSsize_t(), arrayobject::as_chars, Py_buffer::buf, arrayobject::data, Py_buffer::format, Py_buffer::itemsize, arraydescr::itemsize, Py_buffer::len, Py_buffer::ndim, arrayobject::ob_descr, Py_buffer::obj, Py_buffer::readonly, Py_buffer::shape, Py_buffer::strides, Py_buffer::suboffsets, and arraydescr::typecode.
Referenced by __pyx_pw_7cpython_5array_5array_1__getbuffer__().
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_11pop (PyObject * __pyx_v_self, CYTHON_UNUSED PyObject * unused) static
References __pyx_pf_12pynestkernel_10NESTEngine_10pop().
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_13push_connection_datums (PyObject * __pyx_v_self, PyObject * __pyx_v_conns) static
References __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums().
static int __pyx_pw_12pynestkernel_10NESTEngine_1__cinit__ (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_CheckKeywordStrings(), __pyx_pf_12pynestkernel_10NESTEngine___cinit__(), and __Pyx_RaiseArgtupleInvalid().
Referenced by __pyx_tp_new_12pynestkernel_NESTEngine().
static void __pyx_pw_12pynestkernel_10NESTEngine_3__dealloc__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__().
Referenced by __pyx_tp_dealloc_12pynestkernel_NESTEngine().
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_5init (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_n_s_argv, __pyx_n_s_modulepath, __Pyx_ParseOptionalKeywords(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), and __Pyx_RaiseArgtupleInvalid().
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_7run (PyObject * __pyx_v_self, PyObject * __pyx_v_cmd) static
References __pyx_pf_12pynestkernel_10NESTEngine_6run().
static PyObject * __pyx_pw_12pynestkernel_10NESTEngine_9push (PyObject * __pyx_v_self, PyObject * __pyx_v_obj) static
References __pyx_pf_12pynestkernel_10NESTEngine_8push().
static int __pyx_pw_12pynestkernel_10SLILiteral_1__init__ (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __pyx_n_s_name, __Pyx_ParseOptionalKeywords(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), and __Pyx_RaiseArgtupleInvalid().
static Py_hash_t __pyx_pw_12pynestkernel_10SLILiteral_3__hash__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_10SLILiteral_2__hash__().
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_4name_1__get__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_10SLILiteral_4name___get__().
Referenced by __pyx_getprop_12pynestkernel_10SLILiteral_name().
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_5__repr__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_10SLILiteral_4__repr__().
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_7__str__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_10SLILiteral_6__str__().
static PyObject * __pyx_pw_12pynestkernel_10SLILiteral_9__richcmp__ (PyObject * __pyx_v_self, PyObject * __pyx_v_other, int __pyx_v_op) static
References __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__().
static int __pyx_pw_12pynestkernel_8SLIDatum_1__cinit__ (PyObject * __pyx_v_self, PyObject * __pyx_args, PyObject * __pyx_kwds) static
References __Pyx_CheckKeywordStrings(), __pyx_pf_12pynestkernel_8SLIDatum___cinit__(), and __Pyx_RaiseArgtupleInvalid().
Referenced by __pyx_tp_new_12pynestkernel_SLIDatum().
static void __pyx_pw_12pynestkernel_8SLIDatum_3__dealloc__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_8SLIDatum_2__dealloc__().
Referenced by __pyx_tp_dealloc_12pynestkernel_SLIDatum().
static PyObject * __pyx_pw_12pynestkernel_8SLIDatum_5__repr__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_8SLIDatum_4__repr__().
static PyObject * __pyx_pw_12pynestkernel_8SLIDatum_5dtype_1__get__ (PyObject * __pyx_v_self) static
References __pyx_pf_12pynestkernel_8SLIDatum_5dtype___get__().
Referenced by __pyx_getprop_12pynestkernel_8SLIDatum_dtype().
static CYTHON_UNUSED int __pyx_pw_7cpython_5array_5array_1__getbuffer__ (PyObject * __pyx_v_self, Py_buffer * __pyx_v_info, int __pyx_v_flags) static
References __pyx_pf_7cpython_5array_5array___getbuffer__().
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_UNUSED void __pyx_pw_7cpython_5array_5array_3__releasebuffer__ (PyObject * __pyx_v_self, Py_buffer * __pyx_v_info) static
References __pyx_pf_7cpython_5array_5array_2__releasebuffer__().
Referenced by __Pyx_GetModuleGlobalName().
static PyObject* __Pyx_Py3ClassCreate (PyObject * metaclass, PyObject * name, PyObject * bases, PyObject * dict, PyObject * mkw, int calculate_metaclass, int allow_py2_metaclass) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static PyObject* __Pyx_Py3MetaclassPrepare (PyObject * metaclass, PyObject * bases, PyObject * name, PyObject * qualname, PyObject * mkw, PyObject * modname, PyObject * doc) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static CYTHON_INLINE size_t __Pyx_Py_UNICODE_strlen (const Py_UNICODE * u) static
References nest::names::u.
static char * __pyx_pybuffer_index (Py_buffer * __pyx_v_view, char * __pyx_v_bufp, Py_ssize_t __pyx_v_index, Py_ssize_t __pyx_v_dim) static
References __Pyx_AddTraceback(), __pyx_clineno, __Pyx_div_Py_ssize_t(), __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), __Pyx_Raise(), Py_buffer::itemsize, Py_buffer::len, Py_buffer::ndim, Py_buffer::shape, Py_buffer::strides, and Py_buffer::suboffsets.
Referenced by __pyx_memoryview_get_item_pointer().
static CYTHON_INLINE int __Pyx_PyBytes_Equals (PyObject * s1, PyObject * s2, int equals) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t (PyObject *) static
Referenced by __pyx_array___cinit__(), __pyx_array_MemoryView_5array___cinit__(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_get_item_pointer(), __pyx_memview_slice(), and __pyx_pf_7cpython_5array_5array___getbuffer__().
static CYTHON_INLINE char __Pyx_PyInt_As_char (PyObject *) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_PyInt_As_int (PyObject *) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview___cinit__(), and __pyx_memoryview_setitem_slice_assignment().
static CYTHON_INLINE long __Pyx_PyInt_As_long (PyObject *) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_GetModuleGlobalName(), and __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums().
static CYTHON_INLINE size_t __Pyx_PyInt_As_size_t (PyObject *) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_int (int value) static
Referenced by __pyx_array_MemoryView_5array___cinit__(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_new(), and get_memview_MemoryView_5array_7memview___get__().
static CYTHON_INLINE PyObject* __Pyx_PyInt_From_long (long value) static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_convert_item_to_object(), and __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums().
static CYTHON_INLINE PyObject* __Pyx_PyInt_FromSize_t (size_t) static
Referenced by __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_GetModuleGlobalName(), and __pyx_pf_12pynestkernel_10NESTEngine_4init().
static CYTHON_INLINE int __Pyx_PyList_Append (PyObject * list, PyObject * x) static
Referenced by _unellipsify().
static CYTHON_INLINE int __Pyx_PyList_Extend (PyObject * L, PyObject * v) static
Referenced by _unellipsify().
static CYTHON_INLINE PyObject* __Pyx_PyNumber_Int (PyObject * x) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE char* __Pyx_PyObject_AsString (PyObject *) static
Referenced by __pyx_array_MemoryView_5array___cinit__(), __Pyx_GetModuleGlobalName(), and __pyx_pf_12pynestkernel_10NESTEngine_4init().
static CYTHON_INLINE char* __Pyx_PyObject_AsStringAndSize (PyObject * , Py_ssize_t * length) static
Referenced by __pyx_convert_string_from_py_(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject * __Pyx_PyObject_Call (PyObject * func, PyObject * arg, PyObject * kw) static
Referenced by __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_array_new(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_new(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), __pyx_pf_12pynestkernel_8SLIDatum_4__repr__(), __pyx_pybuffer_index(), _unellipsify(), assert_direct_dimensions(), get_memview_MemoryView_5array_7memview___get__(), and PyInit_pynestkernel().
static CYTHON_INLINE PyObject* __Pyx_PyObject_GetAttrStr (PyObject * obj, PyObject * attr_name) static
Referenced by __pyx_array_MemoryView_5array_10__setitem__(), __pyx_array_MemoryView_5array_6__getattr__(), __pyx_array_MemoryView_5array_8__getitem__(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __Pyx_GetBuiltinName(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__(), __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_MemoryView_10memoryview_14__str__(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memview_slice(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__(), and __pyx_pf_12pynestkernel_8SLIDatum_4__repr__().
static CYTHON_INLINE int __Pyx_PyObject_IsTrue (PyObject *) static
Referenced by __pyx_array___cinit__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_f_12pynestkernel_python_object_to_datum(), __Pyx_GetModuleGlobalName(), __pyx_memoryview___cinit__(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_memview_slice(), and _unellipsify().
static CYTHON_INLINE __Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_double (PyObject *) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE __Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_float (PyObject *) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE __Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_int (PyObject *) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE __Pyx_memviewslice __Pyx_PyObject_to_MemoryviewSlice_ds_long (PyObject *) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_PyUnicode_Equals (PyObject * s1, PyObject * s2, int equals) static
Referenced by __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_f_12pynestkernel_python_object_to_datum(), and __Pyx_GetModuleGlobalName().
static CYTHON_INLINE PyObject* __Pyx_PyUnicode_FromString (const char *) static
Referenced by __Pyx_GetModuleGlobalName().
static void __Pyx_Raise (PyObject * type, PyObject * value, PyObject * tb, PyObject * cause) static
Referenced by __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_datum_to_object(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pybuffer_index(), _unellipsify(), and assert_direct_dimensions().
static void __Pyx_RaiseArgtupleInvalid (const char * func_name, int exact, Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found) static
Referenced by __pyx_array___cinit__(), __pyx_memoryview___cinit__(), __pyx_MemviewEnum___init__(), __pyx_pw_12pynestkernel_10NESTEngine_1__cinit__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), __pyx_pw_12pynestkernel_10SLILiteral_1__init__(), and __pyx_pw_12pynestkernel_8SLIDatum_1__cinit__().
static void __Pyx_RaiseDoubleKeywordsError (const char * func_name, PyObject * kw_name) static
Referenced by __Pyx_ParseOptionalKeywords().
static CYTHON_INLINE void __Pyx_RaiseNeedMoreValuesError (Py_ssize_t index) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), and __pyx_memoryview_MemoryView_10memoryview_6__setitem__().
static CYTHON_INLINE void __Pyx_RaiseNoneNotIterableError (void) static
Referenced by __Pyx_GetModuleGlobalName(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), and __pyx_memoryview_MemoryView_10memoryview_6__setitem__().
static CYTHON_INLINE void __Pyx_RaiseTooManyValuesError (Py_ssize_t expected) static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), and __pyx_memoryview_MemoryView_10memoryview_6__setitem__().
static CYTHON_INLINE void __Pyx_RaiseUnboundLocalError (const char * varname) static
Referenced by __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __Pyx_GetModuleGlobalName(), and __pyx_memview_slice().
static __Pyx_RefNannyAPIStruct * __Pyx_RefNannyImportAPI (const char * modname) static
References nest::names::p.
Referenced by PyInit_pynestkernel().
static void __Pyx_ReleaseBuffer (Py_buffer * view) static
Referenced by __Pyx_GetModuleGlobalName(), and __pyx_memoryview_MemoryView_10memoryview_2__dealloc__().
static CYTHON_INLINE void __Pyx_SafeReleaseBuffer (Py_buffer * info) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_SetItemInt_Fast (PyObject * o, Py_ssize_t i, PyObject * v, int is_list, int wraparound, int boundscheck) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_SetItemInt_Generic (PyObject * o, PyObject * j, PyObject * v) static
Referenced by __Pyx_GetModuleGlobalName().
static int __Pyx_SetVtable (PyObject * dict, void * vtable) static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
static int __pyx_slices_overlap (__Pyx_memviewslice * slice1, __Pyx_memviewslice * slice2, int ndim, size_t itemsize) static
Referenced by __Pyx_GetModuleGlobalName(), and __pyx_memoryview_copy_contents().
static PyObject* __pyx_sq_item_array (PyObject * o, Py_ssize_t i) static
References nest::names::x.
static PyObject* __pyx_sq_item_memoryview (PyObject * o, Py_ssize_t i) static
References nest::names::x.
static CYTHON_INLINE int __pyx_sub_acquisition_count_locked (__pyx_atomic_int * acquisition_count, PyThread_type_lock lock) static
Referenced by __Pyx_GetModuleGlobalName().
static int __pyx_tp_clear_12pynestkernel_SLILiteral (PyObject * o) static
References __pyx_obj_12pynestkernel_SLILiteral::_hash, __pyx_obj_12pynestkernel_SLILiteral::name, and nest::names::p.
static int __pyx_tp_clear__memoryviewslice (PyObject * o) static
References __pyx_tp_clear_memoryview(), __pyx_memoryviewslice_obj::from_object, __pyx_memoryviewslice_obj::from_slice, and nest::names::p.
static int __pyx_tp_clear_Enum (PyObject * o) static
References __pyx_MemviewEnum_obj::name, and nest::names::p.
static int __pyx_tp_clear_memoryview (PyObject * o) static
References __pyx_memoryview_obj::_array_interface, __pyx_memoryview_obj::_size, Py_buffer::obj, __pyx_memoryview_obj::obj, nest::names::p, and __pyx_memoryview_obj::view.
Referenced by __pyx_tp_clear__memoryviewslice().
static void __pyx_tp_dealloc_12pynestkernel_NESTEngine (PyObject * o) static
References __pyx_pw_12pynestkernel_10NESTEngine_3__dealloc__().
static void __pyx_tp_dealloc_12pynestkernel_SLIDatum (PyObject * o) static
References __pyx_pw_12pynestkernel_8SLIDatum_3__dealloc__(), __pyx_obj_12pynestkernel_SLIDatum::dtype, and nest::names::p.
static void __pyx_tp_dealloc_12pynestkernel_SLILiteral (PyObject * o) static
References __pyx_obj_12pynestkernel_SLILiteral::_hash, __pyx_obj_12pynestkernel_SLILiteral::name, and nest::names::p.
static void __pyx_tp_dealloc__memoryviewslice (PyObject * o) static
References __pyx_memoryviewslice___dealloc__(), __pyx_tp_dealloc_memoryview(), __pyx_memoryviewslice_obj::from_object, and nest::names::p.
static void __pyx_tp_dealloc_array (PyObject * o) static
References __pyx_array___dealloc__(), __pyx_array_obj::_format, __pyx_array_obj::mode, and nest::names::p.
static void __pyx_tp_dealloc_Enum (PyObject * o) static
References __pyx_MemviewEnum_obj::name, and nest::names::p.
static void __pyx_tp_dealloc_memoryview (PyObject * o) static
References __pyx_memoryview___dealloc__(), __pyx_memoryview_obj::_array_interface, __pyx_memoryview_obj::_size, __pyx_memoryview_obj::obj, and nest::names::p.
Referenced by __pyx_tp_dealloc__memoryviewslice().
static PyObject* __pyx_tp_getattro_array (PyObject * o, PyObject * n) static
References __pyx_array___getattr__().
static PyObject* __pyx_tp_new_12pynestkernel_NESTEngine (PyTypeObject * t, PyObject * a, PyObject * k) static
static PyObject* __pyx_tp_new_12pynestkernel_NESTEngine (PyTypeObject * t, CYTHON_UNUSED PyObject * a, CYTHON_UNUSED PyObject * k) static
References __pyx_empty_tuple, and __pyx_pw_12pynestkernel_10NESTEngine_1__cinit__().
static PyObject* __pyx_tp_new_12pynestkernel_SLIDatum (PyTypeObject * t, PyObject * a, PyObject * k) static
static PyObject* __pyx_tp_new_12pynestkernel_SLIDatum (PyTypeObject * t, CYTHON_UNUSED PyObject * a, CYTHON_UNUSED PyObject * k) static
References __pyx_empty_tuple, __pyx_pw_12pynestkernel_8SLIDatum_1__cinit__(), __pyx_obj_12pynestkernel_SLIDatum::__pyx_vtab, __pyx_vtabptr_12pynestkernel_SLIDatum, __pyx_obj_12pynestkernel_SLIDatum::dtype, and nest::names::p.
static PyObject* __pyx_tp_new_12pynestkernel_SLILiteral (PyTypeObject * t, PyObject * a, PyObject * k) static
static PyObject* __pyx_tp_new_12pynestkernel_SLILiteral (PyTypeObject * t, CYTHON_UNUSED PyObject * a, CYTHON_UNUSED PyObject * k) static
References __pyx_empty_tuple, __pyx_obj_12pynestkernel_SLILiteral::_hash, __pyx_obj_12pynestkernel_SLILiteral::name, and nest::names::p.
static PyObject * __pyx_tp_new__memoryviewslice (PyTypeObject * t, PyObject * a, PyObject * k) static
References __pyx_memoryviewslice_obj::__pyx_base, __pyx_tp_new_memoryview(), __pyx_memoryview_obj::__pyx_vtab, __pyx_memoryviewslice_obj::from_object, __pyx_memoryviewslice_obj::from_slice, __Pyx_memviewslice::memview, and nest::names::p.
static PyObject * __pyx_tp_new_array (PyTypeObject * t, PyObject * a, PyObject * k) static
References __pyx_array___cinit__(), __pyx_empty_tuple, __pyx_array_obj::_format, __pyx_array_obj::mode, and nest::names::p.
static PyObject* __pyx_tp_new_Enum (PyTypeObject * t, PyObject * a, PyObject * k) static
static PyObject* __pyx_tp_new_Enum (PyTypeObject * t, CYTHON_UNUSED PyObject * a, CYTHON_UNUSED PyObject * k) static
References __pyx_empty_tuple, __pyx_MemviewEnum_obj::name, and nest::names::p.
static PyObject * __pyx_tp_new_memoryview (PyTypeObject * t, PyObject * a, PyObject * k) static
References __pyx_empty_tuple, __pyx_memoryview___cinit__(), __pyx_memoryview_obj::__pyx_vtab, __pyx_vtabptr_memoryview, __pyx_memoryview_obj::_array_interface, __pyx_memoryview_obj::_size, Py_buffer::obj, __pyx_memoryview_obj::obj, nest::names::p, and __pyx_memoryview_obj::view.
Referenced by __pyx_tp_new__memoryviewslice().
static int __pyx_tp_traverse_12pynestkernel_SLILiteral (PyObject * o, visitproc v, void * a) static
References __pyx_obj_12pynestkernel_SLILiteral::_hash, nest::names::a, numerics::e, __pyx_obj_12pynestkernel_SLILiteral::name, and nest::names::p.
static int __pyx_tp_traverse__memoryviewslice (PyObject * o, visitproc v, void * a) static
References __pyx_tp_traverse_memoryview(), nest::names::a, numerics::e, __pyx_memoryviewslice_obj::from_object, and nest::names::p.
static int __pyx_tp_traverse_Enum (PyObject * o, visitproc v, void * a) static
References nest::names::a, numerics::e, __pyx_MemviewEnum_obj::name, and nest::names::p.
static int __pyx_tp_traverse_memoryview (PyObject * o, visitproc v, void * a) static
References __pyx_memoryview_obj::_array_interface, __pyx_memoryview_obj::_size, nest::names::a, numerics::e, Py_buffer::obj, __pyx_memoryview_obj::obj, nest::names::p, and __pyx_memoryview_obj::view.
Referenced by __pyx_tp_traverse__memoryviewslice().
static int __pyx_typeinfo_cmp (__Pyx_TypeInfo * a, __Pyx_TypeInfo * b) static
Referenced by __Pyx_GetModuleGlobalName().
static CYTHON_INLINE int __Pyx_TypeTest (PyObject * obj, PyTypeObject * type) static
Referenced by __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __Pyx_GetModuleGlobalName(), __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__(), and __pyx_memview_slice().
static int __Pyx_ValidateAndInit_memviewslice (int * axes_specs, int c_or_f_flag, int buf_flags, int ndim, __Pyx_TypeInfo * dtype, __Pyx_BufFmt_StackElem stack[], __Pyx_memviewslice * memviewslice, PyObject * original_obj) static
Referenced by __Pyx_GetModuleGlobalName().
static void __Pyx_WriteUnraisable (const char * name, int clineno, int lineno, const char * filename, int full_traceback) static
Referenced by __pyx_memoryview_get_slice_from_memoryview(), and __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__().
static void __Pyx_WriteUnraisable (const char * name, CYTHON_UNUSED int clineno, CYTHON_UNUSED int lineno, CYTHON_UNUSED const char * filename, int full_traceback) static
References __Pyx_ErrFetch(), and __Pyx_ErrRestore().
static CYTHON_INLINE void __Pyx_XDEC_MEMVIEW (__Pyx_memviewslice * , int , int) static
Referenced by __Pyx_GetModuleGlobalName().
static void _copy_strided_to_strided (char * __pyx_v_src_data, Py_ssize_t * __pyx_v_src_strides, char * __pyx_v_dst_data, Py_ssize_t * __pyx_v_dst_strides, Py_ssize_t * __pyx_v_src_shape, Py_ssize_t * __pyx_v_dst_shape, int __pyx_v_ndim, size_t __pyx_v_itemsize) static
Referenced by copy_strided_to_strided().
static PyObject * _unellipsify (PyObject * __pyx_v_index, int __pyx_v_ndim) static
References __Pyx_AddTraceback(), __pyx_builtin_Ellipsis, __pyx_clineno, __pyx_f, __pyx_filename, __pyx_int_0, __pyx_lineno, __Pyx_PyList_Append(), __Pyx_PyList_Extend(), __Pyx_PyObject_Call(), __Pyx_PyObject_IsTrue(), and __Pyx_Raise().
Referenced by __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), and __pyx_memoryview_MemoryView_10memoryview_6__setitem__().
static Py_ssize_t abs_py_ssize_t (Py_ssize_t __pyx_v_arg) static
Referenced by __pyx_get_best_slice_order().
static PyObject * assert_direct_dimensions (Py_ssize_t * __pyx_v_suboffsets, int __pyx_v_ndim) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyObject_Call(), and __Pyx_Raise().
Referenced by __pyx_memoryview_setitem_slice_assign_scalar().
static void copy_strided_to_strided (__Pyx_memviewslice * __pyx_v_src, __Pyx_memviewslice * __pyx_v_dst, int __pyx_v_ndim, size_t __pyx_v_itemsize) static
References _copy_strided_to_strided(), __Pyx_memviewslice::data, __Pyx_memviewslice::shape, and __Pyx_memviewslice::strides.
Referenced by __pyx_memoryview_copy_contents(), and __pyx_memoryview_copy_data_to_temp().
static PyObject * get_memview (PyObject * __pyx_v_self) static
References get_memview_MemoryView_5array_7memview___get__().
Referenced by __pyx_getprop___pyx_array_memview().
static PyObject * get_memview_MemoryView_5array_7memview___get__ (struct __pyx_array_obj * __pyx_v_self) static
References __Pyx_AddTraceback(), __pyx_clineno, __pyx_f, __pyx_filename, __pyx_lineno, __Pyx_PyInt_From_int(), __Pyx_PyObject_Call(), and __pyx_array_obj::dtype_is_object.
Referenced by get_memview().
PyMODINIT_FUNC initpynestkernel (void)
PyObject * newarrayobject (PyTypeObject * type, Py_ssize_t size, struct arraydescr * descr) static
References arrayobject::allocated, arrayobject::data, arraydescr::itemsize, arrayobject::ob_descr, arrayobject::ob_item, arrayobject::ob_size, and arrayobject::weakreflist.
Referenced by __pyx_f_7cpython_5array_clone(), and __pyx_f_7cpython_5array_copy().
PyMODINIT_FUNC PyInit_pynestkernel (void)
References __Pyx_AddTraceback(), __pyx_array_getbuffer(), __pyx_b, __pyx_vtabstruct__memoryviewslice::__pyx_base, __Pyx_CalculateMetaclass(), __pyx_capsule_create(), __Pyx_check_binary_version(), __pyx_clineno, __pyx_convert_string_from_py_(), __pyx_d, __pyx_empty_bytes, __pyx_empty_tuple, __Pyx_ExceptionReset(), __Pyx_ExceptionSave(), __pyx_f, __pyx_f_12pynestkernel_8SLIDatum__set_datum(), __pyx_filename, __Pyx_Import(), __Pyx_ImportType(), __Pyx_init_sys_getdefaultencoding_params(), __Pyx_InitCachedBuiltins(), __Pyx_InitCachedConstants(), __Pyx_InitGlobals(), __pyx_lineno, __pyx_m, __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_get_item_pointer(), __pyx_memoryview_getbuffer(), __pyx_memoryview_is_slice(), __pyx_memoryview_setitem_indexed(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_type, __pyx_memoryviewslice_assign_item_from_object(), __pyx_memoryviewslice_convert_item_to_object(), __Pyx_Py3ClassCreate(), __Pyx_Py3MetaclassPrepare(), __Pyx_PyObject_Call(), __Pyx_RefNannyImportAPI(), __Pyx_SetVtable(), __pyx_type_12pynestkernel_NESTEngine, __pyx_type_12pynestkernel_SLIDatum, __pyx_type_12pynestkernel_SLILiteral, __pyx_type___pyx_array, __pyx_type___pyx_memoryview, __pyx_type___pyx_memoryviewslice, __pyx_type___pyx_MemviewEnum, __pyx_vtable_12pynestkernel_SLIDatum, __pyx_vtable__memoryviewslice, __pyx_vtable_memoryview, __pyx_vtabptr_memoryview, __pyx_vtabstruct_12pynestkernel_SLIDatum::_set_datum, __pyx_vtabstruct_memoryview::assign_item_from_object, __pyx_vtabstruct_memoryview::convert_item_to_object, __pyx_vtabstruct_memoryview::get_item_pointer, __pyx_vtabstruct_memoryview::is_slice, __pyx_vtabstruct_memoryview::setitem_indexed, __pyx_vtabstruct_memoryview::setitem_slice_assign_scalar, and __pyx_vtabstruct_memoryview::setitem_slice_assignment.
static CYTHON_INLINE int resize (arrayobject * self, Py_ssize_t n) static
References nest::names::n.
Referenced by nest::RingBuffer::clear(), and nest::ListRingBuffer::clear().
static CYTHON_INLINE int resize_smart (arrayobject * self, Py_ssize_t n) static
References nest::names::n.
Referenced by __pyx_f_7cpython_5array_extend_buffer().
Variable Documentation
PyTypeObject* __pyx_array_type = 0 static
PyObject* __pyx_b static
Referenced by __Pyx_GetBuiltinName(), __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
PyObject* __pyx_builtin_Ellipsis static
Referenced by __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), and _unellipsify().
PyObject* __pyx_builtin_enumerate static
PyObject* __pyx_builtin_Exception static
PyObject* __pyx_builtin_id static
PyObject* __pyx_builtin_ImportError static
PyObject* __pyx_builtin_IndexError static
PyObject* __pyx_builtin_MemoryError static
PyObject* __pyx_builtin_range static
PyObject* __pyx_builtin_TypeError static
PyObject* __pyx_builtin_ValueError static
PyObject* __pyx_builtin_xrange static
const char* __pyx_cfilenm = __FILE__ static
Referenced by __Pyx_GetModuleGlobalName().
int __pyx_clineno = 0 static
Referenced by __pyx_array___cinit__(), __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array_10__setitem__(), __pyx_array_MemoryView_5array_6__getattr__(), __pyx_array_MemoryView_5array_8__getitem__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_array_new(), __pyx_convert_string_from_py_(), __pyx_convert_string_to_py_(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_f_7cpython_5array_clone(), __pyx_f_7cpython_5array_copy(), __pyx_f_7cpython_5array_extend(), __pyx_f_7cpython_5array_extend_buffer(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_InitCachedBuiltins(), __Pyx_InitCachedConstants(), __Pyx_InitGlobals(), __pyx_memoryview___cinit__(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_copy_object(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_item_pointer(), __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__(), __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__(), __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__(), __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__(), __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__(), __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_MemoryView_10memoryview_14__str__(), __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), __pyx_memoryview_MemoryView_10memoryview_18is_f_contig(), __pyx_memoryview_MemoryView_10memoryview_20copy(), __pyx_memoryview_MemoryView_10memoryview_22copy_fortran(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_memoryview_new(), __pyx_memoryview_setitem_indexed(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_slice_memviewslice(), __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__(), __pyx_memoryviewslice_assign_item_from_object(), __pyx_memoryviewslice_convert_item_to_object(), __pyx_memslice_transpose(), __pyx_memview_slice(), __pyx_MemviewEnum___init__(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pf_12pynestkernel_10SLILiteral_2__hash__(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), __pyx_pf_12pynestkernel_8SLIDatum_4__repr__(), __pyx_pf_7cpython_5array_5array___getbuffer__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), __pyx_pw_12pynestkernel_10SLILiteral_1__init__(), __pyx_pybuffer_index(), _unellipsify(), assert_direct_dimensions(), get_memview_MemoryView_5array_7memview___get__(), and PyInit_pynestkernel().
struct __Pyx_CodeObjectCache __pyx_code_cache = {0,0,NULL} static
PyObject* __pyx_d static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
char* __PYX_DEFAULT_STRING_ENCODING static
PyObject* __pyx_empty_bytes static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
PyObject* __pyx_empty_tuple static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_datum_to_object(), __Pyx_GetModuleGlobalName(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_tp_new_12pynestkernel_NESTEngine(), __pyx_tp_new_12pynestkernel_SLIDatum(), __pyx_tp_new_12pynestkernel_SLILiteral(), __pyx_tp_new_array(), __pyx_tp_new_Enum(), __pyx_tp_new_memoryview(), and PyInit_pynestkernel().
const char* __pyx_f[] static
Initial value:
= {
  "pynestkernel.pyx",
  "array.pxd",
  "stringsource",
  "stringsource",
  "stringsource",
  "type.pxd",
  "bool.pxd",
  "complex.pxd",
}
Referenced by __pyx_array___cinit__(), __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array_10__setitem__(), __pyx_array_MemoryView_5array_6__getattr__(), __pyx_array_MemoryView_5array_8__getitem__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_array_new(), __pyx_convert_string_from_py_(), __pyx_convert_string_to_py_(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_f_7cpython_5array_clone(), __pyx_f_7cpython_5array_copy(), __pyx_f_7cpython_5array_extend(), __pyx_f_7cpython_5array_extend_buffer(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_InitCachedBuiltins(), __Pyx_InitCachedConstants(), __Pyx_InitGlobals(), __pyx_memoryview___cinit__(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_copy_object(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_item_pointer(), __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__(), __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__(), __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__(), __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__(), __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__(), __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_MemoryView_10memoryview_14__str__(), __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), __pyx_memoryview_MemoryView_10memoryview_18is_f_contig(), __pyx_memoryview_MemoryView_10memoryview_20copy(), __pyx_memoryview_MemoryView_10memoryview_22copy_fortran(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_memoryview_new(), __pyx_memoryview_setitem_indexed(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_slice_memviewslice(), __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__(), __pyx_memoryviewslice_assign_item_from_object(), __pyx_memoryviewslice_convert_item_to_object(), __pyx_memslice_transpose(), __pyx_memview_slice(), __pyx_MemviewEnum___init__(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pf_12pynestkernel_10SLILiteral_2__hash__(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), __pyx_pf_12pynestkernel_8SLIDatum_4__repr__(), __pyx_pf_7cpython_5array_5array___getbuffer__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), __pyx_pw_12pynestkernel_10SLILiteral_1__init__(), __pyx_pybuffer_index(), _unellipsify(), assert_direct_dimensions(), get_memview_MemoryView_5array_7memview___get__(), and PyInit_pynestkernel().
const char* __pyx_filename static
Referenced by __pyx_array___cinit__(), __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array_10__setitem__(), __pyx_array_MemoryView_5array_6__getattr__(), __pyx_array_MemoryView_5array_8__getitem__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_array_new(), __pyx_convert_string_from_py_(), __pyx_convert_string_to_py_(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_f_7cpython_5array_clone(), __pyx_f_7cpython_5array_copy(), __pyx_f_7cpython_5array_extend(), __pyx_f_7cpython_5array_extend_buffer(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_InitCachedBuiltins(), __Pyx_InitCachedConstants(), __Pyx_InitGlobals(), __pyx_memoryview___cinit__(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_copy_object(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_item_pointer(), __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__(), __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__(), __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__(), __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__(), __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__(), __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_MemoryView_10memoryview_14__str__(), __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), __pyx_memoryview_MemoryView_10memoryview_18is_f_contig(), __pyx_memoryview_MemoryView_10memoryview_20copy(), __pyx_memoryview_MemoryView_10memoryview_22copy_fortran(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_memoryview_new(), __pyx_memoryview_setitem_indexed(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_slice_memviewslice(), __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__(), __pyx_memoryviewslice_assign_item_from_object(), __pyx_memoryviewslice_convert_item_to_object(), __pyx_memslice_transpose(), __pyx_memview_slice(), __pyx_MemviewEnum___init__(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pf_12pynestkernel_10SLILiteral_2__hash__(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), __pyx_pf_12pynestkernel_8SLIDatum_4__repr__(), __pyx_pf_7cpython_5array_5array___getbuffer__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), __pyx_pw_12pynestkernel_10SLILiteral_1__init__(), __pyx_pybuffer_index(), _unellipsify(), assert_direct_dimensions(), get_memview_MemoryView_5array_7memview___get__(), and PyInit_pynestkernel().
struct PyGetSetDef __pyx_getsets_12pynestkernel_SLIDatum[] static
Initial value:
= {
  {(char *)"dtype", __pyx_getprop_12pynestkernel_8SLIDatum_dtype, 0, 0, 0},
  {0, 0, 0, 0, 0}
}
struct PyGetSetDef __pyx_getsets_12pynestkernel_SLILiteral[] static
Initial value:
= {
  {(char *)"name", __pyx_getprop_12pynestkernel_10SLILiteral_name, 0, 0, 0},
  {0, 0, 0, 0, 0}
}
struct PyGetSetDef __pyx_getsets__memoryviewslice[] static
Initial value:
= {
  {(char *)"base", __pyx_getprop___pyx_memoryviewslice_base, 0, 0, 0},
  {0, 0, 0, 0, 0}
}
struct PyGetSetDef __pyx_getsets_array[] static
Initial value:
= {
  {(char *)"memview", __pyx_getprop___pyx_array_memview, 0, 0, 0},
  {0, 0, 0, 0, 0}
}
struct PyGetSetDef __pyx_getsets_memoryview[] static
Initial value:
= {
  {(char *)"T", __pyx_getprop___pyx_memoryview_T, 0, 0, 0},
  {(char *)"base", __pyx_getprop___pyx_memoryview_base, 0, 0, 0},
  {(char *)"shape", __pyx_getprop___pyx_memoryview_shape, 0, 0, 0},
  {(char *)"strides", __pyx_getprop___pyx_memoryview_strides, 0, 0, 0},
  {(char *)"suboffsets", __pyx_getprop___pyx_memoryview_suboffsets, 0, 0, 0},
  {(char *)"ndim", __pyx_getprop___pyx_memoryview_ndim, 0, 0, 0},
  {(char *)"itemsize", __pyx_getprop___pyx_memoryview_itemsize, 0, 0, 0},
  {(char *)"nbytes", __pyx_getprop___pyx_memoryview_nbytes, 0, 0, 0},
  {(char *)"size", __pyx_getprop___pyx_memoryview_size, 0, 0, 0},
  {0, 0, 0, 0, 0}
}
PyObject* __pyx_int_0 static
Referenced by __pyx_memview_slice(), and _unellipsify().
PyObject* __pyx_int_1 static
Referenced by __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__().
PyObject* __pyx_int_5 static
PyObject* __pyx_int_neg_1 static
char __pyx_k_[] = "" static
char __pyx_k_0[] = "{0}" static
long __pyx_k__27 static
double __pyx_k__28 static
long __pyx_k__29 static
double __pyx_k__30 static
long __pyx_k__31 static
double __pyx_k__32 static
long __pyx_k__33 static
double __pyx_k__34 static
long __pyx_k__35 static
double __pyx_k__36 static
long __pyx_k__37 static
double __pyx_k__38 static
long __pyx_k__39 static
double __pyx_k__40 static
char __pyx_k_All_dimensions_preceding_dimensi[] = "All dimensions preceding dimension %d must be indexed and not sliced" static
char __pyx_k_allocate_buffer[] = "allocate_buffer" static
char __pyx_k_argv[] = "argv" static
char __pyx_k_argv_can_t_be_empty[] = "argv can't be empty" static
char __pyx_k_array[] = "array" static
char __pyx_k_arraytype[] = "arraytype" static
char __pyx_k_base[] = "base" static
char __pyx_k_booltype[] = "booltype" static
char __pyx_k_Buffer_view_does_not_expose_stri[] = "Buffer view does not expose strides" static
char __pyx_k_c[] = "c" static
char __pyx_k_Can_only_create_a_buffer_that_is[] = "Can only create a buffer that is contiguous in memory." static
char __pyx_k_Cannot_index_with_type_s[] = "Cannot index with type '%s'" static
char __pyx_k_Cannot_transpose_memoryview_with[] = "Cannot transpose memoryview with indirect dimensions" static
char __pyx_k_class[] = "__class__" static
char __pyx_k_CONN_LEN[] = "CONN_LEN" static
char __pyx_k_connectiontype[] = "connectiontype" static
char __pyx_k_contiguous_and_direct[] = "<contiguous and direct>" static
char __pyx_k_contiguous_and_indirect[] = "<contiguous and indirect>" static
char __pyx_k_conversion_resulted_in_a_None_ob[] = "conversion resulted in a None object" static
char __pyx_k_conversion_resulted_in_a_null_po[] = "conversion resulted in a null pointer" static
char __pyx_k_couldn_t_allocate_argv_bytes[] = "couldn't allocate argv_bytes" static
char __pyx_k_d[] = "d" static
char __pyx_k_datum_is_a_null_pointer[] = "datum is a null pointer" static
char __pyx_k_dictionarytype[] = "dictionarytype" static
char __pyx_k_Dimension_d_is_not_direct[] = "Dimension %d is not direct" static
char __pyx_k_doc[] = "__doc__" static
char __pyx_k_doubletype[] = "doubletype" static
char __pyx_k_doublevectortype[] = "doublevectortype" static
char __pyx_k_dtype[] = "dtype" static
char __pyx_k_dtype_is_object[] = "dtype_is_object" static
char __pyx_k_Ellipsis[] = "Ellipsis" static
char __pyx_k_Empty_shape_tuple_for_cython_arr[] = "Empty shape tuple for cython.array" static
char __pyx_k_encode[] = "encode" static
char __pyx_k_engine_already_initialized[] = "engine already initialized" static
char __pyx_k_engine_uninitialized[] = "engine uninitialized" static
char __pyx_k_enumerate[] = "enumerate" static
char __pyx_k_error[] = "error" static
char __pyx_k_Exception[] = "Exception" static
char __pyx_k_failed_to_unpack_passed_connecti[] = "failed to unpack passed connection generator object" static
char __pyx_k_flags[] = "flags" static
char __pyx_k_float[] = "float_" static
char __pyx_k_floating[] = "floating" static
char __pyx_k_format[] = "format" static
char __pyx_k_fortran[] = "fortran" static
char __pyx_k_frombuffer[] = "frombuffer" static
char __pyx_k_getbuffer_obj_view_flags[] = "getbuffer(obj, view, flags)" static
char __pyx_k_got_differing_extents_in_dimensi[] = "got differing extents in dimension %d (got %d and %d)" static
char __pyx_k_id[] = "id" static
char __pyx_k_import[] = "__import__" static
char __pyx_k_ImportError[] = "ImportError" static
char __pyx_k_Index_out_of_bounds_axis_d[] = "Index out of bounds (axis %d)" static
char __pyx_k_IndexError[] = "IndexError" static
char __pyx_k_Indirect_dimensions_not_supporte[] = "Indirect dimensions not supported" static
char __pyx_k_int[] = "int_" static
char __pyx_k_integer[] = "integer" static
char __pyx_k_integertype[] = "integertype" static
char __pyx_k_interpreter_stack_is_empty[] = "interpreter stack is empty" static
char __pyx_k_intvectortype[] = "intvectortype" static
char __pyx_k_Invalid_mode_expected_c_or_fortr[] = "Invalid mode, expected 'c' or 'fortran', got %s" static
char __pyx_k_Invalid_shape_in_axis_d_d[] = "Invalid shape in axis %d: %d." static
char __pyx_k_issubdtype[] = "issubdtype" static
char __pyx_k_item[] = "item" static
char __pyx_k_items[] = "items" static
char __pyx_k_itemsize[] = "itemsize" static
char __pyx_k_itemsize_0_for_cython_array[] = "itemsize <= 0 for cython.array" static
char __pyx_k_l[] = "l" static
char __pyx_k_literaltype[] = "literaltype" static
char __pyx_k_main[] = "__main__" static
char __pyx_k_masktype[] = "masktype" static
char __pyx_k_MemoryError[] = "MemoryError" static
char __pyx_k_MemoryView_of_r_at_0x_x[] = "<MemoryView of %r at 0x%x>" static
char __pyx_k_MemoryView_of_r_object[] = "<MemoryView of %r object>" static
char __pyx_k_memview[] = "memview" static
char __pyx_k_metaclass[] = "__metaclass__" static
char __pyx_k_mode[] = "mode" static
char __pyx_k_module[] = "__module__" static
char __pyx_k_modulepath[] = "modulepath" static
char __pyx_k_name[] = "name" static
char __pyx_k_name_2[] = "__name__" static
char __pyx_k_ndarray[] = "ndarray" static
char __pyx_k_ndim[] = "ndim" static
char __pyx_k_NESTError[] = "NESTError" static
char __pyx_k_numpy[] = "numpy" static
char __pyx_k_O[] = "O" static
char __pyx_k_obj[] = "obj" static
char __pyx_k_only_vectors_of_integers_or_floa[] = "only vectors of integers or floats are supported" static
char __pyx_k_Out_of_bounds_on_buffer_access_a[] = "Out of bounds on buffer access (axis %d)" static
char __pyx_k_pack[] = "pack" static
char __pyx_k_parametertype[] = "parametertype" static
char __pyx_k_port[] = "port" static
char __pyx_k_prepare[] = "__prepare__" static
char __pyx_k_pynest[] = "pynest\000" static
Referenced by __pyx_pf_12pynestkernel_10NESTEngine_4init().
char __pyx_k_pynestkernel[] = "pynestkernel" static
char __pyx_k_pyx_getbuffer[] = "__pyx_getbuffer" static
char __pyx_k_pyx_releasebuffer[] = "__pyx_releasebuffer" static
char __pyx_k_pyx_vtable[] = "__pyx_vtable__" static
char __pyx_k_qualname[] = "__qualname__" static
char __pyx_k_range[] = "range" static
char __pyx_k_shape[] = "shape" static
char __pyx_k_size[] = "size" static
char __pyx_k_SLIDatum_0[] = "<SLIDatum: {0}>" static
char __pyx_k_SLIDatum_unassociated[] = "<SLIDatum: unassociated>" static
char __pyx_k_SLILiteral_0[] = "<SLILiteral: {0}>" static
char __pyx_k_source[] = "source" static
char __pyx_k_start[] = "start" static
char __pyx_k_step[] = "step" static
char __pyx_k_Step_may_not_be_zero_axis_d[] = "Step may not be zero (axis %d)" static
char __pyx_k_stop[] = "stop" static
char __pyx_k_strided_and_direct[] = "<strided and direct>" static
char __pyx_k_strided_and_direct_or_indirect[] = "<strided and direct or indirect>" static
char __pyx_k_strided_and_indirect[] = "<strided and indirect>" static
char __pyx_k_stringtype[] = "stringtype" static
char __pyx_k_struct[] = "struct" static
char __pyx_k_synapse_modelid[] = "synapse_modelid" static
char __pyx_k_target_thread[] = "target_thread" static
char __pyx_k_test[] = "__test__" static
char __pyx_k_TypeError[] = "TypeError" static
char __pyx_k_unable_to_allocate_array_data[] = "unable to allocate array data." static
char __pyx_k_unable_to_allocate_shape_and_str[] = "unable to allocate shape and strides." static
char __pyx_k_Unable_to_convert_item_to_object[] = "Unable to convert item to object" static
char __pyx_k_unknown_Python_type_0[] = "unknown Python type: {0}" static
char __pyx_k_unknown_SLI_datum_type_0[] = "unknown SLI datum type: {0}" static
char __pyx_k_unknown_SLI_type_0[] = "unknown SLI type: {0}" static
char __pyx_k_unpack[] = "unpack" static
char __pyx_k_ValueError[] = "ValueError" static
char __pyx_k_xrange[] = "xrange" static
PyObject* __pyx_kp_s_0 static
PyObject* __pyx_kp_s_argv_can_t_be_empty static
PyObject* __pyx_kp_s_Buffer_view_does_not_expose_stri static
PyObject* __pyx_kp_s_Can_only_create_a_buffer_that_is static
PyObject* __pyx_kp_s_Cannot_index_with_type_s static
PyObject* __pyx_kp_s_contiguous_and_direct static
PyObject* __pyx_kp_s_contiguous_and_indirect static
PyObject* __pyx_kp_s_conversion_resulted_in_a_None_ob static
PyObject* __pyx_kp_s_conversion_resulted_in_a_null_po static
PyObject* __pyx_kp_s_couldn_t_allocate_argv_bytes static
PyObject* __pyx_kp_s_datum_is_a_null_pointer static
PyObject* __pyx_kp_s_Empty_shape_tuple_for_cython_arr static
PyObject* __pyx_kp_s_engine_already_initialized static
PyObject* __pyx_kp_s_engine_uninitialized static
PyObject* __pyx_kp_s_failed_to_unpack_passed_connecti static
PyObject* __pyx_kp_s_got_differing_extents_in_dimensi static
PyObject* __pyx_kp_s_Indirect_dimensions_not_supporte static
PyObject* __pyx_kp_s_interpreter_stack_is_empty static
PyObject* __pyx_kp_s_Invalid_mode_expected_c_or_fortr static
PyObject* __pyx_kp_s_Invalid_shape_in_axis_d_d static
PyObject* __pyx_kp_s_itemsize_0_for_cython_array static
PyObject* __pyx_kp_s_MemoryView_of_r_at_0x_x static
PyObject* __pyx_kp_s_MemoryView_of_r_object static
PyObject* __pyx_kp_s_only_vectors_of_integers_or_floa static
PyObject* __pyx_kp_s_Out_of_bounds_on_buffer_access_a static
PyObject* __pyx_kp_s_SLIDatum_0 static
PyObject* __pyx_kp_s_SLIDatum_unassociated static
Referenced by __pyx_pf_12pynestkernel_8SLIDatum_4__repr__().
PyObject* __pyx_kp_s_SLILiteral_0 static
PyObject* __pyx_kp_s_strided_and_direct static
PyObject* __pyx_kp_s_strided_and_direct_or_indirect static
PyObject* __pyx_kp_s_strided_and_indirect static
PyObject* __pyx_kp_s_unable_to_allocate_array_data static
PyObject* __pyx_kp_s_unable_to_allocate_shape_and_str static
PyObject* __pyx_kp_s_Unable_to_convert_item_to_object static
PyObject* __pyx_kp_s_unknown_Python_type_0 static
PyObject* __pyx_kp_s_unknown_SLI_datum_type_0 static
PyObject* __pyx_kp_s_unknown_SLI_type_0 static
PyObject* __pyx_kp_u_ static
Referenced by __pyx_pf_12pynestkernel_8SLIDatum___cinit__().
int __pyx_lineno static
Referenced by __pyx_array___cinit__(), __pyx_array_getbuffer_MemoryView_5array_2__getbuffer__(), __pyx_array_MemoryView_5array_10__setitem__(), __pyx_array_MemoryView_5array_6__getattr__(), __pyx_array_MemoryView_5array_8__getitem__(), __pyx_array_MemoryView_5array___cinit__(), __pyx_array_new(), __pyx_convert_string_from_py_(), __pyx_convert_string_to_py_(), __pyx_f_12pynestkernel_python_object_to_datum(), __pyx_f_12pynestkernel_sli_array_to_object(), __pyx_f_12pynestkernel_sli_connection_to_object(), __pyx_f_12pynestkernel_sli_datum_to_object(), __pyx_f_12pynestkernel_sli_dict_to_object(), __pyx_f_7cpython_5array_clone(), __pyx_f_7cpython_5array_copy(), __pyx_f_7cpython_5array_extend(), __pyx_f_7cpython_5array_extend_buffer(), __pyx_fuse_0_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_0_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object(), __pyx_fuse_2_0__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_3_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __pyx_fuse_4_1__pyx_f_12pynestkernel_python_buffer_to_datum(), __Pyx_InitCachedBuiltins(), __Pyx_InitCachedConstants(), __Pyx_InitGlobals(), __pyx_memoryview___cinit__(), __pyx_memoryview_assign_item_from_object(), __pyx_memoryview_convert_item_to_object(), __pyx_memoryview_copy_contents(), __pyx_memoryview_copy_data_to_temp(), __pyx_memoryview_copy_object(), __pyx_memoryview_copy_object_from_slice(), __pyx_memoryview_err(), __pyx_memoryview_err_dim(), __pyx_memoryview_err_extents(), __pyx_memoryview_fromslice(), __pyx_memoryview_get_item_pointer(), __pyx_memoryview_get_itemsize_MemoryView_10memoryview_8itemsize___get__(), __pyx_memoryview_get_nbytes_MemoryView_10memoryview_6nbytes___get__(), __pyx_memoryview_get_ndim_MemoryView_10memoryview_4ndim___get__(), __pyx_memoryview_get_shape_MemoryView_10memoryview_5shape___get__(), __pyx_memoryview_get_size_MemoryView_10memoryview_4size___get__(), __pyx_memoryview_get_slice_from_memoryview(), __pyx_memoryview_get_strides_MemoryView_10memoryview_7strides___get__(), __pyx_memoryview_get_suboffsets_MemoryView_10memoryview_10suboffsets___get__(), __pyx_memoryview_is_slice(), __pyx_memoryview_MemoryView_10memoryview_12__repr__(), __pyx_memoryview_MemoryView_10memoryview_14__str__(), __pyx_memoryview_MemoryView_10memoryview_16is_c_contig(), __pyx_memoryview_MemoryView_10memoryview_18is_f_contig(), __pyx_memoryview_MemoryView_10memoryview_20copy(), __pyx_memoryview_MemoryView_10memoryview_22copy_fortran(), __pyx_memoryview_MemoryView_10memoryview_4__getitem__(), __pyx_memoryview_MemoryView_10memoryview_6__setitem__(), __pyx_memoryview_MemoryView_10memoryview___cinit__(), __pyx_memoryview_new(), __pyx_memoryview_setitem_indexed(), __pyx_memoryview_setitem_slice_assign_scalar(), __pyx_memoryview_setitem_slice_assignment(), __pyx_memoryview_slice_memviewslice(), __pyx_memoryview_transpose_MemoryView_10memoryview_1T___get__(), __pyx_memoryviewslice_assign_item_from_object(), __pyx_memoryviewslice_convert_item_to_object(), __pyx_memslice_transpose(), __pyx_memview_slice(), __pyx_MemviewEnum___init__(), __pyx_pf_12pynestkernel_10NESTEngine_10pop(), __pyx_pf_12pynestkernel_10NESTEngine_12push_connection_datums(), __pyx_pf_12pynestkernel_10NESTEngine_2__dealloc__(), __pyx_pf_12pynestkernel_10NESTEngine_4init(), __pyx_pf_12pynestkernel_10NESTEngine_6run(), __pyx_pf_12pynestkernel_10NESTEngine_8push(), __pyx_pf_12pynestkernel_10SLILiteral_2__hash__(), __pyx_pf_12pynestkernel_10SLILiteral_4__repr__(), __pyx_pf_12pynestkernel_10SLILiteral_6__str__(), __pyx_pf_12pynestkernel_10SLILiteral_8__richcmp__(), __pyx_pf_12pynestkernel_10SLILiteral___init__(), __pyx_pf_12pynestkernel_8SLIDatum_4__repr__(), __pyx_pf_7cpython_5array_5array___getbuffer__(), __pyx_pw_12pynestkernel_10NESTEngine_5init(), __pyx_pw_12pynestkernel_10SLILiteral_1__init__(), __pyx_pybuffer_index(), _unellipsify(), assert_direct_dimensions(), get_memview_MemoryView_5array_7memview___get__(), and PyInit_pynestkernel().
PyObject* __pyx_m static
Referenced by __Pyx_GetModuleGlobalName(), and PyInit_pynestkernel().
PyTypeObject* __pyx_memoryview_type = 0 static
Referenced by __pyx_memoryview_MemoryView_10memoryview___cinit__(), and PyInit_pynestkernel().
PyTypeObject* __pyx_memoryviewslice_type = 0 static
PyTypeObject* __pyx_MemviewEnum_type = 0 static
PyMethodDef __pyx_methods[] static
Initial value:
= {
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods_12pynestkernel_NESTEngine[] static
Initial value:
= {
  {__Pyx_NAMESTR("init"), (PyCFunction)__pyx_pw_12pynestkernel_10NESTEngine_5init, METH_VARARGS|METH_KEYWORDS, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("run"), (PyCFunction)__pyx_pw_12pynestkernel_10NESTEngine_7run, METH_O, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("push"), (PyCFunction)__pyx_pw_12pynestkernel_10NESTEngine_9push, METH_O, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("pop"), (PyCFunction)__pyx_pw_12pynestkernel_10NESTEngine_11pop, METH_NOARGS, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("push_connection_datums"), (PyCFunction)__pyx_pw_12pynestkernel_10NESTEngine_13push_connection_datums, METH_O, __Pyx_DOCSTR(0)},
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods_12pynestkernel_SLIDatum[] static
Initial value:
= {
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods_12pynestkernel_SLILiteral[] static
Initial value:
= {
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods__memoryviewslice[] static
Initial value:
= {
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods_array[] static
Initial value:
= {
  {__Pyx_NAMESTR("__getattr__"), (PyCFunction)__pyx_array___getattr__, METH_O|METH_COEXIST, __Pyx_DOCSTR(0)},
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods_Enum[] static
Initial value:
= {
  {0, 0, 0, 0}
}
PyMethodDef __pyx_methods_memoryview[] static
Initial value:
= {
  {__Pyx_NAMESTR("is_c_contig"), (PyCFunction)__pyx_memoryview_is_c_contig, METH_NOARGS, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("is_f_contig"), (PyCFunction)__pyx_memoryview_is_f_contig, METH_NOARGS, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("copy"), (PyCFunction)__pyx_memoryview_copy, METH_NOARGS, __Pyx_DOCSTR(0)},
  {__Pyx_NAMESTR("copy_fortran"), (PyCFunction)__pyx_memoryview_copy_fortran, METH_NOARGS, __Pyx_DOCSTR(0)},
  {0, 0, 0, 0}
}
Py_ssize_t __Pyx_minusones[] = {-1, -1, -1, -1, -1, -1, -1, -1} static
Referenced by __Pyx_GetModuleGlobalName().
int __pyx_module_is_main_pynestkernel = 0
struct PyModuleDef __pyx_moduledef static
Initial value:
= {
  #if PY_VERSION_HEX < 0x03020000
    { PyObject_HEAD_INIT(NULL) NULL, 0, NULL },
  #else
    PyModuleDef_HEAD_INIT,
  #endif
    __Pyx_NAMESTR("pynestkernel"),
    0,
    -1,
    __pyx_methods ,
    NULL,
    NULL,
    NULL,
    NULL
}
PyObject* __pyx_n_b_arraytype static
PyObject* __pyx_n_b_booltype static
PyObject* __pyx_n_b_connectiontype static
PyObject* __pyx_n_b_dictionarytype static
PyObject* __pyx_n_b_doubletype static
PyObject* __pyx_n_b_doublevectortype static
PyObject* __pyx_n_b_integertype static
PyObject* __pyx_n_b_intvectortype static
PyObject* __pyx_n_b_literaltype static
PyObject* __pyx_n_b_masktype static
PyObject* __pyx_n_b_O static
PyObject* __pyx_n_b_parametertype static
PyObject* __pyx_n_b_stringtype static
PyObject* __pyx_n_s_allocate_buffer static
Referenced by __pyx_array___cinit__().
PyObject* __pyx_n_s_argv static
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_5init().
PyObject* __pyx_n_s_array static
PyObject* __pyx_n_s_base static
PyObject* __pyx_n_s_c static
PyObject* __pyx_n_s_class static
PyObject* __pyx_n_s_CONN_LEN static
PyObject* __pyx_n_s_d static
PyObject* __pyx_n_s_doc static
PyObject* __pyx_n_s_dtype static
PyObject* __pyx_n_s_dtype_is_object static
Referenced by __pyx_memoryview___cinit__().
PyObject* __pyx_n_s_Ellipsis static
PyObject* __pyx_n_s_encode static
PyObject* __pyx_n_s_enumerate static
PyObject* __pyx_n_s_error static
PyObject* __pyx_n_s_Exception static
PyObject* __pyx_n_s_flags static
Referenced by __pyx_memoryview___cinit__().
PyObject* __pyx_n_s_float static
PyObject* __pyx_n_s_floating static
PyObject* __pyx_n_s_format static
Referenced by __pyx_array___cinit__().
PyObject* __pyx_n_s_fortran static
PyObject* __pyx_n_s_frombuffer static
PyObject* __pyx_n_s_id static
PyObject* __pyx_n_s_import static
PyObject* __pyx_n_s_ImportError static
PyObject* __pyx_n_s_IndexError static
PyObject* __pyx_n_s_int static
PyObject* __pyx_n_s_integer static
PyObject* __pyx_n_s_issubdtype static
PyObject* __pyx_n_s_item static
PyObject* __pyx_n_s_items static
PyObject* __pyx_n_s_itemsize static
Referenced by __pyx_array___cinit__().
PyObject* __pyx_n_s_l static
PyObject* __pyx_n_s_main static
PyObject* __pyx_n_s_MemoryError static
PyObject* __pyx_n_s_memview static
PyObject* __pyx_n_s_metaclass static
PyObject* __pyx_n_s_mode static
Referenced by __pyx_array___cinit__().
PyObject* __pyx_n_s_module static
PyObject* __pyx_n_s_modulepath static
Referenced by __pyx_pw_12pynestkernel_10NESTEngine_5init().
PyObject* __pyx_n_s_name static
Referenced by __pyx_MemviewEnum___init__(), and __pyx_pw_12pynestkernel_10SLILiteral_1__init__().
PyObject* __pyx_n_s_name_2 static
PyObject* __pyx_n_s_ndarray static
PyObject* __pyx_n_s_ndim static
PyObject* __pyx_n_s_NESTError static
PyObject* __pyx_n_s_numpy static
PyObject* __pyx_n_s_obj static
Referenced by __pyx_memoryview___cinit__().
PyObject* __pyx_n_s_pack static
PyObject* __pyx_n_s_prepare static
PyObject* __pyx_n_s_pynestkernel static
PyObject* __pyx_n_s_pyx_getbuffer static
PyObject* __pyx_n_s_pyx_releasebuffer static
PyObject* __pyx_n_s_pyx_vtable static
PyObject* __pyx_n_s_qualname static
PyObject* __pyx_n_s_range static
PyObject* __pyx_n_s_shape static
Referenced by __pyx_array___cinit__().
PyObject* __pyx_n_s_size static
PyObject* __pyx_n_s_start static
PyObject* __pyx_n_s_step static
PyObject* __pyx_n_s_stop static
PyObject* __pyx_n_s_struct static
PyObject* __pyx_n_s_test static
PyObject* __pyx_n_s_TypeError static
PyObject* __pyx_n_s_unpack static
PyObject* __pyx_n_s_ValueError static
PyObject* __pyx_n_s_xrange static
PyObject* __pyx_n_u_c static
Referenced by __pyx_array_MemoryView_5array___cinit__().
PyObject* __pyx_n_u_fortran static
Referenced by __pyx_array_MemoryView_5array___cinit__().
PyObject* __pyx_n_u_port static
PyObject* __pyx_n_u_source static
PyObject* __pyx_n_u_synapse_modelid static
PyObject* __pyx_n_u_target_thread static
PyTypeObject* __pyx_ptype_12pynestkernel_NESTEngine = 0 static
PyTypeObject* __pyx_ptype_12pynestkernel_SLIDatum = 0 static
PyTypeObject* __pyx_ptype_12pynestkernel_SLILiteral = 0 static
PyTypeObject* __pyx_ptype_7cpython_4bool_bool = 0 static
PyTypeObject* __pyx_ptype_7cpython_4type_type = 0 static
PyTypeObject* __pyx_ptype_7cpython_5array_array = 0 static
PyTypeObject* __pyx_ptype_7cpython_7complex_complex = 0 static
__Pyx_RefNannyAPIStruct* __Pyx_RefNanny = NULL static
__Pyx_StringTabEntry __pyx_string_tab[] static
int __Pyx_sys_getdefaultencoding_not_ascii static
Referenced by __Pyx_GetModuleGlobalName(), and __Pyx_init_sys_getdefaultencoding_params().
PyBufferProcs __pyx_tp_as_buffer_array static
Initial value:
= {
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  __pyx_array_getbuffer,
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0,
  #endif
}
PyBufferProcs __pyx_tp_as_buffer_memoryview static
Initial value:
= {
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_MAJOR_VERSION < 3
  0,
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  __pyx_memoryview_getbuffer,
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0,
  #endif
}
PyMappingMethods __pyx_tp_as_mapping_array static
Initial value:
= {
  0,
  __pyx_array___getitem__,
  __pyx_mp_ass_subscript_array,
}
PyMappingMethods __pyx_tp_as_mapping_memoryview static
Initial value:
= {
  __pyx_memoryview___len__,
  __pyx_memoryview___getitem__,
  __pyx_mp_ass_subscript_memoryview,
}
PySequenceMethods __pyx_tp_as_sequence_array static
Initial value:
= {
  0,
  0,
  0,
  __pyx_sq_item_array,
  0,
  0,
  0,
  0,
  0,
  0,
}
PySequenceMethods __pyx_tp_as_sequence_memoryview static
Initial value:
= {
  __pyx_memoryview___len__,
  0,
  0,
  __pyx_sq_item_memoryview,
  0,
  0,
  0,
  0,
  0,
  0,
}
PyObject* __pyx_tuple__10 static
PyObject* __pyx_tuple__11 static
PyObject* __pyx_tuple__12 static
PyObject* __pyx_tuple__13 static
PyObject* __pyx_tuple__14 static
PyObject* __pyx_tuple__15 static
PyObject* __pyx_tuple__16 static
PyObject* __pyx_tuple__17 static
PyObject* __pyx_tuple__18 static
PyObject* __pyx_tuple__19 static
PyObject* __pyx_tuple__2 static
PyObject* __pyx_tuple__20 static
PyObject* __pyx_tuple__21 static
PyObject* __pyx_tuple__22 static
PyObject* __pyx_tuple__23 static
PyObject* __pyx_tuple__24 static
PyObject* __pyx_tuple__25 static
PyObject* __pyx_tuple__26 static
PyObject* __pyx_tuple__3 static
PyObject* __pyx_tuple__4 static
PyObject* __pyx_tuple__41 static
PyObject* __pyx_tuple__42 static
PyObject* __pyx_tuple__43 static
PyObject* __pyx_tuple__44 static
PyObject* __pyx_tuple__45 static
PyObject* __pyx_tuple__5 static
PyObject* __pyx_tuple__6 static
PyObject* __pyx_tuple__7 static
PyObject* __pyx_tuple__8 static
PyObject* __pyx_tuple__9 static
PyTypeObject __pyx_type_12pynestkernel_NESTEngine static
Referenced by PyInit_pynestkernel().
PyTypeObject __pyx_type_12pynestkernel_SLIDatum static
Referenced by PyInit_pynestkernel().
PyTypeObject __pyx_type_12pynestkernel_SLILiteral static
Referenced by PyInit_pynestkernel().
PyTypeObject __pyx_type___pyx_array static
Referenced by PyInit_pynestkernel().
PyTypeObject __pyx_type___pyx_memoryview static
Referenced by PyInit_pynestkernel().
PyTypeObject __pyx_type___pyx_memoryviewslice static
Referenced by PyInit_pynestkernel().
PyTypeObject __pyx_type___pyx_MemviewEnum static
Referenced by PyInit_pynestkernel().
__Pyx_TypeInfo __Pyx_TypeInfo_double = { "double", NULL, sizeof(double), { 0 }, 0, 'R', 0, 0 } static
__Pyx_TypeInfo __Pyx_TypeInfo_float = { "float", NULL, sizeof(float), { 0 }, 0, 'R', 0, 0 } static
__Pyx_TypeInfo __Pyx_TypeInfo_int = { "int", NULL, sizeof(int), { 0 }, 0, IS_UNSIGNED(int) ? 'U' : 'I', IS_UNSIGNED(int), 0 } static
__Pyx_TypeInfo __Pyx_TypeInfo_long = { "long", NULL, sizeof(long), { 0 }, 0, IS_UNSIGNED(long) ? 'U' : 'I', IS_UNSIGNED(long), 0 } static
PyObject* __pyx_v_12pynestkernel_ARRAY_DOUBLE = 0 static
Referenced by __pyx_fuse_1_1__pyx_f_12pynestkernel_sli_vector_to_object().
PyObject* __pyx_v_12pynestkernel_ARRAY_LONG = 0 static
Referenced by __pyx_f_12pynestkernel_sli_connection_to_object(), and __pyx_fuse_0_0__pyx_f_12pynestkernel_sli_vector_to_object().
PyObject* __pyx_v_12pynestkernel_CONN_NAME_PRT = 0 static
PyObject* __pyx_v_12pynestkernel_CONN_NAME_SRC = 0 static
PyObject* __pyx_v_12pynestkernel_CONN_NAME_SYN = 0 static
PyObject* __pyx_v_12pynestkernel_CONN_NAME_THREAD = 0 static
int __pyx_v_12pynestkernel_HAVE_NUMPY static
Referenced by __pyx_f_12pynestkernel_python_object_to_datum().
std::string __pyx_v_12pynestkernel_SLI_TYPE_ARRAY static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_BOOL static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_CONNECTION static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_DICTIONARY static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_DOUBLE static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_INTEGER static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_LITERAL static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_MASK static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_PARAMETER static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_STRING static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_VECTOR_DOUBLE static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
std::string __pyx_v_12pynestkernel_SLI_TYPE_VECTOR_INT static
Referenced by __pyx_f_12pynestkernel_sli_datum_to_object().
struct __pyx_vtabstruct_12pynestkernel_SLIDatum __pyx_vtable_12pynestkernel_SLIDatum static
Referenced by PyInit_pynestkernel().
struct __pyx_vtabstruct__memoryviewslice __pyx_vtable__memoryviewslice static
Referenced by PyInit_pynestkernel().
struct __pyx_vtabstruct_memoryview __pyx_vtable_memoryview static
Referenced by PyInit_pynestkernel().
struct __pyx_vtabstruct_12pynestkernel_SLIDatum* __pyx_vtabptr_12pynestkernel_SLIDatum static
Referenced by __pyx_tp_new_12pynestkernel_SLIDatum().
struct __pyx_vtabstruct__memoryviewslice* __pyx_vtabptr__memoryviewslice static
struct __pyx_vtabstruct_memoryview* __pyx_vtabptr_memoryview static
Referenced by __pyx_tp_new_memoryview(), and PyInit_pynestkernel().
Py_ssize_t __Pyx_zeros[] = {0, 0, 0, 0, 0, 0, 0, 0} static
Referenced by __Pyx_GetModuleGlobalName().
PyObject* contiguous = 0 static
PyObject* generic = 0 static
PyObject* indirect = 0 static
PyObject* indirect_contiguous = 0 static
PyObject* strided = 0 static