NEST: randomtest.cpp File Reference
randomtest.cpp File Reference
Functions
void printres (double mean, double sdev, double dt)
void rungen (librandom::RngPtr rng, const unsigned long N)
void rundev (librandom::RandomDev *rnd, const unsigned long N)
template<typename NumberGenerator >
void register_rng (const std::string &name, DictionaryDatum &dict)
int main (void)
Variables
const unsigned long Ngen = 1000000UL
const unsigned long Ndev = 1000000UL
const unsigned long seed = 1234567890UL
Function Documentation
int main (void)
References librandom::GslRandomGen::add_gsl_rngs(), librandom::RandomGen::DefaultSeed, Ndev, Ngen, printres(), rundev(), rungen(), and seed.
void printres (double mean, double sdev, double dt)
Referenced by main(), rundev(), and rungen().
template<typename NumberGenerator > void register_rng (const std::string & name, DictionaryDatum & dict)
void rundev (librandom::RandomDev * rnd, const unsigned long N)
References nest::names::dt, nest::names::mean, nest::names::N, printres(), and nest::names::x.
Referenced by main().
void rungen (librandom::RngPtr rng, const unsigned long N)
References nest::names::dt, nest::names::mean, nest::names::N, printres(), and nest::names::x.
Referenced by main().
Variable Documentation
const unsigned long Ndev = 1000000UL
Referenced by main().
const unsigned long Ngen = 1000000UL
Referenced by main().
const unsigned long seed = 1234567890UL
Referenced by RandomNumbers::CreateRNGFunction::execute(), FilesystemModule::TmpNamFunction::execute(), RandomNumbers::SeedFunction::execute(), main(), and nest::Scheduler::prepare_nodes().