NEST: sliarray.cc File Reference
sliarray.cc File Reference
Functions
template<class T , class D >
static void eq_execute (SLIInterpreter *i)
Function Documentation
template<class T , class D > static void eq_execute (SLIInterpreter * i) static
References SLIInterpreter::ArgumentTypeError, Token::datum(), SLIInterpreter::EStack, TokenStack::load(), SLIInterpreter::OStack, TokenStack::pick(), TokenStack::pop(), TokenStack::push_by_pointer(), SLIInterpreter::raiseerror(), and SLIInterpreter::StackUnderflowError.