NEST: slicontrol.cc File Reference
slicontrol.cc File Reference
Functions
void init_slicontrol (SLIInterpreter *i)
Variables
const SetGuardFunction setguardfunction
const RemoveGuardFunction removeguardfunction
const Backtrace_onFunction backtrace_onfunction
const Backtrace_offFunction backtrace_offfunction
const OStackdumpFunction ostackdumpfunction
const EStackdumpFunction estackdumpfunction
const LoopFunction loopfunction
const ExitFunction exitfunction
const QuitFunction quitfunction
const IfFunction iffunction
const IfelseFunction ifelsefunction
const RepeatFunction repeatfunction
const CloseinputFunction closeinputfunction
const StoppedFunction stoppedfunction
const StopFunction stopfunction
const CurrentnameFunction currentnamefunction
const IparsestdinFunction iparsestdinfunction
const ParsestdinFunction parsestdinfunction
const IparseFunction iparsefunction
const DefFunction deffunction
const SetFunction setfunction
const LoadFunction loadfunction
const LookupFunction lookupfunction
const ForFunction forfunction
const Forall_aFunction forall_afunction
const Forall_iterFunction forall_iterfunction
const Forallindexed_aFunction forallindexed_afunction
const Forallindexed_sFunction forallindexed_sfunction
const Forall_sFunction forall_sfunction
const RaiseerrorFunction raiseerrorfunction
const PrinterrorFunction printerrorfunction
const RaiseagainFunction raiseagainfunction
const CyclesFunction cyclesfunction
const CodeAccessedFunction codeaccessedfunction
const CodeExecutedFunction codeexecutedfunction
const ExecFunction execfunction
const TypeinfoFunction typeinfofunction
const SwitchFunction switchfunction
const SwitchdefaultFunction switchdefaultfunction
const CaseFunction casefunction
const CounttomarkFunction counttomarkfunction
const PclocksFunction pclocksfunction
const PclockspersecFunction pclockspersecfunction
const PgetrusageFunction pgetrusagefunction
const TimeFunction timefunction
const Sleep_dFunction sleep_dfunction
const Sleep_iFunction sleep_ifunction
const Token_sFunction token_sfunction
const Token_isFunction token_isfunction
const Symbol_sFunction symbol_sfunction
const SetVerbosityFunction setverbosityfunction
const VerbosityFunction verbosityfunction
const MessageFunction messagefunction
const NoopFunction noopfunction
const StartFunction startfunction
const DebugOnFunction debugonfunction
const DebugOffFunction debugofffunction
const DebugFunction debugfunction
Function Documentation
void init_slicontrol (SLIInterpreter * i)
References SLIInterpreter::createcommand(), SLIInterpreter::def(), SLIInterpreter::false_name, SLIInterpreter::istopped_name, SLIInterpreter::mark_name, SLIInterpreter::newerror_name, SLIInterpreter::recordstacks_name, and SLIInterpreter::true_name.
Referenced by SLIInterpreter::initexternals().
Variable Documentation
const Backtrace_offFunction backtrace_offfunction
const Backtrace_onFunction backtrace_onfunction
const CaseFunction casefunction
const CloseinputFunction closeinputfunction
const CodeAccessedFunction codeaccessedfunction
const CodeExecutedFunction codeexecutedfunction
const CounttomarkFunction counttomarkfunction
const CurrentnameFunction currentnamefunction
const CyclesFunction cyclesfunction
const DebugFunction debugfunction
const DebugOffFunction debugofffunction
const DebugOnFunction debugonfunction
const DefFunction deffunction
const EStackdumpFunction estackdumpfunction
const ExecFunction execfunction
const ExitFunction exitfunction
const Forall_aFunction forall_afunction
const Forall_iterFunction forall_iterfunction
const Forall_sFunction forall_sfunction
const Forallindexed_aFunction forallindexed_afunction
const Forallindexed_sFunction forallindexed_sfunction
const ForFunction forfunction
const IfelseFunction ifelsefunction
const IfFunction iffunction
const IparseFunction iparsefunction
const IparsestdinFunction iparsestdinfunction
const LoadFunction loadfunction
const LookupFunction lookupfunction
const LoopFunction loopfunction
const MessageFunction messagefunction
const NoopFunction noopfunction
const OStackdumpFunction ostackdumpfunction
const ParsestdinFunction parsestdinfunction
const PclocksFunction pclocksfunction
const PclockspersecFunction pclockspersecfunction
const PgetrusageFunction pgetrusagefunction
const PrinterrorFunction printerrorfunction
const QuitFunction quitfunction
const RaiseagainFunction raiseagainfunction
const RaiseerrorFunction raiseerrorfunction
const RemoveGuardFunction removeguardfunction
const RepeatFunction repeatfunction
const SetFunction setfunction
const SetGuardFunction setguardfunction
const SetVerbosityFunction setverbosityfunction
const Sleep_dFunction sleep_dfunction
const Sleep_iFunction sleep_ifunction
const StartFunction startfunction
const StopFunction stopfunction
const StoppedFunction stoppedfunction
const SwitchdefaultFunction switchdefaultfunction
const SwitchFunction switchfunction
const Symbol_sFunction symbol_sfunction
const TimeFunction timefunction
const Token_isFunction token_isfunction
const Token_sFunction token_sfunction
const TypeinfoFunction typeinfofunction
const VerbosityFunction verbosityfunction