NEST: sparsetable.h File Reference
sparsetable.h File Reference
Classes
class table_element_adaptor< tabletype >
class table_iterator< tabletype >
class const_table_iterator< tabletype >
class two_d_iterator< containertype >
class const_two_d_iterator< containertype >
class destructive_two_d_iterator< containertype >
class sparsegroup< T, GROUP_SIZE, Alloc >
class sparsegroup< T, GROUP_SIZE, Alloc >::alloc_impl< A >
class sparsegroup< T, GROUP_SIZE, Alloc >::alloc_impl< libc_allocator_with_realloc< A > >
class sparsegroup< T, GROUP_SIZE, Alloc >::Settings
class sparsetable< T, GROUP_SIZE, Alloc >
class sparsetable< T, GROUP_SIZE, Alloc >::Settings
Namespaces
base
Typedefs
typedef uint16_t u_int16_t
typedef __int16 int16_t
Functions
template<class T >
table_iterator< T > operator+ (typename table_iterator< T >::difference_type i, table_iterator< T > it)
template<class T >
const_table_iterator< T > operator+ (typename const_table_iterator< T >::difference_type i, const_table_iterator< T > it)
template<class T , u_int16_t GROUP_SIZE, class Alloc >
void swap (sparsegroup< T, GROUP_SIZE, Alloc > &x, sparsegroup< T, GROUP_SIZE, Alloc > &y)
template<class T , u_int16_t GROUP_SIZE, class Alloc >
void swap (sparsetable< T, GROUP_SIZE, Alloc > &x, sparsetable< T, GROUP_SIZE, Alloc > &y)
Variables
static const u_int16_t DEFAULT_SPARSEGROUP_SIZE = 48
Typedef Documentation
typedef short int int16_t
typedef unsigned short int u_int16_t
Function Documentation
template<class T > table_iterator<T> operator+ (typename table_iterator< T >::difference_type i, table_iterator< T > it)
template<class T > const_table_iterator<T> operator+ (typename const_table_iterator< T >::difference_type i, const_table_iterator< T > it)
template<class T , u_int16_t GROUP_SIZE, class Alloc > void swap (sparsegroup< T, GROUP_SIZE, Alloc > & x, sparsegroup< T, GROUP_SIZE, Alloc > & y) inline
References sparsegroup< T, GROUP_SIZE, Alloc >::swap().
Referenced by nest::sinusoidal_gamma_generator::init_buffers_(), Token::swap(), TokenArray::swap(), sparsegroup< T, GROUP_SIZE, Alloc >::swap(), and sparsetable< T, GROUP_SIZE, Alloc >::swap().
template<class T , u_int16_t GROUP_SIZE, class Alloc > void swap (sparsetable< T, GROUP_SIZE, Alloc > & x, sparsetable< T, GROUP_SIZE, Alloc > & y) inline
References sparsetable< T, GROUP_SIZE, Alloc >::swap().
Variable Documentation
const u_int16_t DEFAULT_SPARSEGROUP_SIZE = 48 static