NEST: __pyx_vtabstruct_memoryview Struct Reference
__pyx_vtabstruct_memoryview Struct Reference
Public Attributes
char *(* get_item_pointer)(struct __pyx_memoryview_obj *, PyObject *)
PyObject *(* is_slice)(struct __pyx_memoryview_obj *, PyObject *)
PyObject *(* setitem_slice_assignment)(struct __pyx_memoryview_obj *, PyObject *, PyObject *)
PyObject *(* setitem_slice_assign_scalar)(struct __pyx_memoryview_obj *, struct __pyx_memoryview_obj *, PyObject *)
PyObject *(* setitem_indexed)(struct __pyx_memoryview_obj *, PyObject *, PyObject *)
PyObject *(* convert_item_to_object)(struct __pyx_memoryview_obj *, char *)
PyObject *(* assign_item_from_object)(struct __pyx_memoryview_obj *, char *, PyObject *)
Member Data Documentation
PyObject*(* __pyx_vtabstruct_memoryview::assign_item_from_object)(struct __pyx_memoryview_obj *, char *, PyObject *)
Referenced by __pyx_memoryviewslice_assign_item_from_object(), and PyInit_pynestkernel().
PyObject*(* __pyx_vtabstruct_memoryview::convert_item_to_object)(struct __pyx_memoryview_obj *, char *)
Referenced by __pyx_memoryviewslice_convert_item_to_object(), and PyInit_pynestkernel().
char*(* __pyx_vtabstruct_memoryview::get_item_pointer)(struct __pyx_memoryview_obj *, PyObject *)
Referenced by PyInit_pynestkernel().
PyObject*(* __pyx_vtabstruct_memoryview::is_slice)(struct __pyx_memoryview_obj *, PyObject *)
Referenced by PyInit_pynestkernel().
PyObject*(* __pyx_vtabstruct_memoryview::setitem_indexed)(struct __pyx_memoryview_obj *, PyObject *, PyObject *)
Referenced by PyInit_pynestkernel().
PyObject*(* __pyx_vtabstruct_memoryview::setitem_slice_assign_scalar)(struct __pyx_memoryview_obj *, struct __pyx_memoryview_obj *, PyObject *)
Referenced by PyInit_pynestkernel().
PyObject*(* __pyx_vtabstruct_memoryview::setitem_slice_assignment)(struct __pyx_memoryview_obj *, PyObject *, PyObject *)
Referenced by PyInit_pynestkernel().
The documentation for this struct was generated from the following file:
pynestkernel.cpp