NEST: nest::hh_psc_alpha::State_ Struct Reference
nest::hh_psc_alpha::State_ Struct Reference
State variables of the model.
#include <hh_psc_alpha.h>
Public Types
enum StateVecElems {
V_M = 0, HH_M, HH_H, HH_N,
DI_EXC, I_EXC, DI_INH, I_INH,
STATE_VEC_SIZE
}
Enumeration identifying elements in state array State_::y_.
Public Member Functions
State_ (const Parameters_ &)
Default initialization.
State_ (const State_ &)
State_ & operator= (const State_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &)
Public Attributes
double_t y_ [STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
int_t r_
number of refractory steps remaining
Detailed Description
State variables of the model.
Note
Copy constructor and assignment operator required because of C-style array.
Member Enumeration Documentation
enum nest::hh_psc_alpha::State_::StateVecElems
Enumeration identifying elements in state array State_::y_.
The state vector must be passed to GSL as a C array. This enum identifies the elements of the vector. It must be public to be accessible from the iteration function.
Enumerator
V_M
HH_M
HH_H
HH_N
DI_EXC
I_EXC
DI_INH
I_INH
STATE_VEC_SIZE
Constructor & Destructor Documentation
nest::hh_psc_alpha::State_::State_ (const Parameters_ &)
Default initialization.
References HH_H, HH_M, HH_N, STATE_VEC_SIZE, and y_.
nest::hh_psc_alpha::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::hh_psc_alpha::State_::get (DictionaryDatum & d) const
References nest::names::Act_h, nest::names::Act_m, nest::names::d, nest::names::Inact_n, and nest::names::V_m.
Referenced by nest::hh_psc_alpha::get_status().
nest::hh_psc_alpha::State_ & nest::hh_psc_alpha::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::hh_psc_alpha::State_::set (const DictionaryDatum & d)
References nest::names::Act_h, nest::names::Act_m, nest::names::d, nest::names::Inact_n, and nest::names::V_m.
Referenced by nest::hh_psc_alpha::set_status().
Member Data Documentation
int_t nest::hh_psc_alpha::State_::r_
number of refractory steps remaining
Referenced by operator=().
double_t nest::hh_psc_alpha::State_::y_[STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
Referenced by nest::hh_psc_alpha::get_y_elem_(), operator=(), and State_().
The documentation for this struct was generated from the following files:
hh_psc_alpha.h
hh_psc_alpha.cpp