NEST: nest::sinusoidal_poisson_generator::Parameters_ Struct Reference
nest::sinusoidal_poisson_generator::Parameters_ Struct Reference
Public Member Functions
Parameters_ ()
Sets default parameter values.
Parameters_ (const Parameters_ &)
Parameters_ & operator= (const Parameters_ &p)
void get (DictionaryDatum &) const
Store current values in dictionary.
void set (const DictionaryDatum &, const sinusoidal_poisson_generator &)
Set values from dicitonary.
Public Attributes
double_t om_
temporal frequency in radian/ms.
double_t phi_
phase in radian
double_t dc_
DC amplitude in spikes/s.
double_t ac_
AC amplitude in spikes/s.
bool individual_spike_trains_
Emit individual spike trains for each target, or same for all?
Constructor & Destructor Documentation
nest::sinusoidal_poisson_generator::Parameters_::Parameters_ ()
Sets default parameter values.
nest::sinusoidal_poisson_generator::Parameters_::Parameters_ (const Parameters_ & p)
Member Function Documentation
void nest::sinusoidal_poisson_generator::Parameters_::get (DictionaryDatum & d) const
Store current values in dictionary.
References nest::names::ac, nest::names::dc, nest::names::freq, nest::names::individual_spike_trains, nest::names::phi, and numerics::pi.
Referenced by nest::sinusoidal_poisson_generator::get_status().
nest::sinusoidal_poisson_generator::Parameters_ & nest::sinusoidal_poisson_generator::Parameters_::operator= (const Parameters_ & p)
References ac_, dc_, individual_spike_trains_, om_, and phi_.
void nest::sinusoidal_poisson_generator::Parameters_::set (const DictionaryDatum & d, const sinusoidal_poisson_generator & n)
Set values from dicitonary.
Note
State is passed so that the position can be reset if the spike_times_ vector has been filled with new data.
References nest::names::ac, nest::names::d, nest::names::dc, nest::names::freq, nest::names::individual_spike_trains, nest::Node::is_model_prototype(), nest::names::phi, and numerics::pi.
Referenced by nest::sinusoidal_poisson_generator::set_status().
Member Data Documentation
double_t nest::sinusoidal_poisson_generator::Parameters_::ac_
AC amplitude in spikes/s.
Referenced by operator=().
double_t nest::sinusoidal_poisson_generator::Parameters_::dc_
DC amplitude in spikes/s.
Referenced by operator=().
bool nest::sinusoidal_poisson_generator::Parameters_::individual_spike_trains_
Emit individual spike trains for each target, or same for all?
Referenced by nest::sinusoidal_poisson_generator::has_proxies(), and operator=().
double_t nest::sinusoidal_poisson_generator::Parameters_::om_
temporal frequency in radian/ms.
Referenced by operator=().
double_t nest::sinusoidal_poisson_generator::Parameters_::phi_
phase in radian
Referenced by operator=().
The documentation for this struct was generated from the following files:
sinusoidal_poisson_generator.h
sinusoidal_poisson_generator.cpp