NEST: nest::spike_generator::Parameters_ Struct Reference
nest::spike_generator::Parameters_ Struct Reference
Public Member Functions
Parameters_ ()
Sets default parameter values.
Parameters_ (const Parameters_ &)
Recalibrate all times.
void get (DictionaryDatum &) const
Store current values in dictionary.
void set (const DictionaryDatum &, State_ &, const Time &, const Time &)
Set values from dicitonary.
void assert_valid_spike_time_and_insert_ (double, const Time &, const Time &)
Insert spike time to arrays, throw BadProperty for invalid spike times.
Public Attributes
std::vector< Time > spike_stamps_
Spike time stamp as Time, rel to origin_.
std::vector< double > spike_offsets_
Spike time offset, if using precise_times_.
std::vector< double > spike_weights_
Spike weights as double.
bool precise_times_
Interpret spike times as precise, i.e. send as step and offset.
bool allow_offgrid_spikes_
Allow and round up spikes not on steps; irrelevant if precise_times_.
bool shift_now_spikes_
Shift spike times at present to next step.
Constructor & Destructor Documentation
nest::spike_generator::Parameters_::Parameters_ ()
Sets default parameter values.
nest::spike_generator::Parameters_::Parameters_ (const Parameters_ & op)
Recalibrate all times.
Member Function Documentation
void nest::spike_generator::Parameters_::assert_valid_spike_time_and_insert_ (double t, const Time & origin, const Time & now)
Insert spike time to arrays, throw BadProperty for invalid spike times.
Parameters
spike time, ms
origin
current simulation time
References nest::Time::advance(), assert(), nest::Time::get_ms(), nest::Time::is_grid_time(), nest::Time::ms, nest::Time::ms_stamp, nest::names::offset, and nest::names::t_spike.
void nest::spike_generator::Parameters_::get (DictionaryDatum & d) const
Store current values in dictionary.
References assert(), nest::names::n, nest::names::precise_times, and nest::names::spike_times.
Referenced by nest::spike_generator::get_status().
void nest::spike_generator::Parameters_::set (const DictionaryDatum & d, State_ & s, const Time & origin, const Time & now)
Set values from dicitonary.
Note
State is passed so that the position can be reset if the spike_times_ or spike_weights_ vector has been filled with new data, or if the origin was reset.
References nest::names::d, nest::names::origin, nest::spike_generator::State_::position_, nest::names::precise_times, and nest::names::spike_times.
Referenced by nest::spike_generator::set_status().
Member Data Documentation
bool nest::spike_generator::Parameters_::allow_offgrid_spikes_
Allow and round up spikes not on steps; irrelevant if precise_times_.
bool nest::spike_generator::Parameters_::precise_times_
Interpret spike times as precise, i.e. send as step and offset.
bool nest::spike_generator::Parameters_::shift_now_spikes_
Shift spike times at present to next step.
std::vector<double> nest::spike_generator::Parameters_::spike_offsets_
Spike time offset, if using precise_times_.
std::vector<Time> nest::spike_generator::Parameters_::spike_stamps_
Spike time stamp as Time, rel to origin_.
std::vector<double> nest::spike_generator::Parameters_::spike_weights_
Spike weights as double.
The documentation for this struct was generated from the following files:
spike_generator.h
spike_generator.cpp