NEST: nest::mip_generator::Parameters_ Struct Reference
nest::mip_generator::Parameters_ Struct Reference
Store independent parameters of the model.
Public Member Functions
Parameters_ ()
Sets default parameter values.
Parameters_ (const Parameters_ &)
void get (DictionaryDatum &) const
Store current values in dictionary.
void set (const DictionaryDatum &)
Set values from dicitonary.
Public Attributes
double_t rate_
process rate in Hz
double_t p_copy_
copy probability for each spike in the mother process
ulong_t mother_seed_
seed of the mother process
librandom::RngPtr rng_
random number generator for mother process
Detailed Description
Store independent parameters of the model.
Mother RNG is a parameter since it can be changed. Not entirely in keeping with persistence rules, since it changes state during updates. But okay in the sense that it thus is not reset on ResetNetwork. Should go once we have proper global RNG scheme.
Constructor & Destructor Documentation
nest::mip_generator::Parameters_::Parameters_ ()
Sets default parameter values.
References librandom::RandomGen::create_knuthlfg_rng(), mother_seed_, and rng_.
nest::mip_generator::Parameters_::Parameters_ (const Parameters_ & p)
References mother_seed_, and rng_.
Member Function Documentation
void nest::mip_generator::Parameters_::get (DictionaryDatum & d) const
Store current values in dictionary.
References nest::names::mother_seed, nest::names::p_copy, and nest::names::rate.
Referenced by nest::mip_generator::get_status().
void nest::mip_generator::Parameters_::set (const DictionaryDatum & d)
Set values from dicitonary.
References nest::names::d, nest::names::mother_rng, nest::names::mother_seed, nest::names::p_copy, and nest::names::rate.
Referenced by nest::mip_generator::set_status().
Member Data Documentation
ulong_t nest::mip_generator::Parameters_::mother_seed_
seed of the mother process
Referenced by Parameters_().
double_t nest::mip_generator::Parameters_::p_copy_
copy probability for each spike in the mother process
double_t nest::mip_generator::Parameters_::rate_
process rate in Hz
librandom::RngPtr nest::mip_generator::Parameters_::rng_
random number generator for mother process
Referenced by Parameters_().
The documentation for this struct was generated from the following files:
mip_generator.h
mip_generator.cpp