NEST: nest::correlation_detector::State_ Struct Reference
nest::correlation_detector::State_ Struct Reference
Public Member Functions
State_ ()
initialize default state
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &, bool)
void reset (const Parameters_ &)
Public Attributes
std::vector< long_t > n_events_
spike counters
std::vector< SpikelistType > incoming_
incoming spikes, sorted
std::vector< double_t > histogram_
Weighted histogram.
std::vector< double_t > histogram_correction_
used for Kahan summation algorithm
std::vector< long_t > count_histogram_
Unweighted histogram.
Detailed Description
Todo:
Is there a replacement for std::list that allows fast insertion inside, fast deletion at the beginning, and maintains sorting?
Note
Constructed with empty structures, which are set to proper sizes by init_buffers_().
State_ only contains read-out values, so we copy-construct using the default c'tor.
Constructor & Destructor Documentation
nest::correlation_detector::State_::State_ ()
initialize default state
Member Function Documentation
void nest::correlation_detector::State_::get (DictionaryDatum & d) const
References nest::names::count_histogram, nest::names::histogram, nest::names::histogram_correction, and nest::names::n_events.
void nest::correlation_detector::State_::reset (const Parameters_ & p)
References assert(), nest::correlation_detector::Parameters_::delta_tau_, nest::Time::get_steps(), nest::Time::is_multiple_of(), and nest::correlation_detector::Parameters_::tau_max_.
void nest::correlation_detector::State_::set (const DictionaryDatum & d, const Parameters_ & p, bool reset_required)
Parameters
bool if true, force state reset
References nest::names::n_events, and updateValue().
Referenced by nest::correlation_detector::set_status().
Member Data Documentation
std::vector<long_t> nest::correlation_detector::State_::count_histogram_
Unweighted histogram.
std::vector<double_t> nest::correlation_detector::State_::histogram_
Weighted histogram.
Note
Data type is double to accomodate weights.
std::vector<double_t> nest::correlation_detector::State_::histogram_correction_
used for Kahan summation algorithm
std::vector<SpikelistType> nest::correlation_detector::State_::incoming_
incoming spikes, sorted
std::vector<long_t> nest::correlation_detector::State_::n_events_
spike counters
The documentation for this struct was generated from the following files:
correlation_detector.h
correlation_detector.cpp