NEST: nest::Selector Struct Reference
nest::Selector Struct Reference
Contains rules for selecting nodes from a layer when connecting.
#include <selector.h>
Public Member Functions
Selector ()
The default constructor creates a Selector with no specific rules, so all nodes are selected.
Selector (const DictionaryDatum &d)
The dictionary used to initialize the Selector may contain parameters 'model', which is the name of a model to select by, and/or 'lid', which is the depth to select by (an integer >= 1).
bool select_model () const
bool select_depth () const
bool operator== (const Selector &other)
Test if two selectors are equal, i.e.
Public Attributes
long_t model
The model to select, or -1 if all models are allowed.
long_t depth
The depth to select, or -1 if all depths are allowed.
Detailed Description
Contains rules for selecting nodes from a layer when connecting.
Users may select by model or by depth.
Constructor & Destructor Documentation
nest::Selector::Selector () inline
The default constructor creates a Selector with no specific rules, so all nodes are selected.
nest::Selector::Selector (const DictionaryDatum & d)
The dictionary used to initialize the Selector may contain parameters 'model', which is the name of a model to select by, and/or 'lid', which is the depth to select by (an integer >= 1).
Parameters
d Dictionary containing parameters for the Selector.
References depth, Token::empty(), nest::Network::get_modeldict(), nest::names::lid, Dictionary::lookup(), model, nest::names::model, and nest::Node::network().
Member Function Documentation
bool nest::Selector::operator== (const Selector & other) inline
Test if two selectors are equal, i.e.
contain the same rules.
Returns
true if both selectors are equal.
References depth, and model.
bool nest::Selector::select_depth () const inline
Returns
true if this Selector selects by depth
References depth.
Referenced by nest::FreeLayer< D >::communicate_positions_(), nest::ConnectionCreator::convergent_connect_(), nest::GridLayer< D >::insert_global_positions_(), nest::FreeLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::masked_iterator::masked_iterator(), nest::ConnectionCreator::source_driven_connect_(), and nest::ConnectionCreator::target_driven_connect_().
bool nest::Selector::select_model () const inline
Returns
true if this Selector selects by model
References model.
Referenced by nest::FreeLayer< D >::communicate_positions_(), nest::ConnectionCreator::convergent_connect_(), nest::GridLayer< D >::insert_global_positions_(), nest::FreeLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::masked_iterator::masked_iterator(), nest::ConnectionCreator::source_driven_connect_(), and nest::ConnectionCreator::target_driven_connect_().
Member Data Documentation
long_t nest::Selector::depth
The depth to select, or -1 if all depths are allowed.
Referenced by nest::FreeLayer< D >::communicate_positions_(), nest::ConnectionCreator::convergent_connect_(), nest::GridLayer< D >::insert_global_positions_(), nest::FreeLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::masked_iterator::masked_iterator(), operator==(), select_depth(), Selector(), nest::ConnectionCreator::source_driven_connect_(), and nest::ConnectionCreator::target_driven_connect_().
long_t nest::Selector::model
The model to select, or -1 if all models are allowed.
Referenced by nest::FreeLayer< D >::communicate_positions_(), nest::ConnectionCreator::convergent_connect_(), nest::GridLayer< D >::insert_global_positions_(), nest::FreeLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::insert_local_positions_ntree_(), nest::GridLayer< D >::masked_iterator::masked_iterator(), operator==(), select_model(), Selector(), nest::ConnectionCreator::source_driven_connect_(), and nest::ConnectionCreator::target_driven_connect_().
The documentation for this struct was generated from the following files:
selector.h
selector.cpp