NEST: nest::RecordingDevice::State_ Struct Reference
nest::RecordingDevice::State_ Struct Reference
Public Member Functions
State_ ()
Sets default parameter values.
void clear_events ()
clear all data
void get (DictionaryDatum &, const Parameters_ &) const
Store current values in dictionary.
void set (const DictionaryDatum &)
Get values from dictionary.
Public Attributes
size_t events_
Event counter.
std::vector< long > event_senders_
List of event sender ids.
std::vector< double_t > event_times_ms_
List of event times in ms.
std::vector< long > event_times_steps_
List of event times in steps.
std::vector< double_t > event_times_offsets_
List of event time offsets.
std::vector< double_t > event_weights_
List of event weights.
Constructor & Destructor Documentation
nest::RecordingDevice::State_::State_ ()
Sets default parameter values.
Member Function Documentation
void nest::RecordingDevice::State_::clear_events ()
clear all data
Referenced by nest::RecordingDevice::set_status().
void nest::RecordingDevice::State_::get (DictionaryDatum & d, const Parameters_ & p) const
Store current values in dictionary.
References append_property(), assert(), nest::names::d, nest::names::events, getValue< long >(), initialize_property_doublevector(), initialize_property_intvector(), nest::names::n_events, nest::names::offsets, nest::RecordingDevice::Parameters_::precise_times_, provide_property(), nest::names::senders, nest::RecordingDevice::Parameters_::time_in_steps_, nest::names::times, nest::RecordingDevice::Parameters_::to_accumulator_, nest::names::weights, nest::RecordingDevice::Parameters_::withgid_, nest::RecordingDevice::Parameters_::withtime_, and nest::RecordingDevice::Parameters_::withweight_.
Referenced by nest::RecordingDevice::get_status().
void nest::RecordingDevice::State_::set (const DictionaryDatum & d)
Get values from dictionary.
References nest::names::n_events.
Referenced by nest::RecordingDevice::set_status().
Member Data Documentation
std::vector<long> nest::RecordingDevice::State_::event_senders_
List of event sender ids.
std::vector<double_t> nest::RecordingDevice::State_::event_times_ms_
List of event times in ms.
std::vector<double_t> nest::RecordingDevice::State_::event_times_offsets_
List of event time offsets.
std::vector<long> nest::RecordingDevice::State_::event_times_steps_
List of event times in steps.
std::vector<double_t> nest::RecordingDevice::State_::event_weights_
List of event weights.
size_t nest::RecordingDevice::State_::events_
Event counter.
Referenced by nest::RecordingDevice::set_status().
The documentation for this struct was generated from the following files:
recording_device.h
recording_device.cpp