NEST: nest::RecordingDevice::Parameters_ Struct Reference
nest::RecordingDevice::Parameters_ Struct Reference
Public Member Functions
Parameters_ (const std::string &, bool, bool, bool)
Set default parameter values.
void get (const RecordingDevice &, DictionaryDatum &) const
Store current values in dictionary.
void set (const RecordingDevice &, const Buffers_ &, const DictionaryDatum &)
Set values from dicitonary.
Public Attributes
bool to_file_
true if recorder writes its output to a file
bool to_screen_
true if recorder writes its output to stdout
bool to_memory_
true if data should be recorded in memory, default
bool to_accumulator_
true if data is to be accumulated; exclusive to all other to_*
bool time_in_steps_
true if time is printed in steps, not ms.
bool precise_times_
true if time is computed including offset
bool withgid_
true if element GID is to be printed, default
bool withtime_
true if time of event is to be printed, default
bool withweight_
true if weight of event is to be printed
long precision_
precision of doubles written to file
bool scientific_
use scientific format if true, else fixed
bool binary_
true if to write files in binary mode instead of ASCII
long fbuffer_size_
the buffer size to use when writing to file
long fbuffer_size_old_
the buffer size to use when writing to file (old)
std::string label_
a user-defined label for symbolic device names.
std::string file_ext_
the file name extension to use, without .
std::string filename_
the filename, if recording to a file (read-only)
bool close_after_simulate_
if true, finalize() shall close the stream
bool flush_after_simulate_
if true, finalize() shall flush the stream
bool flush_records_
if true, flush stream after each output
bool close_on_reset_
if true, close stream in init_buffers()
Constructor & Destructor Documentation
nest::RecordingDevice::Parameters_::Parameters_ (const std::string & file_ext, bool withtime, bool withgid, bool withweight)
Set default parameter values.
Parameters
Default file name extension, excluding ".".
Default value for withtime property
Default value for withgid property
Member Function Documentation
void nest::RecordingDevice::Parameters_::get (const RecordingDevice & rd, DictionaryDatum & d) const
Store current values in dictionary.
References nest::names::accumulator, ad, append_property(), nest::names::binary, nest::names::close_after_simulate, nest::names::close_on_reset, nest::names::fbuffer_size, nest::names::file, nest::names::file_extension, nest::names::filenames, nest::names::flush_after_simulate, nest::names::flush_records, initialize_property_array(), nest::names::label, nest::names::memory, nest::RecordingDevice::mode_, nest::RecordingDevice::MULTIMETER, nest::names::precise_times, nest::names::precision, TokenArray::push_back(), nest::names::record_to, nest::names::scientific, nest::names::screen, nest::RecordingDevice::SPIKE_DETECTOR, nest::names::time_in_steps, nest::names::to_accumulator, nest::names::to_file, nest::names::to_memory, nest::names::to_screen, nest::names::withgid, nest::names::withtime, and nest::names::withweight.
Referenced by nest::RecordingDevice::get_status().
void nest::RecordingDevice::Parameters_::set (const RecordingDevice & rd, const Buffers_ & , const DictionaryDatum & d)
Set values from dicitonary.
References nest::names::accumulator, ad, TokenArray::begin(), nest::names::binary, nest::names::close_after_simulate, nest::names::close_on_reset, nest::names::d, TokenArray::end(), nest::names::fbuffer_size, nest::names::file, nest::names::file_extension, nest::names::flush_after_simulate, nest::names::flush_records, nest::NestModule::get_network(), nest::names::label, SLIInterpreter::M_INFO, SLIInterpreter::M_WARNING, nest::names::memory, nest::Network::message(), nest::RecordingDevice::mode_, nest::RecordingDevice::MULTIMETER, nest::Node::network(), nest::names::precise_times, nest::names::precision, nest::names::record_to, nest::names::scientific, nest::names::screen, nest::RecordingDevice::SPIKE_DETECTOR, nest::names::time_in_steps, nest::names::to_accumulator, nest::names::to_file, nest::names::to_memory, nest::names::to_screen, nest::names::withgid, nest::names::withtime, and nest::names::withweight.
Referenced by nest::RecordingDevice::set_status().
Member Data Documentation
bool nest::RecordingDevice::Parameters_::binary_
true if to write files in binary mode instead of ASCII
bool nest::RecordingDevice::Parameters_::close_after_simulate_
if true, finalize() shall close the stream
bool nest::RecordingDevice::Parameters_::close_on_reset_
if true, close stream in init_buffers()
long nest::RecordingDevice::Parameters_::fbuffer_size_
the buffer size to use when writing to file
long nest::RecordingDevice::Parameters_::fbuffer_size_old_
the buffer size to use when writing to file (old)
std::string nest::RecordingDevice::Parameters_::file_ext_
the file name extension to use, without .
std::string nest::RecordingDevice::Parameters_::filename_
the filename, if recording to a file (read-only)
bool nest::RecordingDevice::Parameters_::flush_after_simulate_
if true, finalize() shall flush the stream
bool nest::RecordingDevice::Parameters_::flush_records_
if true, flush stream after each output
std::string nest::RecordingDevice::Parameters_::label_
a user-defined label for symbolic device names.
bool nest::RecordingDevice::Parameters_::precise_times_
true if time is computed including offset
Referenced by nest::RecordingDevice::State_::get(), and nest::RecordingDevice::set_precise().
long nest::RecordingDevice::Parameters_::precision_
precision of doubles written to file
Referenced by nest::RecordingDevice::set_precise().
bool nest::RecordingDevice::Parameters_::scientific_
use scientific format if true, else fixed
bool nest::RecordingDevice::Parameters_::time_in_steps_
true if time is printed in steps, not ms.
Referenced by nest::RecordingDevice::State_::get().
bool nest::RecordingDevice::Parameters_::to_accumulator_
true if data is to be accumulated; exclusive to all other to_*
Referenced by nest::RecordingDevice::State_::get(), and nest::RecordingDevice::to_accumulator().
bool nest::RecordingDevice::Parameters_::to_file_
true if recorder writes its output to a file
Referenced by nest::RecordingDevice::print_value(), and nest::RecordingDevice::to_file().
bool nest::RecordingDevice::Parameters_::to_memory_
true if data should be recorded in memory, default
Referenced by nest::RecordingDevice::to_memory().
bool nest::RecordingDevice::Parameters_::to_screen_
true if recorder writes its output to stdout
Referenced by nest::RecordingDevice::print_value(), and nest::RecordingDevice::to_screen().
bool nest::RecordingDevice::Parameters_::withgid_
true if element GID is to be printed, default
Referenced by nest::RecordingDevice::State_::get().
bool nest::RecordingDevice::Parameters_::withtime_
true if time of event is to be printed, default
Referenced by nest::RecordingDevice::State_::get().
bool nest::RecordingDevice::Parameters_::withweight_
true if weight of event is to be printed
Referenced by nest::RecordingDevice::State_::get().
The documentation for this struct was generated from the following files:
recording_device.h
recording_device.cpp