NEST: nest::hh_cond_exp_traub::State_ Struct Reference
nest::hh_cond_exp_traub::State_ Struct Reference
State variables of the model.
#include <hh_cond_exp_traub.h>
Public Types
enum StateVecElems {
V_M = 0, HH_M, HH_H, HH_N,
G_EXC, G_INH, STATE_VEC_SIZE
}
Symbolic indices to the elements of the state vector y.
Public Member Functions
State_ (const Parameters_ &p)
State_ (const State_ &s)
State_ & operator= (const State_ &s)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &)
Public Attributes
double y_ [STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
int_t r_
number of refractory steps remaining
Detailed Description
State variables of the model.
Member Enumeration Documentation
enum nest::hh_cond_exp_traub::State_::StateVecElems
Symbolic indices to the elements of the state vector y.
Enumerator
V_M
HH_M
HH_H
HH_N
G_EXC
G_INH
STATE_VEC_SIZE
Constructor & Destructor Documentation
nest::hh_cond_exp_traub::State_::State_ (const Parameters_ & p)
References nest::hh_cond_exp_traub::Parameters_::E_L, HH_H, HH_M, HH_N, STATE_VEC_SIZE, and y_.
nest::hh_cond_exp_traub::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::hh_cond_exp_traub::State_::get (DictionaryDatum & d) const
References nest::names::Act_h, nest::names::Act_m, nest::names::d, nest::names::Inact_n, and nest::names::V_m.
Referenced by nest::hh_cond_exp_traub::get_status().
nest::hh_cond_exp_traub::State_ & nest::hh_cond_exp_traub::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::hh_cond_exp_traub::State_::set (const DictionaryDatum & d, const Parameters_ &)
References nest::names::Act_h, nest::names::Act_m, nest::names::d, nest::names::Inact_n, and nest::names::V_m.
Referenced by nest::hh_cond_exp_traub::set_status().
Member Data Documentation
int_t nest::hh_cond_exp_traub::State_::r_
number of refractory steps remaining
Referenced by operator=().
double nest::hh_cond_exp_traub::State_::y_[STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
Referenced by nest::hh_cond_exp_traub::get_y_elem_(), operator=(), and State_().
The documentation for this struct was generated from the following files:
hh_cond_exp_traub.h
hh_cond_exp_traub.cpp