NEST: nest::iaf_psc_alpha_canon::State_ Struct Reference
nest::iaf_psc_alpha_canon::State_ Struct Reference
State variables of the model.
Public Member Functions
State_ ()
Default initialization.
void get (DictionaryDatum &, const Parameters_ &) const
void set (const DictionaryDatum &, const Parameters_ &, double)
Set values from dictionary.
Public Attributes
double_t y0_
external input current
double_t y1_
alpha current, first component
double_t y2_
alpha current, second component
double_t y3_
Membrane pot. rel. to resting pot. E_L_.
bool is_refractory_
true while refractory
long_t last_spike_step_
time stamp of most recent spike
double_t last_spike_offset_
offset of most recent spike
Detailed Description
State variables of the model.
Constructor & Destructor Documentation
nest::iaf_psc_alpha_canon::State_::State_ ()
Default initialization.
Member Function Documentation
void nest::iaf_psc_alpha_canon::State_::get (DictionaryDatum & d, const Parameters_ & p) const
References nest::names::d, nest::iaf_psc_alpha_canon::Parameters_::E_L_, nest::Time::get_ms(), nest::names::is_refractory, nest::names::offset, nest::names::t_spike, and nest::names::V_m.
Referenced by nest::iaf_psc_alpha_canon::get_status().
void nest::iaf_psc_alpha_canon::State_::set (const DictionaryDatum & d, const Parameters_ & p, double delta_EL)
Set values from dictionary.
Parameters
dictionary to take data from
current parameters
Change in reversal potential E_L specified by this dict
References nest::names::d, nest::iaf_psc_alpha_canon::Parameters_::E_L_, and nest::names::V_m.
Referenced by nest::iaf_psc_alpha_canon::set_status().
Member Data Documentation
bool nest::iaf_psc_alpha_canon::State_::is_refractory_
true while refractory
double_t nest::iaf_psc_alpha_canon::State_::last_spike_offset_
offset of most recent spike
long_t nest::iaf_psc_alpha_canon::State_::last_spike_step_
time stamp of most recent spike
double_t nest::iaf_psc_alpha_canon::State_::y0_
external input current
double_t nest::iaf_psc_alpha_canon::State_::y1_
alpha current, first component
Referenced by nest::iaf_psc_alpha_canon::get_y1_().
double_t nest::iaf_psc_alpha_canon::State_::y2_
alpha current, second component
Referenced by nest::iaf_psc_alpha_canon::get_y2_().
double_t nest::iaf_psc_alpha_canon::State_::y3_
Membrane pot. rel. to resting pot. E_L_.
Referenced by nest::iaf_psc_alpha_canon::get_V_m_().
The documentation for this struct was generated from the following files:
iaf_psc_alpha_canon.h
iaf_psc_alpha_canon.cpp