NEST: nest::iaf_cond_exp_sfa_rr::State_ Struct Reference
nest::iaf_cond_exp_sfa_rr::State_ Struct Reference
State variables of the model.
#include <iaf_cond_exp_sfa_rr.h>
Public Types
enum StateVecElems {
V_M = 0, G_EXC, G_INH, G_SFA,
G_RR, STATE_VEC_SIZE
}
Symbolic indices to the elements of the state vector y.
Public Member Functions
State_ (const Parameters_ &)
Default initialization.
State_ (const State_ &)
State_ & operator= (const State_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &)
Public Attributes
double_t y_ [STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
int_t r_
number of refractory steps remaining
Detailed Description
State variables of the model.
Note
Copy constructor and assignment operator required because of C-style array.
Member Enumeration Documentation
enum nest::iaf_cond_exp_sfa_rr::State_::StateVecElems
Symbolic indices to the elements of the state vector y.
Enumerator
V_M
G_EXC
G_INH
G_SFA
G_RR
STATE_VEC_SIZE
Constructor & Destructor Documentation
nest::iaf_cond_exp_sfa_rr::State_::State_ (const Parameters_ & p)
Default initialization.
References nest::iaf_cond_exp_sfa_rr::Parameters_::E_L, STATE_VEC_SIZE, V_M, and y_.
nest::iaf_cond_exp_sfa_rr::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::iaf_cond_exp_sfa_rr::State_::get (DictionaryDatum & d) const
References nest::names::d, nest::names::g_ex, nest::names::g_in, nest::names::g_rr, nest::names::g_sfa, and nest::names::V_m.
Referenced by nest::iaf_cond_exp_sfa_rr::get_status().
nest::iaf_cond_exp_sfa_rr::State_ & nest::iaf_cond_exp_sfa_rr::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::iaf_cond_exp_sfa_rr::State_::set (const DictionaryDatum & d, const Parameters_ &)
References nest::names::d, nest::names::g_ex, nest::names::g_in, nest::names::g_rr, nest::names::g_sfa, and nest::names::V_m.
Referenced by nest::iaf_cond_exp_sfa_rr::set_status().
Member Data Documentation
int_t nest::iaf_cond_exp_sfa_rr::State_::r_
number of refractory steps remaining
Referenced by operator=().
double_t nest::iaf_cond_exp_sfa_rr::State_::y_[STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
Referenced by nest::iaf_cond_exp_sfa_rr::get_y_elem_(), operator=(), and State_().
The documentation for this struct was generated from the following files:
iaf_cond_exp_sfa_rr.h
iaf_cond_exp_sfa_rr.cpp