NEST: nest::Time::ms Struct Reference
nest::Time::ms Struct Reference
#include <nest_time.h>
Public Member Functions
ms (double_t t)
ms (long_t t)
ms (const Token &t)
Static Public Member Functions
static double_t fromtoken (const Token &t)
Public Attributes
double_t t
Constructor & Destructor Documentation
nest::Time::ms::ms (double_t t) inline explicit
nest::Time::ms::ms (long_t t) inline explicit
nest::Time::ms::ms (const Token & t) inline explicit
Member Function Documentation
nest::double_t Time::ms::fromtoken (const Token & t) static
References Token::datum(), GenericDatum< D, slt >::get(), Datum::gettypename(), and Name::toString().
Member Data Documentation
double_t nest::Time::ms::t
The documentation for this struct was generated from the following files:
nest_time.h
nest_time.cpp