NEST: nest::noise_generator::Parameters_ Struct Reference
nest::noise_generator::Parameters_ Struct Reference
Store independent parameters of the model.
Public Member Functions
Parameters_ ()
Sets default parameter values.
Parameters_ (const Parameters_ &)
void get (DictionaryDatum &) const
Store current values in dictionary.
void set (const DictionaryDatum &, const noise_generator &)
Set values from dicitonary.
Public Attributes
double_t mean_
mean current, in pA
double_t std_
standard deviation of current, in pA
double_t std_mod_
standard deviation of current modulation, in pA
double_t freq_
Standard frequency in Hz.
double_t phi_deg_
Phase of sinusodial noise modulation (0-360 deg)
Time dt_
time interval between updates
size_t num_targets_
Number of targets.
Detailed Description
Store independent parameters of the model.
Constructor & Destructor Documentation
nest::noise_generator::Parameters_::Parameters_ ()
Sets default parameter values.
nest::noise_generator::Parameters_::Parameters_ (const Parameters_ & p)
References nest::Time::calibrate(), and dt_.
Member Function Documentation
void nest::noise_generator::Parameters_::get (DictionaryDatum & d) const
Store current values in dictionary.
References nest::names::dt, nest::names::frequency, nest::names::mean, nest::names::phase, nest::names::std, and nest::names::std_mod.
Referenced by nest::noise_generator::get_status().
void nest::noise_generator::Parameters_::set (const DictionaryDatum & d, const noise_generator & n)
Set values from dicitonary.
References nest::names::d, nest::names::dt, nest::names::frequency, nest::Node::get_name(), nest::names::mean, nest::names::phase, nest::names::std, and nest::names::std_mod.
Referenced by nest::noise_generator::set_status().
Member Data Documentation
Time nest::noise_generator::Parameters_::dt_
time interval between updates
Referenced by nest::noise_generator::noise_generator(), and Parameters_().
double_t nest::noise_generator::Parameters_::freq_
Standard frequency in Hz.
double_t nest::noise_generator::Parameters_::mean_
mean current, in pA
size_t nest::noise_generator::Parameters_::num_targets_
Number of targets.
This is a hidden parameter; must be placed in parameters, even though it is an implementation detail, since it concerns the connections and must not be affected by resets.
Referenced by nest::noise_generator::set_status().
double_t nest::noise_generator::Parameters_::phi_deg_
Phase of sinusodial noise modulation (0-360 deg)
double_t nest::noise_generator::Parameters_::std_
standard deviation of current, in pA
double_t nest::noise_generator::Parameters_::std_mod_
standard deviation of current modulation, in pA
The documentation for this struct was generated from the following files:
noise_generator.h
noise_generator.cpp