NEST: nest::SynIdDelay Struct Reference
nest::SynIdDelay Struct Reference
#include <syn_id_delay.h>
Public Member Functions
SynIdDelay (double_t d)
SynIdDelay (const SynIdDelay &s)
double_t get_delay_ms () const
Return the delay of the connection in ms.
void set_delay_ms (const double_t d)
Set the delay of the connection specified in ms.
Public Attributes
unsigned syn_id: 8
unsigned delay: 24
Constructor & Destructor Documentation
nest::SynIdDelay::SynIdDelay (double_t d) inline
References set_delay_ms().
nest::SynIdDelay::SynIdDelay (const SynIdDelay & s) inline
Member Function Documentation
double_t nest::SynIdDelay::get_delay_ms () const inline
Return the delay of the connection in ms.
References nest::Time::delay_steps_to_ms().
Referenced by nest::Connection< targetidentifierT >::get_delay().
void nest::SynIdDelay::set_delay_ms (const double_t d) inline
Set the delay of the connection specified in ms.
References nest::Time::delay_ms_to_steps().
Referenced by nest::Connection< targetidentifierT >::set_delay(), and SynIdDelay().
Member Data Documentation
unsigned nest::SynIdDelay::delay
Referenced by nest::Connection< targetidentifierT >::get_delay_steps(), and nest::Connection< targetidentifierT >::set_delay_steps().
unsigned nest::SynIdDelay::syn_id
Referenced by nest::Connection< targetidentifierT >::get_syn_id(), and nest::Connection< targetidentifierT >::set_syn_id().
The documentation for this struct was generated from the following file:
syn_id_delay.h