NEST: nest::pulsepacket_generator::Parameters_ Struct Reference
nest::pulsepacket_generator::Parameters_ Struct Reference
Public Member Functions
Parameters_ ()
Sets default parameter values.
void get (DictionaryDatum &) const
Store current values in dictionary.
void set (const DictionaryDatum &, pulsepacket_generator &)
Set values from dicitonary.
Public Attributes
std::vector< double_t > pulse_times_
times of pulses
long_t a_
number of pulses in a packet
double_t sdev_
standard deviation of the packet
double_t sdev_tolerance_
Constructor & Destructor Documentation
nest::pulsepacket_generator::Parameters_::Parameters_ ()
Sets default parameter values.
Member Function Documentation
void nest::pulsepacket_generator::Parameters_::get (DictionaryDatum & d) const
Store current values in dictionary.
Referenced by nest::pulsepacket_generator::get_status().
void nest::pulsepacket_generator::Parameters_::set (const DictionaryDatum & d, pulsepacket_generator & ppg)
Set values from dicitonary.
Note
Buffer is passed so that the position etc can be reset parameters have been changed.
References nest::pulsepacket_generator::B_, nest::names::d, nest::pulsepacket_generator::Buffers_::spiketimes_, and updateValue().
Referenced by nest::pulsepacket_generator::set_status().
Member Data Documentation
long_t nest::pulsepacket_generator::Parameters_::a_
number of pulses in a packet
std::vector<double_t> nest::pulsepacket_generator::Parameters_::pulse_times_
times of pulses
double_t nest::pulsepacket_generator::Parameters_::sdev_
standard deviation of the packet
double_t nest::pulsepacket_generator::Parameters_::sdev_tolerance_
The documentation for this struct was generated from the following files:
pulsepacket_generator.h
pulsepacket_generator.cpp