NEST: nest::aeif_cond_alpha::State_ Struct Reference
nest::aeif_cond_alpha::State_ Struct Reference
State variables of the model.
#include <aeif_cond_alpha.h>
Public Types
enum StateVecElems {
V_M = 0, DG_EXC, G_EXC, DG_INH,
G_INH, W, STATE_VEC_SIZE
}
Enumeration identifying elements in state array State_::y_.
Public Member Functions
State_ (const Parameters_ &)
Default initialization.
State_ (const State_ &)
State_ & operator= (const State_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &)
Public Attributes
double_t y_ [STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
int_t r_
number of refractory steps remaining
Detailed Description
State variables of the model.
Note
Copy constructor and assignment operator required because of C-style array.
Member Enumeration Documentation
enum nest::aeif_cond_alpha::State_::StateVecElems
Enumeration identifying elements in state array State_::y_.
The state vector must be passed to GSL as a C array. This enum identifies the elements of the vector. It must be public to be accessible from the iteration function.
Enumerator
V_M
DG_EXC
G_EXC
DG_INH
G_INH
W
STATE_VEC_SIZE
Constructor & Destructor Documentation
nest::aeif_cond_alpha::State_::State_ (const Parameters_ & p)
Default initialization.
References nest::aeif_cond_alpha::Parameters_::E_L, STATE_VEC_SIZE, and y_.
nest::aeif_cond_alpha::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::aeif_cond_alpha::State_::get (DictionaryDatum & d) const
References nest::names::d, nest::names::dg_ex, nest::names::dg_in, nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
Referenced by nest::aeif_cond_alpha::get_status().
nest::aeif_cond_alpha::State_ & nest::aeif_cond_alpha::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::aeif_cond_alpha::State_::set (const DictionaryDatum & d, const Parameters_ &)
References nest::names::d, nest::names::dg_ex, nest::names::dg_in, nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
Referenced by nest::aeif_cond_alpha::set_status().
Member Data Documentation
int_t nest::aeif_cond_alpha::State_::r_
number of refractory steps remaining
Referenced by operator=().
double_t nest::aeif_cond_alpha::State_::y_[STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
Referenced by nest::aeif_cond_alpha::get_y_elem_(), operator=(), and State_().
The documentation for this struct was generated from the following files:
aeif_cond_alpha.h
aeif_cond_alpha.cpp