NEST: nest::Device::Parameters_ Struct Reference
nest::Device::Parameters_ Struct Reference
Independent parameters of the model.
Public Member Functions
Parameters_ ()
Sets default parameter values.
Parameters_ (const Parameters_ &)
Copy and recalibrate parameter set.
void get (DictionaryDatum &) const
Store current values in dictionary.
void set (const DictionaryDatum &)
Set values from dictionary.
Public Attributes
Time origin_
Origin of device time axis, relative to network time. Defaults to 0.
Time start_
Stop time, relative to origin. Defaults to "infinity".
Time stop_
Detailed Description
Independent parameters of the model.
Constructor & Destructor Documentation
nest::Device::Parameters_::Parameters_ ()
Sets default parameter values.
nest::Device::Parameters_::Parameters_ (const Parameters_ & p)
Copy and recalibrate parameter set.
References nest::Time::calibrate(), origin_, start_, and stop_.
Member Function Documentation
void nest::Device::Parameters_::get (DictionaryDatum & d) const
Store current values in dictionary.
References nest::names::origin, nest::names::start, and nest::names::stop.
Referenced by nest::Device::get_status().
void nest::Device::Parameters_::set (const DictionaryDatum & d)
Set values from dictionary.
References nest::Time::ms, nest::names::origin, nest::names::start, and nest::names::stop.
Referenced by nest::Device::set_status().
Member Data Documentation
Time nest::Device::Parameters_::origin_
Origin of device time axis, relative to network time. Defaults to 0.
Start time, relative to origin. Defaults to 0.
Referenced by Parameters_().
Time nest::Device::Parameters_::start_
Stop time, relative to origin. Defaults to "infinity".
Referenced by Parameters_().
Time nest::Device::Parameters_::stop_
Referenced by Parameters_().
The documentation for this struct was generated from the following files:
device.h
device.cpp