NEST: nest::Multimeter::Parameters_ Struct Reference
nest::Multimeter::Parameters_ Struct Reference
Public Member Functions
Parameters_ ()
Parameters_ (const Parameters_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Buffers_ &)
Public Attributes
Time interval_
recording interval, in ms
std::vector< Name > record_from_
which data to record
Constructor & Destructor Documentation
nest::Multimeter::Parameters_::Parameters_ ()
nest::Multimeter::Parameters_::Parameters_ (const Parameters_ & p)
References nest::Time::calibrate(), and interval_.
Member Function Documentation
void nest::Multimeter::Parameters_::get (DictionaryDatum & d) const
References ad, nest::names::interval, TokenArray::push_back(), and nest::names::record_from.
void nest::Multimeter::Parameters_::set (const DictionaryDatum & d, const Buffers_ & b)
References ad, TokenArray::begin(), nest::names::d, TokenArray::end(), nest::Time::get_resolution(), nest::Multimeter::Buffers_::has_targets_, nest::names::interval, TokenArray::push_back(), nest::names::record_from, and nest::Time::step.
Referenced by nest::Multimeter::set_status().
Member Data Documentation
Time nest::Multimeter::Parameters_::interval_
recording interval, in ms
Referenced by Parameters_(), and nest::Multimeter::send_test_event().
std::vector<Name> nest::Multimeter::Parameters_::record_from_
which data to record
Referenced by nest::Multimeter::add_data_(), nest::Multimeter::send_test_event(), and nest::Multimeter::update().
The documentation for this struct was generated from the following files:
multimeter.h
multimeter.cpp