NEST: nest::iaf_cond_exp::State_ Struct Reference
nest::iaf_cond_exp::State_ Struct Reference
State variables of the model.
#include <iaf_cond_exp.h>
Public Types
enum StateVecElems { V_M = 0, G_EXC, G_INH, STATE_VEC_SIZE }
Symbolic indices to the elements of the state vector y.
Public Member Functions
State_ (const Parameters_ &)
Default initialization.
State_ (const State_ &)
State_ & operator= (const State_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &)
Public Attributes
double_t y_ [STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
int_t r_
number of refractory steps remaining
Detailed Description
State variables of the model.
Note
Copy constructor and assignment operator required because of C-style array.
Member Enumeration Documentation
enum nest::iaf_cond_exp::State_::StateVecElems
Symbolic indices to the elements of the state vector y.
Enumerator
V_M
G_EXC
G_INH
STATE_VEC_SIZE
Constructor & Destructor Documentation
nest::iaf_cond_exp::State_::State_ (const Parameters_ & p)
Default initialization.
References nest::iaf_cond_exp::Parameters_::E_L, G_EXC, G_INH, V_M, and y_.
nest::iaf_cond_exp::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::iaf_cond_exp::State_::get (DictionaryDatum & d) const
References nest::names::d, and nest::names::V_m.
Referenced by nest::iaf_cond_exp::get_status().
nest::iaf_cond_exp::State_ & nest::iaf_cond_exp::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::iaf_cond_exp::State_::set (const DictionaryDatum & d, const Parameters_ &)
References nest::names::d, and nest::names::V_m.
Referenced by nest::iaf_cond_exp::set_status().
Member Data Documentation
int_t nest::iaf_cond_exp::State_::r_
number of refractory steps remaining
Referenced by operator=().
double_t nest::iaf_cond_exp::State_::y_[STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
Referenced by nest::iaf_cond_exp::get_y_elem_(), operator=(), and State_().
The documentation for this struct was generated from the following files:
iaf_cond_exp.h
iaf_cond_exp.cpp