NEST: nest::iaf_cond_alpha_mc::State_ Struct Reference
nest::iaf_cond_alpha_mc::State_ Struct Reference
State variables of the model.
#include <iaf_cond_alpha_mc.h>
Public Types
enum StateVecElems_ {
V_M = 0, DG_EXC, G_EXC, DG_INH,
G_INH, STATE_VEC_COMPS
}
Elements of state vector.
Public Member Functions
State_ (const Parameters_ &)
Default initialization.
State_ (const State_ &)
State_ & operator= (const State_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &)
Static Public Member Functions
static size_t idx (size_t comp, StateVecElems_ elem)
Compute linear index into state array from compartment and element.
Public Attributes
double_t y_ [STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
int_t r_
number of refractory steps remaining
Static Public Attributes
static const size_t STATE_VEC_SIZE = STATE_VEC_COMPS * NCOMP
total size of state vector
Detailed Description
State variables of the model.
Note
Copy constructor and assignment operator required because of C-style array.
Member Enumeration Documentation
enum nest::iaf_cond_alpha_mc::State_::StateVecElems_
Elements of state vector.
For the multicompartmental case here, these are offset values. The state variables are stored in contiguous blocks for each compartment, beginning with the soma.
Enumerator
V_M
DG_EXC
G_EXC
DG_INH
G_INH
STATE_VEC_COMPS
Constructor & Destructor Documentation
nest::iaf_cond_alpha_mc::State_::State_ (const Parameters_ & p)
Default initialization.
References nest::iaf_cond_alpha_mc::Parameters_::E_L, idx(), nest::names::n, nest::iaf_cond_alpha_mc::NCOMP, STATE_VEC_SIZE, V_M, and y_.
nest::iaf_cond_alpha_mc::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::iaf_cond_alpha_mc::State_::get (DictionaryDatum & d) const
References assert(), nest::iaf_cond_alpha_mc::comp_names_, nest::names::d, nest::names::n, nest::iaf_cond_alpha_mc::NCOMP, and nest::names::V_m.
Referenced by nest::iaf_cond_alpha_mc::get_status().
static size_t nest::iaf_cond_alpha_mc::State_::idx (size_t comp, StateVecElems_ elem) inline static
Compute linear index into state array from compartment and element.
Parameters
comp compartment index
elem elemet index
Note
compartment argument is not of type Compartments_, since looping over enumerations does not work.
References STATE_VEC_COMPS.
Referenced by nest::iaf_cond_alpha_mc::get_y_elem_(), and State_().
nest::iaf_cond_alpha_mc::State_ & nest::iaf_cond_alpha_mc::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::iaf_cond_alpha_mc::State_::set (const DictionaryDatum & d, const Parameters_ &)
References nest::iaf_cond_alpha_mc::comp_names_, nest::names::d, nest::names::n, nest::iaf_cond_alpha_mc::NCOMP, and nest::names::V_m.
Referenced by nest::iaf_cond_alpha_mc::set_status().
Member Data Documentation
int_t nest::iaf_cond_alpha_mc::State_::r_
number of refractory steps remaining
Referenced by nest::iaf_cond_alpha_mc::get_r_(), and operator=().
const size_t nest::iaf_cond_alpha_mc::State_::STATE_VEC_SIZE = STATE_VEC_COMPS * NCOMP static
total size of state vector
Referenced by State_().
double_t nest::iaf_cond_alpha_mc::State_::y_[STATE_VEC_SIZE]
neuron state, must be C-array for GSL solver
Referenced by nest::iaf_cond_alpha_mc::get_y_elem_(), operator=(), and State_().
The documentation for this struct was generated from the following files:
iaf_cond_alpha_mc.h
iaf_cond_alpha_mc.cpp