NEST: nest::aeif_cond_alpha_RK5::State_ Struct Reference
nest::aeif_cond_alpha_RK5::State_ Struct Reference
State variables of the model.
#include <aeif_cond_alpha_RK5.h>
Public Types
enum StateVecElems {
V_M = 0, DG_EXC, G_EXC, DG_INH,
G_INH, W, STATE_VEC_SIZE
}
Enumeration identifying elements in state array State_::y_.
Public Member Functions
State_ (const Parameters_ &)
Default initialization.
State_ (const State_ &)
State_ & operator= (const State_ &)
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &)
Public Attributes
double_t y_ [STATE_VEC_SIZE]
neuron state
double_t k1 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t k2 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t k3 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t k4 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t k5 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t k6 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t k7 [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t yin [STATE_VEC_SIZE]
Runge-Kutta variable.
double_t ynew [STATE_VEC_SIZE]
5th order update
double_t yref [STATE_VEC_SIZE]
4th order update
int_t r_
number of refractory steps remaining
Detailed Description
State variables of the model.
Note
Copy constructor and assignment operator required because of C-style array.
Member Enumeration Documentation
enum nest::aeif_cond_alpha_RK5::State_::StateVecElems
Enumeration identifying elements in state array State_::y_.
The state vector is passed as a C array. This enum identifies the elements of the vector. It must be public to be accessible from the iteration function.
Enumerator
V_M
DG_EXC
G_EXC
DG_INH
G_INH
W
STATE_VEC_SIZE
Constructor & Destructor Documentation
nest::aeif_cond_alpha_RK5::State_::State_ (const Parameters_ & p)
Default initialization.
References nest::aeif_cond_alpha_RK5::Parameters_::E_L, STATE_VEC_SIZE, and y_.
nest::aeif_cond_alpha_RK5::State_::State_ (const State_ & s)
References STATE_VEC_SIZE, and y_.
Member Function Documentation
void nest::aeif_cond_alpha_RK5::State_::get (DictionaryDatum & d) const
References nest::names::d, nest::names::dg_ex, nest::names::dg_in, nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
Referenced by nest::aeif_cond_alpha_RK5::get_status().
nest::aeif_cond_alpha_RK5::State_ & nest::aeif_cond_alpha_RK5::State_::operator= (const State_ & s)
References assert(), r_, and y_.
void nest::aeif_cond_alpha_RK5::State_::set (const DictionaryDatum & d, const Parameters_ &)
References nest::names::d, nest::names::dg_ex, nest::names::dg_in, nest::names::g_ex, nest::names::g_in, nest::names::V_m, and nest::names::w.
Referenced by nest::aeif_cond_alpha_RK5::set_status().
Member Data Documentation
double_t nest::aeif_cond_alpha_RK5::State_::k1[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::k2[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::k3[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::k4[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::k5[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::k6[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::k7[STATE_VEC_SIZE]
Runge-Kutta variable.
int_t nest::aeif_cond_alpha_RK5::State_::r_
number of refractory steps remaining
Referenced by operator=().
double_t nest::aeif_cond_alpha_RK5::State_::y_[STATE_VEC_SIZE]
neuron state
Referenced by nest::aeif_cond_alpha_RK5::get_y_elem_(), operator=(), and State_().
double_t nest::aeif_cond_alpha_RK5::State_::yin[STATE_VEC_SIZE]
Runge-Kutta variable.
double_t nest::aeif_cond_alpha_RK5::State_::ynew[STATE_VEC_SIZE]
5th order update
double_t nest::aeif_cond_alpha_RK5::State_::yref[STATE_VEC_SIZE]
4th order update
The documentation for this struct was generated from the following files:
aeif_cond_alpha_RK5.h
aeif_cond_alpha_RK5.cpp