NEST: nest::correlomatrix_detector::State_ Struct Reference
nest::correlomatrix_detector::State_ Struct Reference
Public Member Functions
State_ ()
initialize default state
void get (DictionaryDatum &) const
void set (const DictionaryDatum &, const Parameters_ &, bool)
void reset (const Parameters_ &)
Public Attributes
std::vector< long_t > n_events_
spike counters
SpikelistType incoming_
incoming spikes, sorted
std::vector< std::vector
< std::vector< double_t > > > covariance_
Weighted covariance matrix.
std::vector< std::vector
< std::vector< long_t > > > count_covariance_
Unweighted covariance matrix.
Detailed Description
Todo:
Is there a replacement for std::list that allows fast insertion inside, fast deletion at the beginning, and maintains sorting?
Note
Constructed with empty structures, which are set to proper sizes by init_buffers_().
State_ only contains read-out values, so we copy-construct using the default c'tor.
Constructor & Destructor Documentation
nest::correlomatrix_detector::State_::State_ ()
initialize default state
Member Function Documentation
void nest::correlomatrix_detector::State_::get (DictionaryDatum & d) const
References nest::names::count_covariance, nest::names::covariance, nest::names::n_events, and TokenArray::push_back().
void nest::correlomatrix_detector::State_::reset (const Parameters_ & p)
References assert(), nest::correlomatrix_detector::Parameters_::delta_tau_, nest::Time::get_steps(), nest::Time::is_multiple_of(), nest::correlomatrix_detector::Parameters_::N_channels_, and nest::correlomatrix_detector::Parameters_::tau_max_.
void nest::correlomatrix_detector::State_::set (const DictionaryDatum & , const Parameters_ & , bool)
Parameters
bool if true, force state reset
Member Data Documentation
std::vector<std::vector<std::vector<long_t> > > nest::correlomatrix_detector::State_::count_covariance_
Unweighted covariance matrix.
std::vector<std::vector<std::vector<double_t> > > nest::correlomatrix_detector::State_::covariance_
Weighted covariance matrix.
Note
Data type is double to accomodate weights.
SpikelistType nest::correlomatrix_detector::State_::incoming_
incoming spikes, sorted
std::vector<long_t> nest::correlomatrix_detector::State_::n_events_
spike counters
The documentation for this struct was generated from the following files:
correlomatrix_detector.h
correlomatrix_detector.cpp