NEST: nest::iaf_psc_exp_ps::State_ Struct Reference
nest::iaf_psc_exp_ps::State_ Struct Reference
State variables of the model.
Public Member Functions
State_ ()
Default initialization.
void get (DictionaryDatum &, const Parameters_ &) const
void set (const DictionaryDatum &, const Parameters_ &, double)
Set values from dictionary.
Public Attributes
double_t y0_
External input current.
double_t y1_ex_
Exc. exponetial current.
double_t y1_in_
Inh. exponetial current.
double_t y2_
Membrane potential (relative to resting potential)
bool is_refractory_
True while refractory.
long_t last_spike_step_
Time stamp of most recent spike.
double_t last_spike_offset_
Offset of most recent spike.
Detailed Description
State variables of the model.
Constructor & Destructor Documentation
nest::iaf_psc_exp_ps::State_::State_ ()
Default initialization.
Member Function Documentation
void nest::iaf_psc_exp_ps::State_::get (DictionaryDatum & d, const Parameters_ & p) const
References nest::names::d, nest::iaf_psc_exp_ps::Parameters_::E_L_, nest::Time::get_ms(), nest::names::is_refractory, nest::names::offset, nest::names::t_spike, and nest::names::V_m.
Referenced by nest::iaf_psc_exp_ps::get_status().
void nest::iaf_psc_exp_ps::State_::set (const DictionaryDatum & d, const Parameters_ & p, double delta_EL)
Set values from dictionary.
Parameters
dictionary to take data from
current parameters
Change in reversal potential E_L specified by this dict
References nest::iaf_psc_exp_ps::Parameters_::E_L_, and nest::names::V_m.
Referenced by nest::iaf_psc_exp_ps::set_status().
Member Data Documentation
bool nest::iaf_psc_exp_ps::State_::is_refractory_
True while refractory.
double_t nest::iaf_psc_exp_ps::State_::last_spike_offset_
Offset of most recent spike.
long_t nest::iaf_psc_exp_ps::State_::last_spike_step_
Time stamp of most recent spike.
double_t nest::iaf_psc_exp_ps::State_::y0_
External input current.
double_t nest::iaf_psc_exp_ps::State_::y1_ex_
Exc. exponetial current.
double_t nest::iaf_psc_exp_ps::State_::y1_in_
Inh. exponetial current.
double_t nest::iaf_psc_exp_ps::State_::y2_
Membrane potential (relative to resting potential)
Referenced by nest::iaf_psc_exp_ps::get_V_m_().
The documentation for this struct was generated from the following files:
iaf_psc_exp_ps.h
iaf_psc_exp_ps.cpp