NEST: tokenutils.cc File Reference
tokenutils.cc File Reference
Functions
template<>
long getValue< long > (const Token &t)
template<>
void setValue< long > (const Token &t, long const &value)
template<>
Token newToken< long > (long const &value)
template<>
double getValue< double > (const Token &t)
template<>
void setValue< double > (const Token &t, double const &value)
template<>
float getValue< float > (const Token &t)
template<>
void setValue< float > (const Token &t, float const &value)
template<>
Token newToken< double > (double const &value)
template<>
bool getValue< bool > (const Token &t)
template<>
void setValue< bool > (const Token &t, bool const &value)
template<>
Token newToken< bool > (bool const &value)
template<>
std::string getValue< std::string > (const Token &t)
template<>
void setValue< std::string > (const Token &t, std::string const &value)
template<>
Token newToken< std::string > (std::string const &value)
template<>
std::vector< double > getValue< std::vector< double > > (const Token &t)
template<>
void setValue< std::vector< double > > (const Token &t, std::vector< double > const &value)
template<>
Token newToken< std::vector< double > > (std::vector< double > const &value)
template<>
std::vector< long > getValue< std::vector< long > > (const Token &t)
template<>
void setValue< std::vector< long > > (const Token &t, std::vector< long > const &value)
template<>
Token newToken< std::vector< long > > (std::vector< long > const &value)
template<>
std::valarray< double > getValue< std::valarray< double > > (const Token &t)
template<>
void setValue< std::valarray< double > > (const Token &t, std::valarray< double > const &value)
template<>
Token newToken< std::valarray< double > > (std::valarray< double > const &value)
template<>
std::valarray< long > getValue< std::valarray< long > > (const Token &t)
template<>
void setValue< std::valarray< long > > (const Token &t, std::valarray< long > const &value)
template<>
Token newToken< std::valarray< long > > (std::valarray< long > const &value)
Function Documentation
template<> bool getValue< bool > (const Token & t)
References nest::names::d, Datum::gettypename(), and Name::toString().
Referenced by nest::ConnectionCreator::ConnectionCreator(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_ia_ia_daa_daa_b_b_lFunction::execute(), nest::NestModule::TimeCommunication_i_i_bFunction::execute(), Token::operator bool(), nest::Network::quit_by_error(), and nest::Layer< D >::set_status().
template<> double getValue< double > (const Token & t)
References nest::names::d, Datum::gettypename(), and Name::toString().
Referenced by SLIArrayModule::GaborFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), nest::NestModule::SetAcceptableLatencyFunction::execute(), SLIArrayModule::FiniteQ_dFunction::execute(), nest::sli_neuron::get_V_m_(), and Token::operator double().
template<> float getValue< float > (const Token & t)
References nest::names::d, Datum::gettypename(), and Name::toString().
Referenced by Token::operator float().
template<> long getValue< long > (const Token & t)
References nest::names::d, Datum::gettypename(), and Name::toString().
Referenced by nest::Network::convergent_connect(), nest::TopologyModule::create_mask(), nest::Network::divergent_connect(), nest::ConnectionGeneratorModule::CGConnect_cg_i_i_D_lFunction::execute(), RandomNumbers::CreateRNGFunction::execute(), RandomNumbers::IrandFunction::execute(), RandomNumbers::SeedFunction::execute(), SLIArrayModule::RotateFunction::execute(), RandomNumbers::RandomArrayFunction::execute(), nest::NestModule::ChangeSubnet_iFunction::execute(), nest::NestModule::GetNodes_i_D_b_bFunction::execute(), nest::NestModule::GetLeaves_i_D_bFunction::execute(), nest::NestModule::GetChildren_i_D_bFunction::execute(), nest::NestModule::GetStatus_iFunction::execute(), nest::NestModule::SetStatus_idFunction::execute(), nest::NestModule::SetStatus_CDFunction::execute(), nest::NestModule::Create_l_iFunction::execute(), SLIArrayModule::GaborFunction::execute(), nest::NestModule::DataConnect_i_D_sFunction::execute(), SLIArrayModule::Gauss2dFunction::execute(), nest::NestModule::Connect_i_i_lFunction::execute(), nest::NestModule::Connect_i_i_d_d_lFunction::execute(), nest::NestModule::Connect_i_i_D_lFunction::execute(), nest::NestModule::DivergentConnect_i_ia_a_a_lFunction::execute(), nest::NestModule::RDivergentConnect_i_i_ia_da_da_b_b_lFunction::execute(), nest::NestModule::ConvergentConnect_ia_i_a_a_lFunction::execute(), nest::NestModule::RConvergentConnect_ia_i_i_da_da_b_b_lFunction::execute(), RangeIterator_aFunction::execute(), nest::NestModule::PrintNetworkFunction::execute(), nest::NestModule::SetFakeNumProcessesFunction_i::execute(), nest::NestModule::SetNumRecProcessesFunction_i::execute(), nest::NestModule::TimeCommunication_i_i_bFunction::execute(), nest::NestModule::TimeCommunicationv_i_iFunction::execute(), nest::NestModule::TimeCommunicationAlltoall_i_iFunction::execute(), nest::NestModule::TimeCommunicationAlltoallv_i_iFunction::execute(), nest::NestModule::MPIAbort_iFunction::execute(), nest::NestModule::GetVpRngFunction::execute(), nest::NestModule::SetMaxBufferedFunction::execute(), SLIInterpreter::execute_(), SLIInterpreter::execute_debug_(), nest::RecordingDevice::State_::get(), nest::Network::get_exitcode(), nest::GridMask< D >::GridMask(), Token::operator long(), Token::operator size_t(), nest::Scheduler::prepare_nodes(), nest::Network::random_convergent_connect(), and SLIInterpreter::terminate().
template<> std::string getValue< std::string > (const Token & t)
References Datum::gettypename(), nest::names::n, and Name::toString().
template<> std::valarray<double> getValue< std::valarray< double > > (const Token & t)
template<> std::valarray<long> getValue< std::valarray< long > > (const Token & t)
template<> std::vector<double> getValue< std::vector< double > > (const Token & t)
References ad, Datum::gettypename(), Name::toString(), and TokenArray::toVector().
template<> std::vector<long> getValue< std::vector< long > > (const Token & t)
References ad, Datum::gettypename(), Name::toString(), and TokenArray::toVector().
template<> Token newToken< bool > (bool const & value)
template<> Token newToken< double > (double const & value)
template<> Token newToken< long > (long const & value)
template<> Token newToken< std::string > (std::string const & value)
template<> Token newToken< std::valarray< double > > (std::valarray< double > const & value)
template<> Token newToken< std::valarray< long > > (std::valarray< long > const & value)
template<> Token newToken< std::vector< double > > (std::vector< double > const & value)
template<> Token newToken< std::vector< long > > (std::vector< long > const & value)
template<> void setValue< bool > (const Token & t, bool const & value)
References nest::names::d, Datum::gettypename(), and Name::toString().
template<> void setValue< double > (const Token & t, double const & value)
References nest::names::d, Datum::gettypename(), and Name::toString().
Referenced by setValue< std::valarray< double > >(), and setValue< std::vector< double > >().
template<> void setValue< float > (const Token & t, float const & value)
References nest::names::d, Datum::gettypename(), and Name::toString().
template<> void setValue< long > (const Token & t, long const & value)
References nest::names::d, Datum::gettypename(), and Name::toString().
Referenced by setValue< std::valarray< long > >(), and setValue< std::vector< long > >().
template<> void setValue< std::string > (const Token & t, std::string const & value)
References nest::names::b, Datum::gettypename(), nest::names::n, and Name::toString().
template<> void setValue< std::valarray< double > > (const Token & t, std::valarray< double > const & value)
References ad, nest::names::d, Datum::gettypename(), setValue< double >(), TokenArray::size(), and Name::toString().
template<> void setValue< std::valarray< long > > (const Token & t, std::valarray< long > const & value)
References ad, nest::names::d, Datum::gettypename(), setValue< long >(), TokenArray::size(), and Name::toString().
template<> void setValue< std::vector< double > > (const Token & t, std::vector< double > const & value)
References ad, nest::names::d, Datum::gettypename(), setValue< double >(), TokenArray::size(), and Name::toString().
template<> void setValue< std::vector< long > > (const Token & t, std::vector< long > const & value)
References ad, nest::names::d, Datum::gettypename(), setValue< long >(), TokenArray::size(), and Name::toString().